### ISSUE TITLE
Gambling in same game as "gold finders"

### ISSUE THREAD

**Issue by IAmRelaxed** [kolton/d2bot-with-kolbot#101]
Hi friends,

In my current setup, I have 7 characters using "Team MF" to complete long multi-act runs that take 10-15 minutes per game. I have an 8th character that I would like to use the gamble feature in the same game as the 7 runners, but I'm having a hard time making that happen.

With the default Gamble.js, when my gold finder enters the same game as the gambler (to begin the mf run) he will drop his gold and then leave the game, thinking that he is going to go back to finding gold in a separate game. After playing around with the Gamble.js functions, I've gotten my "MF Leader" (and also the gold finder) to drop the gold without leaving the game, but I can't get him to then start running the boss/area scripts. I'm thinking that this shouldn't be too bad of a fix since it looks like there's already a "current gold" check upon entering the game. I think I just need to find a way to reactivate the boss/area scripts following that check. Any ideas or code snippet to help fix this problem?

Any input is appreciated, many thanks!

-Relax

**Comment by WiZzMaN47** [comment]
you just have to have Script.Gamble = true; at the top of your char file or before your scripts you have true.. order from top to bottom
