### ISSUE TITLE
Perfect or Close to Perf Unique item Pickit File

### ISSUE THREAD

**Issue by olsoner1** [kolton/d2bot-with-kolbot#1025]
I have been working on making this but I keep on messing up or find a old pickit file that does not work. Can anyone share with me?

**Comment by KolbotMod** [comment]
send me a folder with a bot I will see

**Comment by olsoner1** [comment]
thanks for the fast reply. I actually went back and looked at the Kolton.nip file from two months ago and it had what I am looking for. Just need to take out the parts I need and done. I had changed so much from the start of ladder to pick up everything. Now I just need perfect stuff.
