### ISSUE TITLE
skip a person in skill quests script? 

### ISSUE THREAD

**Issue by cryptic7s** [kolton/d2bot-with-kolbot#1028]
there a way to skip a person in skill quests script? cant figure it out. and im trying to skip izzy

**Comment by blinktenor** [comment]
https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/bots/Rusher.js#L23

Try removing them from this line. The other option if you want to turn it on/off quickly is make a config for it and put it into your character config.

**Comment by cryptic7s** [comment]
ight ty
