### ISSUE TITLE
Need Help With Code

### ISSUE THREAD

**Issue by PhiRip7** [kolton/d2bot-with-kolbot#1032]
I've noticed sometimes the bot screens goes black, but if you see it and hit esc it fixes and the bot can continue the run. What would I have to add to the code to have the bot automatically hit esc when this issue occurs and where would I put it?

**Comment by noah-** [comment]
What version are you running? This should never happen.

**Comment by PhiRip7** [comment]
18.6.15.200

**Comment by noah-** [comment]
Use a more recent version.
