### ISSUE TITLE
how to specify crushing blow as an item stat

### ISSUE THREAD

**Issue by Learningslow** [kolton/d2bot-with-kolbot#1037]
Hello,
Im trying to craft blood gloves with 10% crushing blow when i have the value [crushingblow] == 10
It says unknown stat in the kolton.nip.

Anyone know how to get crushing blow items to work in pickit?

**Comment by bfass** [comment]
There is a detailed guide on [how to config your pickits](https://github.com/blizzhackers/pickits/blob/master/NipGuide.md)
Add 

[itemcrushingblow] >= 1
or [itemcrushingblowperlevel] >= 1
or [itemcrushingblowbytime] >= 1

to
{stats} 
-->
{properties} # {stats} # {maxquantity}

like:
[type] == sword && [quality] == unique # [itemcrushingblow] >= 1

There is also a [list of all stats](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/NTItemAlias.dbl). You can also find it in your kolbot folder : d2bs\kolbot\libs\NTItemAlias.dbl

**Comment by Learningslow** [comment]
> There is a detailed guide on [how to config your pickits](https://github.com/blizzhackers/pickits/blob/master/NipGuide.md)
> Add
> 
> [itemcrushingblow] >= 1
> or [itemcrushingblowperlevel] >= 1
> or [itemcrushingblowbytime] >= 1
> 
> to
> {stats}
> -->
> {properties} # {stats} # {maxquantity}
> 
> like:
> [type] == sword && [quality] == unique # [itemcrushingblow] >= 1
> 
> There is also a [list of all stats](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/NTItemAlias.dbl). You can also find it in your kolbot folder : d2bs\kolbot\libs\NTItemAlias.dbl

thanks I found the list of stats appreciate the help
