### ISSUE TITLE
Please help me with this weird weapon swapping thing, d2bs

### ISSUE THREAD

**Issue by abicodue** [kolton/d2bot-with-kolbot#1057]
My ww barb does this weird weapon swapping thing. Followings are the configs and the video:

config: https://dpaste.de/WBYT
video: https://youtu.be/1xIZquqJFFg

I updated my d2bs from the 'about' menu, so it's up to date.

**Comment by DarkHorseDre** [comment]
youve already created a thread for this - dont create more than one post for the same item.
please close this one.

link https://github.com/kolton/d2bot-with-kolbot/issues/1042

**Comment by abicodue** [comment]
a
