### ISSUE TITLE
Does anyone know how to.....

### ISSUE THREAD

**Issue by Ornate-Hunter** [kolton/d2bot-with-kolbot#1072]
Make the bot kick open barrels?

**Comment by Ornate-Hunter** [comment]
and urns, and large urns, and all those other little chances at items sitting around that the bot blindly flys by

**Comment by texxxmex** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/1014

Check that thread out. Should be what you want.

**Comment by Ornate-Hunter** [comment]
thank you very much Tex, I appreciate that greatly.

**Comment by Ornate-Hunter** [comment]
Ok so i got most of the bot to open most of the containers,But.....
It is grabbing dead rogues, but skipping the dead rogues that are on posts, is this a dead rogue 2 or is it some other id?

**Comment by JohnnyMakeBeliever** [comment]
Is this all we can add or can we go ham and add all of this? 

http://diablo.wikia.com/wiki/Containers

**Comment by Ornate-Hunter** [comment]
I added them all and now i open everything but, dead rogues that are on posts, corpses that are on posts and the corpses that are tied up on their knees.

**Comment by Ornate-Hunter** [comment]
So mine looks like this
var i, unit,
			list = [],
			ids = ["chest", "chest3", "armorstand", "weaponrack", "hidden stash", "roguecorpse", "skeleton", "skullpile", "skull pile", "loose rock", "loose boulder","barrel","basket","crate","urn","jug","jar","large urn","small urn","casket","sarcophagus","tomb","undefiled grave","rat's nest","goo pile","cocoon","bone chest","hung skeleton","hidden stash","skulls and rocks","burial chest","hollow log","trapped soul","dead rogue","guard corpse","dead barbarian"];
