### ISSUE TITLE
any1 knows config codes for a farming ww barb?

### ISSUE THREAD

**Issue by abicodue** [kolton/d2bot-with-kolbot#1076]
I used basic codes for my farming ww barb(who is a lead not a following BO barb), and it does a weird weapon swapping thing. I don't know how to write new codes for actually farming ww barb. Can anyone PLEASE write down the proper codes and post it?

My current config codes and the video of weird weapon swapping:
config: https://dpaste.de/WBYT
video: https://youtu.be/1xIZquqJFFg

**Comment by aim2kill** [comment]
Look like you having problem with the barb no detecting the BC state
