### ISSUE TITLE
Elemental Druid stuck in countess

### ISSUE THREAD

**Issue by germanchop** [kolton/d2bot-with-kolbot#1083]
Hi!
I have a Pally running and when send mftp he come down he cant cast (i think is a space problem) i add a enigma and wont solve the problem. If i move it a little he cast and work perfectly. any clue?
Thx

**Comment by fabio1999ita** [comment]
you need mfhelp whit fix
[MFHelper.txt](https://github.com/kolton/d2bot-with-kolbot/files/2788025/MFHelper.txt)
try this mfh

**Comment by germanchop** [comment]
Good!!! Thx 
work good now :)

**Comment by fabio1999ita** [comment]
But now bot don't stop after bug correct? You can execute first countess whit dudu and after do mfh for bypass bug

**Comment by germanchop** [comment]
the druid stay on tower lvl 5 unable to summon the vine, if i start without the druid he miss the bo

**Comment by fabio1999ita** [comment]
For bo you can use the function for bo at start of char config

**Comment by germanchop** [comment]
I solve it adding something before countess

**Comment by Bchilled** [comment]
Where do you put the MFHelper.txt to fix this issue?
