### ISSUE TITLE
D2m.dll failed to load

### ISSUE THREAD

**Issue by Cdons** [kolton/d2bot-with-kolbot#1089]
Hi, new here
Went through a bunch of previous topics with same issue and couldnt find any real solution except to download a link not available anymore. Is there any fix for this yet or do i just need to continue install/re install till it works?
Followed different videos on YT and still cant get it, any help is appreciated
Thanks

Edit
Nvm i figured it out. But now i finally got it to load i found out about the 16 digit keys ... so all 7 of my key sets have already been claimed. Only way to get another set is to buy it off blizz site?

**Comment by semirotta** [comment]
I dont know about the cd-key thing, my key works just fine and I use the one I have from CD I bought like 20 years ago. Also the .dll issue is annoying and happens randomly I've noticed, just change the branch and youre fine most likely.

**Comment by Cdons** [comment]
So when you say change the branch I could t figure that one out, in your thread the link was broken and I can’t find the limedropper utf branch or whatever. But I’ve now at least got the loader popping up and trying to log in. I just apparently can’t use any of my old 16 digit keys unless there is a way around the “claimed” key. I don’t really wanna use the only 26 digit I have linked to my main account. I will if that’s all I’ve got cause I’m not dropping 25 bucks on a 26 digit when I have 7 old keys here lol. So is there any other way to use these old keys?

**Comment by semirotta** [comment]
Oh right I think the 16 digit key becomes an issue when you have multiple accounts in use but I use only one so I have no issue with it.
I cant unfortunately give any answer on the old keys :(

**Comment by Cdons** [comment]
Well as of now I’m only running one, but when I installed the game through daemon light for the virtual disc I used an old key. Once everything started to load up it said the key you used had been disabled. So then I started making key sets of the few 16s I have and everyone I tried said claimed already. So that’s pretty lame but I can’t say I never expected this buying keys off non blizzard sites :/. So that’s all good I have one or two 26 keys it was just too late last night to try anything else lol. Thanks for the comments though. Anything helps

**Comment by semirotta** [comment]
I personally would never buy cd-key to a game from anywhere else than the original creator or safe website where they are sold. Sites like g2a etc. are just garbage because the keys are purchased with stolen credit cards and accounts and what not so the keys will stop working most likely eventually.
