### ISSUE TITLE
Follower Leech just using Teleport - how disable it?

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#1091]
Hey another problem...

i got a soso leech and she only use teleport to move in Diablo Wakka ore other area...
how i can disable it?
i dont want so reset stats...
because she got no mana and try to move and stuck then...

is there a option mby?

**Comment by aim2kill** [comment]
If you using follower script then...
/*
* Follower by kolton
* To initiate the follow sequence make a TP and send command "1".
*
* Commands:
* Main commands:
*	1 - take leader's tp from town / move to leader's town
*	2 - take leader's tp to town
*	3 - town manager
*	c - get corpse
*	p - pick items
*	s - toggle stop
*	<charname> s - toggle stop <charname>
* Attack:
*	a - attack toggle for all
*	<charname> a - attack toggle for <charname>
*	aon - attack on for all
*	<charname> aon - attack on for <charname>
*	aoff - attack off for all
*	<charname> aoff - attack off for <charname>
* Teleport: *** characters without teleport skill will ignore tele command ***
*	tele - toggle teleport for all
*	<charname> tele - toggle teleport for <charname>
*	tele on - teleport on for all
*	<charname> tele on -  teleport on for <charname>
*	tele off - teleport off for all
*	<charname> tele off - teleport off for <charname>
* Skills: *** refer to skills.txt ***
*	all skill <skillid> - change skill for all. refer to skills.txt
*	<charname> skill <skillid> - change skill for <charname>
*	<class> skill <skillid> - change skill for all characters of certain class *** any part of class name will do *** for example: "sorc skill 36", "zon skill 0", "din skill 106"
* Auras: *** refer to skills.txt ***
*	all aura <skillid> - change aura for all paladins
*	<charname> aura <skillid> - change aura for <charname>
* Town:
*	a2-5 - move to appropriate act (after quest) !NOTE: Disable 'no sound' or game will crash!
*	talk <npc name> - talk to a npc in town
* Misc.
*	cow - enter red cow portal
*	wp - all players activate a nearby wp
*	<charname> wp - <charname> activates a nearby wp
*	bo - barbarian precast
*	<charname> tp - make a TP. Needs a TP tome if not using custom libs.
*	move - move in a random direction (use if you're stuck by followers)
*	reload - reload script. Use only in case of emergency, or after editing character config.
*	quit - exit game
*

**Comment by DS1337** [comment]
Entry Script Follower but in Char Config is only Diablo Wakka on "true"
nothing else :)

**Comment by aim2kill** [comment]
Weird wakka is design for walking only

**Comment by 5noop** [comment]
Set `Pather.teleport = false;` after `function Wakka() {` in Wakka.js

**Comment by DS1337** [comment]
> 
> 
> Set `Pather.teleport = false;` after `function Wakka() {` in Wakka.js

I know, little bit late, but works fine! :-D

I did not try it 1 year ago, but now i got the same Problem and found my own post haha ^^

Ty buddy <3
