### ISSUE TITLE
how do you get wakka to wait for lead?

### ISSUE THREAD

**Issue by theeomen** [kolton/d2bot-with-kolbot#1095]
havent been able to figure this out . so ive been adding extra bots to follower ..

**Comment by aim2kill** [comment]
Wait for? The follower is leaving the gmae? Does the leader inv the follower and follower accept?

**Comment by theeomen** [comment]
follower waiting for lead . just with chaos

**Comment by aim2kill** [comment]
Follower wait at town and leader open tp at the start and call for followe(wakka)

**Comment by aim2kill** [comment]
That the leader config?
Cause I see you have 
Scripts.Wakka = false;

**Comment by theeomen** [comment]
yeah an no it was set to true i changed earlier to try to see if there would be any effect.

**Comment by DarkHorseDre** [comment]
FYI this has been added to the code but over to koltons new home (https://github.com/blizzhackers/)

a new parameter allows you to set number of minutes to wait for leader, so you can close this issue
