### ISSUE TITLE
Claimed CD Key issue

### ISSUE THREAD

**Issue by Cdons** [kolton/d2bot-with-kolbot#1097]
Before i give up on every old key i have im just making sure ive done everything correctly. Im not sure if everyone is still using old 16 digit keys that they registered on bnet site or not. But i have 7 keys, the one i installed my game with through Daemon that i had planned to use said it was disabled when the bot tried to log. So then i went and made key files assuming i did it correctly and the other 6 of my keys said " Claimed on b Net. " I then went to blizzard site and tried typing in every key in the converter and they all said already claimed. So im just curios is everyone still using old cd keys they bought off non blizzard sites like I did, or are most using 26 digit keys that were converted from old 16 digit keys or just bought a new 26 set and typed that into the key file. I do have a 26 key to try when i get home tonight but was wondering if i just throw out all those old keys cause I didnt register them in time and just lost out. Not even really mad as i expected something to happen down the road buying non blizzard keys but wasnt sure if i was doing everything properly so curious what keys others are using. Sorry for the rant.
Thanks

**Comment by braxIRL** [comment]
I'm almost positive you lost the keys due to the site you bought them from. When blizzard implemented the 26 keys sites began to claim as many old keys as possible as it became their keys again because they claimed them before you did. I guess the lesson is to just buy the $10 keys from blizzard instead of being cheap and getting scammed down the road :)

**Comment by Cdons** [comment]
Ya I know that now lol. But it’s all good I got much use out of those keys. Just wanted to make sure it wasn’t me doing something. Thanks
