### ISSUE TITLE
channelbot block when join

### ISSUE THREAD

**Issue by fabio1999ita** [kolton/d2bot-with-kolbot#1100]
after a while time the bot channel is going crashes in entering the game, the console comes out "joining + name game" but will remain' stopped until you intervene
![bot](https://user-images.githubusercontent.com/27001568/51570238-d775d300-1e9e-11e9-9f98-8f2ab60f7235.PNG)
![bot1](https://user-images.githubusercontent.com/27001568/51570301-fb391900-1e9e-11e9-8fef-366440011e21.PNG)

**Comment by braxIRL** [comment]
is this your lead bot or a follower bot?

**Comment by braxIRL** [comment]
Wait are you saying the bot channel is trying to enter games or when your other bot enters a game, the bot channel crashes? Sorry for my confusion

**Comment by braxIRL** [comment]
correct me if I'm wrong anybody, but the "D2BotChannel.dbj" isn't meant to actually join games. It just announces shit in a channel to help others follow your games or other peoples games by ".login" via channel. So I'm still a bit confused to why your bot is having issues "joining" games?

**Comment by fabio1999ita** [comment]
"D2BotChannel.dbj" is equals to d2botfollower but botfollower join to local game in same computer, botchanne join in two or more computer

**Comment by fabio1999ita** [comment]
i fix it from line 488 to 513 in D2BotChannel.dbj

			me.blockmouse = true;

			ControlAction.click(6, 594, 433, 172, 32); //key join game

			me.blockmouse = false;
			lastGameStatus = "pending";
			
			if (!locationTimeout(5000, location)) { // in case create button gets bugged
				if (!ControlAction.click(6, 533, 469, 120, 20)) { // Create
					break;
				}			
			
				if (!ControlAction.click(6, 652, 469, 120, 20)) { // Join
					break;
				}

			}
			
			if (!locationTimeout(15000, location)) { // in case create button gets bugged
				ControlAction.click(6, 533, 469, 120, 20)	// Create
				delay(500);
				ControlAction.click(6, 652, 469, 120, 20)	// Join	
				break;
			}
			
			//locationTimeout(5000, location);
		
![fix1](https://user-images.githubusercontent.com/27001568/51861981-e1d01b00-233d-11e9-9b3f-8f49e97df7b0.PNG)
