### ISSUE TITLE
AutoSmurf issue

### ISSUE THREAD

**Issue by gbgodoy** [kolton/d2bot-with-kolbot#1101]
strange problem, my smurf is doing everything right but when he goes town after doing DEN he just stand at WP saying that will start next quest BloodRaven and quit game. But the strange is that if i run it on single player he dont do any errors.

Can any1 help me with this?

[https://pastebin.com/fFNQBXZa](url)

**Comment by 5noop** [comment]
Any error in the logs ?

**Comment by gbgodoy** [comment]
no errors, it get internet interrupted and leave the game
[https://i.postimg.cc/7YhhR12S/Sem-t-tulo.png](url)

**Comment by aim2kill** [comment]
Did he get wp after doing den?
