### ISSUE TITLE
Scripts.KillDclone?

### ISSUE THREAD

**Issue by braxIRL** [kolton/d2bot-with-kolbot#1104]
Does the Scripts.KillDClone need to be set true for DClone Config options to work? If so I have them both active, but Scripts.KillDClone keeps heading to arcane sanctuary into the cellars but gets an error msg that there is no target. Which makes sense because he's not there nor should he be because Diablo hasn't walked the earth. So what I'm really asking is, is this working properly or am I missing something? I thought the bot knew if DClone walked the earth or not and if not it would just end the game.

**Comment by DarkHorseDre** [comment]
not sure what that setting does, think its disabled on mine.  you need to enable:

 Config.StopOnDClone = true; // Go to town and idle as soon as Diablo walks the Earth
    Config.SoJWaitTime = 5; // Time in minutes to wait for another SoJ sale before leaving game. 0 = disabled
    Config.KillDclone = true; // Go to Palace Cellar 3 and try to kill Diablo Clone. Pointless if you already have Annihilus.
    Config.DCloneQuit = false; // 1 = quit when Diablo walks, 2 = quit on soj sales, 0 = disabled

**Comment by braxIRL** [comment]
Ya all of that for me is enabled but there's another line (198) Scripts.KillDclone = false; // Kill Diablo Clone by using Arcane Sanctuary waypoint. Diablo needs to walk the Earth in the game.

Does this need to be enabled?

I've also gone ahead and tested the script. At the end of my Cbaal runs, it runs the script and all my bots head for arcane sanctuary but, DClone hasn't walked the earth. So why are they running to arcane sanctuary? 

Thanks for the response again DarkHorseDre! :)

**Comment by braxIRL** [comment]
You didn't "technically" say no lol sorry I assumed when you said "I don't know" that you didn't know if it needed to be on or not. Have you had DClone walk the earth and it work? I'm just trying not to miss DClone because I've yet to obtain an Anni.

**Comment by DarkHorseDre** [comment]
>not sure what that setting does, think its disabled on mine
:D

> I'm just trying not to miss DClone because I've yet to obtain an Anni.

set the settings I told you and it will do as the in-line comments, and I said it will!

You wont see many dclone walks as few people buy up all the sojs, choose an ip, then camp on the ips and sell to get multiple walks.  leaving `config.StopOnDClone = true` for all profiles in hell enable you to hold that IP if he walks.  if it can kill dclone then you enable the feature I listed to do that.

read the comments! read the whole config - lots of good stuff to learn (and confuse) in there!
