### ISSUE TITLE
MF Leader/Helper independence?

### ISSUE THREAD

**Issue by fadriansquest** [kolton/d2bot-with-kolbot#1112]
How can I essentially set up two MFLeaders? I would like Sorc 1 to create a game and farm areas A & B, while Sorc 2 joins the same game and farms areas C & D? Slightly different from Leader and Helper since I want the two Sorcs to be simultaneously farming SEPARATE areas, not helping each other kill the same bosses. Which scripts can I use and what do I have to edit to make this work?

Additionally, in the future I would like to run the scenario above while also having a Baal runner and leeched all in the same game.

Hopefully this isn’t too difficult since I see it occurring all the time. I’m just confused on how to set it up. 
Thanks.

**Comment by DarkHorseDre** [comment]
I dont know how to make a leader JOIN another game but I'd guess you set mfleader in config then use follower entry script (to force game joining).  set leader name for leader 2 as leader 1,

set follower entry script up to pair toon appropriately:
var JoinSettings = {
"lead1": ["follow1", "follow2"],
"lead2": ["follow3", "follow4"]
};
