### ISSUE TITLE
please help me with light sorc config attack

### ISSUE THREAD

**Issue by petre1972** [kolton/d2bot-with-kolbot#1121]
please tell me how to set  up config attack for light sorc.
I made these settings :

Config.AttackSkill[0] = 49; // Preattack skill.
	Config.AttackSkill[1] = 49; // Primary skill to bosses.
	Config.AttackSkill[2] = 53; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 49; // Primary skill to others.
	Config.AttackSkill[4] = 53; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 49; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 53; // Secondary untimed skill if monster is immune to primary untimed.
![screenshot001](https://user-images.githubusercontent.com/41229801/51776580-86feaf80-2102-11e9-978c-5492b3c682e2.jpg)

create a game, there are no errors , but does not start.
Thanks

**Comment by DS1337** [comment]
Learn READ buddy! :)

	// User addon script. Read the description in libs/bots/UserAddon.js
	Scripts.UserAddon = true; // !!!YOU MUST SET THIS TO FALSE IF YOU WANT TO RUN BOSS/AREA SCRIPTS!!!

Do it on FALSE!

**Comment by aim2kill** [comment]
Beside what DS1337 say also
Config.AttackSkill[0] = -1; // Preattack skill.
Config.AttackSkill[1] = 49; // Primary skill to bosses.
Config.AttackSkill[2] = 53; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
Config.AttackSkill[3] = 49; // Primary skill to others.
Config.AttackSkill[4] = 53; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed

**Comment by petre1972** [comment]
thank you, I did not think about it :)   now it works .

**Comment by aim2kill** [comment]
@sander74300 post your sorc config as a pastebin

**Comment by Helpmeplease1993** [comment]
hello! im glad the original poster figured out his problem for his bot! but im having an extremly difficult time getting mine started, i was hoping there was a way i could just copy and paste some one elses sorceress script into my config, ive litterally spent days trying to go over the script but i can not figure it out, i even go through walk through videos and i still cant get it to work, the first error i get is bad attack config. also note, i did turn // User addon script. Read the description in libs/bots/UserAddon.js
Scripts.UserAddon = true; // !!!YOU MUST SET THIS TO FALSE IF YOU WANT TO RUN BOSS/AREA SCRIPTS!!! to (false)                                                                                                	 
        Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = -59; // Primary skill to bosses.
	Config.AttackSkill[2] = -39; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = -59; // Primary skill to others.
	Config.AttackSkill[4] = -39; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -36; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -36; // Secondary untimed skill if monster is immune to primary untimed.

**Comment by Oregon-Snake** [comment]
remove the minuses, ie
        Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 59; // Primary skill to bosses.
	Config.AttackSkill[2] = 45; // Primary untimed skill to bosses. Keep at -1 if 
        Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 59; // Primary skill to others.
	Config.AttackSkill[4] = 45; // Primary untimed skill to others. Keep at -1 if 
        Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 56; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 47; // Secondary untimed skill if monster is immune to 
        primary untimed.

you can copy and paste this assuming you want to use the same skills for your light sorc
