### ISSUE TITLE
Chest Mania not working fine

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#1122]
Hey guys...

i want, dat my bot do the Lower Kurast (LK) Chests...
but he do it 3 times!?!

	// *** act 3 ***
	Scripts.Stormtree = false;
	Scripts.KurastTemples = false;
	Scripts.Icehawk = false;
	Scripts.Endugu = false;
	Scripts.Travincal = false;
		Config.Travincal.PortalLeech = false; // Set to true to open a portal for leechers.
	Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
		Config.ChestMania.Act1 = //[13, 14, 15, 16, 18, 19]; // List of act 1 areas to open chests in
		Config.ChestMania.Act2 = //[55, 59, 65, 66, 67, 68, 69, 70, 71, 72]; // List of act 2 areas to open chests in
		Config.ChestMania.Act3 = [79]; // List of act 3 areas to open chests in
		Config.ChestMania.Act4 = //[]; // List of act 4 areas to open chests in
		Config.ChestMania.Act5 = //[115, 116, 119, 125, 126, 127]; // List of act 5 areas to open chests in
	Scripts.Mephisto = true;
		Config.Mephisto.MoatTrick = false;
		Config.Mephisto.KillCouncil = false;
		Config.Mephisto.TakeRedPortal = true;

What did i do wrong...??
Why he do it 3 times? :)

//EDIT

I put it in Akt 3 befor he do Mephi...so he do first chest then after dat meph...
this is working, but ya, he do it 3 times the Chest Mania?!

**Comment by aim2kill** [comment]
The only thing is see wrong is // place then infront of //config.chest of the one you d9nt want to do

**Comment by khayhurst** [comment]
aim2kill is correct. Since this is JavaScript you're essentially assigning 79 to acts 1 and 2 as well as act 3 due to commenting out the arrays ending in semicolons. aim2kill's solution should work, if not, remove the numbers from the arrays so it looks like act 4.
