### ISSUE TITLE
FTJ and RD Issue

### ISSUE THREAD

**Issue by olsoner1** [kolton/d2bot-with-kolbot#1124]
I just started botting this ladder. Started off with one char and now just got to four chars with four keys. I am running 650-750 second games with all four chars in one game. Doing a 20 second game delay before each game also. I just went from 3 bots to 4 bots and I am really experiencing issues with FTJ and RD's. What is the issue?

**Comment by aim2kill** [comment]
So each bot is doing 5-6 game per hour that 20 to 24 game, no including chicken,I suggest to add more scripts to you bot to make it aleast 20 mins each. That what I do

**Comment by semirotta** [comment]
Just make the games longer, my game times are between 40-60 minutes easily and I dont have issues with RD's. Happens mostly when I try solo mule :P

**Comment by timbula** [comment]
yea u have to make games long as possible atleast if you use more than one profile.
