### ISSUE TITLE
How many games per CD-Key/Bot/IP - 2019 Realm Down

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#1132]
Hey me again...

Blizzarhackers and Etal are down...so all forum post are gone...

how many games u can do per 1h with 1 CD-Key/Bot/IP?
What is up to date in 2019 1.14d?
New rules for Realm Downs (RD)? :)

And anybody got some (old/new)Links from the chance logs and everything?

have a nice day! :)

**Comment by DS1337** [comment]
30 per h? o.O so more then befor?
befor it was like 20 per h and now 30? o.O
I read something about 5-10 Runs in 1h :/
U think u can find the link again mby? :)

**Comment by semirotta** [comment]
I believe its 20 per hour max.

**Comment by DS1337** [comment]
Check Out my post on epvp...juse translate mby
i have do a research for it! :)

https://www.elitepvpers.com/forum/diablo-2/1855205-d2bot-mit-kolbot-release-ein-neuer-bot-f-r-d2bs-401.html#post37370221
