### ISSUE TITLE
Are there any other link?

### ISSUE THREAD

**Issue by gbgodoy** [kolton/d2bot-with-kolbot#1139]
i have everything working fine but i want to know what that limedrop-utf8 version can do better
is this the only link available?

https://github.com/kolton/d2bot-with-kolbot/tree/limedrop-utf8

**Comment by fabio1999ita** [comment]
install: https://github.com/kolton/d2bot-with-kolbot/wiki/Lime-Drop-Install
usage: https://github.com/kolton/d2bot-with-kolbot/wiki/Lime-Drop-Use
