### ISSUE TITLE
Full Clear Worldstone

### ISSUE THREAD

**Issue by luvvi** [kolton/d2bot-with-kolbot#1142]
I've been messing with Pather.js to kill Specters on the way to Summoner. The link [here](https://github.com/kolton/d2bot-with-kolbot/issues/592) will show you how to accomplish this.

I'm curious if it's possible add something similar so that my team will full clear Worldstone. I've tried using ClearAnyArea but it doesn't seem to work well when you're doing team MF.

**Comment by JohnnyMakeBeliever** [comment]
I do wish the mfleader/helper config worked better with clearanyarea

**Comment by DarkHorseDre** [comment]
So you want followers to stay near leader when clearing or?

I like the way tristleecher works: followers locate leader and stay within distance of 4 at all times (even if leader tele's). they also attack (script needs changing so they pickit too btw)

**Comment by luvvi** [comment]
Yea it would be ideal if the followers could stay near the leader. Honestly I'd be happy if they could clear Worldstone in the same way they clear Chaos.

**Comment by DarkHorseDre** [comment]
wait, do you just want the team to clear worldstone as they do say mausoleum? (I cant remember how they do cs - thought it was multiple tps per seal?)

if so, change the command the mfleader gives in worldstone. if something else let me know, but I think it will be easy if you just want the mfhelpers to clear an area in the same way as another script (mfhelper recognises kill, clear and a few other commands)

**Comment by luvvi** [comment]
The team currently clears Worldstone in the same way that they would clear Mausoleum, they only go after boss packs and leaves everything else alive. I'm trying to set this up so that they will kill everything (like they do in Chaos).

I think one possible solution could be adding lines to Pather.js so that all monster types found in Worldstone can be targeted. I got this idea from the following script (Pather.js Line 24):

```
if (Config.Countess.KillGhosts && [21, 22, 23, 24, 25].indexOf(me.area) > -1) {
			monList = Attack.getMob(38, 0, 30);

			if (monList) {
				Attack.clearList(monList);
			}
		}
```
This script targets all Ghosts on the way to Countess. If I can find the correct monster ID's I might be able to do something similar for Worldstone. What do you think?

**Comment by JohnnyMakeBeliever** [comment]
Config.cleartype = 0 as the script follows your clear type

**Comment by luvvi** [comment]
> Config.cleartype = 0 as the script follows your clear type

This could work but then it will do a full clear on all scripts. Is there way to run this for Worldstone only?

**Comment by DarkHorseDre** [comment]
@JohnnyMakeBeliever is saying you can call attack which will use cleartype based upon the config.  if you want it to be fixed for one script then hardcode the call.

e.g. mfhelper receives a command from mfleader of clearlevel and does this:
`                        Attack.clearLevel(Config.ClearType);`

So you could just put
`Attack.clearLevel(0);

well at least I assume parsing a 0 would be enough, but you get the idea

**Comment by DarkHorseDre** [comment]
Yes multiple scripts - thats standard! 

The worldstone script behaves like the scripts you want, where the leader issues commands and the followers process them in mfhelper.  you use both scripts so you must have seen how they work.

mfhelper will respond to clear and kill commands as I said.

example from Mausoleum.js:

Attack.clearLevel(Config.ClearType);

from attack.js
`if (Config.MFLeader) {`
`			Pather.makePortal();`
`			say("clearlevel " + getArea().name);`
`		}`

cleartype 0 = kill all monsters.

so from worldstone script you already have the clearlevel lines so you just need to change the parameter for cleartype in your config to 0 or hard code it in worldstone script to the literal 0 or whatever as I wrote above. that should tell mfhelpers to clearlevel all mobs.  Does that not work? or did I miss something? I havent read your script :)
