### ISSUE TITLE
mule start random

### ISSUE THREAD

**Issue by fabio1999ita** [kolton/d2bot-with-kolbot#1145]
my mule try to start random, it is possible to disable check mule? and start it only when i want?

**Comment by JohnGoblikon** [comment]
I made a thread about this too. I got no response. Just watched bot mule 1 item in the middle of a run.

**Comment by fabio1999ita** [comment]
i think that i have fix it (file: AutoMule.js, line 103 to 125)
![fix](https://user-images.githubusercontent.com/27001568/51861050-87ce5600-233b-11e9-93e6-e256d2c07071.PNG)
