### ISSUE TITLE
colorful words in the console

### ISSUE THREAD

**Issue by fabio1999ita** [kolton/d2bot-with-kolbot#1146]
i have this in code:
print("ÿc4MFHelperÿc0: Kill");
but console prints it all whit white color, i want write it whit color
someone know how to write word whit color in console?

**Comment by fabio1999ita** [comment]
i will try

**Comment by fabio1999ita** [comment]
it doesn't work
![prova1](https://user-images.githubusercontent.com/27001568/51863179-a1be6780-2340-11e9-99a6-5a2b77e9bbf8.PNG)

**Comment by DarkHorseDre** [comment]
lol you didnt write what I put in my post at all bro. pay attention.

**Comment by fabio1999ita** [comment]
so i want color that string... how can I do?

**Comment by noah-** [comment]
your code has a bug on line 8, it's not even printing what you wrote...

**Comment by fabio1999ita** [comment]
Can you give me a example of code for print("text"); whit text coloured?

**Comment by ryancrunchi** [comment]
you have to print a prefix of one of these :
```
WHITE: "ÿc0",
RED: "ÿc1",
NEON_GREEN: "ÿc2",
BLUE: "ÿc3",
DARK_GOLD: "ÿc4",
GRAY: "ÿc5",
BLACK: "ÿc6",
LIGHT_GOLD: "ÿc7",
ORANGE: "ÿc8",
YELLOW: "ÿc9",
DARK_GREEN: "ÿc:",
PURPLE: "ÿc;",
GREEN: "ÿc<"
```
e.g : `print("ÿc3text");` will display `text` in blue.

**Comment by fabio1999ita** [comment]
> you have to print a prefix of one of these :
> 
> ```
> WHITE: "ÿc0",
> RED: "ÿc1",
> NEON_GREEN: "ÿc2",
> BLUE: "ÿc3",
> DARK_GOLD: "ÿc4",
> GRAY: "ÿc5",
> BLACK: "ÿc6",
> LIGHT_GOLD: "ÿc7",
> ORANGE: "ÿc8",
> YELLOW: "ÿc9",
> DARK_GREEN: "ÿc:",
> PURPLE: "ÿc;",
> GREEN: "ÿc<"
> ```
> e.g : `print("ÿc3text");` will display `text` in blue.



I had already tried those prefixes
![cattura](https://user-images.githubusercontent.com/27001568/51915927-8012be00-23dc-11e9-945f-44248517fb54.PNG)
[MFHelper.txt](https://github.com/kolton/d2bot-with-kolbot/files/2808159/MFHelper.txt)

**Comment by fabio1999ita** [comment]
i check file whit SVN and now work
