### ISSUE TITLE
Leecher get corpse

### ISSUE THREAD

**Issue by RickerMD** [kolton/d2bot-with-kolbot#1147]
Is there a way to Leechers get corpses after death and return to leeching normally?

**Comment by RickerMD** [comment]
>           after death leech don't have teleport to go to its corpses

even sorcys?

**Comment by fabio1999ita** [comment]
I imagine that to get such a thing you should program it alone, in case you had a soso and then try to go back where it was dead would be cotroproducente since it would die again and you would build a loop

**Comment by DarkHorseDre** [comment]
Feah, naked sorc with no gear or BO (low life, low fcr, low block..) = bad idea

the bot is geared towards grabbing corpse in town so you'd have to customise as @fabio1999ita says

**Comment by RickerMD** [comment]
Ty all
