### ISSUE TITLE
PubJoin > How to join only fresh games

### ISSUE THREAD

**Issue by andreshko92** [kolton/d2bot-with-kolbot#1151]
As said in the title, is there a way to restrict the bot to pass all games older then particular time ? Right now I am loosing a lot of time stalling and doign nothing because of joining in games which are near its end (diabaal runs)

Thank you , any help is highly appreciated !

**Comment by fabio1999ita** [comment]
there isn't function, but you can follow same public run

**Comment by andreshko92** [comment]
well disappointing , thank you fabio

**Comment by gbgodoy** [comment]
as soon it doesnt enter the same game 2 times it will remove old games from list very fast

**Comment by ryancrunchi** [comment]
a PR is currently waiting for review and merge for this.
https://github.com/kolton/d2bot-with-kolbot/pull/985

**Comment by andreshko92** [comment]
Ryanchrunchi , that would be a fixer !

**Comment by andreshko92** [comment]
Hey Ryan any news  ?

**Comment by ryancrunchi** [comment]
The feature approval is not up to me. Can’t do anything more

**Comment by andreshko92** [comment]
Thanks for the update
