### ISSUE TITLE
Leecher using Vigor to move - how to change it?

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#1155]
Hey guys

i use the Entry Follower to lev up my Char in Wakka and BaalAssistant
normal leech setup...

al is working, but how can i chance, dat my Pala dont use Vigor to move?
he is pretty low life and got no resi...
so, i want to change it to salvation...

Its not a problem if he walks slower, but walking with salvation it is alot better so leech in Dia and Baal Runs...

i checked out BaalAssistant.js and Wakka.js for "Vigor" ore "115"(Attack/Aura Skill-ID), but i dont finde anything about it...
but somewhere there must be the point, dat he use Vigor to move in Wakka and BaalAssistant?!

I have set it on false, so its better for my leecher and my Party, when salvation is on in Baal:

Config.BaalAssistant.Helper = false; // Set to true to help attack, set false to to leech.

Is there anybody who got a idea to change vigor to salvation on my leecher? :)

**Comment by 5noop** [comment]
Set `Config.Vigor` to false in your character config file.

**Comment by DarkHorseDre** [comment]
as @5noop said, disable vigor.

the pala will then use the last aura activated when moving.  to ensure it is salvation you could modify your scripts, but easier to just set the primary aura (`Config.AttackSkill[4]`) to salvation in the attack in the pala config
