### ISSUE TITLE
Bot is not joining leaders tp in Chaos to kill

### ISSUE THREAD

**Issue by Smas87** [kolton/d2bot-with-kolbot#1166]
So when i first downloaded kolbot i config it so that the follower will join tp and help leader kill chaos. Than something went wrong and i had to reinstall and download it again. Now when i config it The follower will join but does not take the Tp? but when i use Wakka to lvl my low lvl chars it takes tp.. any reason why this is happening? did i set it up wrong? This is my configs for followers is that right?
-Thx

Config.Leader = "lorddessmf"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
	Config.QuitList = ["lorddessmf"]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];
	Config.QuitListMode = 1; // 0 = use character names; 1 = use profile names (all profiles must run on the same computer).

	Scripts.TristramLeech = false; // Enters Tristram, attempts to stay close to the leader and will try and help kill.
	Scripts.TravincalLeech = false; // Enters portal at back of Travincal.
		Config.TravincalLeech.Helper = true; // If set to true the character will teleport to the stairs and help attack.
	Scripts.MFHelper = false; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true
	Scripts.Wakka = false; // Walking chaos leecher with auto leader assignment, stays at safe distance from the leader
	Scripts.SealLeecher = false; // Enter safe portals to Chaos. Leader should run SealLeader.
	Scripts.DiabloHelper = true; // Chaos helper, kills monsters and doesn't open seals on its own.
		Config.DiabloHelper.Wait = 720; // Seconds to wait for a runner to be in Chaos. If Config.Leader is set, it will wait only for the leader.
		Config.DiabloHelper.Entrance = true; // Start from entrance. Set to false to start from star.
		Config.DiabloHelper.SkipTP = false; // Don't wait for town portal and directly head to chaos. It will clear monsters around chaos entrance and wait for the runner.
		Config.DiabloHelper.SkipIfBaal = false; // End script if there are party members in a Baal run.
	Scripts.AutoBaal = false; // Baal leecher with auto leader assignment
		Config.AutoBaal.FindShrine = false; // false = disabled, 1 = search after hot tp message, 2 = search as soon as leader is found
		Config.AutoBaal.LeechSpot = [15115, 5050]; // X, Y coords of Throne Room leech spot
		Config.AutoBaal.LongRangeSupport = false; // Cast long distance skills from a safe spot
	Scripts.BaalHelper = false;
		Config.BaalHelper.Wait = 120; // Seconds to wait for a runner to be in Throne
		Config.BaalHelper.KillNihlathak = false; // Kill Nihlathak before going to Throne
		Config.BaalHelper.FastChaos = false; // Kill Diablo before going to Throne
		Config.BaalHelper.DollQuit = false;  // End script if Dolls (Undead Soul Killers) are found.
		Config.BaalHelper.KillBaal = true; // Kill Baal. If set to false, you must configure Config.QuitList or the bot will wait indefinitely.
		Config.BaalHelper.SkipTP = false; // Don't wait for a TP, go to WSK3 and wait for someone to go to throne. Anti PK measure.
	Scripts.Follower = true; // Script that follows a manually played leader around like a merc. For a list of commands, see Follower.js

	// *** special scripts ***
	Scripts.WPGetter = true; // Get missing waypoints
	Scripts.GetKeys = false;  // Hunt for T/H/D keys
	Scripts.OrgTorch = false;
		Config.OrgTorch.MakeTorch = true; // Convert organ sets to torches
		Config.OrgTorch.WaitForKeys = true; // Enable Torch System to get keys from other profiles. See libs/TorchSystem.js for more info
		Config.OrgTorch.WaitTimeout = 15; // Time in minutes to wait for keys before moving on
		Config.OrgTorch.UseSalvation = true; // Use Salvation aura on Mephisto (if possible)
		Config.OrgTorch.GetFade = false; // Get fade by standing in a fire. You MUST have Last Wish or Treachery on your character being worn.
	Scripts.Rusher = false; // Rush bot. For a list of commands, see Rusher.js
		Config.Rusher.WaitPlayerCount = 0; // Wait until game has a certain number of players (0 - don't wait, 8 - wait for full game).
		Config.Rusher.Radament = false; // Do Radament quest.
		Config.Rusher.LamEsen = false; // Do Lam Esen quest.
		Config.Rusher.Izual = false; // Do Izual quest.
		Config.Rusher.Shenk = false; // Do Shenk quest.
		Config.Rusher.Anya = false; // Do Anya quest.
		Config.Rusher.LastRun = ""; // End rush after this run. List of runs: http://pastebin.com/Uez3nZ6g
	Scripts.Rushee = false; // Automatic rushee, works with Rusher. Set Rusher's character name as Config.Leader
		Config.Rushee.Quester = false; // Enter portals and get quest items.
		Config.Rushee.Bumper = false; // Do Ancients and Baal. Minimum levels: 20 - norm, 40 - nightmare
	Scripts.CrushTele = false; // classic rush teleporter. go to area of interest and press "-" numpad key
	Scripts.Questing = false; // solves missing quests (skill/stat+shenk)
	Scripts.Gamble = false; // Gambling system, other characters will mule gold into your game so you can gamble infinitely. See Gambling.js
	Scripts.Crafting = false; // Crafting system, other characters will mule crafting ingredients. See CraftingSystem.js
	Scripts.GhostBusters = false; // Kill ghosts in most areas that contain them
	Scripts.Enchant = false;
		Config.Enchant.Triggers = ["chant", "cows", "wps"]; // Chat commands for enchant, cow level and waypoint giving
		Config.Enchant.GetLeg = false; // Get Wirt's Leg from Tristram. If set to false, it will check for the leg in town.
		Config.Enchant.AutoChant = false; // Automatically enchant nearby players and their minions
		Config.Enchant.GameLength = 20; // Game length in minutes
	Scripts.IPHunter = false;
		Config.IPHunter.IPList = []; // List of IPs to look for. example: [165, 201, 64]
		Config.IPHunter.GameLength = 3; // Number of minutes to stay in game if ip wasn't found
	Scripts.KillDclone = false; // Kill Diablo Clone by using Arcane Sanctuary waypoint. Diablo needs to walk the Earth in the game.
	Scripts.ShopBot = false; // Shopbot script. Automatically uses shopbot.nip and ignores other pickits.
		// Supported NPCs: Akara, Charsi, Gheed, Elzix, Fara, Drognan, Ormus, Asheara, Hratli, Jamella, Halbu, Anya. Multiple NPCs are also supported, example: ["Elzix", "Fara"]
		// Use common sense when combining NPCs. Shopping in different acts will probably lead to bugs.
		Config.ShopBot.ShopNPC = "Anya";
		// Put item classid numbers or names to scan (remember to put quotes around names). Leave blank to scan ALL items. See libs/config/templates/ShopBot.txt
		Config.ShopBot.ScanIDs = [];
		Config.ShopBot.CycleDelay = 0; // Delay between shopping cycles in milliseconds, might help with crashes.
		Config.ShopBot.QuitOnMatch = false; // Leave game as soon as an item is shopped.
	Scripts.ChestMania = false; // Open chests in configured areas. See sdk/areas.txt
		Config.ChestMania.Act1 = [13, 14, 15, 16, 18, 19]; // List of act 1 areas to open chests in
		Config.ChestMania.Act2 = [55, 59, 65, 66, 67, 68, 69, 70, 71, 72]; // List of act 2 areas to open chests in
		Config.ChestMania.Act3 = [79, 80, 81, 92, 93, 84, 85, 90]; // List of act 3 areas to open chests in
		Config.ChestMania.Act4 = []; // List of act 4 areas to open chests in
		Config.ChestMania.Act5 = [115, 116, 119, 125, 126, 127]; // List of act 5 areas to open chests in
	Scripts.ClearAnyArea = false; // Clear any area. Uses Config.ClearType to determine which type of monsters to kill.
		Config.ClearAnyArea.AreaList = []; // List of area ids to clear. See sdk/areas.txt

**Comment by DarkHorseDre** [comment]
I only see diablohelper enabled but you mention wakka?

Post both leader and follower configs - but when you post, paste to pastebin.com and share the link as your configs fill the page and do not allow syntax highlighting, making it harder for people to help.

ps  - You have `scripts.Follower` enabled - this is for manual play with a follower walking close.  disable that.

**Comment by aim2kill** [comment]
Follower is for leader manual play that why the follower isnt taking the tp because the follower command to take tp is 1

**Comment by Smas87** [comment]
ya i did this when i was missing around with it but thx!!! i will post the pastebin

**Comment by Smas87** [comment]
here is the Leaders Configs   https://pastebin.com/QbuCAgTN
Here is the Followers configs  https://pastebin.com/m7AMwRL8

**Comment by DarkHorseDre** [comment]
which script are you trying to make the followers use?

**Comment by aim2kill** [comment]
Are you try to make the follower help leader in all leader scripts or just diablo/baal?

**Comment by DarkHorseDre** [comment]
ok so Diablo and DiabloHelper ..
does follower quit game/show error after timeout (12 mins)**?**

not sure whats wrong..

in theory it should work for wakka as it does dh.  i assume you just disable one and enable the other - no other changes**?**

fyi: `lorddessmf` is set as leader (character name) but quitlist will look for profile name as you set Config.QuitListMode = 1; (I Assume you have profile and char name the same, but I'd set this to 0 to be consistent and avoid future issues).

I also notice your  `Config.DiabloHelper.Wait = 720` s which I assume u set so you can guarantee leader will get to throne and tp in time.

It may be a leader issue.

To test:
set public mode for follower to accept only.
set leader to invite only
reduce diablohelptimer to lower number, say 2 mins (as below, leader will tele to star)
set leader diablo to tart from star (Config.Diablo.Entrance = false) - assume u have tele

you now will have time to see if follower detects leader and takes tp, or just timeout after 2 mins (before leader can finish cs)

**Comment by aim2kill** [comment]
Leader >>>>Config.MFLeader = true;
But 
Follower>>>Scripts.MFHelper = false;

**Comment by Smas87** [comment]
ok this is my sorc Leader  https://pastebin.com/0NUyQDtf
This the follower pally  https://pastebin.com/MUuVetjF
This is another follower Pally  https://pastebin.com/v406JwBJ

ok so when i put the Leader (sorc) to just invite only it does but when i put the 2 followers to just accept they won't so i switch them back to invite and accept they do both accept but when the leader makes tp at Star they wont enter.. waited for 160sec than both exit game Log says    

Error in DiabloHelper (diablohelper.js #444) Player wait timed out (No leader portals found) (Area: 103, Ping:46, Game: Runehunterzs195)

**Comment by aim2kill** [comment]
Try from the start not star and see if work

**Comment by Smas87** [comment]
i try both same thing

**Comment by aim2kill** [comment]
Does leader make tp? and say star tp up or no?

**Comment by Smas87** [comment]
https://pastebin.com/R3BSUZiX

**Comment by Smas87** [comment]
o i closed it? lol

**Comment by Smas87** [comment]
oops didnt mean to close it

**Comment by aim2kill** [comment]
Its ok did you check my last edit

**Comment by Smas87** [comment]
ya going to try it now

**Comment by aim2kill** [comment]
I believe you leader name is either missing a CaP someWheRe

**Comment by Smas87** [comment]
omg TyVM i left the leader blank and went with Profile name i thought i had it at profile name but didnt.. do you have a d2jsp? i need to send you some FG LOL

**Comment by Smas87** [comment]
stuck at it for like months

**Comment by aim2kill** [comment]
Its ok. I dont have d2jsp. Im glad to help

**Comment by Smas87** [comment]
Thx Your the best!!!!

**Comment by DarkHorseDre** [comment]
I swear I mentioned profile name and to test leader detection! ;)

**Comment by yumirrrrr** [comment]
Hello friends, I have a problem with the kolbot: the bot goes baalassistant.js makes me jump the error (baalassistant.js # 286) BaalHelper: Leader not party.

// Start
if (Leader) {
for (i = 0; i < 30; i += 1) {
if (Misc.inMyParty(Leader)) {
break;
}
delay(1000);
}
if (i === 30) {
throw new Error("BaalHelper: Leader not partied");
}
}

**Comment by hamsygab** [comment]
Hello im tryed everything but still my follower not entering in the tp  ............ can you check my sitting pls 


[Paladin.Bulgariapower.txt](https://github.com/kolton/d2bot-with-kolbot/files/4708507/Paladin.Bulgariapower.txt)
[Sorceress.Baybe.txt](https://github.com/kolton/d2bot-with-kolbot/files/4708509/Sorceress.Baybe.txt)

**Comment by aim2kill** [comment]
> Hello im tryed everything but still my follower not entering in the tp ............ can you check my sitting pls
> and my light sos not doing any dmg , saying the spell working but he just teleport not doing dmg
> 
> * he not selling the items who picking that i saw ..
>   ,
>   many thanks
> 
> [Paladin.Bulgariapower.txt](https://github.com/kolton/d2bot-with-kolbot/files/4708507/Paladin.Bulgariapower.txt)
> [Sorceress.Baybe.txt](https://github.com/kolton/d2bot-with-kolbot/files/4708509/Sorceress.Baybe.txt)

On sorc change 
On sorc change Scripts.MFHelper = true;
 Scripts.MFHelper = false; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true

**Comment by hamsygab** [comment]
thanks trying now

**Comment by hamsygab** [comment]
still not going in

**Comment by hamsygab** [comment]
change it but not going

**Comment by hamsygab** [comment]
leader not portied error
