### ISSUE TITLE
Remove Nip file

### ISSUE THREAD

**Issue by gbgodoy** [kolton/d2bot-with-kolbot#1167]
im doing a smurf team and i need to remove nip files from been loaded when my char hit certain lvl

ex. 1to9.nip
     10to30.nip
     and others...

than when i get to level 10 stop picking from 1to9.nip

i saw this in a post a few days ago and fits perfectly but i digged a LOT and could findind it

any help?

**Comment by DarkHorseDre** [comment]
if you use the autobuild feature you can specify config per level, including nip files

**Comment by gbgodoy** [comment]
im doing this but when i hit higher levels i dont want to pick the low items anymore but they are still been 
loaded

**Comment by gbgodoy** [comment]
yes thats correct, and this will help for sure.

thnx a lot i was going for the wrong way

**Comment by DarkHorseDre** [comment]
oh, I forgot about autoequip - it uses pickit files with the [tier] parameter - I have never used them but think they are character levels :)

d2bs\kolbot\pickit\Autoequip\READ.txt
example pickit:
d2bs\kolbot\pickit\Autoequip\sorceress.xpac.nip

**Comment by gbgodoy** [comment]
i thought tier create layers not based on char level

**Comment by DarkHorseDre** [comment]
ah ok then ignore me :D

**Comment by gbgodoy** [comment]
> ahhhhh yeah ok! it wont overwrite nips, it will add to a list - soz!
> 
> you could do a complicated thing where you call a script which checks the character level then loads the appropriate pickit, but there may be an easier way - what's the reason for the different nips vs level? to ensure it only picks good items it can use?
> 
> if so, you can specify level requirements in addition to stats for each item..

didnt work, ex. i cant remove bots from picking 1+ gold because the 1-9.nip is loaded

**Comment by DarkHorseDre** [comment]
I split my pots, gold and other non eq items into separate nips, so I can set low gold amounts when starting, then change to higher amounts later.
I also have a levelling set of nips (pots, items, gems etc) so I can enable them when necessary.

**Comment by gbgodoy** [comment]
im doing that too, but im trying something automated

**Comment by aim2kill** [comment]
Config.PickitFiles.splice(Config.PickitFiles.indexOf("the nipyouwanttoremove.nip"),1);
This need to be added to you autobuild

**Comment by DarkHorseDre** [comment]
@aim2kill - never seen it and didnt even think of that, good call :)

**Comment by aim2kill** [comment]
@DarkHorseDre Np mate

**Comment by gbgodoy** [comment]
thnx !! thats what i saw but i digged a lot here and im my history but could find.

ty !
