### ISSUE TITLE
Sorc with Lord De Seis

### ISSUE THREAD

**Issue by semirotta** [kolton/d2bot-with-kolbot#1169]
Does anyone have some sort of good sorc configuration in some place to avoid sorc getting almost killed about all the time with Lord De Seis in act4 chaos sanctuary?

The group usually has the aura that boosts att dmg and speed for the hostiles, soso tends to go too close and get one shot. Bit annoying because Ive been following it and it seems to happen quite often, most of the time it still manages to pull through luckily. I just wonder if there would be another way to try avoid this from happening? I have set dodge into 100% so its always trying to stay away from enemies.

**Comment by DarkHorseDre** [comment]
This has been raised before and people customised around it.  Search the issue list - something to do with changing the tele position and maybe the attack range.

**Comment by semirotta** [comment]
I need to keep digging. It's really frustrating

> 17:15:51 Life Chicken (384/2088) to Lord De Seis in Chaos Sanctuary. Ping: 93
17:48:42 Life Chicken (757/2088) to Lord De Seis in Chaos Sanctuary. Ping: 79

**Comment by DarkHorseDre** [comment]
searching is easy.  
click on 'issues' at the top of this page. it defaults to 'is open' in filters.

in filter box, type key words, search,

I just found the issue I told you about on the first page.

**Comment by semirotta** [comment]
Changed some things on Diablo file, seems to still die but like at least 50% less than it used to. So it definitely positions itself now better. I think I just got to tweakit and see how it goes

**Comment by semirotta** [comment]
Damn I love act4, I dont understand what is wrong with it. All this within 1 hour. It's just ridiculous how it teleports into the enemy piles and gets itself killed. :'D. I even have dodge 100% so it tries to dodge constantly. 

 Life Chicken (783/2088) to Doom Knight in Chaos Sanctuary. Ping: 78
 Life Chicken (610/2088) to Lord De Seis in Chaos Sanctuary. Ping: 62
Life Chicken (591/2088) to Doom Knight in Chaos Sanctuary. Ping: 94
Life Chicken (696/2088) to Doom Knight in Chaos Sanctuary. Ping: 78
Window has unexpectedly exited... starting profile
Crash Info: Script: Diablo Area: Chaos Sanctuary

**Comment by DarkHorseDre** [comment]
which class is the toon that is dying?
which skills is it using on de seis?
is it playing solo or supported by followers/leader and other follower?

**Comment by semirotta** [comment]
Sorcerer lvl 95 (soon 96)
ORB / FB combo
Solo, I only own one cd-key and no money to buy new 1s :S

**Comment by DarkHorseDre** [comment]
ok so quick test - change skill to blizzard for a couple runs and see if there is any difference.

if there is you may need to play with the range of attack as i posted 4 days ago
