### ISSUE TITLE
D2Bot fail to start - requirments?

### ISSUE THREAD

**Issue by trodas** [kolton/d2bot-with-kolbot#117]
What I did:
...
I get the zip archive, made a second Diablo 2 copy on different HDD and setuped it to run in window (-w parameter), then copied ONE my gameprofile into it (surprisingly Diablo 2 find all the profiles?!) and created a D2Bot dir", inside Diablo 2 dir, as the readme insist it need to be done.
Then I unpacked the archive and then I started the D2Bot.exe file.

And error 0xc0000135 resulted. Perhaps my old machine with Windows XP SP3 did not meet some requirmets? Do this software need something else also...?

...

This is unclear a bit for me:

.../D2Bot dir/D2BS/scripts.../
in your initial scirpts folder you must have
Folder: data <--- THIS IS MANDATORY!
File: D2BotLead.dbj
File: D2BotFollow.dbj
File: Any other starters you want

1) it is not possible to create a directory with name "scripts..." - the dots are omited
2) even when I create the dirs "scripts" and under it the directory "data" and copy the D2BotLead.dbj and D2BotFollow.dbj files into both of these directories, the D2Bot fail on start.

Some of the files are .js ... does it mean that it require JavaScript installed to work?

Thanks for some help.

**Comment by WiZzMaN47** [comment]
are u sure u have the path in the setup pointing to the right file.
i almost allways use lead beacuse even a lead can be configed to follow or do anyhting else
