### ISSUE TITLE
Bot doesnt move

### ISSUE THREAD

**Issue by truccoo** [kolton/d2bot-with-kolbot#1175]
Hi ! i just downloaded it, i made all config. When i put it ON, bot starts and make the game, but doesnt move when its on a game.

**Comment by drogga** [comment]
What does it say ingame when you open console

**Comment by aim2kill** [comment]
Did you read the config???

**Comment by truccoo** [comment]
wow Thanks aim2kill! sorry it was obvious, but i forgot all about bots and settings after many years ^^.
