### ISSUE TITLE
Lead Chicken Follower stay

### ISSUE THREAD

**Issue by truccoo** [kolton/d2bot-with-kolbot#1180]
Sorry if im gonna ask something obvious, but im really lost with these things xD.

i've having many problems, i started to run 2 soso bots, one lead and one follower. sometimes my lead dies (im poor :( ) and the follower stays at game waiting for nothing. 
How can i change it? I mean, if lead chicken, i wanna the follower leaves too.

Ty all ^^

**Comment by fabio1999ita** [comment]
at line 128 and 129 of char follower write nameofsosoleader in Config.Leader and Config.QuitList
`	Config.Leader = "nameofsosoleader"; //...
`
`	Config.QuitList = ["nameofsosoleader"]; //...
`

**Comment by truccoo** [comment]
Ty so much! ^^
