### ISSUE TITLE
Suggestion: Barb should not use "Find Item" at Throne Of Destruction

### ISSUE THREAD

**Issue by mcvk56** [kolton/d2bot-with-kolbot#1181]
Hello,
it makes no sense when Barb try to use "Find Item" at "Throne Of Destruction(Baalwaves)" because
the corpses disappear anyway and he tries to use "Find Item" on them

**Comment by DarkHorseDre** [comment]
Wrap an `if` in whichever script to check areaid 131 before casting find item:
(if areaid !== 131) { 
cast finditem}

that way it will only cast if not in throne

**Comment by mcvk56** [comment]
> 
> 
> Wrap an `if` in whichever script to check areaid 131 before casting find item:
> (if areaid !== 131) {
> cast finditem}
> 
> that way it will only cast if not in throne

that could work 
I try it later and let you know, thx :)

**Comment by 5noop** [comment]
If you don't want to change the attack file you can set specific parameters for each script in your config file. For instance if you run the baal script simply write this:
`Scripts.Baal = { FindItem: false };`

**Comment by DarkHorseDre** [comment]
truedat @5noop but does that work only for Baal or the whole baal script?
You would want to cast finditem on each mob of each wave, but not in the throne of destruction

**Comment by 5noop** [comment]
It's valid for the whole script. Not sure what you mean in your last sentence, the 5 waves spawn in the throne of destruction so changing the attack file or the parameter would yield the same result as far as I know.

**Comment by DarkHorseDre** [comment]
my bad, I misread op and thought he didn't want to do it for baal only!

So you're right, for baal waves, better to do in config as you never wanna do that (unless barb is 2nd+ toon and is running around doing find item during each wave)
