### ISSUE TITLE
Sorc Script skipping random uniques

### ISSUE THREAD

**Issue by kkstewart** [kolton/d2bot-with-kolbot#1186]
I have it to only skip physical and lightning immune, however it will do damage to a unique (last counsel member or lord seis in chaos) and then just tele away when either myself or merc could easily kill (seems like all lightning immune). I turned off tele stomp because sometimes it would get me killed when I could just clear everything else and then finish it off and that when I started to notice the issue. Can someone shed some light on this issue.
I'm a fully equip light sorc doing  lightning and full equip bot with infinity
[Sorceress.CIitCommander.txt](https://github.com/kolton/d2bot-with-kolbot/files/2830653/Sorceress.CIitCommander.txt)

**Comment by imbalanced** [comment]
If you don't have telestomp on, it'll skip immunes by default.

**Comment by kkstewart** [comment]
that seems odd? is there a way for telestomp to start after the mob is killed?
