### ISSUE TITLE
No gold pickup / item selling

### ISSUE THREAD

**Issue by kmdallday** [kolton/d2bot-with-kolbot#119]
So my not keeps getting items, identifying them, and dropping them without selling them, and also doesn't pickup gold. So after a little time, my not has zero gold.

I'm going to try to redownload everything when I get home and see if that solves the issue.

**Comment by DetectiveSquirrel** [comment]
Change to false
Config.FieldID = false; // Identify items in the field instead of going to town.
And maybe lower the gold to pickup aswell

**Comment by WiZzMaN47** [comment]
[name] == gold # [gold]  >= 1          // this will pick up 1 gold or anything greater
 put that line in your pickit file kolton.nip or whatever u use.
