### ISSUE TITLE
OrgTorch How does it work?

### ISSUE THREAD

**Issue by OneKelPeta** [kolton/d2bot-with-kolbot#1190]
Hi.
The Wiki doesn't describe anything and I can't find anything on the net.
I have 1 smite and 2 sorcs running for Keys and other stuff in the same game.
One sorc is running D2BotLead script and the smite is follower.
I want the smite to get keys from sorcs or by himself and open new game to do hf run.

Is this possible or how can i get this script other way around to work?
Should everybody have OrgTorch script activated?
Also don't understand the TorchSystem.js.
Thanx.

**Comment by drogga** [comment]
Enable OrgTorch with Smiter only and edit the Scripts below.
Use D2BotLead.dbj for Smiter
Open TorchSystem and edit Line 37-42 (Newest version)

"PROFILE NAME" -> Your Smiter Profile name

KeyFinderProfiles -> ["MF 1", "MF 2"],
(MF 1 & MF 2 must be your Sorceress Profile names)

FarmGame -> "Ubers-" for example (No Numbers)

I never used it before but I'm pretty sure that's the whole Config.
Not sure how it works ingame, so don't ask.

**Comment by OneKelPeta** [comment]
Thanks.
Tried it out and it works.
But smiter without enigma is stupid as hell.
He pulls all enemies, gets stuck and ends script.
