### ISSUE TITLE
Cubing higher runes?

### ISSUE THREAD

**Issue by EzRuneEzLife** [kolton/d2bot-with-kolbot#1195]
Can't seem to make it cube runes like sur -> ber. It stops at Ohm.

I've tried adding this, but I dont think its enough

Config.Recipes.push([Recipe.Rune, "Ohm Rune"]); // Upgrade Ohm to Lo
Config.Recipes.push([Recipe.Rune, "Lo Rune"]); // Upgrade Lo to Sur
Config.Recipes.push([Recipe.Rune, "Sur Rune"]); // Upgrade Sur to Ber

**Comment by EzRuneEzLife** [comment]
Never mind, it worked!

**Comment by oband2** [comment]
Would like to know how u made it work, it seems like i cant make my bot cube any runes, even tho its set to true, can u post your runecubing setup here?
