### ISSUE TITLE
FTJ action

### ISSUE THREAD

**Issue by Chopatona** [kolton/d2bot-with-kolbot#1197]
If FTJ happens while making the next game(+1),

I want to set my Bot to go in and out of the previous game(+0).

Is there any way?

sorry for bad English

**Comment by PoBErs** [comment]
AFAIK FTJ happens when you get connection interrupted and blizzards server still thinks your character is in a game. So even if you tried joining your last game it wouldn't work.

**Comment by Chopatona** [comment]
Ah ok understand thx fo reply :)
