### ISSUE TITLE
Pick up small gems

### ISSUE THREAD

**Issue by kmdallday** [kolton/d2bot-with-kolbot#120]
Hey I'm not sure how to make the bot pick up small gems for cubing such as chipped diamonds and such. How does one go about that?

**Comment by custompro12** [comment]
Add a line for each type in your pickit file (default: d2bs\kolbot\pickit\kolton.nip). Example:
`[name] == chippedamethyst`

The pickit file that your profile is using is listed in your profile's config (d2bs\kolbot\libs\config). Default:
`Config.PickitFiles.push("kolton.nip");`

See the Wiki page on 'Pickit' for more information
https://github.com/kolton/d2bot-with-kolbot/wiki/Pickit

**Comment by WiZzMaN47** [comment]
Cubing = true
Config.Recipes.push([Recipe.Gem, 557])
 copy and paste... 557 thru 581
That will cube all gems and skulls
