### ISSUE TITLE
Bot keeps getting black screen at chest

### ISSUE THREAD

**Issue by master2g** [kolton/d2bot-with-kolbot#1202]
My bot keeps getting that error where he sits at the chest with a blacked out screen.  He won't move until the game ends or I press escape so that it closes the broken menu.  Anyone know a fix to get around this?  I'd rather it not happen when I'm asleep.  Happens like 3-5 times a night and I'm sure it has something to do with auto crafting / cubing.

**Comment by fabio1999ita** [comment]
i think you don't have last upgrade, it was also happening to me a few months ago with the old versions
