### ISSUE TITLE
How do I make the Bot identify Items and keep random stats

### ISSUE THREAD

**Issue by drogga** [kolton/d2bot-with-kolbot#1212]
For example:

Magic Vampirebone Gloves with random stats

**Comment by semirotta** [comment]
For example like this:
> [Type] == gloves && [Quality] == rare && [Flag] != ethereal # [IAS] >= 20 && ([ItemAddSkillTab] >= 2 || [Strength] >= 14 || [Dexterity] >= 14) && ([LifeLeech] >= 3 || [ManaLeech] >= 3)

**Comment by DarkHorseDre** [comment]
if the stats are to be random, then specify the minimum you want.
so you mentioned `magic` and `vampirebone`

so all you need to satisfy your request is:
`[name] == vampirebonegloves && [quality] == magic`

but if you then realise it is taking eths, like semirotta said, add `[flag] != ethereal`

if you dont want truly random stats :) then qualify as semirotta stated.

**Comment by drogga** [comment]
> 
> 
> if the stats are to be random, then specify the minimum you want.
> so you mentioned `magic` and `vampirebone`
> 
> so all you need to satisfy your request is:
> `[name] == vampirebonegloves && [quality] == magic`
> 
> but if you then realise it is taking eths, like semirotta said, add `[flag] != ethereal`
> 
> if you dont want truly random stats :) then qualify as semirotta stated.

**Comment by drogga** [comment]
I'm looking for something without adding all the Magic Prefixes and Suffixes

[Name] == VampireboneGloves && [Quality] == Magic
only keeps them unidentified

Do I have to edit the "Item identification settings" in my Character Configs ?

Let me know

**Comment by DarkHorseDre** [comment]
if you want them to be random, why do you care if theyre id'd?

Use the flag parameter.
taken from kolton.nip, shipped with the bot:
```[name] == barbedshield && [quality] == unique && [flag] == identified```

**Comment by drogga** [comment]
> 
> 
> if you want them to be random, why do you care if theyre id'd?
> 
> Use the flag parameter.
> taken from kolton.nip, shipped with the bot:
> `[name] == barbedshield && [quality] == unique && [flag] == identified`

I don't want to identifiy the items afterwards
It's not a big deal^^but I just want to know if it's possible without adding all the different Prefixes/Suffixes.
The one you posted only keeps the Item with random stats if it's already identfied (Gambling random Circlets to re-roll them for example)

**Comment by DarkHorseDre** [comment]
haha ok

I get it now - think i read a thread about this but cant find it.
You want to id them and keep them no matter what.. I cant test this but try enabling cainid for all items and leave it as vampiregloves && rare?

**Comment by drogga** [comment]
> 
> 
> haha ok
> 
> I get it now - think i read a thread about this but cant find it.
> You want to id them and keep them no matter what.. I cant test this but try enabling cainid for all items and leave it as vampiregloves && rare?

Cain doesn't work

You have to edit it in the Pickit file, but there's no syntax (If that's the right word) for that.
Only if you add all the Prefix and Suffix that can spawn...but that's too much work

**Comment by DarkHorseDre** [comment]
ok - wel then do it in pickit.js & town.js maybe - I've modified pickit.js it in the past to handle runes and other items differently.  townjs seems to have some code for id'ing too, but I cant check it out 'anymo :)

**Comment by 5noop** [comment]
What about `[defense] > 0` ?

**Comment by DarkHorseDre** [comment]
zomg @5noop that works! I did that when I started! doh!

**Comment by drogga** [comment]
> 
> 
> What about `[defense] > 0` ?

I've tried that before

It doesn't identify the Item

**Comment by DarkHorseDre** [comment]
@drogga thats strange.  please paste your character config and the nip files referenced within to pastebin and share links here, ty.

**Comment by drogga** [comment]
https://pastebin.com/HQqqf0KM - Character Config

[Name] == HeavyBracers && [Quality] == Magic // Hit Power Gloves
[Name] == Vambraces && [Quality] == Magic // Hit Power Gloves

[Name] == WyrmhideBoots && [Quality] == Magic // Caster Boots

[Name] == VampirefangBelt && [Quality] == Magic // Caster Belt

[Name] == BattleBoots && [Quality] == Magic // Blood Boots

[Name] == VampireboneGloves && [Quality] == Magic // Blood Gloves

[Name] == MeshBelt && [Quality] == Magic // Blood Belt
[Name] == MithrilCoil && [Quality] == Magic // Blood Belt

I want the Bot to identify those Items without adding all kind of Magic Prefix/Suffixes that comes with it
Like I said..not a big deal, just want to know if it's possible

**Comment by DarkHorseDre** [comment]
It is possible, but something isnt right.

You didnt paste the nip - is the text in your post ALL of test.nip?


Changing the line to:
```[Name] == VampirefangBelt && [Quality] == Magic # [defense] > 0```
will force the bot to identify the item to verify the defense is > 0.  if it is not doing this, something is wrong with your setup.

**Comment by drogga** [comment]
> 
> 
> It is possible, but something isnt right.
> 
> You didnt paste the nip - is the text in your post ALL of test.nip?
> 
> Changing the line to:
> `[Name] == VampirefangBelt && [Quality] == Magic # [defense] > 0`
> will force the bot to identify the item to verify the defense is > 0. if it is not doing this, something is wrong with your setup.

Only keeps the Unid, doesn't identify it.
Just tried it
There's nothing wrong with my Config
It's just not possible I think

**Comment by DarkHorseDre** [comment]
:)
ok so tested it - problem is defense can be read before its id'd.. cant think of a stat which will be there but not read.. I tried ```[coldresist]+[fireresist]+[lightresist] >= 0``` and no joy.

**Comment by drogga** [comment]
Thanks for help

Closed
