### ISSUE TITLE
sorceress attack config question- static

### ISSUE THREAD

**Issue by ninojuice** [kolton/d2bot-with-kolbot#1213]
Hello, I wanted to know for solo Lead for light sorc, if I can configure it for sorceress to use static field first, then lightning after on bosses. 
Config.AttackSkill[0] = 40,57,58; // Preattack skill.
	Config.AttackSkill[1] = 49; // Primary skill to bosses.
	Config.AttackSkill[2] = 42; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 53; // Primary skill to others.
	Config.AttackSkill[4] = 49; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

**Comment by DarkHorseDre** [comment]
you can only set one skill per config.attack[] array section, so dont do it that way.

in your config, set this command - there are comments there to help:
Config.CastStatic = 60; // Cast static until the target is at designated life percent. 100 = disabled.
Config.StaticList = []; // List of monster NAMES or CLASSIDS to static. Example: Config.StaticList = ["Andariel", 243];

**Comment by ninojuice** [comment]
Thanks @DarkHorseDre problem solved .
