### ISSUE TITLE
CORE15 D2Bot.exe

### ISSUE THREAD

**Issue by cnbrkhancan** [kolton/d2bot-with-kolbot#122]
Contains Worm.Win32.Luder.ccwj.

Thank god auto deleted by my Kaspersky.

Last time I downloaded kolbot core (which was about 6-7 months ago) there were no problems.

Can you release a new core without trojans and worms in it?

Your great work is much appreciated

**Comment by kolton** [comment]
It's a false positive. Avast no longer tags it as malware after I sent the report. I'll look into reporting it to other AV programs that are tagging it.

**Comment by Tryey** [comment]
Having this issue with Bit Defender as well
