### ISSUE TITLE
Not hiding in the corner for wave 3 baal

### ISSUE THREAD

**Issue by wills219** [kolton/d2bot-with-kolbot#1220]
Could anyone help me figure out how to stop my hdin from teleporting to the corner on the hydra wave for baal. If anyone has a solution please help!

**Comment by DarkHorseDre** [comment]
At a quick glance the `baal.js` file seems to be where it checkshydra, and within that function it moves to a location:

```case 3:
Attack.clear(40);
this.checkHydra();

tick = getTickCount();

break;```

So test commenting out the `this.checkHydra();` line and I'm guessing it will stand there and get toasted by the hydras :D

**Comment by wills219** [comment]
Has anyone found a solution to this that caused the bot to not load script

**Comment by mf022** [comment]
the solution is in https://github.com/kolton/d2bot-with-kolbot/issues/1444#issuecomment-481813692
