### ISSUE TITLE
Window has unexpectedly exited... starting profile

### ISSUE THREAD

**Issue by MaximusDecimus** [kolton/d2bot-with-kolbot#123]
Hi

I'm having this error in D2Bot console. Game window is closed immediately after bot tries to create the game.

D2BS log below:

[06/10/15 11:35:04] D2BS 356: D2BS Engine startup complete.
[06/10/15 11:35:04] D2BS 356: My
[06/10/15 11:35:22] D2BS 356: Warden activity detected! Terminating Diablo to ensure your safety:)

Any help much appreciated.

**Comment by dzik87** [comment]
Do you try to run kolbot on private server ?

**Comment by MaximusDecimus** [comment]
Yes, I'm trying to run it on private server.

**Comment by dzik87** [comment]
no chances if warden is on

**Comment by MaximusDecimus** [comment]
Thanks dzik87.

So nothing can be done?

**Comment by dzik87** [comment]
actually. only if you find someone who modify and disable warden check in d2bs core

**Comment by MaximusDecimus** [comment]
Yea, I guess that will require someone familiar with d2bs. Do you know anybody who could help for good karma/beer?

**Comment by dzik87** [comment]
No I don't.
Actually I don't think it is a good idea to bot there, where warden is active. They ban you most probably as soon as possible.

**Comment by MaximusDecimus** [comment]
Ok, will try my luck on d2bs irc channel. Thanks!
