### ISSUE TITLE
Can't view character items

### ISSUE THREAD

**Issue by KevinBurris** [kolton/d2bot-with-kolbot#1237]
Hi, I was told by another user that you can see the items another character is using by hovering over their character in town. I, for the life of me, can not get this working and I don't know why. I've tried several different entry paths. Can anyone explain to me how this feature works? Thank you

**Comment by drogga** [comment]
Scripts.UserAddon = true; will show you the items

**Comment by KevinBurris** [comment]
Thank you drogga!
