### ISSUE TITLE
Remove the classid etc popup when paying manually?

### ISSUE THREAD

**Issue by master2g** [kolton/d2bot-with-kolbot#1238]
Hey I was wondering if there is a way to turn off that annoying popup that shows classid/ code / item level/ socketed with /  etc when hovering over items.  It's very annoying and gets in the way while I'm playing.

**Comment by 5noop** [comment]
When running UserAddon I guess ? You'll have to delete line 90 in UserAddon.js.

**Comment by master2g** [comment]
Got it thanks 5noop, SOLVED

**Comment by mcvk56** [comment]
hi,
if it solved close this issue :)
