### ISSUE TITLE
Error in Pickit

### ISSUE THREAD

**Issue by drogga** [kolton/d2bot-with-kolbot#1253]
Trying to pick up Widowmaker with +5 Guided Arrow
That's my line:
[Name] == WardBow && [Quality] == Unique # [PlusSkillGuideArrow] == 5 // Widowmaker

says Unknown stat: PlusSkillGuideArrow

Even tried with SkillGuideArrow

same error

What's the problem here ?

**Comment by 5noop** [comment]
It's Guided Arrow, you are missing a d. You better copy/paste directly the affixe name from NTItemAlias to avoid this kind of mistake.

**Comment by drogga** [comment]
Oh god I'm stupid

I checked ItemAlias like 10 times and didn't see the "d" ^^
