### ISSUE TITLE
MFhelper runs away on its own

### ISSUE THREAD

**Issue by Nerazapam** [kolton/d2bot-with-kolbot#1254]
Set up a leader and follower, both join the same game, join the same party, leader starts doing his run and the helper also starts running, but hitting different bosses. 
Set follower to TRUE, not sure why the helper keeps splitting off.

**Comment by DarkHorseDre** [comment]
He probably has boss scripts set - disable all boss scripts when running mfhelper.

follower should be disabled. it provides different featurs, as per the inline comments

**Comment by aim2kill** [comment]
Make sure followers scripts ate set to false act 1 thru act 5
As DarkHorseDre say you dont need follower set to true

**Comment by Nerazapam** [comment]
Wow yeah that was the problem, thanks for the solution guys. Left a few of the boss scripts set to true on the follower.
