### ISSUE TITLE
Need help to configure for two or more custom clear area and kill type

### ISSUE THREAD

**Issue by Fee920** [kolton/d2bot-with-kolbot#1256]
Please add more then 1  clear any area and kill type, there are some area that i want to do last only, due to character might chicken and i dont want bot to leave before other boss/area.  

What i want to have bot do clear any area, then do D/baal then go clear any area again such as Nihlathaks Temple/Worldstone all level/Throne Of Destruction. 

Also i want specific area to have different clear type.

Let me know if this is possible.

**Comment by 5noop** [comment]
The easiest way is probably to copy/paste ClearAnyArea.js et rename everything: the file name, the function inside and the config parameters in Config.js. For instance you can add '2' at the end so it will be ClearAnyArea2.js etc

Then you have to call it in your character file with Scripts.ClearAnyArea2, don't forget the config parameters.
Finally to set different clear type you can pass the property ClearType to the script, for instance if you want to clear all monsters in your 2nd script simply write this: `Scripts.ClearAnyArea2 = { ClearType: 0 };`
(more info about this on the wiki).

**Comment by Fee920** [comment]
This is what i change it to, and its erroring out.  The error from in game shows script is not define...... Error in character config

function **ClearAnyArea2**() {
	var i;

	Town.doChores();

	for (i = 0; i < Config.**ClearAnyArea2**.AreaList.length; i += 1) {
		if (Pather.journeyTo(Config.**ClearAnyArea2**.AreaList[i])) {
			Attack.clearLevel(Config.ClearType);
		}
	}

	return true;
}


In my character config file, i added,

	Scripts.ClearAnyArea2 = true;
		Config.ClearAnyArea2.AreaList = [107]
	Script.ClearAnyArea2 = {ClearType:0};


i also update the config.js and added 

	ChestMania: {
		Act1: [],
		Act2: [],
		Act3: [],
		Act4: [],
		Act5: []
	},
	ClearAnyArea: {
		AreaList: []
	},
	ClearAnyArea2: {
		AreaList: []
	},
	Rusher: {

**Comment by Fee920** [comment]
its erroring on this line of code 

Script.ClearAnyArea2 = {ClearType:0};

**Comment by Fee920** [comment]
I figure it out, thanks
