### ISSUE TITLE
MFHelper after DiabloHelper

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#1257]
Hey guys, another think...

i got MFHelper on true, then DiabloHelper, then BaalAssistant...
but after DiabloHelper, I will use MFHelper again for Pindel, Shenk etc....

	Scripts.MFHelper = true; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true
	Scripts.Wakka = false; // Walking chaos leecher with auto leader assignment, stays at safe distance from the leader
	Scripts.SealLeecher = false; // Enter safe portals to Chaos. Leader should run SealLeader.
	Scripts.DiabloHelper = true; // Chaos helper, kills monsters and doesn't open seals on its own.
		Config.DiabloHelper.Wait = 120; // Seconds to wait for a runner to be in Chaos. If Config.Leader is set, it will wait only for the leader.
		Config.DiabloHelper.Entrance = true; // Start from entrance. Set to false to start from star.
		Config.DiabloHelper.SkipTP = false; // Don't wait for town portal and directly head to chaos. It will clear monsters around chaos entrance and wait for the runner.
		Config.DiabloHelper.SkipIfBaal = true; // End script if there are party members in a Baal run.
	Scripts.MFHelper = true; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true

But after DiabloHelper its starting automatically BaalAssistant.

Any solution mby? :)

**Comment by crackedsash** [comment]
I would try this:
1: copy the mfhelperscript in bots folder and rename to mfhelper2
2. after diablohelper script add the line Scripts.MFHelper2 = true; (instead of script.mfhelper u have now)

If that doesnt work I think you might have to add something in config.js, but try it first;)

**Comment by DS1337** [comment]
ok i tested it, but this is not working :(

The Error after Diablo:

Error in MFHelper2 (loader.js line 132): Invalid script function name

In DiabloHelper:

	this.diabloPrep();
	Attack.kill(243); // Diablo
	Pickit.pickItems();

	return true;
}

Scripts.MFHelper2 = true;

In Config:

	Scripts.MFHelper = false; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true
	Scripts.Wakka = false; // Walking chaos leecher with auto leader assignment, stays at safe distance from the leader
	Scripts.SealLeecher = false; // Enter safe portals to Chaos. Leader should run SealLeader.
	Scripts.DiabloHelper = false; // Chaos helper, kills monsters and doesn't open seals on its own.
		Config.DiabloHelper.Wait = 120; // Seconds to wait for a runner to be in Chaos. If Config.Leader is set, it will wait only for the leader.
		Config.DiabloHelper.Entrance = true; // Start from entrance. Set to false to start from star.
		Config.DiabloHelper.SkipTP = false; // Don't wait for town portal and directly head to chaos. It will clear monsters around chaos entrance and wait for the runner.
		Config.DiabloHelper.SkipIfBaal = false; // End script if there are party members in a Baal run.
	Scripts.MFHelper2 = false; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true


Normally must working fine, ore not? :S 
What did i wrong? ^^

**Comment by crackedsash** [comment]
Error in MFHelper2 (loader.js line 132): Invalid script function name

Did you copy the mfhelper file in the bot folder? and rename to mfhelper2?

**Comment by crackedsash** [comment]
seems like you missunderstood... 

I would try this:
1: copy the mfhelperscript in bots folder and rename to mfhelper2
--> go to bots folder - make a copy of mfhelper, rename this file to mfhelper 2

2. after diablohelper script add the line Scripts.MFHelper2 = true; (instead of script.mfhelper u have now)
-- go in config, add line:
scripts.MFHelper2 = true; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true

**dont do it in In diablohelper like you did here under:**
 DiabloHelper:

```
this.diabloPrep();
Attack.kill(243); // Diablo
Pickit.pickItems();

return true;
```
}
Scripts.MFHelper2 = true;

sorry if its wasnt clear enough the first time

**Comment by aim2kill** [comment]
Just move the scripts from act 5 before the diablo/baal

**Comment by crackedsash** [comment]
> Just move the scripts from act 5 before the diablo/baal in your config

y or this;)

**Comment by DS1337** [comment]
I already did a copy of MFHelper in Bots folder, and yes, i renamed it to MFHelper2 :)

ok, i delete the "Scripts.MFHelper2 = true;" in DiabloHelper and try it again...

ore how aim2kill says...i just sort my Scripts...
But normally i dont like it...After Act 3, he will go act 5, then back to act 4, then again act 5...
not looking good lol :D

**Comment by aim2kill** [comment]
That the way I have it and work great

**Comment by crackedsash** [comment]
@ #982 

have a look here, got it to work with chestmania script (where i also had to add something in the common//config.js --> maybe you can do similar steps for mfhelper...

**Comment by DS1337** [comment]
Ok, i tryed it out now and is NOT working...

Create a copy of MFHelper.js and renamed it to MFHelper2.js and put it in Bots folder...
Then i add the line Scripts.MFHelper2 = true; in Char Config after DiabloHelper...

but same Error:

"Error in MFHelper2 (loader.js line 132): Invalid script function name"

I change now the order of the Scripts... :/

**Comment by crackedsash** [comment]
oooops, open mfhelper2.js in edit

edit this function (on top):
function MFHelper() { --->function MFHelper2() {

this should do the trick....

**Comment by DS1337** [comment]
Will try it later buddy, must going to work now :D

**Comment by DS1337** [comment]
> 
> 
> oooops, open mfhelper2.js in edit
> 
> edit this function (on top):
> function MFHelper() { --->function MFHelper2() {
> 
> this should do the trick....

Works perfect with this now! ty buddy! ;)

**Comment by casualBotter** [comment]
> > oooops, open mfhelper2.js in edit
> > edit this function (on top):
> > function MFHelper() { --->function MFHelper2() {
> > this should do the trick....
> 
> Works perfect with this now! ty buddy! ;)

Did it work from saving the file with the only changes being done being copying the file and renaming it or did you also change the function as suggested in this? I'm having the same issue at the moment
