### ISSUE TITLE
MFHelper Error: Attack.clear: 250 not found - Summoner Act 2

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#1259]
New one...

Title says...my MF Helper (soso) got an error on Act 2 @ Summoner...
"Error: Attack.clear: 250 not found"

she is not going in, in the TP and kill the Summoner with my Leader (for the MF).

Whats the Problem there?
I dont change something in the config ore else...

Any solution mby? :)

**Comment by aim2kill** [comment]
Does she try to walk to tp,when leader call it

**Comment by DarkHorseDre** [comment]
250 not found = means it didnt find the summoner, but youre saying it never entered the tp at all?

if so, has it ever entered in the past?  does it do this everytime?

**Comment by DS1337** [comment]
Yes, she walks to the TP Spot on Act 2, and no she never entered the tp befor...
Summoner still there after Leader do the TP, so she must go in mby...

**Comment by DarkHorseDre** [comment]
np - I asked as you can also get quest bugged so helper cant enter tp.

You problem happens a lot with the walk from act 1 to 2 - you can add a delay for the summoner script after the `Pather.useWaypoint(74);` or similar

**Comment by DS1337** [comment]
> 
> 
> np - I asked as you can also get quest bugged so helper cant enter tp.
> 
> You problem happens a lot with the walk from act 1 to 2 - you can add a delay for the summoner script after the `Pather.useWaypoint(74);` or similar

ya right, but summoner is not so important with the MFHelper Sorc :)
So nvm ^^

When the Leader is going from Act 2 to akt 3, the MFHelper is start moving to Act 3 too, dat i know...
But, is there a way, to skip the summoner/Duriel as MFHelper mby?
so after Andy, she will going/wait to act 3 and w8 there ore something else?
Skipping Act 2 and ignore it mby?

**Comment by DarkHorseDre** [comment]
ok so firstly, I meant moving from 2 to 3 takes a lot of time :) its the walk from portalspot to wp :(

>But, is there a way, to skip the summoner/Duriel as MFHelper mby?

mfhelper currently tracks the act that the leader is in and moves to it. I modified mine to only switch acts when the leader leaves town, not when in town (as it often goes to other act towns for pots)
You would need to modify the mfhelper script to goto act 3 town if leader is in act 2 areaid

An issue is that mfhelper script enters a tp THEN checks the areaid (and if leader is in same area) - so you'd have to get it to ignore act2 commands.. it gets messy at this point.
Maybe silence the leader when in act 2?  The leader uses the 'say' command in the attack.js so you could wrap an if around it (if areaid/summonerclassid then dont say a word) - with the mfhlper in act 3 it should work?  I havent thought this through fully :)

Heres the part of mfhelper which makes helpers move acts:
this.getPlayerAct = function (player) {
		if (player.area > 0 && player.area <= 39) {
			return 1;
		}

		if (player.area >= 40 && player.area <= 74) {
			return 2;
		}

		if (player.area >= 75 && player.area <= 102) {
			return 3;
		}

		if (player.area >= 103 && player.area <= 108) {
			return 4;
		}

		if (player.area >= 109) {
			return 5;
		}

		return false;
	};


remember: if they hear a command and theyre at the wrong portal spot, it could cause problems - better to silence the leader.

**Comment by DS1337** [comment]
Silencing the leader sounds logical.
I have also thought about removing the checking feature of Act 2 so that my MFHelper either waits Act 1 and then goes directly to Act 3. However, I'm unsure what to hire for it.

Simply removing this one will probably not help:

		if (player.area >= 40 && player.area <= 74) {
			return 2;
		}

And i found the "say" command in Attack.js, but what to do with it?

		if (Config.MFLeader) {
			Pather.makePortal();
			say("kill " + classId);

		if (Config.MFLeader && !!bossId) {
			Pather.makePortal();
			say("clear " + bossId);

Ore how to silent the bot, so he dont give commands like "Kill 250, Duriel..." etc. ?
But the problem with this is, it does not matter if he gives commands ore not, the MFHelper keep following in the Act, where the Leader is!
And when the Leader is outside of the Town but in act 2, the MFHelper still follow him to the same act, ore not?
U say, dat your MFHelper starting moving to the Leader-Act, after your Leader leaves the town.
But with silenting the bot, it doesn't matter if the bot say commands ore not, right?

Mby I will try to just delet the part and try it:

		if (player.area >= 40 && player.area <= 74) {
			return 2;
		}

if not, i dont know... :/

**Comment by DarkHorseDre** [comment]
I think if the helpers go to act 2, that's fine (except the time they take travelling)

silencing is best then

now, the attack.js is dynamic in that it is split between (from memory): attack single target, attack and clear target, clear area (e.g. mausoleum), and maybe one other.
it parses the mob or area id when doing so:
```say("kill " + classId);```
```say("clear " + bossId);```

what you want to is wrap an if in there to avoid the classids of act 2 bosses (found in the `monster classID's.txt` file)
e.g. (this code has not been checked!! its more psuedo)

var act2classestoavoid = ["Radamentclassid", "summonerclassid"];
if (Config.MFLeader) {
		Pather.makePortal();
                    if (!classid in act2classestoavoid) {
		          say("kill " + classId);
                     }
}
note that if you clear any areas in act 2, you will need to check areaid in a similar way.

changing act follow behaviour:
firstly, I changed mine to remove the areaids of the towns (1, 40 etc) - look at areaid.txt

	if (player.area > 1 && player.area <= 39) {
			return 1;
		}

		if (player.area > 40 && player.area <= 74) {
			return 2;
		}

		if (player.area > 75 && player.area <= 102) {
			return 3;
		}

		if (player.area > 103 && player.area <= 108) {
			return 4;
		}

		if (player.area > 109) {
			return 5;
		}

then for act to, just change "return 2" (tell it to goto act 2) to whichever act you want it to go to, to wait (1 or 3, right?)
