### ISSUE TITLE
AutoMule Error

### ISSUE THREAD

**Issue by JayChesney** [kolton/d2bot-with-kolbot#126]
Trying to set up autoMule for the first time 
Giving me an error message 
Error (105) Kolbot/Lib/automule Santax Error Missing after element list

**Comment by DetectiveSquirrel** [comment]
stopProfile: ""atlantaga" "Dasani" "Atlanta Zon" "GaAtlanta"",

can only have one profile name.

this is the only acceptable way of using this option.
 stopProfile: "atlantaga",

**Comment by JayChesney** [comment]
thank got that working now i made a new thread about my leechers
