### ISSUE TITLE
Error setting up follower/leecher

### ISSUE THREAD

**Issue by Snitzh** [kolton/d2bot-with-kolbot#1265]
I have tryed to setup a simple follower that can lvl up while my leader runs dia.
I get Errors as shown in the picture. WHat do i do wrong ??
Atm the leecher just joins the games and then do nothing.
![dia 2 error](https://user-images.githubusercontent.com/47917230/53285792-3dd36700-3765-11e9-8a65-b29a9148f2e8.png)

**Comment by DarkHorseDre** [comment]
It references "illegal character" and your character config.

You have a typo in your character config.
if you cant find it, paste the contents of your character config to pastebin.com and copy the link to that page to this thread

**Comment by Snitzh** [comment]
I Have no clue what i have set wrong :// 
Pasted entire config in this pastebin:
https://pastebin.com/Pe0LspnB

**Comment by Snitzh** [comment]
> It references "illegal character" and your character config.
> 
> You have a typo in your character config.
> if you cant find it, paste the contents of your character config to pastebin.com and copy the link to that page to this thread

I Have no clue what i have set wrong ://
Pasted entire config in this pastebin:
https://pastebin.com/Pe0LspnB

**Comment by drogga** [comment]
Config.Eldritch.KillDacFarren = ´false;

Remove ' and reload the script

**Comment by Snitzh** [comment]
> Config.Eldritch.KillDacFarren = ´false;
> 
> Remove ' and reload the script

This helped me out solving the first error thx. 
Now i need it to stop trying to reach anything by itself, and just wait for the leader to reach chaos and make a portal for her. Do u know what settings i have wrong here ?

**Comment by Snitzh** [comment]
It runs the script "diabloHelper" that i have now disabled. But how do i config so she joins game, wait for the leader to hit chaossancturary and then take hes portal and follows to get xp?

**Comment by drogga** [comment]
You have to enable it and use D2BotFollow.dbj as Entry Script

**Comment by Snitzh** [comment]
> You have to enable it and use D2BotFollow.dbj as Entry Script

I am using D2botfollow as entry script. What u mean by "you have to enable it" ?

**Comment by drogga** [comment]
Scripts.DiabloHelper = true;

**Comment by Snitzh** [comment]
> Scripts.DiabloHelper = true;

If i set that to enable my leecher tryes to reach chaos on her own as soon she joins battle, instead of waiting for portal from leader ?

**Comment by drogga** [comment]
Try Config.DiabloHelper.Wait = 120;

It's set to 10 on the Script you posted

maybe that's the problem

Post the actual Config and don't change anything

**Comment by Snitzh** [comment]
Seems my problem now is that they dont PP so they are in a party. The leechers leaves games after 1,5-2 min cause of this. My config are theese:
https://pastebin.com/xMzgUDgb

**Comment by drogga** [comment]
What's PP

**Comment by Snitzh** [comment]
They dont invite or accept party invites....

**Comment by drogga** [comment]
Did you edit Config.PublicMode for leechers
How many Bots do you run

**Comment by Snitzh** [comment]
I only have 1 leader thats working just fine. Now i wanna connect this random lvl 20 leecher so she can get some lvl up. If u mean the part in the char config file my settings are in the link above - guess u mean this right?
Config.LocalChat.Enabled = false; // enable the LocalChat system
	Config.LocalChat.Toggle = false; // optional, set to KEY value to toggle through modes 0, 1, 2
	Config.LocalChat.Mode = 1; // 0 = disabled, 1 = chat from 'say' (recommended), 2 = all chat (for manual play)
	// If Config.Leader is set, the bot will only accept invites from leader. If Config.PublicMode is not 0, Baal and Diablo script will open Town Portals.
	Config.PublicMode = 1; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable
	// Party message settings. Each setting represents an array of messages that will be randomly chosen.
	// $name, $level, $class and $killer are replaced by the player's name, level, class and killer
	Config.Greetings = []; // Example: ["Hello, $name (level $level $class)"]
	Config.DeathMessages = []; // Example: ["Watch out for that $killer, $name!"]
	Config.Congratulations = []; // Example: ["Congrats on level $level, $name!"]
	Config.ShitList = false; // Blacklist hostile players so they don't get invited to party.
	Config.UnpartyShitlisted = false; // Leave party if someone invited a blacklisted player.

**Comment by drogga** [comment]
Config.PublicMode = 1 with Main
Config.PublicMode = 2 with Leecher

should work

I thought you were using a Sorc to help you out with Chaos runs, that's why I said you need to enable DiabloHelper for the Sorc to join the Portal.

**Comment by Snitzh** [comment]
Still have the error that they dont party up. and leecher leaves after a period of time. 
What to do ? :S 

![d2 pp error](https://user-images.githubusercontent.com/47917230/53288391-80a63680-3787-11e9-83de-75e9e105a1de.png)

**Comment by Snitzh** [comment]
Both my setups are here, if anyone can fix the issue 👍 
https://pastebin.com/jZBsHFsF - Leader
https://pastebin.com/KQ9FiFDd - Leecher

**Comment by drogga** [comment]
sorry I had to leave for a few minutes
Did you try Config.PublicMode = 1 on both Characters before ?
I have the same settings, so I don't know why it's not working for you

**Comment by aim2kill** [comment]
They do party, I can see you pally in the screenshot

**Comment by Snitzh** [comment]
> They do party, I can see you pally in the screenshot. The problem is you pally is taking a long time to get to chaos do to pally doing others scripts and follower leave

They dont party. On the screenshot it just loads the scipt, it does not perform an accept, cause no invitations are given. So ur saying the kolbot scipt cant manage to just let the leecher wait for him to be done with other farming areas unless i set a delay timer on the leecher? :S

**Comment by aim2kill** [comment]
Why I see your pally in the party in the screenshot

**Comment by Snitzh** [comment]
> Why I see your pally in the party in the screenshot. Did you manually party?

Yes i can make the leecher follow if I manually party them up. But it does not work with being set to a party manually...

**Comment by Snitzh** [comment]
> Why I see your pally in the party in the screenshot. Did you manually party?

Yeah i have done it manually. if i do that, the leecher follows ok. But they dont party up without manually doing so. dunno what to solve it :S

**Comment by aim2kill** [comment]
K now you pally name That-Palla, make sure isnt that-Palla. Remember cap matter

**Comment by Snitzh** [comment]
> K now you pally name That-Palla, make sure isnt that-Palla. Remember case sensitive

Its "That_Pala" as put into the script. as far i can see everything is setup correctly but it just dont work.

**Comment by aim2kill** [comment]
On leader change Config.PublicMode = 1 to 3 see if helps

**Comment by Snitzh** [comment]
Allrdy tryed that .. Nothing changes. :/

**Comment by Snitzh** [comment]
> It references "illegal character" and your character config.
> 
> You have a typo in your character config.
> if you cant find it, paste the contents of your character config to pastebin.com and copy the link to that page to this thread

Perhaps i need u to take a look at this ? :S now ive gotten alot further, but still cant make the leader and leecher to party.  Any ideas?

**Comment by aim2kill** [comment]
Remove config.leader = ""  leave blank and wait for palla to get to chaos

**Comment by Snitzh** [comment]
That does not change anything. If not manually set to party they dont go party. My leecher says "no leader found" as the error before she go idle and eventually quit the game. Its like the connection from the leader towards the leecher is not being made.

**Comment by Snitzh** [comment]
> Remove config.leader = "" leave blank and wait for palla to get to chaos

That does not change anything. If not manually set to party they dont go party. My leecher says "no leader found" as the error before she go idle and eventually quit the game. Its like the connection from the leader towards the leecher is not being made.

**Comment by DarkHorseDre** [comment]
the code works fine, you have set something wrong. 

no leader found means it's not finding the profile or character name you specified with config.leader (if you set at all? )

I have not read your config but 8ensure you read the config comments correctly and set the leader name/profile name, case sensitive.

setting the public mode (leader profile set to invite, follower set to accept) and leader set correctly, all works well

**Comment by Snitzh** [comment]
> the code works fine, you have set something wrong.
> 
> no leader found means it's not finding the profile or character name you specified with config.leader (if you set at all? )
> 
> I have not read your config but 8ensure you read the config comments correctly and set the leader name/profile name, case sensitive.
> 
> setting the public mode (leader profile set to invite, follower set to accept) and leader set correctly, all works well

Beside the thing that the leader dont sent an invite to party when both join the game  - everything els works like a charm. If i  do it manually they do as scipted. Just cant get them in a party with manually attending.

**Comment by drogga** [comment]
Did you fix it ?

**Comment by drogga** [comment]
I tried your Configs on my Paladin & Sorceress
Config.Leader = "CharacterNameHere";
Config.PublicMode = 3; -> Main Bot
Config.PublicMode = 2; -> Leecher
and it works perfect for me.

You probably spelled your Main Character wrong...that's what I think

Make sure both Bots are running (don't pause)

If it's not gonna work, just delete the Leecher Config -> Start Profil to create a new Config and edit it again.

**Comment by Snitzh** [comment]
> I tried your Configs on my Paladin & Sorceress
> Config.Leader = "CharacterNameHere";
> Config.PublicMode = 3; -> Main Bot
> Config.PublicMode = 2; -> Leecher
> and it works perfect for me.
> 
> You probably spelled your Main Character wrong...that's what I think
> 
> Make sure both Bots are running (don't pause)
> 
> If it's not gonna work, just delete the Leecher Config -> Start Profil to create a new Config and edit it again.

Again and again have i checked that name to make sure it was not just a small error there, but i can ensure that it is spelled 100% as the ingame name shows. 
Guess the only solution is to delete the configs and start over -. somethings gotta be wrong. 
Thx all for helping.  Mass love <3

**Comment by Snitzh** [comment]
Update:
Didnt help to delete configs and set them up again.
My Leaders name is "That_Pala" - any know if its the underscore _ that coulud make the bug ?
Im gonna delete the rest of the configs to make sure its all unaffected from prev. changes.

**Comment by Snitzh** [comment]
Source found!!!
Was a wrong setup in the D2Botlead & D2Botfollow configs that caused the probs. 
Nothing was wrong in the char configs or with the name.
Thanks so much all who took of your time to help me in any way! Your the Best :) 

Snitzh.

**Comment by DarkHorseDre** [comment]
good to hear you got it sorted!

settings in follow and lead are for joining channels and games (and game delays) - what setting affected your chars ability to party AFTER joining game?

**Comment by Snitzh** [comment]
> good to hear you got it sorted!
> 
> settings in follow and lead are for joining channels and games (and game delays) - what setting affected your chars ability to party AFTER joining game?

Well seems that i had messed up the names in the "Join game settings" or the "var Joinsettings". I think this have been the prob, but it could be other place as well since i downloaded all files and started from fresh by setting everything up. Now my next question is  - can i run 1 leader and 2 leechers from same PC/ IP without getting "realms down" cause of two many joined games ? have avg runtime of 7 min per run with my current 1 leader and 1 leecher.

**Comment by DarkHorseDre** [comment]
yeah it wasn't the join settings - that determines if your followers will find and enter games hosted by leader.
Your problem was that they entered the game then didn't party - entry scripts don't handle in-game partying etc.

yes use join settings to allow 2 followers to join 1 leader - but set game time to be a minimum of 20 mins

set in char config:
Config.MinGameTime = 60; // Min game time in seconds. Bot will TP to town and stay in game if the run is completed before.
- good to keep just in case you change number and length of runs for a toon in future

set in follower entry:
CrashDelay: 5, // Seconds to wait after a d2 window crash
RealmDownDelay: 5, // Minutes to wait after getting Realm Down message

set in leader - minimum 5 mins between game creation in various scenarios:
MinGameTime: 300, // Minimum game length in seconds. If a game is ended too soon, the rest of the time is waited in the lobby
CreateGameDelay: 10, // Seconds to wait before creating a new game
CrashDelay: 25, // Seconds to wait after a d2 window crash
RealmDownDelay: 5, // Minutes to wait after getting Realm Down message

**Comment by aim2kill** [comment]
Since you redownload you fix whatever was wrong but wasnt the D2botlead or follower at all ,100% sure.
