### ISSUE TITLE
My Leader/Leecher wont party up.

### ISSUE THREAD

**Issue by Snitzh** [kolton/d2bot-with-kolbot#1266]
Leader works just fine, but the leecher times out after no party is performed. I want the leecher to wait for leader to reach chaosS and then leech Xp.
Both my setups are here, if anyone can fix the issue 👍
https://pastebin.com/jZBsHFsF - Leader
https://pastebin.com/KQ9FiFDd - Leecher

![d2 pp error](https://user-images.githubusercontent.com/47917230/53288622-b7ca1700-378a-11e9-921f-3dfa7af3a008.png)

**Comment by aim2kill** [comment]
They do party, I can see you pally in the screenshot. The problem is you pally is taking a long time to get to chaos do to pally doing others scripts and follower leave

**Comment by Snitzh** [comment]
They dont party. On the screenshot it just loads the scipt, it does not perform an accept, cause no invitations are given. So ur saying the kolbot scipt cant manage to just let the leecher wait for him to be done with other farming areas unless i set a delay timer on the leecher? :S

**Comment by Snitzh** [comment]
> They do party, I can see you pally in the screenshot. The problem is you pally is taking a long time to get to chaos do to pally doing others scripts and follower leave

They dont party. On the screenshot it just loads the scipt, it does not perform an accept, cause no invitations are given. So ur saying the kolbot scipt cant manage to just let the leecher wait for him to be done with other farming areas unless i set a delay timer on the leecher? :S

**Comment by crackedsash** [comment]
Try setting leaser to invite only (3)?

**Comment by Snitzh** [comment]
> Try setting leader to invite only (3)?

Tryed it all. 
That does not change anything. If not manually set to party they dont go party. My leecher says "no leader found" as the error before she go idle and eventually quit the game. Its like the connection from the leader towards the leecher is not being made.

**Comment by crackedsash** [comment]
Did u put leader in config?

**Comment by lordnakki** [comment]
I got it work myself when i checked lowercase alphabets on my config.leader, after i fixed my config.leaders name with uppercase alphabet it started to work.
