### ISSUE TITLE
control character in game

### ISSUE THREAD

**Issue by ninojuice** [kolton/d2bot-with-kolbot#1267]
Is it possible to take control of your character while bot is running its script? I guess simpler way to put it is "pause" what the bot is doing so I can take control.

**Comment by aim2kill** [comment]
`
	// Event functions
	this.keyEvent = function (key) {
		switch (key) {
		case 19: // Pause/Break key
			this.togglePause();

			break;
		case 123: // F12 key
			me.overhead("Revealing " + Pather.getAreaName(me.area));
			revealLevel(true);

			break;
		case 107: // Numpad +
			showConsole();`
Around line 350 in tooslthread

**Comment by ninojuice** [comment]
thanks!
