### ISSUE TITLE
disable identify between boss unless inventory is full?

### ISSUE THREAD

**Issue by Fee920** [kolton/d2bot-with-kolbot#1270]
I dont want bot to identify when there still room for next boss area.  Some examples is when doing Andy, and bot only pick up 1 ring, but have to stop by NPC to identify before going to next area.  By only have bot identify when inventory is full, can speed up the runs.  Let me know if this is possible or not.

**Comment by 5noop** [comment]
Go to town.js and add that at the start of the identify function:
```

**Comment by Fee920** [comment]
thanks, its working now.
