### ISSUE TITLE
Can you reload Config.Inventory without doing a .reload?

### ISSUE THREAD

**Issue by Fee920** [kolton/d2bot-with-kolbot#1272]
When adding charms to inventory, i dont want to perform the .reload, to reload the character configuration because the bot will start as if game just started, but some times, the bot is in the middle of a game.

Is there was to reload the Config.Inventory without reloading the whole character configuration?

**Comment by Zombenstein** [comment]
Well.   It restarts as if the game just started 'because' it reloads char config, getting the scripts again.

You could configure hotkeys to load a specific config setting, but I don't see it being very practical.

**Comment by Fee920** [comment]
how do i go about doing that?  If i can reload the Config.Inventory[0] to [3], then it should do the trick?

**Comment by DarkHorseDre** [comment]
What if you use autobuild and add the inventory entry there, then force that to be reloaded? (like it does when the toon levels up)?
I dont know how to do it but I'd look into autobuild to see how it is executed upon level up.. (I think it performs stat and skill point assignment in the middle of a game?)
