### ISSUE TITLE
Question on Follower chicken

### ISSUE THREAD

**Issue by Fee920** [kolton/d2bot-with-kolbot#1273]
I have 4 bots mfin one game.  1 bot is the lead, the other 3 is set to mf other area's.  Sometime one of the bot will chicken and will rejoin the game.  How can i disable rejoin if chicken and wait for next game?  FYI, i do not have MF helper enabler for any of the character configuration.

**Comment by 5noop** [comment]
What you could do is set in a min game time (in the entry script .dbj) that is roughly equivalent to your game duration.
