### ISSUE TITLE
need help disabling MFHelper making portal 

### ISSUE THREAD

**Issue by Fee920** [kolton/d2bot-with-kolbot#1275]
How to disable MFHelper from making portal at boss/areas?  MY MFHelper are MF their own area, and dont need them making TP to every boss/areas they are clearing

**Comment by 5noop** [comment]
Why are you using MFHelper in the first place ?

**Comment by Fee920** [comment]
I read somewhere that with MFHelper, if the bot chicken it will not rejoin same game, to prevent R/D.  I have 4 bots MFing 1 game, all different areas.

**Comment by aim2kill** [comment]
The bots wont rejoin the same game if they chicken, try setting you bot with setting if you dont have set yet.will save many chicken(I dont recomment it for HC)
Config.TownHP = 0; // Go to town if life is under designated percent

**Comment by Fee920** [comment]
This is my chicken settings.  How i have it configure is that, if life is below 50%, the bot should go to town to heal and chicken if below 35%.  Should i increase 50% to 70%?

	// Chicken settings
	Config.LifeChicken = 35; // Exit game if life is less or equal to designated percent.
	Config.ManaChicken = 0; // Exit game if mana is less or equal to designated percent.
	Config.MercChicken = 0; // Exit game if merc's life is less or equal to designated percent.
	Config.TownHP = 50; // Go to town if life is under designated percent.
	//Config.TownMP = 0; // Go to town if mana is under designated percent.

**Comment by DarkHorseDre** [comment]
I set mine to drink healpot at 80+%
drink rejuv if near 50%
then chicken if rejuv doesnt work

problem with goto town is that it can die/chicken if stuck getting into tp..

**Comment by Fee920** [comment]
This is my potion settings.  I stop using MFHelper and they are not mfing their own game, but still chicken once in a while due to souls/dolls

	// Potion settings
	Config.UseHP = 80; // Drink a healing potion if life is under designated percent.
	Config.UseRejuvHP = 65;  // Drink a rejuvenation potion if life is under designated percent.
	Config.UseMP = 30; // Drink a mana potion if mana is under designated percent.
	Config.UseRejuvMP = 10; // Drink a rejuvenation potion if mana is under designated percent.
	Config.UseMercHP = 70; // Give a healing potion to your merc if his/her life is under designated percent.
	Config.UseMercRejuv = 40; // Give a rejuvenation potion to your merc if his/her life is under designated percent.
	Config.HPBuffer = 0; // Number of healing potions to keep in inventory.
	Config.MPBuffer = 0; // Number of mana potions to keep in inventory.
	Config.RejuvBuffer = 1; // Number of rejuvenation potions to keep in inventory.
