### ISSUE TITLE
D2Bot crash

### ISSUE THREAD

**Issue by naeul99** [kolton/d2bot-with-kolbot#1277]
D2Bot is crashed after loggin a battle.net. A crach informaion is follow as.

### Application Error : 
오류 있는 응용 프로그램 이름: D2Bot.exe, 버전: 19.2.8.100, 타임스탬프: 0x5c5e744c
오류 있는 모듈 이름: KERNELBASE.dll, 버전: 10.0.17763.292, 타임스탬프: 0x02385dc9
예외 코드: 0xe0434352
오류 오프셋: 0x0011b022
오류 있는 프로세스 ID: 0x4590
오류 있는 응용 프로그램 시작 시간: 0x01d4cccc9bd7dc48
오류 있는 응용 프로그램 경로: D:\....\D2Bot.exe
오류 있는 모듈 경로: C:\WINDOWS\System32\KERNELBASE.dll
보고서 ID: a29bae92-c29b-4d66-b2cc-755b8e1fbf74
오류 있는 패키지 전체 이름: 
오류 있는 패키지에 상대적인 응용 프로그램 ID: 

### .NET Runtime Error : 
Application: D2Bot.exe
Framework Version: v4.0.30319
설명: Unhandled exception has occurred in your application
예외 정보:System.ComponentModel.Win32Exception
   위치: System.Diagnostics.ProcessManager.OpenProcess(Int32, Int32, Boolean)
   위치: System.Diagnostics.Process.GetProcessHandle(Int32, Boolean)
   위치: System.Diagnostics.Process.get_HasExited()
   위치: D2Bot.D2Profile.StopClient()
   위치: D2Bot.D2Profile.RestartClient(Boolean)
   위치: D2Bot.D2Profile+<>c__DisplayClass151_0.<Restart>b__0()
   위치: System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   위치: System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   위치: System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   위치: System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   위치: System.Threading.ThreadHelper.ThreadStart()

**Comment by aim2kill** [comment]
Maybe the language

**Comment by Snitzh** [comment]
> Maybe the language

hahahah

**Comment by noah-** [comment]
can you update your .net version and try again

**Comment by naeul99** [comment]
I solved this problem with windows 10 re-install..
My .net version is 4.7.2 that is included in windows 10.
Maybe after windows update, kernelbase.dll is not founded in D2BOT.

**Comment by noah-** [comment]
That’s very odd
