### ISSUE TITLE
D2BotFollow crashes on startup when join delay is configured

### ISSUE THREAD

**Issue by Jankelele** [kolton/d2bot-with-kolbot#1281]
This code causes the Profile executing D2BotFollow to crash at startup. When I comment out:

> "BicepsMF2": {JoinDelay: 6},
> 	"BicepsMF3": {JoinDelay: 9},
> 	"BicepsMF4: {JoinDelay: 3},
> 	"BicepsMF5": {JoinDelay: 6},
> 	"BicepsMF1": {JoinDelay: 3}

It works perfectly fine however I get RD eventually, because too many characters join/quit simultaneously I guess.

```
var JoinSettings = {
	"Janiuszko": ["BicepsMF1", "BicepsMF2", "BicepsMF3"],
	"BicepsPal": ["BicepsMF4", "BicepsMF5"]
};

// Advanced config - you don't have to edit this unless you need some of the features provided
var AdvancedConfig = {
	/* Features: Override join delay for each profile

	* Format *:
		"Profile Name": {JoinDelay: number_of_seconds}

	* Example * (don't edit this - it's just an example):
		"MyProfile1": {JoinDelay: 3},
		"MyProfile2": {JoinDelay: 6}
	*/

	// Put your lines under this one. Multiple entries are separated by commas. No comma after the last one.

"BicepsMF2": {JoinDelay: 6},
	"BicepsMF3": {JoinDelay: 9},
	"BicepsMF4: {JoinDelay: 3},
	"BicepsMF5": {JoinDelay: 6},
	"BicepsMF1": {JoinDelay: 3}
};
```

**Comment by DarkHorseDre** [comment]
I have simiar issues but didnt notice a crash caused by joindelay (only re-enabled recently).  Let me know how it goes

(I think quilist also causes issues...  @zombie created a quitdelay for this issue - I may have to copy that!)

**Comment by artashur** [comment]
"BicepsMF4: {JoinDelay: 3},
____________^____________
you miss a symbol  **"**
so it cause the crash

**Comment by Jankelele** [comment]
> "BicepsMF4: {JoinDelay: 3},
> ************^************
> you miss a symbol **"**
> so it cause the crash

Thank you for that. Seems to work fine indeed

**Comment by DarkHorseDre** [comment]
OK
