### ISSUE TITLE
disable option about fail to join reducer

### ISSUE THREAD

**Issue by mustaka1124** [kolton/d2bot-with-kolbot#1282]
currently there is a patch that reducing waiting time of creating a game.
i don't want the patch. it's too short for current asia server status.
could you make a option to disable the patch?
thank you.

**Comment by mustaka1124** [comment]
sorry i'm not sure where is better to post it on. :(

**Comment by DarkHorseDre** [comment]
not sure of the patch you refer to but create game delays are usually handled with a config parameter.

from the 'D2BotLead.dbj'
	CreateGameDelay: 10, // Seconds to wait before creating a new game

if the new file decreases this, then change it.

**Comment by SoongFish** [comment]
asia server, currently, needs least 10+ sec to create game but kolbot gives up in 3 sec and return FTJ. no longer FTJ Delay problem. we need how to make waiting in iron gate screen over 10+ sec :(

**Comment by DarkHorseDre** [comment]
did you try extending creategame delay as per my post above? Thats what you need to change.

you can try extending ftj just incase the game thinks its both/either one:
FTJDelay: 10, // Seconds to wait after failing to create a game

**Comment by mustaka1124** [comment]
nah... i solved this by recompiling d2bs :)

**Comment by SoongFish** [comment]
저도 주세오

**Comment by noah-** [comment]
noted, I will make this optional

**Comment by SoongFish** [comment]
thx :)
