### ISSUE TITLE
Wont join mule game

### ISSUE THREAD

**Issue by tarapice** [kolton/d2bot-with-kolbot#129]
So ive tried to figure this out, but it seems my sorce is not joining the mule game.

it says "Mule profile busy", and then goes on to doing mf runes instead of muling.

**Comment by ovaaj** [comment]
curious how u solved this? im having this problem :(

**Comment by tarapice** [comment]
That was a long time ago, but i belive it was something with a option being on or off, or both acount that dident have the other on friendlist.

I might sett up again. I will let u know
