### ISSUE TITLE
Problem checking scripts

### ISSUE THREAD

**Issue by ixrogue** [kolton/d2bot-with-kolbot#1293]
So I tried downloading the notepad++ and followed the steps on putting the nipchecker plugin. Only problem was that I downloaded the c++ and I don’t have the folder “API” to put the rest of the nip checker in.

Maybe it doesn’t come with one and I have to do something special? All this is new to me so any answer you can explain it like you’re explaining to your grandma will help me tremendously. There’s so many lines that pickit isn’t using causing my errors

**Comment by smacd2** [comment]
Had same issue. Can someone clarify this?
Is there a specific ++ version we need to use for plugin to work

**Comment by drogga** [comment]
Newest Version should have it

**Comment by ixrogue** [comment]
I downloaded the 7.6.3 (current version) on 32 bit and it still doesn’t show it. Do I have to create a new folder named API?

**Comment by ixrogue** [comment]
I found the answer.  Check notepad++ and find the updated installation and run it. The name is ‘GUP.exe’ that will give you the hidden update version and it’ll start working

**Comment by GodsHand86** [comment]
I'm having this problem. I've run the GUP.exe but all it does is say there's a new version, then download and install the same version.
