### ISSUE TITLE
Please force the mule profile making normal game.

### ISSUE THREAD

**Issue by artashur** [kolton/d2bot-with-kolbot#1305]
this is an automule issue.
some of my mule character aldready pass hell but not all.
there is a situation that my my character make a hell game when muling.
if the muleA make a hell game and pick item then muleA's bag is full.
the next character muleB maybe cant get in the game because that is a hell game.
sorry for my bad english.

by the way. i also found the rushee script had some problem.
if you set  Config.Rushee.Quester = false
when finishing duriel and order them to go to act3.  the bot just stuck because they won't talk to drognan so they can't take the protal to palace to talk to jerhym
they just stuck there and dont go to act3

**Comment by 5noop** [comment]
About your first problem you can modify D2BotMule.dbj by adding "Normal" as a 3rd argument to createGame at line 621 (if you use the last version), like this:
`createGame(muleObj.muleGameName[0], muleObj.muleGameName[1], "Normal");`

**Comment by artashur** [comment]
> About your first problem you can modify D2BotMule.dbj by adding "Normal" as a 3rd argument to createGame at line 621 (if you use the last version), like this:
> `createGame(muleObj.muleGameName[0], muleObj.muleGameName[1], "Normal");`

I really appreciate that. it helpful
