### ISSUE TITLE
keep getting "Invalid runewords entry: Superior Akaran Rondache"

### ISSUE THREAD

**Issue by Fee920** [kolton/d2bot-with-kolbot#1306]
Can you guys double check my code to make spirit shield?

07:32:17 (d6) Invalid runewords entry: Superior Akaran Rondache
07:32:17 (d6) Invalid runewords entry: Superior Sacred Targe
07:32:17 (d6) Invalid runewords entry: Superior Akaran Targe
07:32:18 (d6) Invalid runewords entry: Superior Akaran Rondache
07:32:18 (d6) Invalid runewords entry: Superior Sacred Targe
07:32:18 (d6) Invalid runewords entry: Superior Akaran Rondache
07:32:18 (d6) Invalid runewords entry: Superior Akaran Targe
07:32:18 (d6) Invalid runewords entry: Superior Sacred Targe
07:32:18 (d6) Invalid runewords entry: Superior Akaran Targe

	Config.Runewords.push([Runeword.Spirit, "Superior Akaran Rondache"]); // Make Spirit Akaran Rondache
	Config.Runewords.push([Runeword.Spirit, "Akaran Rondache"]); // Make Spirit Akaran Rondache
	Config.Runewords.push([Runeword.Spirit, "Kurast Shield"]); // Make Spirit Akaran Rondache
	Config.Runewords.push([Runeword.Spirit, "Sacred Rondache"]); // Make Spirit Akaran Rondache
	Config.Runewords.push([Runeword.Spirit, "Superior Sacred Targe"]); // Make Spirit Sacred Targe 
	Config.Runewords.push([Runeword.Spirit, "Sacred Targe"]); // Make Spirit Sacred Targe 
	Config.Runewords.push([Runeword.Spirit, "Superior Akaran Targe"]); // Make Spirit Akaran Targe
	Config.Runewords.push([Runeword.Spirit, "Akaran Targe"]); // Make Spirit Akaran Targe
	Config.KeepRunewords.push("[type] == shield || [type] == auricshields # [fcr] == 35");

**Comment by 5noop** [comment]
Don't write "superior" in the name
