### ISSUE TITLE
Leader not partied 

### ISSUE THREAD

**Issue by tarapice** [kolton/d2bot-with-kolbot#131]
wakka.js leader not partied line 250.

i get that when i trie to do walker script.

Ive been thru it alot of times and i cant find out why.

**Comment by WiZzMaN47** [comment]
in wakka.js do u have line 16 set correctly?
		leader = "D2CharNameHere";
i think its even case sensitive

**Comment by tarapice** [comment]
oh totaly dident see that. thanks! :+1:
