### ISSUE TITLE
D2bot in the cloud?

### ISSUE THREAD

**Issue by chanceplay** [kolton/d2bot-with-kolbot#1320]
I did a quick search and didn't see the answer. Is it possible to install D2BOT in the cloud (GoogleDrive, etc) or does it need to run locally?

I've been able to run it from the cloud, successfully, until tweaks were made to scripts and it crashed (Windows unexpected error, restarting profile). I just reinstall, and it works fine again. 

So just curious if it's suppose to be able to run in the cloud, or it's a bad idea. 

I prefer to run in the cloud so I can share files between my systems.

**Comment by DarkHorseDre** [comment]
Well installing it to a synced cloud location (google drive) isn't running in the cloud - I have my files on dropbox so I can access them remotely (but the exe runs on my pc ofc) and it works fine (the pc has a copy locally so the files are actually being ran locally.  I assume this is the same for google drive?)

**Comment by chanceplay** [comment]
You did not understand my questing. I'm talking about having the executables in the cloud, not just nip, etc files.

Thanks anyway.

**Comment by DarkHorseDre** [comment]
`question`.

You are not making yourself clear. I've covered what I imagine you mean, so why dont you elaborate? you've just repeated the same thing.  What do you mean by 'having the executables in the cloud'?
As I said I have the entire repo on dropbox so what exactly do you mean? 

express yourself clearly and you'll get your answer sooner.

**Comment by chanceplay** [comment]
The question is clear, otherwise I wouldn't repeat. Thanks anyway.
