### ISSUE TITLE
No process is associated with this object (exceptions.log)

### ISSUE THREAD

**Issue by cotimvp** [kolton/d2bot-with-kolbot#1322]
exceptions.log

09/03/2019 19:30
System.InvalidOperationException: Nenhum processo associado a este objeto. No process is associated with this object
   em System.Diagnostics.Process.EnsureState(State state)
   em System.Diagnostics.Process.EnsureState(State state)
   em System.Diagnostics.Process.get_MainWindowHandle()
   em D2Bot.D2Profile.ShowWindowThread()
   em D2Bot.Main.HandleAction(D2Profile d2p, ProfileAction pa)
   em D2Bot.Main.<>c__DisplayClass57_0.<WorkThread>b__0()

**Comment by drogga** [comment]
Download the newest version and see if that works

**Comment by cotimvp** [comment]
> Download the newest version and see if that works

I think that's the problem, I never had this issue with the prev version, now that I'm update i'm having this issue

**Comment by noah-** [comment]
make sure to redownload all files and not reuse old files
