### ISSUE TITLE
automule error

### ISSUE THREAD

**Issue by sspls1** [kolton/d2bot-with-kolbot#1327]
[error (22)] file(kolbot\libs\automule.js:176) TypeError: muleObj.stopProfile.toLowerCase is not a function
https://pastebin.com/YBsDmccm  automule,js
also my 1 of 5 bots dont want to mule with full inventory

**Comment by imbalanced** [comment]
stopProfile is just a string and it does not support array format.

**Comment by sspls1** [comment]
> stopProfile is just a string and it does not support array format.

thanks, got it.
and how can i mule 5 bot profiles with 5 keys?

**Comment by Blitz28** [comment]
you will have to make 2 bot profiles. it explains how to make a second in the link below. basicly you will have 4 bots in profile 1 and you will use bot 5 as the kill profile so the other 4 can mule and then in profile 2 you can make it just for that 1 bot and use a random one of the 4 as its kill profile for muling.

https://github.com/kolton/d2bot-with-kolbot/wiki/AutoMule-and-TorchMule

**Comment by Blitz28** [comment]
https://github.com/kolton/d2bot-with-kolbot/wiki/AutoMule-and-TorchMule#multiple-mules-and-multiple-realm-muling

**Comment by sspls1** [comment]
> https://github.com/kolton/d2bot-with-kolbot/wiki/AutoMule-and-TorchMule#multiple-mules-and-multiple-realm-muling

thanks a lot, got it and it helped^^
