### ISSUE TITLE
MF Helper not joining games

### ISSUE THREAD

**Issue by kputnam325** [kolton/d2bot-with-kolbot#1329]
My mfhelper sorc is not joining my leader's games. Both are added to friends lists in game. I set the channel for both to join (this works) and set the leader as in game leader in both char configs. The d2bs profiles are both set in D2botfollow file. Not sure what I'm missing here. Follow/mfhelp works correctly. Only issue is it will not join the game.

Leader Char Config: https://pastebin.com/6Y9uDx5Q
Follower Char Config: https://pastebin.com/PxvJ5349
D2BotLead: https://pastebin.com/Vi600mqG
D2BotFollow: https://pastebin.com/SJGY082d

Any help would be appreciated!

**Comment by DarkHorseDre** [comment]
who is "MF Hammerdin" (joinsettings) vs I_PoopHammers (Config.Leader, quitlist) ? 

200FCR Sorc must be the name of the profile name of the follower sorc

Youve also set I_PoopHammers as config.leader for the leader - prob take that out

The game joining is not controlled by char config so ensure the profile/char names in follow entry script are correct - may be case sensitive too.

if you only have 1 leader, I just put a catchall:
var JoinSettings = {
	"leaderprofile": ["all"]
};

I also set char and profiles names to be the same so I never have to think about it

**Comment by kputnam325** [comment]
> if you only have 1 leader, I just put a catchall:
var JoinSettings = {
"leaderprofile": ["all"]
};

> I also set char and profiles names to be the same so I never have to think about it

These two changes fixed everything! Making the chars and profiles the same name was a pretty good idea.

**Comment by DarkHorseDre** [comment]
Glad you got it sorted bro.  Just remember that you have the catchall set - guaranteed you will forget if you ever try to run more than 1 leader and you'll wonder why they keep joining the wrong game xD

**Comment by kputnam325** [comment]
> 
> 
> Glad you got it sorted bro. Just remember that you have the catchall set - guaranteed you will forget if you ever try to run more than 1 leader and you'll wonder why they keep joining the wrong game xD

Ha! I bet I wont forget now!

Thanks man
