### ISSUE TITLE
attack.js line 214

### ISSUE THREAD

**Issue by flyrom99** [kolton/d2bot-with-kolbot#133]
Every time the bot goes on to kill a boss, it says error in attack.js line 214

![image](https://cloud.githubusercontent.com/assets/11250934/12222716/761632c4-b792-11e5-83d0-34f698e8e2d1.png)

**Comment by mboufos** [comment]
did you put the attacks on char config ? or attacks are -1 to all :P

**Comment by flyrom99** [comment]
I just used a friend's script and got it sorted out. Thanks, though
