### ISSUE TITLE
pickit

### ISSUE THREAD

**Issue by si0keeeee** [kolton/d2bot-with-kolbot#1340]
Looking for good pickit with rare items , blue good items , scs and gc

some one can help me pasting good one pickit to not use kolbot plz??

thanks in advance

**Comment by DarkHorseDre** [comment]
https://darcvigilante.site/showthread.php?tid=9

**Comment by si0keeeee** [comment]
thanks for help :dagger: 
u use ursell or some that u linked?

**Comment by DarkHorseDre** [comment]
No I have created mine from the original kolton.nip which has taken a long time but would have been easier to use one of these.

also I do not look for perfect items as I dont mind using lesser items until the perfect arrives
(e.g. if min ED is 100 and perfect ED is 200, I will take 100 and then update pickit to 190+)
