### ISSUE TITLE
Diablo2 not starting when starting bot.

### ISSUE THREAD

**Issue by oband2** [kolton/d2bot-with-kolbot#1341]
Made a few changes regarding installing d2, and suddenly im getting this fault:
Window has unexpectedly exited... starting profile

Bot is not opening d2, what did i do different? Game path seems to be fine.

**Comment by noah-** [comment]
follow install guide, don't use any compatibility modes

**Comment by oband2** [comment]
guess i deleted something in one of the configs.
reinstalled and working
