### ISSUE TITLE
is there a fresh copy of d2botlead i can download' think i messed mine up somehow dont create games

### ISSUE THREAD

**Issue by lew130** [kolton/d2bot-with-kolbot#1342]

**Comment by DarkHorseDre** [comment]
All the code is hosted on this site.  If you use svn you can re download using the context menu, or manually download from the code tab: https://github.com/kolton/d2bot-with-kolbot/tree/master/d2bs/kolbot

**Comment by lew130** [comment]
thx i redid whole thing
