### ISSUE TITLE
Leader Crash and Followers Stand around

### ISSUE THREAD

**Issue by Damaven** [kolton/d2bot-with-kolbot#1344]
Hey guys,

Sometimes my leader crashes for some random reason and my two followers just stand there and don't do anything. My leader then goes on to the next game and continues the MF run while my two followers are still standing around in the previous game.

Is there a way to fix this?  Maybe have the followers exit the game if the leader exits or crashes for whatever reason.

Thanks in advance!

**Comment by DarkHorseDre** [comment]
I had this - did you set Config.QuitList in followers?

in d2bs set the response time to lower amount

I still get these so if it still happens after that, I'm not sure

**Comment by Damaven** [comment]
Dude,

thank you. it works. I totally overlooked that quitlist feature. thanks!
