### ISSUE TITLE
Followers help clear worldstone

### ISSUE THREAD

**Issue by Damaven** [kolton/d2bot-with-kolbot#1346]
How do you get your followers to help clear Nith and Worldstone?? Thanks in advance.

**Comment by DarkHorseDre** [comment]
You will see baalhelper and baalassistant/chaos assistant scripts referenced and commented in the character configs - they can assist in killing or for nihi can kill for you.

mfhelper will make followers assist in killing bosses

**Comment by Damaven** [comment]
Basically im just looking for the followers to clear worldstone the same way they clear pits or tunnels, etc.

**Comment by DarkHorseDre** [comment]
ok so what I wrote helps you with that bro

**Comment by Damaven** [comment]
So I need to add the worldstone to the baalassist?

Any idea how it should look?

**Comment by DarkHorseDre** [comment]
read the notes on baal assistance and baal/diablo helper - if it does what you want, enable it

**Comment by Damaven** [comment]
I found this previous reply you posted on another thread,
"wait, do you just want the team to clear worldstone as they do say mausoleum? (I cant remember how they do cs - thought it was multiple tps per seal?)
if so, change the command the mfleader gives in worldstone. if something else let me know, but I think it will be easy if you just want the mfhelpers to clear an area in the same way as another script (mfhelper recognises kill, clear and a few other commands)"

I guess my question is, how do I change or add the command my mfleader gives to the followers in order for them to help clear worldstone instead of standing and just waiting for the Throne TP.

**Comment by DarkHorseDre** [comment]
more to the point, why wont you let the standard functionality do the job?
i.e. mf helper until cs and baal, then followers run the cs/baal helpers and actually help clear them?

if you want to change what leader 'says' then its in attack.js

You then have to add code to mfhelper to `switch` or process the the new command
