### ISSUE TITLE
singleplayer /p8?

### ISSUE THREAD

**Issue by oband2** [kolton/d2bot-with-kolbot#1352]
This is prolly rare, but since i have some queue time i want to try my bot in singleplayer, however i have a hard time figuring out how i make it say /players 8 at the start of the game to get most drops. I could do it manually, but after each crash and restart of d2 it would be reset to p1,

I tried with the quitmessage, in this case i would do one p1 run after a crash, and then p8, but it doesnt seem to say it.
Config.LastMessage = "/players 8"; // Message or array of messages to say at the end of the run.

What else could i do?

**Comment by noah-** [comment]
add say("/players 8");
in default.dbj would work

**Comment by oband2** [comment]
> add say("/players 8");
> in default.dbj would work

that worked, thanks!
