### ISSUE TITLE
can only run 1 bot automatically

### ISSUE THREAD

**Issue by lew130** [kolton/d2bot-with-kolbot#1355]
I can run 1 bot all night no problem I can add other bots manually no prob. if i stop others and then add after first starts no problem.
if i start all 3 first time will work 2nd time the leader will never create the game while the other 2 are running any ideas Help
Lewie

**Comment by oband2** [comment]
Are u running chars from same account? or same cdkey?

**Comment by lew130** [comment]
same account different cdkeys
ah you cant do from same account?

**Comment by lew130** [comment]
is that true i cant run 2 from same account

**Comment by oband2** [comment]
well, u can, but.... if they ever meet at same time in the channel, or the lobby where u join game, they will disconnect eachother.
thats why u should only do 1 bot pr account.
maybe u could do like min time + max time both same amount of time, like 10 minuts, and then u start the bot with 5 minuts difference, then there should be limited chance that they would meet in lobby unless crash etc. so the bot will be in game for exactly 10 minuts both of them

**Comment by lew130** [comment]
thx i am redoing them
