### ISSUE TITLE
Follower Issue

### ISSUE THREAD

**Issue by Damaven** [kolton/d2bot-with-kolbot#1362]
Okay,

My followers follow my leader no issue there.

BUT once my leader gets to Act4 and DiabloHelper is done, my followers jump to BaalHelper.  They no longer follow my leader but instead wait for my leader to send a Throne TP.

They wont follow my Leader to clear Worldstone but just wait for that throne TP and begin BaalHelper.

How do I get my followers to help clear worldstone BEFORE running Baalhelper?

Thanks in advance.

**Comment by oband2** [comment]
would suggest u make your leechers run wolrdstone script aswell. not sure how its done otherwise.

**Comment by Damaven** [comment]
Tried that.

When I set my followers to run the worldstone script, they do so... but before they run DiabloHealper causing my leader to clear Diablo by himself while my followers are doing Worldstone.

**Comment by 5noop** [comment]
When your leader starts diablo the script MfHelper will stop so your leecher can run Diablohelper, after that MfHelper won't restart. An easy solution would be to clear Worldstone before going to diablo.

**Comment by oband2** [comment]
Yes, because scripts starts in the order, from top to bottom, copy paste the worldstone scripts and place it under the diablo script in leechings settings. should help.

**Comment by Damaven** [comment]
Dude....

it worked. lmao

I just cut/pasted the worldstone script b4 diablo.  I love you guys. lol

ty
