### ISSUE TITLE
Bot not cubing my pul runes.

### ISSUE THREAD

**Issue by oband2** [kolton/d2bot-with-kolbot#1364]
Got these settings, but my bot dont like to cube the any runes, why not? got enough lem, pul, gul and sur runes to cube into an upgrade, what is wrong? i shouldnt tell it to pickup gems, right? it should do automatic. I just saw it skipped a flawed emerald which is used to cube lems.
	Config.Cubing = true; // Set to true to enable cubing.

	// Ingredients for the following recipes will be auto-picked, for classids check libs/NTItemAlias.dbl

	//Config.Recipes.push([Recipe.Gem, "Flawless Amethyst"]); // Make Perfect Amethyst
	//Config.Recipes.push([Recipe.Gem, "Flawless Topaz"]); // Make Perfect Topaz
	//Config.Recipes.push([Recipe.Gem, "Flawless Sapphire"]); // Make Perfect Sapphire
	//Config.Recipes.push([Recipe.Gem, "Flawless Emerald"]); // Make Perfect Emerald
	//Config.Recipes.push([Recipe.Gem, "Flawless Ruby"]); // Make Perfect Ruby
	//Config.Recipes.push([Recipe.Gem, "Flawless Diamond"]); // Make Perfect Diamond
	//Config.Recipes.push([Recipe.Gem, "Flawless Skull"]); // Make Perfect Skull

	//Config.Recipes.push([Recipe.Token]); // Make Token of Absolution
	Config.Recipes.push([Recipe.Rune, "Lem Rune"]); // Upgrade Lem to Pul
	Config.Recipes.push([Recipe.Rune, "Pul Rune"]); // Upgrade Pul to Um
	Config.Recipes.push([Recipe.Rune, "Um Rune"]); // Upgrade Um to Mal
	//Config.Recipes.push([Recipe.Rune, "Mal Rune"]); // Upgrade Mal to Ist
	//Config.Recipes.push([Recipe.Rune, "Ist Rune"]); // Upgrade Ist to Gul
	Config.Recipes.push([Recipe.Rune, "Gul Rune"]); // Upgrade Gul to Vex
	Config.Recipes.push([Recipe.Rune, "Sur Rune"]); // Upgrade Sur to Ber

Pick it:
[name] >= pulrune && [name] <= zodrune

**Comment by JohnnyMakeBeliever** [comment]
Is this single player?

**Comment by oband2** [comment]
> Is this single player?

Oh yes, cubing in singleplayer not possible?

**Comment by drogga** [comment]
Line looks fine. Make sure you enabled Cubing
I don't play Single Player..but I don't see why it wouldn't work there
The Bot will collect the Gem when he has at least 2 of the same rune in the Chest

**Comment by JohnnyMakeBeliever** [comment]
The script checks if you're ladder

**Comment by oband2** [comment]
> The script checks if you're ladder

but not if im singleplayer? :D

**Comment by aim2kill** [comment]
You need mod cubing.js and remove this line
if (me.ladder) {

break;
				case 623: // dol->hel
					if (me.ladder) {
						this.recipes.push({Ingredients: [623, 623, 623, 572], Index: Recipe.Rune});
					}
