### ISSUE TITLE
Failed to include baalhelper script.

### ISSUE THREAD

**Issue by oband2** [kolton/d2bot-with-kolbot#1366]
After trying to edit too mange things i fucked something up, dunno what exactly, im getting this error:
https://gyazo.com/6cf2921e6899f55829fc463f7a6850da
failed to include baalhelper and something with pather.js.
Tried to overwrite pather.js from scratch but doesnt seem to work

**Comment by oband2** [comment]
nvm fixed.

**Comment by diablo2fan** [comment]
Baalhelper works for public games? I’m trying to set my bot up to join public games for levels - but... are having a hard time with it. 😳

**Comment by oband2** [comment]
Seems to only work for private, if i do it public, it doesnt wait for safe tp, it just goes into hot tp and rushes to leech spot without throne being clear :D

**Comment by drogga** [comment]
You have to setup BaalAssistant for that.

It works fine.

**Comment by diablo2fan** [comment]
Drogga

Is baalassistant the only thing i need to edit? In order for the bot to join other peoples public baalruns? 

I’ve tried to set it up a couple of times without luck. My char joins the runs, accept the invite and then just stands in town. 

Do i need to edit anything in follower, Channel etc?

**Comment by oband2** [comment]
> You have to setup BaalAssistant for that.
> 
> It works fine.

Yes, but if u use baalassistent, leecher wont go to baal in chamber, he just leaves after wave 5, even tho its set to true and baal message is the same, dunno why.
