### ISSUE TITLE
06:22:15 (Paladin hftz)  Error in KillDclone (attack.js #229) Attack.kill: Target not found (Area: 54, Ping:312, Game: Hft50)

### ISSUE THREAD

**Issue by arcangeli** [kolton/d2bot-with-kolbot#1370]
iso help i think its due of my dclone search ??

took annilhus off and put d2clone to true

wut i do wrong ?

is this only cuz he dint find dclone ?

**Comment by DarkHorseDre** [comment]
yes, disable that setting and only enable 
Config.StopOnDClone = true; // Go to town and idle as soon as Diablo walks the Earth
	Config.SoJWaitTime = 5; // Time in minutes to wait for another SoJ sale before leaving game. 0 = disabled

set desired values for wait

**Comment by arcangeli** [comment]
is this good

Scripts.KillDclone = false; // Kill Diablo Clone by using Arcane Sanctuary waypoint. Diablo needs to walk the Earth in the game

// DClone config
	Config.StopOnDClone = true; // Go to town and idle as soon as Diablo walks the Earth
	Config.SoJWaitTime = 5; // Time in minutes to wait for another SoJ sale before leaving game. 0 = disabled
	Config.KillDclone = false; // Go to Palace Cellar 3 and try to kill Diablo Clone. Pointless if you already have Annihilus.
	Config.DCloneQuit = false; // 1 = quit when Diablo walks, 2 = quit on soj sales, 0 = disabled
