### ISSUE TITLE
06:22:15 (Paladin hftz) Error in KillDclone (attack.js #229) Attack.kill: Target not found (Area: 54, Ping:312, Game: Hft50) #1370

### ISSUE THREAD

**Issue by arcangeli** [kolton/d2bot-with-kolbot#1371]
this for dclone annilhus

dint get reply on my 2nd post last thread so I made it like this same title

is this good
Scripts.KillDclone = false; // Kill Diablo Clone by using Arcane Sanctuary waypoint. Diablo needs to walk the Earth in the game
// DClone config
Config.StopOnDClone = true; // Go to town and idle as soon as Diablo walks the Earth
Config.SoJWaitTime = 5; // Time in minutes to wait for another SoJ sale before leaving game. 0 = disabled
Config.KillDclone = false; // Go to Palace Cellar 3 and try to kill Diablo Clone. Pointless if you already have Annihilus.
Config.DCloneQuit = false; // 1 = quit when Diablo walks, 2 = quit on soj sales, 0 = disabled

**Comment by DarkHorseDre** [comment]
You can set this:

Scripts.KillDclone = false; // Kill Diablo Clone by using Arcane Sanctuary waypoint. Diablo needs to walk the Earth in the game
// DClone config
Config.StopOnDClone = true; // Go to town and idle as soon as Diablo walks the Earth
Config.SoJWaitTime = 5; // Time in minutes to wait for another SoJ sale before leaving game. 0 = disabled
Config.KillDclone = true; // Go to Palace Cellar 3 and try to kill Diablo Clone. Pointless if you already have Annihilus.
Config.DCloneQuit = false; 

Now please close all your issues and don't duplicate them in future
