### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by Badcraft80** [kolton/d2bot-with-kolbot#138]
OK im new here and im just now start use the kolbot!
I want run lead/leech bots ... I have 2 pc at home and 2 cd key and have a high lvl sorc and a lowlvl pala.
I try following the instructions, but dont work :( the leechbot stay in the channel lobby!
(ps.: can i make these lead/leech runs on 1 pc? ... how?)

**Comment by mboufos** [comment]
check the wiki :P  and youtube :P
