### ISSUE TITLE
Baalassistance char is stupid.

### ISSUE THREAD

**Issue by oband2** [kolton/d2bot-with-kolbot#1383]
I have a issue with having my leechers completing a baalrun.

If i use Autobaal they take first tp and is at risk, they will then complete baalrun and leech the baalkill, but if i use Baalassistance, the leecher will take the safe tp, but will either quit after wave 5, or go to baal chamber but quit before baal is dead.

What i want is:
Find xp shrine (does fine on both scripts)
Take safe tp
Leech 5 waves
Go to baalchamber and complete baalkill before quit.

what is wrong with my script?

https://pastebin.com/EJQ3286n Leechers
https://pastebin.com/zQhsCxuq Leader

**Comment by Kosoleld** [comment]
safeMsg = ["safe", "throne clear", "leechers can come", "tp is up", "1 clear"], // safe message - casing doesn't matter
		baalMsg = ["baal"], // baal message - casing doesn't matter
		hotMsg = ["hot", "warm", "dangerous", "lethal"]; // used for shrine hunt

You cannot use "tp is up" for hot it's part of the list for safe msg. Make sure they are compatible.

**Comment by oband2** [comment]
Solved ty Kosoleld!
Didnt know that if hot tp message had a part of the safe message in it, it would react on that.
So if i had "Tp is up!! but dont come yet" it will react on "tp is up" and thinks its safe. t4i!
