### ISSUE TITLE
19.3.23.100 crash

### ISSUE THREAD

**Issue by sangami70** [kolton/d2bot-with-kolbot#1388]
Yesterday bot running is find （more than 10 hour）

But it’s crashed many time today...

Someone help me

**Comment by noah-** [comment]
Did you update via autoupdate recently?

**Comment by sangami70** [comment]
> Did you update via autoupdate recently?

yes, it is.

i redownload 19.3.23.100 pack 

it happen again ( same problem?)
01:27:36 (LOKImf2) Window has unexpectedly exited... starting profile
01:27:39 (LOKImf2) Crash Info: Script: Pindleskin Area: The Pandemonium Fortress
01:28:46 (LOKImf2) D2BS is not responding... starting profile
01:28:50 (LOKImf2) Crash Info: Script: none Area: out of game
01:29:57 (LOKImf2) D2BS is not responding... starting profile
01:30:01 (LOKImf2) Crash Info: Script: none Area: out of game
01:31:07 (LOKImf2) D2BS is not responding... starting profile
01:31:11 (LOKImf2) Crash Info: Script: none Area: out of game
01:32:18 (LOKImf2) D2BS is not responding... starting profile
01:32:22 (LOKImf2) Crash Info: Script: none Area: out of game
01:33:28 (LOKImf2) D2BS is not responding... starting profile
01:33:32 (LOKImf2) Crash Info: Script: none Area: out of game
01:34:39 (LOKImf2) D2BS is not responding... starting profile
01:34:43 (LOKImf2) Crash Info: Script: none Area: out of game
01:35:50 (LOKImf2) D2BS is not responding... starting profile
01:35:54 (LOKImf2) Crash Info: Script: none Area: out of game
01:37:00 (LOKImf2) D2BS is not responding... starting profile
01:37:05 (LOKImf2) Crash Info: Script: none Area: out of game
01:38:11 (LOKImf2) D2BS is not responding... starting profile
01:38:15 (LOKImf2) Crash Info: Script: none Area: out of game
01:39:22 (LOKImf2) D2BS is not responding... starting profile
01:39:26 (LOKImf2) Crash Info: Script: none Area: out of game
01:40:33 (LOKImf2) D2BS is not responding... starting profile
01:40:37 (LOKImf2) Crash Info: Script: none Area: out of game
01:41:43 (LOKImf2) D2BS is not responding... starting profile
01:41:47 (LOKImf2) Crash Info: Script: none Area: out of game
01:42:54 (LOKImf2) D2BS is not responding... starting profile
01:42:58 (LOKImf2) Crash Info: Script: none Area: out of game
01:44:05 (LOKImf2) D2BS is not responding... starting profile
01:44:09 (LOKImf2) Crash Info: Script: none Area: out of game
01:45:15 (LOKImf2) D2BS is not responding... starting profile
01:45:19 (LOKImf2) Crash Info: Script: none Area: out of game
01:46:26 (LOKImf2) D2BS is not responding... starting profile
01:46:30 (LOKImf2) Crash Info: Script: none Area: out of game
01:47:27 (LOKImf1) [Game: Yukimf152//Yuki666 (19:22)] [Level: 95 (50.59%)] [XP: 651886] [Games ETA: 170]
01:47:27 (LOKImf3) [Game: Yukimf152//Yuki666 (19:17)] [Level: 94 (21.81%)] [XP: 1389466] [Games ETA: 116]
01:47:37 (LOKImf2) D2BS is not responding... starting profile
01:47:41 (LOKImf2) Crash Info: Script: none Area: out of game
01:48:48 (LOKImf2) D2BS is not responding... starting profile
01:48:52 (LOKImf2) Crash Info: Script: none Area: out of game
01:49:47 (LOKImf1)  Error in Summoner (attack.js #435) Attack.clear: 250 not found (Area: 74, Ping:218, Game: Yukimf153)
01:49:58 (LOKImf2) D2BS is not responding... starting profile
01:50:02 (LOKImf2) Crash Info: Script: none Area: out of game
01:51:09 (LOKImf2) D2BS is not responding... starting profile
01:51:13 (LOKImf2) Crash Info: Script: none Area: out of game
01:52:19 (LOKImf2) D2BS is not responding... starting profile
01:52:23 (LOKImf2) Crash Info: Script: none Area: out of game
01:53:30 (LOKImf2) D2BS is not responding... starting profile
01:53:34 (LOKImf2) Crash Info: Script: none Area: out of game
01:54:41 (LOKImf2) D2BS is not responding... starting profile
01:54:45 (LOKImf2) Crash Info: Script: none Area: out of game
01:55:51 (LOKImf2) D2BS is not responding... starting profile
01:55:55 (LOKImf2) Crash Info: Script: none Area: out of game
01:57:02 (LOKImf2) D2BS is not responding... starting profile
01:57:06 (LOKImf2) Crash Info: Script: none Area: out of game
01:58:13 (LOKImf2) D2BS is not responding... starting profile
01:58:17 (LOKImf2) Crash Info: Script: none Area: out of game
01:59:23 (LOKImf2) D2BS is not responding... starting profile
01:59:27 (LOKImf2) Crash Info: Script: none Area: out of game
02:00:34 (LOKImf2) D2BS is not responding... starting profile
02:00:38 (LOKImf2) Crash Info: Script: none Area: out of game
02:01:45 (LOKImf2) D2BS is not responding... starting profile
02:01:49 (LOKImf2) Crash Info: Script: none Area: out of game
02:02:55 (LOKImf2) D2BS is not responding... starting profile
02:02:59 (LOKImf2) Crash Info: Script: none Area: out of game
02:04:06 (LOKImf2) D2BS is not responding... starting profile
02:04:10 (LOKImf2) Crash Info: Script: none Area: out of game
02:04:50 (LOKImf1) [Game: Yukimf153//Yuki666 (17:08)] [Level: 95 (50.85%)] [XP: 525652] [Games ETA: 210]
02:04:50 (LOKImf3) [Game: Yukimf153//Yuki666 (17:03)] [Level: 94 (22.33%)] [XP: 1079091] [Games ETA: 148]
02:05:16 (LOKImf2) D2BS is not responding... starting profile
02:05:21 (LOKImf2) Crash Info: Script: none Area: out of game
02:06:27 (LOKImf2) D2BS is not responding... starting profile
02:06:31 (LOKImf2) Crash Info: Script: none Area: out of game
02:07:38 (LOKImf2) D2BS is not responding... starting profile
02:07:42 (LOKImf2) Crash Info: Script: none Area: out of game
02:08:49 (LOKImf2) D2BS is not responding... starting profile
02:08:53 (LOKImf2) Crash Info: Script: none Area: out of game
02:10:00 (LOKImf2) D2BS is not responding... starting profile
02:10:04 (LOKImf2) Crash Info: Script: none Area: out of game
02:11:10 (LOKImf2) D2BS is not responding... starting profile
02:11:14 (LOKImf2) Crash Info: Script: none Area: out of game
02:12:21 (LOKImf2) D2BS is not responding... starting profile
02:12:25 (LOKImf2) Crash Info: Script: none Area: out of game
02:13:31 (LOKImf2) D2BS is not responding... starting profile
02:13:35 (LOKImf2) Crash Info: Script: none Area: out of game
02:14:41 (LOKImf2) D2BS is not responding... starting profile
02:14:45 (LOKImf2) Crash Info: Script: none Area: out of game
02:15:52 (LOKImf2) D2BS is not responding... starting profile
02:15:56 (LOKImf2) Crash Info: Script: none Area: out of game
02:17:02 (LOKImf2) D2BS is not responding... starting profile
02:17:06 (LOKImf2) Crash Info: Script: none Area: out of game
02:18:13 (LOKImf2) D2BS is not responding... starting profile
02:18:17 (LOKImf2) Crash Info: Script: none Area: out of game
02:19:23 (LOKImf2) D2BS is not responding... starting profile
02:19:27 (LOKImf2) Crash Info: Script: none Area: out of game
02:20:34 (LOKImf2) D2BS is not responding... starting profile
02:20:38 (LOKImf2) Crash Info: Script: none Area: out of game
02:21:45 (LOKImf2) D2BS is not responding... starting profile
02:21:49 (LOKImf2) Crash Info: Script: none Area: out of game
02:22:55 (LOKImf2) D2BS is not responding... starting profile
02:22:59 (LOKImf2) Crash Info: Script: none Area: out of game
02:24:06 (LOKImf2) D2BS is not responding... starting profile
02:24:10 (LOKImf2) Crash Info: Script: none Area: out of game
02:24:13 (LOKImf1) [Game: Yukimf154//Yuki666 (19:06)] [Level: 95 (51.14%)] [XP: 587360] [Games ETA: 187]
02:24:13 (LOKImf3) [Game: Yukimf154//Yuki666 (19:01)] [Level: 94 (22.88%)] [XP: 1132745] [Games ETA: 140]
02:25:17 (LOKImf2) D2BS is not responding... starting profile
02:25:21 (LOKImf2) Crash Info: Script: none Area: out of game
02:26:27 (LOKImf2) D2BS is not responding... starting profile
02:26:31 (LOKImf2) Crash Info: Script: none Area: out of game
02:27:38 (LOKImf2) D2BS is not responding... starting profile
02:27:42 (LOKImf2) Crash Info: Script: none Area: out of game
02:28:49 (LOKImf2) D2BS is not responding... starting profile
02:28:53 (LOKImf2) Crash Info: Script: none Area: out of game
02:30:00 (LOKImf2) D2BS is not responding... starting profile
02:30:04 (LOKImf2) Crash Info: Script: none Area: out of game
02:31:11 (LOKImf2) D2BS is not responding... starting profile
02:31:15 (LOKImf2) Crash Info: Script: none Area: out of game
02:32:21 (LOKImf2) D2BS is not responding... starting profile
02:32:25 (LOKImf2) Crash Info: Script: none Area: out of game
02:33:32 (LOKImf2) D2BS is not responding... starting profile
02:33:36 (LOKImf2) Crash Info: Script: none Area: out of game
02:34:43 (LOKImf2) D2BS is not responding... starting profile
02:34:47 (LOKImf2) Crash Info: Script: none Area: out of game
02:35:53 (LOKImf2) D2BS is not responding... starting profile
02:35:58 (LOKImf2) Crash Info: Script: none Area: out of game
02:37:04 (LOKImf2) D2BS is not responding... starting profile
02:37:08 (LOKImf2) Crash Info: Script: none Area: out of game
02:38:15 (LOKImf2) D2BS is not responding... starting profile
02:38:19 (LOKImf2) Crash Info: Script: none Area: out of game
02:39:26 (LOKImf2) D2BS is not responding... starting profile
02:39:30 (LOKImf2) Crash Info: Script: none Area: out of game
02:40:36 (LOKImf2) D2BS is not responding... starting profile
02:40:40 (LOKImf2) Crash Info: Script: none Area: out of game
02:41:47 (LOKImf2) D2BS is not responding... starting profile
02:41:51 (LOKImf2) Crash Info: Script: none Area: out of game
02:42:58 (LOKImf2) D2BS is not responding... starting profile
02:43:02 (LOKImf2) Crash Info: Script: none Area: out of game
02:43:10 (LOKImf1) [Game: Yukimf155//Yuki666 (18:42)] [Level: 95 (51.41%)] [XP: 606655] [Games ETA: 180]
02:43:10 (LOKImf3) [Game: Yukimf155//Yuki666 (18:36)] [Level: 94 (23.43%)] [XP: 1135978] [Games ETA: 139]
02:44:08 (LOKImf2) D2BS is not responding... starting profile
02:44:12 (LOKImf2) Crash Info: Script: none Area: out of game
02:45:19 (LOKImf2) D2BS is not responding... starting profile
02:45:23 (LOKImf2) Crash Info: Script: none Area: out of game
02:46:29 (LOKImf2) D2BS is not responding... starting profile
02:46:33 (LOKImf2) Crash Info: Script: none Area: out of game
02:47:40 (LOKImf2) D2BS is not responding... starting profile
02:47:44 (LOKImf2) Crash Info: Script: none Area: out of game
02:48:51 (LOKImf2) D2BS is not responding... starting profile
02:48:55 (LOKImf2) Crash Info: Script: none Area: out of game
02:50:01 (LOKImf2) D2BS is not responding... starting profile
02:50:05 (LOKImf2) Crash Info: Script: none Area: out of game
02:51:11 (LOKImf2) D2BS is not responding... starting profile
02:51:15 (LOKImf2) Crash Info: Script: none Area: out of game
02:52:21 (LOKImf2) D2BS is not responding... starting profile
02:52:25 (LOKImf2)


but my lokimf1 and lokimf2 chapter i s  copy from 18.3.xx.100
just copy and drop them into 19.3.23.100 config file

**Comment by sangami70** [comment]
> Did you update via autoupdate recently?

again now

09:20:24 (LOKImf1) Window has unexpectedly exited... starting profile
09:20:27 (LOKImf1) Crash Info: Script: Worldstone Area: Worldstone Keep Level 3
09:21:34 (LOKImf1) D2BS is not responding... starting profile
09:21:38 (LOKImf1) Crash Info: Script: none Area: out of game
09:22:45 (LOKImf1) D2BS is not responding... starting profile
09:22:50 (LOKImf1) Crash Info: Script: none Area: out of game
09:23:56 (LOKImf1) D2BS is not responding... starting profile
09:24:01 (LOKImf1) Crash Info: Script: none Area: out of game
09:25:08 (LOKImf1) D2BS is not responding... starting profile
09:25:12 (LOKImf1) Crash Info: Script: none Area: out of game
09:26:19 (LOKImf1) D2BS is not responding... starting profile
09:26:24 (LOKImf1) Crash Info: Script: none Area: out of game
09:27:30 (LOKImf1) D2BS is not responding... starting profile
09:27:35 (LOKImf1) Crash Info: Script: none Area: out of game

**Comment by noah-** [comment]
You need to redownload all files from github. Autoupdate is not enough for the recent changes. You need to redo all your char config files as well since config settings have changed. It is not backwards compatible.
