### ISSUE TITLE
Phantom Character Config

### ISSUE THREAD

**Issue by LeMule** [kolton/d2bot-with-kolbot#139]
This is my first ever issue logged on anything, ever! (Outside from work!)

The Gist Of It : Character loads into game, loads some phantom config (haven't determined what it's loading, but it's definitely not it's own config)

I've never spawned this Paladin.Foo.js myself like one normally would (game loads, doesn't find one, press "Home", "Space", proceed with the usual), nor am I ever prompted to for some reason. (I had this toon leveled by someone)

If I manually create his config by copy/pasting an already-made one and renaming accordingly, its simply ignored and loads said-phantom config anyways.

I've done a bit of digging though nothing to boast about. Tried some basic things like restarting d2bot#, restarting my pc ( o.o ), and searching for some kind of file that might be loaded in memory that might cause this. No luck.

I've seen this before, but always managed to get it working, "randomly" again. Though this time it looks to be here to stay, so I'm reaching out for a bit of support.

Thanks!

**Comment by dzik87** [comment]
Char config name is case sensitive.

**Comment by LeMule** [comment]
Thank you, but unfortunately it matches, usually quite careful with case sensitivity regardless.

**Comment by dzik87** [comment]
If you create new config and paste that what is inside pre made to newly created one it still don't work ?

**Comment by LeMule** [comment]
This is technically what I tried when I wasn't prompted to "spawn" one upon first time the character is loaded into a game. I've just tried removing this file and it manages to find this phantom config anyways. Is the in-game log mirrored in a file somewhere that I could have a look to see who's config it actually is loading?

**Comment by dzik87** [comment]
You can check _CustomConfig.js file and see if you have any entry's there. Also files like Class.ProfileName.js have higher priority than Class.Charname.js

**Comment by LeMule** [comment]
Wow I had never realized that Class.ProfileName.js would take priority like that.

Just my humble opinion but is this really as designed? It seems wrong to have it prioritize like that since one doesn't necessarily associate a profile name with a character name generally (at least I don't). It causes more or less of a "ghost" issue like this one, that can be insanely hard to track down without reaching out for assistance.

It would take a fair bit of technical knowledge to figure that one out on ones own (I'm done debugging code when I leave work typically :) ). Again though, just my humble opinion. Thank you for the help.

**Comment by dzik87** [comment]
Ye there is more like that. Full list by priority:
1. Custom config
2. Class.Profile.js
3. Realm.Class.Charname.js
4. Class.Charname.js
5. Profile.js
else default config.

Anyway glad you solved your problem :)

**Comment by LeMule** [comment]
I believe removing Class.Profile.js from that list would make it absolutely perfect! Perhaps there is underlying functionality depending on this though *cringe*. Thanks for the added details, and for the help of course!
