### ISSUE TITLE
[Strict Warning (232)] File(Kolbot\libs\ntitemparser.dbl:216) octal literals and octal escape sequences are deprecated

### ISSUE THREAD

**Issue by kkh00** [kolton/d2bot-with-kolbot#1395]
Hey,

from time to time the Bot showing me this warning on screen:

"[Strict Warning (232)] File(Kolbot\libs\ntitemparser.dbl:216) octal literals and octal escape sequences are deprecated"

I never touched the NTItemparser.dbl. 

Does anyone know what causes this issue and how I can solve it?

**Comment by noah-** [comment]
you have a bug in a nip file
