### ISSUE TITLE
How to open Golden Chest at Bonesaw? (Not all chests)

### ISSUE THREAD

**Issue by firekil** [kolton/d2bot-with-kolbot#1396]
I am trying to get my bot to open the big fat chest near Bonesaw. I do not want to enable 
`Config.OpenChests = false;` because I do not want to waste time opening other chests.

I tried adding these lines under the Bonesaw script in my profile:
`Config.Bonesaw.OpenChest = true;`
`Config.Bonesaw.OpenChests = true;`

but nothing happens. 

The Eldritch script contains this config line:
`		Config.Eldritch.OpenChest = true;`

How do I make one like this but for Bonesaw?

**Comment by DarkHorseDre** [comment]
Those "openchest" configs are set in config and then acted upon within the eldritch/ancienttunnels script.

What you need is a line which does the same, e,g from `ancienttunnels.js`:
if (Config.AncientTunnels.OpenChest && Pather.moveToPreset(me.area, 2, 580) && Misc.openChests(5)) {
		Pickit.pickItems();
}
This line does a bit more than just open and pickit but you get the idea.

I cant access stuff from work today but I think the `Pather.moveToPreset(me.area, 2, 580)` should work for you as I think the unittype (2) chest? and presetid (580) special chest? would match in your case - give it a try until you get something definitive.

e.g. put this in the script you're running:
`Pather.moveToPreset(me.area, 2, 580) {
		Pickit.pickItems();
};`

**Comment by DarkHorseDre** [comment]
ok that will work (you could have reduced the code a bit) but you have to remember to set the option under eldritch for it to work.
add a new config in config. js and call it from your config. 

btw I haven't played lod for a while and I feel like another script does this chest? I could be wrong, can't check as pc kaput QQ

**Comment by firekil** [comment]
Perfect! This removed the warning and the chest opens. I can even choose if I want it to open the chest before or after killing Bonesaw by moving the code around. Pretty sweet.
