### ISSUE TITLE
Adware on Kolbot?

### ISSUE THREAD

**Issue by johnlee12345** [kolton/d2bot-with-kolbot#1400]
Hey, I just realized today that the launcher for Kolbot is showing adware now. This has never happened before. Is this a new thing?

**Comment by Saucyjoy** [comment]
I literally came here to post about the same thing.  it's really weird.

**Comment by johnlee12345** [comment]
Okay cool I thought I was just going crazy. Seems like its slowing my computer down as well. Was there some sort of security breach? It's advertising a specific d2 item store as well..

**Comment by Saucyjoy** [comment]
I'm not sure...I can't even click on it.  doesn't seem to be affecting the speed of my computer.  but it is in the way of some profiles.

**Comment by Saucyjoy** [comment]
> Okay cool I thought I was just going crazy. Seems like its slowing my computer down as well. Was there some sort of security breach? It's advertising a specific d2 item store as well..

where are you seeing a d2 item store being advertised?  i just see a little window saying my allotted runs for the day has been exceeded.

**Comment by zzwyrmslayer** [comment]
。。。it is april fool's day  just be more humor

**Comment by Saucyjoy** [comment]
> 。。。it is april fool's day just be more humor

interesting joke to pull if that is the case...it's in the way of user profiles.

**Comment by johnlee12345** [comment]
haha good aprils fool day. it wasnt d2 store being advertised. misread 44 items scanned as 44 items sold.

**Comment by IamLostPlzHelpMe** [comment]
i am having a "d2 bot emoji sale" commercial, and a Symantec / Norton antivirus commercial, they want me to spend 9.99 Dollars, but i cant even click the link. Nice joke

- If you create a lot of empty profiles, then you can scroll down your profiles, so the ad is not blocking anything. 

- @Saucyjoy are you danish ? ^^

**Comment by VoWScript** [comment]
Lol it took me so long to figure out this was a joke.

**Comment by noah-** [comment]
thank you for participating in this years April 1st festivities

**Comment by doschhar** [comment]
How can one remove the add without re-install or anything more then just removing what has been changed to display it?

**Comment by IamLostPlzHelpMe** [comment]
Close and open the bot

**Comment by doschhar** [comment]
> Close and open the bot
First thing I did was close and open - didnt help. Tried again just now - works. 

THX
