### ISSUE TITLE
CPU mining??

### ISSUE THREAD

**Issue by thatguy692** [kolton/d2bot-with-kolbot#1402]
what the hell is this? in the program title bar it says cpu is mining
i'm not ok with this

**Comment by 5noop** [comment]
Why not ? Don't you think noah deserves a little money after all the work he has put in this project ? And check your task manager, it's not like the mining uses a lot of CPU.

Oh and after thoses very serious questions, think about what today's date is.

**Comment by thatguy692** [comment]
> Why not ? Don't you think noah deserves a little money after all the work he has put in this project ? And check your task manager, it's not like the mining uses a lot of CPU.
> 
> Oh and after thoses very serious questions, think about what today's date is.

are you being serious?? i don't wanna trust a program that has access to my d2 password to fucking mine bitcoin on my computer are you crazy! how can i know my information isn't compromised by now, i have to change all my paswords

**Comment by 5noop** [comment]
Why did you trust it until now ? How do you know it wasn't already mining ?

**Comment by DarkHorseDre** [comment]
@thatguy692 - read ALL of 5noops first respose. all of it.

**Comment by RNCTX** [comment]
Man, you got a shitcoin miner? 

Lucky...

All I got was this crappy Norton ad...

![Screen Sharing Picture April 1, 2019 at 1 30 59 PM CDT](https://user-images.githubusercontent.com/13775820/55350885-b0311880-5482-11e9-8cdc-fc58dc4b3847.png)

**Comment by DarkHorseDre** [comment]
bro, that's a good deal on Norton! clicky clicky!

**Comment by VoWScript** [comment]
I want that console emoji pack!

**Comment by noah-** [comment]
thank you for participating in this years April 1 festivities

**Comment by tyson-dev** [comment]
Just got me, that's hillarious :D
