### ISSUE TITLE
CPU mining, crappy Norton ad, ....

### ISSUE THREAD

**Issue by MWEDVAG** [kolton/d2bot-with-kolbot#1406]
good Morning. i can understand that you are looking for running costs and motivation to take money. There is nothing wrong with that. only one thing: why do not ask us first? all the botters i know are 25 or older, we all have work. So, let's choose: either cpu mining, ad whatever, or pay ad free version. or a flat-rate support for the project, with closed download area. how do you see it?

**Comment by IamLostPlzHelpMe** [comment]
can you even click the link?

**Comment by IamLostPlzHelpMe** [comment]
Close the bot and Open it again, and the april fools ad is gone :)

**Comment by MWEDVAG** [comment]
ok … but how can me support this Project? me dont care about little $ and when it helps - me will support. on year 2018 me spend 100$ to Wikipedia. good projekt - so me pay for it.

pls tel me anyone - thx

**Comment by noah-** [comment]
kolbot is free to use and ad free
donations are not accepted, thanks
