### ISSUE TITLE
How to go straight to Canyon of the Magi after Summoner?

### ISSUE THREAD

**Issue by firekil** [kolton/d2bot-with-kolbot#1408]
I would like to open and take the portal to Canyon of the Magi after killing the summoner so that I can do Duriel right after. 

In the Mephisto.js script you have this line:
```
if (Config.Mephisto.TakeRedPortal) {
		Pather.moveTo(17590, 8068);
		delay(1500);
		Pather.moveTo(17601, 8070);
		Pather.usePortal(null);
}
```

Can I do something similar for the Summoner?

**Comment by DarkHorseDre** [comment]
I guess you could if you know the coords for the red portal 
(try: while(true){say(me.x+","+me.y);delay(2000);})

the issue i see is that once your summoner script ends you will need to run duriel script, which will make the toon tp to town.. there are a few ways around this but will involve some mods I reckon (e.g. call the duriel script from the summoner etc. but then the more creative types may have already solved this :p )

**Comment by 5noop** [comment]
```
	let journal = getUnit(2, 357);

	if (!journal) {
		throw new Error("Journal not found");
	}

	Pather.moveTo(journal.x, journal.y);
	journal.interact();
	delay(500);
	me.cancel();

	for (let i = 0; i < 20; i++) {
		if (Pather.getPortal(46)) {
			break;
		}
		delay(50);
	}

	if (i === 19) {
		throw new Error("Arcane portal not found")
	}

	Pather.usePortal(46);
```
But then as @DarkHorseDre said you shouldn't start the existing Duriel script because it will make you go to town. So what you could do for example is to copy what you need from Duriel script and paste it in the Summoner script.

**Comment by firekil** [comment]
Ok so adding 

```
if (Config.Summoner.Journal) {
		let journal = getUnit(2, 357);

		if (!journal) {
			throw new Error("Journal not found");
		}

		Pather.moveTo(journal.x, journal.y);
		journal.interact();
		delay(500);
		me.cancel();
}
```

after the line `Attack.clear(15, 0, 250); // The Summoner` lets me open and take the portal. 

After that I commented out Town.doChores and Pather.useWaypoint(46) in the Duriel script. However I still encounter an error whereas the Duriel script tells me "Failed to move to Tal Rasha's Tomb".

**Comment by noah-** [comment]
this would be a good feature for a pr

**Comment by 5noop** [comment]
The bot will automatically go to town between 2 scripts so put everything in the Summoner script, killing Duriel included. Also you are missing a part of what I wrote in your post.

**Comment by firekil** [comment]
@5noop the part I left out was returning an error and it seemed to work fine without it. It only returns to town because Town.doChores is called in every script.

**Comment by DarkHorseDre** [comment]
@5noop can the summoner script call the duriel script?
if so, can a check on journal config and me.area be used to tell the duri script to not do town chores but instead continue to duri?
something like:

var i, unit;

if (!Config.Summoner.Journal && !me.area === 46) {
	Town.doChores();
	Pather.useWaypoint(46);
}
	Precast.doPrecast(true); //do this as first action if we are continuing from summoner (we are in canyon and Config.Summoner.Journal is true)
..
..

**Comment by 5noop** [comment]
@DarkHorseDre Yeah a script is a function so we can call it as long as the file is included.
Your idea should work but then we would have a Summoner parameter in the Duriel script, I'm not a huge fan of that. Still better than copy/paste the whole Duriel script in Summoner though. Maybe I can only put the condition with me.area !==46

**Comment by DarkHorseDre** [comment]
word.

well I was simpifying. I'm ultimately talking aobut a config parameter for the summoner to duriel link. could be something more appropriate? "config.killduriaftersummoner" or similar?

**Comment by 5noop** [comment]
If we follow the convention it should be Config.Summoner.KillDuriel. It's just that I don't like the idea of using a Summoner config parameter in anything else than the Summoner script, scripts should be as standalone as possible. A global parameter would be even worse imo, the char config file is messy enough.

Anyway a check with me.area should be good enough.

**Comment by noah-** [comment]
could add something in both the summoner and duriel script to check if the other is enabled and modify what to do based on that (use book and do duriel vs go to town and do normal)

**Comment by DarkHorseDre** [comment]
yeah that wasn't literal @5noop , and I hear you, but we already link rakanishu to gris and other boss links.
Theres no way to avoid either setting global params or link params from script to script - the modular design can only stretch so far to accommodate what we do naturally - after all, thats what the boss should be mimicking!  For firekil's needs I think a param will allow him to do what he wants without affecting the solo/normal running of either script..

**Comment by 5noop** [comment]
> Theres no way to avoid either setting global params or link params from script to script

True but I want to avoid them as much as possible :) and I like noah's idea because we don't need parameters then, gonna submit a pr soon

**Comment by DarkHorseDre** [comment]
xD

..but but but thats what I already suggested 
>if so, can a check on journal config and me.area be used to tell the duri script to not do town chores but instead continue to duri?

👼

**Comment by 5noop** [comment]
Maybe I misunderstood you then (: 
Anyway you can check what I did here https://github.com/kolton/d2bot-with-kolbot/pull/1419/commits/ebbde6abd28556d4279e8c67fbbc316bc5dd4fb9

**Comment by firekil** [comment]
Hey guys thanks for helping with this. 

@5noop nevermind your code works fine, I had copied it wrong before.

I tried a bunch of different things like moving him to the wp before starting the Duriel script and copying the Duriel script into Summoner.js but nothing seems to work.

**Comment by 5noop** [comment]
This has been added to master, you can update.

**Comment by firekil** [comment]
Sweet awesome, I'll try it out when I get home.

**Comment by firekil** [comment]
This works beautifully. If both the Summoner and Duriel scripts are set to true, the bot will now automatically takes the red portal to Canyon of Magi and start Duriel right away. Thanks guys.
