### ISSUE TITLE
setup /players x on start?

### ISSUE THREAD

**Issue by lacid** [kolton/d2bot-with-kolbot#1410]
how to setup /players x on start?

**Comment by Saucyjoy** [comment]
you can't set player count online.  /playersx command only works in single player.

**Comment by lacid** [comment]
yes, that's what I play, single player.

**Comment by MWEDVAG** [comment]
got the same Problem - me solve it on this way (when exist a better way feel free to say this)

in the char config, me add under line 28 this: 		say("/players 8");

works finde for me

hf and Gl mate

**Comment by MWEDVAG** [comment]
btw - can you me say how me can set that the droid stay on the paladon in the throne? he stay hat the sorc and hurricane cant get good dmg on this way. me test many many Things with attack and classid Things, but never worked fine. thx for answer
