### ISSUE TITLE
New to Kolbot

### ISSUE THREAD

**Issue by msaint91** [kolton/d2bot-with-kolbot#1425]
Hi I am new and would like to have a better understanding. When I googled I saw a video saying I have to torrent d2 and manually update the patch in order to run kolbot. Is this true? It seems that based on what I am reading here I should not have to do this. I have official copies from battle.net installed currently (no mpq files or any other modifications other than to be able to run two copies at once using sandboxie). If I do have to torrent diablo and go through all the extra steps I will just pass on running the bot.

**Comment by 5noop** [comment]
The official download works fine
