### ISSUE TITLE
Config.PacketWalk

### ISSUE THREAD

**Issue by MWEDVAG** [kolton/d2bot-with-kolbot#1428]
hey. could we impose an option in a future version:

	// General config
	Config.PacketWalk = true; // Use packets to walk. Improves speed and stop hangs. (act4 ;b)

kukbot use this in the past. you can see packet walk on this link:

https://www.youtube.com/watch?v=oh6CowXQBGA

Thanks for the attention

**Comment by noah-** [comment]
This doesn't have any use
you should not have any a4 hangs with current version

**Comment by MWEDVAG** [comment]
ok thanks for answer.

**Comment by MWEDVAG** [comment]
can you say me how me can Change the staypoint from the droid in the throne? me try many Things.
