### ISSUE TITLE
My Char just stay in the town.

### ISSUE THREAD

**Issue by cheapyau** [kolton/d2bot-with-kolbot#1430]
Try to make a team with total 3 members (1 sor, 1 bar and 1 din). When all char join in one game they will not go out and  only stay in town. Message in "din" screen show " I am not assigned a role in my config file. Please rectify this omission and restart." How can I solve this problem? Please help.

**Comment by tlwh163** [comment]
PLZ Reading instructions

**Comment by cheapyau** [comment]
Problem fixed. Thx

**Comment by XhelkCODE** [comment]
eiii solucion???

**Comment by anders-i** [comment]
The problem is the character names is case sensitive had same problem just figured it out.. :)

Scripts.AutoSmurf = true;
		Config.AutoSmurf.TeamSize = 5;
		Config.AutoSmurf.TeleportingSorc = "SoMe_NamE"; // your leader sorceress charname.
		Config.AutoSmurf.BoBarb = "BobArb"; // boBarb charname
		Config.AutoSmurf.OtherChars = ["naaaAMe1", "naM2", "JAvaZon"]; // all team charnames, excluding the leader and boBarb
		Config.AutoSmurf.AllTeamProfiles = ["SorcLeader", "Javazon", "PalaHammer", "AssA", "Barb"]; // the whole team PROFILE names
