### ISSUE TITLE
Bot Sits in Town After Baal

### ISSUE THREAD

**Issue by mitchelllee222** [kolton/d2bot-with-kolbot#1432]
I'm running a single character that's just doing solo cs/baal runs.  After he finishes baal, he'll loot, go to town, sell, then walk back towards his portal, stop and just sit there.  It won't proceed to the next game.

If I edit the Config.Inventory table to have no open slots, so that the bot doesn't loot, as soon as it finishes it's run, it'll close the game and go to the next game.  It's only when I have inventory slots open and the bot loots something to identify or sell.  Although I'm a very experienced programmer, I'm new kolbot, so I'm not quite sure why it's hanging up when it goes to town.

**Comment by TPABHuKOB** [comment]
Open console ('Home' btn) and look what name of script runs after Baal.
Looks like your bot start 'Rushee' script

**Comment by mitchelllee222** [comment]
### When it gets done with baal, it's coming back to town and saying "Staring script: MFHelper"  So, that's why it's doing it.  Don't know why that was true unless I fat fingered and flipped it on the keyboard as I've only been using one account.
