### ISSUE TITLE
Change distance in throne for druid

### ISSUE THREAD

**Issue by MWEDVAG** [kolton/d2bot-with-kolbot#1435]
hi. me read all 30 sites here, and use google - cant find an answer.

my elementar druid stay at sorc in throne, would be nice when he stay at the pala.

me think the answer is in the attack.js, me try many things, but cant find a solution.

thanks for help me

**Comment by 5noop** [comment]
Check this https://github.com/kolton/d2bot-with-kolbot/issues/909

**Comment by MWEDVAG** [comment]
very very thx this helps alot! (me look all threads dawn-.-) and worked:

			if (safeCheck && !baalCheck && me.area === 131 && me.area !== 132) {
				if (!baalCheck && !throneStatus) {
					if (Helper) {
						Attack.clear(15);
						this.clearThrone();

	//			Pather.moveTo(15094, (me.classid === 1 || me.classid === 2 || me.classid === 3 || me.classid === 4 || me.classid === 5 || me.classid === 6 || me.classid === 7) ? 5029 : 5038);
	//			Pather.moveTo(15094, (me.classid === 3 || me.classid === 4) ? 5029 : 5038);
	
				Pather.moveTo(15094, (me.classid === 7 || me.classid === 5) ? 5029 : 5038);
	
					//char ids:
					// 1 Sorc
					// 3 pala
					// 4 barb
					// 5 druid
					
					//vor bo
					
					delay(3000);
					
					
					
	//					Precast.doPrecast(true);
					}

					tick = getTickCount();

					MainLoop: while (true) {
						if (Helper) {
							if (getDistance(me, 15094, (me.classid === 7 || me.classid === 5) ? 5029 : 5038) > 3) {
								Pather.moveTo(15094, (me.classid === 7 || me.classid === 5) ? 5029 : 5038);
							}
						}
