### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tarapice** [kolton/d2bot-with-kolbot#144]
If i want to run say 3 bots in same game, To do the Mfing together.
So they would join and exist areas together.

How would i sett this up?

**Comment by mboufos** [comment]
1 check the channel script and the leader
2 make all chars friend together :P 
3 and you use the same scripts :) for dia baal runs the leader will do the classic diablo/baal script and the others the diablo helper autobaal/baal assistance :)
also the leader will do the invites :P

**Comment by tarapice** [comment]
was htinking more of Pit\Acient tunnels etc.

**Comment by mboufos** [comment]
if you want all chars to go to  pit/ancient etc you will put the same scripts :) i guess clear area etc :)
