### ISSUE TITLE
[EN/FR] Pickit list wrong ? No loot after 150runs ! bot with weak character !

### ISSUE THREAD

**Issue by shaaya26** [kolton/d2bot-with-kolbot#1446]
Hello !

First ... Sorry for my english  :p

"Work" on Nightmare :
I'm recently trying to make a bot with kolbot ...so my character do what i want ...clear boss etc etc..
BUT ! after 150run in nightmare vs andariel+mephisto+baal every run .... my bot didn't keep any items

the bot always sell everythings....or skip some items... this is my pickit list 
->https://pastebin.com/Kw81JEbv?fbclid=IwAR0QDxPEWIXN3pbip5TyJuO0BVOUYA9KTn6_vDgfWCO3FUM6D9M-vP7T_2c

i'm poor and weak with my sorc blizz.... so i can't go to hell and clear boss easily so i go NM but i don't know if this pickit list is appropriate to do this ? I don't want perfect item ...

And if someone have a pickit list who work perfectly its better :)

Same text but in french :

Bonjour à tous ! 

je joue en cauchemars car ma sorc blizz est trop faible pour l'enfer.

Récemment j'ai programmé kolbot et tout marche bien , il fait les runs correctement etc etc 
Mais c'est au niveau des loots que je pense être dans le faux... après 150 run contre andy+meph+baal....rien du tout.... il a tout vendu ou que sais-je...

voici mon fichier pickit -> https://pastebin.com/Kw81JEbv?fbclid=IwAR0QDxPEWIXN3pbip5TyJuO0BVOUYA9KTn6_vDgfWCO3FUM6D9M-vP7T_2c

pouvez vous m'éclairer ? est-ce ma pickit list qui n'est pas adaptée pour le cauchemars ?
Si quelqu'un a une picklit qui déchire je suis preneur :D

**Comment by tlwh163** [comment]
One BOT is still very weak in MF. It needs more than 4 BOTs i think. 
There is no need to stay too long for the nightmare difficulty. You should quickly raise the character level and then enter the hell difficulty MF.
For BLZ-SOR, at Hell, you can start MF Mausoleum & Crypt, & Mephisto(MoatTrick)
When PET has the best weapon, you can add AncientTunnels & Duriel.

**Comment by shaaya26** [comment]
Ty for your help i will try this !
there is a script for the MoatTrick ?

**Comment by DarkHorseDre** [comment]
Hey,
if your bot has no items, the items which drop in NM can be good (mephi, dia, and soj from andy).  The default kolton.nip is not complete and looks for perfect stats (e.g. [name] == amulet && [quality] == unique # [strength] == 5 && [fireresist] >= 30 // mara) instead of minimum stats.  Botting in NM with an incomplete and perfect seeking pickin is the reason why you have no drops.

This is a list of pickits shared recently, change yours!
https://darcvigilante.site/showthread.php?tid=9

Bonne chance! ;)

**Comment by shaaya26** [comment]
Problem solved :) thank you a lot ! after 100run andy -> tulwar 89% + 2xnage (18-28)

**Comment by DarkHorseDre** [comment]
du rien

aha yes, you will find many ali baba from nm andy xD

**Comment by Retalha** [comment]
> Problem solved :) thank you a lot ! after 100run andy -> tulwar 89% + 2xnage (18-28) 

How was the issue resolved? What did you do or change in kobolt?
