### ISSUE TITLE
Minimizing screen every time I start a new game

### ISSUE THREAD

**Issue by omegaeclipse** [kolton/d2bot-with-kolbot#1450]
Hi everyone, new here, I saw that someone posted something similar a while back in July but it sounds like it never got resolved.

Was wondering if there was something in the script I have to change from true to false to make it stop minimizing the screen every time I go into a game or leave a game. It causes crashes a lot of the time, and can't find what is exactly the problem. 

Its not window mode as I turned that off a while a go. Thanks in advance.

**Comment by mf022** [comment]
> Its not window mode as I turned that off a while a go.
it isn't related.
btw on windows 10 you should set -w parameter, otherwise d2 window will crash.

check https://github.com/kolton/d2bot-with-kolbot/wiki/D2Bot-%23-Manager-Setup#create-a-profile
18. 
check the visible mode if you play manually.

**Comment by omegaeclipse** [comment]
Okay that works, I just hate window mode so I turned it off right away. Problem fixed. Thank you.
