### ISSUE TITLE
leechers spamming join game on a non-exsisting game

### ISSUE THREAD

**Issue by oband2** [kolton/d2bot-with-kolbot#1451]
Follower file: https://pastebin.com/2cqFKiEg
Consol text: https://pastebin.com/RSB0QsqN

When failed to join a game, that doesnt exsist, they just spam it, and i guess this have caused me to get queue time previously, lucky i caught this one, but i dont know why it does it, i dont have anything in my follower saying join every 1 sec? which they do.
https://i.gyazo.com/thumb/1200/201b43249727b36964dcde9624c00171-png.jpg

**Comment by DarkHorseDre** [comment]
For a follower to join a leader game you need to configure:
profiles in d2manager for each toon
config files for each toon (leader, scripts etc)
follower entry
leader entry

So pls share the profile setup (screenshot) for the leader and a failing follower (hiding passwords but show at least part of the game name), and character configs.

You just need to check the game name of the leader is that which the follower is attempting to use, and if not, which games is it using.  

Are all toons on the same pc? 
ensure they are on each others friends list
