### ISSUE TITLE
[ClassID] == dagger # [EnhancedDamage] >= 180

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1458]
why wont it keep all dagger types
also [Type] == dagger < does not work
ie < stiletto / kiris / pinograd ...etc

gives me 
unknown property : classid
unknown  type : dagger

but when you do this it keeps all armor/helm .. bow/axe ... etc
[Type] == helm # [EnhancedDefense] >= 180
[Type] == bow # [EnhancedDamage] >= 180

**Comment by ross-weir** [comment]
Try this instead, I think daggers go under knife

`[Type] == knife`

**Comment by DarkHorseDre** [comment]
I'm not sure if its type = knife or sword.  iirc its:
`[type] == sword && [name] <= blade` etc

**Comment by gtoilet** [comment]
thanks , knife worked
