### ISSUE TITLE
D2bs.dll failed to load/js32.dll failed to load 

### ISSUE THREAD

**Issue by TsMysticK** [kolton/d2bot-with-kolbot#146]
When i start the bot it crashes instantly. Starts diablo but that diablo can not connect to bnet 

Can anyone help me fix installation and or config?

**Comment by WiZzMaN47** [comment]
make sure u run it under admin mode or whatever its called under the windows os

**Comment by dzik87** [comment]
D2BS version in this repo is compatible only with 1.13d. To use it with 1.14 you need to find version hack on bh forums.
