### ISSUE TITLE
How to change attackskill for specific script?

### ISSUE THREAD

**Issue by CptClawPLN** [kolton/d2bot-with-kolbot#1464]
I'd like to keep my current attack config the same because I use it for every other script, but in the diablo script i'd like to change my Config.AttackSkill[1] and Config.AttackSkill[3] only in this script. Anyone mind helping me out?

**Comment by tlwh163** [comment]
diablo.js --> About line 425

	// start
	var AS1 = Config.AttackSkill[1], //<--- Inserted line
	    AS3 = Config.AttackSkill[3]; //<--- Inserted line
	Config.AttackSkill[1] = xxx;     //Skill ID what u want <--- Inserted line
	Config.AttackSkill[3] = yyy;     //Skill ID what u want <--- Inserted line

	Town.doChores();
	....
	....
	....

	this.diabloPrep();
	Attack.kill(243); // Diablo
	Pickit.pickItems();
	
	Config.AttackSkill[1] = AS1;  //<--- Inserted line
	Config.AttackSkill[3] = AS3;  //<--- Inserted line

**Comment by 5noop** [comment]
You can pass any config properties to your diablo script in the character file, c.f. https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config#advanced-options

But be careful, AttackSkill is an array so you will have to write something like that:
`Scripts.Diablo = { AttackSkill: [0, 1, 2, 3, 4, 5, 6] }; `
(0 corresponds to `Config.AttackSkill[0] ` etc)

**Comment by tlwh163** [comment]
Scripts.SomeScript = {changed_properties};

This grammar is very advanced, learning!  TK

**Comment by CptClawPLN** [comment]
> You can pass any config properties to your diablo script in the character file, c.f. https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config#advanced-options
> 
> But be careful, AttackSkill is an array so you will have to write something like that:
> `Scripts.Diablo = { AttackSkill: [0, 1, 2, 3, 4, 5, 6] }; `
> (0 corresponds to `Config.AttackSkill[0]`, 1 to `Config.AttackSkill[1]` etc)

How would I define the actual skill for it to use with this?
Scripts.Diablo = { AttackSkill: [0, 1, 2, 3, 4, 5, 6] }; 
AttackSkill[0] = xxx?;
