### ISSUE TITLE
Baal Assistant issue

### ISSUE THREAD

**Issue by VtecPower** [kolton/d2bot-with-kolbot#147]
so my problem at the moment is that my bot wont use safe tp when leader says the safe tp message and i tried different things and none worked bot just sit in town so i need to use hottp but since he doesnt fight he can die some times and lose xp .. so help me plzz D:

**Comment by mboufos** [comment]
re-check the safe tp message :P

**Comment by VtecPower** [comment]
i copy pasted the leaders message :/

**Comment by mboufos** [comment]
do you enable 
	Scripts.BaalAssistant = **true**; // Used to leech or help in baal runs.
		Config.BaalAssistant.Wait = 120; // Seconds to wait for a runner to be in the throne / portal wait / safe TP wait / hot TP wait...
		Config.BaalAssistant.KillNihlathak = false; // Kill Nihlathak before going to Throne
		Config.BaalAssistant.FastChaos = false; // Kill Diablo before going to Throne
		Config.BaalAssistant.Helper = true; // Set to true to help attack, set false to to leech.
		Config.BaalAssistant.GetShrine = false; // Set to true to get a experience shrine at the start of the run.
		Config.BaalAssistant.GetShrineWaitForHotTP = false; // Set to true to get a experience shrine after leader shouts the hot tp message as defined in Config.BaalAssistant.HotTPMessage
		Config.BaalAssistant.SkipTP = false; // Set to true to enable the helper to skip the TP and teleport down to the throne room.
		Config.BaalAssistant.WaitForSafeTP = **true**; // Set to true to wait for a safe TP message (defined in SafeTPMessage)
		Config.BaalAssistant.DollQuit = false; // Quit on dolls. (Hardcore players?)
		Config.BaalAssistant.SoulQuit = false; // Quit on Souls. (Hardcore players?)
		Config.BaalAssistant.KillBaal = true; // Set to true to kill baal, if you set to false you MUST configure Config.QuitList or Config.BaalAssistant.NextGameMessage or the bot will wait indefinitely. 
		Config.BaalAssistant.HotTPMessage = ["Hot"]; // Configure safe TP messages.
		Config.BaalAssistant.**SafeTPMessage** = ["Safe", "Clear"]; // Configure safe TP messages.
		Config.BaalAssistant.BaalMessage = ["Baal"]; // Configure baal messages, this is a precautionary measure.
		Config.BaalAssistant.NextGameMessage = ["Next Game", "Next", "New Game"];	// Next Game message, this is a precautionary quit command, Reccomended setting up: Config.QuitList


check the bolds :)

**Comment by VtecPower** [comment]
ya and it just sit a tp :/

**Comment by mboufos** [comment]
ok then i guess you havent add the leaders name at config lead ?
Config.Leader = "Leader name here ";  ?

**Comment by VtecPower** [comment]
well im using Config.QuitListMode but ima try leader name :)

**Comment by VtecPower** [comment]
o well ya thx that was it :o  and btw is there anyway to make wakka script a bit faster?

**Comment by mboufos** [comment]
:D no idea about wakka script :P

**Comment by VtecPower** [comment]
ok well thx you :p
