### ISSUE TITLE
[UNSOLVED] Undefined Config.PrimarySlot | Undefined Config.LocalChat | TypeError: Config.LocalChat Undefined.

### ISSUE THREAD

**Issue by jmcother** [kolton/d2bot-with-kolbot#1472]
[SOLVED] Undefined Config.PrimarySlot | Undefined Config.LocalChat | TypeError: Config.LocalChat Undefined.

At a total loss on this one. Not sure where to begin fixing it.

Image below.

![Capture3](https://user-images.githubusercontent.com/49925261/56618215-82557480-65e7-11e9-9fa2-b738a59637bb.PNG)

If there is anything else I can provide that will help please let me know.

**Comment by JaySleepy** [comment]
How did you fix it? Getting same error.

**Comment by jmcother** [comment]
It is an issue with the config.js file. It was missing some parameters. I took a good config.js file and added back in the autosmurf portion(the whole reason I used a bad config.js file in the first place). 

tdlr: You are missing the localchat section on the config.js file.

**Comment by JaySleepy** [comment]
What about the attack error?

**Comment by jmcother** [comment]
That was part of the same issue. When I had added the bad config.js file(it was an old config file from a previous version of kolton) some of the new code wasnt represented in the config file.

**Comment by jmcother** [comment]
https://m.me/justice.cother message me here in fb. I'll respond more and help you get it fixed.

**Comment by JaySleepy** [comment]
Can you drop your config.js here? I don't know where I would find a good config. It was from a freshly downloaded kolton.

**Comment by jmcother** [comment]
^^^

**Comment by JaySleepy** [comment]
I see the error.
	Cubing: false,
	CubeRepair: false,
	RepairPercent: 40,
	Recipes: [],
	MakeRunewords: false,
	Runewords: [],
	KeepRunewords: [],
	Gamble: false,
	GambleItems: [],
	GambleGoldStart: 0,
	GambleGoldStop: 0,
	MiniShopBot: false,
	TeleSwitch: false,
	MFSwitchPercent: 0,
	**PrimarySlot: -1,**
	LogExperience: false,
	TownCheck: false,
	PingQuit: [{Ping: 0, Duration: 0}],
	PacketShopping: false,

**Comment by JaySleepy** [comment]
Its missing that line... along with other lines... oh geez.

**Comment by jmcother** [comment]
fixed then?

**Comment by JaySleepy** [comment]
Yeah, since I edited so much I forgot to change my autobuild back to chainL and I got a bunch of non found Blizzard autobuild errors. LOL I felt like a idiot when I figured that out... Thank you so much for pointing me in the right direction.
