### ISSUE TITLE
rolling exile 

### ISSUE THREAD

**Issue by mayphilc** [kolton/d2bot-with-kolbot#1483]
what would be the lines needed to roll and keep 16 aura ebugged ST exile?
bot ebugged a eth ST now i want it to roll a 16 exile with that baase

**Comment by tlwh163** [comment]
Config.Cubing = true;
Config.Recipes.push([Recipe.Socket.Shield, 498, Roll.Eth]);

Config.MakeRunewords = true;
Config.Runewords.push([Runeword.Exile, 498]);
Config.KeepRunewords.push("[name] == 498 # [enhanceddefense] >= 260 && [defianceaura] >= 16");

**Comment by mayphilc** [comment]
thanks a ton man,
i shouldnt have to add the runes to my pickit right it works like the other cubing recipes and autoloot?

**Comment by mayphilc** [comment]
i use this to ebug the shield, should i use item id instead?
Config.Recipes.push([Recipe.Socket.Shield, "Sacred Rondache", Roll.Eth]);

**Comment by tlwh163** [comment]
its ok
