### ISSUE TITLE
kolton.nip rare ring problem

### ISSUE THREAD

**Issue by mayphilc** [kolton/d2bot-with-kolbot#1484]
this line:
`[name] == ring && [quality] == rare # [fcr] == 10 && ([fireresist] >= 20 || [lightresist] >= 20 || [fireresist] >= 9 && [lightresist] >= 9 && ([maxhp] >= 30 || [maxmana] >= 60) || [maxhp] >= 30 && [maxmana] >= 60)`

does not work correctly., it loots GARBAGE rings. heres a ring it looted:
10fcr
14 mana
20 light resist

looking at the line i can tell its supposed to check the resists better. as it is it keeps any ring with 10 fcr and 10+ fire or llight res.

there is a missing ")"

here is how the line should be:
`[name] == ring && [quality] == rare # [fcr] == 10 && ([fireresist] >= 20 || [lightresist] >= 20 || [fireresist] >= 9 && [lightresist] >= 9) && ([maxhp] >= 30 || [maxmana] >= 60) || [maxhp] >= 30 && [maxmana] >= 60)`

**Comment by mf022** [comment]
recheck the comparison https://github.com/blizzhackers/pickits/blob/master/NipGuide.md/#comparison-symbols and the brackets

the last part is useless
```
[name] == ring && [quality] == rare # [fcr] == 10 && ([fireresist] >= 20 || [lightresist] >= 20 || ([fireresist] >= 9 && [lightresist] >= 9)) && ([maxhp] >= 30 || [maxmana] >= 60)
```
you have 3 stat conditions to keep the ring
* fcr 10
* FR >= 20 
   or LR >= 20
   or FR >=9 + LR >= 9
* maxhp >= 30
   or maxmana >= 60

**Comment by mayphilc** [comment]
yeah that was in the kolton.nip thats not even a line i made.
thanks for making it better

**Comment by mf022** [comment]
anyway these:
[fireresist] >= 20 || [lightresist] >= 20 || ([fireresist] >= 9 && [lightresist] >= 9)

can be rewritten like:
[fireresist]+[lightresist] >= 18

**Comment by tlwh163** [comment]
yes, advanced!

**Comment by DarkHorseDre** [comment]
May  be more accurate to do this if you want FR OR LR to be 20+, IR==OR FR>=9 && LR>=9:
`[fireresist] >= 20 || [lightresist] >= 20 || ([fireresist] >= 9 && [lightresist] >= 9)`

as 
`[fireresist]+[lightresist] >= 18` could mean that FR = 1 and LR = 17, and any other permutation of LR+FR >=18

Use brackets to group your expressions correctly
