### ISSUE TITLE
Sorces skips diablo

### ISSUE THREAD

**Issue by tarapice** [kolton/d2bot-with-kolbot#149]
Error in Diablo (diablo.js #321) Diablo not found

**Comment by mboufos** [comment]
some sosos if  one of 3 mini bosses are immune cant kill is so she skip it, and diablo doesnt apear ofc :P

**Comment by tarapice** [comment]
hum. will telestomp fix this?

**Comment by mboufos** [comment]
em i guess yes , you can try it :P else make a light soso with infinity heheh :)

**Comment by tarapice** [comment]
i do have infinity :P

**Comment by mboufos** [comment]
then make a pala  :D hehe emm you can try to put 1 skill to firebolt or ice just to hit if boss is immue ( so merc have time to kill it )

**Comment by tarapice** [comment]
hum. gona sett it up with a necro with auras. maybe it will help

**Comment by tarapice** [comment]
also trying out that Mf leader function, but seems the followers quit before the area is done at times.

**Comment by tarapice** [comment]
also the leecher wont go back to town
