### ISSUE TITLE
Fix for NTItemAlias.dbl

### ISSUE THREAD

**Issue by 3CoRmEuM** [kolton/d2bot-with-kolbot#1506]
NTItemAlias.dbl

Actual:
```
line 1111: NTIPAliasStat["skillfissure"] = [107,231];
line 1114: NTIPAliasStat["skillcarrionvine"] = [107,234];
```
Fix:
```
line 1111: NTIPAliasStat["skillcarrionvine"] = [107,231];
line 1114: NTIPAliasStat["skillfissure"] = [107,234];
```

It seems, that I don't have the permission to PR or I may be dumb, I'll PR that fix on this way.

**Comment by tlwh163** [comment]
NTIPAliasStat["107,231"] = [107,231];
NTIPAliasStat["107,234"] = [107,234];

**Comment by mf022** [comment]
> It seems, that I don't have the permission to PR

First of all, you should fork the [main repository](https://github.com/kolton/d2bot-with-kolbot) (check top-right line), then you can add your fixes to your forked repo, and the PR can be sent finally.

**Comment by 3CoRmEuM** [comment]
@mf022 Thanks mate, I'll look into this o/

**Comment by 3CoRmEuM** [comment]
I were successful, Thanks mf022 =)

Closed ~
