### ISSUE TITLE
"leader not partied" wakka 250 issue

### ISSUE THREAD

**Issue by soubie1** [kolton/d2bot-with-kolbot#1507]
Hey everyone!

try'n to do diaruns with 1 leech (on sp, shouldn't matter i think)
1 lead opens game
2 leech joins
3 partyin' works fine, bot starts run, gives tps

4. leecher stands in a4 town, waits till Error("Wakka Line 250: Leader not partied"); apperars. 

Note: same error appears if i run trist f.e. , same "wakka" error, wtf?
tried to find solutions, 
f.e. https://github.com/kolton/d2bot-with-kolbot/issues/131 didn't change anything. 
as far as i see, leader/leecher scrips are set up fine.

any idea/fixing method?
thanks for thinkin about

**Comment by soubie1** [comment]
I just dont get this. 
tried to run the dialeecher as a baalhelper aswell- same "wakka" error. never even changed sth there.

// start
	Town.goToTown(4);
	Town.move("portalspot");

	if (Config.Leader) {
		leader = Config.Leader;

		for (i = 0; i < 30; i += 1) {
			if (Misc.inMyParty(leader)) {
				break;
			}

			delay(1000);
		}

		if (i === 30) {
			throw new Error("Wakka: Leader not partied");                <--- line 250
		}
	}

	autoLeaderDetect(108);
	Town.doChores();

how is this error created?

**Comment by 5noop** [comment]
Check if you correctly set your leader name in Config.Leader in your leecher config file. Note that if you don't write anything it should autodetect the leader.

**Comment by soubie1** [comment]
@5noop ty for answering!

i checked the name, and tried to leave it "" now- both get the sake wakka 250 error.
listed all changes i did (i think?) for this, maby u can find it
for further expl.:
i'm runnin on tcp/ip games, trying to lvl up a char on nm diaruns. 

lead char: 
Scripts.Diablo = true;

// Public game options

	// If LocalChat is enabled, chat can be sent via 'sendCopyData' instead of BNET
	// To allow 'say' to use BNET, use 'say("msg", true)', the 2nd parameter will force BNET
	// LocalChat messages will only be visible on clients running on the same PC
	Config.LocalChat.Enabled = true; // enable the LocalChat system
	Config.LocalChat.Toggle = false; // optional, set to KEY value to toggle through modes 0, 1, 2
	Config.LocalChat.Mode = 0; // 0 = disabled, 1 = chat from 'say' (recommended), 2 = all chat (for manual play)
	// If Config.Leader is set, the bot will only accept invites from leader. If Config.PublicMode is not 0, Baal and Diablo script will open Town Portals.
	Config.PublicMode = 1; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable
	// Party message settings. Each setting represents an array of messages that will be randomly chosen.
	// $name, $level, $class and $killer are replaced by the player's name, level, class and killer
	Config.Greetings = ["hi"]; // Example: ["Hello, $name (level $level $class)"]
	Config.DeathMessages = ["oh"]; // Example: ["Watch out for that $killer, $name!"]
	Config.Congratulations = []; // Example: ["Congrats on level $level, $name!"]
	Config.ShitList = false; // Blacklist hostile players so they don't get invited to party.
	Config.UnpartyShitlisted = false; // Leave party if someone invited a blacklisted player.

Leech Char:

123 /* ### leeching section ###
	* Unless stated otherwise, leader's character name isn't needed on order to run.
	* Don't use more scripts of the same type! (Run AutoBaal OR BaalHelper, not both)
	*/

	Config.Leader = "soubie"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
	Config.QuitList = ["soubie"]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];
	Config.QuitListMode = 0; // 0 = use character names; 1 = use profile names (all profiles must run on the same computer).

	Scripts.TristramLeech = false; // Enters Tristram, attempts to stay close to the leader and will try and help kill.
	Scripts.TravincalLeech = false; // Enters portal at back of Travincal.
		Config.TravincalLeech.Helper = true; // If set to true the character will teleport to the stairs and help attack.
	Scripts.MFHelper = false; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true
	Scripts.Wakka = true; // Walking chaos leecher with auto leader assignment, stays at safe distance 130 from the leader

438 Config.PublicMode = 1; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable


BotLead:
9// ChannelConfig can override these options for individual profiles.
10	JoinChannel: "KOLBOT", // Default channel. Can be an array of channels - ["channel 1", "channel 2"]
11	FirstJoinMessage: "hi", // Default join message. Can be an array of messages
12	AnnounceGames: false, // Default value
13	AfterGameMessage: "", // Default message after a finished game. Can be an array of messages

botfollow:

2 JoinChannel: "KOLBOT", // Name of the channel to join
3	FirstJoinMessage: "I'm a leecher", // Message to say when first joining a channel, usually ".login"
4	ChatActionsDelay: 2, // Seconds to wait in lobby before entering a channel

51 var JoinSettings = {
52	"soubie": ["runes"]

soubie=lead runes=leech

**Comment by 5noop** [comment]
> i checked the name, and tried to leave it "" now- both get the same wakka 250 error.

You mean your leader and leecher get the error ? This should definitely not be happening since the leader isn't even running Wakka (right ?).
I'd say the easiest way to try to solve that is to re download the whole bot and write your config again.

**Comment by soubie1** [comment]
@5noop 
just the leecher gets the error...
maby the best advise, but i wanted to try at least .. fk that xD

**Comment by soubie1** [comment]
@5noop 
Update: set up completly new. 
works.
thanks m8!
