### ISSUE TITLE
Tcp/ip leecher question

### ISSUE THREAD

**Issue by soubie1** [kolton/d2bot-with-kolbot#1509]
hey! 

got my lead/follow set up fine, playn tcp/ip games.

leecher is set up to quit with leader via Quit.List.
Now there is this issue:

sometimes the leech ends the run 1ms after leader left. file is saved correclty, everything fine
BUT
other times the loader seems to quit too slow (i think thats the problem?), so that it gets the " Host of this game left, game closed". in this case, no exp, nor items etc. are saved, 
the run was basically not done in saves.

So if i run autobaal f.e. like every 1/3 runs end with this, making 2/3 of runs useless..

any ideas or same problems?

**Comment by 3CoRmEuM** [comment]
Hey,

I got the same issue. What I do at the moment, is, I don't use QuitList anymore AND I made sure, that my host char leaves the game at last. I made some noobie changes here and there to get rid of this issue.

In d2bot-with-kolbot-master/d2bs/kolbot/libs/bots/...
I made and put a separate script called TCPIPHostExit.js:
```
function TCPIPHostExit() {
	delay(9000);
	quit(true);
	return true;
}
```

And I added this in my charconfigs ( where to put in charconfig ? I would suggest line 226 in unmodified charconfigs, behind BaalAssistant and before Town Settings :
`Scripts.TCPIPHostExit = true;`

As the last script for leechers "returns true", they will leave the game. That happens also with leader: last script returns true ? -> then NG. So I made TCPIPHostExit.js as my last script. My Hoster waits nine seconds so leechers have enough time to pick stuff at the end of their run ! and then leaves itself.

Seems to work as intendet so far. I hope the kolbot devs and collaborateurs may getting also a solution for this issue like Hyperjoin for TCP/IP a well done thing is =)

The thing with "quit(true);" is, if I used just "quit();", I believed that it was doing another exit method, but I'm not sure though and don't dare to edit it back to quit();. It may be a placebo effect... dunno ( I searched overall in botfolder for quit(true);, but there is none :(

But it seems to work.

Trial and error o/

PS: At ALL of you guys, If I'm telling untrue stuff and/or if I made mistakes or am offering dumb solutions, please feel free to correct me =)

**Comment by mf022** [comment]
even with quitlist there can be set a delay before quit.
check https://github.com/kolton/d2bot-with-kolbot/issues/1462#issuecomment-484983690

**Comment by 3CoRmEuM** [comment]
@mf022 I'm missing to use QuitList since I bot in HC TCP/IP xD I'll defenitly give it a try, thanks mf022 o/

**Comment by mf022** [comment]
> delay((5, 30) * 1000);

this line should be
```
			delay(10000);
```
for fixed 10 seconds delay

rand(5, 30) = random integer number between 5 and 30
delay is measured in miliseconds, so * 1000 is needed
