### ISSUE TITLE
Question pickit

### ISSUE THREAD

**Issue by tarapice** [kolton/d2bot-with-kolbot#151]
is it possible to add ur own items?

cuz i cant see any "rare orb" with Orb insted of blizzard.

also other things

**Comment by WiZzMaN47** [comment]
[type] == orb && [quality] == rare # [sorceressskills] <= 3
[type] == orb && [quality] == magic # [fireskilltab]+[skillenchant] >= 6
[type] == orb && [quality] == magic # [coldskilltab]+[skillfrozenorb] >= 6
not sure what u tryn to pick up but i hope that helps

**Comment by LeMule** [comment]
In the file ...\Kolbot\trunk\d2bs\kolbot\libs\NTItemParser.dbl, you can find a detailed explanation of the pickit syntax. Relevant item information to help you build your pickit file can mostly be found here http://classic.battle.net/diablo2exp/ 

Hope that helps.
