### ISSUE TITLE
Having a probelm with OrgTorch Script Error.(Target not found)

### ISSUE THREAD

**Issue by zain122** [kolton/d2bot-with-kolbot#1513]
Error in OrgTorch (attack.js line 229): Attack.kill: Target not found
Stack: main@default.dbj:201, Loader.init@loader.js:17, Loader.loadScripts@loader.js:135, OrgTorch@orgtorch.js:429, @orgtorch.js:178, Attack.kill@attack.js:229

Attack.kill(707): Target not found

	Scripts.OrgTorch = false; 
		Config.OrgTorch.MakeTorch = true; 
		Config.OrgTorch.WaitForKeys = false; 
		Config.OrgTorch.WaitTimeout = 15; 
		Config.OrgTorch.UseSalvation = true; 
		Config.OrgTorch.GetFade = false; 
	

Thanks.

**Comment by tlwh163** [comment]
Private service is like this

**Comment by zain122** [comment]
Yes.Private service.How to run OrgTorch Script.

**Comment by zain122** [comment]
Yes.Private service.How to run OrgTorch Script.

**Comment by tlwh163** [comment]
I am modifying the script like this. There are some garbled characters that are Chinese comment information. You can ignore


    //遍历当前地图 搜寻指定ID的怪物
    this.findBoss = function (bossId) {
        var result, myRoom, room = getRoom(), rooms = [];
        if (!room) return false;
        function RoomSort(a, b) {
            return getDistance(myRoom[0], myRoom[1], a[0], a[1]) - getDistance(myRoom[0], myRoom[1], b[0], b[1]);
        }
        do {
            rooms.push([room.x * 5 + room.xsize / 2, room.y * 5 + room.ysize / 2]);
        } while (room.getNext());
        while (rooms.length > 0) {
            if (!myRoom) room = getRoom(me.x, me.y);
            if (room) {
                if (room instanceof Array) myRoom = [room[0], room[1]];
                    else myRoom = [room.x * 5 + room.xsize / 2, room.y * 5 + room.ysize / 2];
            }
            rooms.sort(RoomSort); room = rooms.shift();
            result = Pather.getNearestWalkable(room[0], room[1], 18, 3);
            if (result) {
                Pather.moveTo(result[0], result[1]); delay(50);
                if (getUnit(1, bossId)) return true;
            }
        } return false;
    };

	// 击杀UBER的具体过程
	this.pandemoniumRun = function () {
		switch (me.area) {
		case 133: // 女王巢穴-莉莉丝 Matron's Den
			Precast.doPrecast(true);
            if (this.findBoss(707)) Attack.kill(707);
			Pickit.pickItems(); Town.goToTown(); break;
		case 134: // 遗忘沙漠-督瑞尔 Forgotten Sands
			Precast.doPrecast(true);
            if (this.findBoss(708)) Attack.kill(708);
   			Pickit.pickItems(); Town.goToTown(); break;
		case 135: // 苦难熔炉-依卒尔 Furnace of Pain
			Precast.doPrecast(true);
            if (this.findBoss(706)) Attack.kill(706);
   			Pickit.pickItems(); Town.goToTown(); break;
		case 136: // 崔斯特瑞姆-UBER3BOSS Tristram
			var skillBackup = Config.AttackSkill[2]; //临时保存战斗设置
            var TpBackup = Pather.teleport;  //临时保存TP设置
			Precast.doPrecast(true); Pather.teleport = false;     //关闭TP
			if (me.getSkill(125, 1) >= 1) {Config.AttackSkill[2] = 125; Skill.setSkill(125, 0);} //救助
            if (me.getSkill(123, 1) >= 20) {Config.AttackSkill[2] = 123; Skill.setSkill(123, 0);} //审判
			if (this.findBoss(704)) Attack.kill(704);
            Pather.teleport = TpBackup; Config.AttackSkill[2] = skillBackup; //还原战斗设置
			if (this.findBoss(709)) Attack.kill(709);
			if (this.findBoss(705)) Attack.kill(705);
   			Pickit.pickItems(); this.checkTorch(); break;
		}
	};

**Comment by zain122** [comment]
Thank you very much.@tlwh163
