### ISSUE TITLE
Need help, How do i mute my bot from saying its cleared the seals after it makes a tp.

### ISSUE THREAD

**Issue by Jabbie4432** [kolton/d2bot-with-kolbot#1519]
Hi how do i stop the Lead bot from saying 
'clear Grand Vizier Of Chaos'
'clear Infector Of Souls'
'clear Lord De Seis'
And opening portals at every seal
after it clears the seals in chaos
Im pretty sure i have the rite config to stop it but it wont stop:

Scripts.OuterSteppes = false;
    Scripts.Izual = false;
    Scripts.Hephasto = false;
    Scripts.Vizier = false; // Intended for classic sorc, kills Vizier only.
    Scripts.FastDiablo = false;
    Scripts.Diablo = true;
        Config.Diablo.WalkClear = false; // Disable teleport while clearing to protect leechers
        Config.Diablo.Entrance = true; // Start from entrance
        Config.Diablo.SealWarning = "";
        Config.Diablo.EntranceTP = "";
        Config.Diablo.StarTP = "";
        Config.Diablo.DiabloMsg = "";
    Scripts.SealLeader = false;

**Comment by tlwh163** [comment]
Config.LocalChat.Enabled = true;
	Config.LocalChat.Toggle = false;
	Config.LocalChat.Mode = 1;

ALL of you team anyone
