### ISSUE TITLE
D2botLead

### ISSUE THREAD

**Issue by VtecPower** [kolton/d2bot-with-kolbot#152]
is there a way to make leader say 2 joinmessage? like

.login
Join me for Best .............

same for after game message
 
AND
 can we add our time delay in the "AnnounceGame"
like : Next Game will be ******* in 20 sec 
 
lmk if some of these are possible:

**Comment by dzik87** [comment]
`FirstJoinMessage: "", // Default join message. Can be an array of messages`

according to that you can do:

`FirstJoinMessage: [".login", "Join me for Best ............."], // Default join message. Can be an array of messages`

To achieve timer in game announcing you need add some kind of timer into it.
