### ISSUE TITLE
what game time with 8 bots same IP to avoid realm down?

### ISSUE THREAD

**Issue by sasquach15** [kolton/d2bot-with-kolbot#1522]
hi guys, constantly getting realm down while botting with 8 bots in 1 game (all from 1 computer/ 1 IP)
my game lenght is 7 minutes, rarely getting crashes/ chickens yet still getting realm downs every 2-4 hour
im afraid it will end with 2week realm down, had that once before

i though 7 min per game is enough to avoid that kind of issue but seems i was wrong
anyone knows what game lenght should i set to aviod realm downs?

**Comment by IGhostcrawler** [comment]
8 * 1.66 = 13.28 minutes of gametime minimum

**Comment by sasquach15** [comment]
> 
> 
> 8 * 1.66 = 13.28 minutes of gametime minimum

where did you get that info? how about rule 100games/12h?
i will change gametime to 13:28 but i'd like to know why is that

**Comment by oband2** [comment]
u can only do 100games/12 hour pr IP adress, has nothing to do with cdkey etc
if u want to do 8 players your games must be 7:20 x 8 to avoid queue time.

Lmk if u need help with more IP adress', u can add me on discord thomes#1771
