### ISSUE TITLE
Shopbot not stashing shopped items

### ISSUE THREAD

**Issue by Mikeyc123** [kolton/d2bot-with-kolbot#1530]
Hi,

I've ran shopbot with Anya for a couple days now and it's not stashing any items it's shopped. The items are in shopbot.nip and they show up on my pickit log that they have been shopped but when I log onto the character the shopped items aren't in stash. My character's inventory is open under char config. I'm stumped what it could be. Anyone know how to fix this?

**Comment by mf022** [comment]
> My character's inventory is open under char config.

be sure you have configured it properly https://github.com/blizzhackers/documentation/blob/master/kolbot/CharacterConfig.md#inventory-lock-configuration

**Comment by 5noop** [comment]
Did you add shopbot.nip to your pickit list, like this `Config.PickitFiles.push("shopbot.nip");` ? Or the items you shopped are already in your current pickit ?

**Comment by Mikeyc123** [comment]
Double checked inventory and it's configured correctly. 
I didn't add "shopbot.nip" under pickit file since it says in char config shopbot will automatically use that pickit. Hopefully the fix is that easy. I will swap out and report back. 
Thanks for the input guys

**Comment by mf022** [comment]
line 17 from [Shopbot.js](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/bots/ShopBot.js) is:
```
			filepath = "pickit/shopbot.nip",
```
so only [shopbot.nip](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/pickit/shopbot.nip) file should be loaded.

**Comment by DarkHorseDre** [comment]
@jaenster if I make the change to move this to config, I can slip this in with your PR? (,")

**Comment by Mikeyc123** [comment]
Swapped out "kolton.nip" with "shopbot.nip" under character config and bot is stashing items now. Thanks for the help guys

**Comment by Divisi0ns** [comment]
> line 17 from [Shopbot.js](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/bots/ShopBot.js) is:
> 
> ```
> 			filepath = "pickit/shopbot.nip",
> ```
> 
> so only [shopbot.nip](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/pickit/shopbot.nip) pickit file should be loaded.


Where do I get this file can you link it to me here please?? I'm having the same problem and mine shopbot file is different then this

**Comment by Divisi0ns** [comment]
> Swapped out "kolton.nip" with "shopbot.nip" under character config and bot is stashing items now. Thanks for the help guys


How do I fix mine, it's not stashing shopped items for me either,  please lmk

[img]https://i.ibb.co/r0phRq0/20200506-221501.jpg[/img]

[img]https://i.ibb.co/Z19Y9yv/20200506-221545.jpg[/img]

[img]https://i.ibb.co/bLBYZKH/20200506-221638.jpg[/img]

**Comment by Divisi0ns** [comment]
> Swapped out "kolton.nip" with "shopbot.nip" under character config and bot is stashing items now. Thanks for the help guys

is yours like this?? or how exactly is yours?? because mine is doing the same thing not stashing what it shops..
https://i.ibb.co/bLBYZKH/20200506-221638.jpg%5B/img%5D
