### ISSUE TITLE
Too many chars bo-ing at once

### ISSUE THREAD

**Issue by FireSauceGod** [kolton/d2bot-with-kolbot#1536]
I have a total of 5 bots running the same game. They all receive BO from the barb at the start of the game but when they clear chaos and throne room all chars bo at once after seals and waves. How do I get them to stop so just my barb continues to bo?

Edit: They all meeting in cata 2 for bo and then begin their MF scripts. Once they take their individual wp's to begin mf scripts they all bo and over write the barb bo.

**Comment by FireSauceGod** [comment]
I took away the other 4 bots CTA's and stashed them but if there is a work around so they can hold their CTA's and not ever bo that would be greatly appreciated.

**Comment by jaenster** [comment]
That is the best/easy fix indeed =)

**Comment by mf022** [comment]
>  but if there is a work around so they can hold their CTA's and not ever bo

maybe you should try to add some lines, just after the default line 20 from Precast.js
```
		if (me.classid !== 4 && getScript(true).name.toLowerCase() === "libs/bots/mfhelper.js") {
			return false;
		}
```

**Comment by tlwh163** [comment]
no cta if u brave man, Because the BOBAR is long enough

**Comment by mf022** [comment]
> the BO Barb is long enough

and if isn't there can be some choices like @nag0k script for HC players
https://d2bot.discourse.group/t/how-to-get-kolbot-to-bo-more-then-once-per-game/44/2
