### ISSUE TITLE
my bot pick items like rings amulet and put in stash without identify them :P

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1540]

**Comment by RaduCiurescu** [comment]
This is my char conf https://pastebin.com/haFazKrM
and this my kolton  https://pastebin.com/4k6SiXfr 
WHERE IS WRONG ? :D 
help please !
thx
!

**Comment by aim2kill** [comment]
Make sure in the LLD there not a ring/amulet


    // Pickit config. Default folder is kolbot/pickit.
    Config.PickitFiles.push("kolton.nip");
    Config.PickitFiles.push("LLD.nip");
    Config.PickRange = 39; // Pick radius
    Config.FastPick = true; // Check and pick items between attacks

**Comment by RaduCiurescu** [comment]
thank you !!
i took ldd out .
