### ISSUE TITLE
my bot stop at log account

### ISSUE THREAD

**Issue by mike651** [kolton/d2bot-with-kolbot#155]
hello , I'm using for the first time D2bot . I have trouble configuring the totaliter ... For the moment I followed the help getting started . I am, however, faced with a problem : my bot start the game , go to the main menu and then do not do anything (I assume to have forgotten a few things but I can not find or )

**Comment by mboufos** [comment]
Hello , after blizz patch i think that kolbot is not working :)

**Comment by mike651** [comment]
ah crap , does anyone know of a botD2 works for the patch1.14B and in passing why not maphack : D Thanks !

**Comment by mboufos** [comment]
There are some custom fix's but all are detectable so just wait a bit :D more heheheh

**Comment by mike651** [comment]
Hello , I tested D2NT and I am facing a problem after you configure the script my character creates the game no longer displays a configuration error but leaves the game directly to recreate another ...
Will someone be able to help me ?
I just copy the script if it can help you thank you :)
