### ISSUE TITLE
my bot put items in stash without identify them ,what can i do ? help !fast!pls!ty

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1553]
https://pastebin.com/2N2HCQUf                 my necro config ty!

**Comment by DarkHorseDre** [comment]
It will be down to what you specified in your pickit file

you need to check the item type and stats (which you didnt mention) and the corresponding entries in your pickit

**Comment by oband2** [comment]
Your pickit file would prolly be "kolton.nip"

Here is a list of all the items your bot picks up.

If your item is like [Name] = diadem # Unique

Then it will just keep a unid diadem which would be griffon, then u would need to type in the specific stats on the griffons u would like to keep e.g. +15 to lightning dmg, however u need to fine the correct code for that.

**Comment by RaduCiurescu** [comment]
yeah sorry i forgot ,but that s my kolton https://pastebin.com/6FQPirft .

**Comment by DarkHorseDre** [comment]
ok and which items did you have problems with?  kinda need to piece this together ;)

**Comment by RaduCiurescu** [comment]
rings ,amulets ,arachnid ,dusk armor which is ormus ,nosferatu ,andy ...

**Comment by DarkHorseDre** [comment]
your config has these 2 entries:
`    Config.PickitFiles.push("kolton.nip");`
`    Config.PickitFiles.push("LLD.nip");`

and yet you linked 1 nip file.  You should have linked both ofc.

I cant see issues with your kolton at a quick glance (except that of below) but you need to check your LLD.nip.  if you didnt purposely set this LLD nip then best to disable this nip as it could be causing conflict and it gives you more lines to check.  only enable nips and entries within nips that you know you need and understand.

ok, so arachs as an example:

you have 2 entries - one for eth and one for non eth:
`[name] == spiderwebsash && [quality] == unique && [flag] != ethereal # [enhanceddefense] <= 120`
`[name] == spiderwebsash && [quality] == unique && [flag] == ethereal # [enhanceddefense] <= 120`

you could just have one line to represent both - this reduces your pickit size and chances of error
`[name] == spiderwebsash && [quality] == unique # [enhanceddefense] <= 120`

also - try the nip checker - its not gonna fix every issue but covers most - https://github.com/noah-/NipCheck

**Comment by RaduCiurescu** [comment]
Thank you ! This helped me so much !
