### ISSUE TITLE
how can i make him to pick essence and do tokens ?

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1554]

**Comment by DarkHorseDre** [comment]
not sure but a quick check shows iphunter uses beep:
`beep();` // works if windows sounds are enabled

**Comment by RaduCiurescu** [comment]
thanks anyway but I think i have solved by adding in kolton this: "// RESPEC ESSENCES
[Name] == TwistedEssenceOfSuffering # # [MaxQuantity] == 5
[Name] == ChargedEssenceOfHatred # # [MaxQuantity] == 10
[Name] == BurningEssenceOfTerror # # [MaxQuantity] == 10
[Name] == FesteringEssenceOfDestruction # # [MaxQuantity] == 10 "
and I deleted the two " // " from the front 359 line of the char config .

**Comment by DarkHorseDre** [comment]
sorry bro, typed answer to wrong topic lol

there are 2 ways to do this. The main way is to enable cubing of the token, and bot will collect the correct essences WITHOUT you having to enable pickit:

`Config.Recipes.push([Recipe.Token]);` // Make Token of Absolution

doing your way without enabling this wont make token

if you do it your way and enable cubing, you will store too many essences.  better to enable cubing but not specify essences in pickit (unless you want spares, but eventually you wont want space lost to essences and will just want the tokens)

**Comment by RaduCiurescu** [comment]
RIGHT! ,thank you ! :D
