### ISSUE TITLE
sound on finding

### ISSUE THREAD

**Issue by lacid** [kolton/d2bot-with-kolbot#1555]
is there a way for bot to alarm when it finds something, like some windows sound or how could I add that?

**Comment by DarkHorseDre** [comment]
never tried but I see iphunter does this:

me.overhead("IP found!");
			`beep();` // works if windows sounds are enabled
			Town.move("waypoint");
			Town.move("stash");

**Comment by lacid** [comment]
I've put it to town.js into stash function.. and it works, thanks.

**Comment by RaduCiurescu** [comment]
more exactly where you put it? :)

**Comment by DarkHorseDre** [comment]
He said stash function, probably somewhere here:

```
if (result) {
		Misc.itemLogger("Stashed", items[i]);						 
                 Storage.Stash.MoveTo(items[i]);

**Comment by lacid** [comment]
thanks, I have already replied in Radus new thread https://github.com/kolton/d2bot-with-kolbot/issues/1561

**Comment by RaduCiurescu** [comment]
under which one line ? ^&^

**Comment by lacid** [comment]
already answered in your new thread #1561
