### ISSUE TITLE
its possible to set the bot to do just worldstone keep level 2 and 3  ?

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1557]

**Comment by DarkHorseDre** [comment]
I cant test right now (maybe someone else will) but try this:

You could copy the worldstone script and run it as a new script and edit it, or edit the main one.

current code (my old version is prolly the same):
```
	if (Pather.moveToExit(128, true)) {
		Attack.clearLevel(Config.ClearType);
	}

	if (Pather.moveToExit([129, 130], true)) {
		Attack.clearLevel(Config.ClearType);
	}
```
comment out the pather.movetoexit(128,true)) block:

	/*if (Pather.moveToExit(128, true)) {
		Attack.clearLevel(Config.ClearType);
	}*/

this should make bot clear WSK2, then move to WSK3, clear that and exit as normal

**Comment by RaduCiurescu** [comment]
yep that worked ty
