### ISSUE TITLE
Question about AutoSmurf and 8 ppl parties

### ISSUE THREAD

**Issue by ElDiGee** [kolton/d2bot-with-kolbot#1558]
If I run a small 4 player party my autosmurf runs smoothly. Now I wanted to setup a 8 player Party. So far so good. They all join the game and everyone writes, that he is ready, then the bots #1-4 going outside the town and start waiting for bot #5-8 to come, but they are only standing near the wp and will w8.

the last message I get// they print is:

> Received team is ready!
startSharing: true lowestAct: 1

I also tried GZer's script (https://github.com/GZer/MyKolbot), but had a little trouble when I only added a few lines here and there and added "LevelFollower" + "LevelLeader" to my files. I did not want to commit fully to an older version. Before I do that, is there a way to get autosmurf working with the current updated version? If you guys need any files let me know.

```
//misc : starting & teams
		var lowestAct, // Doesn't need to be a global variable, but must be declared when all players are in their highest Act.
			startSharing = this.partyLevel(6); // Doesn't need to be a global variable.

		while (!lowestAct) { // Wait for everyone to get back to their Town, then record the lowest Town.
			lowestAct = this.partyAct();

			delay(250);
		}

		print("startSharing: " + startSharing + " lowestAct: " + lowestAct);
```
---------------------------------------------------------------------------------------------
```
//---------------------Assembling waypointsToReceive & waypointsToShare---------------------
		for (var i = 0 ; i < myWaypoints.length ; i += 1) { 		// Loop thru the myWaypoints list.
			if (startSharing &&										// Team Members need to be at least Level 8, otherwise they might not have a Town Portal Tome.
					i < 8 || 										// Cold Plains thru Catacombs Level 2 have no additional requirements.
					(i >= 8 && i <= 15 && lowestAct > 1) ||			// Sewers Level 2 thru Canyon Of The Magi requires at least Act 2.
					(i >= 16 && i <= 23 && lowestAct > 2) ||		// Spider Forest thru Durance Of Hate Level 2 requires at least Act 3.
					((i === 24 || i === 25) && lowestAct > 3) ||	// City Of The Damned and River Of Flame require at least Act 4.
					(i >= 26 && i <= 33 && lowestAct > 4)) {		// Frigid Highlands thru Worldstone Keep Level 2 requires Act 5.
				if (myWaypoints[i]) { // I have the waypoint.
```

are btw the only lines I found mentioning startSharing.
But I actually don't think that there is something wrong with that line, they just seem to get stuck in it.

![Problem](https://user-images.githubusercontent.com/50920008/58882754-3f55e900-86dd-11e9-95a8-68b27a480286.png)

I moved the other 3 who also don't move, outside town, but basically 4 go outside and update their console/status and 4 stay at their wp's (a1 or a2). 

Here is the Leader + his other 3 - who move according to plan and then start w8ing outside of town (I pasted in the part he wrote when he started w8ing outside of town)
Why are only 4 players able to "move on" after sharing wps and the other 4 get stucked in a loop?
Will try and check my scripts etc. but have no clue where to start.
![Unbenannt](https://user-images.githubusercontent.com/50920008/58883635-19314880-86df-11e9-9a94-b686af4b2237.png)

solved it myself - had a bit interference with another part of that GZ script ...only a small problem left now this can be closed tho

**Comment by JordanBlais-Help** [comment]
Hey, 

Anyway you could let me know how you fixed this or if possible send me your Kolbot Folder I’ve been stuck on this for a few days. I cannot seem to get the chars to work. I’m using 2 Druid, 2 Sorc 2 Paladin,
Let me know thanks!

**Comment by bozodude** [comment]
Check this ~line 407 (depending on char)
**Config.BossPriority = true; // Set to true to attack Unique/SuperUnique monsters first when clearing
	Config.ClearType = 0; // Monster spectype to kill in level clear scripts (ie. Mausoleum). 0xF = skip normal, 0x7 = champions/bosses, 0 = all**

Make sure the character is set to clear. The scripts running are telling the bots to clear areas, if the clear type is non existent they will wait for party at some next location because they think everything is cleared.
