### ISSUE TITLE
sound on finding #2

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1561]
I have seen above how to do but I do not know exactly where to put

me.overhead (" IP found! ");
beep (); // works if windows sounds are enabled
Town.move ( "waypoint");
Town.move ( "stash"); 

in stash function, who can help me?

**Comment by lacid** [comment]
I have put it into town.js file, after the line 1544, it will _beep_ only when stashing items into stash, not gold which is ok.

```
if (result) {
	Misc.itemLogger("Stashed", items[i]);
	Storage.Stash.MoveTo(items[i]);
	beep(); // works if windows sounds are enabled
}
```

**Comment by RaduCiurescu** [comment]
done, thx !
