### ISSUE TITLE
my paladin use holy shield on cta .

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1562]
what can i do ? :)

**Comment by DarkHorseDre** [comment]
please explain clearly

**Comment by ARkaine2** [comment]
DarkHorseDre,

I have the same problem, but with sorceress.
Let's say that on swap i have CTA+Lidless Wall (my sorc build has not enough strength to equip Spirit [Sonarch], so on swap is Lidless) -- that's 2 skills.
Main weapon is HotO+something that's at least 3 skills.

For example:
Sorc gave herself and her mercenary BC & BO.
And it will be better to cast ES from main weapon.

**Comment by DarkHorseDre** [comment]
there was a problem with weapon switch which is also used in precast - ensure youre using the latest version of kolbot as there were fixes

weapon switch code should workout the best slot with most skills for the precast skill in question.  note that default code does not consider skills where no hard points are spent (e.g. no points in ES but ES on item - wont see it)
