### ISSUE TITLE
my bot don t stash gold 

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1564]
this is my char config https://pastebin.com/i4WriQF0

**Comment by lacid** [comment]
related issues
https://github.com/kolton/d2bot-with-kolbot/issues/119
https://github.com/kolton/d2bot-with-kolbot/issues/204

**Comment by RaduCiurescu** [comment]
don t work :P

**Comment by lacid** [comment]
what lvl is your char? maybe he's not picking because he's full and not gambling, based on your gamble settings you should be at least 94lvl to start gamble at `Config.GambleGoldStart = 3440000;`

or check your kolton.nip file, must be there

**Comment by RaduCiurescu** [comment]
he is 94

**Comment by DarkHorseDre** [comment]
@RaduCiurescu you've done it again - asking for help but not showing the files needed - your pickit determines if gold is picked - share that at the same time as your config

**Comment by RaduCiurescu** [comment]
ah ,sorry ,i compared with clasic char config and i found the problem :D
my misstake ^^
