### ISSUE TITLE
follower fail to click battle.net

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1567]
is it just me or what I ripped  < https://raw.githubusercontent.com/kolton/d2bot-with-kolbot/master/d2bs/kolbot/D2BotFollow.dbj

only clicks other /join-host

I know a bit about entry points I think I had changed every possiable control click but I failed

**Comment by ElDiGee** [comment]
Not sure if I understand you. But from what I am getting you should add ur profile name here

`*/

var JoinSettings = {
	"Leader": ["Leecher"]
};`

and replace "Leader" with ur D2BotLead Profile name and ["Leecher"] with all or whatever Profile u are using as D2BotFollow.

Should look like this "gtoiletLeader":["gtoiletFollow"] or like this "gtoiletLeader":["all"]

**Comment by gtoilet** [comment]
yea I know to do that , reguardless it still clicks other
