### ISSUE TITLE
how to put to do just good chests in lower kurast ?

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1568]

**Comment by ElDiGee** [comment]
`Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
		//Config.ChestMania.Act1 = [13, 14, 15, 16, 18, 19]; // List of act 1 areas to open chests in
		//Config.ChestMania.Act2 = [55, 59, 65, 66, 67, 68, 69, 70, 71, 72]; // List of act 2 areas to open chests in
		Config.ChestMania.Act3 = [79, 80, 81]; // List of act 3 areas to open chests in
		Config.ChestMania.Act4 = []; // List of act 4 areas to open chests in
		//Config.ChestMania.Act5 = [115, 116, 119, 125, 126, 127]; // List of act 5 areas to open chests in	`

**Comment by RaduCiurescu** [comment]
thank you !

**Comment by gtoilet** [comment]
or do you mean only open the golden chests?

**Comment by RaduCiurescu** [comment]
yeah

**Comment by gtoilet** [comment]
im sure theres somewhere to define what chests to open but im not sure where

@noah or @DarkHorseDre

might know where the few people on here that I know have the knowledge of where it might be

**Comment by DarkHorseDre** [comment]
Pahhahahaha! I get more wrong than I get right! :p  and Noah defo knows but prolly wont see this/have time.. there are others *coughcough @5noop cough*

I don't use chestmania but I can see it uses area id's, and I assume it uses misc.js containers.. so,
if you want to isolate the chest types, you'd need to modify that list, but.. it would affect all chests..

This block in misc shows MOST of the containers (I found a new one the other day):
```
		// Testing all container code
		if (Config.OpenChests === 2) {
			containers = [
				"chest", "loose rock", "hidden stash", "loose boulder", "corpseonstick", "casket", "armorstand", "weaponrack", "barrel", "holeanim", "tomb2",
				"tomb3", "roguecorpse", "ratnest", "corpse", "goo pile", "largeurn", "urn", "chest3", "jug", "skeleton", "guardcorpse", "sarcophagus", "object2",
				"cocoon", "basket", "stash", "hollow log", "hungskeleton", "pillar", "skullpile", "skull pile", "jar3", "jar2", "jar1", "bonechest", "woodchestl",
				"woodchestr", "barrel wilderness", "burialchestr", "burialchestl", "explodingchest", "chestl", "chestr", "groundtomb", "icecavejar1", "icecavejar2",
				"icecavejar3", "icecavejar4", "deadperson", "deadperson2", "evilurn", "tomb1l", "tomb3l", "groundtombl"
			];
		}
```
so I'd do this (top of my head as I write this quickly before my boss see's):

1. identify the chest names/types and list separately in misc.js/kurast script
2. setup a way to use this new container set for lower kurast only (maybe add `Config.OpenChests === 3` within chestmania and then make a new if block as above checking for the value '3'?  a better way but more changes would be to add a new config option to profile and config.js for lowerkurast only - depends if you want this for all toons and if you can be bothered?)
3. script will run as normal but only open those chestids in that area for that script.

If you get stuck and nobody else helps and can wait 10 hours, give me a shout and I'll test it at home

**Comment by gtoilet** [comment]
Config.OpenChests === 3

right below the first townchores in chestmaina.js resulted in skipping things like basket , stash , skull piles

but if you put 2 and the container list and add containers  to the var
and edit the containers list that you just put in the chestmaina.js
will result in only open that list vs the list in misc

**Comment by DarkHorseDre** [comment]
yeah i directly referenced that but suggested an alternative to fit the brief in OP.
==2 is the wider list but you may not want to add all of them as they will slow you down (e.g. baskets in act 3) or get you killed (e.g. baskets in durance of hate).

if you enable option 2 for whole of chestmania your runs will be much longer

**Comment by RaduCiurescu** [comment]
thx
