### ISSUE TITLE
please view your exceptions.log file. d2bot# will close now 

### ISSUE THREAD

**Issue by sasquach15** [kolton/d2bot-with-kolbot#1571]
hi, got this message every 1-2 days. after that my bots stop until i close manager and start all bots again. pretty annoying
when i open exceptions.log i see:

04.06.2019 18:13
System.IO.IOException: Proces nie może uzyskać dostępu do pliku „C:\Users\sasa\Desktop\botino\logs\keyinfo.log”, ponieważ jest on używany przez inny proces.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   w System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   w System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   w System.IO.StreamWriter..ctor(String path, Boolean append)
   w D2Bot.Main.HandleMessage(IntPtr hWnd, String message)
   w D2Bot.Main.<>c__DisplayClass57_0.<WorkThread>b__0()

what means 'proccess cannot get acces to file [...] becouse it is currently in use by another proccess'

any idea why i have this issue?

**Comment by ls9009** [comment]
Why did you close this, im having the same issue
