### ISSUE TITLE
force repair

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1572]
title ... want to force repair at chores not when about breaks

**Comment by gtoilet** [comment]
also how to
	Pickit.pickItems();
gold droped at vendor in town

**Comment by DarkHorseDre** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/1201

**Comment by DarkHorseDre** [comment]
`this.repair();` is called at the start of town.js.
call town this.repair() whenever you are in town and want to repair (so tp first)

**Comment by romaingallay** [comment]
You can change the default behavior of doChores in town.js by setting `repair = true` as default parameter.
```doChores: function (repair = true) {```
It's from a recent commit so don't forget to update.

**Comment by gtoilet** [comment]
thanks @darkhorsedre
@romaingallay , that's what I needed

**Comment by DarkHorseDre** [comment]
yeah I havent updated in ages xD

**Comment by gtoilet** [comment]
when your barb has a lower durb wep
I want him to run repair at every start of script as he runs helpers before cs
