### ISSUE TITLE
force minishopbot

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1574]
trying to send toon to npc interact trade and push minishopper
this interacts npc and trades but the minishopper don't scan npc

		Town.move(NPC.Drognan);
		Drognan = getUnit(1, NPC.Drognan);
		Drognan.startTrade("MiniShopBot");

**Comment by DarkHorseDre** [comment]
Why cant you just call Town.shopItems? it seems to do all the shopbot stuff inc. selecting and interacting npc in whichever town youre in

**Comment by gtoilet** [comment]
that doesn't show that it scanned for items via the minishopbot msg in console

		Town.move(NPC.Drognan);
		Drognan = getUnit(1, NPC.Drognan);	
		Drognan.startTrade("Town.shopItems");
or when I remove the Drognan.startTrade
and just have it  as
Town.shopItems


guess ill try to work in the function for buying potions thanks men

**Comment by DarkHorseDre** [comment]
so your additional requiremnetn is that you want it to show what it scanned in the console?
if this isnt standard, add it via `D2Bot.printToConsole("messge", n);`?

what im staying is taht at start of town.js you have `this.shopItems();` so why cant you just do that whenever you need?

**Comment by gtoilet** [comment]
this works

Town.initNPC("Shop", "drogcheck");
Town.shopItems();
me.cancel();
