### ISSUE TITLE
KolBot and Horadric Cube

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1576]
How (and: is it possible) to make KolBot move items into Horadric Cube?
Not for receipe, but to keep item(s) untill character will get to town.

**Comment by DarkHorseDre** [comment]
short answer is yes, with customisation, but it could also conflict with it trying to cube things.  I'd avoid it and just use stash & inv. space more efficiently.

**Comment by gtoilet** [comment]
but what if there is no transmuting going to be used for the cube
my classic barb doesn't cube anything but still has his cube top right inv
where would I change it for him

**Comment by DarkHorseDre** [comment]
ok sure, but then you have to code around reserving the space for cube but still using it for storage, then opening to look for items, placing items in and out of it.. its a lot to add == not worth doing

**Comment by DarkHorseDre** [comment]
.. if the barb isnt using it for cubing or anything at all, disable Config.Cubing and throw away the cube - he wont try to get another one and you can get the 2x2 space back
