### ISSUE TITLE
please help this error message

### ISSUE THREAD

**Issue by KOREAGOD** [kolton/d2bot-with-kolbot#1577]
i'm using follower.js  >> 
but this error message my leecher enter leader portal >>  [[  Leader Unit Found ]]  
and my characters all out room

why this situation ????

my english is so fucking bad sorry

**Comment by DarkHorseDre** [comment]
in the follower config ensure the config.leader is set, case sensitive
https://github.com/kolton/d2bot-with-kolbot/issues/1542

**Comment by gtoilet** [comment]
vouch DHD , only place to set config leader is in leaders char config

**Comment by DarkHorseDre** [comment]
no, config.leader is set in the followers config - it tells follower who is the leader

**Comment by KOREAGOD** [comment]
Config.Leader = "ABC";
Scripts.Follower = true

anything else???

**Comment by DarkHorseDre** [comment]
leader should issue invites and followers accept ofc..
