### ISSUE TITLE
Scanning items at armor npc's

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1579]
Hey its possible to make him to scan npc (which repair ur armor) too ,checking for circles :?

**Comment by DarkHorseDre** [comment]
yeah, enable minishopbot and ensure the circlets are in your picket.

(all items in your picket will be shopped if available AFAIK)

**Comment by RaduCiurescu** [comment]
thx

**Comment by RaduCiurescu** [comment]
yeah ,but i wanted to say if he can scan from another npcs shop ,like forgers (larzuk in a5 ,etc)
