### ISSUE TITLE
error on bot loading

### ISSUE THREAD

**Issue by deseis30** [kolton/d2bot-with-kolbot#158]
the error is as follows {

**Comment by deseis30** [comment]
object reference is not set to an instance of a object
on the newest version of d2bot.exe with kolbot

**Comment by deseis30** [comment]
I looked at those pull requests it didn't work there is nothing wrong with them, so basically the bot loads d2 and it just sits there and the screen either freezes or it does nothing and can not load d2 after that I click battle.net to manually so it and it doesnt even connect there.

**Comment by dzik87** [comment]
Looks like you are trying to run bot on 1.14 on outdated d2bs core. Try get versionhack from bh. Please be aware that versionhacked d2bs is not official release and it is not supported here.
