### ISSUE TITLE
Best attacks for light soso ? 

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1580]

**Comment by master2g** [comment]
Lightning?  What else is there?  charged bolt never does enough damage and chain lightning will never be as powerful as lightning.

**Comment by RaduCiurescu** [comment]
yeah

**Comment by RaduCiurescu** [comment]
so just lighting ? or light and chain ?

**Comment by master2g** [comment]
Well be aware that this forum is for ISSUES only, but you want to max these with lightning
Charged Bolt: +8% Lightning Damage Per Level
Nova: +8% Lightning Damage Per Level
Chain Lightning: +8% Lightning Damage Per Level
1 point static field

If you don't mind.  Please click the solved button to close this after you've read my reply.

**Comment by RaduCiurescu** [comment]
ok

**Comment by Bcubrich** [comment]
If it's PvM chain lighting is actually best. I config my bot to use lightning on all the area bosses, but CL on everything else.
