### ISSUE TITLE
My soso dont kill soul collector in chaos sanctay ,then she skip diablo :P

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1582]
what can i do ?

**Comment by RaduCiurescu** [comment]
https://pastebin.com/xwhwYEHY this is my char config .
Need help fast ,ty!

**Comment by mf022** [comment]
I guess that you are talking about **"Infector of Souls"**, so check the description line 479, and uncomment line 480
```
	Config.SkipException = [getLocaleString(2851), getLocaleString(2852), getLocaleString(2853)]; // vizier, de seis, infector
```

If you are talking about [**"Storm Casters"**](https://gamepedia.cursecdn.com/diablo_gamepedia/3/3b/Storm_Caster_%28Diablo_II%29.gif?version=04fa0111f5470cd0b5bbd457d0367037) in Hell mode those monsters are lightning immune, so finally those are skipped. In this case if you are running a lonely sorceress, be sure that you activate line 513:
```
	Config.TeleStomp = true; // Use merc to attack bosses if they're immune to attacks, but not to physical damage
```

**Comment by RaduCiurescu** [comment]
work now ,thx!!
