### ISSUE TITLE
KolBot loses keys

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1583]
Help please
Seems that bot buys pack of keys only when previous pack of keys is over.
Is it possible to make KolBot check amount of keys in inventory and make it buy keys when they are going to over?

![Screenshot003 c](https://user-images.githubusercontent.com/31447095/59147460-907b1b00-8a04-11e9-80bd-b273ad9738e0.jpg)

**Comment by mf022** [comment]
for buying keys check this line on your config:
```
	Config.OpenChests = true; // Open chests. Controls key buying.
```
otherwise you can add this line in your pickit:
```
[name] == key # # [maxquantity] == 12
```

**Comment by DarkHorseDre** [comment]
I was told to not lock the space where key is kept - maxquantity will help too

**Comment by ARkaine2** [comment]
Thanks a lot for clarifying answers! :)
