### ISSUE TITLE
its possile to add a second config for dodge?  help fasttt

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1584]
" Config.Dodge = true; // Move away from monsters that get too close. Don't use with short-ranged attacks like Poison Dagger.
	Config.DodgeRange = 6; // Distance to keep from monsters.
	Config.DodgeHP = 100; // Dodge only if HP percent is less than or equal to Config.DodgeHP. 100 = always dodge.
	Config.BossPriority = false; // Set to true to attack Unique/SuperUnique monsters first when clearing
	Config.ClearType = 0 // Monster spectype to kill in level clear scripts (ie. Mausoleum). 0xF = skip normal, 0x7 = champions/bosses, 0 = all
	Config.TeleStomp = true; // Use merc to attack bosses if they're immune to attacks, but not to physical damage "
this is my base but want to add ,i mean another part which will add dogerange = 15 when she is under 50

**Comment by gtoilet** [comment]
I was also thinking about something like this
sometimes the sorc when casting orb will stand in place and get hit by the oblivion knights range attacks
when theres a lot of them she will lose a lot of HP before she moves again

**Comment by RaduCiurescu** [comment]
Config.DodgeRange = 9 ; // Distance to keep from monsters.
	Config.DodgeHP = 100; // Dodge only if HP percent is less than or equal to Config.DodgeHP. 100 = always dodge.
	{ 
           if( Config.DodgeHP <= 55) 
			Config.DodgeRange = 15 ; // Distance to keep from monsters.
	}
 
i tried to add this " if " but don't know if works correctly
