### ISSUE TITLE
longer time to kill de seis

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1590]
sometimes my barb don't kill him , where do I add a longer kill time?
I didn't see much of anything in the diablohelper.js , in reguards as a time limit to kill him

**Comment by DarkHorseDre** [comment]
you havent provided any info but its probably not a timer but number of attack attempts in attack.js IIRC its about 300

**Comment by gtoilet** [comment]
I wasn't sure where to fix it that's why I didn't offer much info
thanks man ill look into it

**Comment by DarkHorseDre** [comment]
lol well i meant info on scripts running or attacks used/error messages/what it says when he "doesn't kill him". closest guess is exceeding attack count

**Comment by gtoilet** [comment]
yea some times hes just fast/Fanta enchant and barb don't kill him and sorc is orb only so she don't ever stick around , the only error it ever gets is when diablo don't show up from seis still alive

running pretty much stock helper.js only mod is fector/seis/visor and a command bo
https://raw.githubusercontent.com/kolton/d2bot-with-kolbot/master/d2bs/kolbot/libs/bots/DiabloHelper.js

**Comment by DarkHorseDre** [comment]
when you say "barb dont kill him" - what does that mean? barb stops attacking? error message? 

did changing the attack count help?

**Comment by gtoilet** [comment]
yea barb would just stop attacking , changing the attack.js fixed that problem I had

thanks , now to the next issue

**Comment by Toviv** [comment]
I actually decided to see if i could record her do it and she did it for me LOL here is a video

https://youtu.be/QKPi6CptZhw

sorry the extra black on the side, i just made a super quick obs profile and fucked it up lmao
