### ISSUE TITLE
Secondary skill if monster is immune to primary.

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1592]
there is that but what about a 2ndary to boss
where would I look did quick search of attack.js
didn't see anything that looked like I was looking for

**Comment by gtoilet** [comment]
tried this

	Config.AttackSkill[1] = 64,62; // Primary skill to bosses.

tried  [64,62]

both failed

**Comment by DarkHorseDre** [comment]
each attack is an element of an array.  you cant add 2 values to one array element (well there is such a thing as 2 dimensional array but kolbot wasnt coded to read 2 element values)

this should be the immune option for bosses
Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.

**Comment by gtoilet** [comment]
i tried that also but im only looking for a 2ndary boss attack , that also works for the oblivion knights and when she casts that she stands there and gets wrecked by their cast skills
