### ISSUE TITLE
Bot crashing fresh install

### ISSUE THREAD

**Issue by Magikilla** [kolton/d2bot-with-kolbot#1593]
Everytime i try and run the bot it says D2BS is not responding... Starting profile  when I have -w set in the peramiter but if i take it away and it runs in full window mode it logs me in and everything

does anyone have any idea how to fix this issue

**Comment by gtoilet** [comment]
could be a lot of things from that would assume your fully updated to lod 114
with all the right software to run bot

**Comment by Magikilla** [comment]
Yes everything is 100% done correctly this only happened when i uodated the bot from the last update

**Comment by DarkHorseDre** [comment]
never heard that before but sounds like d2bs maybe.  you're applying the -w to the profile in the parameter box, right?

I'd re-download the d2bot exe and dlls just in case there was corruption or incompatibility in version (dont update the manager from the update menu until all is stable)

**Comment by gtoilet** [comment]
ive only ever seen that exact msg when I was trying to get my classic only install to work on d2bs
or when something wasn't up to date enuf

**Comment by Magikilla** [comment]
Ive uninstalled and reinstalled it 4 times still same issue. It inly works if i take everything out of the peramiters and it runs in full screen mode

**Comment by gtoilet** [comment]
-w -sleepy -ftj

what mine runs under

**Comment by Magikilla** [comment]
Ya i have that put and still same issue

**Comment by gtoilet** [comment]
well assume it run as admin .. would be about the only thing I got left to add

**Comment by Magikilla** [comment]
Ya it is ran as admin :-(

**Comment by DarkHorseDre** [comment]
It's weird as Kolbot needs window mode and shouldn't work/work well in full screen..

it wont be admin as he didnt change that inbetween failures and successes.

Can you run the game without d2bs in window mode? (create a shortcut to programfiles and add the -w)?

**Comment by Magikilla** [comment]
Yes i can olay the game in window mode without d2bs

**Comment by DarkHorseDre** [comment]
mate i would re-download the kolbot files (mainly the d2bs.exe and dll, but do all if you're not sure)

download a fresh copy, make no changes other than to CREATE a new profile, point to your install and run the game

**Comment by DarkHorseDre** [comment]
looool dayum you just jinxed then bro :)

you followed the guide inc. dependencies? https://github.com/kolton/d2bot-with-kolbot/wiki

@5noop @jaenster @noah- any ideas?

**Comment by Magikilla** [comment]
Yes i followed the guide 100%

**Comment by 5noop** [comment]
Try to launch d2bot with win7 compatibility, I heard it fixed the not responding thing for some people.

**Comment by DarkHorseDre** [comment]
Good shout @5noop but I have one of mine running in compat and one not.. if he doesn't get lucky, what you think about fact the game runs natively in window mode but not via d2bot?

**Comment by Magikilla** [comment]
@5noop ill try that when i get home and let u guys know

**Comment by 5noop** [comment]
@DarkHorseDre no idea, I'm not familiar with d2bs/d2bot

**Comment by maelstrm30** [comment]
@Magikilla figured out his issue.  It's a thing from the past, but it worked.  Setting diablo2.exe, game.exe, and d2bot.exe in Win7 Compat mode fixed his issue.

**Comment by DarkHorseDre** [comment]
yeah 5noop called that one out!

**Comment by gtoilet** [comment]
i wouldn't have suggested comp since I never think of that I only run win 7 machines and they run bot ez

**Comment by DarkHorseDre** [comment]
funny thing is i was on win 7 couple months ago, now win10: 1 on compat one not.. different versions of d2bot tho..
