### ISSUE TITLE
how can my follow always pick item?

### ISSUE THREAD

**Issue by okokoksss** [kolton/d2bot-with-kolbot#1596]
my follows didn`t pick up items except for the potions.
So I always have to press P button when the battle is over.
How can I always pick up an item without pressing P button?
Or, what command can you set so that you can always pick up an item or not pick it up?

thank for your help

**Comment by DarkHorseDre** [comment]
sounds like you may need to add a pickit line - which entry script and config scripts are your followers running? (follower.js, rushee, mfhelper, other?..)

**Comment by okokoksss** [comment]
> sounds like you may need to add a pickit line - which entry script and config scripts are your followers running? (follower.js, rushee, mfhelper, other?..)

my Character script in  Scripts.Follower = true 
so.. it`s mean follower.js maybe
and already add pickit line
But my followers only pick up items when they open the chest.
My followers don't pick up items until I press the P button.

**Comment by gtoilet** [comment]
some line somewhere after their attack function
looks like line
678
add a pickit after this.pickpotions
give feed back about it

**Comment by DarkHorseDre** [comment]
ok so follower is designed that way.  only pick potions and pickit chests only.  they created a command for P to pick. saves you having to search through 7 followers for a good item you saw/want/need to drop.

look for these lines: 
``` javascript
Misc.openChest(unit);
Pickit.pickItems();
```
thats explicit auto pickit when dealing with chest.

for attacks, just find the attack lines and include a pickitems after each and before the return:
``` javascript
Attack.clear(20, false, false, false, false);
this.pickPotions(20);
```

becomes:
``` javascript
Attack.clear(20, false, false, false, false);
this.pickItems(20);
```

there is one more attack.clear I can see but do check the whole script

**Comment by okokoksss** [comment]
> thats explicit auto pickit when dealing with chest.

oh i understand
thx for your help :) 👍

**Comment by okokoksss** [comment]
> ok so follower is designed that way. only pick potions and pickit chests only. they created a command for P to pick. saves you having to search through 7 followers for a good item you saw/want/need to drop.
> 
> look for these lines:
> 
> ```js
> Misc.openChest(unit);
> Pickit.pickItems();
> ```
> 
> thats explicit auto pickit when dealing with chest.
> I cant test this, but try: for attacks, just find the attack lines and include a pickitems after each and before the return:
> 
> ```js
> Attack.clear(20, false, false, false, false);
> this.pickPotions(20);
> ```
> 
> becomes:
> 
> ```js
> Attack.clear(20, false, false, false, false);
> this.pickItems(20);
> ```
> 
> there is one more attack.clear I can see but do check the whole script

Attack.clear(20, false, false, false, false);
this.pickItems(20); << it`s error

Attack.clear(20, false, false, false, false);
this.pickItems(20);

**Comment by okokoksss** [comment]
> ok so follower is designed that way. only pick potions and pickit chests only. they created a command for P to pick. saves you having to search through 7 followers for a good item you saw/want/need to drop.
> 
> look for these lines:
> 
> ```js
> Misc.openChest(unit);
> Pickit.pickItems();
> ```
> 
> thats explicit auto pickit when dealing with chest.
> I cant test this, but try: for attacks, just find the attack lines and include a pickitems after each and before the return:
> 
> ```js
> Attack.clear(20, false, false, false, false);
> this.pickPotions(20);
> ```
> 
> becomes:
> 
> ```js
> Attack.clear(20, false, false, false, false);
> this.pickItems(20);
> ```
> 
> there is one more attack.clear I can see but do check the whole script

oh testing and find error

> Attack.clear(20, false, false, false, false);
> this.pickItems(20); <<< it`s error

> Attack.clear(20, false, false, false, false);
> this.pickPotions(20);
> Pickit.pickItems(); 

so i did it
very good work
thx

**Comment by DarkHorseDre** [comment]
haha yeah sorry i wasnt sure if a range is supplied with pickitems :)

remove pickpotions as it should pick potions when you pickitems and if they are in your pickit

**Comment by okokoksss** [comment]
> haha yeah sorry i wasnt sure if a range is supplied with pickitems :)
> 
> remove pickpotions as it should pick potions when you pickitems and if they are in your pickit

thx for your help :)
