### ISSUE TITLE
spawnable skills

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1598]
wheres the link / list of what skills spawn
classic only install and im trying to make a lld nip and a staff nip
I know that skills of 30 wont spawn on staff
maby like certain skills wont spawn on the same staff

**Comment by DarkHorseDre** [comment]
not sure if I understood, but check the prefix and suffix pages: http://classic.battle.net/diablo2exp/items/magic/pre.shtml

tells you at which level o/class/tab skills become available on each item type, by magic and rare (not white, but I assume white follows same level rules).

**Comment by gtoilet** [comment]
yea i had that link , i was looking for some info for if a staff like this would spawn

`[type] == Staff # [sorceressskills] == 2 && [FCR] == 20 && [SkillBlizzard] == 3 && [SkillGlacialSpike] >= 1 && [SkillIceBolt] >= 1 # [maxquantity] == 2
[type] == Staff # [sorceressskills] == 2 && [FCR] == 20 && [SkillBlizzard] == 3 && [SkillGlacialSpike] >= 1 && [SkillIceBlast] >= 1 # [maxquantity] == 2
[type] == Staff # [sorceressskills] == 2 && [FCR] == 20 && [Skillchainlightning] == 3 && [SkillNova] >= 1 && [SkillLightning] >= 1 # [maxquantity] == 2
`

**Comment by DarkHorseDre** [comment]
Ahh yeah, I know that wouldnt (think 5/6 max in total?) but I cant remember where the source of info is that states that.. let me thinky...

**Comment by DarkHorseDre** [comment]
aha!

look per item.
example - staves:
http://classic.battle.net/diablo2exp/items/normal/staves.shtml

"Staves can have up to 3 staffmods (bonuses to specific Sorceress spells), each ranging from +1 to +3 to skill level."

so thats max of 3 per skill, 9 in total (although I think sorceress skills is max 2?)

**Comment by DarkHorseDre** [comment]
I think in practice you get +2 skills plus 3 of another skill, maybe 1 or 2 for other skills.

like primal helms with 2 barb and 3 BO and 1 shout..

**Comment by gtoilet** [comment]
I know in classic you get 2skill/3blizzard/blast
I wasn't sure if every skill would spawn staff
as I don't think I have ever seen a hydra mod

**Comment by DarkHorseDre** [comment]
yeah true - not every skill does - they will be in the mpqs i reckon so ask around - discord/internetz

**Comment by 5noop** [comment]
Skills lvl 30 cannot roll on staff/scepter in classic. Im not sure you could get every skill with +2sorc, the ilvl might be too high for skills lvl 1 for instance.

**Comment by gtoilet** [comment]
long time ago I finally shopped my chanter staff
2/10/3chant/1+tele
be great to find my
2/10/lightning/chain light
wanted to make some classic staff sorcs

**Comment by DarkHorseDre** [comment]
@5noop do you have a source for that info? feel like i saw that listed out years ago somewhere

**Comment by gtoilet** [comment]
meh

**Comment by DarkHorseDre** [comment]
@gtoilet 
this may help - https://forums.d2jsp.org/topic.php?t=67041534&f=87
