### ISSUE TITLE
AutoBuild Strict Warning 162

### ISSUE THREAD

**Issue by TheDarkmess** [kolton/d2bot-with-kolbot#1599]
Hello everyone,
im trying to use Autobuild but i got this error, it looks like to be a problem in the autobuild.js file..
thing is i didnt edit it.. ill attach files. 
Thanks for help

(https://imgur.com/a/gwap61J)

(https://pastebin.com/kf7havA1)

(https://pastebin.com/5pV7BM6m)

((https://pastebin.com/Wxx1Vk7g))

**Comment by DarkHorseDre** [comment]
it wont be autobuild.js - that file was affected by the error caused, probably by your HDin autobuild script

its easy to make copy/paste errors in this file - check you have closed all {} and added ; where needed.  compare the example one included in Kolbot if youre unsure

level 30 may have an extra } but I cant check here

**Comment by TheDarkmess** [comment]
syntax is correct but looks like this part of the code cant be missing..

Update: function () {
				
			}	

Added back and no errors so far. Thanks for support !

**Comment by DarkHorseDre** [comment]
yeah those commas at the end are important too - bear that in mind!
