### ISSUE TITLE
Kolbot Not logging Runes picked

### ISSUE THREAD

**Issue by mj123x** [kolton/d2bot-with-kolbot#1611]
Anyone know why. For items kept it doesn't put it on main screen where it shows runs/deaths/etc

thx

**Comment by DarkHorseDre** [comment]
There are many settings within your character config (and some not!) - we always recommend reading through ALL of it BEFORE running the bot, to save time and increase understanding.

There are 3 settings you will find when you CTRL-F "rune":
```javascript
Config.LogLowRunes = false; // Log low runes (El - Dol) on item viewer
Config.LogMiddleRunes = false; // Log middle runes (Hel - Mal) on item viewer
Config.LogHighRunes = true; // Log high runes (Ist - Zod) on item viewer
```
