### ISSUE TITLE
autosmurf .. sync

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1618]
guy asked me to look at this new autosmurf.js
got it to start click wp and say sync in the console
eventually it will just push to next script while intown

https://github.com/JeanMax/AutoSmurf

**Comment by ElDiGee** [comment]
you should use the updated one by @dark-f [https://github.com/mf022/d2bs/wiki/Misc_options](url) ...love mf022's misc corner btw ...

**Comment by gtoilet** [comment]
shows nothing in link

**Comment by ElDiGee** [comment]
> 
> 
> shows nothing in link

sry no idea why it doesn't show

here is the google search (first result for me)
[https://www.google.com/search?client=firefox-b-d&ei=KgwKXYO8JIyCgAan1IXoDg&q=d2bs+dark-f&oq=d2bs+dark-f&gs_l=psy-ab.3..35i39.1948.4027..4108...0.0..0.77.783.11......0....1..gws-wiz.......0i67j0i131j0j0i30j0i203j0i22i30.HRzn8womJqE](Here)
and the direct link to the download
[https://cdn.discordapp.com/attachments/228855570537381888/456564852971012096/AutoSmurf_2018-6-13.rar](here)
