### ISSUE TITLE
Bot stops at log in screen

### ISSUE THREAD

**Issue by zarckco** [kolton/d2bot-with-kolbot#162]
So I am new to kolbot but I installed it and got everything set up but after seeing the intro screen and selecting Battle.net (U.S. East), kolbot ensures I have the correct username and inserts the password but the log in button is greyed out.  

At first, I thought this was a key problem but if I put the -L in the profile, it loads fine.  Does anyone know what this problem could be?

**Comment by zarckco** [comment]
It has to be a problem with the loader.  I think the botting program is actually freezing after putting in the password.  I feel like the the issue is with the bot attempting to load the D2Bot Lead.dbj file...

**Comment by dzik87** [comment]
I had same issues some time ago. Let your keys and IPs cool down for couple good hours. I never found why it is like that but changing IP to another one is fixing it.
