### ISSUE TITLE
min game time setting don t work correctly ?

### ISSUE THREAD

**Issue by RaduCiurescu** [kolton/d2bot-with-kolbot#1624]
although the game takes over 40seconds (the limit that we setto in the conf config / general config line 430) it still waits for nearly 50 seconds, in lobby not in town.
   

// General config
	Config.AutoMap = false; // Set to true to open automap at the beginning of the game.
	Config.LastMessage = ""; // Message or array of messages to say at the end of the run. Use $nextgame to say next game - "Next game: $nextgame" (works with lead entry point)
-->	Config.MinGameTime = 40; // Min game time in seconds. Bot will TP to town and stay in game if the run is completed before.
	Config.MaxGameTime = 0; // Maximum game time in seconds. Quit game when limit is reached.
	Config.TeleSwitch = false; // Switch to secondary (non-primary) slot when teleporting more than 5 nodes.
	Config.OpenChests = true; // Open chests. Controls key buying.
	Config.MiniShopBot = true; // Scan items in NPC shops.
	Config.PacketShopping = true; // Use packets to shop. Improves shopping speed.
	Config.TownCheck = true; // Go to town if out of potions
	Config.LogExperience = true; // Print experience statistics in the manager.
	Config.PingQuit = [{Ping: 0, Duration: 0}]; // Quit if ping is over the given value for over the given time period in seconds.

how to put him to don t have any min game duration ?

**Comment by DarkHorseDre** [comment]
why would you want a minimum game time of 40 seconds?  5 minutes is a good minimum

also check what you have set in `D2BotLead.dbj`if the entry script you are using is lead

**Comment by RaduCiurescu** [comment]
usually i am using a short rute to run, and want to move faster

**Comment by DarkHorseDre** [comment]
You will get temp banned if your games are so short

**Comment by RaduCiurescu** [comment]
uh, ok ,thx
