### ISSUE TITLE
Cubing Full Rejuvs

### ISSUE THREAD

**Issue by Spoofzor** [kolton/d2bot-with-kolbot#1625]
#628 was the closest I have seen to a solution, but I still am not able to get this working.

I created a case for full rejuv recipe in cubing.js:

Line 96, added to var Recipe
`Potion: {
		Rejuv: 56
	}`

Line 204, added to switch(Config.Recipes[i][0])
```
case Recipe.Potion.Rejuv:
	this.recipes.push({Ingredients: [Config.Recipes[i][1], Config.Recipes[i][1], Config.Recipes[i][1]], Index: Recipe.Potion.Rejuv, AlwaysEnabled: true});
				break
```

*Edit* This is where the majority of my skepticism is focused. I used the syntax from the flawless gem cubing recipe. Thinking it would be similar. Instead of 3 flawless gem of the same type it is 3 rejuvenation potions.

I added the newly created recipe to character config:
Line 350, added to cubing section
```
Config.Cubing = true;

Config.Recipes.push([Recipe.Potion.Rejuv, "Rejuvenation Potion"]);
```

Even added to kolton.nip just to be sure:
Line 624, added rejuv pots
`[name] == rejuvenationpotion`

Had a few syntax errors pointing me in the right direction, at first, but now I am error free. The bot accepts my changes, picks up rejuv pots (ofc because added to pickit), even went to get cube when I didn't have one. But, does not cube rejuvs into full rejuvs.

I am still looking over cubing.js, but does anyone know of something I am overlooking or neglecting? Thanks in advance.

**Comment by DarkHorseDre** [comment]
This was asked before theres an issue here for it somewhere, I'd have a search (it may be closed or open)
not sure if it was solved tho.

Look at `recipe.gem` and `recipe.rune` - you are effectively doing the exact same thing as gems (and low runes) except the ids need to change.

if you follow the process through from recipe definition, ingredient specification (the id of a small rejuv) and adding to cubing area of char config, you should be able to replicate it for full rejuvs,

ps - cube is always grabbed when config.cubing is set
pps - any item in pickit will be collected but thats separate from cubing.  note that as long as you have a cubing recipe enabled with specified ingredients, the bot will collect the ingredients without them being in the pickit.  the resultant full rejuv needs to be in the pickit for it to be kept

**Comment by mf022** [comment]
maybe, the additional number of rejuv potions in inventory (Config.RejuvBuffer) is involved too, and also there are some items which are excluded from stashing, like potions, ... .
In a past abandoned project now, I've tried some things about cubing rejuvs without success, including the cubing of healing+mana+gems in order to get rejuvenation/full rejuvs potions.

**Comment by DarkHorseDre** [comment]
that's not a problem, you just add them to Ignore list in Town.stash() 

it's not a big deal. it's the same as cubing the aforementioned

**Comment by Spoofzor** [comment]
@mf022 
I didn't have to mess with/include/ignore rejuvs being stored in the belt/buffer to get this to work. Although I suspect I might have to in order for this to work as I intended.

@DarkHorseDre 
I included the info about cube and pickit to clarify that cubing and pickit are functioning as expected. It retrieved a cube and picked up potions because "I told it to". Meaning my additional code didn't disrupt functioning scripts. I removed regular rejuvenation potions from the pickit list to continue testing. Full rejuvs are still on the list.

I was careful to add additional cases where necessary for the rejuv potions in cubing.js
I switched my syntax from `...{Ingredients: [Config.Recipes[i][1], ...}` to `...{Ingredients: [515, 515, 515]}...`
Then commented out rejuvenation potions from items not getting stashed in Town.js

It works. Just not quite as I intended, yet.

Because I have columns for rejuvenation potions on my belt.. if the bot doesn't have a full belt column  any picked up rejuvenation potions (intended for crafting because it is now disabled in pickit) go to the belt instead of to the stash/inventory for cubing.

But, after my belt/buffer is full, the bot DOES collect regular rejuvs, cubes them into full, and stashes them.

Further testing and script editing will be required to enable full functionality.
I'll attempt to allow the bot to continue cubing only to a max of maybe 10 stashed(?) stopping or dropping after that. Checking belt for regular juvs to use in crafting and replace with full juvs if possible. Checking and filling empty  rejuv slots in belt columns when the bot goes to stash to deposit gold/item(s).

I fully expect this to require modifying additional scripts outside of cubing.js, but am uncertain about where to begin. I will continue to update my progress.

**Comment by DarkHorseDre** [comment]
Haha this is sounding a bit of an effort :)

I think youre conflicting with the default belt/pot buying which is triggered in town.js IIRC.
indeed there isnt a recipe I can think of that uses items which are collected in the belt (pots) as even scrolls arent placed there..

I think if you pick a joov for crafting and joovbuffer = 0 and belt column is not full of joovs, the GAME will place that joov in the belt.  the only way around it is to manually place the joov in inv.  this requires:
1) to identify the need to pick as ingredient and not pot to drink (I think you have this)
2) manual inv open, click pot, place in inv - like in real life.

That said, the brain boxes may have a simpler way of looking at this, as I think this is all about perspective.. (as I assume not enabling joov belt column is an option, especially in hc)

@5noop @jaenster spillage on aisle no 9! xD

**Comment by Spoofzor** [comment]
@DarkHorseDre 
I agree. A bit more effort than I anticipated, but I am not discouraged.

This could all be remedied by having my sorc able to reliably farm hell, and thus full rejuvs, but she is entirely self-found and only running farming nm at the moment. 

Thank you for an overview of the situation. Are you saying it is not possible for the bot to interact with potions on the belt through scripts? I haven't tried, so I am legitimately unsure.

I am still not completely familiar with the functions to handle/move items, but a little trial and error on a guinea pig character should aid my efforts. If this is even possible, I will start by combing through town.js and adding statements and cases to handle the rejuvenation potions.

**Comment by jaenster** [comment]
The problem is that, that rev pots already are claimed by basic pickit for pots for the belt. Therefor, it doesn't arrive at the cube script.

What you could do, quite easy, is create a script (add a js file to libs\bots\) and search for 3 rev pots, and cube them up to full rev pots.

So.. i did; this is what i came up with. Save as MakeRevPots.js


```javascript
function MakeRevPots() {
	Storage.Init();
	let locations = {
			Belt: 2,
			Inventory: 3,
			Cube: 6,
			Stash: 7,
		},
		orgin = [],cube=me.getItem(549/* the cube it self*/);

	// Get a list of all items
	let revpots = me.getItems()
		.filter(item => item.classid === 515); // Filter out all those rev pots


	if (revpots.length < 3) { // There are more as 2 rev pots
		return; // Not enough to cube
	}

	// Go to town and open stash
	Town.goToTown() && Town.moveToSpot('stash');
	Town.openStash();

	// For reasons unclear, cubing goes wrong in stash in my test, so for ease, i put cube in inventory
	cube.location !== locations.Inventory && Storage.Inventory.MoveTo(cube);
	me.cancel();
	me.cancel();

	// clear the cube, otherwise we cant transmute
	Cubing.emptyCube();

	// Remove excessive pots from the list. (only groups of 3)
	revpots.length = (revpots.length-(revpots.length % 3));

	// Call this function for each pot
	revpots.forEach(function (pot, index) {

		// Add this to the original location
		orgin.push({location: pot.location, x: pot.x, y: pot.y});

		Town.openStash();

		// Move to inventory first (to avoid bugs)
		Storage.Inventory.MoveTo(pot);
		me.cancel(); // remove inventory/cube window
		me.cancel(); // remove inventory window (if it was cube)

		// Move the current pot to the cube
		Storage.Cube.MoveTo(pot);
		// For every third pot
		if (!index || (1+index) % 3 !== 0) {
			me.cancel(); // remove cube window
			me.cancel(); // remove stash window
		} else {
			// press the transmute button
			Cubing.openCube() && transmute();

			// high delay here to avoid issues with ping spikes
			delay(me.ping * 5 + 1000); // <-- probably can be less

			// Find all items in the cube. (the full rev pot)
			let fullrev = me.findItem(-1, -1, 6);

			// Sort the original locations of the pots. Put a low location first (belt = 2, rest is higher).
			orgin.sort((a, b) => a.location - b.location).some(function (orgin) { // Loop over all the original spots.

					// Loop trough all possible locations
					for (let i in locations) {
						// If location is matched with its orgin, we know the name of the spot
						locations[i] === orgin.location && (orgin.location = i); // Store the name of the location
					}

					Storage.Inventory.MoveTo(fullrev); // First put to inventory;
					me.cancel(); // cube
					me.cancel(); // inventory

					// If the storage location is known, put the pot to this location
					Storage[orgin.location] && Storage[orgin.location].moveTo(fullrev);

					// If returned true, the prototype some stops looping.
					return fullrev.location !== locations.Cube;
				});

			// empty the array
			orgin.length = 0;
		}
	});
	// Put cube back in stash
	Storage.Stash.MoveTo(cube);
	me.cancel();
	me.cancel();
}
```

**Comment by DarkHorseDre** [comment]
Frickin ell @jaenster, I mean, dayum... :D

**Comment by DarkHorseDre** [comment]
Hey, I didnt read the code as Iz drunk and tired but assuming your script just overides and cubes, how do you decide on what goes to belt for default handling and usage?

**Comment by jaenster** [comment]
Read when your sober 🙃

**Comment by S2Flare** [comment]
I made that script, added it to my config and it loads when starting but doesn't ever cube, does it need added to town?

**Comment by DarkHorseDre** [comment]
I think this is a standalone script to do this one thing, so you need to call it whenever you need it
@jaenster this correct?

I was more thinking to have this run whenever needed, as with other config.cubing recipes. after all, its just another recipe and pickit keep entry ;)

**Comment by S2Flare** [comment]
Right so can we have it run during "Do town stuff?", I'm not great at scripting but I think I will make backups and try it out.

**Comment by jaenster** [comment]
You could embed this within town.doChotes obv. It isnt optimal, but its something.

Im not saying this is “the fix”, but it is one atleast

**Comment by Spoofzor** [comment]
@jaenster 
Wow. WOOOOW. Absolutely above and beyond my expectations. Thank you, jaenster, so much.
I will test this out this evening when I am back at my PC.

@DarkHorseDre Wouldn't have been possible without you. Cheers man.

Thanks everyone for contributing to the struggle. If I end up making changes I will post here to share with others. If I run into problems/errors I will post those too. Thanks again everyone.

**Comment by S2Flare** [comment]
If you don't mind me asking @Spoofzor what did you have to do with this script jaenster made besides where to place it? Add it to char config and comment them out in pickit or more than that?

**Comment by S2Flare** [comment]
Nevermind I think I finally figured it out, I threw it in default and it seems to be working as intended now I think.

**Comment by DarkHorseDre** [comment]
Big shout to @jaenster for nailing it as usual xD

**Comment by Drakalkaisa** [comment]
I got mine to work by changing a couple small things, just the following under the rest of the perf gem recipes ;

`//make full rejuv
				if (this.subRecipes.indexOf(516) === -1 && (this.recipes[i].Ingredients[j] === 516 || (this.recipes[i].Ingredients[j] === "pgem" && this.gemList.indexOf(516) > -1))) {
					this.recipes.push({Ingredients: [515, 515, 515], Index: Recipe.Gem, AlwaysEnabled: true, MainRecipe: this.recipes[i].Index});
					this.subRecipes.push(516);
				}`

and added the item type to the gems and runes section

`// Gems and runes
		if ((unit.itemType >= 96 && unit.itemType <= 102) || unit.itemType === 74 || unit.itemType === 78) {
			if (!recipe.Enabled && recipe.Ingredients[0] !== unit.classid && recipe.Ingredients[1] !== unit.classid) {
				return false;
			}`

then added the new recipe in the character profile as if it were just another gem:

`	/* Cubing config. All recipe names are available in Templates/Cubing.txt. For item names/classids check NTItemAlias.dbl
	 * The format is Config.Recipes.push([recipe_name, item_name_or_classid, etherealness]). Etherealness is optional and only applies to some recipes.
	 */
	Config.Cubing = true; // Set to true to enable cubing.

	// Ingredients for the following recipes will be auto-picked, for classids check libs/NTItemAlias.dbl	
	
	//Config.Recipes.push([Recipe.Gem, "Flawless Amethyst"]); // Make Perfect Amethyst
	//Config.Recipes.push([Recipe.Gem, "Flawless Topaz"]); // Make Perfect Topaz
	//Config.Recipes.push([Recipe.Gem, "Flawless Sapphire"]); // Make Perfect Sapphire
	//Config.Recipes.push([Recipe.Gem, "Flawless Emerald"]); // Make Perfect Emerald
	//Config.Recipes.push([Recipe.Gem, "Flawless Ruby"]); // Make Perfect Ruby
	//Config.Recipes.push([Recipe.Gem, "Flawless Diamond"]); // Make Perfect Diamond
	//Config.Recipes.push([Recipe.Gem, "Flawless Skull"]); // Make Perfect Skull
	Config.Recipes.push([Recipe.Gem, "Rejuvenation Potion"]); // Make Perfect Amethyst`


I'm not really familiar with any of this stuff so its probably sloppy and could be made better, but its working just fine for me, only issue I have is it sticks them into my stash after, as if it were a pgem, but I'm sure ill figure that out soon, or if anyone can tell me how to make just that recipe get placed in my inventory instead that'd be cool.

**Comment by Drakalkaisa** [comment]
Im really new to this so its almost certainly not an elegant solution, but I figured 3 revpots are just like 3 gems so why not code it in that way? I just added it right under the other pgems in Cubing.js around line 660 or whatever

`				//make full rejuv
				if (this.subRecipes.indexOf(516) === -1 && (this.recipes[i].Ingredients[j] === 516 || (this.recipes[i].Ingredients[j] === "pgem" && this.gemList.indexOf(516) > -1))) {
					this.recipes.push({Ingredients: [515, 515, 515], Index: Recipe.Gem, AlwaysEnabled: true, MainRecipe: this.recipes[i].Index});
					this.subRecipes.push(516);
				}`

Then around 800 I added the item  type (78) to the list of things to take even from locked inventory spaces (was just trying to be consistent and including revpots in all the gem places)

`		// Gems and runes
		if ((unit.itemType >= 96 && unit.itemType <= 102) || unit.itemType === 74 || unit.itemType === 78) {
			if (!recipe.Enabled && recipe.Ingredients[0] !== unit.classid && recipe.Ingredients[1] !== unit.classid) {
				return false;
			}`

And finally just added the new recipe in the character config, as if it were just any other gem, around line 400

`Config.Recipes.push([Recipe.Gem, "Rejuvenation Potion"]);`

All im trying to figure out now is how to get it to put them in the inventory/belt instead of stashing them like it does with the pgems, I think if im low on rejuvs though (some missing in belt, or less than my buffer) it will take them out and put them in inventory cause now I checked back in the new ones are all in my inventory....

**Comment by DarkHorseDre** [comment]
aha! Good man! This is what I was saying - GJ!

Just ignore the item types in the town.js stashing funcitons.
try looking for `ignoredItemTypes` at the top or within 'canStash' funct and add the id to the list

**Comment by Spoofzor** [comment]
@Drakalkaisa 
This method did work for me also, but like you and I both pointed out, it doesn't take them into account when you need full juvs on your belt. Jaenster has graciously provided us with a handmade solution. See above

Cheers. glhf

**Comment by shepchri88** [comment]
I made a js file and added it to the folders, but how should it be activated?

I added " Config.CubeRejuv = true; " to the character config but it hasn't done anything.

**Comment by shepchri88** [comment]
@Drakalkaisa

So what precisely is the way that it works?

**Comment by shepchri88** [comment]
@Spoofzor so what exactly is the way that it works?
