### ISSUE TITLE
Pindel

### ISSUE THREAD

**Issue by DennisX1** [kolton/d2bot-with-kolbot#1633]
The bot uses the portal, then it ports to pindel and then it leaves the game. 

Dont know what is wrong. Set the Pindelscript to true, Tried to change the order but changes nothing

**Comment by DarkHorseDre** [comment]
does it show an error in console or log files at all?!
you should link to your config, especially if there are no errors in console/logs

**Comment by DennisX1** [comment]
Thanks four your answer, but i already solved the problem.

The problem was, that i just defined the main attack (blizzard), but the script seems to require an additional attack like glacial spike to work properly.

**Comment by DarkHorseDre** [comment]
nah it doesnt - you probably specified a combination of attacks and immune skips which were not configuured correctly.  if it cant attack it causes an issue

note that blizzard is a timed attack so cant be specified as a untimed attack.
also note that pindle is a boss, so if you dont specify a VALID boss skill, it will cause an issue.
also note that if you didnt configure an attack for 'others' then it will cause an issue as pindle has minions.
also note that if pindle is cold immune and you only have blizz/glacial configured, you'll have issues.

This is valid:
```js
 Config.AttackSkill[0] = -1; // Preattack skill.
    Config.AttackSkill[1] = 59; // Primary skill to bosses.
    Config.AttackSkill[2] = -1; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
    Config.AttackSkill[3] = 59; // Primary skill to others.
    Config.AttackSkill[4] = -1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
    Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
    Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.
 ```

if you didnt have that and then added glacial spike, you had a different issue, as above.

**Comment by DennisX1** [comment]
thanks for your time :)

**Comment by DarkHorseDre** [comment]
^^
