### ISSUE TITLE
Revive Merc function not working properly

### ISSUE THREAD

**Issue by Mnsky** [kolton/d2bot-with-kolbot#1637]
Hi, I'm using kolbot with a non-English Diablo game. Everything works fine except the `reviveMerc` function is broken. It will open the Merc NPC dialog and then close it without actually reviving the merc.

I tried adding `case "Merc"` to the `initNPC` function, after line 207 in `Town.js`:
208		case "Merc":
209			Misc.useMenu(0x1507);
210			me.cancel();
211			break

A bit strange to me why this is missing, but the bot can revive merc after the change now, except with every successful revival, the current boss/area script will be skipped with error "(town.js #1450) dialog is undefined", then go to next script normally, like nothing happened.
1446	MainLoop:
1447		for (i = 0; i < 3; i += 1) {
1448			dialog = getDialogLines();
1449
1450			for (lines = 0; lines < dialog.length; lines += 1) {

**Comment by DarkHorseDre** [comment]
Wait, merc revive seems to just workout if it needs revving, find the appropriate npc, opens dialogue, reads dialogue, interacts with menu.

if I'm correct - if the text does not match, then it will fail.

what text appears in the npc dialog on your install?

**Comment by Mnsky** [comment]
> if I'm correct - if the text does not match, then it will fail.
Thank you for the reminder, it's indeed a text match issue.
And turns out it only tries to match the colon, if the revive option does not contain a colon, then the interation will fail.
I happened to change the resurrect string in D2's `expansion.tbl` a while ago, got all fixed now.
