### ISSUE TITLE
Wont open game

### ISSUE THREAD

**Issue by zzdreams** [kolton/d2bot-with-kolbot#1639]
Ok when I run 2 bots and they leave or die at the same time one will not make game  even when not in the same game one just kinda lags at the screen to create a game and I have to restart the hole char manually 
Any ideas to fix

**Comment by DarkHorseDre** [comment]
This happens when they are on the same account,
Are they running on separate accounts?

**Comment by zzdreams** [comment]
Yes they are same account  :(
No way to fix it besides 2 accounts

**Comment by DarkHorseDre** [comment]
no, if you play manually you will be kicked out if you enter chat/lobby with more than 1 character from the same account. it's how the game works :(

you could code delays to exits etc but it's really not worth the effort. just rush a new toon and level on a new account and transfer the items and reuse the configuration file

**Comment by zzdreams** [comment]
Thank you
