### ISSUE TITLE
"Dynamic" character changing in follower

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1647]
Can Kolbot profiles that used as followers open Diablo (game.exe) like leader profiles (with D2BotMap as Entry Script)?

Let's look what I mean: 

D2BotMap simply starts game, then user by his own hands entering account, selecting character, creating game etc.

What advantages do we get here?

We aren't "attached" to any char config (because we play character manualy and D2BotMap "knows" it) and we can change leader anytime (if corresponding leaders specified in follower script).

This gives us ability to "dynamicly" change leaders (in one Diablo window and in one Kolbot profile we can change leader multiple times [we can select any specified leader]).

Can Kolbot (follower script) simply open Diablo 2 window, let us by our hands select any character and only then (when we'll enter a game) start behave like a follower?

**Comment by 5noop** [comment]
So basically you want an entry script that behaves like D2BotMap but allows you to run scripts in game ?

What you can do is simply copy D2BotMap.dbj, rename it however you want (like D2BotCustom.dbj, don't forget the .dbj at the end) and use it as entry script for your follower.

**Comment by ARkaine2** [comment]
Do I understand right that we'll have to create config for each character?

But I'm interested in possibility of changing multiple characters in Diablo window that was opened by some Kolbot profile (profile which we decided to use as follower).

How to make Diablo window that was opened by some profile automaticly act like follower when we choose ANY character? 

Even if this characters config doesn't exist. 

Probably there's a way to create some "universal" config that will start acting like follower when we entered the game by ANY character that (we selected by our hands and that is not specified in any config)? 

Look what i'm interested for (with multiple profiles/windows this can give us some advantages).

1. We have Diablo 2 window that was opened by Kolbot with some Entry Script.
2. In this window we select ANY character and enter game.
3. Selected character in game starts to act like follower.

**Comment by 5noop** [comment]
> Do I understand right that we'll have to create config for each character?

Not necessarily, you can have a config linked to a profile or even multiple profiles linked to one config. Read this https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config#advanced-options I think it should answer your question.

**Comment by ARkaine2** [comment]
Seems that it is what I was looking for. Thanks!
