### ISSUE TITLE
Leader Chicken Follower Not Leaving

### ISSUE THREAD

**Issue by olsoner1** [kolton/d2bot-with-kolbot#1648]
I am trying to have my follower leave the game if my leader chickens out or leaves the game. How can this be setup? My issue is that my leader might chicken then my follower is way behind in games.

**Comment by Jcarey89** [comment]
Config.Leader = ""; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
	Config.QuitList = [""]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];
	Config.QuitListMode = 0; // 0 = use character names; 1 = use profile names (all profiles must run on the same computer).

in quit list put ur char name or put profile of the leader and change quitlistmode to 1

**Comment by olsoner1** [comment]
ty
