### ISSUE TITLE
Please remove Virus

### ISSUE THREAD

**Issue by HansGerber** [kolton/d2bot-with-kolbot#165]
When i try to download the files as zip and unpack the kolbot files a Virus is detected in the D2Bot.exe.
Would be great if you could upload a clean version of the file again (if possible)

Thank you

**Comment by JPM1920** [comment]
I have had that problem before using Norton Internet Virus System.  I had to allow the suspected item and then it worked fine.  That was back before the last D2 update patch.

Now you have to us a temp patch that I found over on Blizzhackers website.  But it does work.

I use Windows 7, so don't know anything about Windows 10, which I will never use.

**Comment by JPM1920** [comment]
This is the temp hack that I have found that does work.

http://www.blizzhackers.cc/viewtopic.php?f=182&t=536079

**Comment by dzik87** [comment]
It is false positive. You can help us and report it as false positive.
