### ISSUE TITLE
Pickit Question - Max/Min Damage

### ISSUE THREAD

**Issue by bellsom** [kolton/d2bot-with-kolbot#1653]
In regard to jewels, some spawn with plus max damage or plus min damage, which is straightforward in the pickit. Some spawn with the mod reading "adds xx-xx damage". For an example line i use:

[name] == jewel && [quality] <= rare # ([maxdamage] >= 9 || [mindamage] >= 4) && [itemlevelreq] <= 9

This will pick up jewels that have 9+ max damage or 4+ min damage, but would it work for a jewel that reads "Adds 4-9 Damage" or would this need to be a separate line? I looked through the NTItemAlias for any other damage syntax but didn't find one that looked more appropriate. 

Thank you!

**Comment by DarkHorseDre** [comment]
Look in NTItemAlias.dbl

i think its these:
plusmindamage
plusmaxdamage
