### ISSUE TITLE
MenuId

### ISSUE THREAD

**Issue by milnap** [kolton/d2bot-with-kolbot#1657]
Does anyone know what is the Menuid for initialize Skills and Stats at Akara.

**Comment by 5noop** [comment]
0x2ba0

You can always iterate on getLocaleString to find this kind of information.

**Comment by milnap** [comment]
First of all.. thanks. 
One more question. is it possible to get Menuid by using getLocaleString ?
As far as I know, the parameter for getLocaleString is the id, and return val is the String.. isn't it?

**Comment by 5noop** [comment]
Thats right, but you can do that in a loop:
´´´
for(let x = 0x0; x < 0xffff; x++) {
	if (getLocaleString(x).toLowerCase() === "reset stat/skill points") {
		print("id = " + x);
		break;
	}
}´´´

**Comment by milnap** [comment]
what a nice tip..^^ thanks a lot.
