### ISSUE TITLE
weaponswitch problem

### ISSUE THREAD

**Issue by xiphias12** [kolton/d2bot-with-kolbot#1659]
Hello!

I'm trying to config that one of my leecher's gonna switch to weaponslot with ondals. I'm using autobaal-script and tried to add this after the safe tp message:

Precast.weaponSwitch();

But it says "weaponSwitch is not a function" and ends script. Any thoughts on how I could make this work?

**Comment by 5noop** [comment]
The function `weaponSwitch()` is in Attack not in Precast

**Comment by xiphias12** [comment]
> The function `weaponSwitch()` is in Attack not in Precast

Thank you for your reply.

Should I try to add something like:
this.weaponSwitch <-- that is the line used in MFswitch.

**Comment by xiphias12** [comment]
> > The function `weaponSwitch()` is in Attack not in Precast
> 
> Thank you for your reply.
> 
> Should I try to add something like:
> this.weaponSwitch <-- that is the line used in MFswitch.

Yes. Added:
this.weaponSwitch();

Seems to work. Can be closed!

**Comment by xiphias12** [comment]
> > > The function `weaponSwitch()` is in Attack not in Precast
> > 
> > 
> > Thank you for your reply.
> > Should I try to add something like:
> > this.weaponSwitch <-- that is the line used in MFswitch.
> 
> Yes. Added:
> this.weaponSwitch();
> 
> Seems to work. Can be closed!

I was wrong. It did switch in the beginning but now when I watch it it doesnt do it anymore... what's wrong?

**Comment by 5noop** [comment]
You need to call `Attack.weaponSwitch()`

**Comment by xiphias12** [comment]
> You have to call `Attack.weaponSwitch()`

Thanks, seems to work.
