### ISSUE TITLE
Window has unexpectedly exited... starting profile

### ISSUE THREAD

**Issue by Vinny21** [kolton/d2bot-with-kolbot#166]
as soon i start the bot i get this message (Window has unexpectedly exited... starting profile) in the Console Tab...

**Comment by DetectiveSquirrel** [comment]
Your profile name in the bot is too long, make it shorter (12 chars or less)

**Comment by Vinny21** [comment]
My profile name has 4 letters

Envoyé de mon iPhone

Le 31 mai 2016 à 21:25, Detective Squirrel <notifications@github.com<mailto:notifications@github.com>> a écrit :


Your profile name in the bot is too long, make it shorter (12 chars or less)

**Comment by tank08520** [comment]
崩潰信息:腳本:都不是:出遊戲
窗口已意外退出...開始簡介 
D2BS沒有響應 開始簡介
崩潰信息:腳本:無輸入區域:盜賊營地

這有解嗎~..

**Comment by dzik87** [comment]
#164
