### ISSUE TITLE
"Dynamic" character changing in follower

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1661]
> Do I understand right that we'll have to create config for each character?

Not necessarily, you can have a config linked to a profile or even multiple profiles linked to one config. Read this https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config#advanced-options I think it should answer your question.

_Originally posted by @5noop in https://github.com/kolton/d2bot-with-kolbot/issues/1647#issuecomment-504740870_

I got problem. I can't input any account/password and even can't move mouse cursor in Diablo 2 window that started by follower profile.

**Comment by ARkaine2** [comment]
![Untitled](https://user-images.githubusercontent.com/31447095/59981556-c546bf00-960d-11e9-85f3-48756012086c.png)

**Comment by 5noop** [comment]
Seems to be an issue with the entry script. You can simply use D2BotBlank instead of what I told you in the other thread, even if both solutions should work.
