### ISSUE TITLE
Shrines and Wells

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1669]
Is it possible to make bot pick not only shrines but also and wells?

**Comment by DarkHorseDre** [comment]
Short answer yes - but the bot files do not list wells as a shrine (https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/sdk/Shrines.txt)
So you'd need to get its id, or worse still, its reference and add to the list..

**Comment by ARkaine2** [comment]
> So you'd need to get its id, or worse still, its reference and add to the list..

To which list? Where is that listed?
Because i want allow bot to pick not only wells but and evil urns in 5 act. ;)

**Comment by DarkHorseDre** [comment]
I gave you the list - its not on there - so you'd have to get it yourself

evil urns/objects are not handled by the shrine getter code as they are two different things.

short answer if you're not good with code is to set: Config.OpenChests = 2;

if youre happy to mod then review the mostly complete list in misc.js and customise as you please
