### ISSUE TITLE
color code  problem

### ISSUE THREAD

**Issue by xfwduke** [kolton/d2bot-with-kolbot#167]
![c4c45fb30ea9d8b1f7f7ab4e5d5d30b5](https://cloud.githubusercontent.com/assets/977823/15765708/555f3bda-296a-11e6-9a74-c086c3338c3d.jpg)

Item imgs kol generated contained unreadable code.
Like ?C4 etc.

I guess they were color code and try to fix it.
But I can't find any information about which library kol used to generate imgs...

**Comment by mboufos** [comment]
this version of kolbot working with the latest patch ?

**Comment by dzik87** [comment]
@xfwduke You most probably edited files and saved without checking codingpage. Files are saved in ANSI coding and if you change something in them and save with different coding you might end up with such problems. I would suggest use \xFF instead y and ÿ what is more accurate and never change with changing coding page on file.
