### ISSUE TITLE
GhostBusters

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1670]
Is it possible to make bot hunt ghosts only in specified areas?

Seems that when you select "Scripts.GhostBusters = true" bot starts the GhostBusters scrip and begins to hunt ghosts in every area where ghosts should be.

But i'm interested in hunting ghosts only in specified areas.

I want to specify bot to kill only (super)unique/champion/minion monsters in most areas (what can be specified by: Config.ClearType = 0xF), but in areas which contain ghosts I want to do ghosthunting (kill all white ghosts but only in specified areas).

**Comment by ARkaine2** [comment]
I found in GhostBusters.js

`		sequence = ["cellar", "jail", "cathedral", "tombs", "flayerDungeon", "crystalinePassage", "glacialTrail", "icyCellar"];`

**Comment by ARkaine2** [comment]
But question is here:
How do I specify Arcane Sanctuary in such format?..

**Comment by DarkHorseDre** [comment]
Read the whole file - theres a function for each 'sequence' entry.
example:
```js
    this.cathedral = function () { // inner cloister wp
        Pather.useWaypoint(32);
        Precast.doPrecast(true);
        Pather.moveToExit(33, true);
        this.clearGhosts();
 
        return true;
    };```

so you'll need a function for arcane and add that function name to the sequence list in the same way it has been done.
you'll see references to wp's, so change that to the wp for arcane. you'll also need to tell it to travel arcane - depends how you wanna do it.  moving from wp to each corner and returning may be one way, similar to canyon..
