### ISSUE TITLE
enchant bot issue

### ISSUE THREAD

**Issue by bellop1** [kolton/d2bot-with-kolbot#1673]
Bot accepts/party invites

then chants

but when i test & say " chant " bot crashes or if i say " wps " it crashes as well.

The only thing i changed was to take out "WPS" from her char config.

She's in leader mode.

error -
 Error in Enchant (enchant.js #500) Config.Enchant.Triggers[2] is undefined (Area: 1, Ping:125, Game: uuuof)

**Comment by 5noop** [comment]
Yeah you cannot just remove the keyword "wps". Put "" instead if you don't want it to be used.

**Comment by bellop1** [comment]
savior. thank you
