### ISSUE TITLE
Bot wont do certain bosses

### ISSUE THREAD

**Issue by BlackCaboose** [kolton/d2bot-with-kolbot#1676]
It'll tele to the area then instantly tp and move on to next boss. I tried to do Ancient Tunnels and Pindle and it just tps and moves to next, I also ran into the same thing with the summoner. But it kills andarial and meph just fine

**Comment by DarkHorseDre** [comment]
you need to read the info in console window and d2manager - what does it say?

its probably skipping  immunes or trying to use a skill you set that is incorrect.  look into it

**Comment by BlackCaboose** [comment]
it doesnt tell me anything of why its not doing the AT or Summoner. ill take a screenshot tomorrow when i get a chance.

**Comment by DarkHorseDre** [comment]
try to watch it do those also - they are both in eary act 2 so wont take long - dont change your script sequence tho

and please note my previous post about immunes and other configs which could cause bot to skip (like telling it to static or use a skill you dont have etc)

**Comment by BlackCaboose** [comment]
![coding](https://user-images.githubusercontent.com/52187497/60179816-21fbd280-97e4-11e9-93cf-c746fa58ab80.PNG)
![coding2](https://user-images.githubusercontent.com/52187497/60179818-23c59600-97e4-11e9-801a-4e172fce2fa7.PNG)
![coding3](https://user-images.githubusercontent.com/52187497/60179819-258f5980-97e4-11e9-87d9-6e5a06c3e163.PNG)
![coding4](https://user-images.githubusercontent.com/52187497/60179821-27591d00-97e4-11e9-859d-e2edb7670b8c.PNG)


https://photos.app.goo.gl/cp2rshN8BSsmDJC96


so this is what happens.

**Comment by 5noop** [comment]
Check your Config.Attackskill, you set a primary skill for bosses but not for any other mobs. Which means your bot can attack any boss but that's all.

By the way you should have an error in the console when the bot enters a game.

**Comment by BlackCaboose** [comment]
Thank you I will check it when I get home!

**Comment by DarkHorseDre** [comment]
I'm having de ja vu!

**Comment by BlackCaboose** [comment]
im pretty new to the coding world so i appreciate everyone trying to help me!

**Comment by DarkHorseDre** [comment]
yeah we don't mind helping bro, and I'm no coder - but there are things appearing on your screen that you're ignoring!

What 5noop told you is what I told you in my first post! QQ ;)

**Comment by BlackCaboose** [comment]
i didnt ignore you bro! i thought i had it set correctly i did not know that there was a everything else attack. back in the day of using mousepads and d2jsp bots there was just a one attack for all deal. definitely my mistake!  Again much appreciated for everyones help and the quick replies! :)

**Comment by DarkHorseDre** [comment]
haha no I said you ignored it - the red text in your console :p

no worries - we all try, I still screwup, and @5noop slaps me straight xD

**Comment by BlackCaboose** [comment]
XD ahhhh i thought you were referring to the console on the application itself! My misunderstanding. Maybe later i can pick your brain on some pickit config cause i dont understand the values for charms. I'm trying to get it to keep only 100+ but it keeps picking up 50pdsc

**Comment by BlackCaboose** [comment]
YOU GUYS ROCK! IT WORKED!

**Comment by DarkHorseDre** [comment]
gratz

welp, I said both ;)
`You need to read the info in console window and d2manager`

yeah psn scs are a common issue that has been covered - search these issues!
