### ISSUE TITLE
Kolbot problem with token creation

### ISSUE THREAD

**Issue by deadbandit** [kolton/d2bot-with-kolbot#1677]
My kolbot creates tokens of absolution, but IDK what it does with them. I see it in the logs, but it's not in my inventory, and I don't have muling set up.

**Comment by MasterofBots** [comment]
I would check to see if its on ure pickit. it might have token of absolution marked off as dont find. If so, it might just make and then drop

**Comment by DarkHorseDre** [comment]
yup - if you craft something and the resultant item is not in pickit the bot will drop it.
its the same as finding a token of absolution and not having it in pickit - it will be dropped/not picked

**Comment by deadbandit** [comment]
> 
> 
> I would check to see if its on ure pickit. it might have token of absolution marked off as dont find. If so, it might just make and then drop

That was the first thing I checked, my picked doesn't have the token, or essences for that matter. However, it will pick up essences and stash them for tokens if you activate the cube enable part in character file.

**Comment by MasterofBots** [comment]
The essence part is auto if char config is to make token. But u need token in pickit for it to keep

**Comment by DarkHorseDre** [comment]
if you enable config.cubing it will collect required parts (as per the defined recipes) and then make the end product.  if thats not in your pickit, it will drop it.

**Comment by deadbandit** [comment]
So I checked my pickit file, and I DO have token of absolution on there. I ALSO have UM on there set to have max of 50, and I have it set up to also cube pul's > UM. While I was watching, it created an UM. So I thought "cool it's working".. Then I go to my stash to check on things, and the UM is gone as well.

**Comment by DarkHorseDre** [comment]
paste the config the active profile is using and the pickit(s) referenced within it to pastebin.com or similar and link here plz

**Comment by deadbandit** [comment]
[name] == tokenofabsolution
[name] == umrune # # [MaxQuantity] == 50

Config.Cubing = true; // Set to true to enable cubing.
Config.Recipes.push([Recipe.Rune, "Pul Rune"]); // Upgrade Pul to Um
Config.Recipes.push([Recipe.Token]); // Make Token of Absolution

If you want, I can copy/paste the entirety of the files and link them.

**Comment by deadbandit** [comment]
Actually I want to close this.. For some reason, it took my power going out (restartubg my computer) to get this to work properly. I had restarted kolbot multiple times.. I truly have no idea what happened.
