### ISSUE TITLE
Static only on baal

### ISSUE THREAD

**Issue by xiphias12** [kolton/d2bot-with-kolbot#1678]
Trying to figure out how I could change the baalscript so my sorc enters chamber and then only make static on baal. Then I would like her to make a tp and go town/continue with next script.

In the baal script:

Attack.kill(544); // Baal <-- I guess this needs to be changed somehow with Pather.makePortal();

Anyone got any thoughts?

**Comment by xiphias12** [comment]
What if I add a function in Attack.js similar to this:

	kill: function (classId) {
		if (Config.AttackSkill[1] < 0) {
			return false;
		}

		var i, target, gid, result,
			retry = 0,
			errorInfo = "",
			attackCount = 0;

		if (typeof classId === "object") {
			target = classId;
		}

		for (i = 0; !target && i < 5; i += 1) {
			target = getUnit(1, classId);

			delay(200);
		}

		if (!target) {
			throw new Error("Attack.kill: Target not found");
		}

		gid = target.gid;

		if (Config.MFLeader) {
			Pather.makePortal();
			say("kill " + classId);
		}

Changing the phrase "Kill" to like "Static". Then somehow change that it's always only attackskill static field.  And instead of Attack.Kill(544) it would be Attack.Static(544)?

**Comment by 5noop** [comment]
You can use the function `Attack.hurt()` and edit your sorc config to use static on baal

**Comment by xiphias12** [comment]
> You can use the function `Attack.hurt()` and edit your sorc config to use static on baal

Ok so If I do Attack.Hurt(544) it seems she stays all the way. Can I add something to make her end script when baal is down to 50% HP?

**Comment by 5noop** [comment]
Check the function signature in Attack.js `hurt: function (classId, percent)`, it means you need to pass the hp percent after the class id.

**Comment by xiphias12** [comment]
> Check the function signature in Attack.js `hurt: function (classId, percent)`, it means you need to pass the hp percent after the class id.

Thanks! Got it to work.
