### ISSUE TITLE
Pick items with certain ilvl

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1681]
As we know bot gambling amulets and rerolling charmis with knowing of its ilvl.
Is it possible to specify ilvl in pickit (or probably somewhere else) for certain items?

**Comment by Jtc9289** [comment]
[Name] == GrandCharm && [Quality] == Magic && [Level] >= 98 //BAAL GC
[Name] == SmallCharm && [Quality] == Magic && [Level] >= 98 //BAAL SC

**Comment by ARkaine2** [comment]
That's excactly what i was looking for. :) Thanks a lot!
