### ISSUE TITLE
How to add enchant

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1687]
There's BATTLE ORDERS SCRIPT in default character config.
But how to add in such way enchant?

I added this part of code:
```
	// ENCHANT SCRIPT -- use this for 2+ characters (for example ench sorc + sorc)
	Scripts.Enchant = true;
```
But what else should I add (and probably what else should i do?) to make my sharacter receive enchant from sorc that will enter the game, give enchant and then leave the game.

**Comment by DarkHorseDre** [comment]
You dont need to add anything, ALWAYS read your char configs as the comments are there to help.  In this case their self explanatory:

```js
Scripts.Enchant = false;
		Config.Enchant.Triggers = ["chant", "cows", "wps"]; // Chat commands for enchant, cow level and waypoint giving
		Config.Enchant.GetLeg = false; // Get Wirt's Leg from Tristram. If set to false, it will check for the leg in town.
		Config.Enchant.AutoChant = false; // Automatically enchant nearby players and their minions
		Config.Enchant.GameLength = 20; // Game length in minutes
```

**Comment by ARkaine2** [comment]
Okay, now i see.
Excuse for troubling and thanks for answer.
But now i got another question about running supporter enchant (and/or BO) and team mf at all.

Should i run enchant sorceress (and/or BO) with with its own character config and profile?
Or probably that can be specified in some config file (like with muling)?

Generaly my question is about: How to make them run together?

**Comment by DarkHorseDre** [comment]
lol np

each character has its own config (unless you understand how to make common configs - lets leave that out of this) - each char can run their own scripts and some scripts work together (e.g. leader running baal, follower running autobaal - again this is detailed in the config comments and on the wiki on this site)
heres an example: https://github.com/kolton/d2bot-with-kolbot/wiki/Team-MFing

I have not ran chant script but it is not an mf script - AFAIK it will wait around to chant similar to the BO script.

you can run BO barb who will wait at catacombs and bo (it has limitations - check you are running the latest copy of kolbot and search the issues on this github if you have issues) or you can have the barb run with mfhelper but it wont specifically BO its teammates without customisation.
The enchant sorc doesn't auto enchant teammates AFAIK.

**Comment by ARkaine2** [comment]
Okay. I started run follower script successfully (it joins created by leader profile game and accepts party), but it acts in some strange way.

Leader creates game.
Follower (ench sorc) joins game.
Then leader and follower make party.
Then follower does nothing -- that's the problem.
Then leader starts his first area to run (let's say it's pit).
And only then when leader comes back to town follower gives leader and its merc enchant.

Probably ench sorc gives enchant that's becuase of:
`Config.Enchant.AutoChant = true; // Automatically enchant nearby players and their minions`

But how to make ench sorc behave adequately and give leader enchant from begining of run/game?

**Comment by ARkaine2** [comment]
> The enchant sorc doesn't auto enchant teammates AFAIK.

I interstand this. But probably there's some another (smart) way to make "enchant bot"? :)

**Comment by DarkHorseDre** [comment]
i pasted the information you needed - did you read the comments in the config file that I also pasted above?

please read everything that has been written and take time to familiarise yourself with the files.

**Comment by ARkaine2** [comment]
> i pasted the information you needed - did you read the comments in the config file that I also pasted above?

Of course yes.

I tried to use Enchant script described in this message:

> Scripts.Enchant = false;
> 		Config.Enchant.Triggers = ["chant", "cows", "wps"]; // Chat commands for enchant, cow level and waypoint giving
> 		Config.Enchant.GetLeg = false; // Get Wirt's Leg from Tristram. If set to false, it will check for the leg in town.
> 		Config.Enchant.AutoChant = false; // Automatically enchant nearby players and their minions
> 		Config.Enchant.GameLength = 20; // Game length in minutes

But i got problem described in my next message.

**Comment by DarkHorseDre** [comment]
so... you want autochant. good to know.


where is the follower and leader when it chants the leader after its run?

**Comment by ARkaine2** [comment]
They both are in town of first act.

Then leader immediately starts run (goes to waypoint or to NPC and then to waypoint in town).
At the same time chant sorc joins game, starts Enchant script and goes to location in town where will be opened town portals.

If leader didn't left town and if chant sorc joined game in tme and if leader with its merc near chant sorc then chant sorc gives enchant leader and its merc (seems, that it's AutoChant's work).

But sometimes leader lefts town and chant sorc is too late.

Then our next chance to get AutoChant is when leader comes back to town (by town portal).

**Comment by DarkHorseDre** [comment]
alright, so I looked at the enchant.js, looks pretty straightforward.

the chanter will 1) need to be in party, 2) need to be at portal spot of any of the towns (or it seems act 1 for autochant), 3) be 35 yards or less from leader to chant (or 40 yards for autochant).

when you read it, you'll see the error messages it will print.

what does the console of the enchanter say?  observe it from the time it starts enchant script until it ends and report the errors,
If I read the script correctly, autochant is act 1 only, which kinda makes sense.

you can always make changes you want to these parameters to suit your needs

**Comment by ARkaine2** [comment]
![dsfsddsdf](https://user-images.githubusercontent.com/31447095/60373409-b5155200-9a08-11e9-899f-41ce91cf52f9.png)

Chant bot stays in town and waiting when leader will come back to town by TP, and ONLY THEN chant bot gives enchant to leader.

**Comment by DarkHorseDre** [comment]
I took a quick look at the enchant.js script, seems to be as designed.

```
js
if (me.act > 1) {
			Town.goToTown(1);
		}

		if (Config.Enchant.AutoChant) {
			this.autoChant();
		}
```
basically says to goto act 1 and if not in act 1, go there. then to portal sport. then autochant if configured.
it references the other config.enchant.blah within the char config file.
you havent shared your config so..
