### ISSUE TITLE
How to use useraddon.js?

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1694]
I have tried to add
`include("bots/useraddon.js");`
into D2BotMap.dbj (which is selected as Entry Script), but how can i check loading of this script?
How to use it?..

> Allows you to see more information about items, NPCs and players by placing the cursor over them.
> *				Shows item level, items in sockets, classid, code and magic item prefix/suffix numbers.
> *				Shows monster's classid, HP percent and resistances.
> *				Shows other players' gear.

**Comment by Spoofzor** [comment]
I haven't tried this for myself, but in Character config at the top there is:
`Scripts.UserAddon = false; `

Perhaps setting this to true?

**Comment by ARkaine2** [comment]
Seems that there's similar question here:
https://github.com/kolton/d2bot-with-kolbot/issues/484

**Comment by Spoofzor** [comment]
You can enable useraddon in your config, and then change bot entry script to Blank.
This works.
Does not appear to be possible to merge the two, at least not easily.

**Comment by gadgetsaavy** [comment]
> You can enable useraddon in your config, and then change bot entry script to Blank. This works. Does not appear to be possible to merge the two, at least not easily.

so then if you use a user addon script all the regular stuff in like paladin.name.js needs specified in the add on if you wish to use it?
