### ISSUE TITLE
idle at diablo after xx hp loss

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1700]
lmk how to make barb wait at diablo after xx hp loss

**Comment by Xuk3000** [comment]
Which script are you running? Diablo, FastDiablo, DiabloHelper..
AutoChaos has a config property that you are looking for:
_Config.AutoChaos.Diablo = -1; // -1 = go to town during diablo, 0 = kill to death, x > 0 = kill to x%_

https://gist.github.com/noah-/2685fbeccc72fd595bbe89116aea272e

**Comment by gtoilet** [comment]
just diablo helper
ill c/p that code into it thanks
