### ISSUE TITLE
Error in Diablo: Failed to kill (merc)

### ISSUE THREAD

**Issue by 123lolbox** [kolton/d2bot-with-kolbot#1713]
Hi

Every run I get this error:
16:40:57 (Pala ladder 3)  Error in Diablo (attack.js #214) Failed to kill Zanarhi (Area: 108, Ping:32, Game: secret)

This also happens with Baal and is every run. Why does my scripter ignore killing the boss? It look likes it tries to kill my own merc.

Thanks in advance.

EDIT: Updating to latest version solved this.

**Comment by Milburn1** [comment]
Hi, how did you solve this problem? I faced the same...
