### ISSUE TITLE
Ilvl bug

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1719]
Do that only i have this bug (https://github.com/kolton/d2bot-with-kolbot/issues/1675)?

**Comment by fabio1999ita** [comment]
i have `ilvl 1`, idk what is it

**Comment by ARkaine2** [comment]
This bug creates problem with for example picking 91> level grand chamrs.
Of course we can pick grand charms with 41> life, but it will A LOT reduce getting 91> level grand charms.

**Comment by ARkaine2** [comment]
That was server's mod.
