### ISSUE TITLE
hurt function

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1722]
so i see that HURT function in the attack.js
how can i implement it into my barbs , diablohelper.js
so where he hurts to XX% then idle till death

i tried to just copy the function part and paste it over the diabloprep
didnt work also tried to copy over the boss function but would affect the rest of seal bosses

**Comment by 5noop** [comment]
Did you replace `Attack.kill(243);` by `Attack.hurt(243, XX)` with XX being the percent hp ?

**Comment by gtoilet** [comment]
@5noop , no i didnt  i only copied over the functions
did add a config.diablohelper.hurt = xx
in char config thinking that would work , i will go test now 

Thank you
