### ISSUE TITLE
Full list of items properties

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1726]
Where can I find full list of items properties to use them in pickit file configuration?

There's file NTItemAlias in which listed all items.
Maybe there's something about items properties?

In particular at this moment I'm looking for crushing blow.

**Comment by ElDiGee** [comment]
I think that this is also listed in the NTItemAlias just further down.

**Comment by ARkaine2** [comment]
> I think that this is also listed in the NTItemAlias just further down.

Oh, thanks. :) That's nice. Lol I missed something that was on the eyes.
