### ISSUE TITLE
Bot doesn't log runes

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1727]
Bot doesn't log runes (Hel--Vex) but there's in character config file selected to log them:
```
	Config.LogMiddleRunes = true; // Log middle runes (Hel - Mal) on item viewer
	Config.LogHighRunes = true; // Log high runes (Ist - Zod) on item viewer
```
Maybe there's some additional file that answer for rune loging in which described runes aren't listed.

**Comment by Spoofzor** [comment]
Just out of curiousity, do you have cubing runes enabled?

**Comment by mayphilc** [comment]
I've noticed that if you are cubing runes it will not display the ones it picks up for cubing, however as the OP stated there are times runes just arent logged. I have a ber and no log of it and thays not even inside the range hes talking about nor am I cubing jahs

**Comment by ARkaine2** [comment]
> Just out of curiousity, do you have cubing runes enabled?

Yest.

**Comment by ARkaine2** [comment]
> I've noticed that if you are cubing runes it will not display the ones it picks up for cubing, however as the OP stated there are times runes just arent logged. I have a ber and no log of it and thays not even inside the range hes talking about nor am I cubing jahs

Interesting, thanks for answer. :)
