### ISSUE TITLE
Failed to use waypoint

### ISSUE THREAD

**Issue by 123lolbox** [kolton/d2bot-with-kolbot#1728]
Hello.

Lately i've been having massive fails per run with error code:
13:33:37 (Pala ladder 2)  Error in Worldstone (pather.js #992) useWaypoint: Failed to use waypoint (Area: 1, Ping:47)

As far as I have seen, there's no real solution to this. So what I wonder is, where in pather.js can I edit the distance the script is moving away from the waypoint to retry? 

Is this code correct to alter? (line 948-954 in pather.js)
```
if (!getUIFlag(0x14)) {
						print("waypoint retry " + (i + 1));
						this.moveTo(me.x + rand(-5, 5), me.y + rand(-5, 5));
						Packet.flash(me.gid);

						continue;
					}
```

Thanks in advance.

EDIT: It seems to happen 99% of the time in Act 1, with one specific map spawn where Akara is top right and there is a van in the middle from Akara to the Waypoint. The script then tries to go around it on the upper side and fails. I found a picture online that shows the map orientation i'm describing:
[here](https://www.diabloii.net/forums/data/attachments/11/11479-95a054862e1f119ce1e7cb185236271c.jpg)

EDIT 2: An update solved this. I used version 18.6.15.200 before. If you are like me and lazy enough that you refuse to update, just do it. Zero errors since this 5noop answered.

**Comment by 5noop** [comment]
Looks like you are using an old version, try to update there have been improvements on this kind of issue.
