### ISSUE TITLE
order of area to run

### ISSUE THREAD

**Issue by mst44** [kolton/d2bot-with-kolbot#173]
Hey, im team mfin and i would love to set up my bot to diablo, baal and after them leechers run solo for other areas in same game. One of them go to pit, second one do meph etc. The problem is: when i setup something like this:
```

Scripts.Baal = true;
		Config.Baal.HotTPMessage = "Hot TP!";
		Config.Baal.SafeTPMessage = "Safe TP!";
		Config.Baal.BaalMessage = "Baal!";
		Config.Baal.SoulQuit = false; // End script if Souls (Undead Soul Killers) are found.
		Config.Baal.DollQuit = false; // End script if Dolls (Undead Stigyan Dolls) are found.
		Config.Baal.KillBaal = true; // Kill Baal. Leaves game after wave 5 if false.
Scripts.Andariel = true;

```

bot still goes for andy first.

Is there any option to fix it ?

Thanks <3

**Comment by DetectiveSquirrel** [comment]
Have you removed the Andariel at the top of the script?

**Comment by mst44** [comment]
oh well, i though if i set it to false it will be enough... its working after delete, now will try with //
thanks
