### ISSUE TITLE
Rusher Bot

### ISSUE THREAD

**Issue by Ofock** [kolton/d2bot-with-kolbot#1732]
Hello All,

Ive read through most of these posts about rusher bot and none of them really answer my question.

I cant get the rusher bot to work. I have their profiles set up as rushee is lead and the rusher is follow. They join games fine and the rushee says they found the leader, they join parties fine. the rushee runs over to where the TP will be and the rusher sits in town. I've tried the chat commands and they dont seem to do anything. After a min or so they both leave the game after it says leader not found. Not sure what im doing wrong?

**Comment by mf022** [comment]
> I've tried the chat commands and they dont seem to do anything.

the chat is ok?
... or some of the keys are muted? In this case set the local chat in the char configs.

**Comment by Ofock** [comment]
I'll try it when i get home. Ty for the help!

**Comment by fabio1999ita** [comment]
best way is post here the config of your leader and your follower

**Comment by boddhisatra** [comment]
I was able to use the rusher/rushee scripts the other day to make a bunch of socket toons. I would suggest making sure that you have the right leader name set in the config file for the new toon (config.leader). Also, have in Config.LocalChat.Enabled set to true as mf022 suggested.

The new toon profile runs lead entrypoint, while the booster character runs follow.

**Comment by Ofock** [comment]
Thank you everyone, The chat setting needed to be true and that worked . ty all!
