### ISSUE TITLE
delay but not delay

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1734]
so i got my barb to hurt to xx and he would leave right away wouldnt wait untill death to pickit
so i put a delay but sometimes the delay is longer then when diablo dies
so what condition do i need to add to make him wait untill death and pickit
and not delay untill all items are grabbed then he tries to pickit

**Comment by 5noop** [comment]
Put this instead of your delay:
```
let dia = getUnit(1, 243);
while(!me.dead && dia && Attack.checkMonster(dia)) {
	delay(20);
}
```

**Comment by gtoilet** [comment]
thank you
