### ISSUE TITLE
Another 4 acounts 1 up question

### ISSUE THREAD

**Issue by biggrick75** [kolton/d2bot-with-kolbot#1735]
I understand the 100 games per 12 hours and the 30 games a hour. This information seems wrong. Or im misunderstanding it. I have ran 3 bots 1key each 24 hours a day with a 500sec min game time with no trouble. Was looking for a min game time in seconds for 4bots 1 key each same ip . Thank you for any help you can give

**Comment by fabio1999ita** [comment]
here the official post: https://eu.battle.net/forums/it/bnet/topic/17617822130

in particolar:
Quick connections and disconnections from Battle.net - over 50 connections per hour (behavior often associated with the phenomenon of botting or due to the continuous change of the character).

**Comment by biggrick75** [comment]
Yes and thank you, can any one give examples of there min game times running 4 bots 1 ip

**Comment by biggrick75** [comment]
Well since no one has given examples of there run times I'm just going to test a 660sec min game time with a 60sec make game delay. I'll post a update at 12 hours

**Comment by fabio1999ita** [comment]
up of 16 min/game and 20 sec for recreate new game

**Comment by gtoilet** [comment]
i run 3 to 3:15 min nmcs games this past few days breaks every xx:45 to xx:00

3am was rd restarted eventually and went till 7:20pm for another rd

will do hell now at 3:30min games

**Comment by biggrick75** [comment]
4 bots 1 ip 4 keys 660sec min game with 60 sec create game delay for 12 hours no Rd.  Changed it to 610sec min game and 30 sec create game delay will update in 12 hours.  Let me no what the res of you are doing  thanks

**Comment by BotWaldo** [comment]
i've been averaging 4:30s/game "meph->chaos->baal" 4chars 4cdkeys 1ip. no realmdown yet.. I run bots only 10 hours/day though while i can watch them. do you sleep with them running?

**Comment by biggrick75** [comment]
Another 12 hours no Rd . And yes they run 24\7 only shit down to mule

**Comment by Jtc9289** [comment]
I’ve been running 24-7 4 char 1 ip chaos n baal 7 min games no rd

**Comment by biggrick75** [comment]
More ten 48 hours now no Rd thanks for the feedback
