### ISSUE TITLE
Follower Bot stuck in channel won't join Lead.

### ISSUE THREAD

**Issue by Tannerd00** [kolton/d2bot-with-kolbot#1748]
Made my Sorc the lead and my Hdin the follower. My sorc joins in and runs everything fine. My Hdin will join in channel and never join game. If I join manually with follower then he continues to run Trav as requested in config but then gets stuck in Chaos because "waiting for Lead to join in" Even after my leader runs by the follower will continue to sit in chaos for 60 second before going back to town and starting baal script without lead. I notice that they don't party up together at beginning of game I think that helps. anyway here is Configs for Sorc, Pally, Lead, and Follower. The help would be greatly appreciated.

Sorc (Lead): https://pastebin.com/YELLUa1u
Hdin (Follower): https://pastebin.com/sxHE2Ac1
Leader config: https://pastebin.com/i9dMdQEq
Follower config: https://pastebin.com/5CYgFWCF

**Comment by 5noop** [comment]
If your leader profile on d2bot is called tannerd00 the hdin should join, if it doesnt reinstall the .net dependency.

If you want them to party set Config.PublicMode to 2 for the hdin and 3 for the sorc.

**Comment by Tannerd00** [comment]
Thank you so much for the response! I was able to get my follower to join the same game. My sorc invites him to party because I set party config to 3. I also set my hdin to 2 so he can accept BUT... Hdin doesn't accept party invite and still doesn't recognize the sorc being in diablo/baal rooms. Lmk if I need to repost my new configs. I literally only changed name of profile to tannerd00 on d2bot program and changed party settings to "3" on sorc and "2" on hdin. Thanks again!

**Comment by 5noop** [comment]
`Config.Leader = "firedreyer";`
That's the exact name of your sorc ? (it's case sensitive)

**Comment by Tannerd00** [comment]
Dude your a fucking lifesaver!! <3 It works!!!

**Comment by Tannerd00** [comment]
changed f to F

**Comment by IronSkillit** [comment]
I have this problem as well. My MfHelpers join leader's games just fine. But when I run a manual player with follower bots, the followers won't join the game. they work fine once I manually join them into the game.

**Comment by medgram** [comment]
> I have this problem as well. My MfHelpers join leader's games just fine. But when I run a manual player with follower bots, the followers won't join the game. they work fine once I manually join them into the game.

Anyone can help with this ? I have that problem too... Followers wont join manual player, but if i join them by hand they do all what they have to in game.... only issue is joining...
