### ISSUE TITLE
Teleswitch fail

### ISSUE THREAD

**Issue by bmatusiak** [kolton/d2bot-with-kolbot#175]
the config says true for slot 2...  but as i'm looking into the code. i found that if i chicken when in slot 2... my main weapons become the slot2 next game.. causing the runs to go horrible

**Comment by LeMule** [comment]
In the Misc.js common lib, run to line 1563 (or search Precast.weaponSwitch();) and try passing it either a 1 or a 0 as a parameter.

It's a long shot. I have nothing to test this locally but it seems like you should be able to force it to a certain slot everytime.

**Comment by LeMule** [comment]
The Pather.js common lib actually seems to do a Precast.weaponSwitch(Misc.oldSwitch) if you have your Config.TeleSwitch enabled. Possibly forcing the value here instead would be ideal, but again, I'm just going off what I can read and cannot test any of these theories.

Let me know if either works out.

**Comment by bmatusiak** [comment]
@lemule fix is here

https://github.com/kolton/d2bot-with-kolbot/pull/176
