### ISSUE TITLE
total game time to be stated in console

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1751]
so i wana start tracking how long they take to clear cs
ive watched a few in the console but im not watching all the time
then they still rip cus not good enuf gear
i looked in the default only saw about min/max game time

help me out please

**Comment by DarkHorseDre** [comment]
check out misc.js

```js
	// Log to manager
	log: function () {
```

that function contains code that displays various data including gametime (getGameTime).
just output it to console with 
`D2Bot.printToConsole();`

**Comment by gtoilet** [comment]
i knew it was somewhere since it puts failed to kill deseis i want to see how long it took to fail/complete run
so far im seeing like 5-5.30 game times
