### ISSUE TITLE
Pally Bot get stuck in maggot lair

### ISSUE THREAD

**Issue by Fee920** [kolton/d2bot-with-kolbot#1770]
When there a monster by the door and bot try to teleport next to the monster, the bot go nowhere and get stuck there.  Is there a way to make bot open door instead?

**Comment by croboy** [comment]
It usually tries to kill monsters around the entrance then enter. Are you using the default script or have you edited something?

**Comment by Fee920** [comment]
default script, using clear any area for maggot lair

**Comment by Spoofzor** [comment]
I believe clearAnyArea use `Config.ClearType` 

I wonder if you could change to `Config.ClearType = 0;` which will attempt to kill all monsters on the level before proceeding.
This, of course, would make you kill all monsters in all areas

Alternatively, you might be able to add a simple if statement into `ClearAnyArea.js` to check if you are in maggot lair, if so then `Attack.clearLevel(0);`
Area ids can be found in sdk/areas.txt

**Comment by Fee920** [comment]
I think the main issue is that when the bot trys to kill the monster that is really close to the door, he cant teleport there due to no room, so it doesnt matter what kill type its set to because there could be a door in any direction depending on the direction order the bot is clearing first he may or may not get stuck.

Here is an example of what cloud of happen, bot clears the area from left to right.  All monster from left side and around him is dead.  The only monster left is the monster to the right which is behind a door.  Bot tries to kill monster on the right side, which is behind a door, but cant because the space is too tight and there is no room for bot to teleport to, so when he tries to teleport he dance around the door area after a while he skip the monster or something like that.  Usually when i see the bot get stuck, i click on the door many times for the bot to open door then he can kill monster with no issue.

**Comment by Spoofzor** [comment]
I see now. Thank you for the explanation.
I do not frequent maggot lair so I am unsure of some details off the top of my head. But, with your help we might be able to create a solution. We can add a check to attempt to open the door in maggot lair.

What is the title of 'door' in maggot lair? When you mouse over it, what is it called?

This may involve editing 
`Pather.js` (where openDoor is defined) - Need to add the doors in maggot lair to be detectable (I dont see it currently available)
`Attack.js` - while clearing.. check for maggot lair, failed movement/kill attempts in maggot lair, and then if doors nearby in maggot lair

Then the trial and error portion!

**Comment by Fee920** [comment]
The door is call "CLOSED DOOR"

**Comment by Fee920** [comment]
i dont know much about coding, if you can edit the script and i can test it out

**Comment by Jimetics** [comment]
Out of curiosity, did you by any chance find a solution for this?

**Comment by Fee920** [comment]
no. and i kinda of stop botting
