### ISSUE TITLE
Save picked items log

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1773]
Is it possible to save picked items log?

I mean this one:
![afdssdddffd](https://user-images.githubusercontent.com/31447095/61054832-efafbf00-a3f8-11e9-952a-d7c267be23f1.png)

**Comment by gtoilet** [comment]
it will
https://imgur.com/a/2BSZJgd

**Comment by ARkaine2** [comment]
> it will
> https://imgur.com/a/2BSZJgd

I mean some way to save log (let's say something like "save as..." function) even if we'll close bot application and then start it again.

**Comment by tc85** [comment]
It is already saved (just not in a nice to read format), everything that the bots log in their console is also saved in `./d2bs/d2bs.log`. The strange `ÿc2` parts are just the text color
