### ISSUE TITLE
Pickit Q

### ISSUE THREAD

**Issue by semirotta** [kolton/d2bot-with-kolbot#1774]
Can I make pickit pick up items when im playing myself with maphack for example? or is this function only when the bot is running by itself?

EDIT:
Secondary question is, is it possible to have low lvl character RUN tristrams instead of teleport? because until certain level you don't have teleportation access. Will it still run but just without the teleport?

**Comment by gtoilet** [comment]
there was some manual.js out there i think had that function idk never used it
yes bot will run with out tele

**Comment by semirotta** [comment]
I just wish I could have pickit running without running bot everywhere same time.
