### ISSUE TITLE
bot controls

### ISSUE THREAD

**Issue by semirotta** [kolton/d2bot-with-kolbot#1777]
Not really an issue, just a query: what were the buttons to pause and continue bot while in-game without forcing restart?

I forgot the keys for this completely and couldn't find them through Wiki nor googling. Anyone know them?

**Comment by Jtc9289** [comment]
Pause/ break key mines above backspace  ?

**Comment by semirotta** [comment]
> Pause/ break key mines above backspace ?
> 
> And I googled kolbot controls and 2nd link
> https://github.com/mf022/d2bs/wiki/Hotkeys
> 
> Lmao

LOL wtf I googled for Kolbot controls and found nothing. Went through the whole page. Then I tried to search for controls in wiki but nothing. Ofc I should have searched for HOTKEYS.

Thank you anyway, I tried pause break but had  the log info away so I didnt know if it paused or not :'D
