### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by xiphias12** [kolton/d2bot-with-kolbot#1780]
Geting this error message:
"Login error - Battle.net is not responsing. Please try connecting again in a few minutes. "

I only get it on followers using proxy. The proxies working fine otherwise but I got pretty high latency.

The problem is that the bot shutts down and doesnt try to connecting again after x minutes like other errors like ex. RD. 

How can I make it restart? 

Thanks

**Comment by Berry9** [comment]
I had the same, turned out to be an IP Ban for an accidentally turning on my VPN while using D2. I heard its for 2 weeks if you wait it out, otherwise I reset my IP and re-installed and works fine again
