### ISSUE TITLE
Pickit help needed

### ISSUE THREAD

**Issue by semirotta** [kolton/d2bot-with-kolbot#1782]
I need to pick up Crystal sword 4 sox if found. How do I do that? I tried bunch of things and it always said it was invalid so I just removed it completely for now.

Can anyone give me a hand with this? I'm trying to get Spirit sword to use, almost have runes for it but no sword found. Though I am farming Nightmare since I cant stay alive in Hell for a long time yet.

**Comment by odog13** [comment]
man this is a place to post real programm problems and not things you can find all over the internet if using google but anyways heres the pickit line

[name] == crystalsword && [quality] == normal && [flag] != ethereal # [sockets] == 4

**Comment by semirotta** [comment]
Funny thing is, I always google first...I just can't find anything. I don't know why but googling never yields results when it comes to this. It takes me to very old websites that are no longer functioning or have outdated information. I am sorry but i'd rather ask here than stay idle wondering and trying without success.

So thank you for your patience and good nature, I can now continue and try to find a CS with 4 sox.
