### ISSUE TITLE
Issue at bo script

### ISSUE THREAD

**Issue by xiphias12** [kolton/d2bot-with-kolbot#1783]
I replaced normal bo script with the one from nag0k that should stay at wp all game for re-bo later on. The problem is that my chars only end up precasting holy shield and frozen armor while barb boing etc. They never leave. What's the issue?

**Comment by xiphias12** [comment]
This is the script I am replacing my BattleOrders.js with:

/**
*	@filename	BattleOrders.js
*	@author		nag0k
*	@desc		give Battle Orders buff modded for hardcore, with barbarian waiting whole game on Catacombs 2 wp
*				- the values in lines 14-16 are customizable. 
*				- in barbarian config file you should have Scripts.BattleOrders = true; and Config.QuitList = ["..."]; should be completed.
*				- other chars should have in the running area scripts the lines to get the wp where Boer is:
*					    Pather.useWaypoint(35, true); // take Boer wp
*					    Pather.moveTo(me.x + 5, me.y + 5);
*					    delay(3000);
*/

const BattleOrders = () => {
	const BO_WP = 35; // area to buff - 35 is catacombs level 2
	const TOWN_NEARBY_MONSTER = true; // go to town if monsters nearby
	const TOWN_MANA = 20; // go refill mana if mana drops below this percent

	const shouldHealMana = amount => me.mp < Math.floor(me.mpmax * amount / 100)

	const healMana = () => {
		Pather.useWaypoint(1);
		Town.initNPC("Heal", "heal");
		Pather.useWaypoint(BO_WP);
	};

	const shouldBuff = unit => (
		Misc.inMyParty(unit) &&
		getDistance(me, unit) < 10 &&
		unit.name !== me.name &&
		!unit.dead &&
		!unit.inTown
	)

	const giveBuff = () => {
		const unit = getUnit(0);

		do {
			if (shouldBuff(unit)) {
				Precast.doPrecast(true);
			}
		} while(unit.getNext());
	};

	const monsterNear = () => {
		const unit = getUnit(1);

		if (unit) {
			do {
				if (Attack.checkMonster(unit) && getDistance(me, unit) < 20) {
					return true;
				}
			} while(unit.getNext());
		}

		return false;
	};

	if (!Config.QuitList) {
		showConsole();
		print('Set Config.QuitList in character settings');
		print('If you don\'t I will idle indefinently');
	}

	if (me.playertype && Config.LifeChicken <= 0) {
		showConsole();
		print('ON HARDCORE');
		print('YOU SHOULD SET CHICKEN LIFE');
		print('MONSTERS CAN FIND THEIR WAY TO WPS..');
	}

	if (shouldHealMana(TOWN_MANA)) {
		Town.initNPC("Heal", "heal");
	}

	Town.heal(); // incase our life is low as well

	try {
		Pather.useWaypoint(BO_WP);
	} catch (e) {
		showConsole();
		print('Failed to move to BO WP');
		print('Make sure I have ' + Pather.getAreaName(BO_WP) + ' waypoint');
		delay(20000);

		return true;
	}

	Pather.moveTo(me.x + 4, me.y + 4);

	while (true) {
		giveBuff();

		if (TOWN_NEARBY_MONSTER && monsterNear()) {
			if (!Pather.useWaypoint(1)) {
				break;
			}
		}

		if (shouldHealMana(TOWN_MANA)) {
			healMana();
		}

		delay(25);
	}

	return true;
}


I got this in charconfig Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 0; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = ["XXX", "XXX"]; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.

Barb stands and spams BC,BO,Shout.
Sorc spams frozen armor and pala spams holy shield..

**Comment by 5noop** [comment]
Please don't copy/paste scripts here, use pastebin or some other site.

About your issue it's expected behavior, the script is just for barb.

**Comment by xiphias12** [comment]
> Please don't copy/paste scripts here, use pastebin or some other site.
> 
> About your issue it's expected behavior, the script is just for barb.

Sorry about that, wont happen again.
Do you have any ideas how to get it to work?

**Comment by 5noop** [comment]
Yeah it's written in the script. Or just use nag0k script on your barb and the default script on the others.

**Comment by xiphias12** [comment]
> Yeah it's written in the script. Or just use nag0k script on your barb and the default script on the others.

This is the script: https://pastebin.com/JTmWbqLf

I have setup in barb:
- in barbarian config file you should have Scripts.BattleOrders = true; and Config.QuitList = ["..."]; should be completed.

I've added this in scripts: - other chars should have in the running area scripts the lines to get the wp where Boer is:
*                       Pather.useWaypoint(35, true); // take Boer wp
*                       Pather.moveTo(me.x + 5, me.y + 5);
*                       delay(3000);

Those are the only things I can see in the script? That's how I did and ended like this.

Could I just paste nag0k script in the folder and name it BattleOrdersNag0k and edit it in char config?
