### ISSUE TITLE
BO Barb & Sorc BOTH casting BO over and over.

### ISSUE THREAD

**Issue by T3chn1x** [kolton/d2bot-with-kolbot#1784]
Hi,

**-** I have my BO Barb setup to follow my MF sorc into games and give her BO.

**-** However when they go to Cata 2, the barb keeps casting over and over & the sorc is casting BO, BC and Frozen Armor over and over.

**-** I took CTA off of my sorc, and shes still weapon switching then casting frozen armor and repeating over and over sitting at WP with barb.

**-** In character config files I have the Sorc set to "get bo" and the barb to set to "give bo".

Can anyone help?
--------------------------------

**Sorc config**
`	// User addon script. Read the description in libs/bots/UserAddon.js
	Scripts.UserAddon = true; // !!!YOU MUST SET THIS TO FALSE IF YOU WANT TO RUN BOSS/AREA SCRIPTS!!!

	// Battle orders script - Use this for 2+ characters (for example BO barb + sorc)
	Scripts.BattleOrders = false;
		Config.BattleOrders.Mode = 1; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = []; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.`

**Barb config**
`	// User addon script. Read the description in libs/bots/UserAddon.js
	Scripts.UserAddon = false; // !!!YOU MUST SET THIS TO FALSE IF YOU WANT TO RUN BOSS/AREA SCRIPTS!!!

	// Battle orders script - Use this for 2+ characters (for example BO barb + sorc)
	Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 0; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = ["SorcNameHere"]; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.`

**Comment by xiphias12** [comment]
Are you using nag0k's boscript?

**Comment by T3chn1x** [comment]
> Are you using nag0k's boscript?

Yes.

**Comment by oband2** [comment]
how about turn it into "true" on your sorc, its false now.

**Comment by T3chn1x** [comment]
I figured it out.
