### ISSUE TITLE
How to show in game ip address? 

### ISSUE THREAD

**Issue by XDarkwolf21** [kolton/d2bot-with-kolbot#1786]
Can anyone help me figure out how to get d2bot map to show my in gf ame ip address?

**Comment by Kantonov** [comment]
```
var ip = Number(me.gameserverip.split(".")[3]);
print(ip);
```
I think this will help. Insert those two line in some script you are running. For example on top of battle orders.

**Comment by XDarkwolf21** [comment]
You rock TY!
