### ISSUE TITLE
CRush problems- attackCount Exceeded and act2-3 switch fail

### ISSUE THREAD

**Issue by Zulunations** [kolton/d2bot-with-kolbot#180]
Hey guys

have a problem:
Trying to set up classic Rushes, following happens:

Act 2: Duriel
Sorc (Orb + Firewall, static now 50 (tryed 1 and 10 also...)
Goes in to duriel and after 1 sec he skips and in console:
Failed to kill Duriel attackCount exceeded.

Same happesn for Mephisto...

Further the switch from act 2 to 3 doesnt work. Rushee's walking between jerhyn and meschif and dont click on meschif...

ty for your help guys

**Comment by dzik87** [comment]
#181 should solve your problem.

**Comment by Milburn1** [comment]
Hi, how did you solve this problem? I faced the same...
