### ISSUE TITLE
Error Attack.JS line 298

### ISSUE THREAD

**Issue by keyz54** [kolton/d2bot-with-kolbot#1800]
I had a blizz sorc, and she ran perfectly, I switched her to a lightning sorc and now when she gets to a boss, for example: Andariel, she wont attack and I get error: Error in Andariel (attack.js line 298): Failed to kill Andariel

here is my attack config:
/* Attack config
	 * To disable an attack, set it to -1
	 * Skills MUST be POSITIVE numbers. For reference see http://pastebin.com/baShRwWM
	 */
	Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 49; // Primary skill to bosses.
	Config.AttackSkill[2] = -1; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 53; // Primary skill to others.
	Config.AttackSkill[4] = -1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

I can't seem to find the problem? Any ideas?

**Comment by drako87** [comment]
d2bs\kolbot\libs\config\Templates\Attacks.txt

`*** Single element - blizzard + glacial spike

	Config.AttackSkill[0] = -1; // Preattack skill. Not implemented yet.
	Config.AttackSkill[1] = 59; // Primary skill to bosses.
	Config.AttackSkill[2] = 55; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 59; // Primary skill to others.
	Config.AttackSkill[4] = 55; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

*** Dual element - frozen orb + nova (with glacial spike to lightning immune)

	Config.AttackSkill[0] = -1; // Preattack skill. Not implemented yet.
	Config.AttackSkill[1] = 64; // Primary skill to bosses.
	Config.AttackSkill[2] = 48; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 64; // Primary skill to others.
	Config.AttackSkill[4] = 48; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 55; // Secondary untimed skill if monster is immune to primary untimed.

*** Dual element - blizzard + fireball (with meteor to cold immune and glacial spike to fire immune)

	Config.AttackSkill[0] = -1; // Preattack skill. Not implemented yet.
	Config.AttackSkill[1] = 59; // Primary skill to bosses.
	Config.AttackSkill[2] = 47; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 59; // Primary skill to others.
	Config.AttackSkill[4] = 47; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 56; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 55; // Secondary untimed skill if monster is immune to primary untimed.

*** Tri-element - blizzard with fireball, meteor on cold immune, nova on fire immune

	Config.AttackSkill[0] = -1; // Preattack skill. Not implemented yet.
	Config.AttackSkill[1] = 59; // Primary skill to bosses.
	Config.AttackSkill[2] = 47; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 59; // Primary skill to others.
	Config.AttackSkill[4] = 47; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 56; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 48; // Secondary untimed skill if monster is immune to primary untimed.

*** Tri-element - frozen orb with nova, fire wall on cold immune, glacial spike on lightning immune

	Config.AttackSkill[0] = -1; // Preattack skill. Not implemented yet.
	Config.AttackSkill[1] = 64; // Primary skill to bosses.
	Config.AttackSkill[2] = 48; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 64; // Primary skill to others.
	Config.AttackSkill[4] = 48; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 51; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 55; // Secondary untimed skill if monster is immune to primary untimed.`

**Comment by 5noop** [comment]
Looks correct. Did you set any CustomAttack ?

**Comment by keyz54** [comment]
I found out what the problem was! When I respec'd from a Blizz to Lightning sorc (and acquired infinity) I changed the skip immunes line from ["Cold"] to [""]. The open quotations made it so that my character skipped everything. I deleted the quotations so that it showed []. 

Problem solved.. Thats what happens when you edit your scripts at 3am...

**Comment by Milburn1** [comment]
Hello, in which of the scripts did you edit these parameters?

**Comment by benp100** [comment]
Thx so much, i had the same problem here [""] hahaha ;) after i remove cold
