### ISSUE TITLE
attack error in #214

### ISSUE THREAD

**Issue by ryojoseph** [kolton/d2bot-with-kolbot#181]
Error in DiabloHelper (attack.js #214) Failed to kill Diablo (attackCount exceeded) (Area: 108, Ping:203, Game
 Error in BaalHelper (attack.js #214) Failed to kill Baal (attackCount exceeded) (Area: 132, Ping:265, Game:

**Comment by WiZzMaN47** [comment]
d2bs\kolbot\libs\common\attack.js
	if (attackCount === 300) {              ; <----------- "try to increase this number"
			errorInfo = " (attackCount exceeded)";
		}

		if (Config.MFSwitchPercent) {
			Precast.weaponSwitch(Math.abs(Config.MFSwitch - 1));
		}

		ClassAttack.afterAttack();

		if (!target || !copyUnit(target).x) {
			return true;
		}

		if (target.hp > 0 && target.mode !== 0 && target.mode !== 12) {
			throw new Error("Failed to kill " + target.name + errorInfo);
		}

		return true;

**Comment by Milburn1** [comment]
Hi, how did you solve this problem? I faced the same...
