### ISSUE TITLE
Possible to make bot sell found useless stuff?

### ISSUE THREAD

**Issue by semirotta** [kolton/d2bot-with-kolbot#1819]
Bot currently drops the crappy stuff on ground, way to make it sell them for money instead of dropping? The decent / good stuff it takes to chest as wanted.

**Comment by gbgodoy** [comment]
check this
Config.CainID.Enable = false; // Identify items at Cain

**Comment by semirotta** [comment]
> check this
> Config.CainID.Enable = false; // Identify items at Cain

How is this going to help me? That only changes if the bot uses cain to identify or not. My bot identifys at cain, drops the items at Cain. I would like the bot to SELL the useless items instead of dropping them on ground.

**Comment by Jtc9289** [comment]
If u turn cain Id off it will id and sell at vendor

**Comment by semirotta** [comment]
> If u turn cain Id off it will id and sell at vendor
> 
> If ur losing gold botting upgrade merc

Wait what, so that has to be turned off in order for it to use book and indetify in store?
if Cain is used, it only drops? Holy heck well that is not the wises decision for it. I lose gold because I gamble :'D but thanks and @gbgodoy Sorry you were right, you just didn't explain the fact that if using Cain id, it drops and if not using Cain id, it shops.

Thanks all!

**Comment by Jtc9289** [comment]
// Item identification settings
	Config.CainID.Enable = false; // Identify items at Cain
	Config.CainID.MinGold = 2500000; // Minimum gold (stash + character) to have in order to use Cain.
	Config.CainID.MinUnids = 3; // Minimum number of unid items in order to use Cain.

U can change these settings just gotta read

**Comment by mf022** [comment]
> if Cain is used, it only drops?

by default this is the bot behavior, but take a look to
https://github.com/mf022/d2bs/wiki/Misc_options#use-cain-and-sell-items

**Comment by semirotta** [comment]
Yeah thanks bunch, but I don't want to mess with the other files because I have tendency to ruin everything. I'll edit these few files I was told how to do it
