### ISSUE TITLE
Kolbot 1.14d

### ISSUE THREAD

**Issue by Bene-paul-dev** [kolton/d2bot-with-kolbot#182]
Hi there,

I already saw the other post regarding 1.14d, but it wont work for me as I dont have a 1.14c installation.
Is there a complete guide / tutorial to get Kolbot to work with 1.14d?

Thanks in advance

**Comment by mboufos** [comment]
check this video
https://www.youtube.com/watch?v=IhaPg5hYw18

**Comment by Bene-paul-dev** [comment]
Thanks you, I already found this. Unfortunately the download links from the video's comments are not available anymore

**Comment by mboufos** [comment]
is it safe to post your email here to send you a link ?

**Comment by Bene-paul-dev** [comment]
sure. hackbraten@gmail.com

**Comment by mboufos** [comment]
ok got it delete it :P i got it hehee
