### ISSUE TITLE
leecher dont bo before getting throne?

### ISSUE THREAD

**Issue by odog13** [kolton/d2bot-with-kolbot#1826]
how can i edit config / scripts that leechers dont take random waypoint to cast bo before entering leader tps ?? it takes too much time for me

**Comment by mpoaso** [comment]
i have exact same problem, i tried figure it out myself, no mather what you set it will still go to boo before enterting tp, for example if leecher went to find shrine, after it will still use wp to boo, which is unessecary, becouse it already precasted when went to get shrine

**Comment by odog13** [comment]
yep exactly

**Comment by odog13** [comment]
> 
> 
> i have exact same problem, i tried figure it out myself, no mather what you set it will still go to boo before enterting tp, for example if leecher went to find shrine, after it will still use wp to boo, which is unessecary, becouse it already precasted when went to get shrine

ok man i figured out^^ open baalhelper.js go to line 174 and put a // before (before Pather.useWaypoint)

thats all, enjoy^^

**Comment by mpoaso** [comment]
Can confirm its working, i used for Baalassistant line 369 i put before Pather.useWaypoint("random"); - // and set false instead of true do precast, so all lines from 369 to 374 looks like this 
					//Pather.useWaypoint("random");
					Precast.doPrecast(false);
				} else {
					//Pather.useWaypoint(129);
					Precast.doPrecast(false);
