### ISSUE TITLE
console manager

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1828]
so its got console / char view / key wiz

where would i go to start trying to add another tab for errors / xp log

im getting alot of fail to kill/open seal in CS since im only running 2man games
i want to try to make a tab for them errors or for xp log
so some of the info i want to keep track of dont get lost in the list of bad

**Comment by 5noop** [comment]
You would need to edit d2bot source code for that and it's not public.

**Comment by gtoilet** [comment]
appreciate it i atleast got an answer maby ill just remove its error msgs to hide some of the bs

thanks
