### ISSUE TITLE
Problem with fix 1.14d for kolbot

### ISSUE THREAD

**Issue by Ultriso** [kolton/d2bot-with-kolbot#183]
Hello.

By mistake I update my working diablo 2 to patch 1.14d. When I fix again with correct files, bot start diablo 2, but do not initiate d2bs on window..
How to fix this?
All *.exe got admin permissions.
I try my way on fresh bot, still don't work.

Regards.

**Comment by dzik87** [comment]
Kolbot repository is not official source to get help about versionhack - ask at bh forum or irc
