### ISSUE TITLE
Followers don't talk with NPC(s) via command

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1832]
Subj.

When I play as leader and write "talk cain" (without quotes) follower answers "Invalid NPC" or when I write "Talk Cain" (without quotes again) follower does nothing.

What am I doing wrong?
How (in which format) should i write this command?

In Follower.js I read:
```
		switch (me.act) {
		case 1:
			names = [NPC.Gheed, NPC.Charsi, NPC.Akara, NPC.Kashya, NPC.Cain, NPC.Warriv];

			break;
		case 2:
			names = [NPC.Fara, NPC.Lysander, NPC.Greiz, NPC.Elzix, NPC.Jerhyn, NPC.Meshif, NPC.Drognan, NPC.Atma, NPC.Cain];

			break;
		case 3:
			names = [NPC.Alkor, NPC.Asheara, NPC.Ormus, NPC.Hratli, NPC.Cain];

			break;
		case 4:
			names = [NPC.Halbu, NPC.Tyrael, NPC.Jamella, NPC.Cain];

			break;
		case 5:
			names = [NPC.Larzuk, NPC.Malah, NPC.Qual_Kehk, NPC.Anya, NPC.Nihlathak, NPC.Cain];
```
and it seems that i write name of Cain correctly.

**Comment by ARkaine2** [comment]
I found reason why bot couldn't talk with Cain via command.
That's because Cain quest wasn't done.
But anyway Cain was in acts 2--5 and bot couldn't talk with him yet quest wasn't done.

**Comment by TheDarkmess** [comment]
I m actually experiencing the same issue.. but Cain quest is done..
any clue?

Thanks

**Comment by TheDarkmess** [comment]
still having this problem.. any1 can help?
Thanks
