### ISSUE TITLE
Follower "ExitDelay" (Exit Game Delay)

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1837]
There's in D2BotFollow.dbj function:

```
// Advanced config - you don't have to edit this unless you need some of the features provided
var AdvancedConfig = {
	/* Features: Override join delay for each profile

	* Format *:
		"Profile Name": {JoinDelay: number_of_seconds}

	* Example * (don't edit this - it's just an example):
		"MyProfile1": {JoinDelay: 3},
		"MyProfile2": {JoinDelay: 6}
	*/
```

But is it possible to set exit game delay between different profiles when followers leave game (after leader exited the game or via exit command)? Because i get RD if all followers exit same time. I mean that i need opposite function to "JoinDelay" that will add delay on exit ("ExitDelay").

**Comment by SonnyDAscola** [comment]
You mean game exit?

**Comment by ARkaine2** [comment]
SonnyDAscola,
Yes.

**Comment by SonnyDAscola** [comment]
I will take a look, haven't used follow up till now.

Think there is a way by adding a delay to the next game join (which should result in leaving the old one), but will test it before posting it here.

**Comment by SonnyDAscola** [comment]
I found a quick way to implement this feature by editing 2 lines of code if you are interested. I've tested it already, it works like intended.

When leader exits the game, the profile char exits with delay - customizable for each charakter/profile individually this is what u wanted, right?

**Comment by mf022** [comment]
Did you check https://github.com/kolton/d2bot-with-kolbot/issues/1462#issuecomment-484983690 ?

**Comment by tylerqr** [comment]
@SonnyDAscola I would like those lines of code, pretty please.

**Comment by Mercoory** [comment]
@SonnyDAscola I also looking for that revision, but it is removed from your repository. Also your readme was so promising, I have some ideas too!

**Comment by SonnyDAscola** [comment]
@Mercoory @tylerqr 
hey guys, sorry was on vacation lately. A new revision of my extension project will launch soon. 
At first it was only an idea to provide some fixes but i've come to the conclusion, that some of the ideas deserve a proper way of dealing with it and keeping it public available in a good condition.

@Mercoory you are welcome to share your ideas mate, you also may join me on my quest! I've discussed many things with two friends, all playing for 12 years+, what would be nice to have and what could be optimized. You are also welcome to join our discord and the discussion of what would be a nice to have

@mf022 thank you very much, no haven't seen this to be honest! Great that there's already a way, will take a look and implement it like given for start

**Comment by Mercoory** [comment]
@SonnyDAscola I tried to find your contact, but I was not successful. Please try to reach me, my email address is can be found - or solved :) - via : https://pastebin.com/CKm6F0gV . Thanks

**Comment by Kephren999** [comment]
I solved it but the hard way prob lol

Look at the very bottom of baalhelper script
Add
(Delay 5000) change this number to any amount you like so you can stager exiting 

Add it right after pickitems and quit
You have to do this for each char profile 

I also added a town check so they can be ready for the next run
I’ll post it after I get home
