### ISSUE TITLE
KolBot doesn't skip monsters.

### ISSUE THREAD

**Issue by Iasco** [kolton/d2bot-with-kolbot#1839]
I have 0xF set, but my Kolbot attacks almost every monster still..

Rarely skips anything.

Any help?

**Comment by SonnyDAscola** [comment]
Same problem here

**Comment by 5noop** [comment]
Which scripts are you running ? It won't work with Diablo but it should work with most scripts.

**Comment by SonnyDAscola** [comment]
Clearlevel seems only to apply to the following scripts (image)

You could add these lines to the other scripts i guess?

![clearlevel](https://user-images.githubusercontent.com/44882166/62250231-a8f82800-b3ec-11e9-9b4d-d24f0c9bf30e.PNG)

**Comment by Iasco** [comment]
Its not necessarily that it clears all monsters when it gets to its destination thats the issue.

Its that it doesnt skip any on the way.  For example; when running Andariel, it stops at almost every pack of monsters on the way.  Ideally it would tele straight to Andarials room,  then start clearing.

Another example, is when running baal, it takes almost 4 minutes to get to Throne because it stops and fights everything on the way.

**Comment by 5noop** [comment]
That's not default behavior, did you modify anything or do you use Config.ClearPath ?

**Comment by Iasco** [comment]
> That's not default behavior, did you modify anything or do you use Config.ClearPath ?

Not that I am aware of~ Let me compare to fresh

**Comment by Iasco** [comment]
> That's not default behavior, did you modify anything or do you use Config.ClearPath ?

So I just searched for ClearPath in the directory.  Everything is false

**Comment by Iasco** [comment]
> That's not default behavior, did you modify anything or do you use Config.ClearPath ?

So I made a fresh install, and it seems to be skipping just fine.

??????

**Comment by Iasco** [comment]
> That's not default behavior, did you modify anything or do you use Config.ClearPath ?

Fixed it!

There was an issue in Pather..

Thanks for making me use my brain, idk what you said, but it made me dig and find it after a week of frustration.
