### ISSUE TITLE
setting up attack for bot 1.14d

### ISSUE THREAD

**Issue by damonck** [kolton/d2bot-with-kolbot#184]
i have got the version hack working and i have setup what i want the bot to farm but im not sure how to setup what it uses to attack for my lightning sorc

**Comment by mboufos** [comment]
check some videos on youtube

**Comment by damonck** [comment]
ive tried to watch a few of those videos but they dont help me with the errors im getting with the bot saying attacks are not set and when i do set them it comes up saying somethings wrong withit

**Comment by mboufos** [comment]
what is the error ? because its easy to set up attacks 
http://pastebin.com/baShRwWM click on this

and then
	Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = -1; // Primary skill to bosses.
	Config.AttackSkill[2] = -1; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = -1; // Primary skill to others.
	Config.AttackSkill[4] = -1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.
replace -1 to the attack

**Comment by mboufos** [comment]
Config.AttackSkill[1] = 49; // Primary skill to bosses.   //lighting
Config.AttackSkill[3] = 53; // Primary skill to others.  //chain light 
if you want always to hit with lighting just put 49 both

**Comment by damonck** [comment]
i have the attacks set for those do you have the attack.js part line 12 is wrong for me and default.dbj line 97 is wrong those are the 2 errors im getting for some reason if it works it comes up as bad attack bot wont attack

**Comment by WiZzMaN47** [comment]
Config.AttackSkill[0] = 64; // Preattack skill.
	Config.AttackSkill[1] = 64; // Primary skill to bosses.
	Config.AttackSkill[2] = 55; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 64; // Primary skill to others.
	Config.AttackSkill[4] = 55; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 42; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 49; // Secondary untimed skill if monster is immune to primary untimed.

Sorceress:
36 - Fire Bolt
37 - Warmth
38 - Charged Bolt
39 - Ice Bolt
40 - Frozen Armor
41 - Inferno
42 - Static Field
43 - Telekinesis
44 - Frost Nova
45 - Ice Blast
46 - Blaze
47 - Fire Ball
48 - Nova
49 - Lightning
50 - Shiver Armor
51 - Fire Wall
52 - Enchant
53 - Chain Lightning
54 - Teleport
55 - Glacial Spike
56 - Meteor
57 - Thunder Storm
58 - Energy Shield
59 - Blizzard
60 - Chilling Armor
61 - Fire Mastery
62 - Hydra
63 - Lightning Mastery
64 - Frozen Orb
65 - Cold Mastery

**Comment by dzik87** [comment]
read:
\d2bs\kolbot\sdk\skills.txt
\d2bs\kolbot\libs\config\Templates\Attacks.txt

There is everything how to setup bot.
Also before asking read wiki where you have a lot of informations about setting up bot
https://github.com/kolton/d2bot-with-kolbot/wiki

**Comment by damonck** [comment]
I looked at videos and know the numbers for the attacks how ever the bot wouldnt attack

Sent from my iPhone

On 6 Sep 2016, at 6:59 AM, dzik <notifications@github.com<mailto:notifications@github.com>> wrote:


read:
\d2bs\kolbot\sdk\skills.txt
\d2bs\kolbot\libs\config\Templates\Attacks.txt

There is everything how to setup bot.
Also before asking read wiki where you have a lot of informations about setting up bot
https://github.com/kolton/d2bot-with-kolbot/wiki

-
