### ISSUE TITLE
[Strict Warning (162)] File(kolbot\libs\common\misc.js:1974) reference to undefined property obj[i]

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1843]
Each time I get this error warning.

[Strict Warning (162)] File(kolbot\libs\common\misc.js:1973) reference to undefined property obj[i]
AND
[Strict Warning (162)] File(kolbot\libs\common\misc.js:1974) reference to undefined property obj[i]

![image](https://user-images.githubusercontent.com/31447095/62275811-6b76b780-b44b-11e9-896f-66cd475057ee.png)

In Misc.js (strings 1969--1978):

```

		// Handle Array
		if (obj instanceof Array) {
			copy = [];

			for (i = 0; i < obj.length; i += 1) {
				copy[i] = this.clone(obj[i]);
			}

			return copy;
		}

```

What can be wrong?

**Comment by mf022** [comment]
you could try to compare using SVN Diff for your Misc.js

if this error persists, try to use [SVN Update](https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md#keep-bot-files-updated) for your d2bot-with-kolbot folder

**Comment by Morzh1978** [comment]
Seems like you have accidentally disabled some line of configuration code whilst mending your character config file or leaving your file open unattended so accidental keystroke etc. delivered the damage then changes were saved with no prior checks for integrity.

Simple example: 

[Strict Warning (162)] File(kolbot\libs\common\loader.js:54) reference to undefined property obj[i]
AND
[Strict Warning (162)] File(kolbot\libs\common\town.js:280 reference to undefined property Config.MinColumn[i]
AND
[Strict Warning (162)] File(kolbot\libs\common\misc.js:1952) reference to undefined property obj[i]

appears IF that line: 

**Config.MinColumn[3] = 0;**

is removed by error, whilst mending setting for pickits shown below.

	// Pickit config. Default folder is kolbot/pickit. 


So I would suggest you re-check your character config file line-to-line, ideally comparing with a default or older one for something weird that you would not mend on purpose, and begin near the areas you remember to mend last.

**Comment by Morzh1978** [comment]
Also: I may appear that you character still keeps running flawlessly and you can just ignore it.
However, it could trigger stalls and crashes (especially if further config mending creates demand for erroneously disabled functions), so it is better to rectify the issue ASAP.

**Comment by LordOfWinterfell22** [comment]
i have this same prob, i know this post is old but did you ever fix this? wont buy or pickup potions

**Comment by Samael36** [comment]
Had this problem today and went through what I changed recently and realized I accidentally put an extra coma between two character names :
Config.QuitList = ["CharName1", ,"CharName2"]
I guess you will need to remember what you changed before the problem started or verify each line one by one.
