### ISSUE TITLE
The right option ?

### ISSUE THREAD

**Issue by theodor77** [kolton/d2bot-with-kolbot#1850]
Hello guys !
I have  one berserk barb  and on the first  weapon  tab i have  grief+beast .
On the second tab i have 2 x hoto .
What option  i need to do   , whene the barbarian cast the BO's  turn   to the seconb tab  ?
Its +6 skill lvl more !
Thank guys !

**Comment by DarkHorseDre** [comment]
precast should do it automatically

what is happening now? bot switches weapon to hotos, casts bc/bo/shout, then doesn't switch back, then attacks?

**Comment by theodor77** [comment]
> precast should do it automatically
> 
> what is happening now? bot switches weapon to hotos, casts bc/bo/shout, then doesn't switch back, then attacks?

Thank you  brother , i fix it !
Its all ok !
