### ISSUE TITLE
Bot stashes gems but will not reroll charms

### ISSUE THREAD

**Issue by GosKKU** [kolton/d2bot-with-kolbot#1857]
Bot suddenly stopped rerolling Grand Charms.
At first it was cubing and throwing gems away.
I defined the gems in pickit, it began stashing them but still not rolling.
Any help will be much appreciated.

https://pastebin.com/LKDJeTfb

p.s. had the same problem with another char and it worked after I replaced charconfig with an older version.

**Comment by DarkHorseDre** [comment]
You don't put ingredients in pickit for cubing - the comments in the config state the bot will collect them when needed.

so you define cubing, enable the recipe you want (magic reroll in this case I guess) and it will collect gems then reroll the items if they fit the criteria (e.g. magic items need to be level 91+ as per cubing.js recipe definition).

remove gems from pickit unless you want them for OTHER things (else your stash will get full of em) and just enable cubing, the recipe and either place the base item in stash or have it in pickit, with correct ilvl)

**Comment by GosKKU** [comment]
Changed: Removed gems from the pickit 
                 Disabled Flawless to Perfect push in charconfig

Unchanged & Active:
```
Config.Cubing = true; // Set to true to enable cubing.
Config.Recipes.push([Recipe.Caster.Amulet]); // Craft Caster Amulet
Config.Recipes.push([Recipe.Blood.Ring]); // Craft Blood Ring
Config.Recipes.push([Recipe.Caster.Boots, "Wyrmhide Boots"]); // Craft Mana Boots
Config.Recipes.push([Recipe.Reroll.Magic, "Grand Charm"]); // Reroll magic Grand Charm (ilvl 91+)
Config.MakeRunewords = true; // Set to true to enable runeword making/rerolling
Config.Runewords.push([Runeword.Insight, "Thresher", Roll.Eth]); // Make Insight Thresher
Config.KeepRunewords.push("[type] == polearm # [plusskillcriticalstrike] ==6 && [enhanceddamage] >= 260");
```
In stash , double checked using UserAddon:
Grand charm = Item Level99
Eth Thresher 4 free sockets

As a result the champ no longer picks any games ( Observed him passing by flawless sapphire & flawless amethyst).
Paused and pick them up manually and the bot went on to sell them to the NPCs.

https://pastebin.com/0UTSzSZq - current champ config with which he doesn't pick up gems.

**Comment by DarkHorseDre** [comment]
Flawless gems has nothing to do with OP - if you want to cube flawless to pgem, then thats a different recipe, and you need pickit to keep the pgems u create.

If it has 3 pgems and that GC it should roll it, assuming the GC doesnt match your pickit - have you checked this?
do you still have a magic rolling issue?

**Comment by GosKKU** [comment]
Removed Grand Charm Item level 99 from the pickit and the issue no longer persists.

Thank you for your help and quick responses DarkHorseDre :1st_place_medal:

**Comment by Samael36** [comment]
> Changed: Removed gems from the pickit
> Disabled Flawless to Perfect push in charconfig
> 
> Unchanged & Active:
> 
> ```
> Config.Cubing = true; // Set to true to enable cubing.
> Config.Recipes.push([Recipe.Caster.Amulet]); // Craft Caster Amulet
> Config.Recipes.push([Recipe.Blood.Ring]); // Craft Blood Ring
> Config.Recipes.push([Recipe.Caster.Boots, "Wyrmhide Boots"]); // Craft Mana Boots
> Config.Recipes.push([Recipe.Reroll.Magic, "Grand Charm"]); // Reroll magic Grand Charm (ilvl 91+)
> Config.MakeRunewords = true; // Set to true to enable runeword making/rerolling
> Config.Runewords.push([Runeword.Insight, "Thresher", Roll.Eth]); // Make Insight Thresher
> Config.KeepRunewords.push("[type] == polearm # [plusskillcriticalstrike] ==6 && [enhanceddamage] >= 260");
> ```
> 
> In stash , double checked using UserAddon:
> Grand charm = Item Level99
> Eth Thresher 4 free sockets
> 
> As a result the champ no longer picks any gems( Observed him passing by flawless sapphire & flawless amethyst).
> Paused and pick them up manually and the bot went on to sell them to the NPCs.
> 
> https://pastebin.com/0UTSzSZq - current champ config with which he doesn't pick up gems.

I think there needs to be a space between [plusskillcriticalstrike] == and 6.
