### ISSUE TITLE
Bots seem to be skipping over High Runes

### ISSUE THREAD

**Issue by outlawimmortal** [kolton/d2bot-with-kolbot#1861]
So ive come back to diablo to for the ladder reset. decide to bot.. at first everything seems to be running smoothly... with the exception of "too much recursion" and the console not logging the high runes even tho i have every char set to log everything.... eveything was working no probs... but for the last week my bots havent recorded or even picked up a single rune past Mal... Mal seems to be the highest rune they pick up... even checking the pickit there is nothing different about it... eveything looks the same, but no1 wants to pick up and keep the HRS

[name] >= istrune && [name] <= zodrune
seems to be something wrong with that script right there... 

so i decided to add
[name] == surrune
[name] == jahrune
[name] == berrune
[name] == gulrune
[name] == istrune
[name] == lorune
[name] == chamrune
[name] == zodrune

to see if anything changes... because in the past week i havent seen a single one of these runes, before, i was finding at least one of these a night when i let them run overnight....

not sure if this is a common issue or not... i hope you guys can fix this for me!

**Comment by outlawimmortal** [comment]
damn i would send you the whole file but you guys dont support notepad ++

**Comment by semirotta** [comment]
I have this:
[Name] == PulRune
[Name] == UmRune
[Name] == MalRune
[Name] >= IstRune && [Name] <= ZodRune

Works just fine, Ive picked up bers, jahs and all.

**Comment by outlawimmortal** [comment]
> I have this:
> [Name] == PulRune
> [Name] == UmRune
> [Name] == MalRune
> [Name] >= IstRune && [Name] <= ZodRune
> 
> Works just fine, Ive picked up bers, jahs and all.

do you think i need to capitalize the first letters of those words? it seems like mine is identical to yours except you have capital letters to start each word... if that makes sense...

i didnt have any problem before, its just been this last week since its been happening... i did about 100 runs overnight and not a single rune but a ral (for crafting) was picked up... that it is very unusual. 

not sure if i should just delete and reinstall the program... not sure if there is something wrong with the bots that i cant see and cant fix. because my pickit is basically the same. 

only other thing i have done since this started was putting the user addon to true in between games to stop the bots from running scripts so i could clear them.., but i doubt that would have messed anything up considering i didnt change any of the pickit settings, and they seem to be picking up everything else

either i have extremely horrible luck at finding any rune

**Comment by outlawimmortal** [comment]
well after making my changes by actually writing out all the names for the higher runes i found a Gul and a Lo in 16 runs.... not sure if my luck is turning around or the pickits i wrote in actually worked... maybe theres an issue with [name] >= istrune && [name] <= zodrune but i am not sure... closing issue soon, just wanted to let you guys know

**Comment by LoonaWolf** [comment]
I need a lil help, i have my bot programmed to pick up items and runes and i watched as it skipped over the runes i have it set to pick up. how do i fix this issue. ihave it set as:
[name] == FalRune # # [MaxQuantity] == 2
[name] == LemRune # # [MaxQuantity] == 2
[name] == PulRune # # [MaxQuantity] == 2
[name] == UmRune  # # [MaxQuantity] == 2
Ive tried tweaking it in every which way possible and it still continues to skip over everything as if it never dropped

**Comment by semirotta** [comment]
> 

Have you tried without the maximum quantity? why would you have maximum quantity added separatedly? Why not just allow the bot to pick up every single on of those. On top of that, why would you pick up Fal and Lem? They are very common drops. You'll just fill your stash with it.
