### ISSUE TITLE
Cubing Config Recipes

### ISSUE THREAD

**Issue by Kephren999** [kolton/d2bot-with-kolbot#1866]
I just want the bot to cube a phase blade and try for 5 sockates. Nothing seems to work, he isn't even picking up any ingredients for it.

Config.Recipes.push([Recipe.Socket.Weapon, "Phase Blade", Roll.NonEth]); 
Config.Recipes.push([Recipe.Socket.Weapon, "phaseblade", Roll.NonEth]); 

I have also tried 
Config.Recipes.push([Recipe.Socket.Weapon, "225", Roll.NonEth]); 

Ingredients for the following recipes will be auto-picked, for classids check libs/NTItemAlias.dbl
	/* Cubing config. All recipe names are available in Templates/Cubing.txt. For item names/classids check NTItemAlias.dbl

what could i be doing wrong?

thx

**Comment by mf022** [comment]
do you have a pickit line with non-eth phase blade (**/* Base item for the following recipes must be in pickit.)**?
[name] == phaseblade && [flag] != ethereal # [sockets] == 0 || [sockets] == 5 

be sure that you activated cubing
```
	Config.Cubing = true; // Set to true to enable cubing.
```

**Comment by Kephren999** [comment]
yup got that. gone over my char config soo many times, its easy to miss things.
i was looking at cubing.js and noticed this
case Recipe.Socket.Weapon:
this.recipes.push({Ingredients: [Config.Recipes[i][1], 617, 620, 561], Index: Recipe.Socket.Weapon, Ethereal: Config.Recipes[i][2]});

Is the cubing recipe set to only roll Ethereal?

**Comment by mf022** [comment]
> I should mention the bot in question already has a white sup phase blade

superior items cannot be socketed with runes, but only with Larzuk's quest a5q1, and that item will get the max number of sockets depending on it's item level (https://diablo2.diablowiki.net/Sockets#Sockets_by_Number).

**Comment by Kephren999** [comment]
Ohhh god , I forgot about that
No wonder nothing I did worked, tried so hard lol
Thx man
