### ISSUE TITLE
Window has unexpectedly exited... starting profile

### ISSUE THREAD

**Issue by Batutinhas** [kolton/d2bot-with-kolbot#187]
When i run the bot, a d2 windown close fast and give this error: Window has unexpectedly exited... starting profile
Sorry for english.

**Comment by mboufos** [comment]
check permissions and compatibility

**Comment by Batutinhas** [comment]
Im opening with adm, and compatibility is ok...

**Comment by mboufos** [comment]
all drivers are ok also???. net framework 3.5 -  4etc??

**Comment by Batutinhas** [comment]
Yeah, i think. If you have TeamViewer or whatever. Thanks for helping.

**Comment by dzik87** [comment]
Clean bot what is in this repository is not compatible with 1.14d Diablo II.
To use kolbot with it you need version hack what is available on bh forum where you can also get instructions and support for it.

**Comment by Batutinhas** [comment]
Thanks

**Comment by Batutinhas** [comment]
Im having a problem. When i put a versionhack in a d2 copy folder, im opening the bot. But when im join in bnet, the patch is downloading. Sry for english.

**Comment by dzik87** [comment]
There is no support for version hack here. Try ask on bh forum. But i would advice to read instructions carefully. and it will work ;)
