### ISSUE TITLE
Silencing MFHelper Script

### ISSUE THREAD

**Issue by Kephren999** [kolton/d2bot-with-kolbot#1870]
I have spent hours on this lol, mod, test, mod test
i have read and re-read [https://github.com/mf022/d2bs/wiki/Misc_options#silencing-the-scripts](url)

Is there anyway to silence the scripts but still have mfhelper pick up the commands?

i have tried everything. 
it would be nice if    print(   would work to give the commands in mfhelper, is there anyway to achieve this?

**Comment by mf022** [comment]
you should use local chat in mode 1 or 2. 
check the character config file.

**Comment by Kephren999** [comment]
omg you are awesome man thank you so much
i have 4 bots running mfhelper in private games then decided to try public out, but i hate the fact people could see the kill and clear commands
to test i had bot 1 and 2 on local chat mode 1 and bot 3 not using it, and no text showing up Perfect!

if you could answer one thing, is there anyway to allow the public to still see the Hot and Safe TP messages?

**Comment by Kephren999** [comment]
i tried this and it worked out 
line 196 baal.js      say(string,true);
freakin perfect man
there's really no way a bot can get flagged by blizz for simple chat is there?

**Comment by mf022** [comment]
> there's really no way a bot can get flagged by blizz for simple chat is there?

don't exaggerate with too many expressions, cause the server filter chat may catch the leader and your key will be muted temporarily on first step.

**Comment by Kephren999** [comment]
Aye , trying to avoid any situations like that, all I’m really keeping is
the tp messages and the say string on Baal runs that should be ok correct?
I mean I see bots with welcome messages and next game etc
