### ISSUE TITLE
Precast.js

### ISSUE THREAD

**Issue by Kephren999** [kolton/d2bot-with-kolbot#1874]
its just a tiny issue but i thought id ask anyway.
i would like to change how my Sin does her precasting.
Currently she does the following
precasts, then summons her shadow, then she precasts again then shes off

how would i change the order to summon shadow, then precast once.
im getting better at this coding but this file is abit too confusing .

**Comment by mf022** [comment]
the main function is **doPrecast** found on default lines 133-142

1. line 137 - precast BC+BO on CTA equipped chars
2. lines 310-338 assassin buffs
	- precastSkill(xxx, 0) - will check the best slot and will cast that skill on right hand
	- Skill.cast(xxx, 0) - will cast that skill on right hand
