### ISSUE TITLE
Make D2BotMap automatically enter account

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#1879]
Is it possible to make Diablo 2 application (opened via KolBot with D2BotMap as Entry Script) automatically enter account (if account and password are specified in profile) like others Entry Scripts (D2BotFollow, D2BotLeader)?

**Comment by DarkHorseDre** [comment]
It is as I've seen someone elses script do it.  I dont know how, but you'd have to get bot to enter info into those screens as it does with game name and password..

**Comment by mf022** [comment]
maybe you should use the D2BotLead.dbj starter script and add in the config file other map script - [Manual.js](https://github.com/blizzhackers/documentation/blob/master/kolbot/ManualPlay.md#manualjs)
