### ISSUE TITLE
d2bs core code for this release?

### ISSUE THREAD

**Issue by tamethecomplex** [kolton/d2bot-with-kolbot#188]
Does anyone know where the D2BS code used with this kolbot release is?  I have a version of the D2BS core, but it compiles to a much smaller DLL (906 kb vs ~1.7 MB), and crashes in many places where the D2BS.dll packaged with kolbot in this repo does succeed.  Any help finding the correct D2BS core code to use with Kolbot would be much appreciated.  Thanks!

**Comment by mboufos** [comment]
you have to found the version of hack for kolbot for 1.14 version :)

**Comment by tamethecomplex** [comment]
So for anyone wondering the same thing, the current version of the core (I believe) is on the "bob-18" branch on the Assembla site that hosts the D2BS project: https://bigfiles.assembla.com/spaces/d2bs/subversion/source/HEAD/branches/bob-18.  

I personally had great difficulty building the project, because I use visual studio 2015, and the v140 (2015) version of the C++ build tools will not build the project with the version of the spidermonkey libraries bundled with the current d2bs code (build tools v100, corresponding to Visual Studio 2010).  It seems the only way to obtain MS visual studio 2010 is to buy an MSDN subscription (very expensive), and the v100 C++ build tools bundled with the Windows 7 SDK I was not able to get to work with my VS 2015 / Windows 10 setup, try as I might.  I also tried to compile Spidermonkey v1.8 from the Mozilla source, but ran into issues there as well.  Finally, the latest version of Spidermonkey has many breaking changes from Spidermonkey 1.8, and the basic tutorials for the introduction to the current version of the Spidermonkey appear to be out-dated.  For example, the Hello World example for the JSAPI (here: https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/How_to_embed_the_JavaScript_engine) does not work with the current version of Spidermonkey.

I'm thinking of starting a new project to port the latest version of D2BS to a more modern javascript engine.  I'm going to create a new thread for this.
