### ISSUE TITLE
Bot not picking specific item

### ISSUE THREAD

**Issue by xiphias12** [kolton/d2bot-with-kolbot#1889]
I want to keep bases to use larzuk quest to get 4s swords for spirit. Got these pickit lines:

//Spirit sword
[Name] == CrystalSword && ([Quality] == Normal || [Quality] == Superior) # [Sockets] == 4 # # [MaxQuantity] == 1
[Name] == CrystalSword && ([Quality] == Normal || [Quality] == Superior) # ([Sockets] == 4 || [Sockets] == 0) && ([Level] >= 26 && [Level] <= 40) # [MaxQuantity] == 1
[Name] == BroadSword && ([Quality] == Normal || [Quality] == Superior) # ([Sockets] == 4 || [Sockets] == 0) && [Level] >= 26 # [MaxQuantity] == 1

Tried to get the right item level by using [level] but I have seen several swords dropping with the right item level, but bot still doesnt pick up. They have all been 0s.

I don't get any errors from the lines. What's wrong?

**Comment by mf022** [comment]
sockets 4 condition doesn't need level condition, or you can just re-write 1st line
```
([name] == crystalsword || [name] == broadsword) && [quality] <= superior # [sockets] == 4 # # [maxquantity] == 1
```

the other 2 lines can be
```
[name] == crystalsword && [quality] <= superior # [sockets] == 0 && ([level] >= 26 && [level] <= 40) # # [maxquantity] == 1
[name] == broadsword && [quality] <= superior # [sockets] == 0 && [level] >= 26 # # [maxquantity] == 1
```



> but I have seen several swords dropping with the right item level, but bot still doesnt pick up. They have all been 0s.

they were crystal or broad swords at least normal quality?

**Comment by xiphias12** [comment]
> sockets 4 condition doesn't need level condition, or you can just re-write 1st line
> 
> ```
> ([name] == crystalsword || [name] == broadsword) && [quality] <= superior # [sockets] == 4 # # [maxquantity] == 1
> ```
> 
> the other 2 lines can be
> 
> ```
> [name] == crystalsword && [quality] <= superior # [sockets] == 0 && ([level] >= 26 && [level] <= 40) # # [maxquantity] == 1
> [name] == broadsword && [quality] <= superior # [sockets] == 0 && [level] >= 26 # # [maxquantity] == 1
> ```
> 
> > but I have seen several swords dropping with the right item level, but bot still doesnt pick up. They have all been 0s.
> 
> they were crystal or broad swords at least normal quality?

Yes I saw a few 0s broad swords in cow level, non-superior.

**Comment by xiphias12** [comment]
Would it be any difference if I added level at the same side as quality and not same side as sockets?

[Name] == CrystalSword && ([Quality] == Normal || [Quality] == Superior) &&  ([Level] >= 26 && [Level] <= 40) # ([Sockets] == 4 || [Sockets] == 0) # [MaxQuantity] == 1

**Comment by mf022** [comment]
check https://github.com/blizzhackers/pickits/blob/master/NipGuide.md/#format-of-the-nip-lines

**Comment by xiphias12** [comment]
> [level] should be after #
> check https://github.com/blizzhackers/pickits/blob/master/NipGuide.md/#format-of-the-nip-lines

According to that it says its before?

**Comment by mf022** [comment]
> According to that it says its before?

yes, sorry I was wrong in previous answer
```
[level] should be after #
```

it's obvious that is before, like in the guide I had mentioned

**Comment by xiphias12** [comment]
Works when moved level to before #
