### ISSUE TITLE
chicken town wp chicken

### ISSUE THREAD

**Issue by ssassassassa** [kolton/d2bot-with-kolbot#1894]
bot is endless doing the same
after chicken in chaos sanctuary
he open  new game
going to river of flame without healing in town which result in chicken again

in all other acts bot is going to heal first when he is in town
but in act 4 bot always want to go river of flame first
even if the bot is max life but missing some potions he first go river of flame wp and then tp back town for potions

**Comment by CinderLordTurtle** [comment]
What script are you doing there?
Try to add
`Town.doChores();`
somewhere you think it may fit (after initialization).

**Comment by ssassassassa** [comment]
Town.doChores();
that was exactly what was missing in the diablo script
thanks that helped alot :)
