### ISSUE TITLE
Drop items in field instead of going to an npc

### ISSUE THREAD

**Issue by hooonigan1** [kolton/d2bot-with-kolbot#1905]
Is there a way to get my char to drop items while mfing instead of going to an npc after getting a full inventory?
During chaos runs, I want my char to pick up items and drop them if they don't satisfy the pickit list instead of picking up unid items, filling my inventory every 10 seconds and going to NPC to unid and sell.
I know there is 
Config.FieldID = true; // Identify items in the field instead of going to town.
But it doesn't work like the description says.
It still fills my inventory with unid items and goes to NPC to id them.
Any help will be appreciated, thanks!

**Comment by mf022** [comment]
> I know there is
> Config.FieldID = true; // Identify items in the field instead of going to town.
> But it doesn't work like the description says.


Does your toon has a ID tome?

**Comment by hooonigan1** [comment]
No it didn’t, got it working now though thx
