### ISSUE TITLE
WhisperMsg Event ?

### ISSUE THREAD

**Issue by CinderLordTurtle** [kolton/d2bot-with-kolbot#1907]
Does anyone know how to get the whisper messages one gets?

I've read the D2BS Api but there were no informations about the arguments or how to retrieve such informations. I tried to find a way by looking at other scripts but without success so far: 
```
addEventListener("WhisperMsg",
		function (msg) {say(msg);}
);
```

I simply want to store whispers so far.

Any help is appreciated since I seem to miss something about the events.

**Comment by mf022** [comment]
Have you checked the History.txt?
```
Version 1.3 -
...
	.	"chatmsg" and "whispermsg" now listen to channel events as well as in-game events.
```

searching in d2bot files -> https://github.com/noah-/d2bs/blob/master/doc/globalFuncs.h#L962

maybe, you could get some suggestions looking at the d2nt file https://github.com/mf022/D2NT-1.13c/blob/master/D2NT/scripts/NTBot/tools/ChatR.ntj#L116 (note that there whisper msg is case 2 according to the color of text)

**Comment by CinderLordTurtle** [comment]
Truly helpfull, thanks! I should be fine with the ChatR.ntj
