### ISSUE TITLE
Kolbot how do i get the druid to precast grizzly and oaksage before barb bo at  cata lv 2

### ISSUE THREAD

**Issue by ayteex** [kolton/d2bot-with-kolbot#1912]
Kolbot how do i get the druid to precast grizzly and oak sage before the barbarian  battle order script at  cata lv 2.. i want the bear and sage with bo on before they leave...

**Comment by hdikiglb** [comment]
you should be able to put the precast code on the top or before the waypoint pather do achieve this

**Comment by WiZzMaN47** [comment]
Try putting a delay in the battleorders.js for the giver

**Comment by Bchilled** [comment]
I know this was closed, but can you give an example of the code to make this work. iv tryed and doesnt seem to work

**Comment by hdikiglb** [comment]
> 
> 
> I know this was closed, but can you give an example of the code to make this work. iv tryed and doesnt seem to work

iirc you need to alter the script of the first area/boss you're doing
