### ISSUE TITLE
Three parter: Mulelogging, Battle Orders and Antidotes

### ISSUE THREAD

**Issue by Jestah66** [kolton/d2bot-with-kolbot#1913]
Hello all,

I've dug and looked for a while but am coming up short on these.   

When logging mules it skips characters that I assume have been logged recently.  What can I delete/clear to force a full inventory (logging) or to prevent skipping of characters when perming?

I have a smiter that farms organs and grabs torches.  The only time he ever dies is when his BO apparently wears off - indicated by tons less life in the logged death message.  [0 of 1550] When it should say [0 of 2600] (arbitrary numbers).  Is there a function that I can set in a script to monitor the loss of BO and either chicken or go somewhere to buff?  

I would like to add a command to force a character to gulp down a few antidotes (since they stack time-wise) before starting specific runs - primarily the Matron's Den.  I've looked at different parts of the code to see if antidote use is something I could figure out how to add in.  Unfortunately I was unable to figure it out.

Any guidance would be greatly appreciated.

Thanks all

**Comment by mf022** [comment]
> When logging mules it skips characters that I assume have been logged recently. What can I delete/clear to force a full inventory (logging) or to prevent skipping of characters when perming?

this won't happen if you won't exit manually before the perm time (2h) is passed.
the last character is written in .../logs/MuleLog.json due to some lines in D2BotMuleLog.dbj
deleting that file will add the MuleLogger list from the beginning, but you are able to stop that profile, edit the MuleLogger accounts/chars then to start again.



>  Is there a function that I can set in a script to monitor the loss of BO and either chicken or go somewhere to buff?

this is already supposed to be in the default lines 136-137 of Precast.js 
```javascript
		// Force BO 30 seconds before it expires
		this.precastCTA(!me.getState(32) || force || (getTickCount() - this.BOTick >= this.BODuration - 30000));
```

**Comment by Jestah66** [comment]
Thanks for the answers.  I thought something was in there..... when in the moo moo farm, he BO's all the time.   I'm thinking that he loses his BO while engulfed by baddies sometimes in Uber Tristram - he can't toss a portal when I know he normally would......because he's in Tristram.

Thanks again
