### ISSUE TITLE
pickit problems with multiple names in the same line

### ISSUE THREAD

**Issue by sgaspa** [kolton/d2bot-with-kolbot#1917]
I just came back and updated with the latest kol release I got this issue:

every lines in .nip files that are comparing more names in the same line are going to generate a pickit error.

for example
([name] == voulge || [name] == bill) && [quality] == normal # # [maxquantity] == 1
is not working anymore.

it works instead if I do that in 2 different lines, like this:
[name] == voulge && [quality] == normal # # [maxquantity] == 1
[name] == bill  && [quality] == normal # # [maxquantity] == 1

has something changed on the new kol releases, is there any way to fix that?

thanks in advance

**Comment by mf022** [comment]
> ([name] == voulge || [name] == bill) && [quality] == normal # # [maxquantity] == 1

that should work. How you downloaded d2bot-with-kolbot?
zip or [with tortoiseSVN](https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md#download-with-tortoisesvn)
try to use SVNUpdate

**Comment by sgaspa** [comment]
well, I used the SVN checkout and I've already updated, is up to date , 100% sure.

This is the exact error message shown in the game manager log about a line:

Pickit error! Line # 104 Entry: ([name] == ring || name == amulet) && [quality] == rare # [fcr] >= 10  (MW.nip) Error message: name is not defined Trigger item: Bolts

The line seems correct to me, I used the same .nip file in previous release and it worked well.

These errors are coming from the follower script btw, somehow it bugs with certain items name, I don't understand honestly

**Comment by sgaspa** [comment]
follower chars are picking correctly after the error, but that line is out I guess

**Comment by 5noop** [comment]
`([name] == ring || [name] == amulet) && [quality] == rare # [fcr] >= 10`

fixed

**Comment by sgaspa** [comment]
OMG... really? I really didn't see that? wow, I've been watching those lines forever lol and I didn't see the [] missing.. well, thanks <3
