### ISSUE TITLE
Need help with mf areas

### ISSUE THREAD

**Issue by fenixsaurus** [kolton/d2bot-with-kolbot#1920]
i set bot to mf ancient tunnels or any other area and goes in makes tp and leaves ive tried eveything i can think of any ideas

**Comment by 5noop** [comment]
Any error message ? Looks like a bad attack config.

Copy your config file on pastebin.com and post the link here, I'll take a look.

**Comment by fenixsaurus** [comment]
no i did remove the run because wasnt doing it but goes in place makes tp leave goes next order which is meph

**Comment by 5noop** [comment]
`Config.AttackSkill[4] = 59;`

change this to an untimed skill

**Comment by fenixsaurus** [comment]
ok but i dont think thats problem because she does meph fine

**Comment by fenixsaurus** [comment]
Thank you buddy it worked
