### ISSUE TITLE
Follower script doesn't pick up nip files correctly

### ISSUE THREAD

**Issue by sgaspa** [kolton/d2bot-with-kolbot#1923]
Well, my Kol is updated to the latest revision.

I'm experiencing several missing pickups from the follower script. It doesn't happen with other scripts, so I assume the problem is on the follower. 

Basically, it does not pick up after a mob is killed, I have to continue manually send the command "p" to make them pick up.  The "auto" pick up works rarely I can say.

I don't understand if the follower is using the same AI that the Leader script uses, but is there any way to make them pick up ALWAYS after every fight like the other scripts?

Thanks in advance for any help!

**Comment by 5noop** [comment]
This is the default behavior.

You can change it by editing Follower.js, replace line 679 `Attack.clear(20, false, false, false, false);` by `Attack.clear(20, false, false, false, true);`

**Comment by sgaspa** [comment]
wow thanks, that's so interesting.I'm looking now for the Attack.clear() function declaration, there's a place in the code where I can find it, no results from a text search. Thanks btw <3

**Comment by 5noop** [comment]
Attack.clear() is in Attack.js

**Comment by sgaspa** [comment]
Thanks, man, I found it. really appreciated the support :)
