### ISSUE TITLE
d2BotPubJoin - problem

### ISSUE THREAD

**Issue by szeju** [kolton/d2bot-with-kolbot#1949]
I have a problem with “d2BotPubJoin”
I configured the names of the games “diabaal”, “baal” “dia”, the bot joins and … does not use tp leader, he chooses the diablo seal himself and dies.when I get into the game and players are already in act 5 bot spends a long time before he understands that he is dead.when gameentertainment applies only “baal”, the bot doesn’t know that and and does alone “diaball” - and dead …

**Comment by EdgarK3** [comment]
make sure you setting baal helper and diablo helper up and make sure you dont have either of those set to true in the upper portion of the boss scripts section... hope this helps

**Comment by szeju** [comment]
I would like him to wait for the leader's teleport.I would like to disable movement character.because when the leader open the teleport bot ignores this, and goes there alone.When it's in diablo place, bot ignores monsters and runs between them to run diablo seal.
