### ISSUE TITLE
Help with Kolbot!

### ISSUE THREAD

**Issue by JakeZ1** [kolton/d2bot-with-kolbot#195]
Hello, I am completely new to kolbot and would like to start using it. I have used Etal in the past. I would like to know if there are any tutorials on how to setup kolbot and the version hack to work on the newest version of diablo 2. I have tried to install this myself but I just keep getting crashes so if anyone could help that would be great.

**Comment by mboufos** [comment]
https://github.com/DetectiveSquirrel/Version-Hack-Guide-1.14d/blob/master/README.md

:)

**Comment by JakeZ1** [comment]
Hello, thanks for the reply. I have saw this but dont know where to get old d2 because d2mule didnt work for me

**Comment by mboufos** [comment]
pirate bay ?? :P or any other torrent site :) you can find it easy :D

**Comment by JakeZ1** [comment]
I downloaded PowerISO from d2mule. So all I need to get is the torrent and mount it and it will install? I am looking for the 1.13d correct? Then I replace the files with the ones in the 114d folder I download here. Then replace the dll and it should work?

**Comment by mboufos** [comment]
you need
1)iso program to read the iso files 
2)game files in .iso or cds ( if you have cds you dont need the iso program
3)install the game
4)update it to 1.13d
5)copy paste the files
6)enjoy kolbot :)

thats all

**Comment by JakeZ1** [comment]
PowerISO is the program to mount/read the iso files. So I need to go get the game files now. Thanks ill come back with a update at some point within the next 2 hours or so.

**Comment by JakeZ1** [comment]
Cant even get this thing to work...

**Comment by mboufos** [comment]
heheh its not that hard hehe check youtube there is a link about how you can do it :P

**Comment by JakeZ1** [comment]
I got it to work but I have a question. With automule are you able to have the accounts be like example-1 example-2 rather then prefix-aiuouhqhhansldn ect?

**Comment by mboufos** [comment]
you just right the   example-  and mulebot will start making the  example-1.-2-.3 etc

**Comment by JakeZ1** [comment]
Thanks :)
