### ISSUE TITLE
AutoSmurf - Can't Get It Work

### ISSUE THREAD

**Issue by AbbyRoad** [kolton/d2bot-with-kolbot#1957]
I have Kolbot working, but when I added the various AutoSmurf files from GitHub, it no longer works.  The four bots (Leader & 3 followers) stay in town.

The two errors I get are: 
Error (205) File (kolbot\default.dbj:16) TypeError: malformed UTF-8 character sequence at offset 638
Error (1) File Kolbot\default.dbj:104) ReferenceError: Config is not defined.

In the default.dbj file - 
Line 16 is     include("common/Config.js") ;
Line 104 is   Config.init(true) ;

As stated above, the AutoSmurf config file (and the other file mods) I am using was copied from GitHub, and it config file a js file.  

I tried (1) cut & pasting the AutoSmurf code into the existing config file and (2) replacing the existing config file with the version in the AutoSmurf folder, but both yielded the two same errors.

Any assistance would be appreciated.

**Comment by mf022** [comment]
you should check the Encoding of the files in notepad++. Maybe Autosmurf files should be **converted to UTF-8** encoding.

btw, did you follow the Guide.txt and README_en.md from https://github.com/blizzhackers/documentation/blob/master/kolbot/MiscellaneousOptions.md#updated-autosmurf ?

**Comment by AbbyRoad** [comment]
mf022

Thanks for the advice.  For some reason the config file, once copied over, changed from UTF-8 encoding.  I converted it back, and that took care of the two errors.  

Now I have two strict warnings and one new error.  I'll see if they have cropped up with others prior to posting. 

Again, thanks!

Regards;

AbbyRoad
