### ISSUE TITLE
Pickit

### ISSUE THREAD

**Issue by JakeZ1** [kolton/d2bot-with-kolbot#196]
Anyone have a pickit they would be willing to share? It seems my bot isnt picking up anything and I think its because I do not have a great pickit. Thank you,

**Comment by mboufos** [comment]
the kolton pickit picks the perfect items you have to change it :) 
i work with those 
http://www.projectetal.com/forums/wiki/?title=Pickit_Files

:P

**Comment by JakeZ1** [comment]
Yea, thats why I asked if someone had one to share. I have found this link before and know how to edit the pickits I just would like to use someones.
