### ISSUE TITLE
data folder and the red exclamation mark.

### ISSUE THREAD

**Issue by pythagoras694** [kolton/d2bot-with-kolbot#1961]
Hey guys, thanks to anyone who responds. Im curious as to what the green check mark/red on the files themselves mean. Such as cdkeys.json or profile.json. Ive deleted the data in cdkeys, saved, and the file reverted to a green check mark, but im not entirely sure if this is what i am supposed to do. The profile still worked, signing on and completing its run. If anyone more knowledgeable could chime in, itd be greatly appreciated!

**Comment by mf022** [comment]
you should ignore the tortoiseSVN marks that you will see in Windows Explorer.
some files should be changed to add your data, like is cdkeys.json or profile.json, and at least d2bs.ini
The colored marks show that are differences between your files and the default ones exiting on the github repository.

TortoiseSVN updates will keep your changes added to the files/scripts.

**Comment by pythagoras694** [comment]
> you should ignore the tortoiseSVN marks that you will see in Windows Explorer.
> some files should be changed to add your data, like is cdkeys.json or profile.json, and at least d2bs.ini
> The colored marks show that are differences between your files and the default ones exiting on the github repository. You can see the differences choosing **SVN Diff** on R-click option (maybe you should check it first in the TortoiseSVN > Settings > Context Menu)
> 
> TortoiseSVN updates will keep your changes added to the files/scripts. So you can run your modded scripts and to update them according the the github repository updates.

Thank you my good sir! I wasnt sure if it meant that there were corrupted files or not. Another question if you do not mind, when i use my own pickets, the items picked up dont register on the kolbot loader. Is there a way to make it do so?

**Comment by pythagoras694** [comment]
> > Another question if you do not mind, when i use my own pickets, the items picked up dont register on the kolbot loader. Is there a way to make it do so?
> 
> Manual or bot playing?
> 
> In case of botting, if you see the items picked on white console and you don't see them on manager, check this section from char config. **// Manager Item Log Screen**
> https://github.com/blizzhackers/documentation/blob/master/kolbot/CharacterConfig.md/#manager-item-log-screen

Ty man! Greatly appreciated!
