### ISSUE TITLE
level 1 imbue script

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#1965]
i had this like 3yrs ago lost the pastebin link

anyone got this hiding in old file

**Comment by 5noop** [comment]
pretty sure it has been patched

**Comment by gtoilet** [comment]
if you still got the script i would like to try it

**Comment by Legless** [comment]
It was called GiveMalus.js, and posted on bh, but I lost that link too.

**Comment by gtoilet** [comment]
i think i found it on pastebin but cant find it anywhere

**Comment by kacper8812** [comment]
https://pastebin.com/WtaxdCJK
found it in my old files
