### ISSUE TITLE
Leecher not receiving channel messages

### ISSUE THREAD

**Issue by Erfell** [kolton/d2bot-with-kolbot#1967]
Hello, I was running some runs with leader + leecher, and everything was working. Suddenly, then, my leecher (set with D2BotChannel profile) stopped receiving messages from the leader in my private channel.
Attached the image where you can see both the leader view (with messages) and leecher view (without leader message
![image](https://user-images.githubusercontent.com/57200327/67905813-f4001380-fb72-11e9-9787-b1c69bc160d9.png)

Any help?
Thanks in advance :)

**Comment by legitzombie** [comment]
You probably got muted, it happened to me as well but don't worry, it's temporary.
By default, Kolbot spits out the same text over and over which is detectable.
I recommend randomizing all your messages. Good luck.

The most basic example.
```
var random = Math.floor(Math.random() * 3); // Random number between 0 and 2 for the array
var messages = ["Join my channel at ","Find my channel at ","Navigate to my channel at "]; // array with 3 variations
var message = messages[random]; // Picks a random message between the 3
say(message); // Announce message in-game
```

**Comment by Erfell** [comment]
Indeed, it started working again. Thanks a lot, I will try to add these lines!
