### ISSUE TITLE
Rushee bot not joining TP2 but making act changes

### ISSUE THREAD

**Issue by Erfell** [kolton/d2bot-with-kolbot#1972]
Hello, I'm making some rushes and everything apparently works fine:
Leader creates the game
Leecher joining the game
Leecher recognizes leader
They party together
Act change is working

BUT

The rushee is not recognizing messages "1" and "2" to join in and out from TP.

I tried to look inside the rushee script but I can't find anything related to "1" and "2" messages....

**Comment by legitzombie** [comment]
What you're looking for is in the rushee.js file at line 358, 392, 605. 

You should only edit files with notepad++ to avoid breaking the code. 

If all fails, keep your kolbot folder updated with tortoisesvn and redownload the original file(s).

**Comment by Erfell** [comment]
I didn't set correctly the "Quester" in the char config file. Thank you legitzombie, I could find it out thanks to you :)
