### ISSUE TITLE
Leecher/ Follow

### ISSUE THREAD

**Issue by anime143** [kolton/d2bot-with-kolbot#1983]
My leecher is leading instead of my leader. Other words, this leecher is acting as if hes the leader and going off on his own. This is a Hdin character.

I want him to follow and wait until leader get there first or follow close behind like a merch.
Could you help with this?

**Comment by mf022** [comment]
check your char configs
follow https://github.com/blizzhackers/documentation/blob/master/kolbot/MultiBotting.md
