### ISSUE TITLE
is there a way to make tcp/ip follower work in 13d branch?

### ISSUE THREAD

**Issue by a1077w** [kolton/d2bot-with-kolbot#1984]
I want to play d2 with plugy mod, but it only works with 13d and below, and the d2bot version that has tcp/ip option only comes with the client that doesn't support that version of the game.

Is there something i can do to modify the 13d client to make it work?

I don't even need the follower to automatically enter the game of the leader. It would be fine if i could just somehow enter the game manually with that character and then turn on the follower script. Is something like that possible?

**Comment by mf022** [comment]
Did you try to change the starter scripts?
check https://github.com/blizzhackers/documentation/blob/master/kolbot/TCP-IP%20games.md

**Comment by a1077w** [comment]
thank you so much, that worked perfectly
