### ISSUE TITLE
Fail To Join - Major Issues Over Last Two Days

### ISSUE THREAD

**Issue by AbbyRoad** [kolton/d2bot-with-kolbot#1997]
I've been running  4 bot set-up for the last month or so on the East Softcore Ladder, with no major issues while using the default settings (all join and leave at the same time, minimal FTJs and RDs).  Just after the announcement of the ladder reset, I have had numerous FTJs. After anywhere from 1 to 4 successful runs, one or more of the follower bots will get a FTJ.  

Putting in a custom time delay for each bot joining the game has not helped.

My attempt at putting in a delayed exit timing in the Follower.js file seems to be over-ridden by the QuitList command,  (i.e. when the first leaves, they all automatically leave.)

Have others had this FTJ issue recently?  Is there a better way to stagger the exits at the end of the run?

**Comment by AbbyRoad** [comment]
As an update, running only 3 bots resulted in no FTJs, but number of prior FTJs (short games) has resulted in a multi-day RD.  Live and Learn.

I found Mercoory's QuitListDelay code and will give it a try in a few days.

Still curious to hear if anyone else has seen an uptick in FTJs in the last few days.

**Comment by mf022** [comment]
> I found Mercoory's QuitListDelay code
an earlier version can be found on https://github.com/blizzhackers/documentation/blob/master/kolbot/MultiBotting.md#followers-exit-delays

**Comment by alanchais2** [comment]
yea I've been getting FTJ these past few days with any configuration. Is there a fix?

**Comment by AbbyRoad** [comment]
Hi Alan

I know the staggered entry of the followers did not mitigate the issue.  After my RD penalty passes (another day to go), I'll be trying with Mercoory's QuitListDelay code with 4 bots running.  Will post how it works.

As I noted above, FTJs only occurred for me when running 4 bots (3 followers).  No issues with 3 bots (2 followers).

**Comment by YayEC** [comment]
I can confirm numerous FTJ last days, obviously something is implemented or blizz servers issue, no idea.
Swapping cdkeys and game folders not help. Renew IP and change D2 accounts with different chars also.
3 bot chars seems to be running fine unless fourth from same IP log in realm. No matter bot or char playing manually and join same or different game.
Anyone else got similar?

**Comment by AbbyRoad** [comment]
I've been running 4 bots in the same games for the last 5 hours.  Each run is about 7.5 minutes.  So far no FTJs.  Tho changes I made were - using a staggered game join and a staggered game exit for the followers.  I believe that the staggered game  exit is the one preventing the FTJs.

I used Mercoory's QuitListDelay code, that mf022 supplies a link to in his response above.  It seems to successfully address the FTJ issue.

**Comment by AbbyRoad** [comment]
Well, I spoke too soon.  Just after I closed the issue, the FTJs started again.  The staggered exits seemed to help.  I guess I'll need to play around with the length of the stagger between each exiting char.

**Comment by AbbyRoad** [comment]
As I use a Bo/Stun barb, in the BattleOrders Bot file I changed the timeout from 60 sec to 360 sec in both the giver and receiver sections.  This prevents the FTJ events from causing multiple < 2 min games.  For the staggered exits I currently use 0-1, 3-5, 7-9 and 11-13 seconds for the four bots.

The stagger times have dramatically reduced the FTJ events, and the BattleOrders timeout change has prevented the creation of an excessively high number of extremely short games.  Instead the FTJs will result in  ~7 min games, if the bot is unsuccessful in joining, and 10+ min if it does eventually join.

**Comment by spagghet** [comment]
Just wanted to chime in and say I haven't had a ftj on my followers since adding the exit delays as suggested. So thanks for the input.

My leader however still has periodic ftj's. I increased the wait time after a ftj to 900 (15 mins) seconds so it wouldn't keep attempting to create games.
