### ISSUE TITLE
Can't load custom script

### ISSUE THREAD

**Issue by PickAUsernamez** [kolton/d2bot-with-kolbot#2006]
I'm trying to load a custom script I made some time ago, but it doesn't recognize it.

It gives me an error on line 33 of char config file:

// Sorceress config file

/* Brief instructions:
 * Notepad++ is HIGHLY recommended to use for editing these files. Visit http://notepad-plus-plus.org/
 * To comment out something, put // in front of that line
 * !!!Never comment out something you're not sure about, set it to false or disable as noted in description if you don't want to use it.
 * true and false are case sensitive. Good: Config.SomeVar = true; Bad: Config.SomeVar = True;
 */

function LoadConfig() {
	/* Sequence config
	 * Set to true if you want to run it, set to false if not.
	 * If you want to change the order of the scripts, just change the order of their lines by using cut and paste.
	 */
	 
	// User addon script. Read the description in libs/bots/UserAddon.js
	Scripts.UserAddon = false; // !!!YOU MUST SET THIS TO FALSE IF YOU WANT TO RUN BOSS/AREA SCRIPTS!!!

	// Battle orders script - Use this for 2+ characters (for example BO barb + sorc)
	Scripts.BattleOrders = false;
		Config.BattleOrders.Mode = 0; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = []; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.

	// Team MF system
	Config.MFLeader = true; // Set to true if you have one or more MFHelpers. Opens TP and gives commands when doing normal MF runs.

	// Boss/area scripts

	// *** act 1 ***
	
	Scripts.ActOneWalker = false;
	        Config.ActOneWalker.Den = false;  <---- line 33
		Config.ActOneWalker.ColdStony = false; 
		Config.ActOneWalker.Up = false; 
		Config.ActOneWalker.DarkMarsh = false;
		Config.ActOneWalker.TamoeInner = false; 
		Config.ActOneWalker.Barracks = false; 
		Config.ActOneWalker.Jail = false; 
		Config.ActOneWalker.CataWP = false;
		Config.ActOneWalker.Andy = false;

Error in sorceress.teler.js(line 33): Config.ActOneWalker is undefined

It's got to be a simple error, but I'm not seeing it. Script is in bots folder. Named correctly.

**Comment by AbbyRoad** [comment]
Can you post the ActOneWalker bot code? 

I suspect there is a typo or missing code in the bot file.  Specifically do you have a line similar to:

if(Config.ActOneWalker.Den) {
    Attack.clearLevel();
}

**Comment by 5noop** [comment]
You need to define all your parameters (Den, ColdStony, etc) in Config.js

**Comment by PickAUsernamez** [comment]
It's very amateurish for sure.

/**
* @filename ActOneWalker.js
* @author  
* @desc  Walks through Act1
moveTo x, y, retry, clearPath, pop
moveToPreset: function (area, unitType, unitId, offX, offY, clearPath, pop)
*/

function ActOneWalker() {
	
if (Config.ActOneWalker.Den) {
    Town.doChores();
	Town.goToTown(1);
	Pather.moveToExit([2, 8, ], true)
	delay(500);
	Pather.makePortal();
	say("1");
	delay(1000);
	say("1");
	delay(1000);
	say("move")
	Attack.clearLevel();
	delay(1000);
	Town.goToTown();
	Town.move("akara");
	
	akara = getUnit(1, "akara");

	akara.openMenu();
	me.cancel();
	say("2");
	delay(2000);
	say("2");
	delay(1000);
	say("talk akara");
	delay(10000);
	say("move");
	Pather.getWP(3);
	Pather.makePortal();
    say("1");
	delay(1000);
	say("1");
    delay(2000);
	say("wp");
	delay(4000);
	say("2");
	delay(2000);
	say("2");
	Town.goToTown();
    };
if (Config.ActOneWalker.Cold) {
    delay(10000);
	say("3");
    delay(12000);
	Town.doChores();
	Pather.useWaypoint(3);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	delay(3000);
	say("move");
    Pather.moveToPreset(3, 1, 734, 0, 0, Config.ClearType, true)
	Attack.clear(25, 0, getLocaleString(2869)); // Bishibosh
	delay(4000);
	Pather.makePortal();
	say("2");
	delay(2000);
	say("2");
	Pather.getWP(4);
	Pather.makePortal();
    say("1");
	delay(1000);
	say("1");
    delay(4000);
	say("wp");
	delay(4000);
	say("2");
	delay(2000);
	say("2");
	Town.goToTown();
	};
if (Config.ActOneWalker.Stony) {
    delay(10000);
	say("3");
    delay(12000);
	Town.doChores();
	Pather.useWaypoint(4);
	delay(1000);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	delay(1000);
	say("wp");
	delay(3000);
	say("move");
    Pather.moveToPreset(4, 1, 737, 0, 0, Config.ClearType, true)
	Attack.clear(25, 0, getLocaleString(2872)); // Rakanishu
	delay(4000);
	Pather.moveToExit([4, 10, ], false, Config.ClearType);
	Pather.makePortal();
	say("2");
	delay(2000);
	say("2");
	delay(1000);
	Town.goToTown();
	};
if (Config.ActOneWalker.Up) {
    delay(10000);
	say("3");
    delay(12000);
	Town.doChores();
    Pather.useWaypoint(4);
	Pather.moveToExit([4, 10, ], true)
	delay(500);
	Pather.makePortal();
	say("1");
	delay(1000);
	say("1");
	delay(2000);
	say("move");
    Pather.moveToExit([10, 5, ], false, Config.ClearType);
	delay(5000);
    Pather.moveToExit([10, 5, ], true, Config.ClearType);
	delay(1000);
	Pather.moveToPreset(5, 0, 0, 0, 0, Config.ClearType);
	delay(4000);
	Pather.getWP(5);
	delay(4000);
	Pather.makePortal();
	say("2");
	delay(2000);
	say("2");
	Town.goToTown();
    }
if (Config.ActOneWalker.DarkMarsh) {
    delay(10000);
	say("3");
    delay(12000);
	Town.doChores();
	Pather.useWaypoint(5);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	delay(1000);
	say("wp");
	delay(3000);
	say("move");
	Pather.moveToPreset(6, 0, 0, 0, 0, Config.ClearType);
	delay(4000);
	Pather.getWP(6, Config.ClearType);
	delay(4000);
	Pather.makePortal();
	say("2");
	delay(1000);
	say("2");
	Town.goToTown();
	}
if (Config.ActOneWalker.TamoeInner) {
    delay(10000);
	say("3");
    delay(12000);
	Town.doChores();
    Pather.useWaypoint(6);
	revealLevel(true);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	delay(1000);
	say("move");
	Pather.moveToPreset(7, 0, 0, 0, 0, Config.ClearType);
	delay(4000);
	revealLevel(true);
	Pather.moveToPreset(27, 0, 0, 0, 0, Config.ClearType);
	delay(4000);
	revealLevel(true);
	Pather.useWaypoint(27);
	Pather.makePortal();
	say("2");
	delay(2000);
	say("2");
	Town.goToTown();
    }
if (Config.ActOneWalker.Barracks) {
    delay(10000);
	say("3");
    delay(10000);
	Town.doChores();
	Pather.useWaypoint(27);
	revealLevel(true);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	delay(1000);
	say("wp");
	delay(3000);
	say("move");
	Pather.moveToPreset(28, 0, 0, 0, 0, Config.ClearType);
	delay(4000);
	revealLevel(true);
	Pather.moveToExit(29, true, Config.ClearType);
	delay(4000);
	revealLevel(true);
	say("move");
	Pather.useWaypoint(29);
	delay(1000);
	Pather.makePortal();
	say("2");
	delay(2000);
	say("2");
	Town.goToTown();
    }
if (Config.ActOneWalker.Jail) {
    delay(10000);
	say("3");
    delay(10000);
	Town.doChores();
	Pather.useWaypoint(29);
	revealLevel(true);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	delay(1000);
	say("wp");
	delay(3000);
	say("move");
	Pather.moveToExit(30, true, Config.ClearType);
	delay(4000);
	revealLevel(true);
	say("move");
	Pather.moveToExit(31, true, Config.ClearType);
	delay(4000);
	revealLevel(true);
	say("move");
	Pather.moveToExit(32, true, Config.ClearType);
	delay(4000);
	revealLevel(true);
	say("move");
	Pather.useWaypoint(32);
	say("wp");
	delay(3000);
	say("move");
	Pather.makePortal();
	say("2");
	delay(2000);
	say("2");
	Town.goToTown();
    }
if (Config.ActOneWalker.CataWP) {
    delay(10000);
	say("3");
    delay(10000);
	Town.doChores();
	Pather.useWaypoint(32);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	Pather.moveToPreset(33, 0, 0, 0, 0, Config.ClearType);
	Pather.moveToExit(34, true, Config.ClearType);
	Pather.moveToExit(35, true, Config.ClearType);
	Pather.useWaypoint(35);
	say("wp");
	delay(2000);
	Pather.makePortal();
	say("2");
	delay(2000);
	say("2");
	Town.goToTown();
    }
if (Config.ActOneWalker.Andy) {
	Town.doChores();
	Pather.useWaypoint(35);
	Pather.makePortal();
	say("1");
	delay(2000);
	say("1");
	Pather.moveToExit(36, true, Config.ClearType);
	Pather.moveToExit(37, true, Config.ClearType);
	Attack.clearLevel();
	delay(4000);
	Pickit.pickItems();
	Town.goToTown();
    }
return true;
}

**Comment by mf022** [comment]
like @5noop already said above, the bottom of your Config.js should look like:
```javascript
    },
	ActOneWalker: {
		Den: false,
		ColdStony: false,
		Up: false,
		DarkMarsh: false,
		TamoeInner: false,
		Barracks: false,
		Jail: false,
		CataWP: false,
		Andy: false,
	}
};
```

**Comment by tlwh163** [comment]
like this, easy!

// *** act 1 ***

Scripts.ActOneWalker = false;
    if (!Config.hasOwnProperty("ActOneWalker")) {Config.ActOneWalker = {};}
        Config.ActOneWalker.Den = false;  <---- line 33
	Config.ActOneWalker.ColdStony = false; 
	Config.ActOneWalker.Up = false; 
	Config.ActOneWalker.DarkMarsh = false;
	Config.ActOneWalker.TamoeInner = false; 
	Config.ActOneWalker.Barracks = false; 
	Config.ActOneWalker.Jail = false; 
	Config.ActOneWalker.CataWP = false;
	Config.ActOneWalker.Andy = false;
