### ISSUE TITLE
Character selection -> log out (D2BotMap)

### ISSUE THREAD

**Issue by ryancrunchi** [kolton/d2bot-with-kolbot#201]
Hello,
When I run an instance of D2 with D2BotMap as entry point for manual play, log in and select a character (double click or select+OK), I'm kicked out to login screen again. I have not even time to see the lobby. This does not happen every time, but like 1/2.
When it happens my friends see `ryancrunchi has entered battle net` followed by `ryancrunchi has exited battle net`. After some tries I get `Unable to connect to battle net` of course...
Do you know why ?
Maybe the profile I'm running D2BotMap is not set correctly ?

**Comment by mboufos** [comment]
its a blizz bug after patch...

**Comment by ryancrunchi** [comment]
Ok thanks, nothing to do but wait or get lucky ^^
