### ISSUE TITLE
classic cs

### ISSUE THREAD

**Issue by anime143** [kolton/d2bot-with-kolbot#2012]
bump, iso help. 
my setup is based on xpac style but i want it to be classic only. 

i followed as instructed but doesn't seem to work unless i switch it to xpac config like mf helper/ diablo help.

_Originally posted by @anime143 in https://github.com/kolton/d2bot-with-kolbot/issues/460#issuecomment-560236576_

**Comment by noah-** [comment]
https://gist.github.com/noah-/2685fbeccc72fd595bbe89116aea272e

**Comment by gtoilet** [comment]
I use stock Diablo / Diablohelper

They work just fine

**Comment by mf022** [comment]
some variables cannot be removed from char config, unless you'll edit more a lot of library files.
you should search with np++ Find in Files (Ctrl+Shift+F) all the lines related to a variable to see if you could remove it safely.

**Comment by anime143** [comment]
> I use stock Diablo / Diablohelper
> 
> They work just fine

i dont like how the din and barb wonder off and doesn't precast., they do fight but they run the full loop to the seals and back (set to: doesn't hit seal). the sorc would then be on the other side fighting by herself. 


> https://gist.github.com/noah-/2685fbeccc72fd595bbe89116aea272e
@noah- i'll try this out later on today and see if this would fix it.

**Comment by anime143** [comment]
> https://gist.github.com/noah-/2685fbeccc72fd595bbe89116aea272e

@noah- by chars are idle-ing in A4 town, i would like for them to start at the star. If i put taxi- true, they'll taxi fine. Also, this stop my chars from helping kill Andy, Dur, Meph. Could you take a look and adviced? 
[Sorceress.txt](https://github.com/kolton/d2bot-with-kolbot/files/3919483/Sorceress.txt)

**Comment by gtoilet** [comment]
> > I use stock Diablo / Diablohelper
> > They work just fine
> 
> i dont like how the din and barb wonder off and doesn't precast., they do fight but they run the full loop to the seals and back (set to: doesn't hit seal). the sorc would then be on the other side fighting by herself.
> 
> > https://gist.github.com/noah-/2685fbeccc72fd595bbe89116aea272e
> > @noah- i'll try this out later on today and see if this would fix it.

That's simple edits to precast more and for sorc to stay close I have it static alot keeps her from skipping cold immunes
