### ISSUE TITLE
Please help pickit error

### ISSUE THREAD

**Issue by Subsevendgrz** [kolton/d2bot-with-kolbot#2016]
I cannot figure out what is wrong with this line. Can anyone help me?

Pickit error! Line # 742 Entry: [Type] == jewel && [Quality] == magic # ([Defense] >= 64 || [MaxDamage] >= 15] || [EnhancedDamage] >= 40 || [ToHit] >= 100 || [MaxMana] >= 20 || [FireResist]+[LightResist]+[ColdResist]+[PoisonResist] >= 60 || [FireResist] >= 30 || [ColdResist] >= 30 || [LightResist] >= 30 || [PoisonResist] >= 30) (kolton.nip) Error message: missing ) in parenthetical Trigger item: Jewel

Here is the original line # 742
[Type] == jewel && [Quality] == magic # ([Defense] >= 64 || [MaxDamage] >= 15] || [EnhancedDamage] >= 40 || [ToHit] >= 100 || [MaxMana] >= 20 || [FireResist]+[LightResist]+[ColdResist]+[PoisonResist] >= 60 || [FireResist] >= 30 || [ColdResist] >= 30 || [LightResist] >= 30 || [PoisonResist] >= 30)

Thanks in advance

**Comment by mf022** [comment]
> Here is the original line # 742

You posted the same thing twice.

you have an extra bracket after 15 value
[MaxDamage] >= 15]

use {NipCheck](https://github.com/blizzhackers/pickits/blob/master/nipcheck/#nipcheck) plugin for np++

check the [Nip guide](https://github.com/blizzhackers/pickits/blob/master/NipGuide.md/#nip-guide)

**Comment by Subsevendgrz** [comment]
Ty so much. That was driving me crazy. Ill check out the nipcheck when i get home. Greatly appreciated.
