### ISSUE TITLE
Help with bobarb leader and sorc runner setup

### ISSUE THREAD

**Issue by UlfMitHand** [kolton/d2bot-with-kolbot#2020]
Hi, I'm pretty new to the kolbot, but I managed to get the autosmurf script running. I now got 2  chars in hell and want to setup my runs in a certain way. I googled for 8 hours and broke my kolbot twice (had to reset the js).
Can some one help me to setup my bot like this:

I got a Bobarb  and a blizzsorc, each on a sperate account with own d2 keys.

1. The Bobarb opens the game, the blizzsorc joins and they party up.

2. Bobarb buffs the blizzsorc. 
You probably  need to choose a zone?

3. Bobarb waits until blizzsorc is done and leaves the game OR he starts the next game and waits there for the sorc.

If you got any ideas what a Bobarb can do while he is waiting, let me hear it.

4. The blizzsorc starts doing her own runs alone after the buff and joins the next game when she is done.

It is important to me that the barb opens the games. I'm not sure how to make a leader wait and let a follower do all the work.

I kinda know that my barb has to be the leader and know how to setup the follow in game stuff. But I'm not sure how to make the runs.

**Comment by mf022** [comment]
the creator of the game doesn't need to be leader in game.

you can set barb only to open the game (starter script - D2Lead) and to quit it after your solo sorceress, or a team will leave.

for bo barb you can set a modded script - https://github.com/blizzhackers/documentation/blob/master/kolbot/MiscellaneousOptions.md/#modded-battleordersjs

depending of the time of BC/BO/Shout and the areas set for sorceress, other moves to the Catacomb wp should be set from time to time.

**Comment by UlfMitHand** [comment]
Oh damn! Thanks for that info about the leader and starting a game! That changes a lot for me and makes it way more easy!
