### ISSUE TITLE
Leader won't make tps

### ISSUE THREAD

**Issue by GeMiNiJaKe** [kolton/d2bot-with-kolbot#2032]
How can I get leader (pubjoin script) to make tps for my follower (botfollow script)

**Comment by GeMiNiJaKe** [comment]
Only fix I've come up with is pausing the bot and manually making a tp. Btw both bots are on DiabloHelper and BaalHelper

**Comment by mf022** [comment]
These lines from DiabloHelper - https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/bots/DiabloHelper.js#L436, and BaalHelper - https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/bots/BaalHelper.js#L235, tell the bot to take any opened tp (null) to the Chaos or Throne, or the one of the configured leader.

If that seems to not for you, and only if it's the same leader, try to set it in char configs in the leeching section.
