### ISSUE TITLE
Wakka Leech Problem

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#2033]
Hello again, new Problem

is there a way, to autoreconnect in to leaders game, after a wakka leacher is die on a monster?
Right now the leecher is waiting in the Channel and join the new game.

Ya, u can write "reload" in Console, but is there a way to restart the Script and join again the game?

**Comment by mf022** [comment]
Did you try to cancel the chicken exit for your wakka, if it isn't a HC char?

**Comment by DS1337** [comment]
Works, but not a good solution, because u loosing exp...
So why to do Wakka when u loose it anyway? xD
