### ISSUE TITLE
Holy Shield Din

### ISSUE THREAD

**Issue by anime143** [kolton/d2bot-with-kolbot#2039]
Paladin  is not casting holy shield,
is it the precast file? pather? misc? this is my precast.js s

[Precast.txt](https://github.com/kolton/d2bot-with-kolbot/files/3957740/Precast.txt)
ettings.

**Comment by mf022** [comment]
> Precast.txt

your file it's the default Precast.js with no changes.


> Paladin is not casting holy shield,

Does your char have at least 1 point in Holy Shield skill?
