### ISSUE TITLE
wont join mule game

### ISSUE THREAD

**Issue by ovaaj** [kolton/d2bot-with-kolbot#205]
https://github.com/kolton/d2bot-with-kolbot/issues/129
i notice this guy had the same issue but resolved it on his own - i wish i was as fortunate, however that doesnt seem to be the case. my bot was muling fine a few days ago and i edited the automule, only to find i had added an extra comma on the stop profiles line. i deleted the comma and the profile trying to mule whether it be my hdin druid or sorc, it always says 
13:40:59 PM]  <chillz>  MuleCheck triggered!
[13:41:01 PM]  <chillz>  Starting  mule profile: mule
[13:41:02 PM]  <chillz>  Mule profile is busy.
before the mule even has a chance to get logged in let alone in game
i tried grabbing a fresh automule.js file and re-entering my info, but am getting the same result
where it says 
[13:41:10 PM]  <mule>  In  mule game.
[13:42:10 PM]  <mule>  Nobody joined - stopping.

http://pastebin.com/YSdFb3er this is my auto mule file with the pw n acc removed :P lmk if i messed anything obvious up that im not seeing! (im a noob i know)

**Comment by mboufos** [comment]
well those errors are usually from wrong names on profiles re-check the profile name on mule and bots,
["Ovaj", "Tempestuous", "Chillz", "Infuriated"], those should be profiles names i will avoid caps or spaces between names 
and this should be muleProfile: "mule", profile  on kolbot :)

**Comment by ovaaj** [comment]
i mean theyre clearly trying to mule - its just saying the mule profile is busy before its even logged in let alone made the game. also - i noticed the mule is trying to join the same hell game but its on d2botmule.dbj - tis seems odd to me? yea mule is the name of the mule profile :P i changed the caps to see if that does anything ill check back in a min

**Comment by mboufos** [comment]
your mule profile is like this ?
http://oi64.tinypic.com/346q26t.jpg

with useast realm ?

**Comment by ovaaj** [comment]
WOW u were write it was the caps. thanks man :)
