### ISSUE TITLE
ClearAnyArea Error

### ISSUE THREAD

**Issue by satubus** [kolton/d2bot-with-kolbot#2050]
AutoSmurf Leader (brand new char, lvl 1) wants to go to Act 2 [1,40,41,42,56,57].
Can't find the place where act 2 is defined, but it seems to be case 2 when calling function goal from AutoSmurf, but I wonder what triggers case 2? Any ideas?

Thanks in advance

**Comment by 5noop** [comment]
Did you set cubing to false in your char configs ? Because otherwise he's gonna try to get it in act 2.

**Comment by satubus** [comment]
Thanks now my problem is solved. Should written clear in config file.
Another problem is that now my team won't follow my leader.

**Comment by satubus** [comment]
Nevermind, solved it by simply restarting the scripts.
