### ISSUE TITLE
Follower.Js BOT. Javazon is going to town too often to repair javelin.

### ISSUE THREAD

**Issue by sgaspa** [kolton/d2bot-with-kolbot#2057]
Hi,

I'm using a javazon follower bot while I Play manually my sorc and I just notice that the char is going in town very often to repair the javelin quantity at max. It doesn't go when it finishes the stack, but very early with at least 30 javelin....There's a way to set a lower number of javelin or lower the repair flag?  I think is just the follower bot but not sure. 

Thank you

**Comment by anime143** [comment]
in your char config...

Config.RepairPercent = xx; // Durability percent of any equipped item that will trigger repairs.

**Comment by sgaspa** [comment]
Oh god... I'm so blind! thank you very much!!! solved :>
