### ISSUE TITLE
My Sorc doesn't cast static field to the boss

### ISSUE THREAD

**Issue by abcd40404** [kolton/d2bot-with-kolbot#2081]
Here is my attack config:
https://pastebin.com/2mydD34t
I set the config to be Config.StaticList = ["Diablo", "Baal", "Mephisto", "Andariel"];
But it won't cast static when attack the boss.

**Comment by Javapeas** [comment]
Config.CastStatic = 60; // Cast static until the target is at designated life percent. 100 = disabled.

**Comment by abcd40404** [comment]
Yes, I set it to 60(more specific config the link above).

**Comment by Javapeas** [comment]
1. Sorc has Static Skill?
2. Maybe your DodgeRange exceeds range of Static: to check it try to turn off Dodge.

**Comment by abcd40404** [comment]
I found the issue. It's a language problem.
In Sorceress.js Line 47:
The unit.name is Chinese in my case, so it's always false.

**Comment by abcd40404** [comment]
It works when I change to the English version. I close this issue.
