### ISSUE TITLE
The Palace Cellar - clear request

### ISSUE THREAD

**Issue by gravsh** [kolton/d2bot-with-kolbot#2085]
Hi. Is this possible to make a script that allows the bot to clean all thee level of the The Palace Cellar?

**Comment by 5noop** [comment]
Save this under PalaceCellar.js
```
function PalaceCellar() {
	Town.doChores();
	Pather.useWaypoint(74);
	Precast.doPrecast(true);

	if (!Pather.usePortal(null)) {
		throw new Error("Failed to move to Fire Eye");
	}
	Attack.clearLevel(Config.ClearType);

	if (Pather.moveToExit(53, true)) {
		Attack.clearLevel(Config.ClearType);
	}

	if (Pather.moveToExit(52, true)) {
		Attack.clearLevel(Config.ClearType);
	}

	return true;
}
```

It should work but if something is wrong remember you can always ClearAnyArea.

**Comment by gravsh** [comment]
so in the config is should look like this:

Scripts.Summoner = true;
	Config.Summoner.FireEye = true;
	Config.Summoner.ClearPalaceCellar = true; // Clear all 3 levels
?

**Comment by gravsh** [comment]
or
Scripts.Summoner = false;
Config.Summoner.FireEye = true;
Config.Summoner.ClearPalaceCellar = true; // Clear all 3 levels

**Comment by 5noop** [comment]
Scripts.PalaceCellar = true;
