### ISSUE TITLE
Config.Openchests = 2  |  How do i remove barrels, urns, jars?

### ISSUE THREAD

**Issue by loldermond** [kolton/d2bot-with-kolbot#2102]
The title says it all. Or is it possible to only open all the chests in chaos sanctuary? Atm the bot is opening everything in countess area - when i just wished not to overgo the treasures in act 4

**Comment by gtoilet** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/1568

**Comment by WiZzMaN47** [comment]
Misc.js ... Line 995? Look around there to add or remove
