### ISSUE TITLE
Attack.clearlevel wont pickit

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#2111]
So I need it to clear level of champs for made quest set to attack.clearlevel via clear type 0xf
Won't pickit items after kills mobs

And I even put made in nip file thinking that would affect it but doesn't 

I'll link what code I got tomorrow

**Comment by 5noop** [comment]
Attack.clearlevel uses Attack.clear which calls Pickit.pickItems, maybe there is something wrong with your pickit file ?

**Comment by gtoilet** [comment]
Config.PickitFiles.push("kolton.nip");

[Name] == AJadeFigurine && [Quality] == unique





		say("starting bird");
		Town.doChores();
		Precast.doPrecast(true);
		Pather.useWaypoint(76, true);

		if (!Pather.moveToExit([84], true)) {
			throw new Error("potion failed");
		}
	Attack.clearLevel(Config.ClearType = 0xf);
						target = getUnit(4, 546);
					Town.goToTown();
                                if (!me.inTown || !Town.openStash()) {
                                        me.overhear("Failed to open stash");
 
                                        activeAction = false;
 
                                        break;
                                }
				var items = me.findItems(546);

				if (items) {
					while (activeAction && items.length > 0) {
						Packet.dropItem(items.shift());
							
					}
						
				}
					say("jade at stash unparty for complete");
	
				me.cancel();

**Comment by mikedorsi** [comment]
@5noop Should he be calling the Jade Figurine's classID of 546 in his pickit instead of the name?

**Comment by 5noop** [comment]
It's the same but the figurine is of normal quality, you can simply write `[Name] == AJadeFigurine` anyway.

**Comment by gtoilet** [comment]
> It's the same but the figurine is of normal quality, you can simply write `[Name] == AJadeFigurine` anyway.

Did the trick thanks fella
