### ISSUE TITLE
How to bot with 2 accounts without getting banned?

### ISSUE THREAD

**Issue by YOZSi** [kolton/d2bot-with-kolbot#2115]
I've added another account (and another cd-key) but when I use both at the same time I get a temp ban (waiting in line to create a game).

How do you guys do it? What is your gamelead settings ? Can u help me guys ?!

**Comment by kolbotuser** [comment]
I run 2 bots in separate games. Most likely your problem is having too short of games. Mine run 10min ish games and that seems to be okay. Both accounts use d2botlead.dbj

**Comment by Erfell** [comment]
2 choices: you can make longer games (like above) or you can set leader and leecher and have them running in the same game

**Comment by YOZSi** [comment]
Thank you guys ! What is your "CreateGameDelay: 180, // Seconds to wait before creating a new game" settings ? :)

**Comment by kolbotuser** [comment]
> Thank you guys ! What is your "CreateGameDelay: 180, // Seconds to wait before creating a new game" settings ? :)

pretty sure mine is set between 10 and 15 seconds, randomly

**Comment by YOZSi** [comment]
Thank you all ! Problem solved ! :)
