### ISSUE TITLE
+2技 頭飾哪裡錯誤? +2 Skills What's wrong with the headdress?

### ISSUE THREAD

**Issue by x75225** [kolton/d2bot-with-kolbot#2116]
[Name] == ( Tiara || Coronet || Diadem || Circlet) == Rare # [FRW] >= 20 && ([Strength] >= 25 || [Dexterity] >= 25 || [Sockets] >= 2) && [Amazon skills] == 2
[Name] == ( Tiara || Coronet || Diadem || Circlet) == Rare # [FCR] == 20 && ([Strength] >= 25 || [Dexterity] >= 25 || [Sockets] >= 2) && ([fireskilltab] == 2 || [coldskilltab] == 2 || [lightningskilltab] == 2 || [poisonandBoneskilltab] == 2 || [elementalskilltab] == 2 || [palicombatskilltab] == 2 || [trapsskilltab] == 2)
+2 Skills What's wrong with the headdress?

**Comment by InterestingIndeed** [comment]
You are missing "quality" before == Rare

**Comment by x75225** [comment]
Thank you for responding i try to modify it

**Comment by x75225** [comment]
> 您在==之前缺少“質量”


I tried to modify it without any errors. It should be ok

**Comment by x75225** [comment]
> 您在==之前缺少“質量”


I tried to modify it without any errors. It should be no problem.
