### ISSUE TITLE
summon spirit from HOTO

### ISSUE THREAD

**Issue by aochalkov** [kolton/d2bot-with-kolbot#2127]
Hello. Can some one help how can i set my sorc to summon spirit from HOTO?
I read that i need to edit precast script, but it's kindo hard for me...

**Comment by aochalkov** [comment]
I've read https://github.com/kolton/d2bot-with-kolbot/pull/1523 but have no idea, what to do with this...

**Comment by aochalkov** [comment]
I've found code in prototype.js. Can i Use those functions in bot scripts? There is example in thread:

// Only cast an oak, if you dont already have one
!me.getMinionCount(14) && me.castChargedSkill(226)

But i have no idea how to use it =(

**Comment by 5noop** [comment]
I would advise you not to do it. The spirit dies very often so it's kinda useless, and you lose time and gold recasting it after every fight.

If you still want to test it here is the line to add in the precast function:
`!me.getMinionCount(13) && me.getItems(-1, 1).filter(item => item.getPrefix(20557)).map(hoto => Skill.cast(226, 0, me.x, me.y, hoto))`

**Comment by aochalkov** [comment]
ok, thx

**Comment by DarkHorseDre** [comment]
Hey @5noop did you cast the skill in that way? I cant seem to get it to cast unless I use
'Packet.castSkill(0, me.x, me.y)' after setting the skill.
