### ISSUE TITLE
Killing Diablo

### ISSUE THREAD

**Issue by Fishome80** [kolton/d2bot-with-kolbot#2135]
Hi,

during my sorc hit the diablo, she stands a bit far away from diablo. How to set it tele to diablo to get close before? or stands exactly in the mid.

please let me know how to set

**Comment by Fa-b** [comment]
look [here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/bots/Diablo.js#L473-L482):
```js
switch (me.classid) {
    case 1:
	Pather.moveTo(7792, 5294);

	break;
    default:
	Pather.moveTo(7788, 5292);

	break;
}
```

`case 1:` is Sorceress, so you can simply adjust her position before she starts attacking I would guess.

Hope that helps
Fa-b

**Comment by Fishome80** [comment]
Thank you for the information. I can't find the part you mentioned in  Fastdiablo.js. please advise

**Comment by Fa-b** [comment]
Sorry, in FastDiablo.js it should be [here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/bots/FastDiablo.js#L256)

**Comment by Fishome80** [comment]
Thank you it works :)
