### ISSUE TITLE
How to display xy coords?

### ISSUE THREAD

**Issue by webb24** [kolton/d2bot-with-kolbot#2137]
My autobaal bo barb comes through the portal and does his war cries no problem. The problem is he is so far to the side my main crew miss it. Is there a way i can over lay xy coords to see what i need to set the xy coords in the script to? I would like for him to come in and move towards the back and start doing warcries there.

**Comment by gtoilet** [comment]
Alt+home 
Me.x
Me.y

**Comment by webb24** [comment]
Thanks so much! That worked great for me!
