### ISSUE TITLE
Want to skip Battle Orders before some Areas

### ISSUE THREAD

**Issue by GSmitaka** [kolton/d2bot-with-kolbot#2138]
Hey there!
Is there any way to skip the battle orders precast before some areas?
Im running 3 characters party games (Hammer Leader and two Sorcers followers).
So every character has CTA itself and running different areas, but go together in Diablo and Baal.
If my sorc come to chaos after killing summoner for example, she goes first to River of Flame WP, precast BO and then goes to leaders Portal. They doest the same with baal, even they are with BO and it takes a lots of time and misses Baal Waves.
I've tried and set properly the BattleOrders script, but its happening again.

Thanks in advance!

**Comment by gtoilet** [comment]
If you remove precast from Diablo.js will solve your problem but every toon that runs Diablo.js will not buff before run not just the sorc

**Comment by Fa-b** [comment]
Are you using the BaalHelper script?

Maybe [here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/bots/BaalHelper.js#L174-L177)

changing:
```js
Pather.useWaypoint(Config.RandomPrecast ? "random" : 129);
Precast.doPrecast(true);

if (Config.BaalHelper.SkipTP) {
```
to:
```js
// Only do precast if not using Leaders TP
if (Config.BaalHelper.SkipTP) {

    Pather.useWaypoint(Config.RandomPrecast ? "random" : 129);
    Precast.doPrecast(true);
```

Same story for [DiabloHelper.js](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/bots/DiabloHelper.js#L396-L399)

```js
Pather.useWaypoint(Config.RandomPrecast ? "random" : 107);
Precast.doPrecast(true);

if (Config.DiabloHelper.SkipTP) {
```
to:
```js
// Only do precast if not using Leaders TP
if (Config.DiabloHelper.SkipTP) {

    Pather.useWaypoint(Config.RandomPrecast ? "random" : 107);
    Precast.doPrecast(true);
```

This should do the trick I think

**Comment by GSmitaka** [comment]
I just tried the "Non elegant"method and its working perfectly!

Thanks.

**Comment by Fa-b** [comment]
glad i could help :)
