### ISSUE TITLE
How to kill Soul Killers before immune Greater Mummy in Throne of Destruction 

### ISSUE THREAD

**Issue by gravsh** [kolton/d2bot-with-kolbot#2142]
Hi, 
is there a way to setup the bot to kill Soul Killers before any other monsters like Greater Mummies, which are immune. Killing immune Greater Mummies is slow, therefore Soul Killers are able to kill the bot before immune Greater Mummies are actually dead.

Thank for help.

**Comment by Fa-b** [comment]
Well, there appears to be a similar implementation for Dolls already: [Baal.js](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/bots/Baal.js#L100-L125)
That makes it easy to copy paste and adjust for the Souls:
```js
                monList = []; // clear monList
                // Do the same again for souls
                if (Config.AvoidSouls) {
			monster = getUnit(1, 640);

			if (monster) {
				do {
					if (monster.x >= 15072 && monster.x <= 15118 && monster.y >= 5002 && monster.y <= 5079 && Attack.checkMonster(monster) && Attack.skipCheck(monster)) {
						monList.push(copyUnit(monster));
					}
				} while (monster.getNext());
			}

			if (monList.length) {
				Attack.clearList(monList);
			}
		}
```

just add another property to your Config.js [here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/common/Config.js#L295):
```js
AvoidSouls: false,
```

And use it in your character config

**Comment by gravsh** [comment]
Hi, Thanks for the answer.

So the Config.AvoidSouls can exist together with Config.AvoidDolls? Or should I replaced it instead?

**Comment by Fa-b** [comment]
Its bust an addition, leave AvoidDolls as it is..
Bot will first kill dolls, then move on with souls and the rest afterwards
