### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by Djongov** [kolton/d2bot-with-kolbot#2147]
Hey guys,

Awesome work on the bot. I am running it for single player and I just managed to configure my MF sorc to start running. I have plans on recording the runs, so i can review them and see highlights of the runs or where a particular item had dropped visually (i know this gets recorded into the client).

So my questions are:

1. How can I make the bot run with ALT button held all the time. Just so that everything that drops is seen on the ground?
2. How can I make the bot to strash the items I want Unidentified?
Is it by changing the kolton.nip lines like this?
[name] == sacredarmor && [quality] == unique && [flag] != identified // Tyrael or Templar
3. My number of runs stay at 0 in the client. Any idea why? Count of the only way to know how many runes were executed
![image](https://user-images.githubusercontent.com/49032971/72209866-117b2300-34bc-11ea-8484-620ad3d943a8.png)

**Comment by aochalkov** [comment]
2. Bot will keep items if they match conditions. If they match befor indentification, bot will keep them.
In youe example, if you delete "[flag] != identified", bot will not identify sacred armor if it unique.
Can't help about other points...

**Comment by 5noop** [comment]
1. I don't think that's possible with kolbot, but you can always use a macro like autohotkey or autoit.
3. It's not implemented for single player.

**Comment by Djongov** [comment]
Thanks for the answers. Make sense.
