### ISSUE TITLE
Add NPC Anya (shop-scan) to the Pindleskin script

### ISSUE THREAD

**Issue by LAeRacing** [kolton/d2bot-with-kolbot#2149]
Please add the function to the Pindleskin script, that the user can set (true or false) if anya should be visited by running by into the red portal.

Because alot of items can be shoped at Anya hell like 5/6 Traps claws or +3 bo sticks, 3/20 gloves and so on...

This would be great, Thanks :D

**Comment by gtoilet** [comment]
You can set interact with her in script can try to find my code or the thread i made

**Comment by gtoilet** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/1574

**Comment by LAeRacing** [comment]
After a few tryouts i've made it. Thanks @gtoilet for ur support.
Since shopItems will lead to Malah instead of Anya, ive done it like this:

In the file **Pindleskin.js** i've added another var:
```
function Pindleskin() {
	var anya, AnyaShop; //var AnyaShop added
```

after **Town.move(NPC.Anya);**

```
AnyaShop = getUnit(1, NPC.Anya); 	//Anya Shop on Pindleskin
AnyaShop.startTrade();			//
Town.shopItems();			//
me.cancel();				//
```

In the console you can see, that MiniShopBot works and displays the scanned items. It checks for items in your normal char pickit and not the shopbot standard nip file.

**-CLOSED-**
