### ISSUE TITLE
Need help for script for boss fights.

### ISSUE THREAD

**Issue by Evilpino** [kolton/d2bot-with-kolbot#2150]
Hi,

need someones help with script for baal boss fight.

The action i want my follower to do is helping my main hitting baal to 10% hp, after that create townportal, leave world stone chamber and wait in town, stalling XXX sec.

can someone helping me with a script that my char during baal script stop attacking at X% hp and leave fighting place immediatly.

Do I need to unwrite Baal.js? or creating a new config? Thank you for your attentions in advance:)

**Comment by gtoilet** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/1722

**Comment by Evilpino** [comment]
> 
> 
> #1722

thank you, it helps a lot.

**Comment by Evilpino** [comment]
thx for help! t/c
