### ISSUE TITLE
Diablo Helper issue

### ISSUE THREAD

**Issue by Fishome80** [kolton/d2bot-with-kolbot#2151]
My leecher/helper keeps running straight out of town in order to get to chaos at the beginning of every run. I have set it to not skip the portal, yet he still says something like "geting wp" then rushes out of town. I just want him to stand in town, wait for my leader to send a tp so that he can join and help kill stuff from there. This is because i have no enigma and running there is just stupid. Any ideas?

**Comment by gtoilet** [comment]
Give him the wp

**Comment by Fishome80** [comment]
Thank you
