### ISSUE TITLE
Baal fight.

### ISSUE THREAD

**Issue by Evilpino** [kolton/d2bot-with-kolbot#2158]
hi,

first of all i want to describe my problem.
i want my lead and follower to clear throne and then both of them beat baal down to 20% hp.
then i want my follower to leave the throne and let my leader get the last hit (for exp reason).

i know the attack hurt config but can anyone maybe help me how and where implement?

**Comment by Evilpino** [comment]
ofc i think about leader using baal script and follower using baal helper, but i want my leader to come after my follower got first into throne.

**Comment by gtoilet** [comment]
Follower could just unparty stay in area to help pickit after he quits attacking baal

**Comment by Evilpino** [comment]
just solved the problem, thank you:)
