### ISSUE TITLE
Failed to kill Nihlathak (No valid attack skills) - Error

### ISSUE THREAD

**Issue by InterestingIndeed** [kolton/d2bot-with-kolbot#2164]
I am getting this error in some of my runs. Im still pretty new to Kolbot and can't make much of the Error Message. Could it be the char is to weak to kill Nihal (e.g. when it has a certain set of immunities/skills), runs out of mana which leaves the char without a way to attack and then it has "no valid attack skill"?

```
[2020/01/14 22:02:51] <MF Light> Error in Nihlathak (attack.js line 298): Failed to kill Nihlathak (No valid attack skills)
Stack: main@default.dbj:201, Loader.init@loader.js:17, Loader.loadScripts@loader.js:135, Nihlathak@nihlathak.js:24, Attack.kill@attack.js:298
```

**Comment by 5noop** [comment]
Make sure `Config.attackSkill` are properly defined in your char config.

**Comment by InterestingIndeed** [comment]
I believe it is. As I mentioned, it only happens in some of the runs (maybe 1 in 10). Im using a light sorc, heres my attack config using light bolt and chain lightning:

	```
Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 49; // Primary skill to bosses.
	Config.AttackSkill[2] = -1; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 53; // Primary skill to others.
	Config.AttackSkill[4] = -1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.
```

**Comment by 5noop** [comment]
Then it's probably because he's lightning immune, do you use Telestomp ?

**Comment by InterestingIndeed** [comment]
> Then it's probably because he's lightning immune, do you use Telestomp ?

I will try that.

**Comment by Fa-b** [comment]
Get your merc an infinity, lightsorc + telestomp on nihlathak will most probably have you killed...

**Comment by InterestingIndeed** [comment]
> Get your merc an infinity, lightsorc + telestomp on nihlathak will most probably have you killed...

yup, totally true, even with infinity. It increases the chance of dying in CS by a lot as well. Had to find that one out the hard way. My next try will be to add a point to fireball and try that. Not sure If im doing enough dmg with that tough. Im still trying to figure out the "perfect run" for my chars to mf as much as possible while keeping the game time above 11-12 minutes to dodge RD. 

If Nihaltak isnt getting killed that doesn't affect the run that much, just wanted to know what happend there, thanks for all the help.

**Comment by Fa-b** [comment]
I gave my sorc enigma instead of CoH. Strength bonus it brings (for spirit monarch) allows for many more points being spent in vitality (up to 2.5k HP with BO). Also you don't need to spend 3 skillpoints for tele. Telestomping immunes is by far less deadly now.
What I also did in order for the infinity to trigger early enough (range of conviction is 13.3), I reduced the attack range for both Lightning and Chain Lightning from 20 to 15.
Give it a try you will feel the change!

**Comment by InterestingIndeed** [comment]
> I gave my sorc enigma instead of CoH. Strength bonus it brings (for spirit monarch) allows for many more points being spent in vitality (up to 2.5k HP with BO). Also you don't need to spend 3 skillpoints for tele. Telestomping immunes is by far less deadly now.
> What I also did in order for the infinity to trigger early enough (range of conviction is 13.3), I reduced the attack range for both Lightning and Chain Lightning from 20 to 15 in Attack.js.
> Give it a try you will feel the change!

thats what I call a proper recommendation! Now I just have to get my hand on a second Enigma ;) What do you use as dodge range considering the change in attack range?

**Comment by Fa-b** [comment]
Would have to check the Dodge range later and will update this post then.
I think it is around 10, I have also applied another change to Telestomp that was somewhere in the pull requests if I remember correctly. It avoids telestomp when there are more then 3 monsters around the target.

**Comment by InterestingIndeed** [comment]
> Would have to check the Dodge range later and will update this post then.
> I think it is around 10, I have also applied another change to Telestomp that was somewhere in the pull requests if I remember correctly. It avoids telestomp when there are more then 3 monsters around the target.

thank you! much appreciated. I think I had my dodge at 12 when I had a good balance of speed/security (if dodge is put to high, sorc teles more than she deals dmg ;) ).

**Comment by Fa-b** [comment]
I only dodge when life is below a threshold of 90 or 95 % to avoid dodging all the time

**Comment by InterestingIndeed** [comment]
> I only dodge when life is below a threshold of 90 or 95 % to avoid dodging all the time

yeah, I also recently changed that.
