### ISSUE TITLE
Using Kolbot for manual mule?

### ISSUE THREAD

**Issue by InterestingIndeed** [kolton/d2bot-with-kolbot#2166]
How is it possible to use kolbot for manual muling? I want Kolbot to open a game and keep it open while I am muling manually with another instance of diablo 2.

**Comment by InterestingIndeed** [comment]
I am dumb. 

Here is an easy way to mule with yourself using Kolbot. You have to be able to run a 2nd instance of Diablo 2 with another key. 

1. Create a Bot instance with mulelogger and configure it. Use the perming timer (line 30 of mulelogger.js) to make the logger stay in the game for any length of time you wish)
2. mule in the game you created with the mulelogger.

**Comment by WiZzMaN47** [comment]
You can also mule with one instance of d2exp. Make a priv game and wait a
few minutes "2-5" and it will make game stay open even if everyone leaves.
Not reliable for mass mule since items can disappear.
