### ISSUE TITLE
OrgTorch should use walk only when deal with Über Mephisto

### ISSUE THREAD

**Issue by peters0908** [kolton/d2bot-with-kolbot#2168]
Since Über Mephisto got Lvl 20 Conviction and if Pal use Salvation or Lvl 21 Conviction to against that, switch to teleport during fight will be fatal. So please add some script so no teleport during fight with Über Mephisto. Many thanks. ^^

**Comment by Fa-b** [comment]
That sounds like a not so bad idea. Can you see if this works:

```js
if (Config.OrgTorch.UseSalvation && me.classid === 3 && me.getSkill(125, 1)) {
    skillBackup = Config.AttackSkill[2];
    Config.AttackSkill[2] = 125;

    Attack.init();
    
    Pather.teleport = !Config.OrgTorch.ForceSalvation && Pather._teleport; // Don't allow teleporting until Uber Mephisto is down
}

Attack.kill(704);

if (skillBackup && me.classid === 3 && me.getSkill(125, 1)) {
    Config.AttackSkill[2] = skillBackup;

    Pather.teleport = true && Pather._teleport; // Enable teleporting when Uber Mephisto is down

    Attack.init();
}
```
Put it [here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/bots/OrgTorch.js#L231-L244)

And add an entry to the [Config.js](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/common/Config.js#L456-L462):
```js
OrgTorch: {
    WaitForKeys: false,
    WaitTimeout: false,
    UseSalvation: false,
    GetFade: false,
    MakeTorch: true,
    ForceSalvation: false
},
```
Use `Config.OrgTorch.ForceSalvation = true;` in your character config.
It will only happen if `UseSalvation` is also `true` in your character config of course.

As a sidenote, I realised that the `monster classId's.txt`is incomplete. Here are the ID's for the Uber bosses:
```
ubermephisto    704     mephisto        0   Mephisto
uberdiablo      705     diablo          0   Diablo
uberizual       706     izual           0   Izual
uberandariel    707     andariel        0   Lilith
uberduriel      708     duriel          0   Duriel
uberbaal        709     baalcrab        0   Baal Crab
```

**Comment by peters0908** [comment]
Thank you for your great efforts. Your code work great! But now bot will use Vigor instead. lol.
So could you plz add some codes so Vigor will not allow too during Mephisto?

**Comment by peters0908** [comment]
Sorry I just remind that there are a setting can do: 
Config.Vigor = false;

So now everything is fine. Thx again!
