### ISSUE TITLE
MainLoopException: Couldn't open file d: No such file or directory (mulelogger.js #115)

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2172]
I got such error message (many repeated messages in console).
What can be wrong?

![image](https://user-images.githubusercontent.com/31447095/72605707-f5490d00-3925-11ea-99f8-71842f461db7.png)

**Comment by InterestingIndeed** [comment]
Check the mulelogger.js and see whats in line 115?

**Comment by ARkaine2** [comment]
> Check the mulelogger.js and see whats in line 115?

![image](https://user-images.githubusercontent.com/31447095/72611868-d9e4fe80-3933-11ea-907a-74d360d010da.png)

**Comment by ARkaine2** [comment]
Seems that i got that.
I deleted folder Secure (and Web too) from Data.
Thanks you for your help.

**Comment by InterestingIndeed** [comment]
You are welcome. Looking for the lines where the error occurs helps a lot ;) Close the topic when your question is answered please.
