### ISSUE TITLE
Log Runes

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2186]
There's in character config file such part of code:

```
Config.LogLowRunes = false;							// Log low runes (El--Dol)
Config.LogMiddleRunes = false;						// Log middle runes (Hel--Mal)
Config.LogHighRunes = true;							// Log high runes (Ist--Zod)
```

Can you please tell me where can I change which runes excatly are "Low", "Middle" and "High"?
Let's say I want to make middle runes Um--Ist.

**Comment by Fa-b** [comment]
[here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/NTItemAlias.dbl#L715-L747) are the rune IDs.
[here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/common/Misc.js#L1321-L1331) is the definition of whats low, mid or high.

**Comment by ARkaine2** [comment]
Thanks alot. I wanted to change this for a long time. :D Now all will be fine.
