### ISSUE TITLE
How to capture errors of joingame() and take actions accordingly

### ISSUE THREAD

**Issue by Kailai-Wang** [kolton/d2bot-with-kolbot#2187]
The background is in limedrop, I wanted to stop the program if joining the given game failed (instead of creating the game which is the default behavior), and even better: taking different actions depending on the join error (password incorrect, ladder/non-ladder game etc).

But I didn't find a proper way to do that, I tried
```
try {
  joingame(...)
} catch (joinErr) {}
```

But it seems to have no effect.
I notice in location switch there's predefined 28 (game not exist) and 38 (game full), but where can I find other cases? Is there a description?

Also where's actually the implementation of joingame() ? I didn't find it :P

Appreciate for any help!

**Comment by Fa-b** [comment]
Funny, you can't find the implementation of `joingame(...)` but expect it to throw an error upon failure...
Errors are usually thrown when something unexpected happens and used to terminate a program gracefully if possible.
First: You cannot find the `joinGame(...)` function here because it's a D2BS function - so kind of a'core' function. D2BS is also the place to look for the available OOG locations:
```c
enum OOG_Location {
    OOG_NONE = 0,
    OOG_LOBBY,
    OOG_INLINE,
    OOG_CHAT,
    OOG_CREATE,
    OOG_JOIN,
    OOG_LADDER,
    OOG_CHANNEL,
    OOG_MAIN_MENU,
    OOG_LOGIN,
    OOG_LOGIN_ERROR,
    OOG_UNABLE_TO_CONNECT,
    OOG_CHAR_SELECT,
    OOG_REALM_DOWN,
    OOG_DISCONNECTED,
    OOG_NEW_CHARACTER,
    OOG_CHARACTER_SELECT_PLEASE_WAIT,
    OOG_LOST_CONNECTION,
    OOG_D2SPLASH,
    OOG_CDKEY_IN_USE,
    OOG_DIFFICULTY,
    OOG_MAIN_MENU_CONNECTING,
    OOG_INVALID_CDKEY,
    OOG_CONNECTING,
    OOG_SERVER_DOWN,
    OOG_PLEASE_WAIT,
    OOG_GAME_EXIST,
    OOG_GATEWAY,
    OOG_GAME_DOES_NOT_EXIST,
    OOG_CHARACTER_CREATE,
    OOG_CHARACTER_CREATE_ALREADY_EXISTS,
    OOG_AGREE_TO_TERMS,
    OOG_NEW_ACCOUNT,
    OOG_PLEASE_READ,
    OOG_REGISTER_EMAIL,
    OOG_CREDITS,
    OOG_CINEMATICS,
    OOG_CHARACTOR_CHANGE_REALM,
    OOG_GAME_IS_FULL,
    OOG_OTHER_MULTIPLAYER,
    OOG_TCP_IP,
    OOG_ENTER_IP_ADDRESS,
    OOG_CHARACTER_SELECT_NO_CHARS,
    OOG_CHARACTER_SELECT_CHANGE_REALM,
    OOG_UNABLE_TO_CONNECT_TCPIP
};
```
What you want to achieve should still be very easy because you can actually copy and paste what is already working. Look at the D2BotMule.js. A Mule attempts to join an existing game before creating a new game. If it does return with code 28 it will click create game instead. All the Location codes are also explained in that state machine. To see if a game join actually worked, a timeout function is used.
You can use D2BS function getLocation to check where you are. [here](https://github.com/noah-/d2bs#group__globalFunctions_1gae7e03a89a0c5ce69e71e7489b5ff2d28) you find the D2BS API.

**Comment by Kailai-Wang** [comment]
> Funny, you can't find the implementation of `joingame(...)` but expect it to throw an error upon failure...
> Errors are usually thrown when something unexpected happens and used to terminate a program gracefully if possible.
> First: You cannot find the `joinGame(...)` function here because it's a D2BS function - so kind of a'core' function. D2BS is also the place to look for the available OOG locations:
> 
> ```c
> enum OOG_Location {
>     OOG_NONE = 0,
>     OOG_LOBBY,
>     OOG_INLINE,
>     OOG_CHAT,
>     OOG_CREATE,
>     OOG_JOIN,
>     OOG_LADDER,
>     OOG_CHANNEL,
>     OOG_MAIN_MENU,
>     OOG_LOGIN,
>     OOG_LOGIN_ERROR,
>     OOG_UNABLE_TO_CONNECT,
>     OOG_CHAR_SELECT,
>     OOG_REALM_DOWN,
>     OOG_DISCONNECTED,
>     OOG_NEW_CHARACTER,
>     OOG_CHARACTER_SELECT_PLEASE_WAIT,
>     OOG_LOST_CONNECTION,
>     OOG_D2SPLASH,
>     OOG_CDKEY_IN_USE,
>     OOG_DIFFICULTY,
>     OOG_MAIN_MENU_CONNECTING,
>     OOG_INVALID_CDKEY,
>     OOG_CONNECTING,
>     OOG_SERVER_DOWN,
>     OOG_PLEASE_WAIT,
>     OOG_GAME_EXIST,
>     OOG_GATEWAY,
>     OOG_GAME_DOES_NOT_EXIST,
>     OOG_CHARACTER_CREATE,
>     OOG_CHARACTER_CREATE_ALREADY_EXISTS,
>     OOG_AGREE_TO_TERMS,
>     OOG_NEW_ACCOUNT,
>     OOG_PLEASE_READ,
>     OOG_REGISTER_EMAIL,
>     OOG_CREDITS,
>     OOG_CINEMATICS,
>     OOG_CHARACTOR_CHANGE_REALM,
>     OOG_GAME_IS_FULL,
>     OOG_OTHER_MULTIPLAYER,
>     OOG_TCP_IP,
>     OOG_ENTER_IP_ADDRESS,
>     OOG_CHARACTER_SELECT_NO_CHARS,
>     OOG_CHARACTER_SELECT_CHANGE_REALM,
>     OOG_UNABLE_TO_CONNECT_TCPIP
> };
> ```
> 
> What you want to achieve should still be very easy because you can actually copy and paste what is already working. Look at the D2BotMule.js. A Mule attempts to join an existing game before creating a new game. If it does return with code 28 it will click create game instead. All the Location codes are also explained in that state machine. To see if a game join actually worked, a timeout function is used.
> You can use D2BS function getLocation to check where you are. [here](https://github.com/noah-/d2bs#group__globalFunctions_1gae7e03a89a0c5ce69e71e7489b5ff2d28) you find the D2BS API.

thank you for the reply and help! :)
I tried to use it as I found them in other codes (with an empty catch tho).

I agree that making adjustments inside code 28 would be not hard, but it doesn't cover all the cases. For example, when the game password is invalid, the dropper will just try to join the game infinitely (it doesn't fall to OOG_GAME_EXIST branch).. the same applies if a NL char trying to join a ladder game or vice versa.

**Comment by Fa-b** [comment]
[here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/D2BotMule.dbj#L1028) the reason why it tries to join when the game already exists. You could implement a mechanism that changes the mule game name by appending a number and use „createGame“ action instead. The master will need to be able to handle that though. Not sure if it works out of the box. Why not make the game name weird enough to be unique?!

**Comment by Kailai-Wang** [comment]
That's not for the mule, that's for the dropper.. so gameaction.dbj should be the one to check I think. I checked case 26 but it never falls to that branch.

Nvm I'm not in urgend need of this one, was just wondering if there's some configs for it already in case I missed that. Thanks for trying to help though!

**Comment by Fa-b** [comment]
> That's not for the mule, that's for the dropper

Why would the dropper need functions for creating accounts and characters? 
If it doesn‘t fall to case 26, maybe it is not staying there long enough.. can it be that the „Game exist“ Screen switches back to something else within a second?
