### ISSUE TITLE
Ignore fire immunes but don't ignore The Countess

### ISSUE THREAD

**Issue by luisfilipepena** [kolton/d2bot-with-kolbot#2189]
So I have a pure fire sorc with cold act3 merc. She does well the areas I want but she ignores all fire immune and I want that. But I don't want her to ignore The countess specifically because she can kill him with light skill. How can I make her ignore all fire immunes but "The Countess"?

Thanks in advance!!!

**Comment by Fa-b** [comment]
[here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/config/Sorceress.js#L481)

Countess id is 2875

**Comment by luisfilipepena** [comment]
> [here](https://github.com/kolton/d2bot-with-kolbot/blob/900eb9aeeeabff9a9d270cac4aa3692df2779350/d2bs/kolbot/libs/config/Sorceress.js#L481)
> 
> Countess id is 2875

Thank you!!!! I didn't see this line.
