### ISSUE TITLE
4 questions : 1. LastHit Boss with MF char? || 2. Two Mercs with different Auras? || 3. ItemFindbonus = Party / same Area? || 4. Leader helping in Cow level??

### ISSUE THREAD

**Issue by loldermond** [kolton/d2bot-with-kolbot#2196]
I run 2 chars, a Hammerdin Leader and a Lightningsorc MFhelper/Leecher, however you wanna call it.

1. Is there a way to make the paladin last hit / the sorc stop attacking the bosses they do together? (Diablo, Baal)

2. I got holy frost Aura on Merc. So i think about getting a different merc with Pala. Would that stack? Which one can you recommend?

3. I read that you find better items with more players in game. Which restrictions are there? Do all the people have to be in a) party to increase the drops or b) be in the same area while killing or c) both or d) just be in the game, without a party?

4. To time them up, i want to do cows with Lightning Sorc while Pala does the bosses up to Diablo where they meet. But that doesn't work out. I'd like pala to JOIN (he is the leader) sorc to finish cow level in between and, if not possible at all, the other way around, let pala open cow level and let sorc help him (not prefered).

Thanks for your help my dear fellows

**Comment by InterestingIndeed** [comment]
1. You can set the helper to not attack/kill the boss at all. Stopping the attack would probably have to be implemented in the helper scripts themselves. If you check the helper script at the bottom, theres the function

`	Attack.kill(243); // Diablo`

you could try changing that to

`	Attack.hurt(243, 50); // Diablo`

I believe that lets the helper attack until 50% of Diablos help. You can try that, Im not sure if it works.

2. Get another one with the frost Aura (if you let him run solo with the merc as well) and give him an insight so he doesnt run out of mana that easily.

3. The number of players doesn't increase the quality of drops. But 2 equipped bots will kill faster than 1 guy = more kills per minute = more drops per minute = more items that can be good per minute. The chance to find good runes increases with the number of players. At least thats what the rune find guides say.

4. I would rather try to synch my bots than trying to mix so many different things up. Clearing cows takes quite a while from my experience, so I would suggest you either:

- shorten the cow runs (e.g. skip immunes, make the bot stronger)
- lengthen the run of your Paladin (e.g. let him clear Pit level 2, if thats not enough let him clear pit level 1 as well)

Whether thats a solution for you depends on how fast your bots kill/clear. Here is my setup that synched quite nice:

Leader: Pit2, Count, Andy, Rada, Tunnels, Summoner, Meph, Izual, CS-entrance (+some more)
Follower: Cows, DiaHelper (+some more)

Most of the time the follower reaches the leader when the leader is doing the first seal in CS. In a perfect run, the follower reaches the leader right after the entrance portal and in the worst case, Diablo is just about to spawn. Its very very rare that the follower misses diablo (maybe 1 in 30 runs).

**Comment by loldermond** [comment]
thanks. problem is that it takes the paladin ridiculously long to clear cows compared to the lightning sorc. i'm skipping cows for that reason now because i don't want to prolong the games to 10 minutes, for sorc is doing diablo and baal alone (easy for her) and if it was for cows, too it would add another 4 minutes while the paladin wouldnt do anything but cows the whole game if i set him for that. i prefer doing all the bosses , travincal and stuff.

so it might make sense using the frost aura twice since they barely even meet.

i'll try the code for damaging diablo and tell you what happened at some point, maybe once i run a third char.

i refuse to send the hammerdin in as diablohelper cause he doesn't significantly increaste the speed. he would need to go different directions to do so - and i guess that's a lot of orders i know nothing about.
