### ISSUE TITLE
how to revive merc the act you're in instead of stubbornly act 2?

### ISSUE THREAD

**Issue by loldermond** [kolton/d2bot-with-kolbot#2201]
hammerdin is strictly affiliated to the second act

**Comment by Fa-b** [comment]
Whats the problem with that? The distance from the waypoint to Griez is shorter than Kashya, Asheara or Qual-Kehk

**Comment by unseenstorm** [comment]
search reviveMerc: function in Town.js and remove
   // Fuck Aheara
		if (me.act === 3) {
			this.goToTown(2);
		}

this might not work in act 3 as the comment says // Fuck Aheara
