### ISSUE TITLE
Let my bot join public games.

### ISSUE THREAD

**Issue by Evilpino** [kolton/d2bot-with-kolbot#2215]
Hi,

I need help to configure two of my bots joining "public" games. Well to be honest, its not so public either. I just 5 bots, three bots on router 1 and two bots on router 2 with two different ips. I just want my 2 bots from router 2 joining games of my router 1 bots.

Maybe there is already a solution postet, if so then can anyone please send me the link to it?

**Comment by Evilpino** [comment]
Ok, try to write it more simpler. I want my bot to join public games with password. detecting my bot games from router 1 (which is set with password) and joining it.

**Comment by gtoilet** [comment]
Add ro friend list or have them announce
Use either channel oe follower entrypoint

**Comment by Evilpino** [comment]
ok problem solved, thx:)
