### ISSUE TITLE
"MultiDodge" or "Smart Dodge"

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2220]
Is there a way to make bot dodge with 2 conditions?

For example the first one will be:
	Config.DodgeRange = 10;
	Config.DodgeHP = 100;
And the second:
	Config.DodgeRange = 15;
	Config.DodgeHP = 95;

**Comment by InterestingIndeed** [comment]
No, I dont think so.

**Comment by ARkaine2** [comment]
> No, I dont think so.

That's sad. 
For example ping chicken we can set to work with multiple conditions.
