### ISSUE TITLE
Skip certain (specified) kind of monsters

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2228]
That's already my third question in my series of questions about some actions on kind of monsters (https://github.com/kolton/d2bot-with-kolbot/issues/1575, https://github.com/kolton/d2bot-with-kolbot/issues/2199).

Some areas are realy nice to farm, but some of monsters that can be meet there (especialy guest monsters that spawn not every run) are real problem to fight with them.

Is there a way to specify to skip (skip like SkipImmune/SkipEnchant/SkipAura. not chicken, not quit [end script/area] and not SkipException) certain monsters (let's say Black Souls [but not Burning Souls], Skeletons [but not Horrors] etc)?

Is it possible to realize it without large part of code editing?

Maybe we can add some custom modifier or even use already existing (like monster name, monster ID, monster code) to additional string "SkipMonster" in character config file?

**Comment by ARkaine2** [comment]
There's part of code in Attack.js.
Maybe it can be used in some way?

```
// Filter monsters based on classId, spectype and range
  getMob: function (classid, spectype, range, center) {
    var monsterList = [],
      monster = getUnit(1);
```

**Comment by WiZzMaN47** [comment]
Again... Look in your charname.js and find

Config.CustomAttack = {"TheCowKing" : [-1,-1]};

-1 = no attack
