### ISSUE TITLE
Armor / weapons breaking

### ISSUE THREAD

**Issue by hockeyman89** [kolton/d2bot-with-kolbot#2230]
I am trying to run a WW barbarian along with my hammerdin to level him up and also to assist the din. The issue I am having is his weapons and armor break- and he is not repairing either on his own. So when I come back he has died a bunch and all gear is broken. I attempted to select cube repair but when he puts the armor and ral in the cube together the game crashes. Any other ideas? Or how to fix this?

**Comment by InterestingIndeed** [comment]
He probably runs out of money. let him pickup/sell stuff so he can repair at the smiths.

**Comment by iihieiii** [comment]
This command over here helped me alot, it stoped with money problems because the bot will pickup any gold equal/higher than 5k.

**Put this line on your pickit or kolton file:**

[name] == gold # [gold] >= 5000 

Gl ;)

**Comment by hockeyman89** [comment]
Thanks guys- that was the issue.. wasn’t picking up enough to keep up with expensive repairs :)
