### ISSUE TITLE
Bot sometimes stops teleporting

### ISSUE THREAD

**Issue by bigwilly2013** [kolton/d2bot-with-kolbot#2234]
Hi, my bot runs fine and then sometimes will stop teleporting then be stuck on holy shield (HDin) and use all mana then just keep retrying to move over and over again. Any tips?

**Comment by InterestingIndeed** [comment]
Any particular area/boss this happens in? Do you get an error message in the ingame bot console (hit the home key during a run to open the console)?

**Comment by Fa-b** [comment]
Happened to me too twice at least. the reason was that for some reason the teleport skill from enigma was not available.. dunno why it happens. taking the enigma off and back on solves it.

**Comment by InterestingIndeed** [comment]
I guess its a game related issue then, not a bot one?

**Comment by bigwilly2013** [comment]
> Happened to me too twice at least. the reason was that for some reason the teleport skill from enigma was not available.. dunno why it happens. taking the enigma off and back on solves it.

Yep that is exactly what happens. I think it is a game issue as it typically tends to happen when I am using my computer for other things with the bot running in the background, so maybe somehow that messes it up. Thanks for the help!
