### ISSUE TITLE
ClearAnyArea and random order of areas

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2237]
Is it possible to make various order of areas in ClearAnyArea script in each run?

**Comment by InterestingIndeed** [comment]
You found a solution for multiple clears already, right? 

You could create multiple clearanyareas1 ... clearanyareasX. lets say you create 5 different versions with 5 different orders. Then you let a function randomly run one of the 5 versions.

**Comment by ARkaine2** [comment]
InterestingIndeed,

I'm not a programer so it's a little bit complicated for me.

Where and how to randomize which script/route select?

Randomization should be in config file or it should be various routes right in ClearAnyAreaX?

What should I do to randomize for example this part of code?

	var i,
		sequence = ["CrystallinePassage", "GlacialTrail", "AncientsWay"];

To get variants like:

	var i,
		sequence = ["CrystallinePassage", "GlacialTrail", "AncientsWay"];

	var i,
		sequence = ["CrystallinePassage", "AncientsWay", "GlacialTrail"];

	var i,
		sequence = ["GlacialTrail", "AncientsWay", "CrystallinePassage"];
		
	var i,
		sequence = ["GlacialTrail", "CrystallinePassage", "AncientsWay"];

	var i,
		sequence = ["AncientsWay", "CrystallinePassage", "GlacialTrail"];

	var i,
		sequence = ["AncientsWay", "GlacialTrail", "CrystallinePassage"];


And how to speficy randomly select scripts in config file?

	Scripts.A1TowerCellar = true;

	Scripts.A2MaggotLair = true;

	Scripts.A2ArcaneSanctuary = true;
	
	Scripts.A2TalRashasTombs = true;

**Comment by don9395** [comment]
This is an interesting question, one which I've been playing around. First off I moved my clearAnyArea script above the acts in hopes it would go sequentially. My issue originated that the bot would do task prior to clearing area. For example: countess, it would run through all the monsters taking a beating, kill the countess and if selected ghosts. Tele back to town then go the the script clearanyarea. It seems to have solved the issue, now I clear the tower levels and kill countess at the end. I also set up multiple clearanyarea scripts, one for each act.

	Scripts.ClearAnyArea = true; // Clear act 1 pit and tower area. Uses Config.ClearType to determine which type of monsters to kill.
		Config.ClearAnyArea.AreaList = [21, 22, 23, 24, 25, 12, 13]; // List of area ids to clear. See sdk/areas.txt
	Scripts.ClearAnyArea = true; // Clear act 2 ancient tunnel area. Uses Config.ClearType to determine which type of monsters to kill.
		Config.ClearAnyArea.AreaList = [65]; // List of area ids to clear. See sdk/areas.txt
	Scripts.ClearAnyArea = true; // Clear act 3 lower kurast and durance of hate levels 2 and 3. Uses Config.ClearType to determine which type of monsters to kill.
		Config.ClearAnyArea.AreaList = [79, 101, 102]; // List of area ids to clear. See sdk/areas.txt
		
	// Boss/area scripts

	// *** act 1 ***

**Comment by ARkaine2** [comment]
don9395, if you set multiple ClearAnyArea in order like in your example:
```
Scripts.ClearAnyArea = true;
Config.ClearAnyArea.AreaList = [21, 22, 23, 24, 25, 12, 13];
Scripts.ClearAnyArea = true;
Config.ClearAnyArea.AreaList = [65];
Scripts.ClearAnyArea = true;
Config.ClearAnyArea.AreaList = [79, 101, 102];
```

Then you'll got something (or exactly) like this:
```
Scripts.ClearAnyArea = true;
Config.ClearAnyArea.AreaList = [21, 22, 23, 24, 25, 12, 13, 65, 79, 101, 102];
```

I already described how I get to run Scripts.ClearAnyArea with any custom order with other scripts (you should create multiple copies of ClearAnyArea.js and name them something like ClearAnyArea1.js and then change their function to and other part of code to ClearAnyArea1).
But my question in this topic is about RANDOM order, which will change each game.

**Comment by don9395** [comment]
Thanks for the information, I guess my real issue is not with my sorc who can tele around but my pally that must walk through the hostiles. If I can have it clear as it goes the issue is resolved. I tried only running the clearanyarea scripts and it would not even leave town. I must activate one of the quest scripts before the other will work regardless of where I place the script. As for randomness, it seems to take care of that on its own, some games begin with countess and others baal. I can make no rhyme or reason why it begins which task. My final hope is to create a new char that I can script starting at level 1 and letting it grow. So clearing prior to quest is a must. 

As you can see, the scripts are now embedded within the acts as you mentioned. Doesn't seem to affect the order. Maybe when I try my pally again I will be able to tell better since he walks everywhere. This all began trying to obtain a BER. LOL

**Comment by Bcubrich** [comment]
There is actually a straightforward way to do this. Simply use rand and an if statement. 

for example, I do 

```
if (rand(0,3)== 0 ) {
	Scripts.ClearAnyArea = true; // Clear any area. Uses Config.ClearType to determine which type of monsters to kill.
	Config.ClearAnyArea.AreaList = [25]; // List of area ids to clear. See sdk/areas.txt 25=countess	
			}
```

to give a 1/4 chance of doing a countess run . 

You will need to get more creative than this to do what you want to do.

Maybe like this

```
Config.RandomRun =(rand(0,3)

if (Config.RandomRun== 0 ) {
	Scripts.Eyeback = true;
	Scripts.SharpTooth = true;
	Scripts.ThreshSocket = true;
	Scripts.Abaddon = true;
			} else if (Config.RandomRun== 1 ) {
	Scripts.ThreshSocket = true;
	Scripts.Abaddon = true;
	Scripts.Eyeback = true;
	Scripts.SharpTooth = true;
                        }else if (Config.RandomRun== 1 ) {
	Scripts.ThreshSocket = false;
	Scripts.Abaddon = false;
	Scripts.Frozenstein = false;
                        } else  {
	Scripts.Eyeback = false;
	Scripts.SharpTooth = false;
	Scripts.ThreshSocket = false;
                        }

```
