### ISSUE TITLE
Request the perfect pick up file to share

### ISSUE THREAD

**Issue by x75225** [kolton/d2bot-with-kolbot#2247]
I hope to get the perfect pick-up gear. It contains all unique equipment, suits, white holes, no holes, tangible and intangible equipment, jewelry, gems, runes, keys, rare magic, rare equipment, money, and exclusive equipment for each profession.  In the same notepad, thank you all

**Comment by ARkaine2** [comment]
Something like this:
[PerfectPickList.txt](https://github.com/kolton/d2bot-with-kolbot/files/4149818/PerfectPickList.txt)
But beware, it won't take most of items. :D

Rename file extension from .txt to .nip.
Place it into "...\KolBot\D2BS\KolBot\Pickit\".
Configure in your config file this pickit file: Config.PickitFiles.push("MainPickList.nip");

I will be appreciate to hear/read suggestions on it.

**Comment by x75225** [comment]
Thank you for your selfless sharing.

**Comment by x75225** [comment]
> 像這樣的東西：
> [PerfectPickList.txt](https://github.com/kolton/d2bot-with-kolbot/files/4149818/PerfectPickList.txt)
> 但是要注意，它不會佔用大部分項目。：D
> 
> 將文件擴展名從.txt重命名為.nip。
> 將其放入“ ... \ KolBot \ D2BS \ KolBot \ Pickit”中。
> 在配置文件中配置此Pickit文件：Config.PickitFiles.push（“ MainPickList.nip”）;
> 
> 我將不勝感激聽到/閱讀有關它的建議。

感謝您的無私分享。

**Comment by x75225** [comment]
> 像這樣的東西：
> [PerfectPickList.txt](https://github.com/kolton/d2bot-with-kolbot/files/4149818/PerfectPickList.txt)
> 但是要注意，它不會佔用大部分項目。：D
> 
> 將文件擴展名從.txt重命名為.nip。
> 將其放入“ ... \ KolBot \ D2BS \ KolBot \ Pickit”中。
> 在配置文件中配置此Pickit文件：Config.PickitFiles.push（“ MainPickList.nip”）;
> 
> 我將不勝感激聽到/閱讀有關它的建議。

Thank you for your selfless sharing.
