### ISSUE TITLE
Can someone help me with Kolbot PubJoin?

### ISSUE THREAD

**Issue by Haevn107** [kolton/d2bot-with-kolbot#2252]
So I want to have my bot join a public game, and basically go through the baal run and then leave and join the next baal run by the same person. Could someone set it up for me? I am not very familiar with any of this so I am very confused. I use a Hammerdin.

[hamdin_kl.txt](https://github.com/kolton/d2bot-with-kolbot/files/4151544/hamdin_kl.txt)

**Comment by InterestingIndeed** [comment]
this can be configured here.

d2bs/kolbot/D2BotPubJoin.dbj

In line 27 the explanation of how to include games the bot should be looking for is given. The configuration is done in line 46. Just include the game names you are looking for.

**Comment by Haevn107** [comment]
Thank you so much!
