### ISSUE TITLE
Pickit error 

### ISSUE THREAD

**Issue by ljh93** [kolton/d2bot-with-kolbot#2254]
Pickit error! Line # 178 Entry: 
([name] == berserkeraxe || [name] == warspike || [name] == gloriousaxe || [name] == championaxe) && [quality] == superior # [enhanceddamage] == 15 && [tohit] == 3 && ([sockets] >= 4 || [sockets] == 0]) 
(kolton.nip) Error message: missing ) in parenthetical Trigger item:

where  missing ) ?

**Comment by ARkaine2** [comment]
"]" before ")" at the end.

**Comment by ljh93** [comment]
Thx kkk
