### ISSUE TITLE
bo

### ISSUE THREAD

**Issue by anime143** [kolton/d2bot-with-kolbot#2266]
bo barb script question. this may sound silly but is there a bo script similar to enchant.js beside battleorder. 

ex: barb will join the game and idle in town until the player (has to be in party) said the command "bo", the barb will then go to the default waypoint that is assigned and bo. 

reason why im asking is that i want an enchant and bo game at the same time.

**Comment by jmichelsen** [comment]
there isn't a script for it, but it would be simple enough to modify the current BO script or create a new one to do such a thing. Best to start with modeling after the Enchant.js, but for a BO barb. Do similar things, accept "commands", cast the right skills, etc. Let me know if you need more help.

**Comment by gtoilet** [comment]
I made this can add more eod if you need 

https://pastebin.com/s3RXAqKZ
