### ISSUE TITLE
Change amount of TP/ID scrolls in tomes(s) to go to buy TP/ID scrolls

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2268]
Is it possible?
In town Town.js I found part of code that probably answering for buying keys:

```
	wantKeys: function () {
		return this.checkKeys() <= 1;
	},
```

I'd wish to change amount of TP/ID scrolls in tome(s) when bot goes to buy TP/ID scrolls to fill tome(s).

This part of code payed my attention :
```
		// Avoid unnecessary NPC visits
		for (i = 0; i < list.length; i += 1) {
			// Only unid items or sellable junk (low level) should trigger a NPC visit
			if ((!list[i].getFlag(0x10) || Config.LowGold > 0) && ([-1, 4].indexOf(Pickit.checkItem(list[i]).result) > -1 || (!list[i].getFlag(0x10) && Item.hasTier(list[i])))) {
				break;
			}
		}
```

There's also such part of code in Town.js:

```
		if (this.checkScrolls(code) >= 13) {
			return true;
		}
```

But seems that changing of this value doesn't affect anything.
I tried to change it to <= 5 and bot even with 9 scrolls went to nearest NPC and filled tome and sent message:
initNPC: fillTome

How to change amount of scrolls in tomes and minimize unnecessary NPC visits in town?

**Comment by gtoilet** [comment]
Put scrolls in nip grab them on the go

**Comment by ARkaine2** [comment]
gtoilet,
Already done it.
And I'd wish to forget about visiting NPC for buying scrolls except the situations when all scrolls will end or when certain amount of scrolls will left (let's say it will be 1 scroll).

**Comment by Fa-b** [comment]
Just an assumption.. changing the expression from ‚>=13’ to ‚<=5’ will make it buy scrolls UNTIL there are less than 5 :p 
Better change your logic and see if it helps.
