### ISSUE TITLE
Chaos Sanctuary

### ISSUE THREAD

**Issue by don9395** [kolton/d2bot-with-kolbot#2285]
First off allow me to apologize if this has been address before, I could not find it in my searches. 
 I find that my sorc runs into the sanctuary and opens the seals before clearing the area. I have a clear all script however it does not prevent her from opening the seals. She then struggles with trying to clear the sanctuary. 

 You can see the clearanyarea is for the sanctuary but how do I get her to clear, open one seal, clear, open second seal....

 I already tried using "fastdiablo" in lieu of just "diablo". It really doesn't matter all that much since she does eventually win out, I am just curious as this whole bot thing really intrigues me. Thanks

	Scripts.ClearAnyArea = true; // Clear act 4 Pand Fortress, Outter Steps, Chaos Sanctuary. Uses Config.ClearType to determine which type of monsters to kill.
		Config.ClearAnyArea.AreaList = [108]; // List of area ids to clear. See sdk/areas.txt	
	Scripts.FastDiablo = false;
	Scripts.Diablo = true;
		Config.Diablo.WalkClear = false; // Disable teleport while clearing to protect leechers
		Config.Diablo.Entrance = true; // Start from entrance
		Config.Diablo.SealWarning = "Leave the seals alone!";
		Config.Diablo.EntranceTP = "Entrance TP up";
		Config.Diablo.StarTP = "Star TP up";
		Config.Diablo.DiabloMsg = "Diablo";
	Scripts.SealLeader = false; // Clear a safe spot around seals and invite leechers in. Leechers should run SealLeecher script. Don't run with Diablo or FastDiablo.

**Comment by anime143** [comment]
Scripts.ClearAnyArea = false;

diablo script alone does the clearing

**Comment by don9395** [comment]
Thanks, I was trying to dig through the various logic items to see if that were the case.
