### ISSUE TITLE
Downloaded Kolbot again with updates and now Mfhelper wont change acts

### ISSUE THREAD

**Issue by casualBotter** [kolton/d2bot-with-kolbot#2288]
I re-downloaded kolbot and now my Mfhelper wont change acts. The code is there I looked in misc.js and Mfhelper and it has the code but it wont work. My helper partys then stays in the act he initiated from. If a portal goes up in the act hes in he'll take it and start helping but he wont change acts so please help

**Comment by mf022** [comment]
there is a pending pull-request https://github.com/blizzhackers/kolbot/pull/28/files

**Comment by casualBotter** [comment]
so I actually fixed it my putting the functions getplayeract and find player back in mfhelper like it used to be and now it works

**Comment by mf022** [comment]
sorry for that. 
Misc.getPlayerAct function was fixed for MFHelper and Follower.js
https://github.com/blizzhackers/kolbot/commit/a8f4904969533ce6fb4c3fb0aeecf681410505f3
