### ISSUE TITLE
Clearing The Pit Issue

### ISSUE THREAD

**Issue by carleys45** [kolton/d2bot-with-kolbot#2319]
EDITED. Might have found something look at the end please
EDITED #2. Updated Attack.Js with the one i found on GitHub. evrything works fine.

I Have set up A Cbaal run Leader with an attacker helper. I added a third follower that is mainly doing Mf runs while Leader and Follower1 are clearing the Cbaal. Everything works fine with the 3 characters except the Mf runner. The issue is that it enter the pit level 1, says break clearing in pit level1 Overhead, rush to level2 says break the clearing in pit level 2 and then just go back to town to move on with other scripts. No error messages in the console. 
Here is the part for Act1 scripts in my character configs

// *** act 1 ***
	Scripts.Corpsefire = false;
		Config.Corpsefire.ClearDen = false;
	Scripts.Mausoleum = false;
		Config.Mausoleum.KillBloodRaven = false;
		Config.Mausoleum.ClearCrypt = false;
	Scripts.Rakanishu = false;
		Config.Rakanishu.KillGriswold = true;
	Scripts.UndergroundPassage = false;
	Scripts.Coldcrow = false;
	Scripts.Tristram = false;
		Config.Tristram.WalkClear = false; // Disable teleport while clearing to protect leechers
		Config.Tristram.PortalLeech = false; // Set to true to open a portal for leechers.
	Scripts.Pit = true;
		Config.Pit.ClearPit1 = true;
	Scripts.Treehead = false;
	Scripts.Smith = false;
	Scripts.BoneAsh = false;
	Scripts.Countess = true;
		Config.Countess.KillGhosts = false;
	Scripts.Andariel = true;
	Scripts.Cows = false;

Here are the configs in the pit.js 

*	@filename	Pit.js
*	@author		kolton
*	@desc		clear Pit
*/

function Pit() {
	Town.doChores();
	Pather.useWaypoint(6);
	Precast.doPrecast(true);

	if (!Pather.moveToExit([7, 12], true)) {
		throw new Error("Failed to move to Pit level 1");
	}

	if (Config.Pit.ClearPit1) {
		Attack.clearLevel(Config.ClearType);
	}

	if (!Pather.moveToExit(16, true, Config.Pit.ClearPath)) {
		throw new Error("Failed to move to Pit level 2");
	}

	Attack.clearLevel();

	return true;
}

It used to work just fine i don't know what happened for it to stop clearing the pit :(.
Any help would be greatly appreciated ! 
Thanks.

EDIT. 
Found this in the attack.js file but i don't know what to do with it in order to avoid leave the pit.

			if (Config.MFHelper && Config.MFHelper.BreakClearLevel && Config.Leader !== "") {
				var leader = Misc.findPlayer(Config.Leader);

				if (leader.area !== me.area && (!leader.inTown || Misc.getPlayerAct(Config.Leader) !== me.act)) {
					me.overhead("Break the Clearing " + getArea().name);
					return true;
				}
			}

**Comment by tejano89** [comment]
Hi my friends. U need put name leader on line js.901. Beetwen " ". Regards
