### ISSUE TITLE
Chestmania before Clear.

### ISSUE THREAD

**Issue by adamveg** [kolton/d2bot-with-kolbot#2320]
Hi.
Is there a way to set bot to do chestmania on very beginning, before everything else ?

**Comment by carleys45** [comment]
Hi not 100% sure but since scripts order is top to bottom did you tried to move chestmania on top of Act1 in the config ? Really not sure of that but worth a try !

**Comment by WiZzMaN47** [comment]
👍👁👁👍

**Comment by adamveg** [comment]
> 
> 
> Hi not 100% sure but since scripts order is top to bottom did you tried to move chestmania on top of Act1 in the config ? Really not sure of that but worth a try !

That's right my dude, thanks! :)
