### ISSUE TITLE
MF Helper doesn't quit game when Leader chicken

### ISSUE THREAD

**Issue by alz512** [kolton/d2bot-with-kolbot#2333]
Hi, I was wondering if there was any way for the Helper to quit the game if the leader chicken, or quit the game because of
Config.Baal.SoulQuit = true; // End script if Souls (Burning Souls) are found.
Config.Baal.DollQuit = true; // End script if Dolls (Undead Soul Killers) are found.
When the leader does, the helper just stays in game until an error like that appears.
Error in BaalHelper (baalhelper.js #243) Player wait timed out (No leader portals found)

**Comment by GodsHand86** [comment]
Go through your character config again.

**Comment by Bcubrich** [comment]
In the profile of your follow (like the script where you normally say what areas to run and so on, the one that gets  made when you first run the bot) change this code around line 134. Specifically the line where it is "Config.QuitList", you need to but you learder bot characters name. 

`Config.Leader = "NameOFLeader"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)`
`Config.QuitList = ["NameOfLeader"]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];`

Also, good idea to make the leader the most tank character. I run a Metorb Sorc in full tals as the leader and a glass cannon light sorc as backup. The light sorc is week but I have her stand far away with this for follower light sorc

`Config.Dodge = true; // Move away from monsters that get too close. Don't use with short-ranged attacks like Poison Dagger.
Config.DodgeRange = 18; // Distance to keep from monsters.
Config.DodgeHP = 100; // Dodge only if HP percent is less than or equal to Config.DodgeHP. 100 = always dodge. `

and this for my leader metorb sorc

`Config.Dodge = true; // Move away from monsters that get too close. Don't use with short-ranged attacks like Poison Dagger.
Config.DodgeRange = 12; // Distance to keep from monsters.
Config.DodgeHP = 90; // Dodge only if HP percent is less than or equal to Config.DodgeHP. 100 = always dodge.`

This way when my leader is unhurt she stand closer to monsters and she only gets far away when she starts to take damage, whereas the follower is always teleporting away from danger and attacking when she can.

**Comment by alz512** [comment]
> In the profile of your follow (like the script where you normally say what areas to run and so on, the one that gets made when you first run the bot) change this code around line 134. Specifically the line where it is "Config.QuitList", you need to but you learder bot characters name.
> 
> `Config.Leader = "NameOFLeader"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)`
> `Config.QuitList = ["NameOfLeader"]; // List of character names to quit with. `
> 
> Also, good idea to make the leader the most tank character. I run a Metorb Sorc in full tals as the leader and a glass cannon light sorc as backup. The light sorc is week but I have her stand far away with this for follower light sorc
> 
> `Config.Dodge = true; // Move away from monsters that get too close. Don't use with short-ranged attacks like Poison Dagger.`
> `Config.DodgeRange = 18; // Distance to keep from monsters.`
> `Config.DodgeHP = 100; // Dodge only if HP percent is less than or equal to Config.DodgeHP.`
> 
> and this for my leader metorb sorc
> 
> `Config.Dodge = true; // Move away from monsters that get too close. Don't use with short-ranged attacks like Poison Dagger.`
> `Config.DodgeRange = 12; // Distance to keep from monsters.`
> `Config.DodgeHP = 90; // Dodge only if HP percent is less than or equal to Config.DodgeHP.`
> 
> This way when my leader is unhurt she stand closer to monsters and she only gets far away when she starts to take damage, whereas the follower is always teleporting away from danger and attacking when she can.

thanks amazing!!!
