### ISSUE TITLE
Cast Charged Bolt Before Baal Throne Waves

### ISSUE THREAD

**Issue by Bcubrich** [kolton/d2bot-with-kolbot#2336]
Right now my lightning sorcess precasts CL before the baal waves, but a lot of the time they spawn to the side of where she is aiming. It would do more damage if there was a field of charged bolts covering the ground. Is there a simple way to set this up?

**Comment by DarkHorseDre** [comment]
what do you have set for your preattack skill?

**Comment by Bcubrich** [comment]
This totally works! Thanks!
