### ISSUE TITLE
Text in game issues

### ISSUE THREAD

**Issue by theeomen** [kolton/d2bot-with-kolbot#2341]
How would you add text to beginning of game .Like when running text in chaos or baal for instance?

**Comment by DarkHorseDre** [comment]
Just look at the baal/cs scritps - you know what the bot says everyrun so you look for that text.
e.g.
```js
say("Souls found! NG.");
```

**Comment by theeomen** [comment]
> Just look at the baal/cs scritps - you know what the bot says everyrun so you look for that text.
> e.g.
> 
> ```js
> say("Souls found! NG.");
> ```

Yeah that's to easy but let's say I run Andy for instance. How would I get them to text at that when it doesn't have a option to add text like cs/baal scripts

**Comment by DarkHorseDre** [comment]
Like I said - look at the Baal and CS scripts - You put it directly in the script.

If you're trying to ask how to make a config parameter to put in the character config file, add it to config.js, and your character file, just like all the other entries

**Comment by theeomen** [comment]
> Like I said - look at the Baal and CS scripts - You put it directly in the script.
> 
> If you're trying to ask how to make a config parameter to put in the character config file, add it to config.js, and your character file, just like all the other entries

Exactly what I was thinking.  Thanks for the help
