### ISSUE TITLE
5% Chance To Cast Level 14-20 Chain Lightning On Attack

### ISSUE THREAD

**Issue by magicfsih** [kolton/d2bot-with-kolbot#2348]
LightsabrePhase Blade | One-Hand Damage: (87-103) To (117-135) (102-119 Avg)
Required Level: 58Required Strength: 25Required Dexterity: 136Base Weapon Speed: [-30]+150-200% Enhanced Damage (varies)Adds 10-30 DamageAdds 60-120 Magic DamageAdds 1-200 Lightning Damage5-7% Mana Stolen Per Hit (varies)

5% Chance To Cast Level 14-20 Chain Lightning On Attack (varies)

20% Increased Attack SpeedIgnore Target's DefenseLightning Absorb 25%+7 To Light Radius(Only Spawns In Patch 1.10 or later)
-- | --

How to pick those with  20 Level  Chain Lightning  using the pickit  ?

**Comment by DarkHorseDre** [comment]
I think you specify the skill with: `itemskillonhit`
and the level with `itemskillonhitlevel` - let me know if that doesnt work

**Comment by magicfsih** [comment]
itemskillonhitlevel is undefined in my script.

**Comment by magicfsih** [comment]
> I think you specify the skill with: `itemskillonhit`
> and the level with `itemskillonhitlevel` - let me know if that doesnt work

And I do not found itemskillonhitlevel in itemalias.dbl

**Comment by DarkHorseDre** [comment]
It's in NTItemAlias.  Did you get the error from the bot or nip checker?

upon reflection the item states "on attack" so needs to be the equivalent names but with attack.

I tested it in sp and it works.

[Name] == phaseblade && [Quality] == Unique # [lightmindam] >=1 && ([itemskillonattack] == 53 && [itemskillonattacklevel] >= 20)

**Comment by magicfsih** [comment]
> It's in NTItemAlias. Did you get the error from the bot or nip checker?
> 
> upon reflection the item states "on attack" so needs to be the equivalent names but with attack.
> 
> I tested it in sp and it works.
> 
> [Name] == phaseblade && [Quality] == Unique # [lightmindam] >=1 && ([itemskillonattack] == 53 && [itemskillonattacklevel] == 20)

Thank you.
I found  [itemskillonattack]  in my kolbot but have not found [itemskillonattacklevel]  (older version)
I am now migrating my own script to the latest version
Let me test and  I am 90% sure it will work  at the first glance.

**Comment by magicfsih** [comment]
confirm it's working today
