### ISSUE TITLE
Character viewer not showing items pickup location

### ISSUE THREAD

**Issue by sunace** [kolton/d2bot-with-kolbot#236]
Cant seem to figure out where to look to find where I found an item say a ohm rune when I look at the character viewer it only shows a screen shot of the item but not actually where it was picked up like if pickits not loging the items location? all my friends d2bot tells them where they found the items at say worldstone 3, cow level, etc at the bottom of the screen shot but mine only shows the characters name and account name no actual location

also a side note my d2bot has all its buttons going vertically on the left side but my friends and all the screen shots I've seen online have the buttons (add profile, stop, start, etc) horizontally along the top anyone know why that is?

**Comment by Legless** [comment]
Manager shows area/pickit line only at 'Item Viewer' tab, not on 'Char Viewer'.

![mkfvaop](https://user-images.githubusercontent.com/2097587/28651101-68621456-7288-11e7-8986-48383706ac02.png)

**Comment by sunace** [comment]
thank you for the response! but for some reason I don't have that tab I only have 3 console char viewer and key wizard is all no actual item viewer tab do you know why that is?

**Comment by sunace** [comment]
![untitled](https://user-images.githubusercontent.com/30479095/28690734-87fb571a-72d7-11e7-9467-66aa2c477315.png)
this is what my d2bot looks like

**Comment by sunace** [comment]
This is what I see on my d2bot

![untitled](https://user-images.githubusercontent.com/30479095/28690828-d592c1d4-72d7-11e7-97af-08906bf7fbcb.png)
