### ISSUE TITLE
autosmurf ( my char stay in the town and write "i am not assigned a role in my config file"

### ISSUE THREAD

**Issue by periamodely** [kolton/d2bot-with-kolbot#2362]
**hi,
anyone help me plz,
its a scripts my leaders**

	Scripts.AutoSmurf = true;
		Config.AutoSmurf.TeamSize = 2;
		Config.AutoSmurf.TeleportingSorc = "light"; // your leader sorceress charname.
		Config.AutoSmurf.BoBarb = ""; // boBarb charname
		Config.AutoSmurf.OtherChars = ["Hammer"]; // all team charnames, excluding the leader and boBarb
		Config.AutoSmurf.AllTeamProfiles = ["As1","As2"]; // the whole team PROFILE names

**Comment by periamodely** [comment]
Hi. 
I read. The tuto. But. Change the name.  The leader not move and write the problems leader.  
I don t understand.  
😢😢😢

**Comment by periamodely** [comment]
I found the problem.

**Comment by gaterx** [comment]
whats the problem ?

**Comment by HybridGryphon** [comment]
hi periamodely I have the same issue pop up can you help me out
