### ISSUE TITLE
Lead bot stalling

### ISSUE THREAD

**Issue by AntG27** [kolton/d2bot-with-kolbot#2374]
Hi I've tried doing rakanishu runs only on hell single player with 1 lead bot(cold sorc lvl60) Since I barely managed to get to hell and everything seems to just oneshot me with my bad gear. So I was thinking about running a bot with something easy like rakanishu to get some xp and some gear. 
My issue is after finishing rakanishu the bot returns to base and starts stalling for 40 secons. Is there a way to decrease that time? I was looking through some of the files and found something like mingame lenght so I thought that's the issue but when I decreased that number it didn't help and now I'm clueless.

**Comment by DarkHorseDre** [comment]
mingametime is set in your char config and entry scripts (e.g. D2BotLead.dbj)

just ensure you change it back for bnet, or you add a check for SP vs bnet

**Comment by AntG27** [comment]
I've changed it in botlead previously now I've changed it in the char config as well and it works thanks
