### ISSUE TITLE
Bot says "Break the clearing in Ancient Tunnels"

### ISSUE THREAD

**Issue by gangstano** [kolton/d2bot-with-kolbot#2375]
When my sorc enters Ancient Tunnels she immediately says "Break the clearing in Ancient Tunnels" and goes onto the next script...

Any idea what's wrong?

I run her as a follow for my hammerdin, they do different things before going for dia and baal runs together. The only problem I have is this.

**Comment by DarkHorseDre** [comment]
sounds strange - download a new AT script?

**Comment by gangstano** [comment]
Alright tried that but nothing changed.

**Comment by 5noop** [comment]
This should be fixed soon but meanwhile check https://d2bot.discourse.group/t/break-the-clearing/614

**Comment by gangstano** [comment]
Thanks 5noop thats the information I needed!

Adding "Config.MFHelper.BreakClearLevel = false;" to my sorc config solved this problem.
