### ISSUE TITLE
Hotkey for mulelogger in manual profile

### ISSUE THREAD

**Issue by IronMaXxX** [kolton/d2bot-with-kolbot#238]
Hey guys, is there any way to log mules in manual created games using the D2BotMap or D2BotBlank entryscript with an hotkey (for example key "L")?
Is there any way to include this hotkey to the mentioned entries or to call the MuleLogger script with an specific hotkey?

Would be nice to log mules this way, so I don't have to change everything in MuleLogger.js and run the same char with another profile. Deleting items in the Char Viewer is a bit circumstancial if I muled a lot of keys or something else.

Maybe someone can spoon-feed me how this could be done, I'am unable to figure which code really logs the mule and how code can be executed by pressing a hotkey.

Thanks in advance!

**Comment by Legless** [comment]
> which code really logs the mule
MuleLogger.logChar( )  [MuleLogger.js at line 269](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/MuleLogger.js#L269).

> how code can be executed by pressing a hotkey.
Add to [UserAddon](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/bots/UserAddon.js#L18) something like: 

```
case 76: // 'L'
MuleLogger.logChar();
break;
```

And to [D2BotMap](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/D2BotMap.dbj) at line 4 (if you use it as starter script):
```
include("MuleLogger.js");
```

I didn't tested, so probably this wont work, but if you're familiar with js, you should easy fix this.

**Comment by IronMaXxX** [comment]
Thank for your reply Legless!
I tried what you told me but nothing happens.

I think UserAddon isn't loaded whilst using  D2BotMap or am I wrong?
So I tried to add the code to D2BotMap but nothing happens, no files are created, no logs are written, nothing happens.
```
this.keyEvent = function (key) {switch (key) 
{case 76: // 'L'
MuleLogger.logChar();
}
};
```
I also tried to add the following code after the first codesnippet in D2BotMap.js without any result
```
addEventListener("keyup", this.keyEvent);
```

Thanks for your effort Legless

**Comment by LeMule** [comment]
I might have some time on my hands over the weekend, I'll have a look and
get back to you.
Please reply back if you've figured it out so I'm not wasting time helping
someone who doesn't need help anymore :)

As Legless said, familiarity with javascript should be all you need to
figure out any quirks with his solution, and you've at least shown you can
look at the code and not start crying.
Don't give up. It's just code.

**Comment by Legless** [comment]
I digged the code.

Sorry, I'm retarded, there's [already a code](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/tools/ToolsThread.js#L374) to log mules. 

Just press Numpad6 while ingame.

**Comment by IronMaXxX** [comment]
Thanks Legless and LeMule for your support, sometimes I can't see the easy things :)
I close this Issue, thanks again!
