### ISSUE TITLE
Issue with monsters showing on MH when playing manually with UserAddon.js

### ISSUE THREAD

**Issue by Diabloplayer222** [kolton/d2bot-with-kolbot#2383]
So im playing manually and wanted to see other ppl's gear + use pickit + MH.
Entry script is D2BotBlank, and im playing with UserAddon script.

F12 reveals map but i dont see monsters like i see when playing with D2BotMap entry script, any idea to solve this?

If i use D2BotMap as entry script, UserAddon.js doesnt load.

So TLDR;
How to see monsters on map when playing with D2BotBlank, F12 reveals map but no arrow locations to next lvls etc + doenst show monsters on it

Also bonus question:
Is there any way to disable/enable pickit with hotkey command when playing manually?

Ty in advance.

**Comment by DarkHorseDre** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/923

**Comment by Diabloplayer222** [comment]
> #923

Yes i have read that issue also, but it doesnt really give solution.
I have tried all ways but if i play with Manual.js i cant get auto pickit work, and if i play with Useraddon.js i see monsters / numpad commands on MH.

**Comment by DarkHorseDre** [comment]
i'm sure this has been raised a few times and maybe solved - have you searched open and closed issues?

**Comment by 5noop** [comment]
> Yes i have read that issue also, but it doesnt really give solution.

It does https://github.com/kolton/d2bot-with-kolbot/issues/923#issuecomment-488791966

**Comment by Diabloplayer222** [comment]
> > Yes i have read that issue also, but it doesnt really give solution.
> 
> It does [#923 (comment)](https://github.com/kolton/d2bot-with-kolbot/issues/923#issuecomment-488791966)

I could swear i tried that already, but looks i messed smth up or forgot to save lol..

Works fine, thanks buddy! Now just i need to set new hotkeys for moving to next areas since i am mostly playing from laptop so numpad commands arent so good for me. Lets see if i can figure it out.
