### ISSUE TITLE
Kolton bot issue

### ISSUE THREAD

**Issue by Raistlin1986** [kolton/d2bot-with-kolbot#2384]
I keep getting errors in the console:

Failed to create game...

it repeats 10-20 times sometimes in a row...

then it will join a game and work fine for a little bit...

then eventually start up again
![d2issue](https://user-images.githubusercontent.com/63376373/78840146-01de7e00-79c8-11ea-865d-b0a50ecf4c45.png)

**Comment by Raistlin1986** [comment]
if you notice 18:24:27

it created a game and worked...

after that it started it again

**Comment by DarkHorseDre** [comment]
What does the game screen show? are you waiting in line?
does that status line say "waiting in line" or?

**Comment by Raistlin1986** [comment]
yeah. but I increased the "wait in line time" from 60-300...

and I still get ftj after it counts down sometimes...
