### ISSUE TITLE
RE: Clearing issues

### ISSUE THREAD

**Issue by coma42690** [kolton/d2bot-with-kolbot#2385]
Hello, I have just started to run the program and it is working great for Blood Raven, Andariel and Mephisto. However, I am trying to get it to clear the Pit, Countess, and Mausoleum. The bot teleports to these areas but kills nothing and leaves, including countess.. I have telestomp on, which should allow the countess to be killed.

As far as the other areas not being cleared, I have tried a number of things including changing the following lines:
	Scripts.Mausoleum = true;
		Config.Mausoleum.KillBloodRaven = true;
		Config.Mausoleum.ClearCrypt = true;
		Config.Mausoleum.ClearType = 0x7;
	Scripts.Pit = true;
		Config.Pit.ClearPit1 = true;
	Scripts.Countess = true;

Scripts.ClearAnyArea = true; // Clear any area. Uses Config.ClearType to determine which type of monsters to kill.
Config.ClearAnyArea.AreaList = [12, 16, 18, 19 ]; // List of area ids to clear. See sdk/areas.txt

	Config.ClearType = 0x7; // Monster spectype to kill in level clear scripts (ie. Mausoleum). 0xF = skip normal, 0x7 = champions/bosses, 0 = all
	Config.TeleStomp = true; // Use merc to attack bosses if they're immune to attacks, but not to physical damage

I cannot see what I am doing wrong. I have tried searching for an answer but nothing fixes or addresses this. I would be eternally grateful for some assistance! Ty.

**Comment by DarkHorseDre** [comment]
what does the console screen say when this happens? (press the 'home' key)

please paste your complete config to pastebin.com or similar and paste the *link* here

**Comment by coma42690** [comment]
Hi, I ended up figuring it out last night, but thanks so much for your response. It turns out I had set the attack type for bosses but not the secondary attack for non-bosses, so the script was going into the areas but not knowing how to attack non-bosses, and leaving.
