### ISSUE TITLE
What's going on with my pickit?

### ISSUE THREAD

**Issue by Buttpickle** [kolton/d2bot-with-kolbot#2395]
Trying to get it to grab any pally shield that has 4 sockets or 0 so I can make a spirit or one with res for an exile and this is my error

Pickit error! Line # 577 Entry: [type] == auricshields && [quality] <= superior && [class] == elite # [fireresist] <= 45 && (sockets] == 0 || [sockets] == 3 || [sockets] == 4) (pickit.nip) Error message: missing ) in parenthetical Trigger item: Kurast Shield

also, trying to get a Monarch--this line must be wrong because I've been running two bots for days and it hasn't grabbed anything.

[name] == monarch && [quality] <= superior && [flag] != ethereal # [enhanceddefense] <= 15 && ([sockets] == 4 || [sockets] == 0)

Thanks for the help

**Comment by Buttpickle** [comment]
oof, I forgot the [ before the first socket on the pally shield pickit.. I changed that, lets hope that works.

Is the monarch line proper? I feel like I should have gotten a Monarch a long time ago.

**Comment by DarkHorseDre** [comment]
it looks ok - the ED <=15 is redundant (as 15 is max, so they will all be true) and also, monarchs with ED >0 are always superior.

depends on monster density/areas - farming certain areas more may help (eg. ancient tunnels, moomooland etc)

**Comment by Buttpickle** [comment]
Monarchs wont stop dropping now. I guess I just had some bad luck.. Thanks for your reply!
