### ISSUE TITLE
 follower river wp bo

### ISSUE THREAD

**Issue by PRO100Zloy** [kolton/d2bot-with-kolbot#2419]
have a little problem, my followers pick up Bo in river and then run in act1 and wait for a command there

	**Pather.useWaypoint(107, true); // catacombs**

what needs to be changed so that wait after BO in act4

**Comment by PRO100Zloy** [comment]
no one know? 

i use 1 and 2 commandos

**Comment by ckelly44** [comment]
You need to change this line, 89:

https://github.com/kolton/d2bot-with-kolbot/blob/c83eb038bf4d5c76670b4bdb662a536822048ac9/d2bs/kolbot/libs/bots/BattleOrders.js#L89[103 = The Pandemonium Fortress](url)

From the sdk/areas: 103 = The Pandemonium Fortress

**Comment by PRO100Zloy** [comment]
> You need to change this line, 89:
> 
> https://github.com/kolton/d2bot-with-kolbot/blob/c83eb038bf4d5c76670b4bdb662a536822048ac9/d2bs/kolbot/libs/bots/BattleOrders.js#L89
> 
> From the sdk/areas: 103 = The Pandemonium Fortress

ty its worki:)
