### ISSUE TITLE
Need help with gambling.js file, paying fg for solution

### ISSUE THREAD

**Issue by sasquach15** [kolton/d2bot-with-kolbot#2432]
Hey. Paying 1000fg for person who help me.

I set gambling.js script for my bots but it doesnt work the way i want.
I want setup like this:
> 8 characters join game
>7 goldfinders drop gold for gambler and start doing mf/eg run in this game
>1 gambler picks up the gold and go gamble
>repeat

And for now i got this:
>8 characters join game
>7 goldfinders drop gold AND LEAVE
>1 gambler picks up the gold and go gamble, when he spend all gold he's waiting for new gold but no new gold dropped becouse everybody left. 

Basically i want those 7 goldfinders to stay in same game and start their mf/eg run instead of leaving. 

I tried delete line 90 from gambling.js file

quit() 

But then goldfinders drop gold and just stay in game doing nothing. 

Im pretty sure solution is in the gambling.js file but i dont have enough knowledge. 

1000fg for person who help me with this, cheers

**Comment by DarkHorseDre** [comment]
Hey bro, whilst you wait for l33t help, I was thinking you are close to solving this anyway?

can you just call mf after drop?
```js
this.dropGold();
	DataFile.updateStats("gold");
	delay(5000);
	//quit();
	Town.doChores(); //do this before the mf run to minimise them going out of sync going to shops etc
	//do mf here - call clearanyarea or boss script for all 7 followers to do?
        //quit() here or just leave them to mf until leader quits (assuming you have followers quit when leader leaves)
```

**Comment by sasquach15** [comment]
ok, worked with

Town.doChores();

after dropping gold bot does all shop things (repairs/potions etc)
but what command do i have to write under:

Town.doChores();

to start mf run?

**Comment by DarkHorseDre** [comment]
any - depends on what you want them to do?

go off individually to do a set of bosses? or go to different areas each?
or run mfhelper? (then one will need to become config.leader)

add the line after doChores and they will all do it (and if you want them to do something different then it will need some more work)

**Comment by DarkHorseDre** [comment]
'aight he's got it going to a basic level but if anyone can help him polish it, would be awesome!

**Comment by gtoilet** [comment]
you cant just add more runs after gold droper?
or just remove the quit portion from the drop.js?

idk not seen script to really know

**Comment by gtoilet** [comment]
https://pastebin.com/Kms6NM2t

THIS DOESNT WORK YET
  but see something like that

im currently working on it since post

**Comment by sasquach15** [comment]
I did exactly what you said and it doesnt work for me

made new 'drop$.js' file
copied your pastebin
put it in bots folder

bot join game and go mf without dropping

**Comment by DarkHorseDre** [comment]
Nice GT
(btw I didn't take any payment - just looking to learn and help if I can 👼 )

**Comment by gtoilet** [comment]
@sasquach15 did you add scripts.drop$.js = true ... in char config?

**Comment by sasquach15** [comment]
i added Scripts.Drop$.js = true; in char config but still nothing.  got pastebin from gambling.js maybe?

**Comment by gtoilet** [comment]
yea i dont think i changed anything there ... i took from there
and made the script , are you running the newest version of bot?
heres the link to what my gambling.js is
https://pastebin.com/kKAh7DFq

**Comment by gtoilet** [comment]
did you get it working @sasquach15

**Comment by sasquach15** [comment]
> 
> 
> did you get it working @sasquach15

sadly none of your answers helped me, maybe i am not using the newest version of bot. anyway i found good balance with DarkHorseDre advices and help so i'll stay with it for now. Thanks a lot for your help

**Comment by gtoilet** [comment]
19.3.3.100 - manager
1.6.3 - in game

those are the versions i get and i have the DL from may a month 2 tops ago

**Comment by sasquach15** [comment]
> 
> 
> 19.3.3.100 - manager
> 1.6.3 - in game
> 
> those are the versions i get and i have the DL from maby a month 2 tops ago

i updated to 19.3.3.100 and it almost works. Last issue is:

bot goes to act 1, drops his current gold.
go to stash, picks up gold from stash and... stash it again instead of dropping. after that he just goes mf.

any ideas? we're close

**Comment by sasquach15** [comment]
actually it makes sense, this script lacks last command to drop gold


function Drop$() {	
		var goldReserve = 20000;
		
	
			Town.goToTown(1);
			Town.move("stash");

			while (me.getStat(14) + me.getStat(15)) {
				gold(me.getStat(14)); // drop current gold
				Town.openStash();

				if (me.getStat(15) <= me.getStat(12) * 1e4) { // check stashed gold vs max carrying capacity
					gold(me.getStat(15) - goldReserve, 4); // leave minGold in stash, pick the rest
				} else {
					gold(me.getStat(12) * 1e4, 4); // pick max carrying capacity
				}

				return false;
			}
			return false;
		}




your drop$.js is copied from gambling.js at the point where bot picks up all his gold and change game to drop it in another, so it doesnt have a command to drop after picking gold from stash.

could you add a command at the end where he drops gold after he picks it up from stash?

i tried multiple versions with adding new lines to script but all failed

**Comment by gtoilet** [comment]
i dont know what your doing wrong guy i literally ran that script it droped all gold but what i told it to save and then went to andy/dury/cs

and yes that was a rip from gamble.js so where it enables it as a standalone script to just drop coin for your gambler to come grab and keep going

if you need you can pm me TV digits and ill connect to you and see whats up

**Comment by sasquach15** [comment]
i believe it works for you but no idea why this isnt work for me. just spent 3 hours trying to figure it out but still the same - after joining game he drops current gold, go stash, pick max carrying capacity and stash it again or go mf with 940k gold so he cant pick up anything more at all.

are you sure there shouldnt be something like that in your drop$.js file?


		while (me.getStat(14) + me.getStat(15)) {
			gold(me.getStat(14)); // drop current gold
			Town.openStash();

			if (me.getStat(15) <= me.getStat(12) * 1e4) { // check stashed gold vs max carrying capacity
				gold(me.getStat(15) - goldReserve, 4); // leave minGold in stash, pick the rest
			} else {
				gold(me.getStat(12) * 1e4, 4); // pick max carrying capacity
                                <DROP GOLD COMMAND HERE>
			}

			return false;
		}
		return false;
	}

??

or maybe just leave that script and find a way to change <stashing gold> to <dropping gold in act 1>, becouse thats all about it basically
i dont know..

Might be hard to make it on tv, im barely at home lately at random time

do you have any ideas?

**Comment by gtoilet** [comment]
naw ill do a vid and recheck codes again will pm if i can find your error

**Comment by sasquach15** [comment]
> naw ill do a vid and recheck codes again will pm if i can find your error

Any progress?

**Comment by gtoilet** [comment]
> Any progress?

was never able to come up with your error unless i messed with code
i re-did script from gamble and is all good like said before dropped coin and went to next script
https://pastebin.com/Kms6NM2t
[url=https://imgur.com/qCesp78][img]http://i.imgur.com/qCesp78.mp4[/img][/url]

**Comment by sasquach15** [comment]
And heres what my bot doing with  exactly same code...

https://streamable.com/qd0fdw

As you can se he drops gold he carry, goes to stash to pick gold from stash and after few sec he stashes it again instead of dropping. 
After all he only drops what he is carrying which is 900k but 2.5 million still in stash.
I have no ideas what to do to work it your way

**Comment by sasquach15** [comment]
> > Any progress?
> 
> was never able to come up with your error unless i messed with code
> i re-did script from gamble and is all good like said before dropped coin and went to next script
> https://pastebin.com/Kms6NM2t
> https://imgur.com/qCesp78

And heres what my bot doing with exactly same code...

https://streamable.com/qd0fdw

As you can se he drops gold he carry, goes to stash to pick gold from stash and after few sec he stashes it again instead of dropping.
After all he only drops what he is carrying which is usually 900k but 2.5 unused million still in stash :/
I have no ideas what to do to work it your way

**Comment by DarkHorseDre** [comment]
> > Any progress?
> 
> was never able to come up with your error unless i messed with code
> i re-did script from gamble and is all good like said before dropped coin and went to next script
> https://pastebin.com/Kms6NM2t
> https://imgur.com/qCesp78

Does this line move gold from stash to inv?:
```js
gold(me.getStat(15) - goldReserve, 4); // leave minGold in stash, pick the rest
```
if so then I don't see a line that drops the gold (2nd drop) after that?

I assume another drop line is needed after the if and before the return?
```
gold(me.getStat(14)); // drop current gold
```

**Comment by sasquach15** [comment]
> > > Any progress?
> > 
> > 
> > was never able to come up with your error unless i messed with code
> > i re-did script from gamble and is all good like said before dropped coin and went to next script
> > https://pastebin.com/Kms6NM2t
> > https://imgur.com/qCesp78
> 
> Does this line move gold from stash to inv?:
> 
> ```js
> gold(me.getStat(15) - goldReserve, 4); // leave minGold in stash, pick the rest
> ```
> 
> if so then I don't see a line that drops the gold (2nd drop) after that?
> 
> I assume another drop line is needed after the if and before the return?
> 
> ```
> gold(me.getStat(14)); // drop current gold
> ```

I believe its blizzhackers.

Can you tell me where exactly put this line with another drop? Im trying to pu it anywhere between lines 19-21 but nothing changed

**Comment by DarkHorseDre** [comment]
I was asking as I'm not sure but ok, I dont have much time so I'll just paste it here - try this:
```js
function Drop$() {	
		var goldReserve = 20000;
 
 
			Town.goToTown(1);
			Town.move("stash");
 
			while (me.getStat(14) + me.getStat(15)) {
				gold(me.getStat(14)); // drop current gold
				Town.openStash();
 
				if (me.getStat(15) <= me.getStat(12) * 1e4) { // check stashed gold vs max carrying capacity
					gold(me.getStat(15) - goldReserve, 4); // leave minGold in stash, pick the rest
				} else {
					gold(me.getStat(12) * 1e4, 4); // pick max carrying capacity
				}
                                gold(me.getStat(14)); // drop current gold again
				return false;
			}
			return false;
		}
```

**Comment by sasquach15** [comment]
> I was asking as I'm not sure but ok, I dont have much time so I'll just paste it here - try this:
> 
> ```js
> function Drop$() {	
> 		var goldReserve = 20000;
>  
>  
> 			Town.goToTown(1);
> 			Town.move("stash");
>  
> 			while (me.getStat(14) + me.getStat(15)) {
> 				gold(me.getStat(14)); // drop current gold
> 				Town.openStash();
>  
> 				if (me.getStat(15) <= me.getStat(12) * 1e4) { // check stashed gold vs max carrying capacity
> 					gold(me.getStat(15) - goldReserve, 4); // leave minGold in stash, pick the rest
> 				} else {
> 					gold(me.getStat(12) * 1e4, 4); // pick max carrying capacity
> 				}
>                                 gold(me.getStat(14)); // drop current gold again
> 				return false;
> 			}
> 			return false;
> 		}
> ```

Sadly nothings changed

**Comment by sasquach15** [comment]
> 
> 
> any - depends on what you want them to do?
> 
> go off individually to do a set of bosses? or go to different areas each?
> or run mfhelper? (then one will need to become config.leader)
> 
> add the line after doChores and they will all do it (and if you want them to do something different then it will need some more work)

also this might be the way maybe?. the only bot who drops all gold is the one from gambling.js

line 35:   goldFinders: ["bot3"],

he drops all and go script stated few lines under:

`

		if (info && info.goldFinder) {
			for (i = 0; i < info.gambleGames.length; i += 1) {
				if (info.gambleGames[i] && me.gamename.match(info.gambleGames[i], "i")) {
					this.dropGold();
					DataFile.updateStats("gold");
					delay(5000);
					//quit();
					Town.doChores();
					print;
					Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
		Config.ChestMania.Act1 = [2,8,3,9,13,17,18,19,4,10,14,5,6,11,15,21,22,23,24,25,7,12,16,27,28,29,30,31,32,33,34,35,36,37]; // List of act 1 areas to open chests in
		Config.ChestMania.Act2 = [47,48,49,41,55,59,42,56,57,43,62,63,64,44,65,52,53,54,46,66,67,68,69,70,71,72]; // List of act 2 areas to open chests in
		Config.ChestMania.Act3 = []; // List of act 3 areas to open chests in
		Config.ChestMania.Act4 = []; // List of act 4 areas to open chests in
		Config.ChestMania.Act5 = []; // List of act 5 areas to open chests in`

but when i add another bot to line 35:

goldFinders: ["bot3", "bot4"],

then they both do same script and the thing i want is them to do separate things, for example bot1 doing chestmania act1, bot2 doing chestmania act2

that would solve the problem as much as Drop$.js with dropping all gold

**Comment by sasquach15** [comment]
Also DarkHorseDre and gtoilet pm me at jsp, i want to send you both 500fg. You both helped me. Maybe not 100% solved but still i can run decent setup with your help.

My jsp acc is sasax

Also I pay 3000fg for someone who can solve my issue at 100%

**Comment by gtoilet** [comment]
so now your trying to get them to do each their own act of chest mania or go kill monsters/bosses
then come back and drop gold

**Comment by sasquach15** [comment]
> so now your trying to get them to do each their own act of chest mania or go kill monsters/bosses
> then come back and drop gold

Yes, that was the idea from the beggining. My bots only collect gold and i want them to drop all on the ground every game for gamblers

**Comment by gtoilet** [comment]
that should be easy to set up
each run different scripts
return with drop$.js
repeat ...

if your still having problems with that .js i would like to teamview you see what your working with
would be alot easier to set up vs this back and forth

**Comment by sasquach15** [comment]
> that should be easy to set up
> each run different scripts
> return with drop$.js
> repeat ...
> 
> if your still having problems with that .js i would like to teamview you see what your working with
> would be alot easier to set up vs this back and forth

Sounds good. Are you Eu or Usa time zone?
I could share teamview screen tomorrow when im home. Tomorrow ok for you?

**Comment by gtoilet** [comment]
eastern time zone usa
my tomorrow is saturday would be fine
lmk what works for you as my today is friday 3:30am
and will be out of the house most all day

**Comment by sasquach15** [comment]
3.30am at night? If yes, then its 6hours later in my eu timezone. Can we do 10am saturday your time, so its 4pm my time?

**Comment by gtoilet** [comment]
i can try to be awake at that time ill let you know tonight if i think i will be around at that time

**Comment by sasquach15** [comment]
> i can try to be awake at that time ill let you know tonight if i think i will be around at that time

Ok, waiting for info

**Comment by DarkHorseDre** [comment]
> Also DarkHorseDre and gtoilet pm me at jsp, i want to send you both 500fg. You both helped me. Maybe not 100% solved but still i can run decent setup with your help.
> 
> My jsp acc is sasax
> 
> Also I pay 3000fg for someone who can solve my issue at 100%

ah i was going to write to say I've finally managed to setup tcpip games so could look at this stuff soon, but you beat me to it!

Thanks for the offer but I don't remember doing much at all - if GunitToilet doesn't get to finish it let me know

**Comment by gtoilet** [comment]
im about to head to bed its now my time 945pm friday
i should be awake before 10am my time saturday which should be your time 4pm

**Comment by sasquach15** [comment]
Ok, ill be waiting

**Comment by gtoilet** [comment]
post when your ready im awake now

**Comment by sasquach15** [comment]
> post when your ready im awake now

Will be ready in 30minutes. Got any discord maybe?

**Comment by sasquach15** [comment]
Ok im ready, my discord is sasax
Or if you dont have ill write teamwiever id here

**Comment by gtoilet** [comment]
pmd your jsp

**Comment by gtoilet** [comment]
@DarkHorseDre  issue has been taken care of
euro server was laggy or latency something to that effect
wouldnt drop like my video on east server did

solved issue , OP can close thread now

**Comment by DarkHorseDre** [comment]
Good work gangstatoilet xD

**Comment by sasquach15** [comment]
Thank you all for contribution
Problem solved
Topic can be closed
