### ISSUE TITLE
Talk Fara, getting it to scan for items as well

### ISSUE THREAD

**Issue by MoneyMoney33** [kolton/d2bot-with-kolbot#2442]
I am playing manual and my follower will not go to either Fara or Elzix.

My goal would be to say "Talk Fara" and he would not only talk, but scan for items. (This is my goal)  Even better if I can put an easier phrase like "t" and it will talk AND scan items from Fara and Elzix.

or is it possible to add to the town chores and have him go to Fara and Elzix to scan for items?

Any help would be greatly appreciated!

**Comment by DarkHorseDre** [comment]
I think you can just take code from follower/questing.js.  look at this;
```js
		Town.goToTown(); 
		Town.move(NPC.Atma); //goto NPC = atma (could be any)

		atma = getUnit(1, NPC.Atma);

		atma.openMenu(); //open her menu (in this example we do not interact or shop)
		me.cancel(); //close menu
```

in cows, shopping is initiated like:
```js
akara = Town.initNPC("Shop");
```
so in theory you could change the npc name and get the bot to access the target npc and access shop menu

to scan for items - usae build-in code. check your config for:
```js
Config.MiniShopBot = true; // Scan items in NPC shops.
```
everytime your bots visits a shop it scans for items in pickit..

**Comment by gtoilet** [comment]
we talk about it here also if any confusion from dre's comment

https://github.com/kolton/d2bot-with-kolbot/issues/1574

**Comment by MoneyMoney33** [comment]
I tried using this, even changed it to "faracheck" it keeps going to drognan.

Town.initNPC("Shop", "drogcheck");
Town.shopItems();
me.cancel();

**Comment by gtoilet** [comment]
dam going to try make me install lod to check your problem

will try with some classic guys now

**Comment by gtoilet** [comment]
dont know how to get it to TRADE elzix
can put "Gamble" and will go to elzix but idk if you want to scan his gamble or what

**Comment by MoneyMoney33** [comment]
Okay so I put this
	`	tasks: [
		{Heal: NPC.Akara, Shop: NPC.Akara, Trade: NPC.Gheed, Gamble: NPC.Gheed, Repair: NPC.Charsi, Merc: NPC.Kashya, Key: NPC.Akara, CainID: NPC.Cain},
		{Heal: NPC.Fara, Shop: NPC.Drognan, Trade: NPC.Elzix, Gamble: NPC.Elzix, Repair: NPC.Fara, Merc: NPC.Greiz, Key: NPC.Lysander, CainID: NPC.Cain},
		{Heal: NPC.Ormus, Shop: NPC.Ormus, Gamble: NPC.Alkor, Repair: NPC.Hratli, Merc: NPC.Asheara, Key: NPC.Hratli, CainID: NPC.Cain},
		{Heal: NPC.Jamella, Shop: NPC.Jamella, Gamble: NPC.Jamella, Repair: NPC.Halbu, Merc: NPC.Tyrael, Key: NPC.Jamella, CainID: NPC.Cain},
		{Heal: NPC.Malah, Shop: NPC.Malah, Gamble: NPC.Anya, Repair: NPC.Larzuk, Merc: NPC.Qual_Kehk, Key: NPC.Malah, CainID: NPC.Cain}
	],`


and then 

`			case "shop1":
			if (me.inTown) {
				Town.move(NPC.Gheed); //goto NPC = atma (could be any)
				Town.initNPC("Trade", "Elzix");
				Town.shopItems();
				me.cancel(); //close menu
				Town.move("portalspot");
			}`

but ya he isn't opening the trade menu :( so therefore no scanning items.

Maybe I put the < Trade: NPC.Elzix, > wrong? I just didn't see any <> on line 47, so I didn't think I should just throw it in? Maybe I am wrong.

**Comment by DarkHorseDre** [comment]
nice nice!

be careful about changing town.js - your bot could end up visiting non prefered npcs for certain `task`s, or somethint else?

You can also access menu's based upon the action without using town functions:
```js
Misc.useMenu(0x0D44); //trade
```
npc menu id codes are here:
https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/sdk/npcmenuid.txt

**Comment by MoneyMoney33** [comment]
> nice nice!
> 
> be careful about changing town.js - your bot could end up visiting non prefered npcs for certain `task`s, or somethint else?
> 
> You can also access menu's based upon the action without using town functions:
> 
> ```js
> Misc.useMenu(0x0D44); //trade
> ```
> 
> npc menu id codes are here:
> https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/sdk/npcmenuid.txt

OOOOO I just added this prior to townshop and it now works!!! For Elzix and Gheed!!! whoop

**Comment by gtoilet** [comment]
only thing i changed was

		{Heal: NPC.Fara, Shop: NPC.Drognan, Gamble: NPC.Elzix, Trade: NPC.Elzix, Repair: NPC.Fara, Merc: NPC.Greiz, Key: NPC.Lysander, CainID: NPC.Cain},



made my own script to run to make sure would click trade instead of gamble and it worked
i never tried to run any base script to make sure he would go there on his own i forced him to check Elzix

Town.initNPC("Trade", "Elzix");
Town.shopItems();
me.cancel();

**Comment by MoneyMoney33** [comment]
I did a run through all the way through normal and it worked very well. I will say I noticed I dropped more frequently which rarely happens, could have been coincidence, therefore I am going to put this as a Closed topic. Thank you to everyone who helped contribute.
