### ISSUE TITLE
how can bot hit evil urn?

### ISSUE THREAD

**Issue by tunz347** [kolton/d2bot-with-kolbot#2444]
Interested to know if my bot can hit evil urns and other monster spawning surfaces (if others exist)
thanks in advance.

> we talk about stuff in this thread and link to another thread in that thread
> 
> [#2182 (comment)](https://github.com/kolton/d2bot-with-kolbot/issues/2182#issuecomment-576190240)

thanks i'll check it out

**Comment by gtoilet** [comment]
we talk about stuff in this thread and link to another thread in that thread

https://github.com/kolton/d2bot-with-kolbot/issues/2182#issuecomment-576190240
