### ISSUE TITLE
bot glitches at nihlathak

### ISSUE THREAD

**Issue by tunz347** [kolton/d2bot-with-kolbot#2445]
After bot safely killed nihlathak, went to town to heal, but actually didn't heal but went back in the TP with low HP (in order to pick the loot)  and costs chicken at 70% of the cases (if not more), I consider this as glitch, because it doesn't happen in other scripts. Anyone able to edit the synchronization properly?
I must say that I was testing act V and its the glitchiest from all, scripts like frozen tundra are not able to even load...

/**
*	@filename	Nihlathak.js
*	@author		kolton
*	@desc		kill Nihlathak
*/

function Nihlathak() {
	Town.doChores();
	Pather.useWaypoint(123);
	Precast.doPrecast(false);

	if (!Pather.moveToExit(124, true)) {
		throw new Error("Failed to go to Nihlathak");
	}

	Pather.moveToPreset(me.area, 2, 462, 0, 0, false, true);

	if (Config.Nihlathak.ViperQuit && getUnit(1, 597)) {
		print("Tomb Vipers found.");

		return true;
	}

	Attack.kill(526); // Nihlathak
	Pickit.pickItems();

	return true;
}

**Comment by DarkHorseDre** [comment]
You could have a corruption or other issue with your files (just got 2 keys from nih, but sp)

quickest way is to download new zip of kolbot, unpack and copy your config and profiles.json + nip - start it and see if its the same?

**Comment by gtoilet** [comment]
what version of bs were you running was it an older copy or anything changed with any thing
