### ISSUE TITLE
how can use portal of tomb of Tal Rasha?

### ISSUE THREAD

**Issue by buie0906** [kolton/d2bot-with-kolbot#2459]
![portal](https://user-images.githubusercontent.com/24932888/80917769-23027680-8d9c-11ea-85e0-2e072457fcb7.jpg)

hello guys. thank you.
Im manual player.
that portal owner is Tyrael.
i used script `Pather.usePortal(null)`.
but  this not work. 
how can i this work?

**Comment by gtoilet** [comment]
Pather.usePortal(null)

maby that 2nd L was the fault?

**Comment by buie0906** [comment]
oh sorry.I wrote it wrong on the board.

**Comment by gtoilet** [comment]
Pather.usePortal(null) || Pather.usePortal(null, Config.Leader);

that is a copy from rushee.js its what tells you to take that exact portal for quest

**Comment by buie0906** [comment]
ok. thanks. I will try.

**Comment by buie0906** [comment]
oh thank you. It works very well.
