### ISSUE TITLE
What function opens the quest panel?

### ISSUE THREAD

**Issue by buie0906** [kolton/d2bot-with-kolbot#2461]
hello guys.  Thank you~!

**Comment by 5noop** [comment]
You could send the "q" key with `sendKey(81)`, but why do you need that ?

If you want to get some quest information it's probably easier to use packets.

**Comment by buie0906** [comment]
How do you use packets? 
Are you saying this? 'me.getQuest(x,x)'

**Comment by 5noop** [comment]
`me.getQuest` gives some information but not all, again it depends on what you are trying to do.

You can learn a bit about packets by reading a playing with this script https://raw.githubusercontent.com/blizzhackers/documentation/master/kolbot/custom-scripts/Manual.js
and here is a list https://docs.google.com/spreadsheets/d/1WBywvgwO7Yb6VW_0pQ6Ppr7eN6D33bcBONZ_1VUKzuo

**Comment by buie0906** [comment]
thank you! i'll try this.
