### ISSUE TITLE
Empty Schedule

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2464]
Can empty schedule be removed?

![image](https://user-images.githubusercontent.com/31447095/81025769-61716180-8e80-11ea-902e-8efc81268d71.png)

**Comment by DarkHorseDre** [comment]
If you cant delete in d2bs, try deleting the entry from schedule.json?

**Comment by ARkaine2** [comment]
Thanks.
Removing of file schedules.json fixed this problem.

**Comment by DarkHorseDre** [comment]
ah ok, I couldn't remember if you'd lose your data or not.  did you have to close manager (save) and reopen, or did schedule change immediately?
