### ISSUE TITLE
Chicken Delay

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2467]
Please, help.

I read all this (https://github.com/kolton/d2bot-with-kolbot/issues/1331) thread, but I can't make work QuitDelay and Config.QuitDelay.
I doesn't affect bot at all.

I understood that I should add
QuitDelay: [-1, 1, 15]
to config.js
(here's the first question: why are these values?)

Also I understood that I should add
Config.QuitDelay = [0, 4, 5];
to character config file.

I changed it to:
Config.QuitDelay = [0, 350, 360];
But bot simply lefts game and then without delay starts new game.
Is this really seconds?

I'm also not sure about when excatly this delay works: Before or after quit from game?

I need some function that will add delay after quit from game via chicken and that will work when bot in lobby or something like that, that will let to avoid realm down when multiple bots are running.

**Comment by gtoilet** [comment]
na ... get new DL from github everything is already impelemented and works

**Comment by ARkaine2** [comment]
> na ... get new DL from github everything is already impelemented and works
> 
> Config.QuitDelay = [0, 350, 360];
> 
> that would make the bot take 350 to 360 seconds to leave game after the first person left game

So this means that bot(s) in team MF game will wait "after the first person left game"?
But i'm interested in possibility to wait in lobby after chicken with single bot (bot runs with multiple characters separately).

**Comment by gtoilet** [comment]
you set that in their entry point as min game time
	MinGameTime: 180, // Minimum game length in seconds. If a game is ended too soon, the rest of the time is waited in the lobby

if they run each their own game then you run , d2botlead.dbj
or what ever entrypoint you use for them check there for min game time

**Comment by ARkaine2** [comment]
Thank you.
You fully clarified this moment to me.

My mistake was that:
I counted time from chicken and not from game start, as it shown in description.
