### ISSUE TITLE
My shopbot isn't stashing shopped items pls help

### ISSUE THREAD

**Issue by Divisi0ns** [kolton/d2bot-with-kolbot#2473]
My shopbot isn't stashing shopped items, how do I fix this!?? please help, maybe link me to proper shopbot.js if mine is wrong?
How do I fix mine, it's not stashing shopped items for me,  please lmk

[img]https://i.ibb.co/r0phRq0/20200506-221501.jpg[/img]

[img]https://i.ibb.co/Z19Y9yv/20200506-221545.jpg[/img]

[img]https://i.ibb.co/bLBYZKH/20200506-221638.jpg[/img]

**Comment by inherithandle** [comment]
```
/* Inventory lock configuration. !!!READ CAREFULLY!!!
	 * 0 = item is locked and won't be moved. If item occupies more than one slot, ALL of those slots must be set to 0 to lock it in place.
	 * Put 0s where your torch, annihilus and everything else you want to KEEP is.
	 * 1 = item is unlocked and will be dropped, stashed or sold.
	 * If you don't change the default values, the bot won't stash items.
	 */
	Config.Inventory[0] = [0,0,0,0,0,0,0,0,0,0];
	Config.Inventory[1] = [0,0,0,0,0,0,0,0,0,0];
	Config.Inventory[2] = [0,0,0,0,0,0,0,0,0,0];
	Config.Inventory[3] = [0,0,0,0,0,0,0,0,0,0];
```
read carefully comments around `Config.Invetory`. and then set some flags to 1. then your bot will stash picked items.

**Comment by gtoilet** [comment]
[img]https://i.ibb.co/r0phRq0/20200506-221501.jpg[/img]

you need to remove the   //

to enable the bot to get those items
