### ISSUE TITLE
TEAM MF: Make MFLeader quit game if MFHelper chickened from game

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2481]
Is it possible? And how to?

**Comment by faviod** [comment]
If im not mistaking all you have to do is set the MF Helpers character names here in the MFLeader's config

>	Config.QuitList = [""]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];
	Config.QuitListMode = 0; // 0 = use character names; 1 = use profile names (all profiles must run on the same computer).
	Config.QuitListDelay = []; // Quit the game with random delay in case of using Config.QuitList. Example: Config.QuitListDelay = [1, 10]; will exit with random delay between 1 and 10 seconds.

**Comment by ARkaine2** [comment]
Thanks. It works fine.
