### ISSUE TITLE
Specific iLvl pickit range

### ISSUE THREAD

**Issue by PickAUsernamez** [kolton/d2bot-with-kolbot#2490]
Is this correct if I want item with iLvl from range 26-39 picked?

[name] == item && [Quality] <= normal && ([Level] >= 26 || [Level] <= 39) # [sockets] == 0 //

**Comment by DarkHorseDre** [comment]
almost, you need it to be greater than 26 AND less than 39, not OR:

```js
([Level] >= 26 && [Level] <= 39)
```
