### ISSUE TITLE
Priority on Monsters when opening chests

### ISSUE THREAD

**Issue by Oschal** [kolton/d2bot-with-kolbot#2493]
Hi! I am running a very low paladin and programed him to open all chests he finds.
Now when he sees a chest his first priotity is to open it even if there are alot of monsters around it. this causes my low bot to die farely often.

Is there a way to first kill the monsters and then open the chests?

**Comment by DarkHorseDre** [comment]
short answer is you'd have to adjust pather.js to clear the area around the chest. but tbh you're better off not opening them when at low level/weak.

for example, I don't open chests until char level is >=3 and I have at least 1000 gold:
```js
Config.OpenChests = me.charlvl >= 3 && me.gold >= 1000;
```
but as I said, you could set different values, check resistances/life etc.

What difficulty is the bot on and what char level?

**Comment by Oschal** [comment]
Thank you for the answer. I also decided to not open chests now. My Char was Lvl 70 and was running Mausoleum and Catacombs, so i thought with all the chests it might be useful to open them. But i guess i am better of not opening them^^ But thank you very much!

**Comment by DarkHorseDre** [comment]
no probs - also the area makes a big difference - small compact areas like mausoleum, countess etc may be more difficult.

best thing is to run bosses and uniques until you have good gear to push.
also, you're better off with higher TC level chests, in the later acts (from act 3 IIRC)
