### ISSUE TITLE
how can i use charged skill in marrowwalk(lifetap)

### ISSUE THREAD

**Issue by joba1995** [kolton/d2bot-with-kolbot#2494]
I want to use charged skill in marrowwalk(lifetap) before attacking boss
In prototypes.js, just use me.castchargedskill(skillid,unit)

So, i paste this setence in paladin.js 53line
if (unit.classid === 242  && !unit.getState(58)) {
me.castChargedSkill(82, unit);
}

then, it works until going to mephisto(I tried it with mephisto)
but didn't use charged lifetap skills and have an error
Mephisto (prototypes.js line 1204):stats[204].filter is not a function

how can i solve this problem?
i want to use charged lifetap skill once before attacking boss

**Comment by ckelly44** [comment]
Share your prototypes.js file so we can have a look.

**Comment by joba1995** [comment]
> Share your prototypes.js file so we can have a look.


[prototypes.zip](https://github.com/kolton/d2bot-with-kolbot/files/4637837/prototypes.zip)

this is my prototypes.js and paladin.js
thank you ....

**Comment by ckelly44** [comment]
Okay, so it looks like you have a dated bot. The newest one is in the blizzhackers repo. It completely refactors the prototypes.js file. As a result, there were a ton of differences between your file and mine but in that block it looks like you never changed line 1187 to:
`if (this !== me && this.type !== 4) {`
I don't know if that would fix your error, but it's worth a shot.

**Comment by joba1995** [comment]
> Okay, so it looks like you have a dated bot. The newest one is in the blizzhackers repo. It completely refactors the prototypes.js file. As a result, there were a ton of differences between your file and mine but in that block it looks like you never changed line 1187 to:
> `if (this !== me && this.type !== 4) {`
> I don't know if that would fix your error, but it's worth a shot.

thank you for the reply
First, i already test this sentence and have a same error
if (this !== me && this.type !== 4) {
I read your comment before another issue and already try it :(

and I heard your answer and tried it just now...
change kolbot newest one in the blizzhackers repo, but have an another error
and change only prototypes.js and paladin.js
then, another function have error (like cubing ..)

So, I think if you ok, can you share your prototypes.js and paladin.js?
or It may be a little rude.... Sorry.. if you ok..,can you share your kolbot file all of them..?
I want to compare with my file and what's the problem

I'm Sorry to bother you :(

**Comment by ckelly44** [comment]
You did a fresh install with the new repo? Was the error the exact same?

**Comment by joba1995** [comment]
yeah, i install new repo, but have a another error

Error in Mephisto (attack.js #301) Failed to kill Mephisto

**Comment by ckelly44** [comment]
First, don't combine files from the separate repos. If you're using the new repo you should **not** change anything in the prototypes.js file. But you mentioned you did, which changes did you make?

> change kolbot newest one in the blizzhackers repo, but have an another error
and **change only prototypes.js** and paladin.js
then, another function have error (like cubing ..)

**Comment by joba1995** [comment]
No... when i combine files it had very many error...
So, I didn't do that

and when i install new file, i didn't touch anything
just put it this sentence in paladin.js
if (unit.classid === 242 && !unit.getState(58)) {
me.castChargedSkill(82, unit);
}

and prototypes.js had already changed like this
if (this !== me && this.type !== 4) {
So i didn't touch it
but... i have a same error : staats [204]filter is not a function
https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md
I used this link if i install new kolbot

Did I do something wrong?
