### ISSUE TITLE
Pickit Autoequip MaxQuantity

### ISSUE THREAD

**Issue by PickAUsernamez** [kolton/d2bot-with-kolbot#2508]
Need someone to explain why my bot keeps picking things when I have set MaxQuantity == 1 to the selected item... or am I doing that wrong somehow?

[type] == helm && [Flag] != ethereal && [quality] == normal ## [maxquantity] == 1 && [tier] == 1

Yet after it already has picked & equipped one it still picks up more. Cracked/Low Quality/Normal doesn't matter it will pick em and the line is always that. It's not the LowGold's line, but can that do it?

Can I use something like && me.charlvl to stop it from picking something past x level? Would that work?

EDIT: switched types to some names for all instances like this. I'll test it.

**Comment by PickAUsernamez** [comment]
Ok it seems to have stopped picking up the same crap unless it has better stats (like 1 def difference pfft whatever).

But another thing popped up. Autoequip won't equip better tiered items. Instead it stashes them. I have mostly just 1 tier stuff on all my slots and plenty of 2-3 tier items in my stash. Whats up with that?

**Comment by DarkHorseDre** [comment]
you have to set multiple tiers - maxquantity may not work as you do not have layered tiers.

you haeve said that tier 1 = normal helms (non eth)

you can use logic in autoequip and its awesome! e,g.
`me.charlvl >= 9 && [name] == ring && [Quality] <= magic`

as for 2nd post - I'm not sure if maxq is causing an issue as thats more for storing, not equipping.

try those 2 lines without maxq - afterall, it should only change tier 1 if it finds tier>1

**Comment by PickAUsernamez** [comment]
> 
> 
> you have to set multiple tiers - maxquantity may not work as you do not have layered tiers.
> 
> you haeve said that tier 1 = normal helms (non eth)
> 
> you can use logic in autoequip and its awesome! e,g.
> `me.charlvl >= 9 && [name] == ring && [Quality] <= magic`
> 
> as for 2nd post - I'm not sure if maxq is causing an issue as thats more for storing, not equipping.
> 
> try those 2 lines without maxq - afterall, it should only change tier 1 if it finds tier>1

Okay the pickit issue I have overcome, but autoequip still remains.
It picks up the tiered items fine, but doesnt remove the old items if they are lower tier.
Do I have some old file that doesn't support this? I think I downloaded all up-to-date files like a week ago.

Example:

line112 [type] == ring && [quality] == magic # [lightresist] >= 5 # [tier] == 1 
line113 [type] == ring && [quality] == magic # [fireresist] <= 17 || [lightresist] >= 18 # [tier] == 2

It picked up 4 rings from line 113, but didn't equip any of them. Instead it still have some ring of craftsmanships equipped (which are not on any line). It won't remove them.

**Comment by DarkHorseDre** [comment]
hmmm.. seems it thinks the ring is better than the 113 rings

pls paste your config and the contents of the referenced pickits to pastebin.com or similar, and enable the JS syntax highlighting (dont paste any of the content directly to this thread)

**Comment by PickAUsernamez** [comment]
> 
> 
> hmmm.. seems it thinks the ring is better than the 113 rings
> 
> pls paste your config and the contents of the referenced pickits to pastebin.com or similar, and enable the JS syntax highlighting (dont paste any of the content directly to this thread)

I'm gonna have to get back to you soon. Running some heavy testing tonight with different NIP's. Will let you know the results.

**Comment by DarkHorseDre** [comment]
np - bear in mind tiering can be dynamic - here is somethng to bake your noodle: yanked from sonic autoequip:
```js
me.charlvl >= 9 && [name] == ring && [Quality] <= magic 		# [itemchargedskill] >= 0 # [tier] == /*fr+cr+lr*/((item.getStatEx(39) + item.getStatEx(41) + item.getStatEx(43)) * 1000) + /*maxhp+maxmana*/((item.getStatEx(7) + item.getStatEx(9)) * 100) + /*str+dex*/((item.getStatEx(0) + item.getStatEx(2)) * 100) + /*fcr*/(item.getStatEx(105) * 1)
me.charlvl >= 9 && [name] == ring && [Quality] >= set 			# [itemchargedskill] >= 0 # [tier] == /*fr+cr+lr*/((item.getStatEx(39) + item.getStatEx(41) + item.getStatEx(43)) * 10000) + /*maxhp+maxmana*/((item.getStatEx(7) + item.getStatEx(9)) * 1000) + /*str+dex*/((item.getStatEx(0) + item.getStatEx(2)) * 1000) + /*fcr*/(item.getStatEx(105) * 10)
```

2 definitions for rings only, but all the stats are weighted so that the more specified stats are hit, the higher the tier, but defined within 1 line per item type!

**Comment by DarkHorseDre** [comment]
just ensure you've got it all setup properly and nips arent overlapping etc

**Comment by PickAUsernamez** [comment]
~~Ok some early white items found in act1 are still not going through the tier system. It just keeps the first it finds.
Anybody have any clue how I can make it pick up better white items in a tiered system?~~

EDIT: nvm found out I had some splice issue in my config. Now it works.
