### ISSUE TITLE
How to ID Rings & Amu

### ISSUE THREAD

**Issue by Sindanarie** [kolton/d2bot-with-kolbot#2509]
Hey, i cant seem to get Kolbot to id rings and amulets.

[name] == amulet && [quality] == unique

[name] == ring && [quality] == unique

what do i need to amend to make it ID these?

Thank you in advanced :D

**Comment by DarkHorseDre** [comment]
try:
`[name] == ring && [quality] == unique && [flag] == identified`

**Comment by Sindanarie** [comment]
Perfect - Thank you :D
