### ISSUE TITLE
Two questions about [maxquantity]

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2516]
First question (it's more theoretical) is probably simple, but I can't understand this moment.

From what does bot start counting [maxquantity]?

Let's say we have:
[name] == talrune # # [maxquantity] == 1
In pickit.

We also have 1 Tal rune in inventory.

Bot picked 1 Tal rune (as it specified with: "[maxquantity] == 1" in pickit).

So, now we have 2 Tal runes in inventory.

But **what triggers counting specified quantity?**

Let's say we restarted bot.

Now bot has 2 Tal runes in inventory.

Now bot will pick 1 more rune (as it specified with: "[maxquantity] == 1" in pickit).

And bot will have 3 Tal runes in inventory (if I'm not mistaken in logic of bot behaviour).

**Can it be prevented?**

..

And the second (very significant practical for me) question:

Can [maxquantity] work WITH multiple profiles?

Let's say I specified such pickit:
[name] == talrune # # [maxquantity] == 1
[name] == ortrune # # [maxquantity] == 1
[name] == thulrune # # [maxquantity] == 1
[name] == amnrune # # [maxquantity] == 1

And here's what I see:
![acsascascacsacsacs](https://user-images.githubusercontent.com/31447095/82825997-f3372200-9eb4-11ea-8160-38507e211b9c.png)

3 Ort runes, 2 Tal runes etc between multiple profiles.

Can pickit be limited to specified [maxquantity] between multiple profiles?

**Comment by 5noop** [comment]
> (if I'm not mistaken in logic of bot behaviour).

You are, it will check the items in inventory and stash before picking up another one.
The information is not shared between profiles.

**Comment by ARkaine2** [comment]
> > (if I'm not mistaken in logic of bot behaviour).
> 
> You are, it will check the items in inventory and stash before picking up another one.
> The information is not shared between profiles.

Thanks for answer on first question.
Probably there was some cube receipes, that required Tal rune for them.

About second question: I knew this.
But: Is it possible (and how difficult) to make "cross-profile" information sharing in pickit?

**Comment by 5noop** [comment]
It's doable with copydata or socket, but it probably won't be easy without a good knowledge of kolbot and js.
