### ISSUE TITLE
How to access skill damage max and min

### ISSUE THREAD

**Issue by ckelly44** [kolton/d2bot-with-kolbot#2517]
Hi everyone,

I've built my own little UI for my characters using the data I pull from sdk.js in \kolbot\libs\modules. But it doesn't seem to contain stats for skill damage, is there another way to access that info from the client? Thanks.

**Comment by 5noop** [comment]
It's possible but not easy, they did it in this project https://github.com/jaenster/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/modules/GameData.js#L902

**Comment by ckelly44** [comment]
Awesome, thanks brother!
