### ISSUE TITLE
Akara skill reset

### ISSUE THREAD

**Issue by PickAUsernamez** [kolton/d2bot-with-kolbot#2518]
How can I make it to select the "ok" option to confirm skill reset once it has opened the dialogue menu?

**Comment by PickAUsernamez** [comment]
Anybody?

**Comment by 5noop** [comment]
should be useMenu(3401) or useMenu(5102) depending if ok is uppercase or not

**Comment by PickAUsernamez** [comment]
Thanks, the first one did it

**Comment by DarkHorseDre** [comment]
Nice one @5noop - I tried to find this - guess it's from LocaleStringID.js - but how'd you work out what the uppercase "ok" is?

**Comment by 5noop** [comment]
@DarkHorseDre  LocaleStringID is old and incomplete, I generated a new file https://gist.github.com/5noop/c1d52060237ca6751a3ba0e7ae293ee1

**Comment by DarkHorseDre** [comment]
O.o
@5noop  === 'ourhero'; )
