### ISSUE TITLE
Lime Drop not showing items

### ISSUE THREAD

**Issue by CowVoid** [kolton/d2bot-with-kolbot#2532]
It used to work some months ago, now when I try to check the items from lime it wont show any. Any ideas? ty

**Comment by Archon-** [comment]
Same for me. I fixed it by selecting classic/hardcore/non-ladder which is exactly opposite to my account settings. But it worked.

What worries me most is removed limedrop from Github. Anyone knows something? 🤔

**Comment by Daladlad** [comment]
> Same for me. I fixed it by selecting classic/hardcore/non-ladder which is exactly opposite to my account settings. But it worked.
> 
> What worries me most is removed limedrop from Github. Anyone knows something?

Have you tested to see if the dropper works with the opposite settings? Or does this stop it from dropping?

Also my guess is they could be updating Limedrop for the next ladder as they still need to introduce the item queue. That's what I hope anyway

**Comment by Archon-** [comment]
> > Same for me. I fixed it by selecting classic/hardcore/non-ladder which is exactly opposite to my account settings. But it worked.
> > What worries me most is removed limedrop from Github. Anyone knows something?
> 
> Have you tested to see if the dropper works with the opposite settings? Or does this stop it from dropping?
> 
> Also my guess is they could be updating Limedrop for the next ladder as they still need to introduce the item queue. That's what I hope anyway

No, haven't test it as I don't have any char/items on HC etc. Any other configuration shows no items at all.

Yeah, hope so. Item queue is what this project needs. :)

**Comment by CowVoid** [comment]
Solved. ty for the help.
