### ISSUE TITLE
[Pickit] Difference between two lines

### ISSUE THREAD

**Issue by sejkomax** [kolton/d2bot-with-kolbot#2542]
Hey,
I was wondering about one thing.
In my pickit I have two lines:

`[Name] == Shako && [Quality] == unique`
`[Name] == Shako && [Quality] == unique # [Defense] >= 140`

When bot pick it up any shako (f.e. 105 def) in game then he will keep it in stash or throw it away (because there is a line telling to keep only above 140 def)? Does the order in the pickit matter?

**Comment by gtoilet** [comment]
top keeps all
bottom keeps only def 140+

e< no dont matter will keep what ever is in nip
EE< if you want it to only keep 140+ then put     //
on the line with no def mod so its like this

//[Name] == Shako && [Quality] == unique

**Comment by sejkomax** [comment]
Thanks for response.
I would like to keep every shako that I find and I wanted to ask if I had to delete the second record (>= 140).
Now I know that I will keep everything.
