### ISSUE TITLE
Kolbot does not click "Battle.net"

### ISSUE THREAD

**Issue by hutber** [kolton/d2bot-with-kolbot#2543]
So I am completely stuck on this screen and it will never move past it. However if I manually join a game, then it will work perfectly for me. So this makes me believe that the scripts are correct, but something is blocking it somehow.
![image](https://user-images.githubusercontent.com/1344898/84085048-97cb6080-a999-11ea-8c5a-f228c01b9f2e.png)

![image](https://user-images.githubusercontent.com/1344898/84085119-bdf10080-a999-11ea-9556-124f02265cba.png)

**Comment by mearei** [comment]
Change entry script

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone

________________________________

**Comment by hutber** [comment]
Thanks :) I believed I had tried them all, now I am using D2BotLead.dbj. Though he just stands there now once in a game, it is better than before!!

**Comment by gtoilet** [comment]
edit char config from false to true
for the scripts you want to run

**Comment by hutber** [comment]
Thanks again guys.

I do actually have that set:
```javascript
	// *** act 1 ***
	Scripts.Corpsefire = true;
		Config.Corpsefire.ClearDen = true;
	Scripts.Mausoleum = true;
		Config.Mausoleum.KillBloodRaven = true;
		Config.Mausoleum.ClearCrypt = true;
	Scripts.Rakanishu = true;
		Config.Rakanishu.KillGriswold = true;
	Scripts.UndergroundPassage = true;
	Scripts.Coldcrow = true;
	Scripts.Tristram = true;
		Config.Tristram.WalkClear = true; // Disable teleport while clearing to protect leechers
		Config.Tristram.PortalLeech = false; // Set to true to open a portal for leechers.
	Scripts.Pit = false;
		Config.Pit.ClearPit1 = true;
	Scripts.Treehead = false;
	Scripts.Smith = false;
	Scripts.BoneAsh = false;
	Scripts.Countess = false;
		Config.Countess.KillGhosts = false;
	Scripts.Andariel = false;
	Scripts.Cows = false;
```

**Comment by hutber** [comment]
Thank you, I found it in the FAQ :(
