### ISSUE TITLE
Don't display ilvl in the screenshot in Char Viewer

### ISSUE THREAD

**Issue by fun3333** [kolton/d2bot-with-kolbot#2544]
I want it to only display the original, without the ilvl added behind the item.

https://i.imgur.com/0nRyMBm.png

I already removed the account and charname (via unchecking in the settings "Show item header").

But I want to hide the itemlevel (ilvl) behind the item in the screenshot also.

Is there any option for this? What file do I need to edit?

Thank you in advance

**Comment by gtoilet** [comment]
mulelogger.js
