### ISSUE TITLE
one bot 2 followers.... only one follows...

### ISSUE THREAD

**Issue by outlawimmortal** [kolton/d2bot-with-kolbot#2549]
i cannot figure out why one of my leechers wont follow. it happens to be a barbarian and for some reason he just sits in the channel and does nothing. I tried pulling up the log thing on screen when you hit "+" in game but nothing comes up when you are sitting in the channel.... this is how i have my joingame set up... not sure what is wrong here....
BigDswinginDiRT is who has the issue... the name is spelled and written exactly how the character has it in game... i dont know...

var JoinSettings = {
"Basedx": ["Ghettodin", "BigDswinginDiRT"]
};

based is my lead... the other two me leechers... Ghettodin has had zero problems... but i cannot get BigD to follow... even with the entry set to botfollow... it joins channel, clicks on the join game, but doesnt write or do anything... is there something in the character script itself? i have the leader set?

**Comment by gtoilet** [comment]
"Basedx": ["all"]

**Comment by outlawimmortal** [comment]
> "Basedx": ["all"]

you know... maybe i should have tried that... lol i am going to try when i get home... i appreciate you taking the time to respond!

**Comment by outlawimmortal** [comment]
> "Basedx": ["all"]

thank you! that seemed to do the trick!
