### ISSUE TITLE
d2m.dll issue

### ISSUE THREAD

**Issue by gtj416** [kolton/d2bot-with-kolbot#255]
So I get this issue whenever opening the bot, along with window crashed on load.

I followed the wiki to a T and can't seem to get it working. I am trying to get the d2botmap up and running. I pick the d2botmap.dbj file, is that correct.

I don't see a d2m.dll in any of the filed, maybe I missed it.. where is that located to see if I even have it?

Do I have to set up a script for this mode? If so where are those?

Also, it won't load without clicking the visible box and setting perimeters, what numbers should be put here?

So after some trial and error, got it loaded and i can now see the main screen of d2, however it will not connect to bnet, it is just staying on the initial pop up screen that reads "connecting to bnet". Will go no further, checked on single player, no map prompt, no d2bs loader on top.

**Comment by noah-** [comment]
If you are using 1.13d with version hack you need d2m.dll.
If you are using 1.14d, you do not need it.
