### ISSUE TITLE
Failing to Create Game because of Long Lines

### ISSUE THREAD

**Issue by RoySwanson** [kolton/d2bot-with-kolbot#2552]
Hi,

Noob here, I'm failing to create games using kolbot because of there being 1000+ size lines for games. Many times I get down to a <200 position and the bot cancels making the game.

Is this fixable? If I am more patient manually, I can make games just fine. Can I make the bot wait longer before canceling? Or is that feature there for my protection or something?

Also while I'm here, sometimes the bot has a display over the game that shows you its actions (scripts running, pickits loaded, items collected). I mean overlaying the actual d2 game, not the kolbot menu. For me, sometimes it is on, and sometimes it is not. How do I trigger this display on and off?

**Comment by nineinchnailzpsn** [comment]
Same thing is happening to me.  The bot fails to create games but I can create one manually.  Started this morning around 10 est.

**Comment by tunz347** [comment]
Two main things will affect on that issue:
1. Increase the lenght of your games
2. Increase your wait in line time out

**Comment by nineinchnailzpsn** [comment]
> Two main things will affect on that issue:
> 
> 1. Increase the lenght of your games
> 2. Increase your wait in line time out

Bingo.  There are 3 lines in the d2botlead.dbj file.  I increased the accepted times like this and it worked like a charm.

_ConnectingTimeout: 600, // Seconds to wait before cancelling the 'Connecting...' screen
PleaseWaitTimeout: 600, // Seconds to wait before cancelling the 'Please Wait...' screen
WaitInLineTimeout: 600, // Seconds to wait before cancelling the 'Waiting in Line...' screen_

**Comment by RoySwanson** [comment]
> > Two main things will affect on that issue:
> > 
> > 1. Increase the lenght of your games
> > 2. Increase your wait in line time out
> 
> Bingo. There are 3 lines in the d2botlead.dbj file. I increased the accepted times like this and it worked like a charm.
> 
> _ConnectingTimeout: 600, // Seconds to wait before cancelling the 'Connecting...' screen PleaseWaitTimeout: 600, // Seconds to wait before cancelling the 'Please Wait...' screen WaitInLineTimeout: 600, // Seconds to wait before cancelling the 'Waiting in Line...' screen_

Right on, this worked perfect! My games were long enough but I was timing out too soon on the wait in line. Any chance you know what I'm talking about with the in-game display question?
