### ISSUE TITLE
ntitemalias

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#2566]
not sure where to find the error
has to be nip right ? i dont have nips that long
in diablo 298 is about seal layout
in diablohelper 298 is about diablo prep

[img]https://i.imgur.com/9CAYoGg.png[/img]

**Comment by 5noop** [comment]
It happens when someone picks an item right before you.

**Comment by gtoilet** [comment]
so my bots are causing their own errors LOL
guess ill try to find where it prints error to console and take it out

thanks 5noop
