### ISSUE TITLE
D2BotPubJoin does not join mule

### ISSUE THREAD

**Issue by hutber** [kolton/d2bot-with-kolbot#2568]
I have muled successfully for a very long time now, so I am not to worried about that side, however when I play with `pubJoin` it does not join the mule game that is created. It goes to `join game` and then joined one of my `dia` or `baal` games that are set in the config.
```

var IncludeFilter = [
	["baal", "diablo"],
	["baal", "dia"],
	["hqdiabaal"],
	["csbaalen"],
	["Bazdiabaa"],
	["Bdiabaal"],
	["Zdiabaal"],
	["Ukdiabaal"],
	["Diaballz"],
	["Sonicdiabaal"],
	["Mydiabaal"],
	["sonic"]
];

var ExcludeFilter = [
	[""]
];
```

**Comment by gtoilet** [comment]
you mule private?
pubjoin only searches public games

**Comment by hutber** [comment]
I mule private yes.
So I guess I cannot mule privately while using the public games? Its disapointing

**Comment by hutber** [comment]
I am not certain this was the reason, but I had a `E` in my charater_config rather than `e`. Wrong case.
