### ISSUE TITLE
KOLBOT issue

### ISSUE THREAD

**Issue by kiki-prog** [kolton/d2bot-with-kolbot#2569]
Hello , its picking items for exp: pickit tal rasha belt id and the sell , why not keep it ? in kolbot pickit its tal rasha belt .
and one more problem when its start say nip files does't exist : pickit/true but working pick items and the sell :(

**Comment by gtoilet** [comment]
probably because it doesnt meet the defense requirement in nip or someother mod
check your nip files

**Comment by kiki-prog** [comment]
and how i check that defense requirement ?

**Comment by gtoilet** [comment]
nip file open and look

**Comment by kiki-prog** [comment]
I rly dont know how to make the bot to stash the items i want and dont sell it .

**Comment by gtoilet** [comment]
open nip
see items you want kept
remove //
infront of that line
see items you want to sell
put //
infront of that line

google a guide for more help

**Comment by kiki-prog** [comment]
i look in nip and its tal rasha belt and i find it and sell it . :(

**Comment by Mynnion** [comment]
If you want it to save all Tal Rasha belts edit the nip line to:

[name] == meshbelt && [quality] == set # [itemmagicbonus] >= 10 && [defense] >= 35

MF Bonus is 10-15 and base defense is 35-40.  Use the minimum.  Arreatsummit has all the base values listed.
