### ISSUE TITLE
How to grab Waypoints when near them, during clearanyarea/attack.clearlevel

### ISSUE THREAD

**Issue by DarkHorseDre** [kolton/d2bot-with-kolbot#2582]
Can someone save me some time and help id where to place the code to grab a wp whilst moving around during a clearlevel?

bot currently walks past wps when doing clearlevel (cold plains is a good example)

**Comment by gtoilet** [comment]
stabbed wp grabber into clear any area and i watched it clear spider forest and grab wp
only tested the once saw it work and hope it works for you too
https://pastebin.com/xvpti65U

**Comment by DarkHorseDre** [comment]
Thanks dude!
I'll get on this in the morning! even if it doesn't work in all cases I'll be able to tweak it, saving time so it's appreciated!

**Comment by DarkHorseDre** [comment]
Hey GT - it seems it may only get wps once area has been clear - almost impossible for a weak toon who may chicken.

I think it would fit in better within clearlevel (called by clearanyarea) - any idea's where in that attack.clearlevel function to put it? I'm thinking near the end, maybe just before 
```js
result = Pather.getNearestWalkable(room[0], room[1], 18, 3);
```
?

**Comment by gtoilet** [comment]
function ClearAnyArea() {
	var i;

	Town.doChores();

	for (i = 0; i < Config.ClearAnyArea.AreaList.length; i += 1) {
		if (Pather.journeyTo(Config.ClearAnyArea.AreaList[i])) {
			Attack.clearLevel(Config.ClearType);
		}
	result = Pather.getNearestWalkable(room[0], room[1], 18, 3);
}

	return true;
}


maby something like that not sure
yea my test resulted in clear area and then grab wp
maby put a while  in there so its like while clear area grab wp
sucks i dont have a 5th key to run tests my 4 keys are used nmcs team
will try to test some after my movie

**Comment by DarkHorseDre** [comment]
did your paste work correctly? I don't see referenec to wp?

re: testing - BRO! someone said to me "brah, you testing hc on realm?! test in sp!" and its so worth it - thats what I'm testing now - no need to worry about R/D etc 👍

**Comment by gtoilet** [comment]
about to test ... i cant run SP cus all keys being used by bots lol
will try to keep testing to achieve what your after


...yea i understand but im dummy had to remove my key list

**Comment by DarkHorseDre** [comment]
sp = single player! :)

so you can test all non-realm stuff (most of it) and not need keys or go online

**Comment by gtoilet** [comment]
https://pastebin.com/xvpti65U

ok code is scabbed from autosmurf 
she cleared area on her way direct to wp grabbed
then started clearing area

**Comment by DarkHorseDre** [comment]
Thanks dude - you saying toon goes to wp first (if there is one there), clicks, then clears area from that spot?

**Comment by gtoilet** [comment]
yes if you need me make a video for you 
i tested it on stony wp since cold p's is right there by entrance to area
just tested on underground pass lvl 1 since right from stony
she started off clearing
cleared area and started next script

should work how you are wanting it to work
lmk if any errors or anything else will try to help

**Comment by DarkHorseDre** [comment]
oh no thanks for asking - was just checking how you implemented it - I will test it.

I want it to behave as it does now - just that if it comes close to a wp it gets it - not to change its pathing for it (as it will draw more mobs when on foot)

Will test tomorrow - thanks!

**Comment by gtoilet** [comment]
yea the last paste link is
enters area heads toward wp while clearing
clicks wp clears whole area
if in area with NO wp will just clear area

as stated lmk if your in need of any other mod and glad to help

**Comment by DarkHorseDre** [comment]
haha you star!

I do have a few easy issues to discuss - whats your discord?
maybe I can repay you with some testing? :p

**Comment by gtoilet** [comment]
not on disc much ... face is easier as its usually open on tab all the time but here

**Comment by DarkHorseDre** [comment]
ah I'll try you on dc as I'm a fb hater ;)

**Comment by DarkHorseDre** [comment]
I eventually got this working - I placed it in pather.js, within the nodeaction function, above getShrines():

```js
// grab wps whilst pathing 
	getWpsDHD: function () {
		if (getDistance(getUnit(2, "waypoint")) <= 35 && Pather.wpAreas.indexOf(me.area) > -1 && !getWaypoint(Pather.wpAreas.indexOf(me.area))) { 
			//if(!getWaypoint(Pather.wpAreas.indexOf(me.area))) { //crashes when in area that is not in wpAreas - ffs
				Pather.getWP(me.area, true);
				print("Getting nearby wp");
		}
	},
```
