### ISSUE TITLE
My BO barb doesn't take my leader TP

### ISSUE THREAD

**Issue by HiroDen** [kolton/d2bot-with-kolbot#2586]
I am running 3 character in 1 game (Normal difficulty) (leader Blizz Sorc, leacher BO barb and Trap sin)
but when my barb is give bo and then work collect, he just go back to act1 town and doesn't move.
does anybody knows how to take my sorc safe portal in act 5 baal run.
PS. I'm very sorry my English grammar skills.

my bo barb
https://pastebin.com/2Z8p1Faf

**Comment by outlawimmortal** [comment]
Hey there! ive never really posted any answers to any questions, but i may know this one.

 Config.MFLeader = true;

that is set on your barb? if he isnt the leader, this needs to be false i believe. you only set this to true  for the botlead. the leechers have their own section below the a1-5 scripts.

you already have the baal leecher set up correctly, so i believe if you change that value to false that should fix it!

not too sure but i would try that first!

**Comment by HiroDen** [comment]
> Hey there! ive never really posted any answers to any questions, but i may know this one.
> 
> Config.MFLeader = true;
> 
> that is set on your barb? if he isnt the leader, this needs to be false i believe. you only set this to true for the botlead. the leechers have their own section below the a1-5 scripts.
> 
> you already have the baal leecher set up correctly, so i believe if you change that value to false that should fix it!
> 
> not too sure but i would try that first!

I've change it. but it same. barb doesnt move. thank you.
