### ISSUE TITLE
Wakka Script - Change pally's aura

### ISSUE THREAD

**Issue by luisfilipepena** [kolton/d2bot-with-kolbot#2589]
Hello! I'm using Wakka Script and it works just fine, but my pally uses Vigor aura and I want him to use "Salvation" instead, so he can also help the party.
Does any1 figured out how to change it?
Thanks in advance!

**Comment by gtoilet** [comment]
did you try setting his char config to use that aura?

**Comment by luisfilipepena** [comment]
> did you try setting his char config to use that aura?

Yes:
```
	Config.AttackSkill[0] = -1; // Preattack skill. Not implemented yet.
	Config.AttackSkill[1] = 125; // Primary skill to bosses.
	Config.AttackSkill[2] = 125; // Primary aura to bosses
	Config.AttackSkill[3] = 125; // Primary skill to others.
	Config.AttackSkill[4] = 125; // Primary aura to others.
	Config.AttackSkill[5] = 125; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 125; // Secondary aura.
 
	// Low mana skills - these will be used if main skills can't be cast.
	Config.LowManaSkill[0] = -1; // Low mana skill.
	Config.LowManaSkill[1] = -1; // Low mana aura.
```

Also, if i set` Config.Vigor = true;` he uses vigor while walking, if I set to false, he doesn't use any aura.

**Comment by luisfilipepena** [comment]
Ok, so here's how: 
set `Config.Vigor = true;` to `false`
Manually set the aura you want.
The Wakka Script won't change the aura.
