### ISSUE TITLE
Follower won’t take leader tp

### ISSUE THREAD

**Issue by HiroDen** [kolton/d2bot-with-kolbot#2590]
Sorc is leader and barb is follower.
After barb has done BO in catacomb 2 my barb just stood in act1 town. Is there any way to get my Barb to leader’s safe tp?

Barb character config

https://pastebin.com/2Z8p1Faf

**Comment by Deviter** [comment]
hi
change this lines

    // Team MF system
    Config.MFLeader = true; // Set to true if you have one or more MFHelpers. Opens TP and gives commands when doing normal MF runs.

this set to" false",  cause sorceress is the one who must have in true cause is leader, barb is follower

Scripts.Baal = true;
        Config.Baal.HotTPMessage = "Hot TP!";
        Config.Baal.SafeTPMessage = "Safe TP!";
        Config.Baal.BaalMessage = "Baal!";
        Config.Baal.SoulQuit = false; // End script if Souls (Burning Souls) are found.
        Config.Baal.DollQuit = false; // End script if Dolls (Undead Soul Killers) are found.
        Config.Baal.KillBaal = true; // Kill Baal. Leaves game after wave 5 if false.
 
baal must be "false" if is follower 
and true in

// *** Guest scripts ***
 
    // Baal Assistant by YourGreatestMember
    Scripts.BaalAssistant = true; // Used to leech or help in baal runs.
        Config.BaalAssistant.Wait = 120; // Seconds to wait for a runner to be in the throne / portal wait / safe TP wait / hot TP wait...

and if sorc made some other mf sites 

put true in

    Scripts.MFHelper = false; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true



must check d2botfollow.dbj

and edit this lines

/* Join game settings
	Format: "leader's profile": ["leecher 1 profile", "leecher 2 profile", ...]
	If you want everyone to join the same leader, use "leader's profile": ["all"]
	NOTE: Use PROFILE names (profile matches window title), NOT character/account names
	leader:leecher groups need to be divided by a comma
	example:
		var JoinSettings = {
			"lead1": ["follow1", "follow2"],
			"lead2": ["follow3", "follow4"]
		};
 

sry for my bad inglish

**Comment by HiroDen** [comment]
Thank you for reply.
I still have a problem with my barb.
Could you look for my d2botfollow.dbj ?

https://pastebin.com/SRtkrEMA

**Comment by HiroDen** [comment]
Thanks.
