### ISSUE TITLE
can i setup a loot option?

### ISSUE THREAD

**Issue by jstall6** [kolton/d2bot-with-kolbot#2604]
I play hardcore and bot 2 chars at once is there a way to grant my boer loot incase I die and they can just sit in game so I can retrieve my stuff?

**Comment by Danmanjo** [comment]
Sounds to me like automuling but you want them just in town, loot items and go back to town? No idea if that's possible.

**Comment by jstall6** [comment]
no I want my bot to allow my baba to be able to loot him if he dies. had my hdin die and now lost the gear and had to rebuy enigma etc

**Comment by 5noop** [comment]
I'm sure it's possible but it seems pointless to me.

If you have chicken enabled the char will leave the game after dying (or right before if you are lucky) so your bo won't be able to loot it. And if you didn't enable chicken, well you probably should.

**Comment by gtoilet** [comment]
i remember thinking of this when i played HC
as some times game laggs and you die or chicken fails from getting smacked
not sure what the code is to enable loot to players prob lost the code/links
when i lost all my old files

**Comment by jstall6** [comment]
yea I would just rather my din die and be able to get the 2000k fg worth of gear back

**Comment by DarkHorseDre** [comment]
I agree with 5noop. better to avoid the death than try to loot (although I understand the loss, I lost many toons before I worked-around the issues)

do you know what caused the bot deaths?
