### ISSUE TITLE
Diablo XP leech script

### ISSUE THREAD

**Issue by anime143** [kolton/d2bot-with-kolbot#2607]
I want my leader who is already working properly to not kill diablo but instead to stand there/ hide to leech xp when diablo step out.

something like this...?
Pather.moveTo(7767, 5263);

this.diabloPrep();
//Attack.kill(243); // Diablo (note i did this so leader does not kill Diablo but make portal and go to town)
Pickit.pickItems();

Pather.teleport = Pather._teleport;

**Comment by gtoilet** [comment]
this will hurt diablo till hp is xx and stand and wait till dead might be what you want


    Attack.hurt(243, 10); // Diablo
    let dia = getUnit(1, 243);
    while(!me.dead && dia && Attack.checkMonster(dia)) {
    delay(20);

**Comment by anime143** [comment]
it is working now, i get this error.

diablo.js:7 function diablo does not always return a value

**Comment by gtoilet** [comment]
**Attack.hurt(243, 10); // Diablo
let dia = getUnit(1, 243);
while(!me.dead && dia && Attack.checkMonster(dia)) {
delay(20);
}**

the auto filter cut it off
