### ISSUE TITLE
How to change pickit to pick up certain ilvl?

### ISSUE THREAD

**Issue by TerraTony** [kolton/d2bot-with-kolbot#261]
I want my bot to pickup grand charm and small charm from baal and keep it.

I tried [level] but isnt a valid pickit requirment. Anyone can help me out?

**Comment by david1602** [comment]
Can you post your whole line?
I looked this up:
https://www.projectetal.com/forums/wiki/?title=Snagit_NIP_Syntax

And it seems like the level goes before the `#`, maybe that's your issue

**Comment by TerraTony** [comment]
[name] == smallcharm && [quality] == magic # [level] == 99

But level is not a valid argument.

**Comment by david1602** [comment]
I think I just commented that the `level` goes **before** the `#`, try that.

**Comment by LeMule** [comment]
[name] == smallcharm && [quality] == magic && [level] == 99
should parse fine

David posted a very comprehensive guide to the NIP language and the answer
to your problem initially.

**Comment by TerraTony** [comment]
Thanks guys it did work out.

**Comment by TerraTony** [comment]
Apparantly [level] is not correct i got a warning while trying this out:
`([name] == sharkskingloves || [name] == vampirebonegloves) && [quality] == magic && level >= 85`

want to pickup all magic gloves that have a ilvl of 85 or higher i got this error when he found one but didnt pick it up:
[https://imgur.com/a/71rHh](url)

**Comment by TerraTony** [comment]
I am an actual idiot.....

it kmust be [level] not just plain level.
