### ISSUE TITLE
I want clear pit witout teleport. I need walk clear help.

### ISSUE THREAD

**Issue by HiroDen** [kolton/d2bot-with-kolbot#2612]
I have sorc lvl72. I want to run my sorc on pit witout using telport.
Is there anywhere  I can look for?
Example : create game → take wp →teleport →pit →walk clear.
thanks.

**Comment by Kingpece801** [comment]
In your config do you have the following:

"Config.Pit.ClearPit1 = true;"

**Comment by HiroDen** [comment]
I did but my sorc is using teleport while attacking a monster

**Comment by HiroDen** [comment]
can somebody tell me?

**Comment by HiroDen** [comment]
I figured this out
