### ISSUE TITLE
Teleport then walk and clear. How? Is it possible?

### ISSUE THREAD

**Issue by HiroDen** [kolton/d2bot-with-kolbot#2617]
Is there a way to make my leader sorc teleport to places like pit, at, and once in, start to walk, and kill everything in way

**Comment by DarkHorseDre** [comment]
You can either change the way you call each boss script (function) as per (Advanced options):
https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config
(e.g. Scripts.Pit = {NoTele:true};)

or you can disable tele at the start and re-nable at the end of each script/function:

..pit script start
`Config.NoTele = true`
..
..
`Config.NoTele = false`
.. pit script end

**Comment by HiroDen** [comment]
Yes. I change the script but they don't teleport pit. pit scripts works pretty nice.
All I need is just sorc use teleport to pit.

**Comment by DarkHorseDre** [comment]
ahh sorry my bad, pather uses this too so you're gonna have to disable tele as you enter the pit 'room'.

This section moves from wp to pit area:
```js
	if (!Pather.moveToExit([7, 12], true)) {
		throw new Error("Failed to move to Pit level 1");
	}
```

so put the `Config.NoTele = true` line after this, and before the clearlevel.

then set false at end of pit, before `return true`


You can do this for the other bosses

**Comment by HiroDen** [comment]
where is that file located?

**Comment by DarkHorseDre** [comment]
In the folder with all you boss scripts: \kolbot\d2bs\kolbot\libs\bots

**Comment by HiroDen** [comment]
https://pastebin.com/hzAp0iR1

can you look for my pit script?

**Comment by DarkHorseDre** [comment]
You missed a semicolon and the 2nd change.

From the new home for kolton source (latest): https://github.com/blizzhackers/kolbot/blob/master/d2bs/kolbot/libs/bots/Pit.js

The changes you need: https://pastebin.com/4BP6Kt0X

**Comment by HiroDen** [comment]
Thanks
