### ISSUE TITLE
issues with keys and runes - pickit related? settings being ignored

### ISSUE THREAD

**Issue by atolx** [kolton/d2bot-with-kolbot#2621]
Hi, i have this small set of issues with my pickit. Lets start with showing how it looks:

//##########KEYS##########
[Name] == KeyOfTerror # # [MaxQuantity] == 3
[Name] == KeyOfHate # # [MaxQuantity] == 3
[Name] == KeyOfDestruction # # [MaxQuantity] == 3

//##########RUNES##########
[Name] == LemRune # # [MaxQuantity] == 3
[Name] == PulRune # # [MaxQuantity] == 10
[Name] == UmRune # # [MaxQuantity] == 50
[Name] == MalRune # # [MaxQuantity] == 50
[Name] == IstRune # # [MaxQuantity] == 50
[Name] == GulRune # # [MaxQuantity] == 50
[Name] == VexRune # # [MaxQuantity] == 50
[Name] == OhmRune # # [MaxQuantity] == 50
[Name] == LoRune # # [MaxQuantity] == 50
[Name] == SurRune # # [MaxQuantity] == 50
[Name] == BerRune # # [MaxQuantity] == 50
[Name] == JahRune # # [MaxQuantity] == 50
[Name] == ChamRune # # [MaxQuantity] == 50
[Name] == ZodRune # # [MaxQuantity] == 50

pickit name is reset2 and it is the only used pickit in character settings. The issue is, bot completely ignores key drops, and keeps picking runes i didn't even put here, like sol, ko, io, etc. I modified misc file so it would show what is also being dropped and sold - this works fine, setting is in 1 to 8 range, so shows pretty much everything, i identify items by cain. While the sol runes appear on "kept" list in the bot console, they are enabled nowhere in the entire pickit. This happens with many more items (for example flails, i excluded them all yet bot keeps picking and stashing them), but i just need to get the grasp of what is the problem and i'll manually apply the fix to all the other items. Any ideas here?

i have done things like removing all profiles and adding them again, restarting bot after implementing any changes to pickit

/e2 hold on with answering, i may have fixed this by accident, will leave it running 12h to be sure

fixed, issue was that the pickit was overwriting itself so my changes had no effect whatsoever,everything is fine now

**Comment by Zaidore** [comment]
i have the same problem, but my bot is selling runes, how did you manage to fix it ?
