### ISSUE TITLE
HUD Is Gone.

### ISSUE THREAD

**Issue by Kolbotnoob** [kolton/d2bot-with-kolbot#2631]
So when i start botmap before i was able to go into game then a screen was at the bottom Numpad 1-6 like if i hit 1 it would walk to cold plains etc... that dispay isnt there. what did i do wrong and how can i get that back thanks

**Comment by gtoilet** [comment]
expand your screen size in options
or just remember the numbers and stay small

**Comment by Kolbotnoob** [comment]
ty bro!
