### ISSUE TITLE
Pickit With Maphack

### ISSUE THREAD

**Issue by Kolbotnoob** [kolton/d2bot-with-kolbot#2632]
Okay So not a coder but im slowly learning my way around these true false things. bot works great. Useraddon is TRUE in config. but botmap dbj pickit isnt loading or my Nip Files. What am i missing to have them load in. (Its not a error or anything its just not loading either of them on start up. like its turned off somewhere)

edit: If i Use botblank Pickit Works Great But it does not have MH

**Comment by gtoilet** [comment]
there was a thread its probably in the old/closed by now
i never kept a link cus i dont need that function
you can find it if you look hard enuf

**Comment by DarkHorseDre** [comment]
From your char config:
```Config.ManualPlayPick = false; // If set to true and D2BotMap entry script is used, will enable picking in manual play.```

**Comment by Kolbotnoob** [comment]
thanks my man!!
so when im in my char  config this isnt a option am i needing to add this option to my char config?

**Comment by gtoilet** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/2449
https://github.com/kolton/d2bot-with-kolbot/issues/1445


google is a champ

**Comment by Kolbotnoob** [comment]
google is a champ i agree ive already seen those threads. does not help my situation. in my Char config. This --->Config.ManualPlayPick = false         is not a option anywhere even using the "find" to search for it... on the blankbot i can use pickit it works fine... im trying to get the botmap.dbj so i have the hud with enemys showing on map like bosspacks etc/ using numpad to fast tele to places.

**Comment by gtoilet** [comment]
in them threads it talks about moding the config.js and stuff to get it working

**Comment by DarkHorseDre** [comment]
Bro, dont make it harder for yourself!
That config line is built to do what you want.  

if you dont have the options you either dont have latest kolbot (now here: https://github.com/blizzhackers/kolbot - you have to change your svn path as per the notes on those pages) or you didnt update your configs when you updated kolbot.

even if you dont have it but you have latest kolbot, you simply would add it to your char config file.

you can also navigate the "code" tab on hithub to see what the code is showing - if that parameter isn't present then you know something it wrong..
