### ISSUE TITLE
getPresetUnits Failed couldn't access the level!

### ISSUE THREAD

**Issue by CrewCrew1710** [kolton/d2bot-with-kolbot#2642]
I started a new character and I keep getting this error when i'm trying to run mausoleum and Rakanishu, etc. i have gotten the waypoints for these areas but when my character tries to use the waypoints it fails and moves onto the next script which then fails doing the same thing as before. Does anyone know of a fix for this?
![D2](https://user-images.githubusercontent.com/67809873/86501302-4aa29a80-bd5d-11ea-8f00-24da0fd6e65e.png)

**Comment by gtoilet** [comment]
that line in pather.js deals with the wp
watch to see if they cant take the wp or get smacked around after taking wp

**Comment by CrewCrew1710** [comment]
> that line in pather.js deals with the wp
> watch to see if they cant take the wp or get smacked around after taking wp

This actually happens in town and never actually takes any of the wps, It selects the wp in town and pulls up the menu, but then just exits that wp menu and throws me this error, i have checked pather.js, and even updated my files to the new files (i've ran plenty of bots in the past.) and can't seem to fix this issue. It's strange though because if i run one of my old bots they use the wps just fine. It is only on these new ones i have created that're having this issue

I am also curious as to what those numbers before the error are referring to and if those are what is throwing the errors

**Comment by DarkHorseDre** [comment]
The numbers with comma's in white are the areas that pather.js will navigate next for this script.
(you can check areas.txt to look these up)

I assume problem is that the bot is trying to go to get cube as you have cubing enabled but no cube.

best thing to do is to either always get cube for each toon, or change the line in char config from:
```js
Config.Cubing = true; //will try to obtain cube if true and toon doesnt have cube
```
to:
```js
Config.Cubing = me.getItem(549); //only enabled once toon has a cube
```

**Comment by CrewCrew1710** [comment]
> The numbers with comma's in white are the areas that pather.js will navigate next for this script.
> (you can check areas.txt to look these up)
> 
> I assume problem is that the bot is trying to go to get cube as you have cubing enabled but no cube.
> 
> best thing to do is to either always get cube for each toon, or change the line in char config from:
> 
> ```js
> Config.Cubing = true; //will try to obtain cube if true and toon doesnt have cube
> ```
> 
> to:
> 
> ```js
> Config.Cubing = me.getItem(549); //only enabled once toon has a cube
> ```

This was the problem, thank you so much for the help. my toon mustve been trying to access act 2 and didnt have the ability to access it yet and threw it in a loop of not working.

**Comment by DarkHorseDre** [comment]
no worries bro

for anyone else reading - the other issue can be your rushed toon tried to get cube on foot and gets his ass kicked everytime - and you'd never complete a run after that!
