### ISSUE TITLE
Do kill the cowking

### ISSUE THREAD

**Issue by kk1216** [kolton/d2bot-with-kolbot#2643]
umm, the question is simple.

what should I do if I do wanna kill the cowkings.

**Comment by DarkHorseDre** [comment]
I havent tested this, but looks like you need to comment out this section:

```js
		kingPreset = getPresetUnit(me.area, 1, 773);
		badRooms = getRoom(kingPreset.roomx * 5 + kingPreset.x, kingPreset.roomy * 5 + kingPreset.y).getNearby();

		for (i = 0; i < badRooms.length; i += 1) {
			badRooms2 = badRooms[i].getNearby();

			for (j = 0; j < badRooms2.length; j += 1) {
				if (indexes.indexOf(badRooms2[j].x + "" + badRooms2[j].y) === -1) {
					indexes.push(badRooms2[j].x + "" + badRooms2[j].y);
				}
			}
		}
```

**Comment by kk1216** [comment]
Thanks for replying,
I stuck here, dunno what should I change

**Comment by DarkHorseDre** [comment]
Comment out the lines with `//` (or `/*` at start and `*/` at end)

**Comment by kk1216** [comment]
> Comment out the lines with `//` (or `/*` at start and `*/` at end)

i tried, it will be buggy
thanks for replying

**Comment by DarkHorseDre** [comment]
You didn't do what I wrote.

I just tried it - works fine:
![image](https://user-images.githubusercontent.com/41862641/87035095-c0d15200-c1e0-11ea-9044-8042f15efd18.png)

**Comment by kk1216** [comment]
OMG, I just noticed that I /* and */ too much lines, and you're super right. That's the way out! Thank you so much!

**Comment by kk1216** [comment]
OMG, I just noticed that I /* and */ too much lines, and you're super right. That's the way out! Thank you so much!

**Comment by DarkHorseDre** [comment]
no worries

(please click the close button)
