### ISSUE TITLE
Stop Script

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2646]
Is there a way to stop script (for example MFHelper) in certain point/time?

Let's say we doing team MF run.

Leader's script sequence:

```
	Scripts.Cows = true;

	Scripts.Mausoleum = true;
		Config.Mausoleum.ClearCrypt = true;

	Scripts.AncientTunnels = true;

	Scripts.A3DuranceOfHateForCold = true;

	Scripts.A4OuterSpacesForCold = true;

	Scripts.A4RiverOfFlameForCold = true;
```

Follower's script sequence:

```
	Scripts.MFHelper = true;

	Scripts.Mausoleum = true;
		Config.Mausoleum.ClearCrypt = true;

	Scripts.AncientTunnels = true;

	Scripts.A3DuranceOfHateForCold = true;

	Scripts.A4OuterSpacesForCold = true;

	Scripts.A4RiverOfFlameForCold = true;
```

Is there a way to do follower's MFHelper run only during leader's cow run, then stop it and do run with other scripts?

Why not MFHelper during all run? 
Because, if leader will get chicken, run will be corrupted (MFHelpers won't be able to continue run by themselves).

**Comment by DarkHorseDre** [comment]
Hmm.. The issue I see with mfhelper is that it was written in a very specific way, and its a bit inflexible for dynamic use cases.

but if you just want to quit if not in cows, then you may have to do what it does in cs/baal - detect leaders area location and then break that script, which the bot then moves onto the next boss script.

change this:
```js
// Finish MFHelper script if leader is in Chaos or Throne
	if ([108, 131].indexOf(player.area) > -1) {
	break MainLoop;
}
```
to this:
```js
// Finish MFHelper script if leader is in Chaos or Throne
	if ([108, 131, 39].indexOf(player.area) > -1) { //39 is the cow farm
	break MainLoop;
}
```

**Comment by ARkaine2** [comment]
Don't consider me intrusive.
But shouldn't it FINISH MFHelper script if leader will be in cow farm?

**Comment by DarkHorseDre** [comment]
Yes, that's what the line does - if in area 39 (or 108, 131) it stops mfhelper same as when youre leader goes to baal or cs - mfhelper stops and next script is processed (and if no script, toon exits)

**Comment by ARkaine2** [comment]
> Yes, that's what the line does - if in area 39 (or 108, 131) it stops mfhelper same as when youre leader goes to baal or cs - mfhelper stops and next script is processed (and if no script, toon exits)

I think that it can be problem. Let's see why:
By default MFHelper STOPS (!!!) when leader goes to Baal or CS (108 or 131).
So, if we'll add cow farm (39), MFHelpers will STOP when leader will be in cow farm (in other words: during cow run).
But I was needed script that will WORK during cow run and that will stop AFTER cown run.

**Comment by DarkHorseDre** [comment]
lol dude, you used way too many words to point out that I mixed up what you asked for..

you seem to know a lot so that makes this easier and shorter to explain:

as your OP states cows is first and you repeat that you want leader to move onto maus next, and follower to STOP mfhelper, you simply apply the same logic that has been shared but to fit your need:  tell it to stop Mfhelper once leader leaves cows area and act1 camp (to accommodate town visits for pots etc) - remember that the mfhelper receives the "cows" command after the leader has found the leg, tome and opened portal, so after that point the leader shouldnt change areas other than the aforementioned..

good luck

**Comment by ARkaine2** [comment]
At last (after temp ban) I've tried to follow your advice, but I stucked on this problem:

> leader shouldnt change areas other than the aforementioned.

The problem is that:

Leader quit game via chicken when followers continue run.

So we get 2 games:
1. New with only leader that is running new scripts/locations in game.
2. Old with followers that are finishing previous locations game.

Sometimes followers join game (and of course start MFHelper script) and leader quit game via chicken -- so followers are staying doing nothing and MFHelper even can't check when to finish script.
```
// Finish MFHelper script if leader is in Chaos or Throne
	if ([108, 131, 39].indexOf(player.area) > -1) { //39 is the cow farm
	break MainLoop;
}
```
And followers "ENDLESSLY" (until max game time limit is reached) are simply staying in town (in any act):

![image](https://user-images.githubusercontent.com/31447095/86987761-7aa7ce80-c19f-11ea-862e-65ba6f874f25.png)

ATM i have:
```
	Scripts.CowHelper = true;

	Scripts.ClearAnyArea21 = true;
		Config.ClearAnyArea.AreaList21 = [62, 63, 64];	// Maggot Lair (Level 1--3)

	Scripts.ChestMania = true;
		Config.ChestMania.Act3 = [79, 80, 81];			// Lower Kurast, Kurast Bazaar, Upper Kurast

	Scripts.A3DuranceOfHateForCold = true;

	Scripts.Travincal = true;

	Scripts.A4OuterSpacesForCold = true;

	Scripts.A4RiverOfFlameForCold = true;

```
In follower's config file.

Which (CowHelper [based on MFHelper]) contains:

```
			// Finish MFHelper script if leader is in specified areas
			if ([108, 131, 39, 40, 43, 44, 62, 63, 64, 65, 75, 79, 83, 101, 102, 103, 104, 106, 107].indexOf(player.area) > -1) {
				break MainLoop;
			}
```

But can I add to Helper checking for leader's presence in game?
