### ISSUE TITLE
D2BS is not responding... starting profile

### ISSUE THREAD

**Issue by sunace** [kolton/d2bot-with-kolbot#265]
kolbot ran fine for the first 24 hours untell my computer went through an update after that now my profiles will not load when I start a profile the diablo 2 window will come up for about 10 seconds then restart with the error "D2BS is not responding... starting profile" in the d2bot console also the window itself is titled "Diablo II" instead of my profile name "number1" also it will not let me run 2 profiles at once I get error "only one diablo II can run at one time" its acting like I'm opening the game.exe by itself without kolbot I have tried to reinstall everything kolbot and d2 with same issue I even reset my computer back to factory defaults before the update but still same issue I made sure and followed the instructions exactly

I have downloaded all these as well

•Microsoft Visual C++ 2008 SP1 Redistributable Package (x86)
•Microsoft .NET Framework 3.5
•Microsoft .NET Framework 4 (Web Installer)

**Comment by noah-** [comment]
You don't have a fresh install of the files. Likely, you still are using d2m.dll with 1.14d.

**Comment by sunace** [comment]
Sorry to bring up this old question but it still isn't working in using a
fresh install of Diablo 2 verison 1.14d and I'm using a fresh install of
the kolbot master file there is no d2m.dll in the master files's d2bs
folder i have never downloaded the 1.14 hack either d2bot is also running
on verison 1.14 i have even went as far as to try and download etal and
have the sane problem with thag program as well of that helps at all would
it be possible for you to help me wirh kolbot on team viewer or I could
also upload screen shoots if this would help as well

**Comment by imkarrer** [comment]
I am having problems related to d2m.dll also.  #255 indicates that if we are using with the version hack then we need it, but I do not see the file anywhere.  #255 also implies that we can use kolbot with just plain 1.14d?

**Comment by imkarrer** [comment]
It looks like the version hack is no longer required as of this [commit](https://github.com/kolton/d2bot-with-kolbot/commit/ba9acb758d37d03bd383c7e66d4bf0a7c017b3eb)

Mister Kolton, could you confirm?  I am up and running today, but all google searches indicate that the version hack is still a thing.

**Comment by pelthor** [comment]
@noah- or kolton it would be great if you guys could address some 2018 issues. anyways some say kolton works and then again i am having issues getting the bot to do something other then 10 seconds and nuke d2 over and over and over, instead of logging in picking a char and making my life easy.

**Comment by LeMule** [comment]
I missed the part where you were paying folks to make your life easy.

**Comment by imkarrer** [comment]
You could just say that you're accepting pull requests to resolve the matter. Oh wait, there are outstanding pull requests from 2016.

Lol @ trying to get paid for work on open source projects.

**Comment by LeMule** [comment]
Behavior like yours is reason why nobody should give a shit about working
on these publicly.
Have a nice day.

**Comment by imkarrer** [comment]
Go have fun stealing other peoples code and selling it as your own.

**Comment by LeMule** [comment]
I was simply making a point. Impatience, begging and hostility is very
unhealthy for a project of this nature.
I strongly support Kolbot and have a huge amount of respect for the work
that's been done with it and it's associated libraries. I'd expect others
who have nothing to contribute to behave similarly.

Cheers;

**Comment by imkarrer** [comment]
Your point was in poor taste since this is an open source repository.  You also were the first to strike a tone of hostility.

Why would you treat users who file bugs with such disrespect?

You make no sense.  I should stop feeding the trolls.

**Comment by LeMule** [comment]
In response to Pelthor's comment:

*noah- (omitted @ so as to not spam him) or kolton it would be great if you
guys could address some 2018 issues. anyways some say kolton works and then
again i am having issues getting the bot to do something other then 10
seconds and nuke d2 over and over and over, instead of logging in picking a
char and making my life easy. *

I made an offhand remark. You took it upon yourself to be the white knight
following that up. That'll be all. I've nothing further to add and my point
stands.
Have a nice day and good luck with your ongoing issues.

**Comment by LeMule** [comment]
Here's your issue though; I never begged for money nor have a need for it.
I do appreciate your concern about my well-being though.
I don't play D2 anymore. I had some interest in helping with this code-base
when I did, but your kind made me reconsider. I'm sorry you need to feel
superior for knowing how to code Javascript. Surely you want nothing more
today than to have put me in my place. Cheers.

**Comment by imkarrer** [comment]
> I missed the part where you were paying folks to make your life easy.

Your comment is exactly what keeps qualified people from contributing to open source projects.  The notion that you wont help someone unless you get paid for it is orthogonal to open source projects.  Cheers.

**Comment by LeMule** [comment]
Not my problem you decided to take that offensively. My point is that
nobody here is paid to do the work they are doing; so nobody should beg for
anything. All too often, it seems to be forgotten.
Surely if you can't get that through your skull there's something
fundamentally wrong with you. Now please, just stop it; There's nothing
more to add here; but I'm sure you'll go ahead and take the last word.
Whatever helps you sleep at night.

**Comment by noah-** [comment]
1) Microsoft Visual C++ 2010 Redistributable Package (x86)
2) Have ANY .net run-time greater than or equal to 4.0
3) Install D2 1.14d from battle.net
4) Download latest files from github

**Comment by noah-** [comment]
@pelthor read the announcement on blizzhackers regarding the current status of D2BS.
