### ISSUE TITLE
Items with charged skills

### ISSUE THREAD

**Issue by Danmanjo** [kolton/d2bot-with-kolbot#2650]
I am trying to add a line to pickit to find a runestaff with teleport charges on it but can't seem to figure it out.

I want it to be a staff, ethereal, 100 ED, teleport charges and less than lvl 30 req.

([name] == warstaff || [name] == runestaff || [name] == archonstaff) && [quality] <= superior && [flag] == ethereal # [enhanceddamage] == 100 && [itemlevelreq] <= 30 // this is what I currently have and want to make it also have teleport charges.

I read the charged skill items below and still can't figure out what the author is saying.

https://github.com/blizzhackers/pickits/blob/master/NipGuide.md#charged-skill-items

Can someone help me?

@darkhorsedre :p

**Comment by gtoilet** [comment]
([name] == warstaff || [name] == runestaff || [name] == archonstaff) && [quality] <= superior && [flag] == ethereal # [enhanceddamage] == 100 && [itemchargedskill] == 54 && [itemlevelreq] <= 30

**Comment by Danmanjo** [comment]
> ([name] == warstaff || [name] == runestaff || [name] == archonstaff) && [quality] <= superior && [flag] == ethereal # [enhanceddamage] == 100 && [itemchargedskill] == 54 && [itemlevelreq] <= 30

Will give this a try and let you know. Thanks!

**Comment by Danmanjo** [comment]
> ([name] == warstaff || [name] == runestaff || [name] == archonstaff) && [quality] <= superior && [flag] == ethereal # [enhanceddamage] == 100 && [itemchargedskill] == 54 && [itemlevelreq] <= 30

Looks like it worked. Can you tell me how you got [itemchargedskill] == 54? How do you know it's 54?

**Comment by gtoilet** [comment]
folder sdk ... skills.txt
54  is tele

**Comment by Danmanjo** [comment]
> folder sdk ... skills.txt
> 54 is tele

Now it all makes sense. I removed skills numbers I wasn't using. Thanks for all the help!
