### ISSUE TITLE
Dont invite or acept 

### ISSUE THREAD

**Issue by kiki-prog** [kolton/d2bot-with-kolbot#2652]
// If LocalChat is enabled, chat can be sent via 'sendCopyData' instead of BNET
	// To allow 'say' to use BNET, use 'say("msg", true)', the 2nd parameter will force BNET
	// LocalChat messages will only be visible on clients running on the same PC
	Config.LocalChat.Enabled = false; // enable the LocalChat system
	Config.LocalChat.Toggle = false; // optional, set to KEY value to toggle through modes 0, 1, 2
	Config.LocalChat.Mode = 0; // 0 = disabled, 1 = chat from 'say' (recommended), 2 = all chat (for manual play)
	// If Config.Leader is set, the bot will only accept invites from leader. If Config.PublicMode is not 0, Baal and Diablo script will open Town Portals.
	Config.PublicMode = 1; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable
	// Party message settings. Each setting represents an array of messages that will be randomly chosen.
	// $name, $level, $class and $killer are replaced by the player's name, level, class and killer
	Config.Greetings = []; // Example: ["Hello, $name (level $level $class)"]
	Config.DeathMessages = []; // Example: ["Watch out for that $killer, $name!"]
	Config.Congratulations = []; // Example: ["Congrats on level $level, $name!"]
	Config.ShitList = false; // Blacklist hostile players so they don't get invited to party.
	Config.UnpartyShitlisted = false; // Leave party if someone invited a blacklisted player.

I set to one public mode but nothing.

**Comment by gtoilet** [comment]
make sure your leader is set

**Comment by kiki-prog** [comment]
I set the charc leader name and its not working , something else to change ?

**Comment by gtoilet** [comment]
try the other public options make sure it will party
i usually have just leader send invites -1
rest will party to it with - 2

**Comment by kiki-prog** [comment]
but the problem its i use just one bot i set publicmode-1 , still not send invites or accept :( help pls , and also si set the leader still not working . Config leader means i set on lecheers config the charc name and other things no ?

**Comment by gtoilet** [comment]
um cant really follow what you said there lol
set it like this once to test to make sure its the right problem
leader sends invites = Config.PublicMode = 3;
leechers accepts = Config.PublicMode = 2;

if that works then there is a problem with the =1 function of public mode
as i stated i run what i posted above and have no problems with party mode

**Comment by Coofnn** [comment]
so i made a psn nova necro. and im having a issue with my necro accepting party invite from leader. i run 4 sorc's atm. have no issue. ive set up the char config twice now. ive added him to the leaders config. this is the error code he gets once i manually accept the invite ingame.

this is the error code:
strict warning (162) File(kolbot\libs\common\misc.js:852) reference to undefined property unit.area

**Comment by gtoilet** [comment]
@Coofnn 
you got it backwards fella
put your leaders in necro config
unless he sends party invites

**Comment by Coofnn** [comment]
so one of my sorc's cant be leader? has to be the necro now?

**Comment by Coofnn** [comment]
was also going to make a hammerdin to run with them. have 6 bots in same game. im notciing now that he also only has the leader option. unlike the sorc's. is that going to conflict wanting to havea psn necro and a hdin in same game?

**Comment by Coofnn** [comment]
> 
> 
> @Coofnn
> you got it backwards fella
> put your leaders in necro config
> unless he sends party invites

ahh okay i see. im trying to reboot now. i made him the inviter lead in necro config

**Comment by Coofnn** [comment]
he still will not pp with leader. i get the invite. but he doesnt accept

**Comment by gtoilet** [comment]
case sensitive make sure leader name is right
and you dont have to reboot
in game chat < .start
will restart char config after changes

**Comment by Coofnn** [comment]
> 
> 
> case sensitive make sure leader name is right
> and you dont have to reboot
> in game chat < .start
> will restart char config after changes

i have his name in there correctly. still will not join party

**Comment by Coofnn** [comment]
this is so dumb. like the 4 sorc's work so well together.. i have him set up. i now manually can accept party invite. and the bot will semi work. but it will not join the main groups party invite unless i manually change it to.

**Comment by gtoilet** [comment]
so weird i got mine set as i said and the 3 work fine together

**Comment by Coofnn** [comment]
> 
> 
> so weird i got mine set as i said and the 3 work fine together

well this would be my 5th bot in the same game. i currently run 4 no issue. not its not letting the 5th in

**Comment by Coofnn** [comment]
willing to give someone 50$ if they can help me figure this out lol

**Comment by gtoilet** [comment]
you running the newest version?
wouldnt hurt to try a new install
you could have but doubt it something got altered and wont work now idk

**Comment by Coofnn** [comment]
yeah newest version up to date.

**Comment by gtoilet** [comment]
try one less sorc or have multiple invites to necro start trying to eliminate what could be wrong
and im using last years  version 1.633 or what ever

**Comment by 5noop** [comment]
Use the blizzhacker version and set publicmode to true for everyone.

**Comment by kiki-prog** [comment]
i have just one bot i set to public -3 and still not send invites . whyyyyy? ???????
