### ISSUE TITLE
Add error message

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2664]
In continue of this thread (https://github.com/kolton/d2bot-with-kolbot/issues/2646) I found compromise solution.

I made CowHelper.js (https://pastebin.com/RfP39H76) which is based on Cows.js and contains:

```
	Town.goToTown(1);
	Town.doChores();
	delay(45000);
	Pather.usePortal(39);
	Precast.doPrecast(true);
	this.clearCowLevel();
```

So we have:
```
	delay(45000);
	Pather.usePortal(39);
```
This is fine time settings, but I'd like to add error message (just like in other cases / default case: **throw new** Error("Portal not found");) if red portal wasn't open in specified time.

You know, someting like:
```
delay(45000);
Pather.usePortal(39);
IF PORTAL WASN'T OPEN WRITE "Portal not found" and stop script;
Precast.doPrecast(true);
this.clearCowLevel();
```

I see this part of code, but I don't know how to combine it with described above:
![image](https://user-images.githubusercontent.com/31447095/87239446-e4caa880-c417-11ea-8e0d-933adbfdfecb.png)

How to do thist?

I'm not guru of syntax, but I think that there's simple solution.
If someone is good at coding or simply know how to do this, please help.

**Comment by 5noop** [comment]
```
		if (!Pather.getPortal(39)) {
			throw new Error("Portal not found");
		}
```

**Comment by ARkaine2** [comment]
Thanks. Now it works fine.
