### ISSUE TITLE
Hello, Question on Cubing kolbot

### ISSUE THREAD

**Issue by Kolbotnoob** [kolton/d2bot-with-kolbot#2669]
hi i have enabled kolbot to craft blood rings / caster ammys etc. does it look for GG stats or is there like a pickit list/etc i need to modify to make it keep these crafted items. as of right now it just crafts them and there gone.

**Comment by DarkHorseDre** [comment]
if you don't have a pickit line for anything you craft bot will drop the item (if you watch the bot it will do this)

**Comment by Kolbotnoob** [comment]
thank u
