### ISSUE TITLE
Fresh install, no error but still weird npc interaction when starting in a2

### ISSUE THREAD

**Issue by Xdaci** [kolton/d2bot-with-kolbot#2685]
I've been testing some single player bots, a few days ago i noticed when my bot started in a2 she would attempt to interact with drog, be unable to do so, walk away and randomly go to a corner or wander around then spit these errors.
[Warning (206)] File(kolbot/libs/common/prototypes.js:131) delay(0) called, argument must be >=1
[Warning (206)] File(kolbot/libs/common/prototypes.js:133) delay(0) called, argument must be >=1

The only suggestion was to delete my d2bs/kolbot and do a fresh install to the latest version, which i did so.
Luckily it no longer gives an error, and eventually just starts the scripts however it still has the weird failure to interact and the corner/wandering before it eventually starts

Any ideas as to why? Could it be a single player only thing?

heres a video to showcase whats happening

/edit its me hitting home after she walks to the corner to see if it gives an error, it did not luckily. but still weird

/edit 2 if i start her in a1 it runs 100% perfectly, upon going to a2 after completing her a2 scripts she interacts with drog fine. its only when i hit start on her profile and she begins in a2.

[https://youtu.be/fg-23EoBXVY](url)

**Comment by gtoilet** [comment]
set in the end of her last script this

		Town.goToTown(1);

so she returns to act 1 after the end of the last script

**Comment by Xdaci** [comment]
> set in the end of her last script this
> 
> ```
> 	Town.goToTown(1);
> ```
> 
> so she returns to act 1 after the end of the last script

Ty
