### ISSUE TITLE
Question about AutoSmurf

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2689]
There's phrase in manual (https://github.com/blizzhackers/autosmurf):

> when your bot team get the baalLvlnm, the AutoSmurf will enter on Hell difficulty and you should use XXXX2 char-config files, so that you should copy those files using your char names for XXXX2, the same like in XXXX1 case.

Can anyone explain WHAT FOR are XXXX1 and XXXX2 used?
I can't get difference of them except some misc changes like: Different runewords, auto(pickit/equip) etc.

**Comment by noah505050** [comment]
When you're editing your pick it between difficulties open your pickit file
and decide what items you need in the new difficulty.

Use find and replace in your txt editor to swap out things like " &
socketed"     with       " "
 or
an item set with  "==  15" to  ">= 1"

for all lines respectively.

Save a copy in a separate file directory on your desktop for next time

Respectfully,

Noah
