### ISSUE TITLE
Script-specific config override

### ISSUE THREAD

**Issue by IronMaXxX** [kolton/d2bot-with-kolbot#270]
Hey guys, I'am trying to deal with [Script-specific config override](https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config#script-specific-config-override).
Currently I'am running the Worldstone-Script and want my bot to kill every monster on his way.
So I changed the charconfig like this:

old:
```javascript
Scripts.Worldstone = true;
```
new:
```javascript
Scripts.Worldstone = {ClearType = 0};
```
which throws an error at console, what's wrong with this line?
Thanks for your help!

**Comment by Legless** [comment]
Must be:
```
Scripts.Worldstone = {ClearType: 0};
```

**Comment by IronMaXxX** [comment]
Thanks Legless,
readingskills < 0...
