### ISSUE TITLE
Running Tristram Script in Normal

### ISSUE THREAD

**Issue by Bonnono** [kolton/d2bot-with-kolbot#271]
Bot will proceed to go to tree in Dark Wood(even if Cain quest is completed and portal is open) and spit out this error
"Error in Tristram (pickit.js #227) unit is undefined".
This seems to only happen in Normal difficultly(Nightmare and Hell are unaffected).

**Comment by StoneOfJordan** [comment]
I haven't been able to reproduce it, any additional information?

**Comment by Bonnono** [comment]
Additional information I can think to give:
ESCL Sorc
Normal Difficulty
Script in question
```
Scripts.Tristram = true;
		Config.Tristram.PortalLeech = true; // Set to true to open a portal for leechers.
```
Re-checking out the files with minimal edits done, the bot will take wp to Dark wood and go straight to Dark Wood tree and then spit out the error
"14:31:03 (*****)  Error in Tristram (pickit.js #227) unit is undefined (Area: 5, Ping:125, Game: *****)"

**Comment by StoneOfJordan** [comment]
Could you go into a game and tell me what the return for me.getQuest(4, 4); and me.getQuest(4, 0); is? (You can type that into the d2bs console, open it via alt + home.)

**Comment by Bonnono** [comment]
me.getQuest(4, 4); 0
me.getQuest(4, 0); 1

**Comment by StoneOfJordan** [comment]
I see, me.getQuest(4, 4); should return 1, that's why it's trying to "complete" the quest.

You could change line 10 in Tristram.js to something like:
`	if (!me.getQuest(4, 4) && !me.getQuest(4, 0) && !me.getItem(525)) {`
in order to avoid the problem for now. The issue at hand is probably core related.

**Comment by Bonnono** [comment]
Tested the suggested change. 
Line 10 from `if (!me.getQuest(4, 4) && !me.getItem(525)) {` to `if (!me.getQuest(4, 0) && !me.getItem(525)) {`
The bot will now take wp to Stoney Field, clear stone area and just sit in the middle until max game time is reached.

**Comment by StoneOfJordan** [comment]
@Bonnono you'll have to replace all of them. (Line 10, 49, 55)

**Comment by mrandros** [comment]
In the latest version i get this issue too. I tried replace all suggested, but then i get error
Error in Tristram (tristram.js #57) stone is undefined
