### ISSUE TITLE
Config.QuitListDelay issue

### ISSUE THREAD

**Issue by Roycinger** [kolton/d2bot-with-kolbot#2712]
Hi there, 
I configured a QuitListDelay like so:
`Config.Leader = "MyLeadersName";
Config.QuitList = ["MyLeadersName"];
Config.QuitListMode = 0;
Config.QuitListDelay = [1,6];
`
This was working fine for about 5-6 runs until I noticed that the follower was exiting the game in the same moment as the leader.
So I set:
`Config.QuitListDelay = [3,6];`
and it worked again for a few runs until the follower started exiting the game in the same moment as the leader again.

Is this a known issue?
Anything I can supply to analyze this?

Edit: I watched the bot (follower) for a few games now. It seems that the setting (random 3-6 seconds delay) is working every few games but not in every game

**Comment by gtoilet** [comment]
hit your home key and watch the console messages at the end of the runs

**Comment by Roycinger** [comment]
Thats from the follower:
![leave](https://user-images.githubusercontent.com/7791335/89620471-f6289880-d88f-11ea-802c-6e4796520c62.PNG)
On most occasions, the "<Leadername> left" is missing.

**Comment by Roycinger** [comment]
I also noticed that the follower started to quit the game when the leader didnt finish its MF cycle

**Comment by gtoilet** [comment]
so weird ive never had that issue
you use the newest version ?

**Comment by Roycinger** [comment]
Of course :)
To me it looks like the follower leaves the game as soon as all his script are done and therefore ignoring the Quitlist

**Comment by gtoilet** [comment]
set your minimum game time to alot to keep him in game till leader leaves

**Comment by Roycinger** [comment]
Would be an idea.
I guess this is kind of a case of works as intended.
