### ISSUE TITLE
Loss Of In-game Chat

### ISSUE THREAD

**Issue by AbbyRoad** [kolton/d2bot-with-kolbot#2718]
For the last few days D2 has not supported in-game chat (the "gem" on the game list screen has also disappeared).  That means the leader can no longer announce to the followers where it is (Kill XXX), so for much of the mf run  the followers sit in town doing nothing.

While Kolbot allows "LocalChat", would its use increase the risk of the bots being identified as being bots by Blizz?  Thanks!

**Comment by gtoilet** [comment]
you mean the gem activated thing?
i logged classic and its still there

**Comment by AbbyRoad** [comment]
I guess I should have clarified - In Expansion on US East (ladder & non-ladder) the gem is gone.  The ability to chat in-side games does not work in ladder games.  It still works in non-ladder games.  

The in-game chat for ladder games seems to have been down for a couple of days now, possibly since the game queue disappeared. (not certain about when it started).

Being a paranoid puppy, and never having used the LocalChat option before, I'd like to understand if it represents a Blizz monitoring risk.

**Comment by DarkHorseDre** [comment]
I've not played this or last ladder, but you may have been muted.
Some of the threads you can search here mention this - IIRC your toon/account gets banned from sending ingame messages for a while.
localchat is advised but only works for toons on the same pc

**Comment by AbbyRoad** [comment]
Thanks.

**Comment by gtoilet** [comment]
i dont rely on chats for take tps or kill
but as dre said could be muted wait it out i guess
