### ISSUE TITLE
Classic diablo - BOTmap - window has unexpectedly exited... starting profile 

### ISSUE THREAD

**Issue by Chris2301** [kolton/d2bot-with-kolbot#2723]
Hello, 

First try with kolbot and trying to get the maphack working, however I get the "window has unexpectedly exited... starting profile" once i try to start it

1. zipped it
2. added cdkey + profile according to youtube videos
3. Running d2bot as admin + windows 7 compat
4. Running diablo as admin + service pack 3 compat
5. Try and run and error appears
6. checked if there are logs, but there arent any (also not in event viewer)
7. used CCleaner registry tool but no luck
8. patch file in diablo folder says its version 14

9. out of options and asking you guys!! Thanks in advance!

![image](https://user-images.githubusercontent.com/34375616/90276767-bb60ca80-de64-11ea-9059-5acefa156776.png)

**Comment by gtoilet** [comment]
diablo 2 classic is ment for lod install
unless you know what your doing to work around it

**Comment by Chris2301** [comment]
Oké thanks so to verify I can run classic, but only with lod key included and installed?

**Comment by gtoilet** [comment]
when you install lod it will play classic mode yes
when you create char just dont make it expansion
