### ISSUE TITLE
Make barb check corpses (with Find Item skill) of all types of monsters

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2743]
Subj.

Seems that barb checks only non-normal (minions/champions/unique) monsters's corpses with Find Item skill.
Is it possible to make barb check corpses of normal monsters?
It can be very iseful in some locations (like Cow, River of Flame etc).

I tried to change
`	Config.ClearType = 0xF;									// 0xF = skip normal, 0x7 = champions/bosses, 0 = all`
to:
`	Config.ClearType = 0xF;									// 0xF = skip normal, 0x7 = champions/bosses, 0 = all`
(in character config)
And it affects on barb's choice which monsters to attack/kill.
But it doesn't affect on Find Item.

I also looked into Barbarian.js (from: KolBot\D2BS\KolBot\Libs\Common\Attacks\) and found there some notations about "type":
`if ([345, 346, 347].indexOf(unit.classid) === -1 && unit.spectype === 0)`
(It's at: CorpseLoop)
But (seems) it's nothing to change in this string (or maybe I'm mistaken).

Can you help me?

**Comment by DarkHorseDre** [comment]
I havent looked at the code but it is spectype that the barb is checking - you should just remove the spectype check completely to have it check all mobs

also, spectype is not an integer, and 0 may be plain mobs (and not others) and the comparison operator would need to be different - just take out that last part ( && unit.spectype === 0), or use the correct combination to represent all mobs (altho spectype has a bug)

**Comment by ARkaine2** [comment]
After removing
`unit.spectype === 0`
Barb stopped to check corpses at all.

I tried to set it to: 
`unit.spectype == 0`
-- but not difference (still doesn't work [doesn't check any corpses]).

Also found this thread (https://github.com/kolton/d2bot-with-kolbot/issues/2040) where spectypes are described.
And changed to:
`unit.spectype == 0x0`
-- still no success.

I read this (https://github.com/kolton/d2bot-with-kolbot/issues/724) thread (with your detailed answering and trying to help).
And changed.

		if (monster) {
			do {
				if (getDistance(me, monster) <= range && Attack.checkMonster(monster) && !checkCollision(me, monster, 0x4) &&
						(Attack.checkResist(monster, Attack.getSkillElement(Config.AttackSkill[(monster.spectype & 0) ? 1 : 3])) ||
						(Config.AttackSkill[3] > -1 && Attack.checkResist(monster, Attack.getSkillElement(Config.AttackSkill[3]))))) {
					return true;
				}
			} while (monster.getNext());
		}

But it doesn't work.

And here (https://github.com/kolton/d2bot-with-kolbot/issues/948) I found some interesting suggestion about:

> ```
> Config.AttackSkill[1] = X; // Primary skill to bosses.
> Config.AttackSkill[3] = X; // Primary skill to others.
> ```
> Replace X with Skill Find ID. I know I used this back in the days and it worked for me.

But I prefer to use War Cry as attack skill.
So, if we'll go this way, the question is:
How to make barb ust both skills -- War Cry (or another attack skill) on alive enemies and Find Item on (all) corpses?

**Comment by DarkHorseDre** [comment]
good to see you checking posts bro ^^

ok so I fired that previous post off without looking (or thinking!) but WE should have caught the obvious:

This is looking at 3 specific classids - you can check kolbot/sdk/monster classID's.txt and then understand whats happening here:
if ([345, 346, 347].indexOf(unit.classid) === -1 && unit.spectype === 0) {
	return false;
}

once you've understood that you'll realise what those 2 checks that part of checkcorpse is doing.

Try to comment out this whole part of checkcorpse:
/* if ([345, 346, 347].indexOf(unit.classid) === -1 && unit.spectype === 0) {
	return false;
} */

as for spectype & 0x7 (notice the difference between & and == or ===) I dont have time but I'm guessing those entries are about getting the bot to target bosses and not normal mobs (spectype === 0)

I think it didnt work before because you didnt look at the whole file - you kinda need to do that always..

**Comment by ARkaine2** [comment]
**DarkHorseDre,** THANK YOU VERY MUCH! 
Barb became God of Item Finding. :)))

Removing described by you part of code even fixed this (https://github.com/kolton/d2bot-with-kolbot/issues/663) lag/delay problem.

**Comment by DarkHorseDre** [comment]
gg - just ensure you watch it do a full run multiple times as not sure about barb item find..

Hmm that delay issue is one I've seen mentioned a few times - not sure avoiding spectype will avoid it (I suspect ping time and cast code may be at fault) - but if it's working: gg!  just keep an eye on it ;)

**Comment by Raywl** [comment]
Hey guys, I followed this and now my barb does cast "Item FInd" on every corpse.
Somehow another issue more common to appear is, the Barb will try corpse in the unaccessible place(Storm Casters in Lava or behind a wall...). And Barb would stuck there for a long while and may miss the MF team unitil the script ended...
Sometimes MF team may also appear to get stuck by Storm Casters behind the wall too, but I searched out this post: https://github.com/kolton/d2bot-with-kolbot/issues/2898
It seems resolved the issue for MF team, but it didn't stop the Barb casting "Item Find" on corpse in the Lava.
Any idea to fix this? 


> good to see you checking posts bro ^^
> 
> ok so I fired that previous post off without looking (or thinking!) but WE should have caught the obvious:
> 
> This is looking at 3 specific classids - you can check kolbot/sdk/monster classID's.txt and then understand whats happening here:
> if ([345, 346, 347].indexOf(unit.classid) === -1 && unit.spectype === 0) {
> return false;
> }
> 
> once you've understood that you'll realise what those 2 checks that part of checkcorpse is doing.
> 
> Try to comment out this whole part of checkcorpse:
> /* if ([345, 346, 347].indexOf(unit.classid) === -1 && unit.spectype === 0) {
> return false;
> } */
> 
> as for spectype & 0x7 (notice the difference between & and == or ===) I dont have time but I'm guessing those entries are about getting the bot to target bosses and not normal mobs (spectype === 0)
> 
> I think it didnt work before because you didnt look at the whole file - you kinda need to do that always..
