### ISSUE TITLE
(Paladin) PreCast problem

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2746]
I found this thread (https://github.com/kolton/d2bot-with-kolbot/issues/1064), so not only me met this problem.

I'll try to describle problem in more detail.

So:
I have paladin.
Connection that gives me about 200--300 ping.
Paladin swaps to CtA to cast: Battle Command, Battle Orders, Holy Shield.
And seems that paladin switches between skills / swaps weapon too fast -- so he can't get BO or HS.
And he tries to cast BO/HS during battle / during his way more and more.

I tried to change -- 
```
	// SPEEDUP CONFIG
	Config.FCR = n;											// From 0 (disable) to 255 (maximum)
```
But it doesn't affect on this situation.

So my suggestion is that it can be added delay between 
```
			Skill.cast(155, 0); // Battle Command
			Skill.cast(149, 0); // Battle Orders
```
(it's from Precast.js)

But how to do that? 
Thanks.

**Comment by ARkaine2** [comment]
Fixed. I simple added delay and seems that it works fine.

```
			Skill.cast(155, 0); // Battle Command
			delay(20);
			Skill.cast(149, 0); // Battle Orders
			delay(20);
```

**Comment by DarkHorseDre** [comment]
yep, the word delay was a massive hint ;)

you will want to make the ping relative to your personal ping by adding me.ping (its done throughout the code you have so you can check that)
