### ISSUE TITLE
Low Quality Pickit

### ISSUE THREAD

**Issue by Chewbucks** [kolton/d2bot-with-kolbot#2758]
Alright I've been trying to do some research but I have no luck. I know you can upgrade Cracked or Damaged equipment like armor and weapons. How would I write in so my guy would pick up like Damaged Archon Plates?

**Comment by medgram** [comment]
You have something like this in pickup kolton.nip:

> [quality] == superior

maybe just replace == by < like:

> [quality] < superior

**Comment by Chewbucks** [comment]
tyvm sir
