### ISSUE TITLE
How does bot (MFleader) says clearlevel #?

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2767]
I'd wish to insert phrase clearlevel # into non-ClearAnyArea script.

I found that command
`say(me.area);`
Says area number.

But how to mayke bot say
clearlevel #
?

I tried:
`say("clearlevel"; me.area);`
But it's wrong.
And I coudn't find example in another scripts.

Please help.

**Comment by DarkHorseDre** [comment]
> I tried:
> `say("clearlevel"; me.area);`

> And I coudn't find example in another scripts.
> 

text in "" are strings, whereas, as you know, me.area is a variable.  There are examples in almost ALL of the kolbot files of how the bot does what you are seeking. Take the time to check them out - will save you and us time and you will learn something ^^
