### ISSUE TITLE
How to Move Followers to a Different Town After Killing Baal?

### ISSUE THREAD

**Issue by AbbyRoad** [kolton/d2bot-with-kolbot#2781]
One of my bots shops at Anya throughout the run, so at the end of killing Baal, I need two followers to wait in a different town while the lead does Chestmania.  What do I need to change to get the two followers to move from Act 5 Town to, let say, Act 1 Town?  

Thanks!

**Comment by ARkaine2** [comment]
This will depend on used by you script.

Anyway you should add
`Town.goToTown(1);`
to bot's script.
