### ISSUE TITLE
Last version

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2786]
Where can I download it?

I read a lot about it, but I don't know where to find it and it's date.

**Comment by gtoilet** [comment]
left of the issues click the code then click where it says master is that what your after the 113 versions or like the 15633 or what ever last version was not this current version of 2067100

**Comment by ARkaine2** [comment]
> left of the issues click the code then click where it says master

So it's here.

![image](https://user-images.githubusercontent.com/31447095/94164440-b7778d80-fe91-11ea-99ae-17e1fa1e537e.png)

I supposed that maybe somewhere are additional repositories and I thought that there should be more versions and I didn't check there.
Now I downloaded last version (just for checking) from there and it's newer than was mine.
Thanks.

**Comment by gtoilet** [comment]
the newest version is 2067100
last version i had was 15633
