### ISSUE TITLE
Follower does not do anything in game

### ISSUE THREAD

**Issue by quuuick** [kolton/d2bot-with-kolbot#2790]
Hello,

Sorry in advance - I am very new to Github and botting in general. I will try to be brief with my problem.

**Issue**: I have a Leader and a Follower. The idea was to set the Leader to run CS and Baal, and Follower only to leech. The Leader's config works flawlessly with no issue. Problem is that Follower does not move in game at all. However, it joins and quits the game properly.

This is code for character config of Follower:

`Config.Leader = "SooSoo"; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
	Config.QuitList = ["SooSoo"]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];
	Config.QuitListMode = 1; // 0 = use character names; 1 = use profile names (all profiles must run on the same computer).
	Config.QuitListDelay = []; // Quit the game with random delay in case of using Config.QuitList. Example: Config.QuitListDelay = [1, 10]; will exit with random delay between 1 and 10 seconds.

	Scripts.TristramLeech = false; // Enters Tristram, attempts to stay close to the leader and will try and help kill.
	Scripts.TravincalLeech = false; // Enters portal at back of Travincal.
		Config.TravincalLeech.Helper = true; // If set to true the character will teleport to the stairs and help attack.
	Scripts.MFHelper = false; // Run the same MF run as the MFLeader. Leader must have Config.MFLeader = true
	Scripts.Wakka = true; // Walking chaos leecher with auto leader assignment, stays at safe distance from the leader
		Config.Wakka.Wait = 1; // Minutes to wait for leader
	Scripts.SealLeecher = false; // Enter safe portals to Chaos. Leader should run SealLeader.
	Scripts.DiabloHelper = false; // Chaos helper, kills monsters and doesn't open seals on its own.
		Config.DiabloHelper.Wait = 120; // Seconds to wait for a runner to be in Chaos. If Config.Leader is set, it will wait only for the leader.
		Config.DiabloHelper.Entrance = true; // Start from entrance. Set to false to start from star.
		Config.DiabloHelper.SkipTP = false; // Don't wait for town portal and directly head to chaos. It will clear monsters around chaos entrance and wait for the runner.
		Config.DiabloHelper.SkipIfBaal = false; // End script if there are party members in a Baal run.
		Config.DiabloHelper.OpenSeals = false; // Open seals as the helper
		Config.DiabloHelper.SafePrecast = false; // take random WP to safely precast
		Config.DiabloHelper.SealOrder = ["vizier", "seis", "infector"]; // the order in which to clear the seals. If seals are excluded, they won't be checked unless diablo fails to appear
		Config.DiabloHelper.RecheckSeals = false; // Teleport to each seal and double-check that it was opened and boss was killed if Diablo doesn't appear
	Scripts.AutoBaal = true; // Baal leecher with auto leader assignment
		Config.AutoBaal.FindShrine = 2; // false = disabled, 1 = search after hot tp message, 2 = search as soon as leader is found
		Config.AutoBaal.LeechSpot = [15115, 5050]; // X, Y coords of Throne Room leech spot
		Config.AutoBaal.LongRangeSupport = false; // Cast long distance skills from a safe spot
	Scripts.BaalHelper = false;
		Config.BaalHelper.Wait = 120; // Seconds to wait for a runner to be in Throne
		Config.BaalHelper.KillNihlathak = false; // Kill Nihlathak before going to Throne
		Config.BaalHelper.FastChaos = false; // Kill Diablo before going to Throne
		Config.BaalHelper.DollQuit = false; // End script if Dolls (Undead Soul Killers) are found.
		Config.BaalHelper.KillBaal = true; // Kill Baal. If set to false, you must configure Config.QuitList or the bot will wait indefinitely.
		Config.BaalHelper.SkipTP = false; // Don't wait for a TP, go to WSK3 and wait for someone to go to throne. Anti PK measure.
	Scripts.Follower = true; // Script that follows a manually played leader around like a merc. For a list of commands, see Follower.js
`

I have also set edited the D2BotFollow.dbj acccordingly:
`var JoinSettings = {
	"SooSoo": ["EIonMusk"]`

**Why the Follower does not follow the Leader in game, and how can I solve that?**

**Comment by swtop** [comment]
be set the profile name in the D2BotFollow.dbj ,doesnt the char name

**Comment by quuuick** [comment]
> be set the profile name in the D2BotFollow.dbj ,doesn't the char name

Config name and characters name are matching.

**Comment by quuuick** [comment]
Here is the image from follower's console. I still can't figura out why Follower is not moving.
<a href="https://ibb.co/g6q0WXj"><img src="https://i.ibb.co/hCQGdn7/Screenshot-23.png" alt="Screenshot-23" border="0"></a>

**Comment by ARkaine2** [comment]
Disable UserAddon and use another script.

**Comment by quuuick** [comment]
> Disable UserAddon and use another script.

Jesus christ! IT ACTUALLY WORKED!

Thank you!!! Could not solve this for a week almost...
