### ISSUE TITLE
if i want a item what do i need to do

### ISSUE THREAD

**Issue by koedguden** [kolton/d2bot-with-kolbot#2791]
// == Sigon's Complete Steel ==
name] == greathelm && [quality] == set # [maxmana] == 30
[name] == gothicplate && [quality] == set # [enhanceddefense] == 25 && [lightresist] == 30
[name] == greaves && [quality] == set # [frw] == 20 && [coldresist] == 40
[name] == towershield && [quality] == set # [itemaddskilltab] == 1 && [toblock] == 20
[name] == platedbelt && [quality] == set # [fireresist] == 20 && [maxhp] == 20
[name] == gauntlets && [quality] == set # [tohit] == 20 && [strength] == 10
will my bot take these items?

**Comment by gtoilet** [comment]
yes bot will pick them up as shown above

put     //
in front like below to NOT keep item

//[name] == gauntlets && [quality] == set # [tohit] == 20 && [strength] == 10
will my bot take these items? = NO

**Comment by koedguden** [comment]
Thanks, iam new to this

**Comment by koedguden** [comment]
@gtoilet can i set a limit on how many i want?
