### ISSUE TITLE
Bot breaks after Life Chicken

### ISSUE THREAD

**Issue by bozodude** [kolton/d2bot-with-kolbot#2801]
After any of my bots perform a Life Chicken (leaving game and rejoined due to low life) they go to the waypoint and are in the I am Ready state (then just stand there doing nothing) instead of joining back up with the leader. I have to restart every bot in order for them to sync back up again. I use AutoSmurf script as I am new to Kolbot and read it was good to use this for characters from scratch for leveling.

As a note: I added a couple lines for Life Chicken to restart profile instead of Save & Quitting but that did not fix the issue. 

Here are the character configs/any other relevant pastes. Please let me know if you need any additional information and thanks ahead of time for any help!

Char Config (Leader Sorceress) - [Here](https://pastebin.com/VPqqzZXK)
D2BotLead.dbj Config - [Here](https://pastebin.com/n6k2fjY8)
D2BotFollow.dbj Config - [Here](https://pastebin.com/U6pScPTv)

Other than that, most configs were left largely alone. All I did was want four bots to level together (I made 4 profiles, 4 separate accounts.) That's it, barebones. Didn't change much else besides Char configs and lead/follow configs.

***EDIT*** A similar issue with Life Chicken is if the Leader Life Chicken's out, the bot will make a new game while the followers stay in the previous one doing nothing (Waiting for Party) while the Leader waits in the new game doing nothing (Waiting for Party). The Followers will only join the new game if I stop their script/relaunch.

**Comment by Sirk74** [comment]
This one is quite easy.
In Char Config, on line 28 (Config.QuitList) you listed character names. On line 29 (Config.QuitListMode), you chose "1", that means using profile names in the above line.
Either choose "0" on line 29 or use profile names on line 28.

**Comment by bozodude** [comment]
> This one is quite easy.
> In Char Config, on line 28 (Config.QuitList) you listed character names. On line 29 (Config.QuitListMode), you chose "1", that means using profile names in the above line.
> Either choose "0" on line 29 or use profile names on line 28.

Ahhh, yeah. Thank you I actually figured it out in the meantime. Such a simple mistake! Thank you for your help.
