### ISSUE TITLE
Using wp instead going to npc while changing acts

### ISSUE THREAD

**Issue by sasquach15** [kolton/d2bot-with-kolbot#2803]
Any point in script when i can switch this?
Getting constantly crash when my bot ends run in act2 and then use warriv to start in act 1 next run. When i go to wp i got no crash

**Comment by DarkHorseDre** [comment]
in pather.js there is this block of code:

```js
				if (me.area === 40 && npc && getDistance(me, npc) < 50) {
					if (npc && npc.openMenu()) {
						Misc.useMenu(0x0D37);

						if (!Misc.poll(function () {
							return me.area === 1;
						}, 2000, 100)) {
							throw new Error("Failed to go to act 1 using Warriv");
						}
					}
				}
```
try and comment that all out (with /* commented text */) and that leave the `Town.move("waypoint");` that follows

**Comment by sasquach15** [comment]
> in pather.js there is this block of code:
> 
> ```js
> 				if (me.area === 40 && npc && getDistance(me, npc) < 50) {
> 					if (npc && npc.openMenu()) {
> 						Misc.useMenu(0x0D37);
> 
> 						if (!Misc.poll(function () {
> 							return me.area === 1;
> 						}, 2000, 100)) {
> 							throw new Error("Failed to go to act 1 using Warriv");
> 						}
> 					}
> 				}
> ```
> 
> try and comment that all out (with /* commented text */) and that leave the `Town.move("waypoint");` that follows

Worked perfectly, thanks! Perhaps you can help with my other issue? Been weeks and we cant figure it out

https://github.com/kolton/d2bot-with-kolbot/issues/2432

2 last posts with videos shows current issue

**Comment by DarkHorseDre** [comment]
uff dunno - are you using the kolbot from this git or from blizzhackers?
