### ISSUE TITLE
Make bot restart profile instead of exit game on chicken

### ISSUE THREAD

**Issue by ARkaine2** [kolton/d2bot-with-kolbot#2809]
I followed instructions which are described here (https://github.com/blizzhackers/documentation/blob/master/kolbot/MiscellaneousOptions.md#lifechicken-restart-profile) 
but bot lefts game just after start.

Can it be fixed? 
Please help.

I suppose that's NOT because of:
Adding 
`LifeChickenRestart: false,`
in Config.js 

And not because of:
`Config.LifeChickenRestart = true; `
In char config.

Probably it's because of:
`Config.LifeChickenRestart ? D2Bot.restart() : this.exit();`
in ToolsThread.js

**Comment by gr33k** [comment]
Any solution to this? I've followed the same directions to find that it simply does not work :(

the line in ToolsThread.js has moved in the current version it seems, but it's not hard to figure out where you need to put it (L: 555 for me). Despite being put in the expected place - it doesn't rejoin the game after chickening.
