### ISSUE TITLE
Enchant problem

### ISSUE THREAD

**Issue by tumpelo71** [kolton/d2bot-with-kolbot#281]
I have litle problem, enchant startup and works but not talking about instructions.
The chant works with the command and the cows also works if u know right command, but when the new player comes to "the Enchant char" he does not speak anything and does not give instructions
sry my bad english.. 

sometimes says only commands: nothing else

edit: D2botsharp version 14.8.3.59

**Comment by LeMule** [comment]
Chat is removed afaik, for your own safety.
I've seen some public games uppend the "!" before their chantress' chat
messages but I can't confirm whether this is safe or not.

**Comment by tumpelo71** [comment]
oki ty :)
