### ISSUE TITLE
Kill boss packs ROF & CS

### ISSUE THREAD

**Issue by MoneyMoney33** [kolton/d2bot-with-kolbot#2837]
I used the idea from the ghost script that is located in pather.js line 24
````
if (Config.Countess.KillGhosts && [21, 22, 23, 24, 25].indexOf(me.area) > -1) {
	monList = Attack.getMob(38, 0, 30);

	if (monList) {
		Attack.clearList(monList);
	}
}
````

Tried adding below it.     I know right now it is only river of flame but would like to be able to do river of flame and CS if possible adding more monsters like Special venoms and Special casters.

```
if (Config.Diablo.kill && [107].indexOf(me.area) > -1) {
	monList = Attack.getMob(189, 0, 30);
       monList = Attack.getMob(309, 0, 30);


	if (monList) {
		Attack.clearList(monList);
	}
}
```

Also added to common/config under Diablo `kill: = false;`

then under character config I added in under the diablo script
`config.diablo.kill == true;`

**Comment by DarkHorseDre** [comment]
That function you copied is for killing a specific single mob type with a single classid.  it wont do what you want so you have to use a different function (check attack.js), add your own function, or repeat that if block for each classid ;)
(but that could cause unexpected issues)

oh and setting monList twice has zero effect - the last value to be updated will be used.

**Comment by MoneyMoney33** [comment]
Yes, I had updated it to now do

monList = Attack.getMob([189, 309] 0, 30);

this fixed it so it does both of the monster id.

**Comment by MoneyMoney33** [comment]
> That function you copied is for killing a specific single mob type with a single classid. it wont do what you want so you have to use a different function (check attack.js), add your own function, or repeat that if block for each classid ;)
> (but that could cause unexpected issues)
> 
> oh and setting monList twice has zero effect - the last value to be updated will be used.


Yes, I had updated it to now do


```
if (Config.Diablo.kill && me.area === 107) {
 Config.ClearType = 0xF;
	monList = Attack.getMob([189, 309] 0, 30);


	if (monList) {
 Config.ClearType = 0xF;
                Pather.makePortal();
		Attack.clearList(monList);
	}
}
```

this fixed it so it does both of the monster id's that I want and it also only does River of Flame. 

My issue is I want it to clear 0xF; Only and I want it to make a portal right next to the monster.  Right now it makes it far away and clears all monsterid 189 and 309 not just 0xF (It is 0xF in my char config)
