### ISSUE TITLE
BAN WAVE IN PROGRESS - DO NOT RUN KOLBOT

### ISSUE THREAD

**Issue by AbbyRoad** [kolton/d2bot-with-kolbot#2848]
Title says it all.

**Comment by cezars** [comment]
8 CD-Keys gone... this wave got me, it`s a first for everithing

**Comment by AbbyRoad** [comment]
I guess a lot of people using Sonic were hit.  I was using autosmurf with the default settings when I got hit.  Such is life.

**Comment by cezars** [comment]
autosmurf with some changes

**Comment by AbbyRoad** [comment]
Cezars -

Before trying to run again, these are the changes I was planning to make.  Had you modified any of these when you were running Autosmurf?
Config.LocalChat.Mode = 1 (was 2)
Config.PacketShopping = false (was true)
Config.FCR = 0 (was 255)
Config.FHR = 0 (was 255)
Config.FBR = 0 (was 255)
Config.IAS = 0 (was 255)
Config.PacketCasting = 0 (was 2)

**Comment by cezars** [comment]
no, no changes on that. Let me know how this changes work for you but 255 for sure is one of the problem

And if the settings for local chat is not present on the config what is the default setting and were is set ?????

**Comment by gtoilet** [comment]
rip to you all i got flagged day before
all keys and toons still alive

**Comment by AbbyRoad** [comment]
gtoilet

Gratz.
