### ISSUE TITLE
Bot doesn’t follow pickit list

### ISSUE THREAD

**Issue by alisci99** [kolton/d2bot-with-kolbot#2851]

**Comment by DarkHorseDre** [comment]
please paste your character config and pickit file to pastebin.com or similar, and paste the links to them here (please dont paste your file text directly here)

**Comment by alisci99** [comment]
hi, i'm linking you the character configuration and the pickitlist as you asked, hope you'll find the time to help me 
https://pastebin.com/yhzAbgSB : pickit list
https://pastebin.com/eR7DcEGS : character config

**Comment by DarkHorseDre** [comment]
What difficulty and area were you playing?

remember countess can drop RAL as max in normal..

I can see runes below tal are commented out..

"kolton.nip" is the one the config is looking for - if the linked pickit is named that, then it will work.

you have to be sure the items that drop match pickit - the bot can determine item type and a few other values without picking.
what didnt it pick that you think it should?

**Comment by alisci99** [comment]
i'm playing nightmare, and i have seen the countess drop hel rune and shael rune, both without // before them and i also manually checked how many of them i had, and i had only one of each. 
the pickit list i linked is kolton.nip the same in character configuration, that's why i'm so concerned that the bot might be ignoring much more item, and not just some rune.
can you think of any other possible error?

**Comment by DarkHorseDre** [comment]
Hmm... not really - other than you have maxquantity set, but I assume you dont have any hel or shael in stash..

do you have any errors showing in console when you restart/start the bot?

**Comment by alisci99** [comment]
never had an error like that... i spent many hours re-checking those two lists but since i'm new using it i was thinking someone more used to kolbot may point out some uncommon mistake or error

**Comment by DarkHorseDre** [comment]
yes, we all know why you created this post.

you didn't answer - did you have any shael/hel/other rune in stash at all?

start your bot, press home key, take a screenshot and post here plx

**Comment by alisci99** [comment]
yes i had checked, and sorry but nothing happens when i press the home button

**Comment by alisci99** [comment]
if i were to guess, i'd say the problem might be that the bot isn't reading the pickit list as it is now, but still the original one

**Comment by DarkHorseDre** [comment]
when it starts, do you see any text in the centre top part of the game screen?

if no, press the home key and the text console should appear.

>if i were to guess, i'd say the problem might be that the bot isn't reading the pickit list as it is now, but still the original one


easy way to test - rename the kolton.nip in \pickit folder and it should give you an error in the console

**Comment by alisci99** [comment]
ok i did as you said, i tried to rename it and since i wasn't able to rename it without opening it with notepad, i opened it, renamed and then checked in the folder if it was renamed. well it wasn't so i tried to doubleclick it and it opened it again.
the problem is that the file it opened was the original kolton.nip, wich means that all the editing i have been doing till now were only saved in notepad, but never edited the saved file kolbot reads.
can you please tell me the right way of editing?

**Comment by alisci99** [comment]
i usually do it that way: i edit and then press save in notepad (the floppy disc button).
am i forgetting some passage to make it permanent or making any mistake?

**Comment by alisci99** [comment]
okk i managed to make it permanent, thank you for everything, i needed someone who knows what kolbot is to speak to. bb and gl ;)

**Comment by DarkHorseDre** [comment]
lol it wasn't a kolbot issue ;)

glad you got it saved - please click the 'close' button to close this issue.
