### ISSUE TITLE
Drop gold

### ISSUE THREAD

**Issue by BpEoEnRg** [kolton/d2bot-with-kolbot#2860]
I wanted to make a script that joins games, counts the players, and drops 10k gold for each player in the game while saying some holliday phrases. The problem is im not sure how to drop the gold.

Code:   https://pastebin.com/XrNqscQA

I have very limited coding experience and none with js and would appreciate any help. I plan to start manually joining some games, letting the script run, and then working on some more features while waiting to create the next game. Like logging the players to a json file in an array when they are added to the drop count so I can check the player names against the file before droping. I recently returned to d2 so I only have around 5mil between 2  chars and wanna try to get as many real players as i can before Christmas.

**Comment by gtoilet** [comment]
can look at the gamble.js is how i ripped this to drop gold then run other scripts in the same game
https://pastebin.com/Kms6NM2t

**Comment by BpEoEnRg** [comment]
> can look at the gamble.js is how i ripped this to drop gold then run other scripts in the same game
> https://pastebin.com/Kms6NM2t

Thanks, your pastebin really helped. I'm editing the original code so it doesn't get confusing but I think it should work now. I'm gonna try it out tommrow after work.

**Comment by BpEoEnRg** [comment]
Solved:
var dropAmount = 10;
gold(dropAmount);


gold(10); would have the same effect

would drop 10 gold

I updated the pastebin with the semi working code. In a game of 3 players, bot included, it droped 1 stack of gold not 2.
