### ISSUE TITLE
Question about enigma runewords

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2902]
I want the bot keep enigma runeword so ....

Do i have to write it like that?

Config.KeepRunewords.push("[Name] == crystalsword # [skillteleport] == 1");

Or

Config.KeepRunewords.push("[Name] == crystalsword # [plusskillteleport] == 1");

Not sure if [skillteleport] or [plusskillteleport] 

Thx for answer!

**Comment by cezars** [comment]
1) 
Config.KeepRunewords.push("[type] == armor # [plusskillteleport] == 1");
2)
i think is plusskillteleport same as cta plusskillbattleorders (that is working)

**Comment by benp100** [comment]
Thx very much ;)

**Comment by cezars** [comment]
Leave a msg on this topic if it`s working so in the future every one know
