### ISSUE TITLE
How to keep only one monarch in inventory for cubing?

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2904]
How to setup bot for keeping only 1 monarch for cubing?
Maxquantity == 1 in pickit doesn't look like to work.
My bot just stack a lot of monarch in inventory and i'm missing space. I would keep only one, cubing, runeword, and stack on the mule at  one time. Thx.

**Comment by cezars** [comment]
[name] == monarch && [quality] <= superior # [sockets] == 4 # [maxquantity] == 1
