### ISSUE TITLE
Runewords question

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2907]
In this exemple:

Config.Recipes.push([Recipe.Socket.Weapon, "colossusvoulge", Roll.Eth]); 

Config.Runewords.push([Runeword.Insight, "colossusvoulge"]); 

Config.KeepRunewords.push("[type] == polearm # [meditationaura] >= XX");

In the pickit, do i need to add colossus voulge eth 0 sock and colossus voulge eth 4 sock?  If i don't put the 0 sock in pickit, does the bot will loot it because of the recipe.puch/recipe socked? And the same question for runeword, if i got the socket 4 from the recipe.push, do i need to put the 4 sock in pickit or the bot will make the runeword because of config runeword? 

If i need to put the colossus voulge 0 sock and 4 sock in pickit, it is possible to only keep 1 voulge (0 or 4) in inventory ([maxquantity] ==1), because if i enter both in pickit (0 and 4 sock), he will loot 1 with 0 sock and a other one with 4 sock, so total 2 voulge.... i suppose then ... and it take some place in inventory.

Thx in advance for the answer.

**Comment by dynnast** [comment]
The bot should keep any cv with insight in your inv that meets the meditation aura requirement, it doesn't look at sockets anymore at that time.

[name] == colossusvoulge && [flag] == ethereal # ([sockets] == 0 || [sockets] == 4)  # [maxquantity] == 1

this will keep any ethereal cv that has either 0 or 4 sockets but will stop when it has 1

**Comment by benp100** [comment]
Thx very much!
