### ISSUE TITLE
question about pickit

### ISSUE THREAD

**Issue by Grooner** [kolton/d2bot-with-kolbot#2908]
Hi,

I have been looking at some premade pickits, and they have lines such as:

[Type] == Axe && ([Quality] == Rare || [Quality] == Crafted) && [Flag] == ethereal # ([225] >= 1 || [224] >= 1 || [218] >= 1) && [enhanceddamage] >= 200 && [Sockets] >= 2

What do the 225, 224 and 218 refer to?

**Comment by gtoilet** [comment]
maby
NTIPAliasStat["itemtohitpercentperlevel"] = 225;
NTIPAliasStat["itemtohitperlevel"] = 224;
NTIPAliasStat["itemmaxdamageperlevel"] = 218;


all stat related things can be found in the NTItemAlias.dbl

**Comment by Grooner** [comment]
Thanks!  I was looking for the itemalias also, perfect!
