### ISSUE TITLE
Autosmurf  - it is possible to skip anya quest

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2913]
My sorc at nightmare is not enough strong to tp to anya with autosmurf. She is chicken every run. I want to know where in the scrip i can skip anya quest and what to change exacly.

Thx for answer!

**Comment by jstall6** [comment]
im sorry i know this doesnth elp but could you point me in the direction to get the scripts for autosmurf ive found some topics but nothing actually made sense

**Comment by benp100** [comment]
> im sorry i know this doesnth elp but could you point me in the direction to get the scripts for autosmurf ive found some topics but nothing actually made sense

https://github.com/blizzhackers/autosmurf

Don't try to add it to your actually kolbot. Redownload it like a new kolbot .... one file for kolbot master and other one is your kolbot autosmurf. You will save many time loll ;) and if you try to run your smurf on kolbot master later, maybee you will get some crash error. REMEMBER THIS: just clear internet scrap and registry with ccleaner, and crash will be fix. I think, that because he put some temporaly file in registry and that make your other bot crash later ;) its the same thing when you play hardcore and your caracter die, if you create an other one with the same name, sript will crash some time. Ccleaner will fix that ;) hope i had help you!

**Comment by jstall6** [comment]
i see i was looking at my phone earlier i didnt see the download for autosmurf until i got on my pc. im assuming your just testing it out for now maybe change the level that your characters leave normal baal and theyll be high enough to get through anya. whats your jsp by the way im going to set this up tommorow would like to trade thoughts on getting it to run perfect

**Comment by benp100** [comment]
I had looked for keep my char more longer in normal baal for getting more lvl but i can't find it in script. And yes i had already try it, 3 char at lvl 55 in like +/-15h. But my sorc lead died at anya nm when tp and im playing hardcore so i just lvl pally and barb with my 93 sorc loll. My jsp is ben200 ;) just tell me if you find how to keep my char more longer on norm baal run. I will make a recheck to.

**Comment by benp100** [comment]
And with pc, you will be able to download the zip file on your right, hit the (...) and there we go!
