### ISSUE TITLE
Strict warning(162) file(kolbot\libs\common\storage.js:125

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2948]
I got this error : [Strict Warning (162)] File(kolbot\libs\common\storage.js:125) reference to undefined property item.sizex

The bot running well instead of this error, but i would like to set it. I get this error when bot starting the game and go talk with drognan in act2. Anyone got idea? Thx.

**Comment by gtoilet** [comment]
did you have the cube at that time?
might have been trying to stash amulet/staff to make for quest

**Comment by benp100** [comment]
Haa well, i got the cube but char equip amulet hahaha. Thx a lot, i will try to unequip amulet and see if solve issue.

**Comment by benp100** [comment]
This was exacly that, thx so much. Dosn't figure what she 's equiped, running on autosmurf ;)
