### ISSUE TITLE
Pickit/Shopbot. Can't shopping at Drognan.

### ISSUE THREAD

**Issue by spiilmusic** [kolton/d2bot-with-kolbot#295]
Hi there.
I have the following problem:
Bot just goes to Sewer Level 2 and staying. Nothing happens, but cycle counters increase.
Please explain what can be wrong? Also I can do some debug, if you show me which files to watch.

Regards :)

**Comment by spiilmusic** [comment]
Hm. I have another one bug. It seems these are similar bugs. In act 2 bot can't find any healer / potion seller NPC. And just repeatedly open portal -> find seller -> go back to portal -> open portal... Until the scrolls run out. I think it refers to Town.js

**Comment by StoneOfJordan** [comment]
Shop botting doesn't work anymore. That script will never work again. Try Anya.

**Comment by spiilmusic** [comment]
Ok, I see. Thank you for the answer, @StoneOfJordan. 
No, Anya wont help me, I need 2 sock bone wand with +3 bone spear.
So what about troubles with healer / pots seller in 2 act?

**Comment by StoneOfJordan** [comment]
Steps to reproduce? Just tried it and it worked just fine.

**Comment by spiilmusic** [comment]
I'm not sure. Just set Config.TownCheck = true, and after a few hours I've noticed that my bot just clears some areas without potions and without scrolls until the Config.LifeChicken = 30; is triggered :D
After that the bot just stuck in the middle of Lut Gholein (somewhere between WP and Drognan)
It reproduced if I use TownCheck with

 `Scripts.ClearAnyArea = true; 
Config.ClearAnyArea.AreaList = [47,48,49]; // All 2Act Sewer levels
Scripts.Radament = true;`
I think it reproduces any way. Bot can't find NPC when returned to the town. In my case it NEVER bought potions at 2 act :( 

Ok, I'll try to do some debug with this.
