### ISSUE TITLE
It is possible to tell the bot to not auto equip a specific item?

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2950]
Im running auto smurf and auto equip. My bot is equiping amulet of the viper who is needed for act2 quest. If i unequip or stash it, it auto equip again. Is there any command to not equip the specific item? I can write the line with no problem and add it at the good place. The only thing i need is a command key if exist. 

Thx!

**Comment by gtoilet** [comment]
if your running auto equip why not just have them wear any crap amulet to take up the slot
so when your team gets that far and they pick up the amulet it goes the inventory like your wanting

if thats not something your after then im sure the line can be made up to when it picks it up to go inventory>equip slot

**Comment by benp100** [comment]
Yeah, that what i make but with 4 bot team,  she didnt loot any amy yet loll

**Comment by benp100** [comment]
She just finally loot one hahaha and before act2. All is goog now lol.
