### ISSUE TITLE
HC - Force Run/Walk 

### ISSUE THREAD

**Issue by OldMidgard** [kolton/d2bot-with-kolbot#2953]
I'm looking for a piece of code to force the to bot to walk no matter what. Since block chance drops to 25% when running i would rather have the bot walk as so to maintain max block at 75%.

I saw in pather.js there were a few mentions of "runwalk == 0" but changing those didn't seem to work.

anyone know how to make the but walk at all times and not run?

if so is there potential to have it run only in town and walk anywhere outside of town?

**Comment by gtoilet** [comment]
thats already implemented in new version
	Config.NoTele = false; // Restrict char from teleporting. Useful for low level/low mana chars
https://github.com/blizzhackers/kolbot

**Comment by gtoilet** [comment]
actually it does work ... open pather.js
find this line

			if (me.runwalk === 0 && me.stamina / me.staminamax * 100 >= 50) {
				me.runwalk = 1;
			}

swap the runwalk === 0 to 1 , and the runwalk = 1 to 0

or atleast my test made it walk after tele to spot and walk from there to clear cs

**Comment by OldMidgard** [comment]
you are correct! made the change it its functioning perfectly, thank you!
