### ISSUE TITLE
Diablo position

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2954]
I just make my own necro summoner script, for autosmurf,rewrite the pickit/xpac/skill, stat ...all is working fine. Now im trying to figure how i can change the positionning at the star in chaos sanctuary, where diablo spawn. He just stand exacly where diablo spawn, so i got mass of chicken. My sorc and barb is standing at a good place, the same place i want my necro to be to. My necro is setting as follow bot.

Any info are welcome.
Thx

**Comment by Skadwick** [comment]
Hey bud - not sure if you still have this issue.  Assuming you created a custom .js file for your script, you should be able to add a call to Pather.MoveTo(...)

From looking at other lines in the original Diablo.js file, something like the line below should work if added near the top of the diabloPrep section (or similar section in your custom script)

Side note, 7793, 5293 seems to be the coords that most characters are moved to in the diablo pre script.  Not sure if this is actually a good spot or not :P

`Pather.moveTo(7793, 5293, 3, getDistance(me, 7793, 5293) > 50);`

Alternatively, you could try casting a prep skill at a certain coord, which is what many classes do before engaging Diablo.

`Skill.cast(Config.AttackSkill[1], 0, 7793, 5293);`

This is just what I gather from a quick dig through a few scripts.  May be inaccurate, and you may need to play around with it a bit, but hopefully these are at least a good starting point :)

**Comment by benp100** [comment]
Yeah, i just try many different setup with these line, but anything work. I know that these line tell the position of the char, but it look like my necro script is not taken by the bot so probably he is running a default setup ( i suppose, and maybe it for the same reason he take the same position than the paly, because the script was writen for a paly as i read). I just ttried all suggestion you write already, but anything work lol. But thx anyway, its really appreciate. I think i will just let him chicken for some game still he take enough level for resist it, but that will be great if anyone got a solution. 

P.s. when i am changing coord in baal.js, that work. But in diablo.js, i dont know why, but not working

**Comment by benp100** [comment]
That what i try exacly:

break;
case 3: // Paladin
Skill.setSkill(Config.AttackSkill[2]);
Skill.cast(Config.AttackSkill[1], 1);

break;
case 5: // Druid
if (Config.AttackSkill[1] === 245) {
Skill.cast(Config.AttackSkill[1], 0, 7793, 5293);

break;

Change druid section for necro:

break;
case 5: // necro
if (Config.AttackSkill[1] === 66) {  // amplify damage
Skill.cast(Config.AttackSkill[1], 0, 7793, 5297);  //change coord here

Like i said, the sane change work in baal.js

**Comment by benp100** [comment]
Just to tell all folder are setted. Bot is already running, at the moment my 4 toon (sorc, barb, paly, necro are lvl 55). I had rewrite my autoequip pickit/ build, char.js etc. Everything just work very well. Any human action have be required at the moment. If i can set this little thing as the position on diablo, it will be set like perfect lol
