### ISSUE TITLE
Window has unexpectedly exited - D2botfollow repeatedly crashing at start

### ISSUE THREAD

**Issue by swettin** [kolton/d2bot-with-kolbot#2968]
Suddenly had an issue occur this afternoon that I cannot resolve on my own.

Restarted and updated my PC, then as soon as I went to start my d2bs the following issue occurred: Any/all of my profiles will work as intended if the entry script is set to d2botmap or d2botlead. However, when trying to load any profile with the d2botfollow entry script the window unexpectedly exits and that profile crashes then immediately restarts, only to immediately have the window unexpectedly exit and the profile crash immediately. This happens on repeat at a very fast speed, it is not waiting anywhere near the typical 5 seconds that it is set to. 

Someone please help :)

**Comment by gtoilet** [comment]
get fresh zip of bot and start over
could be any small issue

**Comment by swettin** [comment]
**Thanks. I got a fresh zip and reinstalled d2bs/kolbot last night. However I still am getting this issue. I think I pinned it down to one small section of code in the d2botfollow config script...

This is how I have it now, when it is set like this with my "["leader"]:["leecher"] info for my profiles so that the followers follow the leader into games then the issue happens and the d2botfollow profiles will not start and just crash and restart rapidly.**
var StarterConfig = {
	JoinChannel: "op swetty", // Name of the channel to join
	FirstJoinMessage: "", // Message to say when first joining a channel, usually ".login"
	ChatActionsDelay: 2, // Seconds to wait in lobby before entering a channel

	JoinRetryDelay: 5, // Time in seconds to wait before next join attempt
	SwitchKeyDelay: 5, // Seconds to wait before switching a used/banned key or after realm down

	CrashDelay: rand(5, 15), // Seconds to wait after a d2 window crash
	RealmDownDelay: 3, // Minutes to wait after getting Realm Down message
	UnableToConnectDelay: 5, // Minutes to wait after Unable To Connect message
	TCPIPNoHostDelay: 5, // Seconds to wait after Cannot Connect To Server message
	CDKeyInUseDelay: 5, // Minutes to wait before connecting again if CD-Key is in use. SwitchKeys overrides this!
	ConnectingTimeout: 20, // Seconds to wait before cancelling the 'Connecting...' screen
	PleaseWaitTimeout: 30, // Seconds to wait before cancelling the 'Please Wait...' screen
	WaitInLineTimeout: 60, // Seconds to wait before cancelling the 'Waiting in Line...' screen
	GameDoesNotExistTimeout: 30 // Seconds to wait before cancelling the 'Game does not exist.' screen
};

/* Join game settings
	Format: "leader's profile": ["leecher 1 profile", "leecher 2 profile", ...]
	If you want everyone to join the same leader, use "leader's profile": ["all"]
	NOTE: Use PROFILE names (profile matches window title), NOT character/account names
	leader:leecher groups need to be divided by a comma
	example:
		var JoinSettings = {
			"lead1": ["follow1", "follow2"],
			"lead2": ["follow3", "follow4"]
		};
*/


	var JoinSettings = {
		"Hdin": ["Light", "Cold", "Fire", "Windy"]
};

// Advanced config - you don't have to edit this unless you need some of the features provided
var AdvancedConfig = {

**BUT If i remove the "["leader"]:[leecher"] line so that it looks like what is below, the d2botfollow profiles startup, login, join channel, etc. but will not join the leader's games.**

var StarterConfig = {
	JoinChannel: "op swetty", // Name of the channel to join
	FirstJoinMessage: "", // Message to say when first joining a channel, usually ".login"
	ChatActionsDelay: 2, // Seconds to wait in lobby before entering a channel

	JoinRetryDelay: 5, // Time in seconds to wait before next join attempt
	SwitchKeyDelay: 5, // Seconds to wait before switching a used/banned key or after realm down

	CrashDelay: rand(5, 15), // Seconds to wait after a d2 window crash
	RealmDownDelay: 3, // Minutes to wait after getting Realm Down message
	UnableToConnectDelay: 5, // Minutes to wait after Unable To Connect message
	TCPIPNoHostDelay: 5, // Seconds to wait after Cannot Connect To Server message
	CDKeyInUseDelay: 5, // Minutes to wait before connecting again if CD-Key is in use. SwitchKeys overrides this!
	ConnectingTimeout: 20, // Seconds to wait before cancelling the 'Connecting...' screen
	PleaseWaitTimeout: 30, // Seconds to wait before cancelling the 'Please Wait...' screen
	WaitInLineTimeout: 60, // Seconds to wait before cancelling the 'Waiting in Line...' screen
	GameDoesNotExistTimeout: 30 // Seconds to wait before cancelling the 'Game does not exist.' screen
};

/* Join game settings
	Format: "leader's profile": ["leecher 1 profile", "leecher 2 profile", ...]
	If you want everyone to join the same leader, use "leader's profile": ["all"]
	NOTE: Use PROFILE names (profile matches window title), NOT character/account names
	leader:leecher groups need to be divided by a comma
	example:
		var JoinSettings = {
			"lead1": ["follow1", "follow2"],
			"lead2": ["follow3", "follow4"]
		};
*/

// Advanced config - you don't have to edit this unless you need some of the features provided
var AdvancedConfig = {

Really confused as to why I can no longer have the line of script telling the followers to join the leader's games. Is there another way to do this?

**Comment by Butterz51** [comment]
This is what mine looks like.
**_Example:_**

/* Join game settings
	Format: "leader's profile": ["leecher 1 profile", "leecher 2 profile", ...]
	If you want everyone to join the same leader, use "leader's profile": ["all"]
	NOTE: Use PROFILE names (profile matches window title), NOT character/account names
	leader:leecher groups need to be divided by a comma
	example:
		var JoinSettings = {
			"lead1": ["follow1", "follow2"],
			"lead2": ["follow3", "follow4"]
		};
*/

var JoinSettings = {
	"Leader": ["Key2", "Key3", "Key4", "Key5"]
};

// Advanced config - you don't have to edit this unless you need some of the features provided
var AdvancedConfig = {
	/* Features: Override join delay for each profile

	* Format *:
		"Profile Name": {JoinDelay: number_of_seconds}

	* Example * (don't edit this - it's just an example):
		"MyProfile1": {JoinDelay: 3},
		"MyProfile2": {JoinDelay: 6}
	*/

	// Put your lines under this one. Multiple entries are separated by commas. No comma after the last one.
	
	"Key2": {JoinDelay: 1},
	"Key3": {JoinDelay: 2},
	"Key4": {JoinDelay: 3},
	"Key5": {JoinDelay: 4}

};

**Comment by swettin** [comment]
Hey, thank you! I just got it fixed, uninstall/reinstall and re-edited the d2botfollow from scratch... Was about to come and close this out. If my problem happens to anyone uninstall kolbot entirely and reinstall, just make a backup folder with your configs, pickits, and profiles and keys files then copy past and replace. Just make sure you do the d2botfollow config from scratch.
