### ISSUE TITLE
Horde script - missing quest

### ISSUE THREAD

**Issue by benp100** [kolton/d2bot-with-kolbot#2982]
I am running horde script with 4 char team (sorc, barb, paly, druid). Druid missed the travincial council quest, maybe he was at town for buy potion while rest of the team killing council. So now, druid is stuck at council quest, but my sorc is trying to give him the wp for durance of hell (mephisto) but he cant enter in because quest is not complete. So all the team is stuck here because 1 char missing the quest. Is there anyway to enter a manual command in console for the team redo council quest? My team is all at lvl 75, do i need to scrap team and restart one? Or there something we can do? Thx for help

**Comment by WiZzMaN47** [comment]
Press the pause button on keyboard when the console output is hidden and it
will pause script... But you have to pause all 3 and obviously and missing
quest player will have to make game and complete trav to continue
