### ISSUE TITLE
Kolbot Cd Key in Use By Me Issue

### ISSUE THREAD

**Issue by Tachyonian** [kolton/d2bot-with-kolbot#2987]
Hey everyone,

So, here's where I'm at. I currently have three cd keys attached to kolbot. They had been working perfectly for over a month. Now all of a sudden, two of my cd keys are "in use my me" when i try to log into battle net. For sure reason my 2nd cd key can log in just fine. I did do some file clean up on my computer, which included cleaning up my temp file so, perhaps that has something to do with it. Also, I've uninstalled diablo 2 and LOD as well as the kolbot program and nothing has changed. If i log into the key that works and get past the checking version screen i can then enter the names of the battle net accounts that have the associated cd keys that are messing up and use the accounts. Does anyone have any idea why I'm getting this error? I've looked through many posts and most suggest that my hero's didnt exit bnet properly and are in limbo and to wait up to 24hrs. Is there anything I can look into while I wait for this time to expire?

Cheers

**Comment by gtoilet** [comment]
right click profile and go next key or release key it might be stuck on other profile

**Comment by Tachyonian** [comment]
Thanks for the reply, I gave it a try but it appears none of the cd keys are being used. I think it is a case of just waiting since I've done pretty much everything  that has been suggested in other threads. I can at least play/bot on this one cd key until the other ones open back up.

**Comment by Tachyonian** [comment]
Just waited it out.
