### ISSUE TITLE
missing character

### ISSUE THREAD

**Issue by m3ph** [kolton/d2bot-with-kolbot#2990]
I was running bot through the night. When I opened the window he was trying to connect to the game but couldnt. I stopped it and logged on to the game by myself. The foto of the charecter is not showed in game and I cannot create the game with her. And itsnot shown in chat its just name and no pict of the char.

**Comment by m3ph** [comment]
![Uploading 166467368_816298845907790_807567196604211335_n.jpg…]()

**Comment by m3ph** [comment]
![166467368_816298845907790_807567196604211335_n](https://user-images.githubusercontent.com/81556252/112808579-6aab8400-9079-11eb-91d4-81da30919062.jpg)

**Comment by Butterz51** [comment]
I would have to say it got a temp ban on that character since it says Snooze on it. never seen that before. maybe keep an eye on it maybe it will work again sometime.
