### ISSUE TITLE
grand charms from baal

### ISSUE THREAD

**Issue by m3ph** [kolton/d2bot-with-kolbot#3011]
Hi is there any possibility to tell the bot to keep charms dropped from dia,nigh or baal??

**Comment by minuteMed95** [comment]
Hello, in char config file (eg d2bs/kolbot/lib/config/Paladin.js) if you uncomment the line 389 
`//Config.Recipes.push([Recipe.Reroll.Magic, "Grand Charm"]); // Reroll magic Grand Charm (ilvl 91+)`

and edit the line 361 to set the value of `Config.Cubing` to true then your bot will keep grand charms with ilvl > 91 (dropped only by baal / diablo i believe) and your bot will reroll them until they match a line of your pickit file.

hope this helps

**Comment by m3ph** [comment]
thanks a lot :)
