### ISSUE TITLE
GetKeys script don't do anything, anymore, on my character

### ISSUE THREAD

**Issue by jeanmroy** [kolton/d2bot-with-kolbot#3020]
Hi guys,

Sorry to disturb. I've done my first uber yesterday, and got my torch for the first time!
Though today, it looks like when the kolbot arrives at the "GetKeys" scripts, it only does the town chores  and skip to the next script. If I let only the GetKeys to True in my config, it will just stall there.

I've tried to rename my config file to .old and create a new one, but still, it's not working..
GetKeys script is untouched and is working so far on my other D2bot profile.

I tried to comment all my pickit files to be  sure, but even with none, it still doing nothing. (Was thinking maybe I forgot a maxquantity of the keys somewhere, but confirmed I did not).

Any of you have any idea why my paladin can't run for keys anymore ?

In my stash, I actually have 3 keys of each, at the moment..

**Comment by jeanmroy** [comment]
[Paladin.MortalUberKillR.js.zip](https://github.com/kolton/d2bot-with-kolbot/files/6427348/Paladin.MortalUberKillR.js.zip)
Here is the config file of the character.

**Comment by ckelly44** [comment]
GetKeys is actually hard-coded to skip if you have 3 of each keys regardless of your pickit file.
	`if (!me.findItems("pk1") || me.findItems("pk1").length < 3) {`
[GetKeys.js line: 4](https://github.com/blizzhackers/kolbot/blob/dbb028623b144728e9bd47cf420b5006524f4d98/d2bs/kolbot/libs/bots/GetKeys.js#L4)
	`if (!me.findItems("pk2") || me.findItems("pk2").length < 3) {`
[GetKeys.js line: 18](https://github.com/blizzhackers/kolbot/blob/dbb028623b144728e9bd47cf420b5006524f4d98/d2bs/kolbot/libs/bots/GetKeys.js#L18)
	`if (!me.findItems("pk3") || me.findItems("pk3").length < 3) {`
[GetKeys.js line: 33](https://github.com/blizzhackers/kolbot/blob/dbb028623b144728e9bd47cf420b5006524f4d98/d2bs/kolbot/libs/bots/GetKeys.js#L33)

**Comment by jeanmroy** [comment]
oh, good thanks a lot. I will change that then to whatever number above 3.
Thanks!
