### ISSUE TITLE
Kolbot issue strict warning 129

### ISSUE THREAD

**Issue by Xfein** [kolton/d2bot-with-kolbot#3032]
had this issue pop up never changed the ntitemparser

Strict Warning(129)|file((kolbot\libs\ntitemparser.dbl:635) invalid assignment left-hand side

not sure whats wrong with the code on that line.

**Comment by gtoilet** [comment]
you changed something to do with nip file?

**Comment by Xfein** [comment]
nope just pickits like normal.  any ideas what to change or get it back to what it was?

**Comment by gtoilet** [comment]
at most new bot zip
or revert any changes you made recently
since with out knowing what you changed recently or seeing the full error hard to say 
can happen when pc gets crashed or something like that

**Comment by Xfein** [comment]
that is the whole error ill try overwriting it with a new one and see.. no changes were made to anything other than my own pickit files and char configs.. but thanks for the help so far ill try that.

edit- overwriting the file fixed the issues thanks again!
