### ISSUE TITLE
Sorceress losing gear, maybe on death?

### ISSUE THREAD

**Issue by Bcubrich** [kolton/d2bot-with-kolbot#3054]
One sorceress I am running keeps losing gear. I am not sure how because it has happened when no death was logged. I thought item popping wasn't a thing anymore? Has anyone run into this? I am leveling up 4 characters at once and the Lightning sorc is chickening more than the others. I can't figure out why, either, except when she is hit by Blood mana. My Fire/Ice sorc is doing fine.

**Comment by Samael36** [comment]
My cold sorceress had an Edge bow on switch to get a discount on gambling and I just realized it was gone. She auto-quit a few times to escape death and the merc was still alive, no corpse was in the new game and no recorded death on the log. However, she did lose 10% of her experience bar and now no more item on switch.

**Comment by Bcubrich** [comment]
I think I found the issue which I am testing now.  I used a text file comparison to see what my characters that didn't lose gear had, and it looks like I accidentally set cubing repair on. Presumably there is some issue where the item is repaired, then if it's not in your pickit it is discarded. I will update this issue as resolved if this fixes the problem.
