### ISSUE TITLE
Wakka

### ISSUE THREAD

**Issue by JordanRousseauD** [kolton/d2bot-with-kolbot#3056]
I'm just wondering if there was any solution for my follower to stop walking in minions when my leader go back in town to refill potion

**Comment by Samael36** [comment]
I'm not 100% sure, but I think your leader needs to send a message (such as SafeTp) when he goes to town and another one when he returns. Your followed will need to be configured to go to town/enter tp when reading the messages. It's an idea, and sorry I'm too new to script the commands.

**Comment by Samael36** [comment]
I found another post with a different script where Followers return to town.
https://gist.github.com/tokida/7bd74131f3b707989a2d50748af33fb5
