### ISSUE TITLE
Shopping items sold by other players

### ISSUE THREAD

**Issue by Samael36** [kolton/d2bot-with-kolbot#3058]
I'd like some help to configure my follower to buy items sold from other players to Jamella and Malah after Chaos and Baal runs. Sometimes they sell items (like 40% mf chancies as an example) just because they are not 100% perfect. Is this possible?

**Comment by gtoilet** [comment]
as long as they are in the shop when your toon goes to that npc and you have the nip right
i dont see why it would not work
seems like the same principle with the shopbot.js

**Comment by Samael36** [comment]
> as long as they are in the shop when your toon goes to that npc and you have the nip right
> i dont see why it would not work
> seems like the same principle with the shopbot.js

Thank you for your reply. Noticed it works now!
