### ISSUE TITLE
Failed to pick up Tal Rasha's Amulet

### ISSUE THREAD

**Issue by Samael36** [kolton/d2bot-with-kolbot#3066]
Bot was killing Countess, no keys, no runes and it went back to town. I decided to manually go back to verify if it had missed anything. Indeed, a green amulet. Surprise: Tal Rasha's amulet. But why? Am I missing something in my configuration?

[name] == amulet && [quality] == set # [lightresist] == 33

Also noticed the bot won't identify any other unique items either. It picks up shako and stashes it unid. Maybe a related issue?

**Comment by Bcubrich** [comment]
1) Dd you make sure you are using the right pickit? You might be editing a file that is not referenced. You can always make test on easy pickit like

[Type] == armor # [Defense] >=1

just to see if the pickit is working 

2) this is what I use

[Type] == Amulet && [Quality] == set # [SorceressSkills] == 2  // Tal Rasha's Adjucation

**Comment by Samael36** [comment]
Yes, the pickit is working. Items get stashed and logged every now and then. However, they never get identified. So it can't detect the Amulet as a Tal Rasha's if it doesn't see the [SorceressSkills] == 2 yet. Is there a setting to identify every item?

**Comment by Bcubrich** [comment]
Even if you could I don't think that is a good solution to your problem. The pickit isn't working if what you are describing is really happening. Create a pastbin with your pickit file and link it here please.

**Comment by Samael36** [comment]
Thanks for your reply.
I use the default folders kolton.nip and LLD.nip which I personnally modified: 
https://pastebin.com/p6K4cme9
So far it picks all unique rings, amulets and uniques within the kolton.nip file, but only missed Tal Amulet on line 503.

And character configuration:
// Pickit config. Default folder is kolbot/pickit.
	Config.PickitFiles.push("kolton.nip");
	Config.PickitFiles.push("LLD.nip");

Photo of the logs: https://imgur.com/NKVe4xD

**Comment by Samael36** [comment]
Update: Just saw my bot identifying and selling a random set amulet to Jamella, so it seems the problem has been solved somehow, but can't tell why it failed to pick up the Tal Amulet 3 days ago. Anyways thank you for the support and besides that everything works great!
Second update: Just found a Tal Amulet, so problem definitely solved, but no idea why it didn't pick it up at Countess the first time. Maybe it was just going to buy potions and come back pick up the items. Too late to tell.
