### ISSUE TITLE
Not buying keys and ignoring gold chests

### ISSUE THREAD

**Issue by swchoi89** [kolton/d2bot-with-kolbot#3067]
Hi all

I'm really bad with coding - was wondering if you could help me configure my bot to do the following:

In Pit 2, my bot ignores the gold chest in there, same as a few chests in LK which I think yield better drops than current setup?

Also my bot doesn't buy keys, so it ignores locked chests.

Currently running default kolton bot settings.

**Comment by Bcubrich** [comment]
did you change `config.chests =false` to `config.chests =true` in your character config?

**Comment by swchoi89** [comment]
I only have this in my character config

Scripts.ChestMania = true; // Open chests in configured areas. See sdk/areas.txt
		//Config.ChestMania.Act1 = []; // List of act 1 areas to open chests in
		//Config.ChestMania.Act2 = [55, 59, 65, 66, 67, 68, 69, 70, 71, 72]; // List of act 2 areas to open chests in
		Config.ChestMania.Act3 = [79, 80, 81]; // List of act 3 areas to open chests in [80, 81, 92, 93, 84, 85, 90]
		//Config.ChestMania.Act4 = []; // List of act 4 areas to open chests in
		//Config.ChestMania.Act5 =

**Comment by Bcubrich** [comment]
Around line 500 there should be this. If it's missing stick it in and set to true. I don't know exact line because I have changed my script so much. 

`	Config.OpenChests = false; // Open chests. Controls key buying.`
