### ISSUE TITLE
OrgTorch Script doesn't refill potions in belt

### ISSUE THREAD

**Issue by boddhisatra** [kolton/d2bot-with-kolbot#307]
The OrgTorch Script works perfectly, except it does not refill its belt while doing it's town chores. I've tested adding a few mf lines to the script, like eld/shenk, and it will pickup potions in the field but it still won't get them from the vendor.

**Comment by StoneOfJordan** [comment]
[There you go](https://gist.github.com/StoneOfJordan/c6ebc2319b2ecc9f54e4f81a349d04c2)

**Comment by boddhisatra** [comment]
A fix already! What a champ! thanks @StoneOfJordan
