### ISSUE TITLE
Kolbot Assassin config

### ISSUE THREAD

**Issue by RoryCha** [kolton/d2bot-with-kolbot#3086]
Hi there. 

Im having an issue with a traps assassin when running chaos/Baal with my other characters. When loading into a game it says bad attack config, do not expect your bot to attack.

I’ve set the use traps to true and put -256 for shock web on the attack skills.

when she enters to leaders TP she teleports onto the mobs but does not attack at all until she “chickens” out of the game due to low HP. If she survives to the seals she’ll do the same thing until the leader opens the seals and then she’ll plant traps but that is the only time she’ll attack. 

From this, my guess was I forgot to change the config to attack all mobs rather than bosses etc. I checked the config and had set 0 for her to attack all mobs. 

If by some chance she survives the full chaos run and gets a chance to go onto Baal, she’ll not do anything to the normal mobs in the throne but when the waves come in she’ll set traps. Once all waves are done she’ll enter the chamber to kill Baal but exits the game straight away. 

Any help would be awesome. Thanks.

**Comment by cezars** [comment]
/* Attack config
	 * To disable an attack, set it to -1
	 * Skills MUST be POSITIVE numbers. For reference see http://pastebin.com/baShRwWM
	 * Don't put LS/DS/WoF/WoI here! Use Config. UseTraps, Config.Traps and Config.BossTraps
	 */
	Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 256; // Primary skill to bosses.
	Config.AttackSkill[2] = 251; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 256; // Primary skill to others.
	Config.AttackSkill[4] = 251; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

	// Class specific config
	Config.UseTraps = true; // Set to true to use traps
	Config.Traps = [271, 271, 271, 276, 276]; // Skill IDs for traps to be cast on all mosters except act bosses.
	Config.BossTraps = [271, 271, 271, 271, 271]; // Skill IDs for traps to be cast on act bosses.

	Config.SummonShadow = "Master"; // 0 = don't summon, 1 or "Warrior" = summon Shadow Warrior, 2 or "Master" = summon Shadow Master
	Config.UseFade = true; // Set to true to use Fade prebuff.
	Config.UseBoS = false; // Set to true to use Burst of Speed prebuff. TODO: Casting in town + UseFade compatibility
	Config.UseVenom = false; // Set to true to use Venom prebuff. Set to false if you don't have the skill and have Arachnid Mesh - it will cause connection drop otherwise.
	Config.UseCloakofShadows = true; // Set to true to use Cloak of Shadows while fighting. Useful for blinding regular monsters/minions.
	Config.AggressiveCloak = false; // Move into Cloak range or cast if already close

**Comment by RoryCha** [comment]
My Guy! Just tried it now and it’s working a dream. Can’t thank you enough it’s been doing my head in for days!
