### ISSUE TITLE
How to check iLevel when rolling rares

### ISSUE THREAD

**Issue by Deathknight55** [kolton/d2bot-with-kolbot#3092]
I want to have my bots re-roll rares with perfect skulls.  This is one of the lines I have in my character config:
Config.Recipes.push([Recipe.Reroll.Rare, "Demonhide Sash"])
It works fine with one problem.  It always re-rolls the same item causing the iLevel to continuously drop.  Is there a way to set a minimum iLevel?  I've tried this but it did not work.
Config.Recipes.push([Recipe.Reroll.Rare, "Demonhide Sash", [Level] >= 72])
It didn't recognize [Level] 

Also tried changing Cubing.js, line 875
Old line: if (unit.quality === 6 && NTIP.CheckItem(unit) === 0) {
New line: if (unit.quality === 6 && unit.ilvl >= 72 && NTIP.CheckItem(unit) === 0) {

Doing this caused it to throw an error saying the recipe was not defined.

**Comment by Samael36** [comment]
I'm not sure but I think it will automatically discard the item once it falls under level 72.
Otherwise you can try to change line 326 in cubing.js. Change Level: 71 to 72
Not sure if that will work though. Still looking for another solution and will update if found.

**Comment by Deathknight55** [comment]
Yeah, they are still rolling rares well below that level.

**Comment by DarkHorseDre** [comment]
Line 326 is for crafting safety belts, you want `Recipe.Reroll.Rare` (6 pskulls and item).
that recipe doesnt specify the ilevel of the item though..

This section of cubins.js seems to deal with the ingredients for your recipe:
```js
if (recipe.Index === Recipe.Reroll.Rare) {
			if (unit.quality === 6 && NTIP.CheckItem(unit) === 0) {
				return true;
			}
```

Try changing it to look for a level for the ingredient:
```js
if (recipe.Index === Recipe.Reroll.Rare) {
			if (unit.quality === 6 && unit.ilvl >= 72 && NTIP.CheckItem(unit) === 0) {
				return true;
			}
```

this will apply for all items. if you want to only apply this to belts, then add a check for the `unit.itemType` (think it is `19` according to file: `/kolbot/d2bs/kolbot/sdk/commandRef.htm#unit.itemtype` - but if not you can find it defined in the kolbot files yourself.

**Comment by Deathknight55** [comment]
> 
> 
> Line 326 is for crafting safety belts, you want `Recipe.Reroll.Rare` (6 pskulls and item).
> that recipe doesnt specify the ilevel of the item though..
> 
> This section of cubins.js seems to deal with the ingredients for your recipe:
> 
> ```js
> if (recipe.Index === Recipe.Reroll.Rare) {
> 			if (unit.quality === 6 && NTIP.CheckItem(unit) === 0) {
> 				return true;
> 			}
> ```
> 
> Try changing it to look for a level for the ingredient:
> 
> ```js
> if (recipe.Index === Recipe.Reroll.Rare) {
> 			if (unit.quality === 6 && unit.ilvl >= 72 && NTIP.CheckItem(unit) === 0) {
> 				return true;
> 			}
> ```
> 
> this will apply for all items. if you want to only apply this to belts, then add a check for the `unit.itemType` (think it is `19` according to file: `/kolbot/d2bs/kolbot/sdk/commandRef.htm#unit.itemtype` - but if not you can find it defined in the kolbot files yourself.

This worked, thanks

**Comment by DarkHorseDre** [comment]
@Deathknight55  ah i didn't read the 2nd half of your OP :) I see you did what i suggested but didn't work - must've been a typo?
glad its working anyway
