### ISSUE TITLE
Countess Chest

### ISSUE THREAD

**Issue by DmMOnJsp** [kolton/d2bot-with-kolbot#3097]
is there any way to ensure bots stick around for the chest to open every game?
i'm running countess for crafts mainly and my leader didnt do countess yet meaning chest opens every game

**Comment by Samael36** [comment]
Not sure if this is the right solution, but try adding this at line 38 in countess.js

delay(5000);
Pickit.pickItems(); 

It will add a delay of 5 seconds after killing countess, leaving time for the chest to open and items to drop, and then Pickit will be enabled. Give it a try and let us know if it works or not.

**Comment by DmMOnJsp** [comment]
> Not sure if this is the right solution, but try adding this at line 38 in countess.js
> 
> delay(5000);
> Pickit.pickItems();
> 
> It will add a delay of 5 seconds after killing countess, leaving time for the chest to open and items to drop, and then Pickit will be enabled. Give it a try and let us know if it works or not.

Thank you so much for your reply, im so smart to ask theese questions 12 hours before i go vacation xD
i tested out abit
this is what i ended up with from line 33:

	Attack.clear(20, 0, getLocaleString(2875)); // The Countess
	
	delay(6000);
Pickit.pickItems();

	if (Config.OpenChests) {
		Misc.openChestsInArea();
	}

	return true;
}
