### ISSUE TITLE
what is the pickit code for cold damage small charms?

### ISSUE THREAD

**Issue by danmm55** [kolton/d2bot-with-kolbot#3103]
Id like to keep cold damage small charms with either FRW or AR.  Ive gotten bot to keep everything ive wanted out of the ordinary like:
 good jewels with 30 fire res for merc and 15 ias jewels with other mods for sins and +res jewels with other mods for necros and druids.

Is it even possible?

**Comment by DarkHorseDre** [comment]
> pickit code for cold damage small charms

check the default kolton.nip as first call as there's a lot in there:

under small charm section:
[coldmindam]
[coldmaxdam]

min and max roll separately so you need to know what their max values are and what you want.
the Kolton entries are maximum values IIRC
