### ISSUE TITLE
Defining "Games ETA:" in the log

### ISSUE THREAD

**Issue by chairrival** [kolton/d2bot-with-kolbot#3106]
I am not totally clear on the meaning of "Games ETA:" (Games Estimated Time of Arrival?) in the log display:

[Game: _______ ] [Level: _______ ] [XP: _______ ] [Games ETA: _______ ]

I assume it's an estimated number of games to level up, since it's after the XP number. Is that correct?

**Comment by DmMOnJsp** [comment]
its a estimate of levelup indeed
my 2014 etals had something similar
i dont use this feature anymore as i dont care much for the lvling part

its proberbly usefull for automated services and stuff :)
