### ISSUE TITLE
Pather.js Runwalk issue

### ISSUE THREAD

**Issue by DmMOnJsp** [kolton/d2bot-with-kolbot#3108]
So i was messing around trying to make my bots use walkmode outside of town
the checks works fine for when entering town, but i'm only going walk mode some of the time

this is what my pather looks like from line 355:

		// Stamina handler and Charge
		if (!me.inTown && !me.dead) {
			if (me.runwalk === 1 && me.stamina / me.staminamax * 100 <= 20) {
				me.runwalk = 0;
			}

			if (me.runwalk === 1 && me.stamina / me.staminamax * 100 >= 50) {
				me.runwalk = 0;
			}

			if (Config.Charge && me.classid === 3 && me.mp >= 9 && getDistance(me.x, me.y, x, y) > 8 && Skill.setSkill(107, 1)) {
				if (Config.Vigor) {
					Skill.setSkill(115, 0);
				}

				Misc.click(0, 1, x, y);

				while (me.mode !== 1 && me.mode !== 5 && !me.dead) {
					delay(40);
				}
			}
		}

		if (me.inTown && me.runwalk === 0) {
			me.runwalk = 1;
		}

**Comment by DarkHorseDre** [comment]
> ```
> 	if (!me.inTown && !me.dead) {
> 		if (me.runwalk === 1 && me.stamina / me.staminamax * 100 <= 20) {
> 			me.runwalk = 0;
> 		}
> 
> 		if (me.runwalk === 1 && me.stamina / me.staminamax * 100 >= 50) {
> 			me.runwalk = 0;
> 		}
> ```

You've changed the code to set runwalk = 0 when your stamina is <= 20% or >=50%

so it is only =1 if stamina % is between 20 and 50

**Comment by DmMOnJsp** [comment]
yea witch should be never (exept in town because it specificly checks for that)

let me specify what i want, i want my bot to stay on walking mode, unless it's moveing around in town
my code should acheve this in theory no?

**Comment by DmMOnJsp** [comment]
the code somewhat works as intended
my amazon changes to walk mode somewhat consistently

what seems to trigger this though is cs when mobs move, and ama actually follows
my paladin is diffrend though it wont seem to trigger the code on him as he is just teleporting

**Comment by DarkHorseDre** [comment]
Yes, you should always start by stating what you want, then work out what the code is doing then what you should change ;)

What you did isn't correct as you're changing code in a way that doesn't match what the code is doing/what you want to.

The original code is walking when out of town and under 20% stamina.  the 2nd if seems to be setting to run if stamina >=50%

So if you want it to permanently walk (whilst pathing) remove these if's and just set runwalk == 0 (assuming 0 = walk, 1 = run)
e.g.

```js
if (!me.inTown && !me.dead) {
	me.runwalk = 0;
}
```
disclaimer: I haven't checked the pather code or other code that moves the toon (e.g. attack.js) to see if this is the only logic you need to change.

**Comment by DmMOnJsp** [comment]
this would make me walk at all times right (also in town)?

if so would there be a way to implement this check so it only did it for classid 3 (pala) and rest of my army would stay run mode?
(my pala is the only one of 4 who actually has maxblock ^^)

My own draft of this

if (!me.inTown && !me.dead && me.classid === 3) {
	me.runwalk = 0;
}

**Comment by DarkHorseDre** [comment]
lol yeah that's it

once you get familiar with the code and bot you'd want to add a config option so you can control it per character and not by class (as if you'd run another pala it would always walk too) but I assume you don't know how to do that yet (you can search open and closed issues to find where people have been shown how to add new config options)

**Comment by DmMOnJsp** [comment]
so after still struggeling to get every thing working without errors (without success)
i decided to go another route and add this line to my Diablo and baal and nila/pindle js instead:

	if (me.runwalk === 1) {
		me.runwalk = 0;
	}

works like a charm
i even got what i wanted from the start, run in town, walk in combat
