### ISSUE TITLE
MFLeader at the Chaos

### ISSUE THREAD

**Issue by zasef1** [kolton/d2bot-with-kolbot#3118]
How to cancel MFLeader to make a portal after opening the seal in CHAOS
clear Grand Vizier of chaos
clear Lord De Seis
clear Infector of souls
kill 243

I found these lines in attack.js
if (Config.MFLeader && !!bossId) {
Pather.makePortal();
say("clear" + bossId);
if (Config.MFLeader) {
Pather.makePortal();
say("kill "+ classId);
Can I add anything to the above two instructions as a way to cancel his sending message and makePortal

Any help would be greatly appreciated

**Comment by DarkHorseDre** [comment]
You can comment out lines with '\\' in the Javascript and that line will be ignored.

e.g. to stop the portal and the "say" and makeportal command:
```js
if (Config.MFLeader) {
//Pather.makePortal();
//say("kill "+ classId);
}
```
You could comment out the whole if statement but I cannot check what else is there.
you can also use "\* */" to comment out blocks of code but I won't complicate things with that

**Comment by zasef1** [comment]
Sorry, my question is not clear enough.
I used 3 robots in the game
The captain runs MFLeader, and other team members run MFHelper as helpers in other areas
So I cannot comment out Pather.makePortal(); say("kill "+ classId);
However, MFLeader and MFHelper are not needed in the chaos
MFHelper will forcibly stop the script in Chaos, but MFLeader will not

(Config.MFLeader && !!bossId)
("kill "+ classId)
How to add Grand Vizier of chaos, Lord De Seis, Infector of souls, 243 in these two lines.
Let MFleader encounter these four kinds of monsters and do not execute Pather.makePortal() and say("kill "+ classId)

**Comment by DarkHorseDre** [comment]
> How to add Grand Vizier of chaos, Lord De Seis, Infector of souls, 243 in these two lines.
> Let MFleader encounter these four kinds of monsters and do not execute Pather.makePortal() and say("kill "+ classId)

Are you asking how to **not** open portal and announce attack/kill command if it is any of the seal bosses or dia and if mfleader is true?

I'm a little confused as looking at diablo.js portals are only opened at entrance and star - not at seal bosses or dia?

**Comment by zasef1** [comment]
"Are you asking how to not open portal and announce attack/kill command if it is any of the seal bosses or dia and if mfleader is true?"

yes,it is this.

**Comment by DarkHorseDre** [comment]
You didnt answer the second part of my post

ALSO, which script are you running as leader?

**Comment by zasef1** [comment]
Because that is a script command in MFLeader, which has nothing to do with diablo.js
The leader runs MFLeader, Andariel, Travincal, Mephisto, Pindleskin, Eldritch
Finally gather in dia and baal

**Comment by DarkHorseDre** [comment]
So you didn't answer me on purpose? that's not very nice!

Mfleader is not a script (function) it is a config variable. the various scripts/functions check if config leader is set and if so does stuff.

I see what you mean - you want attack.js to stop opening tps  via the mfleader check (I missed that) - so you just need to build an array of the bosses you want to check and add that to the attack.js if statement you quoted.

use the classids from the list in your files: kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/sdk/monster%20classID's.txt for the bosses you want to check for.

Something like:
```
const listOfBossesNotToCallMFhelpersFor = [243, 111, 234, 13452, 2232]; //random classids - you add real ones

if (MFLeader && listOfBossesNotToCallMFhelpersFor.indexOf(classid) == -1){ //you can see classid for the boss is already available so use it
     //open portal and say kill etc
}
```

GL, HF

**Comment by zasef1** [comment]
I am from Taiwan, English through translation software
If some comments make you feel uncomfortable, I feel very sorry
Thank you for helping me solve the problem

**Comment by zasef1** [comment]
I got this error

Error in Diablo (attack.js #244) MFLeader is not defined

Content added in attack.js

const listOfBossesNotToCallMFhelpersFor = [243, 111, 234, 13452, 2232]; //random classids - you add real ones

if (MFLeader && listOfBossesNotToCallMFhelpersFor.indexOf(classid) == -1){ //you can see classid for the boss is already available so use it
     //open portal and say kill etc
}

Which step am I doing wrong

The content of line 244 is
if (MFLeader && listOfBossesNotToCallMFhelpersFor.indexOf(classid) == -1)

Please help again

**Comment by DarkHorseDre** [comment]
No worries.

Sorry  I was writing from memory - you need to use the variables as they are used in the code, so:

`Config.MFLeader`

**Comment by zasef1** [comment]
so,add the following in attack.js, right?

const listOfBossesNotToCallMFhelpersFor = [243, 111, 234, 13452, 2232]; //random classids-you add real ones

if (Config.MFLeader && listOfBossesNotToCallMFhelpersFor.indexOf(classid) == -1){ //you can see classid for the boss is already available so use it
//open portal and say kill etc
}

**Comment by zasef1** [comment]
The leader got this error and will still send a message and makePortal after the seal is opened

Error in Diablo (attack.js #244) classid is not defined

**Comment by DarkHorseDre** [comment]
> Sorry I was writing from memory - you need to use the variables as they are used in the code, so:

remember JS is case sensitive - don't just copy my pseudo-code as I wrote it - check the variables etc are consistent

**Comment by zasef1** [comment]
Ok thanks
In addition, these five sets of numbers
243, 111, 234, 13452, 2232
"13452, 2232"
These two numbers are not in the list of monster classID
Where can i find him

In addition, for these two lines of instructions
const listOfBossesNotToCallMFhelpersFor = [243, 111, 234, 13452, 2232]; //random classids-you add real ones

if (Config.MFLeader && listOfBossesNotToCallMFhelpersFor.indexOf(classid) == -1){ //you can see classid for the boss is already available so use it
//open portal and say kill etc
}
I just need to add it to attack.js, or replace these two lines
if (Config.MFLeader && !!bossId) {
Pather.makePortal();
say("clear" + bossId);
if (Config.MFLeader) {
Pather.makePortal();
say("kill "+ classId);

**Comment by DarkHorseDre** [comment]
I added comments to the code explaining this and I pasted a link to the classids in my previous posts bro.
links are the same in any language ;)

please read and follow what I have written, and check what you are doing

**Comment by zasef1** [comment]
I don't know anything about js...
anyhow
Thank you for taking the time to help me answer the questions
