### ISSUE TITLE
help with kolbot error plz

### ISSUE THREAD

**Issue by joshywashy1234** [kolton/d2bot-with-kolbot#312]
![screenshot001](https://user-images.githubusercontent.com/33191058/32140708-962f1026-bc27-11e7-969a-49905c1dab83.jpg) 

I got it running and configured the sorceress file then I get syntax error 133 and error 0.  the bot just sits in town. I would really appreciate help.please. I included a screenshot

**Comment by joshywashy1234** [comment]
well I fixed my problem, bot runs great! but now I have a new issue...I ran all night 120 or more runs and only picked up, and kept 2 items a +3 throwing mastery barb helm and 25 defense magefist.  its set up to only keep VERY GOOD STAT items....I might say godly....I need to know what is the correct file to edit....and what the codes mean ....like "==" and "<=" and any others please.  8 to 10 years ago I used a bot and it told you what the command was and meant.  so to sum up ....I need to know what file to edit for the bot to keep good items. I want all tal armors not just perfect defense tal armors . I want all shaftstops not just eth shaftstops. I hope this explains. .....that way I actually get stuff....im running diablo 2 lod expansion. on America useast server

**Comment by B2d2** [comment]
basically this takes hours of your tiem going an edditing in picket files.  koltin nip is where you will find all these items set to pick perfects up.  have to edit them to your liking. there are set items that are not listed for lowere lvl stuff so you just have to add them as you see on other items, if you mess and item up nothng will happen other than it wont pick it up.

**Comment by LeMule** [comment]
https://www.projectetal.com/forums/wiki/?title=Nip_Guide_for_Beginners

It's quite detailed. If you don't program, I'd recommend reading through
these guides to get a good grasp of the language before trying to
add/modify your own pickit files.

**Comment by joshywashy1234** [comment]
I got it working thanks for responses

**Comment by joshywashy1234** [comment]
does any one have some info or know where I can find out how to run 2 bots at once.  I have the cd keys already

**Comment by WiZzMaN47** [comment]
U ca. Do it 2 different way.. Set the path to point to the two different copied or you can set up the keys file
