### ISSUE TITLE
Is there a NOT PERFECT pickit list?

### ISSUE THREAD

**Issue by Teffeq** [kolton/d2bot-with-kolbot#3125]
Hey, im pretty new at d2, specially kolbot.
I have really crappy gear but maneged to create h-din with acceptable gear.

My issue is this whole "perfect list" its way to perfect for me, specially with my embarresing magicfind.
Anyway my question is, does anyone have a list that is not that perfect?

**Comment by Samael36** [comment]
Hey, welcome to the community.
I had the same issue when I started and had to review every single line. Takes about 10 minutes.

For example, next line will pick up perfect shako only:
[name] == shako && [quality] == unique && [flag] != ethereal # [defense] == 141 // harlequin crest

Remove the end where it says defense has to be 141 and it will pick any non-eth shako. It should look like this:
[name] == shako && [quality] == unique && [flag] != ethereal

**Comment by DarkHorseDre** [comment]
Try this: https://darcvigilante.site/showthread.php?tid=9

also google pickits - lots out there, and some sharable on discord too

**Comment by Teffeq** [comment]
Thank you both for your comments. 
I managed to remake the line from 
[name] == shako && [quality] == unique && [flag] != ethereal # [defense] == 141 // harlequin crest
>>>>>
[name] == shako && [quality] == unique && [flag] != ethereal # [defense] == 50 // harlequin crest

So he takes everything above 50 defense.

**Comment by Samael36** [comment]
> Thank you both for your comments.
> I managed to remake the line from
> [name] == shako && [quality] == unique && [flag] != ethereal # [defense] == 141 // harlequin crest
> 
> > > > > >
> 
> [name] == shako && [quality] == unique && [flag] != ethereal # [defense] == 50 // harlequin crest
> 
> So he takes everything above 50 defense.

 [defense] == 50 will look for shako with 50 defense ONLY, which doesn't exist.
 [defense] >= 50 will pick up anything above or equal to 50.
