### ISSUE TITLE
pikit is to sensitive!

### ISSUE THREAD

**Issue by joshywashy1234** [kolton/d2bot-with-kolbot#313]
bot runs great! but now I have a new issue...I ran all night 120 or more runs and only picked up, and kept 2 items a +3 throwing mastery barb helm and 25 defense magefist. its set up to only keep VERY GOOD STAT items....I might say godly....I need to know what is the correct file to edit....and what the codes mean ....like "==" and "<=" and any others please. 8 to 10 years ago I used a bot and it told you what the command was and meant. so to sum up ....I need to know what file to edit for the bot to keep good items. I want all tal armors not just perfect defense tal armors . I want all shaftstops not just eth shaftstops. I hope this explains. .....that way I actually get stuff....im running diablo 2 lod expansion. on America useast server. I need all of the good items I usually don't care about stats....is the a premade pikit file that's less sensitive? I still would like to know which file to edit and what the codes are. thanks in advance for any help

**Comment by david1602** [comment]
Not to sound offensive, but did you pay attention in maths?

<= means smaller than or equal to
>= means greater than or equal to
> means greater than
< means smaller than
== means equal

If you have something like `Defense == 953`, then it will only pick up items with 953 defense. You'll have to configure the pickit the way you want it to be, or get a pickit that is preconfigured to pick low items.

I still happen to have these starter pickits here, you can look into it and see if it's of any help.

[pickit.zip](https://github.com/kolton/d2bot-with-kolbot/files/1425346/pickit.zip)

That may be too insensitive, though. It highly depends on your preference, no one can create a pickit except yourself that picks everything up that you expect it to pick up.

**Comment by joshywashy1234** [comment]
did you pay attention in math....im actually a smart person I scored above average on every subject....but was just average in math... I knew what these meant < >   .....but didn't know what == that meant....thank you for the response but you didn't need to make me feel stupid at the same time that was unnecessary
