### ISSUE TITLE
kolbot how do i make it pick up essences

### ISSUE THREAD

**Issue by joshywashy1234** [kolton/d2bot-with-kolbot#314]
hello, how do I make kolbot pick up essences I didn't see an option in the pick it file.....did I miss it?

**Comment by B2d2** [comment]
this is eazt fix.  in char config set cubbing to "true"  then uncomment "take away the // in front of this.         //Config.Recipes.push([Recipe.Token]); // Make Token of Absolution

**Comment by joshywashy1234** [comment]
thank you

**Comment by Kellen-Stuart** [comment]
> how to pick up Natalya's set ?

Please do not comment completely off-topic
