### ISSUE TITLE
need starter pickit file for kolbot

### ISSUE THREAD

**Issue by joshywashy1234** [kolton/d2bot-with-kolbot#315]
hello I accidently clicked close on the last thread that had a pickit file in it.  if your the person who posted it would you please post it here, and thanks for the response. I need a pickit file that picks up good items....but not junk....yet not one that runs all night and doesn't get anything....I think I need a starter pickit file please

**Comment by david1602** [comment]
you can still find your issue under the closed ones, if you click issues and then "closed" instead of "open"
here's the link to your previous issue: https://github.com/kolton/d2bot-with-kolbot/issues/313

**Comment by joshywashy1234** [comment]
ok thank you very much I got it fixed
