### ISSUE TITLE
PrintToConsole, getGameTime It doesn`t work at Level 99.

### ISSUE THREAD

**Issue by PoPoDad** [kolton/d2bot-with-kolbot#3151]
If the character level is 99,
Playtime is not output on the console at the end of the game.

I tried to modify the Misc.js file, but it kept failing.

Is there a way?

**Comment by gtoilet** [comment]
did yours look like this in the misc.js

string = "[Game: " + me.gamename + (me.gamepassword ? "//" + me.gamepassword : "") + getGameTime + "]";

**Comment by PoPoDad** [comment]
Yes, it's like that.
but
If you're level 99.
The string is not working.

**Comment by gtoilet** [comment]
this in config

Config.LogExperience = true;

and what i posted earlier in the misc.js does not print to console at lvl 99?

**Comment by PoPoDad** [comment]
All characters are set LogExperience=true;.
Should I look at other files besides the Misc.js and Character.js files?

Posting is a mistake.
I don't know how to delete it.

**Comment by gtoilet** [comment]
in the string it referrs to 

		var string,
			gain = this.gain(),
			progress = this.progress(),
			runsToLevel = this.runsToLevel(),
			totalRunsToLevel = this.totalRunsToLevel(),
			getGameTime = this.getGameTime(),
			timeToLevel = this.timeToLevel();


and this 

		if (gain) {
			D2Bot.printToConsole(string, 4);

			if (me.getStat(12) > DataFile.getStats().level) {
				D2Bot.printToConsole("Congrats! You gained a level. Current level:" + me.getStat(12), 5);
			}
		}

if theres any gain it should post the manager would try removing things one by one to get it to print even with no gain
at first glance i would start by making it look like this

		var string,
			getGameTime = this.getGameTime();


that would make it post manager only about game time reguardless of gains/runs to lvl

**Comment by PoPoDad** [comment]
Thank you for your advice.


         var string,
		getGameTime = this.getGameTime();
					
        string = "[Game: " + me.gamename + (me.gamepassword ? "//" + me.gamepassword : "") + getGameTime + "]"; 

        if (gain) {
			D2Bot.printToConsole(string, 4);
                      }


But I tried to fix it.
The play time of the 99-level character is not output.

and


         var string,
		getGameTime = this.getGameTime();
					
        string = "[Game: " + me.gamename + (me.gamepassword ? "//" + me.gamepassword : "") + getGameTime + "]"; 

	    D2Bot.printToConsole(string, 4);
              


I'm going to test it.

**Comment by PoPoDad** [comment]
The test is over.

   var string,
	   getGameTime = this.getGameTime();
				
    string = "[Game: " + me.gamename + (me.gamepassword ? "//" + me.gamepassword : "") + getGameTime + "]"; 

    if (getGameTime) {
		D2Bot.printToConsole(string, 4);
                  }



After modifying it like this, the playtime of all characters was printed regardless of the level.

However, only the time is displayed because the contents related to the experience have been changed or deleted.

**Comment by PoPoDad** [comment]
I'm going to fix it like this.
I don't know if it's working normally.



		var string,
			gain = this.gain(),
			progress = this.progress(),
			runsToLevel = this.runsToLevel(),
			totalRunsToLevel = this.totalRunsToLevel(),
			getGameTime = this.getGameTime();
			timeToLevel = this.timeToLevel();

		string = "[Game: " + me.gamename + (me.gamepassword ? "//" + me.gamepassword : "") + getGameTime + "] [Level: " + me.getStat(12) + " (" + progress + "%)] [XP: " + gain + "] [Games ETA: " + runsToLevel + "] [Time ETA: " + timeToLevel + "]";
		
                if (getGameTime) {
	               D2Bot.printToConsole(string, 4);
                       }
		if (gain) {
			
			if (me.getStat(12) > DataFile.getStats().level) {
				D2Bot.printToConsole("Congrats! You gained a level. Current level:" + me.getStat(12), 5);
			}
		}

**Comment by gtoilet** [comment]
you seem to be on the right path
never came to this problem never had 99s to run lol

**Comment by PoPoDad** [comment]
It's done.

Thank you Gtoilet for your help.
I'm sharing the contents.





     log: function () {
		var string,
			gain = this.gain(),
			progress = this.progress(),
			runsToLevel = this.runsToLevel(),
			totalRunsToLevel = this.totalRunsToLevel(),
			getGameTime = this.getGameTime();
			timeToLevel = this.timeToLevel();

		
		     string = "[ Char: " + me.charname + " → Game: " + me.gamename + (me.gamepassword ? " ∥ " + me.gamepassword : "") + getGameTime + "] [Level: " + me.getStat(12) + " (" + progress + "%)] [XP: " + gain + "] [Games ETA: " + runsToLevel + "]";
		
		
		if (getGameTime) {
			D2Bot.printToConsole(string, 4);
		}
		
		if (gain) {
		
		    if (me.getStat(12) > DataFile.getStats().level) {
			      D2Bot.printToConsole("Congrats! You gained a level. Current level:" + me.getStat(12), 5);
		        }

			}
	}
