### ISSUE TITLE
rusher and rushee related

### ISSUE THREAD

**Issue by B2d2** [kolton/d2bot-with-kolbot#317]
Can you only do rushes with kolbot operated rushee?? Im trying to use a non bot char on different computer to be the rushee. I mannually enter game with rusher, it parties kills andy without making a tp for rushee to go in for Q : if i set boss script for andy.   I also set (true) in make portal on rushthreads.js and still doesn't make a tp.  line #110
Other players join/create chant games and can do commands so i know im missing something. please help, ty.
  additional info.  rusher script is the only one activated in my char config profile along with  usser addonscript at top is false to ofc.
bot enters game and idols, if i remove andy boss script. but i cant assign master still.

**Comment by LeMule** [comment]
Try typing "master" (I think, oh and "release" will drop you as it's
master) when the rusher's in the game.
At this point it should be accepting commands from you. Ex: "do andariel"
(always prepend "do")
