### ISSUE TITLE
Creating a function for sendcopydata / ReceiveCopyData

### ISSUE THREAD

**Issue by D2Patch09** [kolton/d2bot-with-kolbot#319]
I'm wanting to setup my mfhelper to take tp's / kill bosses without chat spamming.

I was told instead of having the leader spam "Kill 243" into chat, that d2bs can communicate to each other from d2bs instead of chat.

addEventListener('copydata', ReceiveCopyData); this is suppose to be for mfhelper profile correct? not 100% sure

but I think the one made for leader such as mephisto needs a function with multiple lines? 

starts off with function ReceiveCopyData(msgID, msg) {

after that, I don't have a clue on what to do.

any help on this I would highly appreciate!

**Comment by D2Patch09** [comment]
function sayMsg(string) {
if (!useChat) {
return;
}

say(string);
}

function ReceiveCopyData(mode, msg) {
var obj;

switch (msg) {
case "Handle":
handle = mode;

break;
}



addEventListener('copydata', ReceiveCopyData);


?

**Comment by StoneOfJordan** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/294

Take a look at one of my comments there.

**Comment by D2Patch09** [comment]
that's like another language to me.

i want to just send chat spam like mepisto "kill 243" to another char

if i knew how 1 was wrote, i could possibly do the others.

writing 4 lines for function in mephisto.js and mfhelper.js seems super hard for a moron like myself .

could you write out an example for sorc sending chat msg to another char please . save me a week or 2

**Comment by StoneOfJordan** [comment]
The example you're looking for is in that comment. If you have no idea what to do with that you'll be better off learning the basics first.

**Comment by D2Patch09** [comment]
so sorry, i've been working on it for 3 days and trying to figure out by myself was insane hard.

I actually read it and it looks good.

I only need my leader to send the data to the window right? I don't need to have my mfhelper add any lines because as long as they hear/listen to the command then that's all that needs right?

I should add that function line where it says "say "kill 243"? correct?

I don't know anything about java.  If I knew how to add the function properly for one, I could prob do others easily

I downloaded a notepad plus plugin that checks the lines for any errors, idk if it works good though. it says all my lines have an error, so idk if it's out of date.

**Comment by D2Patch09** [comment]
`	var inputMode = 1337, // some number of your choice
		inputMsg = "hej"; // some message
		
	sendCopyData(null, profileName, inputMode, inputMsg);
	
	addEventListener('copydata', // for recipient
		function receiveCopyData(mode, msg) {
			if (mode === inputMode && msg === inputMsg) { // check input data (msg) & mode
				doSomething();
			}
		} 
	);`


I'm having a hard time, I'm not really good at this stuff.

Does all of this go into 1 file or is this suppose to be for the send data (running mf script)

and the addeventlistener (running mfhelper) ?

Or does the mfleader only need to edit his file to only send the messages to the other window(will he receive it if she does that?)because it only needs to recognize "kill 243" to take a TP or whichever run it's doing?

var inputMode = 1337, // is this the name of the function?
		inputMsg = "hej"; // some message  is this the number you want the leader to type?

sendCopyData(null, CsBarb, inputMode, Kill 243);  ? I'm really bad at this..

I don't have a clue on how to go about and for a moron like me would have too many variables before I could even start testing by trial and error for a very long time before I could possibly get something to run correctly.

I see this in d2botlead(I know profiles have to talk to each other from there)

`	case 4: // Heartbeat ping
		if (msg === "pingreq") {
			sendCopyData(null, me.windowtitle, 4, "pingrep");
		}`

I don't understand what's going on there either.

`function main() {
	debugLog(me.profile);
	addEventListener('copydata', ReceiveCopyData);
	addEventListener('scriptmsg', ScriptMsgEvent);
`

If I could get an example on how to do one, I could probably do the others. 

`		if (Config.MFLeader) {
			Pather.makePortal();
			say("kill " + meph.classid);
		}`

`	function ChatEvent(name, msg) {
		if (!player) {
			var i,
				match = ["!kill", "!clearlevel", "!clear", "!quit", "!cows", "!council"];

			if (msg) {
				for (i = 0; i < match.length; i += 1) {
					if (msg.match(match[i])) {
						player = this.findPlayer(name);

						break;
					}
				}
			}
		}`

Change this? function addEventListener(name, msg) {


This is really hard. I could try and get some d2jsp FG and pay for help for an example or two on this please.

I know I don't know what I'm doing and frustrates someone who does and says I'm not reading enough or trying but I really get confused when looking at it. It's like how some people look at calculus and their brain just waht?!!??

**Comment by D2Patch09** [comment]
`		if (Config.MFLeader) {
			Pather.makePortal();
		var inputMode = 1337, // some number of your choice
		inputMsg = "kill " + meph.classid; // some message
		
	sendCopyData(null, profileName, inputMode, inputMsg);
		}
`

`	function addEventListener('copydata', // for recipient
		function receiveCopyData(mode, msg) {
			if (mode === inputMode && msg === inputMsg) { // check input data (msg) & mode
				doSomething();

			var i,
				match = ["!kill", "!clearlevel", "!clear", "!quit", "!cows", "!council"];

			if (msg) {
				for (i = 0; i < match.length; i += 1) {
					if (msg.match(match[i])) {
						player = this.findPlayer(name);`

I've tried a bunch of different ways but kept hitting  alt+home and reloading over and over and couldn't figure out how to fix it.

I ended up getting error line 334 which was the very end of mfhelper file...

If I could get 1 example of how to fix 1 senddata and receivedata, I could probably do the others.

I just don't know exactly how the fix works.

**Comment by D2Patch09** [comment]
`		if (Config.MFLeader) {
			Pather.makePortal();
		var inputMode = 1437, // some number of your choice
		    inputMsg = "Kill 156"; // some message
		
	    sendCopyData(null, RedBarb, inputMode, inputMsg);
		}
`

Getting error RedBarb is not defined (my helper profile) and even did default profile name and got the same error. 

I tried with mephisto and it didn't have an error but even after editing it, it was still announcing in game "Kill 242" which I don't know if it's joining tp because of my edit or because the game being announced?

`		if (Config.MFLeader) {
			Pather.makePortal();
	    var inputMode = 1337, // some number of your choice
		    inputMsg = "Kill 242"; // some message
		
	    sendCopyData(null, RedBarb, inputMode, inputMsg);
		}
`

**Comment by D2Patch09** [comment]
Now I'm getting this error for mfhelper

	this.findPlayer = function (name) {
		var party = getParty();

and on andy script(trying this instead of meph to test)

line 19 missing ; before statement failed to include script: andariel

**Comment by D2Patch09** [comment]
`sendCopyData(null, profileName, inputMode, inputMsg);`

`addEventListener('copydata', copyDataHandler);

function copyDataHandler(mode, msg) {
   print("recvd data");
}`

I was told to try this for a starter on reddit.

**Comment by D2Patch09** [comment]
I'm getting errors at 99% using code pen when trying to edit stuff

trying this

`addEventListener('copydata', copyDataHandler);

function copyDataHandler(mode, msg) {
   print("recvd data");
}`


`sendCopyData(null, RedBarb, inputMode, "clear " + bossId);`

I've been trying so much stuff...:(

**Comment by D2Patch09** [comment]
guess not..?
