### ISSUE TITLE
D2 kolbot pickit issue - not picking up items…

### ISSUE THREAD

**Issue by Django98782** [kolton/d2bot-with-kolbot#3200]
Hey guys..

my bot isnt picking up anything except pots gold and town portals….

please see the below example of my pickit folder

![IMG_5051](https://github.com/user-attachments/assets/aebd53b9-d3ff-4da5-a9a5-8533340b686c)
![IMG_5052](https://github.com/user-attachments/assets/90bafbd4-a482-480b-a6ff-774d304ccb46)

**Comment by Django98782** [comment]
anyone??

**Comment by theBGuy** [comment]
Just stare at your screenshot for awhile the answer is right there

**Comment by Django98782** [comment]
> Just stare at your screenshot for awhile the answer is right there

Care to explain for a newb please??

**Comment by Django98782** [comment]
> Just stare at your screenshot for awhile the answer is right there

Om goodness!! Is it the //?????

man!!! Thank you!!
