### ISSUE TITLE
REALLY NEED HELP WITH 2 BOTS @ ONCE

### ISSUE THREAD

**Issue by joshywashy1234** [kolton/d2bot-with-kolbot#323]
hello,  Thank you for answering my previous questions but I'm yet to find a solution to this.  In detail would you please tell me how to run 2 bots at once.  I have multiple cd keys.  please and thanks in advance

**Comment by joshywashy1234** [comment]
I downloaded serbys cd key creator/changer but it wasn't the one for 26 characters.  it was asking for a 16 digit key.  I have 26 character cd keys.  I seen a 26 character cd key creator in a you tube video but don't know where to find it.  where can I find a 26 character cd key creator so I can run 2 or 3 bots on the same computer?  or is there another way. please help

**Comment by joshywashy1234** [comment]
i have successfully got 2 bots running without help..... =D

**Comment by D2Patch09** [comment]
lol...congrats! now i bet you got banned, bet u wished u didn't get it working now =D lool
