### ISSUE TITLE
not responding .... starting profile

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#328]
ok so I had previously had the VH work around
eventually deleted all d2bs and removed d2 from laptop
fresh classic install updated , fresh DL from github

was told to look for the d2m.dll in the directory but it wasn't there and the github don't it in the master files anymore so idk as the other forum where I posted is SQL error

**Comment by gtoilet** [comment]
guess ill end up trying the VH thru the new ladder and hope the new patch don't break the VH

**Comment by pelthor** [comment]
If you dont mind, what was the resolution?
