### ISSUE TITLE
Can't even get it started

### ISSUE THREAD

**Issue by master1g** [kolton/d2bot-with-kolbot#329]
I ran the old version fine.  I recently downloaded this new version, which I'm not a fan of at all.  I set up a profile and click start.  I don't know which version I should even have selected, so I tried both 1.13d and 1.14d from settings.  Both just give me the spinning circle and then nothing happens.  Game.exe is just sitting in my processes with no game up and Status says stopped at all times.  Any idea what my problem might be?

**Comment by StoneOfJordan** [comment]
New "anti-cheat".

**Comment by master1g** [comment]
Any idea on possible updates to kolbot then?
