### ISSUE TITLE
"cant find player" Blizzards bot fix

### ISSUE THREAD

**Issue by ToxicRS** [kolton/d2bot-with-kolbot#330]
This is some new thing Blizzard implemented , if u try to create a character while u have opened Diablo II game throught Etal VH , ETal 2.0 or Kolbot's managers the character you create always gonna be on non-ladder even if u selected ladder for them!
If you open a legit Diablo II from 1.14d Diabo folder without the usage of any managers you will be able now to create a ladder character and join/create games , but once if you try to use that created ladder character again throught some of the Managers it will say "Player not found"
All the botting/3rd party softwares are blocked right now from logging into characters. You have to use an official game.exe to play atm. @kolton @alogwe @mnikic @noah- @uscgmatthew

**Comment by gtoilet** [comment]
blizzard support thread with blue post said they are seeing the problem also so idk if its something they ment to do or not or something they tried to do and caused this

**Comment by jmkim2ea** [comment]
there are solution is this 
VMware -> xp install -> D2nT  it is work now
but autosmurf error and D2BS is graphic broken

**Comment by ToxicRS** [comment]
> blizzard support thread with blue post said they are seeing the problem also so idk if its something they ment to do or not or something they tried to do and caused this

https://us.battle.net/forums/en/bnet/topic/20760445932#post-18
