### ISSUE TITLE
getWP... has problem (getPresetUnits failed...)

### ISSUE THREAD

**Issue by DiaLover** [kolton/d2bot-with-kolbot#332]
#Hello.
I had left Diablo for several months. I came back today, and many things were different.
I do not use English well but I will try to explain my problem as hard as possible. I need your advice as an expert.

My character causes a problem in WP in A1.
Error message :  Error in undefined (pather.js #1216) getPresetUnits failed, couldn't access the level! (Area: 1, Ping:100, Game: 04-2)

https://i.imgur.com/8yqMGn4.png

**Comment by DiaLover** [comment]
solved

**Comment by noah-** [comment]
What was the solution? Should post so others with same issue can see.

**Comment by williamwangxiao** [comment]
so could u post you solution plz ?

**Comment by awei2046** [comment]
Config.Cubing = false;
