### ISSUE TITLE
I am looking for an NPC menu

### ISSUE THREAD

**Issue by DiaLover** [kolton/d2bot-with-kolbot#334]
I am looking for a way to reset Skills to Akara.

sendPacket(1, 0x38, 4, 0, 4, unit.gid, 4, 0)
Is this packet blocked?
I can not find the packet. I wait for your advice.

0x0D35 Talk
0x0D44 Trade
0x0D06 Trade/Repair
0x0FB1 Imbue
0x0D46 Gamble
0x0D45 Hire
0x0D36 Go East
0x0D37 Go West
0x0FB4 Identify Items
0x0D38 Sail East
0x0D39 Sail West
0x1507 Ressurect Merc
0x58DC Add Sockets
0x58DD Personalize
0x58D2 Travel to Harrogath

**Comment by GZer** [comment]
> Laz's packet watcher

Any idea where to get this packet watcher?
