### ISSUE TITLE
d2bs ,waypoint connect interrupted, help me

### ISSUE THREAD

**Issue by diz309** [kolton/d2bot-with-kolbot#335]
I am not so good at English.

So please be good to understand my awkward English.

here ,my problem

•Bot logs in, joins game. 
Connection interupted when taking the waypoint. Sometimes before, sometimes after.

how make it fix to pather.js ?

help me plz.

**Comment by DiaLover** [comment]
패서문제가 아닙니다 캐릭터이니에서 변경해주세요

**Comment by diz309** [comment]
어디를 손봐야 하나요?

**Comment by dhorie** [comment]
Any news?

**Comment by WiZzMaN47** [comment]
I havent used bot in a while now but what does the error say?



On Jan 31, 2018 4:11 PM, "dhorie" <notifications@github.com> wrote:

Any news?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kolton/d2bot-with-kolbot/issues/335#issuecomment-362102421>,
or mute the thread

**Comment by dhorie** [comment]
•Bot login, create game, buy some pots and get Connection interupted when taking the waypoint.

I fix this turning off an option in Char Config BUT this making me wait 5 minutes each game with *create games in line* but i dont know if that is the best choice.

**Comment by diz309** [comment]
@dhorie how can i do?

**Comment by diz309** [comment]
@DiaLover 어떻게 해야하나요?

**Comment by diz309** [comment]
@WiZzMaN47 how can i do?

**Comment by RogersRo** [comment]
For those who want to use d2bs, inside each character config.js are these lines by default:

Config.PacketCasting = 0; // 0 = disable, 1 = packet teleport, 2 = full packet casting.
    Config.WaypointMenu = false; // Set to true for Single and private realms

change to: 
Config.PacketCasting = 2; // removes some other bugs i noticed while observing bots
    Config.WaypointMenu = true; // Prevents C/I @ wp
disclaimer: this is fully detectable, but not instant ban, i have been running over a week no issues, keep your games >10m
again, running windows 10 64bit (no VMs, NOTHING extra loaded), no antivirus, etc. any pc can do it, but you WILL be banned in the next wave using any bot out atm

**Comment by whty541** [comment]
Config.PacketCasting = 0; // 0 = disable, 1 = packet teleport, 2 = full packet casting.
    Config.WaypointMenu = false; // Set to true for Single and private realms

change to: 

Config.PacketCasting = 2
    Config.WaypointMenu = true;

**Comment by diz309** [comment]
@whty541 thx sir

**Comment by oNeZ699** [comment]
@whty541 thx so much you fixed my problem aswell
