### ISSUE TITLE
Logout after every run (even when I pause and quit by myself)

### ISSUE THREAD

**Issue by dhorie** [kolton/d2bot-with-kolbot#336]
Run is ok but when it's over, the game left and logout just like c/i but then they need to login back without crashing or restarting.

**Comment by whty541** [comment]
I have the same problem, Bot runs fine after run it kicks back to the login screen and i get put in a Queue.

**Comment by WiZzMaN47** [comment]
All u probably needed to do was change some settings in D2BotMap.dbj
/D2BotLead.dbj or whatever one u use

**Comment by whty541** [comment]
what setting would that be?
