### ISSUE TITLE
Logout after run.

### ISSUE THREAD

**Issue by whty541** [kolton/d2bot-with-kolbot#339]
Bot runs and works fine I have the games set to 10 minutes, so after the wait time is up it exits game and instead of making a new game it seems he logs out and logs back in resulting in a queue, I only have 1 key and one account running so im not sure if its trying to switch to a key or what. Ive looked through the leader file and i cant see any setting in there that i could change, There was a user on here that posted the same issue as me but then he closed it and said fixed without giving the solution. Any help would be great thanks.

**Comment by whty541** [comment]
If i manually close the bot with one second left there will be no queue.

**Comment by WiZzMaN47** [comment]
Try one of the *.dbj files "D2BotLeader.dbj or D2Botfollow.dbj" or whatever
file it is

**Comment by whty541** [comment]
im not sure what im looking for i use D2botlead.dbj but is there a setting in there that needs changed?

**Comment by WiZzMaN47** [comment]
Well in D2Botleader.dbj it has lots of that might help u out. Turn of all
wait times or lessen them

**Comment by whty541** [comment]
took all the wait times off and i still go back to the login screen after a run

**Comment by RogersRo** [comment]
I have same issue. I have used all the .dbj files during troubleshooting. 
It appears to be an issue with d2bs core and the way it handles logins / game creations. Mule, Blank, Lead, Follow all have the same issue. Legit D2 loaded does not produce a queue, but a blank bot loaded, create one game, leave, next game is queued 600s. Bot is working, but not at optimal speed. Currently just maxing every script i can to get max monsters killed/hour due to this queue issue.

**Comment by RogersRo** [comment]
However, vampirewolve on BH has a 1.6xxx version of d2bs, we have 1.5.x.. he may have fixed that core issue ;)

**Comment by sidehacker** [comment]
I'm getting the exact same issue, bot logs after every run then I have to wait in queue. Nothing that I found could fix it either, I've looked through all the .dbj files and still no solution.

**Comment by RogersRo** [comment]
Its definately in the way d2bs leaves the game. If you force close manually before the run is finished, there is no queue on relog. That really narrows it down quite a bit.

**Comment by whty541** [comment]
This problem also happens if your bot chickens.

**Comment by ross-weir** [comment]
**[D2BS is not safe](http://www.blizzhackers.cc/viewtopic.php?f=204&t=545315)**

**Comment by RogersRo** [comment]
Find your toolsthread.js

Locate:
	this.exit = function () {
		this.stopDefault();
		quit();
	};

Change to: 
	this.exit = function () {
		this.stopDefault();
		void quitGame(); // uises d2bs core function to leave game instead
	};

**Comment by RogersRo** [comment]
200+ runs no issues since that fix

**Comment by whty541** [comment]
Works, no queue.

**Comment by tererere** [comment]
you deleted the fix, how can i fix it now?

**Comment by RogersRo** [comment]
Toolsthread.js
	this.exit = function () {
		this.stopDefault();
		//quit();
		quitGame(); // used to prevent 600 game queue after every run, this will close and reload d2 after each run. Not ideal, but works.
	};
