### ISSUE TITLE
Bots Exist Battlenet And Log In Again After Leaving/Finishing A Game

### ISSUE THREAD

**Issue by Bysti21** [kolton/d2bot-with-kolbot#340]
Hey guys.
All of my bots, regardless of which one I use, do fine entering a game and running in the game, but when it comes to them leaving a game, they either exist Battlenet on their own or they get kicked out of Battlenet and then they try to sign back into Battlenet. Sometimes it results in me getting a realm down and sometimes it doesn't, but I'm not sure why it happens. 
This happens if my bots finish a game on their own or if I manually exist the game myself.
This also only happens when I'm using Kolbot and never happens when I'm using Diablo 2 without Kolbot.
I saw that a few other people had the same issue, but none of the solutions were available in their posts so if anyone can help me out, I would appreciate it.

**Comment by RogersRo** [comment]
This issue hasn't been solved. Most likely cause is the d2bs client is not responding to battle net appropriately, so it boots you off after run. Fix is probably not going to happen for this issue if thats the case. (Stage.dlls)

**Comment by Bysti21** [comment]
I think there is a solution to this problem becaue I’ve seen bots working really well and creating games within like 5-10 seconds of ending their current games on both ladder and nonladder within the past couple of weeks so I’m sure there is a solution, but it just might not be out to the public yet.
The worst part about this problem is that my bot has to re-enter battlenet and then they get stuck having to wait in line to make a game and my bot is usually always in a position around 589 so that takes about 10 minutes for them to be able to make a game again.

**Comment by RogersRo** [comment]
You still havent fixed your toolsthread.js if you are getting 600 game queues. I can create games  within 5-10 seconds np even with relog. multiple bots on same ip as well.

**Comment by Bysti21** [comment]
I appreciate the tip, sir. I’ll give it a try when I get home. Thank you.

**Comment by natedawg152** [comment]
Can someone give me a copy of their toolshed file cause I see what your fix is but I don’t really understand what I’m supposed to take out, or add.  My file looks a little different than y’all pictures.  Thank you very much guys
