### ISSUE TITLE
No new games can be created right now

### ISSUE THREAD

**Issue by oNeZ699** [kolton/d2bot-with-kolbot#341]
Hello, when bot finishes the game saves and exit, logs out and login and after I can't create or join new games after liek 10 minutes, how to fix this?
https://gyazo.com/f2ea38a0bea01da9ddc484468b9e78b9
https://gyazo.com/ac815402156442848b55f3724f1cf19c

Thanks in advance guys

**Comment by RogersRo** [comment]
toolsthread.js 

	this.exit = function () {
		this.stopDefault();
		//quit();
		quitGame(); // add this instead
	};

**Comment by oNeZ699** [comment]
thx so much RogersRo for the help

is this correct in toolsthread.js?

https://gyazo.com/ed41aaa4229b2c6b76422eedc9696248

**Comment by RogersRo** [comment]
Np, that looks correct. Run it and see :)

**Comment by oNeZ699** [comment]
@RogersRo thx so much for the help, right now on delay to create game haha, btw is it safe to run Kolbot on 1.14d? or still can be detected?

**Comment by RogersRo** [comment]
It is detectable and will be banned for. Only use accounts and cdkeys you are willing to lose. If you are extra cautious, use a different IP as well, as blizzard is reporting they will ban all accounts on the IP.

**Comment by oNeZ699** [comment]
oh I will be banned? I saw many bots running =(

**Comment by RogersRo** [comment]
Yes, many bots are running because it is cost-effective as its not instant ban, but in waves.

**Comment by oNeZ699** [comment]
ok, your trick worked on toolsthread, now it closes the game, thx so much :+1: 

Hope we don't get banned xD

**Comment by humlebi** [comment]
I get this issue with muleloggers, because instead of quit game/restart the game, it leave to lobby, and select next character. Is it possible to change/replace/insert a code, so it will restart the game instead?

**Comment by natedawg152** [comment]
Can someone post a link to the full script on how it should be.  Cause I don’t think I’m doing it right.  Don’t really know what to delete and what to put in it’d place.  I’d really appreciate it thanks guys

**Comment by pglandrew** [comment]
any fix for this? i use this toolsthread.js

this.exit = function () {
	this.stopDefault();
	//quit();
	quitGame(); // add this instead
};


all was fine...until now...now i just do a run....exit game as normal using quitGame...and now i get line position, any ideea?
