### ISSUE TITLE
MuleLogger : Restart Game, instead of Leave to Lobby change?

### ISSUE THREAD

**Issue by humlebi** [kolton/d2bot-with-kolbot#343]
Hi!

When i use entry "D2BotMuleLog.dbj", i get "Waiting in line" for 600 seconds, after it have checked a character, because after its done, it exit to lobby, and then to character selection, and selecting the next character in line.  Is it possible, to replace some codings, so it will restart game instead, and then continue with the next in line?

**Comment by Bysti21** [comment]
Look at this topic. Just replace those lines in your ToolsThread with the lines in this post. I had the same issue of having to wait in line after leaving a game, but when I replaced those lines with the ones in this post, my characters close D2 and reopen it and they no longer wait in line.

https://github.com/kolton/d2bot-with-kolbot/issues/341

**Comment by humlebi** [comment]
Thanks Bysti21

I tried, and it does not help. When a character is logged, it get kicked out, either to lobby, or back to battlenet login. It does not close the game, like I hoped it would
