### ISSUE TITLE
MF Helpers Get Stuck And Don’t Move

### ISSUE THREAD

**Issue by Bysti21** [kolton/d2bot-with-kolbot#345]
Hey guys. 
I’m having a problem (sometimes) where my MF Helpers get stuck behind mobs and instead of trying to kill the mobs in order to move, they just stand there.
The most frequent examples of this that I get are when doing Anderial and hunting for Destruction Keys (Nik.)
During Anderial, it’s usually only the issue of monsters blocking my Paladin’s way to get to Anderial and my Paladin just stands there using healing pots until he runs out or goes to town to heal.
During Nik. it is sometimes both a problem with monsters blocking my Paladin’s way to get to Nik. as well as sometimes he gets stuck behind a wooden object.
Another issue I have noticed is that, about half of the time, when I am having my MF helper help with Duriel, he goes into my Sorc’s portal but does not attack at all for some reason. This only happens about 50% of the time, but I’m not sure why and why it only happens with Duriel. I stopped running Duriel for this reason and would like to be able to run him again, is possible.

Any solutions or suggestions would be appreciated. Thank you.

**Comment by noah-** [comment]
Post your skills config option. Are you using any of the dodge options?
