### ISSUE TITLE
kolbot 

### ISSUE THREAD

**Issue by snansen** [kolton/d2bot-with-kolbot#347]
my bot just stand in the town and says (bad attack dont ecpect your bot to attack. )     anyone there can help a bit with this issue have looked in the attack script but cant find the issue :(

thanks

**Comment by WiZzMaN47** [comment]
You have to set up the type of attack in the config file.

**Comment by snansen** [comment]
thanks dude. now the bot just make the run and close the game after can you tell me how to repeat the games ? :)

**Comment by snansen** [comment]
16:03:39 (snansen) Window has unexpectedly exited... starting profile
16:03:42 (snansen) Crash Info: Script: no entry Area: Rogue Encampment


the game chrashes all the time and dont know how to see whats wrong

**Comment by noah-** [comment]
if you replaced quit() with quitGame(), that is a side affect
