### ISSUE TITLE
Bot Leaves game and closes all the way to character screen then 600 game wait

### ISSUE THREAD

**Issue by Bayouking** [kolton/d2bot-with-kolbot#348]
I know people have solved this issue but I can't seem to find the solution.

**Comment by pglandrew** [comment]
edit ThreadTools.js 

you have actualy:

this.exit = function () {
this.stopDefault();
quit(); 
};


you need to change with this:

this.exit = function () {
this.stopDefault();
quitGame();
};

this is the fix atm
