### ISSUE TITLE
Silent Fix, bot cant stash or cube anymore, drop items on ground, at NPC

### ISSUE THREAD

**Issue by humlebi** [kolton/d2bot-with-kolbot#350]
After tonights short server down, my farmers cant store items in stash anymore. Instead, they drop loot on the ground, at the NPC, in whatever act the farmer was running in. I got aware of this, when i checked the log, and one of my farmer found a Zod, from a place in A1, and it was laying at Akaras feet

**Comment by icch89** [comment]
did you found a fix, for that?

**Comment by thcjay** [comment]
I inserted a line to actually open the stash before moving items to stash and it works! Surprise surprise!

Town.js line ~1550

**Comment by icch89** [comment]
in "storage" javascript?

**Comment by 77920** [comment]
Its much more than just this.

**Comment by icch89** [comment]
i mean gold is stahsed correct. so he finds chest, also logs the item as "kept"+info, but in my opinion, iam no pro to coding, the stash.item function just need a small fix.

**Comment by pglandrew** [comment]
Hello, any fix for this problem?? can some one help?

Regards

**Comment by humlebi** [comment]
It would have been way easier, if it was made more human-like. Go to stash - store item(s), close stash, move on.. It does this with gold, so why skip this with items and cubings? :(

**Comment by pglandrew** [comment]
@humlebi if that easy can you post here how to fix this please?

**Comment by humlebi** [comment]
@pglandrew if i had it, you bet

**Comment by thcjay** [comment]
It works the same way with Cows.js btw, just openCube before it places leg+tome in there and its good again, apparently.

Gonna take a while for me to go over all the stuff that way, a little help please :(

**Comment by icch89** [comment]
@thcjay can you show us/me pls how you did it for found items? what u did edit where in which script

**Comment by oNeZ699** [comment]
My bot found Vex and other items and dropped fuck! Anything to modify in Town.JS Line 1548?

**Comment by oNeZ699** [comment]
if (result) {
						Misc.itemLogger("Stashed", items[i]);
						Storage.Stash.MoveTo(items[i]);


What we change or add? @thcjay  Thx mate

**Comment by Bysti21** [comment]
I found this line in the Cows bot file and I would think it is the line(s) that needs to be added to get the bots to open the stash, but I am not sure which file or line to insert it in.


		if (!Town.openStash()) {
			throw new Error("Failed to open stash");
		}

**Comment by sunace** [comment]
any fix yet anyone?

**Comment by Aeolus000** [comment]
I added:

this.openStash();

in between that if statement above, and edited town to use telekinesis on the stash, and it seems to be working now for me.  So the full block looks like this now at 1548:

if (result) {
					Misc.itemLogger("Stashed", items[i]);
                                        this.openStash();
					Storage.Stash.MoveTo(items[i]);


not sure if that actually did anything, but my sorc had a few keys of hate drop and never stashed them, then I did this, and it has stashed one since then.

**Comment by oNeZ699** [comment]
@Aeolus000 I tested and works, thanks so much Aeolus!!

**Comment by kololbots** [comment]
I've tried Aeolus 000.
My item dropping doesn't work.
We need your strength.
When you drop the item, close the esc and dorp the item
 and click the stash again.
Please attach a script so that we can drop the item.
I would be grateful.

**Comment by Aeolus000** [comment]
kololbots I have no idea what you're even saying to be honest. It sounds like you're asking me to get it to drop the item? That's the opposite of what we want. We want it in the stash. I also posted the exact change up there. That change goes in Town.js at line 1548

**Comment by kololbots** [comment]
Thank you for your response to Aeolus OOO
Does the automule work correctly now?
Do you drop things off the warehouse ?

**Comment by oNeZ699** [comment]
I am having problems now with cubing runes, not working propperly, but for normal drops works good so whatever.

**Comment by Discjonny** [comment]
Aeolus000 for president!

**Comment by icch89** [comment]
cannot find a function for opencube. can someone tell us where to add which function to open cows/cube
