### ISSUE TITLE
Disconect

### ISSUE THREAD

**Issue by Discjonny** [kolton/d2bot-with-kolbot#352]
Hey there, i setup everything with my bot but if my sorc starts running he disconect after 4 sec ingame or something, create a new game and loop i have no idea what could it be iam running 1.14D and kolbot is also setted with 1.14D can some1 help me? :S

**Comment by Aeolus000** [comment]
i fixed "connection interrupted" issues by changing 2 lines in my character's config, specifically changing these 2 variables:

Config.PackCasting = 2
Config.Waypointmenu = true

**Comment by Discjonny** [comment]
wow thx that fixed it :O

**Comment by Discjonny** [comment]
got a fix when bot is doing run, quiting d2 completly and need to wait 500 positions do create a game? :o

**Comment by Aeolus000** [comment]
The fix for that is in another thread. Something about quitGame() instead of quit()

**Comment by Yrcraw** [comment]
Is there something like quit lobby? So you don't actually quit every game and reload everything?

**Comment by Aeolus000** [comment]
that's what it does unedited. If you do that you get put in the "you must wait to create a game" queue
