### ISSUE TITLE
quitGame(); results in bot/game never reloading

### ISSUE THREAD

**Issue by Aeolus000** [kolton/d2bot-with-kolbot#353]
Basically what it says above. If you set it to quit after the game, it simply quits the game for good. This means I have to manually rerun the bot after every run. I know people around here are saying they don't have that problem, and one fix that was proposed was deleted out of another thread. If anyone can message me it at least, that'd be great.

this.exit = function () {
this.stopDefault();
//quit();
quitGame(); // add this instead
};

This is exactly what I have in my ToolsThread.

**Comment by Aeolus000** [comment]
I think I got my D2bot to not crash as it was running, eliminating this issue on my own.

**Comment by pglandrew** [comment]
how you fix this?

**Comment by Aeolus000** [comment]
Simply running it as admin fixed it for me lol

**Comment by pglandrew** [comment]
you mean you run d2bot.exe run as admin fix the problem with save exit?

i run the d2bot.exe all time with run as admin and still have the problem with save exit, 
atm using quitGame and still get line position game lenght 400 seconds

any ideea?

**Comment by Aeolus000** [comment]
If i don't have it quitGame() then i get the queue everytime. This problem I had just meant that I had to manually restart my bot after every single run. Simply running it as administrator kept it up. With quitGame, I never get the creategame queue anymore.

**Comment by pglandrew** [comment]
ok my problem is this: i use quitGame, i run d2bot as administrator , and still get queue

can you show me your d2botlead.dbj? what you use? maybe is from d2botlead.dbj the problem

**Comment by Aeolus000** [comment]
mine is default on everything except the game delays, which are actually shorter than normal.

**Comment by pglandrew** [comment]
can you give me the default d2botlead.dbj

and game delays what you mean?

**Comment by Aeolus000** [comment]
the default d2botlead is right here on github you can just redownload it. I mean editing the file and changing the wait times in between games.

**Comment by pglandrew** [comment]
you mean the 120 seconds? 
i change 120 seconds to 10 seconds maybe this is the problem?

**Comment by Aeolus000** [comment]
honestly, i'm not sure. If you're having problems, you should do what I did and just trial and error until you figure it out. That's how I got a lot of things working that weren't before. I never even get this problem anymore because quitGame is the solution to that problem.

**Comment by pglandrew** [comment]
I figure out, if maxgame is 400 and he dont dont kill baal, he go relogin...and he get line position, he dont use quitGame, when maxgame is out....shold use quitGame, not relogin...
