### ISSUE TITLE
Is there a way for bot not to crash after every run?

### ISSUE THREAD

**Issue by Yrcraw** [kolton/d2bot-with-kolbot#355]
Got it running smoothly, just after every run it disconnects completely and restarts with no problem. I would like to know if theres a way to not disconnect, join lobby again and create game (without the long queu)

Thx

**Comment by Discjonny** [comment]
would be interested in a solution also, i dont find a way to fix that, if you know how to fix it please add a detailed comment there i need to edit and what exactly :o

**Comment by Aeolus000** [comment]
it has to disconnect, otherwise it puts you in the long "create game queue", which on average is like 15 minutes long. It's better for the bot to just close to whole game.

If you're saying you're getting the long ass create game queue, then you need to change it so the game completely closes after every run.

**Comment by Discjonny** [comment]
hey @Aeolus000  my bot does exactly do this, he runs complete it or it gets a chicken :( and after that my bot is logging out, closing d2 , reopen it relog into it and want to create a new game after some sec, then i need to wait 580~ places about 5-9 Min and i dont know why he does this, if i log in with other method to run multiple d2 chars ( they not online if bot is running ) i can relog change charackter, create a new game and so on it only happen when bot is running, do you have an idea? i already tried this:
https://github.com/kolton/d2bot-with-kolbot/issues/341 
testes a bit, does not work :S

**Comment by Aeolus000** [comment]
I'm not sure. When my bot exits Diablo II and then loads it back up, it doesn't have to wait in a queue, it just makes the next game. Perhaps you need to configure the delays in D2BotLead and stuff? #341 is what fixed this problem for me.

**Comment by Discjonny** [comment]
@Aeolus000 can you give an example from your delays stuff? maybe i find an error or something :)

**Comment by Aeolus000** [comment]
I think mine is actually totally default. Have you edited anything else? What else have you done?

**Comment by Aeolus000** [comment]
doing andariel, mephisto, opening chests in lower kurast, and summoner, my average game time is like 3 minutes.

**Comment by Discjonny** [comment]
no i dont edit it its on default,
it happens in every game lenght, i set it up to run a 6 min game, 10 min, 15 min and now 17 min ( my sorc is weak need to go an other path )
but it happens everytime no matter how long / short the game is

**Comment by Aeolus000** [comment]
I'm not sure what to tell you Jonny. We all had this problem, but putting quitGame() in the correct place in toolsthread solved this for all of us.

**Comment by Yrcraw** [comment]
You know if there is a fix to run ancient tunnels. Right now it c/I every time it opens and tries to get in. Where do u config lk chests?

**Comment by Aeolus000** [comment]
in the character config i have "chestmania" set to true, and i have every act blank except act 3, and i have [79], 79 being the area id for lower kurast

**Comment by Yrcraw** [comment]
Nice! Ill give it a try.

**Comment by Discjonny** [comment]
hey iam at home now, i paste my parameters below:
var StarterConfig = {
	MinGameTime: 120, // Minimum game length in seconds. If a game is ended too soon, the rest of the time is waited in the lobby
	PingQuitDelay: 30, // Time in seconds to wait in lobby after quitting due to high ping
	CreateGameDelay: 10, // Seconds to wait before creating a new game
	ResetCount: 999, // Reset game count back to 1 every X games.
	CharacterDifference: 99, // Character level difference. Set to false to disable character difference.
	ChatActionsDelay: 2, // Seconds to wait in lobby before entering a channel

this.exit = function () {
		this.stopDefault();
		//quit();
		quitGame();

is here something wrong?

**Comment by Aeolus000** [comment]
did you put 
```
this.exit = function () {
this.stopDefault();
//quit();
quitGame();
```

into your d2lead? If not they both seem fine

**Comment by Discjonny** [comment]
no just copy paste it from lead and toolsthread ;D
y need to watch it but i dont know why the wait times comes :S
