### ISSUE TITLE
Added .nip files but bot does not use them

### ISSUE THREAD

**Issue by killswitch1** [kolton/d2bot-with-kolbot#359]
Hi everybody,

I got the following problem: I added some .nip files to the folder /kolbot/pickit and also added the following lines to my char-config-file:

Config.PickitFiles.push("normal.nip");
Config.PickitFiles.push("set.nip");
Config.PickitFiles.push("special.nip");

But the bot seems only to use the kolton.nip and the LLD.nip files. I commented them out:
//Config.PickitFiles.push("kolton.nip");
//Config.PickitFiles.push("LLD.nip");

but the bot does not use my files... so if I configure it this way, he picks up nothing atm. Any ideas what's wrong? Thanks.

**Comment by killswitch1** [comment]
Ok, finally i know now, that it's saying valid entries = 0. 
But on normal.nip I have the [name] == lumrune entry and it should be valid at least...
So still the problem remains...

**Comment by RogersRo** [comment]
Make sure you use the nip checker to verify your files are OK. Then make sure you put them in the right folder ;)

**Comment by killswitch1** [comment]
Well, can you explain what's wrong with [name] == lumrune
? whats your nip checker saying?

**Comment by killswitch1** [comment]
Ok, now I found my problem. It seems because I copied the files from an usb stick and did not create totally new files, they took some strange attributes from the file system. So when the bot tried to read them, he ran into this attribute and could not read the files! I then deleted the files and created them new. Now bot can read them and works perfectly! Issue can be closed :)
