### ISSUE TITLE
18.3.18.100 D2BS is not responding... starting profile

### ISSUE THREAD

**Issue by kk23501876** [kolton/d2bot-with-kolbot#360]
Version18.3.18.100 crashes and D2BS is not responding... starting profile
But version 17.7.10.100 can working normally

I have install Microsoft Visual C++ 2005.2008.2010 Redistributable Package (x86)
and .NET Framework 4.61.

Thank you so mush for kolton bot team update and debug.

**Comment by noah-** [comment]
1) are you starting as admin
2) did you set version to 1.14d

**Comment by kk23501876** [comment]
Yes...
I use starting as admin and set version to 1.14d
My system is win10

**Comment by kk23501876** [comment]
Sorry about that,I find some error
I forget add new game "Profile Name"
