### ISSUE TITLE
useWaypoint: Failed to use waypoint 

### ISSUE THREAD

**Issue by humlebi** [kolton/d2bot-with-kolbot#363]
Hi

I get this error a few times each hour. I live in EU, so i mostly get this outside, like on east and west

When i spot this issue, the character is rubberbanded when going too far away from a npc, then get thrown back to npc. Walking myself doesn't fix this

Is there any setting that is causing/fixing this? I have no idea tbh, otherwise its lag that cause this, and maybe a fault in the "state" of shopping with npc

**Comment by RogersRo** [comment]
what is your ping when this happens?

One way to see your ping through d2bs is to hit Home (open console) then type .exec Print(me,ping);
if its >250-300 range, you will have lots of issues i believe.

**Comment by humlebi** [comment]
@RogersRo Thanks for your reply

I tried that, and nothing happen. This is output from the console, when the errors are happening

16:12:37 (profile)  Error in Eldritch (pather.js #987) useWaypoint: Failed to use waypoint (Area: 1, Ping:156, Game: xx)
16:13:41 (profile)  Error in Abaddon (pather.js #987) useWaypoint: Failed to use waypoint (Area: 1, Ping:172, Game: xx)
16:14:48 (profile)  Error in Bonesaw (pather.js #987) useWaypoint: Failed to use waypoint (Area: 1, Ping:156, Game: xx)

**Comment by noah-** [comment]
This is due to your ping and dsync with server. You can't use waypoint because you are too far away from it.

**Comment by jbost1** [comment]
Any way to increase the movement distance once a failed move to the WP has been made? Usually when I manually move off a distance, and let the bot go back to it, everything is fine.
