### ISSUE TITLE
farcast amazon CS

### ISSUE THREAD

**Issue by ifugenji** [kolton/d2bot-with-kolbot#366]
Hi , i tryed to get farcast with javazon with Charged strike but i changed packet casting = 2 and set up 255 255 fcr fhr ect everywhere ,  is number 24 skill , but i didnt farcast , my javazon is doing the skill with the distance but don't hit enemy ... any advice ?

thanks

**Comment by StoneOfJordan** [comment]
Farcast doesn't work anymore.

**Comment by RfBz** [comment]
any way to mod the script so the zon cs's normally?
