### ISSUE TITLE
Help! - Cow script not cubing leg + book 

### ISSUE THREAD

**Issue by zealomighty** [kolton/d2bot-with-kolbot#368]
Error in Cows (cows.js #179) Failed to cube leg and tome

Do I need to have the cube in an exact location? I've tried quite a few things, any advise would be greatly appreciated!

**Comment by zealomighty** [comment]
Can anyone please assist me with this? I'm trying to edit the script to have the cube in the stash at all times. I think this should fix the issue. Please look into this if you have time my fellow readers. Thank you!!!!!!

**Comment by zealomighty** [comment]
I LOVE YOU NOAH

**Comment by icch89** [comment]
What is the fix?
