### ISSUE TITLE
You are in Line to Create a Game

### ISSUE THREAD

**Issue by TinyHoney** [kolton/d2bot-with-kolbot#373]
You are in Line to Create a Game.
Try Joining a game to avoid Waiting.

Your position in line is : 2700

If i Run 3 Bots on 1 PC i have something like that ... On all cd keys 
i cant join and cannot creating any game .. where is problem ?

**Comment by thcjay** [comment]
README.md
>>D2BS IS NOT SAFE FROM DETECTION!

**Comment by classic191** [comment]
i have the same problem

You are in Line to Create a Game.
Try Joining a game to avoid Waiting.

Your position in line is : 2700

If i Run more the 2 Bots on 1 PC
where is problem?
