### ISSUE TITLE
Adverts

### ISSUE THREAD

**Issue by dannyytty** [kolton/d2bot-with-kolbot#379]
Please don't allow adverts to start creeping in. This was never the purpose of this software, it's a slippery slope and will adversely effect the user experience of this great program.

http://i66.tinypic.com/2ewmip1.jpg

**Comment by wcg928** [comment]
me too    have advertising now?

**Comment by liquid1234** [comment]
I think it’s a april fools joke..=)

**Comment by humlebi** [comment]
I got freaked out when i saw it right before bed xD

close manager, change date on your computer. open manager, see its not there. keep manager open, change date back to april 1st, and bum it pop up :smile:

**Comment by liquid1234** [comment]
Same here..kkkk..=)

**Comment by dannyytty** [comment]
Same here, Please remove as it effects the user experience, we don't want this advert. You have to expand you manager window or it blocks the text, it want it compact the way I had it before.

Thanks and I hope this issue is dealt with swiftly.
