### ISSUE TITLE
Fix for droping items in automule?

### ISSUE THREAD

**Issue by Wiener93** [kolton/d2bot-with-kolbot#380]
Is there already a fix for automule?
I get the bot to open stash and pick up an item, but then he trys to drop it, but hes still in the stash screen.
Maybe someone has a fix not copy pasted from a different script?

**Comment by WiZzMaN47** [comment]
Try adding a pickit file that has all the items so the mule will know what
items to keep

**Comment by Wiener93** [comment]
Sorry maybe i didnt made it clear enough. My problem is the dropping, not the picking up.

**Comment by kololbots** [comment]
sure is done  noah master making file

**Comment by dannyytty** [comment]
use the latest version https://github.com/kolton/d2bot-with-kolbot/archive/master.zip
