### ISSUE TITLE
Stash items problems

### ISSUE THREAD

**Issue by c0ffan** [kolton/d2bot-with-kolbot#385]
Hi, im kinda new to this but i read about 8 hours and cant get the bot to stash items that i would like. for instane it just dont pick up high level runes or epic items it just picks up blue/yellow items and sells em it also sold a SC +20 life which makes no sense. The bot only pick of key of terror but not hate. Can someone please help me this drives me insane.

**Comment by zealomighty** [comment]
edit the pickit script

**Comment by c0ffan** [comment]
That i get but what do i change it tp? anyone have a done script i can use. not picky but wants it to collect perfect items and keys.

Chris

**Comment by zealomighty** [comment]
Discord info?

**Comment by c0ffan** [comment]
c0ffan#2707
