### ISSUE TITLE
Connection interrupted after trying to take Waypoint

### ISSUE THREAD

**Issue by Wingard3** [kolton/d2bot-with-kolbot#386]
Hello,

Downloaded the newest kolbot with tortoise Svn and using a fresh install of the bot and diablo 2. Got the profile running but when it enters game and runs to way point it will immediately get connection interrupted error and character will return to lobby. I am running a sorc and ive tried pindle/countess/diablo scripts and all get interrupted after running to wp. Any help is appreciated.

**Comment by dannyytty** [comment]
Check your character config and make sure its set like this:

Config.WaypointMenu = true;
