### ISSUE TITLE
Checking Versions and Waiting in line

### ISSUE THREAD

**Issue by Wiener93** [kolton/d2bot-with-kolbot#389]
Maybe im doing something wrong, but on login whenever i use D2bs i get stuck at Checking versions window. After canceling the login and loging in again it works most of the time (sometimes i have to repeat it some more times).

Now when the bot is running, after a few runs i get the "Waiting in line for creating a game" or when joining "Cant create more games" message.
I read something to change quit to quitGame, but then theres the Checking versions message holding me back from loging in.

Any solutions?

**Comment by RfBz** [comment]
i think the newest update fix's these problems install via tortoiseSVN

**Comment by Wiener93** [comment]
ive used a fresh install from yesterday so there cant be anything outdated...

**Comment by noah-** [comment]
it's your cdkey likely
