### ISSUE TITLE
D2bs window disappear

### ISSUE THREAD

**Issue by nen64** [kolton/d2bot-with-kolbot#391]
Hi guys, someone can help me out?
 When I start a bot run with d2bs kolbot,  everythings runs well, but after 30 sec the d2bs window disappear (but the game with bot still continue to work)
I would like to know how to resolve it, to let the d2bs window on.
Hope someone can answer me...
thanks!!

**Comment by davcazz** [comment]
does your bot do more than 1 run? I have the same problem .. but he only complete the run one time

**Comment by nen64** [comment]
It depends, but the bot use to make more than 1 run.  the problem is , when it crashes, because d2bs goes off, it cannot relaunch the bot....
If you know something, have any solution, please let me know
thanks, and sorry for my english

**Comment by grinhilsung** [comment]
this would happen to me, it would never start a new game after a chicken. right click ur d2bot.exe and run as administrator. should fix the issue
