### ISSUE TITLE
Custom Exp Getter Thing Help

### ISSUE THREAD

**Issue by JuicyGUm** [kolton/d2bot-with-kolbot#408]
I have this code so that when i press "." or.. the period on my far right on the keyboard, it will automatically run the code that searches for and gets an exp shrine before baal. I have it working but it doesn't teleport as fast as it should.. When i run it as a bot.. the bot teleports real fast but when i run the exp runner in Map and not Leader, it doesnt teleport through the level as fast.. Idk what's the problem maybe you can figure it out lol :) This script line i put in trunk\d2bs\kolbot\tools\ToolsThread.js

		case 110: // decimal point
				Pather.useWaypoint(4);
				Precast.doPrecast(true);

				for (i = 4; i > 1; i -= 1) {
					if (Misc.getShrinesInArea(i, 15, false)) {
						break;
					}
				}
				Town.goToTown();
				if (i === 1) {
					Town.goToTown();
					Pather.useWaypoint(5);

					for (i = 5; i < 8; i += 1) {
						if (Misc.getShrinesInArea(i, 15, false)) {
							break;
						}
					}
					Town.goToTown();
				}

**Comment by RfBz** [comment]
cool great idea il check it out see if i can help

**Comment by gtoilet** [comment]
``

**Comment by gtoilet** [comment]
heres the code I stuck together searches from tome highland to blood moor
