### ISSUE TITLE
Disconnect from battle.net message when attempting to use keys in loader

### ISSUE THREAD

**Issue by multiplay222** [kolton/d2bot-with-kolbot#416]
When I leave key column blank it works fine, but no matter what I do. I can not get the keys to work when input into this loader. I just want to be able to mule things easily by loading two copies at once lol.

Do I need multiple d2 folders? Am I missing something?

**Comment by multiplay222** [comment]
I know many posts seem to be an issue of improper hyphens or spacings, but I have tried both 16 and 26 digit keys with no spaces or hyphens either time.

I know all these keys work because I have used them in the past in the form of .mpq files

Is this the issue? Am I better off calling to mpq files?

**Comment by noah-** [comment]
have you tried without any cdkeys? (this defaults to base install cdkey)

**Comment by multiplay222** [comment]
yes and that works fine, was wondering though if its possible to get more keys working

**Comment by multiplay222** [comment]
YUP issue was install location, all good now.
