### ISSUE TITLE
Lord De Seis seal 

### ISSUE THREAD

**Issue by krazy03** [kolton/d2bot-with-kolbot#422]
Error in Diablo (diablo.js #216) Failed to open de Seis seal

I get this about every other game.. I have the lates version even did a clean install 10 days ago because I messed up a few things by accident. Been getting these for a while even after using new pather that was released not long ago... anyone else have same issue or a fix?

**Comment by StoneOfJordan** [comment]
Change the distance offset to something that works for you or change `seal.interact();` to `Misc.click(0, 0, seal);` for seal id 394.

**Comment by krazy03** [comment]
I changed the distance offset as suggested and haven’t seen it so far. Thanks.

**Comment by noah-** [comment]
In FastDiablo, for example, you can use these offsets for always hitting seal:
Pather.moveToPreset(108, 2, classid, -3, 3);
...
Packet...

-3, 3 seems to work well for all seals

I intend to upload fixed scripts at some point.

**Comment by krazy03** [comment]
It still happens but its like more rare, maybe every 8-10 games. (only happens on layout 1) where seal is straight up from star.

I'm using sorcs, is there a way to use telekinesis to open seals?

Thanks.

**Comment by noah-** [comment]
Is that with the original change or what I suggested (-3, 3)?

**Comment by StoneOfJordan** [comment]
Use `Skill.cast(42, 0, seal);` for telekinesis interaction.

**Comment by krazy03** [comment]
Been trying a mix of both suggestions, will try noah- suggestion with normal unedited script now.

The strange part like i said its not always... i've watch and they sometimes open it and other times they don't if i pause and try to open it myself manually i can't do it either, i end up having to run around the seal and trying a different spot

14:38:19 (xxxxx)  Error in Diablo (diablo.js #216) Failed to open de Seis seal. (Area: 108, Ping:110, Game: xxxxxx). I dont think my ping is high at all either so no idea.

**Comment by noah-** [comment]
Fix for this will be integrated soon. https://github.com/kolton/d2bot-with-kolbot/pull/430
