### ISSUE TITLE
Rushee stashing staff act2

### ISSUE THREAD

**Issue by Neverwhite** [kolton/d2bot-with-kolbot#425]
So the rushee script walks towards the stash to cube the amu and staff for tal rasha chamber. Now the cubing script is made that after cubing it puts the content in inventory and if stash has space put it in stash. 

The problem is just that, it puts the fused staff in stash and continues to tal rasha chamber without the staff and cant open the chamber that way. I have to manually pause the script and take it out of stash and in inventory to have it work as intented. 

I have looked in the cubing script but i don't want to change the way other cubings work. So i am looking for a fix in the rushee script.

The lines are these: 

```
this.cubeStaff = function () {
		var staff = me.getItem("vip"),
			amulet = me.getItem("msf");
		if (!staff || !amulet) {
			return false;
		}

		Storage.Cube.MoveTo(amulet);
		Storage.Cube.MoveTo(staff);
		Cubing.openCube();
		print("making staff");
		transmute();
		delay(750 + me.ping);
		Cubing.emptyCube();
		me.cancel();
		
		return true;
	};
```
Now after me.cancel(); i need some code to take it back from stash into inventory.

**Comment by StoneOfJordan** [comment]
```
this.cubeStaff = function () {
		var staff = me.getItem("vip"),
			amulet = me.getItem("msf");
		if (!staff || !amulet) {
			return false;
		}

		Storage.Cube.MoveTo(amulet);
		Storage.Cube.MoveTo(staff);
		Cubing.openCube();
		print("making staff");
		transmute();
		delay(750 + me.ping);
		staff = me.getItem(91);
		Storage.Inventory.MoveTo(staff);
		me.cancel();
		
		return true;
	};
```

**Comment by noah-** [comment]
change has been integrated
