### ISSUE TITLE
sorc tp telekinesis

### ISSUE THREAD

**Issue by sunace** [kolton/d2bot-with-kolbot#429]
have all the new updates with kolbot
anytime my sorc is in town and trys to enter a tp she trys to use telekinesis on the tp but it doesn't work
she cast telekinesis 3-4 times then just walks in and enters the tp
thinking the telekinesis thro a tp was patched when the whole cube/stash issue happened but is their anyway to make her stop trying to telekinesis and just walk into the tp? it takes her like 10-20 seconds each time just standing there trying to telekinesis the tp

**Comment by DiaLover** [comment]
It was fixed.maybe

**Comment by StoneOfJordan** [comment]
Your pather is out of date. Replace it with the current one: [Pather.js](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/common/Pather.js)

**Comment by noah-** [comment]
this has been fixed in latest versions

**Comment by KevinTyrrell** [comment]
Current release version of https://github.com/kolton/d2bot-with-kolbot/tree/1.14d-stash-cube still has this issue.
