### ISSUE TITLE
shopbot doesnt work

### ISSUE THREAD

**Issue by e-soni** [kolton/d2bot-with-kolbot#433]
Hi noah-, 
i would like to shopbot, but it seems that actually npc's cant be moved anymore...

greetz

**Comment by StoneOfJordan** [comment]
#432

**Comment by mf2212** [comment]
it was available from April 30 https://www.projectetal.com/forums/wiki/?title=D2BS_Misc_Options#fixed_Shopbot

**Comment by noah-** [comment]
Shopbot has been fixed on the kolbot repo.
