### ISSUE TITLE
proxies broke with kolbot?

### ISSUE THREAD

**Issue by dabnaps** [kolton/d2bot-with-kolbot#439]
ive tried vpn/private socks 5 proxies and i always get disconnected from battle.net when i try and key temp banned, is there anything that still works ?

**Comment by StoneOfJordan** [comment]
Yes, proxies that aren't blacklisted.

**Comment by noah-** [comment]
This is not kolbot related.

**Comment by dabnaps** [comment]
lol ok thought the fact that im using the proxies with kolbot would make it
kolbot related thx for such great support
