### ISSUE TITLE
Leecher try to precast?!

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#447]
My Leechers join games and all working perfect!

i have enable:

	Scripts.Wakka = false; // Walking chaos leecher with auto leader assignment, stays at safe distance from the leader

and

	Scripts.BaalAssistant = true; // Used to leech or help in baal runs.
		Config.BaalAssistant.Helper = false; // Set to true to help attack, set false to to leech.

its do perfekt Wakka, but when Baal Assist starts, the will go to WP ore outside of the town and do precast...?!?!

i will only leech in Baal like its write there:
Config.BaalAssistant.Helper = false; // Set to true to help attack, """set false to to leech."""

how to disable precast?
===

	Config.PacketCasting = 0; // 0 = disable, 1 = packet teleport, 2 = full packet casting.
all disable on config with precast...
	Scripts.BattleOrders = false;
		Config.BattleOrders.Mode = 0; // 0 = give BO, 1 = get BO

think its not working ore a Bug :/

**Comment by Wiener93** [comment]
add this to your ballassistant:

`Config.BaalAssistant.RandomPrecast = false; // Set to true to take a random wp and perform a precast.`

will look like this in your config (dependent on other true/ false cases):

`	Scripts.BaalAssistant = false; // Used to leech or help in baal runs.
		Config.BaalAssistant.Wait = 120; // Seconds to wait for a runner to be in the throne / portal wait / safe TP wait / hot TP wait...
		Config.BaalAssistant.KillNihlathak = false; // Kill Nihlathak before going to Throne
		Config.BaalAssistant.FastChaos = false; // Kill Diablo before going to Throne
		Config.BaalAssistant.Helper = true; // Set to true to help attack, set false to to leech.
		Config.BaalAssistant.GetShrine = false; // Set to true to get a experience shrine at the start of the run.
		Config.BaalAssistant.GetShrineWaitForHotTP = false; // Set to true to get a experience shrine after leader shouts the hot tp message as defined in Config.BaalAssistant.HotTPMessage
		Config.BaalAssistant.SkipTP = false; // Set to true to enable the helper to skip the TP and teleport down to the throne room.
		Config.BaalAssistant.WaitForSafeTP = false; // Set to true to wait for a safe TP message (defined in SafeTPMessage)
		Config.BaalAssistant.DollQuit = false; // Quit on dolls. (Hardcore players?)
		Config.BaalAssistant.SoulQuit = false; // Quit on Souls. (Hardcore players?)
		Config.BaalAssistant.KillBaal = true; // Set to true to kill baal, if you set to false you MUST configure Config.QuitList or Config.BaalAssistant.NextGameMessage or the bot will wait indefinitely. 
		Config.BaalAssistant.HotTPMessage = ["Hot"]; // Configure safe TP messages.
		Config.BaalAssistant.SafeTPMessage = ["Safe", "Clear"]; // Configure safe TP messages.
		Config.BaalAssistant.BaalMessage = ["Baal"]; // Configure baal messages, this is a precautionary measure.
		Config.BaalAssistant.NextGameMessage = ["Next Game", "Next", "New Game"];	// Next Game message, this is a precautionary quit command, Reccomended setting up: Config.QuitList
		Config.BaalAssistant.RandomPrecast = false; // Set to true to take a random wp and perform a precast.`

also add this to your Config.js in the directory `d2bot-with-kolbot-master\d2bs\kolbot\libs\common\Config.js`:

`		RandomPrecast = false,`

ontop of your baalassistant.

will look like this afterwards:

`	BaalAssistant: {
		RandomPrecast = false,
		KillNihlathak: false,
		FastChaos: false,
		Wait: 120,
		Helper: false,
		GetShrine: false,
		GetShrineWaitForHotTP: false,
		DollQuit: false,
		SoulQuit: false,
		SkipTP: false,
		WaitForSafeTP: false,
		KillBaal: false,
		HotTPMessage: [],
		SafeTPMessage: [],
		BaalMessage: [],
		NextGameMessage: []

	},`

im not playing lod whatsoever but i think this might solve your problem.

**Comment by jaenster** [comment]
Guess this could be closed now
