### ISSUE TITLE
AutoMule not working!

### ISSUE THREAD

**Issue by DS1337** [kolton/d2bot-with-kolbot#454]
Hey guys me again..

i set up all like here: https://github.com/kolton/d2bot-with-kolbot/wiki/AutoMule-and-TorchMule

and i Pressed N5 ingame (to test)...after dat, my Bot is going out of the game and w8...
after waiting he make a normal NG!?
But my Mule Profile dont start automatic and nothing happen...
like dead..

is there some config, what i miss mby? :)
What did i wrong? ^^

**Comment by TheD90** [comment]
you need to Enable the profile in Automule.js

**Comment by DS1337** [comment]
Bro, it is enable...
i say it, dat ich config it like the guide here: https://github.com/kolton/d2bot-with-kolbot/wiki/AutoMule-and-TorchMule

All my Profiles on D2Bot are registered in Automule.js xD
ore u think, i am only config the Automule Profile, and just w8? :D :D :D
