### ISSUE TITLE
master branch dont work with 1.13d

### ISSUE THREAD

**Issue by 3594302** [kolton/d2bot-with-kolbot#455]
![image](https://user-images.githubusercontent.com/38686562/40463393-ae1bcc60-5f47-11e8-961f-17010edf7fe4.png)

set D2 version to 1.13d

could not run the game ,is this normally?

client 1.13d

**Comment by noah-** [comment]
You need to get the 1.13d files which are in separate branches.

**Comment by 3594302** [comment]
U mean get D2BS.dll D2M.dll  from 1.13d branch?

**Comment by noah-** [comment]
yes

**Comment by 3594302** [comment]
thanks. it seems worked.
