### ISSUE TITLE
Bot not stashing Items

### ISSUE THREAD

**Issue by amgregoi** [kolton/d2bot-with-kolbot#474]
The bot doesn't appear to be stashing any items, after looking through the code a bit I found this in Town.js ~ln. 1540
```
if (tier > 0 && tier < 100) {
	result = false;
}
```
Are all my items failing to meet tier requirements maybe? How are item 'tiers' determined?
It's also eating through gold, is it possible for it to sell useless unids vs throwing them all on the ground?

Thank you

**Comment by noah-** [comment]
if tier is not in the pickit, it is not evaluated, you likely have another issue (like setting up empty stash space for example)

**Comment by amgregoi** [comment]
@noah- 
That sounds reasonable, I didn't come across a setting for stash space.

I did come across the array for setting up free/used inventory space in the character profile.  I assumed the corresponding array for empty stash space would also be somewhere in the Config file (Character and base Config.js) but I'm not seeing anything in that regard.

**Comment by noah-** [comment]
My bad, I meant inventory. Stash should work without any config.

**Comment by amgregoi** [comment]
I definitely had the values for my inventory inverted..

Thanks for the help!
