### ISSUE TITLE
Sell ID'd items rather than toss to ground

### ISSUE THREAD

**Issue by elusiveschemer** [kolton/d2bot-with-kolbot#475]
I've combed over the `sorceress.js` and `D2BotLead.dbj` files but am unable to find how to do this. I'd like the bot to, after ID'ing items with Cain, go to vendor and sell them. Currently the bot drops them in town.  Where can I configure this behavior? If it's not a preset flag/boolean value, does anyone have any configuration I can make in the code/js to alter this behavior?

**Comment by elusiveschemer** [comment]
Update: I edited `/libs/common/Town.js` around [Line 1916](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/common/Town.js#L1916) to sell rather than drop by duplicating the case statement logic to follow the 'Sell' flow regardless. I haven't bothered to investigate the remainder of the codebase so I have no idea if this will break other process/logic flows or pickit entirely but I'll see what happens.

**Comment by elusiveschemer** [comment]
Final update: Confirmed the bot is still picking and functioning appropriately with items. The change I made doesn't appear to have broken any core functionality after a day of running nonstop. Unless @kolton has any specific requirements for the bot, I'd recommend substituting the block of code at [Line 1926](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/common/Town.js#L1926) with the code block at [Line 1933](https://github.com/kolton/d2bot-with-kolbot/blob/master/d2bs/kolbot/libs/common/Town.js#L1933) and making this the core functionality of the bot in `Town.js`.

**Comment by noah-** [comment]
The reason this change is not included is because it is slower to to use cain to id for selling. If you want to sell, don't use cain.

**Comment by elusiveschemer** [comment]
@noah- makes sense I suppose since the cost of ID scrolls/tomes is negligible in the grand scheme of things. I'll close this - thank you.
