### ISSUE TITLE
Pickit error in runeword config!

### ISSUE THREAD

**Issue by AscriptA** [kolton/d2bot-with-kolbot#477]
Iv tried my hardest to figure out why this error is occurring but can't seem to crack it. 
Iv delete most runeword lines of code correctly to try and remove the error but It keeps happening. 
It isn't messing with the script running, but I just don't wanna keep getting spammed with this error.

Currently just running an anya shopper. 

Any ideas?
let me know if you need more info.

**Comment by david1602** [comment]
Maybe you wanna post your config? Or are you on the stock version?

**Comment by AscriptA** [comment]
The runewords.js config ?

**Comment by Antiwarden** [comment]
Can you please tell us what solved the issue? I'm facing this problem right now, and don't know what I've done wrong.
