### ISSUE TITLE
My Char just stay in the town

### ISSUE THREAD

**Issue by franva** [kolton/d2bot-with-kolbot#492]
Not seeing any errors, but the Bot can open game, create a room,then.... my char stands inside town forever....

I cloned the code for the master branch and used a plugin called AutoSmurf.

I created my own config file called : 
Sorceress.wf-sor.js
under this folder:  libs\config

Can anyone please tell me how to fix this?

Thanks

**Comment by JuicyGUm** [comment]
Put useraddon.js in your config to false

**Comment by franva** [comment]
Thanks !
