### ISSUE TITLE
Kolbot pickit Problem

### ISSUE THREAD

**Issue by KlimanTT** [kolton/d2bot-with-kolbot#553]
Hello, 
My Problem is: [Error(1)] File(kolbot\default.dbj:98) ReferenceError: Pickit is not defined
I've been trying for 3 hours already to solve the problem. 
I have the bot ever completely reinstalled and everything newly adjusted, but as soon as I change something in the pickits comes again and again this problem even if I change the pikits back the problem persists.

**Comment by krazy03** [comment]
if the problem happens when you try to edit pickit then you're most likely doing something wrong, post what you're trying to change or what you're trying to add. Will be easier

**Comment by vibeD2** [comment]
i believe his problem is on line 98 of the file

**Comment by krazy03** [comment]
Yes that’s the problem but he said he did fresh Install and it works, then edits pickit and there is a problem. Which he’s most likely causing himself most likely a typo somewhere in the line so if he post can help him

**Comment by KlimanTT** [comment]
Thank you for your quick help. I found and fixed my mistake myself. I had weird way in my common folder no pickit file. Just had to add these and everything went fine.﻿
