### ISSUE TITLE
"Your Connection Has Been Interrupted"

### ISSUE THREAD

**Issue by kevinApowell** [kolton/d2bot-with-kolbot#589]
Okay, so this is seriously getting on my last nerve and I would greatly appreciate any input or help.
I've been able to troubleshoot/solve/adapt most things so far, but this one seems to escape me.

I have 8 chars running all lvl 96+ and they have been running great together for almost a week now.

All of a sudden starting just today for some insane reason.... My assassin account is getting kicked from my games with "Your connection has been interrupted" literally 100% of the time without fail in every game. 
After I noticed that I started to pay close attention and watch her, it does the same exact thing all the time randomly at different points no matter what's going on. She just gets kicked from the game usually before 2-4 minutes in and then just sits in the lobby waiting for the next game.

I even redid her entire char script page from scratch and edited every tiny thing super carefully... SAME THING... so frustrated... please help? Thank you!!

*update: If I let her join the game but not run any scripts and just wait for minimum game time she never gets kicked. As soon as she runs any script, even running to go prebuff within literally the first 3 seconds into the game she gets kicked.

**Comment by DarkHorseDre** [comment]
bro, post your configs to pastebin and link here - replies from the experts are slow but at least they'll have all the info present if/when they look..

**Comment by Math6921** [comment]
https://pastebin.com/3AXpnc3u
