### ISSUE TITLE
Mfhelpers leave CS script and "Stalling for x seconds" if I manually rejoin them

### ISSUE THREAD

**Issue by DarkHorseDre** [kolton/d2bot-with-kolbot#595]
Hi all,

My 2 followers seem to quit before dia, and I just saw them quit with no errors after 1500 seconds.
Any ideas?

Separately, I manually joined them whilst mfleader worked through CS and they did a `me.overhead` "stalling for xx seconds" - why is this?
The main place I see this "stalling" line is in `default.dbj` as:

`if (Config.MinGameTime && getTickCount() - startTime < Config.MinGameTime * 1000) {
		try {
			Town.goToTown();

			while (getTickCount() - startTime < Config.MinGameTime * 1000) {
				me.overhead("Stalling for " + Math.round(((startTime + (Config.MinGameTime * 1000)) - getTickCount()) / 1000) + " Seconds");
				delay(1000);
			}
		} catch (e1) {
			print(e1);
		}
	}`

Looks like it has decided to quit (and does as soon as minimum time is achieved) but I don't see a reason!?

**Comment by gogos-venge** [comment]
Are you using the entry script `D2BotFollow.dbj` ? I always use that one (and configure it to follow the leader profile in the first lines).

**Comment by DarkHorseDre** [comment]
@gogos-venge yes bro, follow for the mfhelpers.

How do you mean configure to follow? as in the `Scripts.Follower`?

Please note that the bot does just find doing most of the bosses from act 1-3, then at dia cs they quit.  the only indicator i see is the run time of 1500 but that was one occurence.  It could also be something to do with the CS script?

**Comment by DarkHorseDre** [comment]
Just edited subject as I saw a game of 1273 seconds where the bots just quit with no explanation.. seems to be CS script (haven't tried BAAL yet, but hear that's an issue too?)

**Comment by gogos-venge** [comment]
@DarkHorseDre No I'm talking about the join settings
```javascript
var JoinSettings = {
	"lead1": ["follow1", "follow2"],
	"lead2": ["follow3", "follow4"]
};
```
But I guess that's not a problem for you since the helpers already follow you using D2BotFollow.dbj.
Now, I believe you are using MFHelper for acts 1-4. Now MFHelper will automatically **end** if they find a leader going to cs or throne.
You can see it here (MFHelper.js):
```javascript
// Finish if leader is in chaos or throne
if ([108, 131].indexOf(player.area) > -1) {
	break;
}
```
I'm not sure if this is the cause, but it's how I can relate to leader going to CS.
Stalling usually happens to me when there are no more directions (scripts ended).

**Comment by DarkHorseDre** [comment]
Ah yes I had all that sorted.

@gogos-venge  **you are the mf man!** I keep saying i'll get looking into these things but never find the time/mindset.  I have a BO fix to look into and a few other unsolved issues!

I think I saw that chaos and baal exit earlier - crazy!  Why would they exit there? I've found countless goodies in CS on random mobs or seal uniques!  I'll be removing that shiz right now!  I'll also scope out that helper script for anything else I do/dont need!

<3

**Comment by DarkHorseDre** [comment]
ok so after commenting out the chaos and throne exits, all is well :)

**Comment by DarkHorseDre** [comment]
to be clear before I close this - this section makes the mfhelper script exit it's loop and end if leader enters dia or baal areas (because you're supposed to run dia and baal helper scripts after mfhelper):

```js
// Finish MFHelper script if leader is in Chaos or Throne
			if ([108, 131].indexOf(player.area) > -1) {
				break MainLoop;
			}
```
