### ISSUE TITLE
Code which interacts with the D2 client?

### ISSUE THREAD

**Issue by KevinTyrrell** [kolton/d2bot-with-kolbot#600]
Where in D2BS/Kolbot is the abstraction layer which controls basic functions like:

* Reading items in the inventory
* Reading what zone the player is in
* Reading the player's x/y coordinates
* Moving the player to x/y coordinates
* Opening the players inventory panel
* Casting a spell the player has learned

etc. I'd like to learn from it.

Thank you.

**Comment by gogos-venge** [comment]
The most used class object is **me**
https://github.com/noah-/d2bs full api here.

**Comment by KevinTyrrell** [comment]
Thank you.
