### ISSUE TITLE
Latest update - need to register and convert 16 char keys

### ISSUE THREAD

**Issue by DarkHorseDre** [kolton/d2bot-with-kolbot#616]
This post contains a copy of the blue post (cba to find initial blue post): https://us.battle.net/forums/en/bnet/topic/20767657443

My question is, if we register these keys, is it a trap?!

should the bot keys be registered in separate accounts and email addresses?

Thoughts?

**Comment by KevinTyrrell** [comment]
This issue does not pertain to Kolbot.

However, there is absolutely zero risk in registering your keys. It is actually advantageous to do so, to avoid key-gens from eventually randomly guessing your Diablo 2 key (and thus them registering it, locking you out of your key forever).

**Comment by DarkHorseDre** [comment]
Sorry, you're right - I was seeking input from botters in general and was on here when I found some of my keys need registering.

thanks for the input - I was concerned as I know blizz uses key/account/ip association when banning!
I had no idea what others do, but from what you say, nobody worries about it!

I'll close this - thanks again.
