### ISSUE TITLE
Is it possible to have bot create a random game name instead of preset name?

### ISSUE THREAD

**Issue by schrobes** [kolton/d2bot-with-kolbot#634]
Instead of having to input game info under the d2bot profile, where the bot creates consecutive runs called mfrun1, mfrun2, etc. Is it possible to have the bot create a randomized game name

**Comment by mf022** [comment]
check https://github.com/kolton/d2bot-with-kolbot/pull/637/commits/3cefefd28aaf15b6a11b82482d8547ab35ee8b01

**Comment by noah-** [comment]
You need to set your gamename to ? in the d2bot profile.
