### ISSUE TITLE
lord de seis issue

### ISSUE THREAD

**Issue by tgats** [kolton/d2bot-with-kolbot#641]
hello there, 
this issue does not bother me while playing softcore, but since i started playing hardcore. i would like to have this problem fixed, where my character would tele straight into lord de seis' mob in hell chaos. i unchecked the tele stomp and this thing still occurs. can someone here with a better knowledge enlighten me? thanks.

**Comment by mf022** [comment]
what class is your char?

if it's a paladin hdin char, be sure that you have upgraded your Holy Shield at max, and you added points in dexterity stats, until you get 75 max block (with HS activated).

**Comment by tgats** [comment]
both pally and druid.

**Comment by tgats** [comment]
i think i may have fixed the problem by switching the original format 
this.seisLayout = this.getLayout(394, 7773);
 to this 
this.seisLayout = this.getLayout(394, 7776);
