### ISSUE TITLE
bot doesnt log in/start

### ISSUE THREAD

**Issue by Lumaraa** [kolton/d2bot-with-kolbot#648]
hello, if i press the start button at the bot the diablo window opens but he doesnt log in or anything. but if i manually login and open a game he starts botting and if he is done with botting he leave the game and just stay in lobby and doesnt create a new game... can someone help me ? 
sorry for my bad english

**Comment by DarkHorseDre** [comment]
Did you set account name and password? then entry script as lead? Did you set game name in d2bot manager?
what does the bot manager screen say under `status`?

**Comment by Lumaraa** [comment]
yes i set everything you can see it in the picture. the bot manager says nothing he just do nothing he dont restart the game or try something

http://www.bilder-upload.eu/show.php?file=daf398-1535381337.jpg

**Comment by DarkHorseDre** [comment]
You problem is in the entry script. I mentioned it in my first post.

select the lead script as entry (`D2BotLead.dbj`)
