### ISSUE TITLE
No logging of H/D/Tkeys?

### ISSUE THREAD

**Issue by killrhythm09** [kolton/d2bot-with-kolbot#659]
Did I miss a setting somewhere? My bots don't seem to be recording when they pick these up.

**Comment by spark10z** [comment]
hi,  do you mean even your bots had picked up "key of xxx" and xfered them to mules,  you do not see them from mule viewer ? or talking about in item .log fine ?

**Comment by killrhythm09** [comment]
Sorry, I should've been more clear.

In D2Bot# (the manager window), in the item log to the right of the console, it doesn't show when they keep keys. The only way I can tell is if I pause the bot and check its inventory manually.

**Comment by imbalanced** [comment]
This is intentional behavior. If you want to see your keys, open /kolbot/libs/TorchSystem.js and set LogKeys value to true.

**Comment by DarkHorseDre** [comment]
Mine doesn't print to console either - looks like `torchsystem.js` is the only place to configure logging keys.
For normal botting it looks like item codes pk1/2/3 are the keys and the code in `pickit.js` seems to not bother printing when it finds them.

line 324 of pickit.js seems to check for the key codes and torchsystem config.
There are cleaner ways to do this, but if you change the next line and add a print before the break line, it should work.  

**so from this**:
`if (["pk1", "pk2", "pk3"].indexOf(item.code) > -1 && !TorchSystem.LogKeys) {
break;`

**To this**: 
`if (["pk1", "pk2", "pk3"].indexOf(item.code) > -1 && !TorchSystem.LogKeys) {
			Misc.itemLogger("Kept", item); //dhd added to show keys
			break;`


Even after that it didnt work, so I had to edit `TorchSystem.js` and enable `LogKeys: true` and now I get the message in the d2bs log window.

![image](https://user-images.githubusercontent.com/41862641/44949073-f0171b00-ae21-11e8-8e7d-987953243785.png)

**Comment by DarkHorseDre** [comment]
Haha @imbalanced as you wrote that I was testing!  I tested wrong way around - enabled torchsystem last and thought i needed to edit pickit aswell as torchsystem #facepalm

**devs** could we please move/copy the config of this to character/nip/other configs?  Seems weird to configure in a file some will never use!  (I'd add to documentation too, obvs)

**Comment by noah-** [comment]
At some point maybe config options will be unified/simplified.
