### ISSUE TITLE
Multiple Rushee problems

### ISSUE THREAD

**Issue by krazy03** [kolton/d2bot-with-kolbot#668]
So if you have more than 1 Rushee in game with Rusher, they can't get pass act 2  unless you set
Config.Rushee.Quester = true; // Enter portals and get quest items. (this to true)

The problem is with 2 Rushee if both are set true, for some reason one picks up the staff other picks up the ammy so they can't make staff unless i do it manually. Much worse when you have more than 2. 

If only 1 is set to true and other false, the one that is set to false does not talk to either Drognan or Atma, so it after Duriel bot Rusher goes to harem and the Rushee bot(s) can't enter TP so they can't advance.

Any help would  be appreciated.

**Comment by DarkHorseDre** [comment]
hey, my bots are down, but I did rush a month ago or so but the bot did progress to the end.
The ammy and staff issue is weird as I thought they took one each.

Are you saying both rushees when 1 is set to questing and one isnt:

both spoke to warriv to get to act 2?
Both rushees running follow entry script?
what is Config.Rusher.LastRun set as for the leader and all rushees?

Are you running the latest trunk?

**probably most importantly, ensure leader isn't muted (can you type in game and the others see the text on their screens?)**

**Comment by krazy03** [comment]
I got it working now, i had to add this above line 238 in Rushee script

					Town.move("atma");

					npc = getUnit(1, "atma");

					if (!npc || !npc.openMenu()) {
						return false;
					}

				me.cancel();

**Comment by DarkHorseDre** [comment]
Hey, I'm really surprised you needed to tweak the code - I usually have one rushee questing and the rest following and it worked fine (I do vaguely recall a few failures - I may need to re-run a rush to remind myself).

**Comment by krazy03** [comment]
Let me know how it turns out, because for me this was the problem, after adding that flawless rush! :)

**Comment by DarkHorseDre** [comment]
lol what's the flawless rush?!

**Comment by DarkHorseDre** [comment]
hey @Krazy03 I'm just getting around to this :)
did you just remove the jeryn line and add the two atma lines?  please paste your whole rushee script if you can :)
