### ISSUE TITLE
Vengeance Skill

### ISSUE THREAD

**Issue by jaenster** [kolton/d2bot-with-kolbot#685]
The Vengeance skill isn't listed in getRange which results in a range of 20.

However, this skill only works on close range.

Requested fix:
Add 
```
            case 111: // Vengeance
```
Between zeal and blessed hammer
```
            case 106: // Zeal
            case 111: // Vengeance
            case 112: // Blessed Hammer
```

**Comment by DarkHorseDre** [comment]
Already covered by noah :)
https://github.com/kolton/d2bot-with-kolbot/issues/632

**Comment by jaenster** [comment]
His proposed fix is the same as me. So don't worry i already did fix it on my side.

But it would be a little fix to take in the main version =)

**Comment by DarkHorseDre** [comment]
haha yes but I'm saying that seeing as though Noah posted the fix, he is aware, and it will (probably) get rolled into a future version! :)

Maybe close this issue and append a request to #632?
