### ISSUE TITLE
potion find mod to cow script

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#724]
https://pastebin.com/mBuNXR6Q

so I want to have barb this.clearcowlevel
and at the end of the function its if(!attack.clear(30))
I want him to clear then try to this.findpotion

I tried to modify the barb attack from item find to potion find and it didn't work in CS and as I only want a potionfind in NM cow lvl I just soon modify the cow script

I totally took the this.finditem and put in 131 potion find , I think I got all relevant item find from the attack file to put in here as a function but barb clears and goes on needs to stop and potion find

**Comment by gtoilet** [comment]
Yea i ripped all the wording from the barb attack about the item find and just changed to 131 for potion find

And as I said I tried modifying what's current as the item find just to potion find and it did not work while I was running a modified run on chaos sanctuary and that's why I started to modify the cow script only as I want to run a nightmare cow run for full potions

**Comment by DarkHorseDre** [comment]
Oh I see - it wasn't clear in your post.

What does "it did not work" mean?
You should post a link to your modified `Barbarian.js` file so we can see what you did.  

I had a quick glimpse and it seems that If you copy or modify the functions it should work.

Note that you need `Config.FindItem` enabled, and gotta change both the getskill/skillcast 142 to 131

I also see references to area = 83 (travi) - but not sure what that does..

**Comment by gtoilet** [comment]
The pastebin link that I posted is a link to the cow script that I am trying to modify I literally took from The Barbarians attack file all that consisted of the find item function and implemented it into the cow script and then after the attack clear I tried telling it to do this. Find potion and when he clears himself he does not find potion

**Comment by DarkHorseDre** [comment]
Ah, doing it that way will be messy.
Also, checking for corpses after the fact is less efficient as I've seen corpses disappear/fail soon after the kill.

You havent said what doesn't work? he "does not find potion" means he casts the skill but no potion found, or he doesn't cast, or??

I would let him normal attack then find potion just as in the original script, and I'd leave the cow script as-is then just modify the attack file - you want the bot to do exactly as the find item function does but with a different skill. You have a working model in the findpotion ability in the class attack script, so modifying that would introduce fewer errors and be easier to debug

**Comment by gtoilet** [comment]
I will later when i can how about this where do I find the corpse list of what monsters he will potion find as he only item find supers I need to add an exception for hell bovine

**Comment by DarkHorseDre** [comment]
I'm at work with limited access to code but I think
unit.spectype may be the check for the monster type, and is used in multiple places (0x7 reminds me of the unique monster parameter in clearAnyArea)

This section seems to evaluate spectype and do nothing if spectype is zero:
` if ([345, 346, 347].indexOf(unit.classid) === -1 && unit.spectype === 0) {`
`            return false;`
you can check this by looking at the monster list file and also checking how spectype or other command is referenced in the attack file when evaluating the target for the castskill for find item

**Comment by gtoilet** [comment]
All right I will check those when I get home but isn't there a list that tells the Barbarian who to loot fine from or is it just the spec type I didn't know if there was some things somewhere that was like the sorceresses static  setting

**Comment by DarkHorseDre** [comment]
Do you mean `config.StaticList`?  that is within the sorc config - you can check the barb config - theres nothing there for it.
`Config.FindItem` is a config for barbs which loots corpses immediately after a kill, and if you look at the code, it seems to use spectype to target only uniques (as per previous post).  You could change that as I mentioned to target all (0) (and you could add a check to see if its the barb doing cows, and change the spectype only then, so other clasases and uses are unaffected).

Looking at it again (at work without my bot or tools) I think this **may** be the line which specifies 0x7 as a target:
`index = ((unit.spectype & 0x7) || unit.type === 0) ? 1 : 3;`
it would be easy to change and test for you..

**Comment by gtoilet** [comment]
Yea after work yesterday I was able to go home and to get it to work and I was also just wondering if there was any way to specify which corpses Tulu like I did not know if the Necromancer had a list of who only it would revive for the Minion monsters skill

**Comment by gtoilet** [comment]
Also here's another thought how can I make potion find only work in nightmare mode as like I've stated before I only want to have a working potion fine for nightmare cows
