### ISSUE TITLE
Precast enchant only

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#736]
Ok now it's time to fix my chant script need to precast enchant only not my cold armor 

I know I could go and alter the spec precast  bit I want to only alter my enchant script

**Comment by DarkHorseDre** [comment]
If precast is called from your chant script, you can add a check in the precast script to check, and if the script is enchant, only cast ench, else do as before.

this is from the cubing script - it checks to see if townchicken is calling the script and if so, do nothing:
 `       if (getScript(true).name === "tools\\townchicken.js") {`
 `           return false;`
 `       }`
