### ISSUE TITLE
Way to add items not currently in Pickit?

### ISSUE THREAD

**Issue by Rhinoface** [kolton/d2bot-with-kolbot#739]
Is there a way to add other items that aren't recognized by the pickit files? For example, winged helms aren't recognized, but is there a way to add?

**Comment by gtoilet** [comment]
Phone died when linking my weak nip can grab the wording from there for what you want https://pastebin.com/W3TrW7YU

**Comment by DarkHorseDre** [comment]
@Rhinoface as your question is general, and related to adding any item I'll give you a general answer:
You add items dependent upon their name or type, then specify the detail if needed.

so winged helms would be a type of helm, check out the item types on AS: http://classic.battle.net/diablo2exp/items/weaponsandarmor.shtml#normal

You'll see that a winged helm is a type of helm, and is exceptional.  so you could specify: 
[name] == wingedhelm && [quality] == rare/unique/normal/superior/magic

you need to understand the type (or name), class, quality and range of attributes  of the items you want to add, and the AS site/other sites will help with that, so will other pickit entries.. and like gtoilet said, there are examples online.

Finally I recommend using notepadd ++ for nip editing and adding the nipcheck plugin as it can help catch most errors.

https://github.com/noah-/NipCheck
