### ISSUE TITLE
Error in ClearAnyArea (pather.js #1303) getPresetUnits failed, couldn't access the level!

### ISSUE THREAD

**Issue by D2Botguy** [kolton/d2bot-with-kolbot#755]
Error in ClearAnyArea (pather.js #1303) getPresetUnits failed, couldn't access the level!

I'm trying to set up a lowbie character to use the ClearAnyArea script and I can not get it to work at alll... 

I've listed the correct areas as a list and then tried them separately as a single area to clear also...
can't clear blood moor... cold plains, stony field... certainly not tower cellar levels where countess is... 

The bot runs to the wp and then glitches out, standing there... I'm going to try a couple things but the reset is in 2 weeks and I'm completely stuck on this now...

**Comment by D2Botguy** [comment]
Update... it works on a melee character that has completed normal difficulty just fine... I'm going to try and resolve the issue by turning off the vigor movement as my lowbie pally does not have vigor...

**Comment by D2Botguy** [comment]
Update... PROBLEM SOLVED!

It apparently has something to do with missing wp's... after I finished a1 with the lowbie and got all wps except Jail 1, I tried to run it from act 2 and the character went searching for a wp in dry hills... after that I got far oasis and lost city on my own for good measure and ran it again, the char used the Lut Gholein wp to go to black marsh and off to hunt countess levels any areas (21, 22, 23, 24, 25)

gg

**Comment by bfass** [comment]
Actually every area script will cause this error if you don't set "config.cubing = false" or your bot will keep trying to get a cube in Act 2 even If it is a fresh level 1 character.
