### ISSUE TITLE
rusher/rushee little issues

### ISSUE THREAD

**Issue by pivoivo** [kolton/d2bot-with-kolbot#759]
Hey guys, sorry if it is a double post, but I could not find anything. If there is already something about that, I would be happy with a link.

1st Problem: Rusher does not enter game automatically (or is this normal?)

2nd and bigger Problem: In A2 the rushee is not entering Duriels Chamber. It takes tp for puting in the staff, then leaves again, wait in town and take the next tp in front of Tyrael, but the quest never finishes, because the rushee was not in the chamber.

Maybe anyone can help me out :)

**Comment by gtoilet** [comment]
Problem 2 is fine it works

**Comment by pivoivo** [comment]
> 
> 
> Problem 2 is fine it works

what do you mean? Just let it run!?
