### ISSUE TITLE
Mpq reader suggestion

### ISSUE THREAD

**Issue by gtoilet** [kolton/d2bot-with-kolbot#764]
A friend asked how to read his old mpq file for old d2bs as new uses new format and I never messed with mpqs help me help him thanks

**Comment by mf022** [comment]
what mpq? 

if it's a loader key, check cdkey viewer
https://github.com/mf022/D2LoD_files/tree/master/D2LoD_key_utilities

if it's about another d2 mpq file, see http://www.zezula.net/en/mpq/download.html
