### ISSUE TITLE
Renaming Config files

### ISSUE THREAD

**Issue by wills219** [kolton/d2bot-with-kolbot#765]
I must be missing something but I can't seem to find how to rename my character files (paladin,sorc, etc,}. When i just try renaming the file it won't use the file.

**Comment by aim2kill** [comment]
When youre renaming the file make sure you dont delete the class from((( sorceress.NamE.js))) and name is case sensitive or just run the bot and press ESC in-game and will automatic make one for you.

**Comment by wills219** [comment]
But my char files don't have .js in the name

**Comment by aim2kill** [comment]
Sorceress.Mychar_Name / Paladin.Hammer-Dre / Amazon.Char-naMe check caps and you cant delete the class from the front of your name

**Comment by mf022** [comment]
https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config#character-config-filename-options

@wills219 
you have to uncheck the Windows Explorer option ["Hide extension for known file types"]([url=https://www.freeimage.us/share-D4A8_5BFFCF30.html][img]https://www.freeimage.us/thumb-D4A8_5BFFCF30.jpg[/img][/url]), then you'll see those extensions of the files.

**Comment by wills219** [comment]
Okay, ill try it again, thanks!

**Comment by wills219** [comment]
Looks like leaving the .js off the end may have worked! I've been searching for an answer to this for a while. Thank you guys.
