### ISSUE TITLE
Pickit doesn't pick up Potions

### ISSUE THREAD

**Issue by shiny001** [kolton/d2bot-with-kolbot#777]
My character picks up everything but potions. I dunno what to do.
my pots.nip is like this:

```
[name] == greaterhealingpotion
[name] == superhealingpotion
[name] == greatermanapotion
[name] == supermanapotion
[name] == rejuvenationpotion
[name] == fullrejuvenationpotion
[name] == gold # [gold] >= 500
```
and my `config:

```
	Config.BeltColumn[0] = "hp";
	Config.BeltColumn[1] = "mp";
	Config.BeltColumn[2] = "rv";
	Config.BeltColumn[3] = "rv";
```
and

`Config.PickitFiles.push("pots.nip");`

I tried everything, even starting from scratch. It picks up gold but not potions. (I have no other pickit nip files attached). What can I do, please help

**Comment by DarkHorseDre** [comment]
You missed out the value for Config.MinColumn[{0-3}] - you should just paste your config & nips to pastebin and link in your first post. please also confirm which branch of code you are using.

if you have set Config.MinColumn[{0-3}] correctly and you drop greater+ pots, it will pick them

**Comment by shiny001** [comment]
Thank you for your reply.
My settings are:
```
	Config.MinColumn[0] = 3;
	Config.MinColumn[1] = 3;
	Config.MinColumn[2] = 0;
	Config.MinColumn[3] = 0;
```
and bot still does not pick them up. 
Does it matter that my D2 installed form downloader and not CD?

**Comment by shiny001** [comment]
[Barbarian.SpellImmunity.txt](https://github.com/kolton/d2bot-with-kolbot/files/2649293/Barbarian.SpellImmunity.txt)
[pots.txt](https://github.com/kolton/d2bot-with-kolbot/files/2649294/pots.txt)

**Comment by DarkHorseDre** [comment]
Yo, thanks.  to answer, I read that you must always install from cd, but it seems you have it working, kinda..

Are you using the TRUNK version of kolbot and its uptodate?

regarding your config, assuming your install isn't causing a problem (I would do the painful cd install just in case unless someone can vouch that it doesnt make a difference), I cannot see why you're not picking up pots. does your bot BUY pots when theyre below 3?

How many rows in his belt?

I have an idea which relates to your `Config.Inventory[]` setting but I want to hear the answers to these questions first

**Comment by DarkHorseDre** [comment]
Also, please link to a screenshot of your bot console upon startup. it should say in green the name of the nip file loaded and number of valid lines it has read

**Comment by DarkHorseDre** [comment]
ok so the structure of the files you download has branches and the main trunk. So the base folder `d2bot-with-kolbot-master` is followed by the trunk folder, or the branches and tags (and `.svn`) folders.

The d2bs and other bot files are located under each branch and trunk, so you need to be using the intended set of files.

Youre using blank (`d2bot-with-kolbot-master/trunk/d2bs/kolbot/D2BotBlank.dbj`) so the bot could operate without the correct config file - can you confirm?

tbh playing blank is not necessarily the same as leaving bot to play itself.  set it to do one clear area or a bot script and see what it does.  ensure it is all set as above, and the config is in the correct path.  also ensure that the bot generated the config rather than you copying and pasting etc. remember that the bot creates a config if it doesnt find one in the expected location.

**Comment by shiny001** [comment]
Hey again DarkHorseDre,

I do not have "trunk folder". My path is like this .... \Desktop\d2bot-with-kolbot-master\d2bs\kolbot\D2BotPubJoin.dbj. (I tried to switch to D2BotPubJoin.dbj)

![image](https://user-images.githubusercontent.com/34689393/49554982-e7b3fd80-f8b2-11e8-8f8f-8d28bd1c3fd3.png)

@GZer. My pots file is nip. I had to change it to .txt so I could upload it. I believe that picket is enabled, because it picks up gold

**Comment by GZer** [comment]
Does you bot actually do anything?
You have a few things changed that I wouldn't normally like follower. your .nip syntax looks fine but you might be missing something else it's impossible to know without you showing us the logs and how the bot performs

**Comment by shiny001** [comment]
No, I pretty much just use my bot as a pickit and chicken (on hardcore). My pickit works perfectly except for pots. I deleted my program few times today, so my log files are empty ATM. My bot gives me no errors (except for "combat is not set up correctly don't expect your  bot to attack") just  doesn't pick up pots for some weird reason.

**Comment by shiny001** [comment]
OMG, DarkHorseDre thank you. you are correct.  "

> right now you are trying to half configure the bot and ignore the errors you've created and frig it to work anyway. this is not the way to do it.

"
I set up my bot to help with public Baal Runs and it started to collect pots!
