### ISSUE TITLE
I just started using this and my first issue is attack.js #214

### ISSUE THREAD

**Issue by olsoner1** [kolton/d2bot-with-kolbot#779]
10:43:05 (xx)  Error in Andariel (attack.js #214) Failed to kill Andariel (doAttack failed) (Area: 37, Ping:62, Game: Skybbq12)
10:43:18 (xx)  Error in Mephisto (attack.js #214) Failed to kill Mephisto (doAttack failed) (Area: 102, Ping:62, Game: xxxx)

setting up a blizz sorc. This is my skill setup. Not sure if I did something wrong here or not.

	/* Attack config
	 * To disable an attack, set it to -1
	 * Skills MUST be POSITIVE numbers. For reference see http://pastebin.com/baShRwWM
	 */
	Config.AttackSkill[59] = -1; // Preattack skill.
	Config.AttackSkill[59] = 1; // Primary skill to bosses.
	Config.AttackSkill[59] = 1; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[59] = 1; // Primary skill to others.
	Config.AttackSkill[59] = 1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[59] = 1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[59] = 1; // Secondary untimed skill if monster is immune to primary untimed.

I then went to the attack file and searched for line 214. 

kill: function (classId) {
		if (Config.AttackSkill[1] < 0) {
			return false;
		}

		var i, target, gid,
			errorInfo = "",
			attackCount = 0;

		if (typeof classId === "object") {
			target = classId;
		}

		for (i = 0; !target && i < 5; i += 1) {
			target = getUnit(1, classId);

			delay(200);
		}

		if (!target) {
			throw new Error("Attack.kill: Target not found");
		}

		gid = target.gid;

		if (Config.MFLeader) {
			Pather.makePortal();
			say("kill " + classId);
		}

		while (attackCount < 300 && this.checkMonster(target) && this.skipCheck(target)) {
			Misc.townCheck();

			if (!target || !copyUnit(target).x) { // Check if unit got invalidated, happens if necro raises a skeleton from the boss's corpse.
				target = getUnit(1, -1, -1, gid);

				if (!target) {
					break;
				}
			}

			if (Config.Dodge && me.hp * 100 / me.hpmax <= Config.DodgeHP) {
				this.deploy(target, Config.DodgeRange, 5, 9);
			}

			if (Config.MFSwitchPercent && target.hp / 128 * 100 < Config.MFSwitchPercent) {
				Precast.weaponSwitch(Math.abs(Config.MFSwitch));
			}

			if (attackCount > 0 && attackCount % 15 === 0 && Skill.getRange(Config.AttackSkill[1]) < 4) {
				Packet.flash(me.gid);
			}

			if (!ClassAttack.doAttack(target, attackCount % 15 === 0)) {
				errorInfo = " (doAttack failed)";

				break;
			}

			attackCount += 1;
		}

		if (attackCount === 300) {
			errorInfo = " (attackCount exceeded)";
		}

		if (Config.MFSwitchPercent) {
			Precast.weaponSwitch(Math.abs(Config.MFSwitch - 1));
		}

		ClassAttack.afterAttack();

		if (!target || !copyUnit(target).x) {
			return true;
		}

		if (target.hp > 0 && target.mode !== 0 && target.mode !== 12) {
			throw new Error("Failed to kill " + target.name + errorInfo);
		}

		return true;

**Comment by aim2kill** [comment]
/* Attack config
 * To disable an attack, set it to -1
 * Skills MUST be POSITIVE numbers. For reference see http://pastebin.com/baShRwWM
 */
Config.AttackSkill[59] = -1; // Preattack skill.
Config.AttackSkill[59] = 1; // Primary skill to bosses.
Config.AttackSkill[59] = 1; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
Config.AttackSkill[59] = 1; // Primary skill to others.
Config.AttackSkill[59] = 1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
Config.AttackSkill[59] = 1; // Secondary skill if monster is immune to primary.
Config.AttackSkill[59] = 1; // Secondary untimed skill if monster is immune to primary

Ok 1st of all
Config.AttackSkill[1] = 59
There no such thing as Config.AttackSkill[59] that why is failing

**Comment by aim2kill** [comment]
Depend in what you want to pick

**Comment by aim2kill** [comment]
This person have a awesome pick but you may still need to edititng to your liking, I can add mine by the weekend which have for low trash pick for ladder reset, middle and high end pick

**Comment by olsoner1** [comment]
yeah its been ten years since I played this game and around 11 years since I used a bot. thanks for the help. Not sure if this will still work though when ladder resets. would be nice if it did though. If you make a low end config that would be really cool.

thanks again

**Comment by olsoner1** [comment]
I got my pickit files setup for the restart. Is there a way to use just pickit and the MH and not he bot?

**Comment by aim2kill** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/754 
Follow this steps
