### ISSUE TITLE
d2 bot exe fatal error

### ISSUE THREAD

**Issue by xxshaggs** [kolton/d2bot-with-kolbot#800]

**Comment by DarkHorseDre** [comment]
You're going to have to elaborate a lot more if you want a response..

**Comment by xxshaggs** [comment]
Hey thanks for responding to me  sorry   kinda new to this  stuff    I've
got it boiled down to something to do with the Microsoft. Net framework
4.7.2  won't work with it   I'm using windows 7   I found a working link
and installed 4.0  it worked finally for a few hours  I put it on before
bed woke up and it was shut down again  I think my comp updated  framework
 am going to look at it again

The msg   when I try to open it up says    d2bot. Exe

Clr error:80004005
The program will now terminate
Best regards,
Jarrett Miller


On Dec 13, 2018 1:04 AM, "DarkHorseDre" <notifications@github.com> wrote:

You're going to have to elaborate a lot more if you want a response..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kolton/d2bot-with-kolbot/issues/800#issuecomment-446892861>,
or mute the thread

**Comment by mf022** [comment]
> Clr error:80004005 
> The program will now terminate

You should try the limedrop-utf8 branch. This [commit] (https://github.com/kolton/d2bot-with-kolbot/commit/61e5a51ab581dfb9e6167bcdd526de424ea1f315) added a fix.
