### ISSUE TITLE
How do I reveal maphack

### ISSUE THREAD

**Issue by ulvSONS** [kolton/d2bot-with-kolbot#801]
I have setup a loader only profile to play manually, I can run and play on it just fine. I do not have maphack when i create or join games. The entry script is d2botmap, can someone help me with this please.

**Comment by sunace** [comment]
botmap should have it already? try pushing f12

**Comment by sunace** [comment]
if that doesn't work double check ur actually using d2botmap and not mule or anything else

**Comment by DarkHorseDre** [comment]
FYI: F12 works even with lead entry script

**Comment by ulvSONS** [comment]
I double checked my entry and it is d2botmap. When I press F12 it just shows/hides npc names, out of town it does nothing. I can reveal the map while bots are running with F12 (is there a way to make that automatic?). The only way I have got it to work is set true on user addon so I will just use that for manual play.

**Comment by DarkHorseDre** [comment]
Somethings wrong with your setup. with `D2BotMap.dbj` as entry you should see a white text menu at bottom left and right of screen to enable/disable vectors, monsters, and autotravel.  The maps should be revealed by default (buts as I said, f12 should reveal manually with other entry scripts). vector lines pointing to each destination should also be visible by default.

Ensure you stop bot, set the profile to use `D2BotMap.dbj as entry`, save, then start bot.

![image](https://user-images.githubusercontent.com/41862641/49961977-e36b8e00-ff0b-11e8-85d3-aca9e8f57a03.png)

**Comment by ulvSONS** [comment]
I ended up having loader only on the manual profiles, took that off and d2botmap works as it should. I can't believe I didn't check that before posting but oh well, thank you all for the help.

**Comment by tylerqr** [comment]
@DarkHorseDre , I have always selected d2botmap as my entry script for manual play and have loved it. But after a few weeks it stops working. Meaning, the map reveal, white text menu and monsters all disappear and it's as if it's using a normal entry script. Pressing F12 doesn't do anything. Any ideas why d2botmap would stop working suddenly?

**Comment by DarkHorseDre** [comment]
no idea mate - corrupted files maybe? check the last modified dates and as last resort download full kolton into separate folder and run it and see if f12 works - would take less than 5 mins to confirm
