### ISSUE TITLE
Kolbot ports out and doesnt clear

### ISSUE THREAD

**Issue by Dratos1** [kolton/d2bot-with-kolbot#814]
Hello, loving Kolbot but I have an issue: Kolbot teleports to AT and as it enters it just portals to town and goes on to the next location. I am completely unsure why it wont stay and clear...

Thanks,

**Comment by IExcision** [comment]
your attacks are not set properly, check the char config

**Comment by Dratos1** [comment]
but my setup works on mephy....

**Comment by IExcision** [comment]
does it say anything in the log? errors?

**Comment by Dratos1** [comment]
nothing.. it just tps to town
