### ISSUE TITLE
Item Viewer

### ISSUE THREAD

**Issue by deaths-A-13itch** [kolton/d2bot-with-kolbot#82]
Hey i was wondering if there is a way to set the item viewer tab on the bot to view all the items that go into the itemlog file?is it the value i set Config.ItemInfoQuality = []; in the char config to see more items sold/crafted/picked up, and what values show what?

**Comment by dzik87** [comment]
You can edit logging item function manually and force it to print everything. But whats the point of doing it ? Bot is printing there only items what he kept.

If you really want see all that spam in console you can edit Pickit.js and modify that function:
`pickItem: function (unit, status, keptLine)`
for all other cases.
