### ISSUE TITLE
Random pickit error "Unknown name:..."

### ISSUE THREAD

**Issue by Inked-Ice** [kolton/d2bot-with-kolbot#822]
So randomly my pickit comes up with a unknown name error message. I thought it was my mistake at first but after trying different lists including the default kolton.nip I had no luck.  

Example error message:
 "Unknown name: largecharm File: ladderuni.nip Line: 265"

Example of my pickit
[Name] == HeavyGloves && [Quality] == Unique && [Flag] != Ethereal # // [EnhancedDefense] >= 20

Any advice??

**Comment by romaingallay** [comment]
Give us the line 265 of your ladderuni.nip file

**Comment by 5noop** [comment]
What is the line 265 in ladderuni.nip ?

**Comment by Inked-Ice** [comment]
Whats on that specific line isnt important it gives that message with every line from uniq items to gold. bot wont even pick up potions anymore. Like i said at the start i had attempted to use the default and still had the same issue with every item 

07:54:06 (laddersorc) Unknown name: keyofhate File: ladderuni.nip Line: 8
07:54:06 (laddersorc) Unknown name: keyofterror File: ladderuni.nip Line: 9
07:54:06 (laddersorc) Unknown name: keyofdestruction File: ladderuni.nip Line: 10

[name] == keyofhate # # [maxquantity] == 9
[name] == keyofterror # # [maxquantity] == 9
[name] == keyofdestruction # # [maxquantity] == 9


07:54:06 (laddersorc) Unknown name: meshbelt File: ladderuni.nip Line: 41
07:54:06 (laddersorc) Unknown name: heavygloves File: ladderuni.nip Line: 45

[name] == meshbelt && [quality] == set // # [itemmagicbonus] == 15 && [defense] == 40


//UNIQUE GLOVES
[Name] == HeavyGloves && [Quality] == Unique && [Flag] != Ethereal # // [EnhancedDefense] >= 20																			//BLOOD FIST

**Comment by jaenster** [comment]
If you open a tag with a #, and no value is after it (like //) it bugs. So remove the # as last line and it should work.

**Comment by Inked-Ice** [comment]
> If you open a tag with a #, and no value is after it (like //) it bugs. So remove the # as last line and it should work.

The thing is it worked before (which is why i chose bloodfists) Its always given to me unid before, also it gives the same error for keys/pots/gems and things with out # its not specific to the item I posted its legit everything that doesn't start  with // even going with the default kolton.nip or lld.nip i get same Unknown Name

**Comment by Inked-Ice** [comment]
[IMG]http://i63.tinypic.com/308wd1k.png[/IMG]

EVERY single item that doesn't start //

**Comment by jaenster** [comment]
Try comparing it too a typical pickit line of a shako and look if you can find the difference

**Comment by 5noop** [comment]
Maybe a broken link with NTItemsAlias ? What if you try this:
`[name] == 422 && [quality] == unique // harlequin crest`

**Comment by Inked-Ice** [comment]
> Maybe a broken link with NTItemAlias ? What if you try this:
> `[name] == 422 && [quality] == unique && [flag] != ethereal # [defense] == 141 // harlequin crest`

That worked! But I still dont understand what happened or how to fix it :(

**Comment by DarkHorseDre** [comment]
Are the files case senstive? in the screenshot, its `**S**hako`

**Comment by 5noop** [comment]
@DarkHorseDre they are not

@Inked-Ice Did you modify in any way the files NTItemAlias.dbl or NTItemParser.dbl ? If you did not I suggest you re download a clean d2bs repo and simply copy/paste your config and pickit files, assuming you did not edit anything else.

**Comment by DarkHorseDre** [comment]
thanks @5noop 

and I agree with @5noop - standard functionality is not working and you say you didn't modify anything (the game recognises the literal item codes but not the alias names for them) - quicker to download a new and complete repo than to troubleshoot

**Comment by Inked-Ice** [comment]
> @DarkHorseDre they are not
> 
> @Inked-Ice Did you modify in any way the files NTItemAlias.dbl or NTItemParser.dbl ? If you did not I suggest you re download a clean d2bs repo and simply copy/paste your config and pickit files, assuming you did not edit anything else.

I went ahead and replaced the NTItemAlias.dbl file and works again! Thanks for letting me pick your brains for answers you all really helped a bunch
