### ISSUE TITLE
Too Many Rejuvs to merc

### ISSUE THREAD

**Issue by Dratos1** [kolton/d2bot-with-kolbot#829]
Hello community, quick question here:  Kol seems to be using the whole row of rejuvs for my merc when it should just use one. My guess is that because there is a slight delay when poping a rejuv, that it thinks it hasnt healed.

Any advice would be appreciated!

**Comment by DarkHorseDre** [comment]
What is your `Config.UseMercRejuv` set as in  char config?

**Comment by Dratos1** [comment]
I've been playing around with trying not to die.. and this is what i came up with on my meteororb

// Potion settings
	Config.UseHP = 90; // Drink a healing potion if life is under designated percent.
	Config.UseRejuvHP = 25;  // Drink a rejuvenation potion if life is under designated percent.
	Config.UseMP = 75; // Drink a mana potion if mana is under designated percent.
	Config.UseRejuvMP = 10; // Drink a rejuvenation potion if mana is under designated percent.
	Config.UseMercHP = 95; // Give a healing potion to your merc if his/her life is under designated percent.
	Config.UseMercRejuv = 30; // Give a rejuvenation potion to your merc if his/her life is under designated percent.
	Config.HPBuffer = 0; // Number of healing potions to keep in inventory.
	Config.MPBuffer = 0; // Number of mana potions to keep in inventory.
	Config.RejuvBuffer = 10; // Number of rejuvenation potions to keep in inventory.

**Comment by DarkHorseDre** [comment]
My second question was do you carry healing pots?

**Comment by Dratos1** [comment]
My apologies, I indeed meant column and not row!

/* Potion types for belt columns from left to right.
	 * Rejuvenation potions must always be rightmost.
	 * Supported potions - Healing ("hp"), Mana ("mp") and Rejuvenation ("rv")
	 */
	Config.BeltColumn[0] = "hp";
	Config.BeltColumn[1] = "mp";
	Config.BeltColumn[2] = "mp";
	Config.BeltColumn[3] = "rv";

	/* Minimum amount of potions. If we have less, go to vendor to purchase more.
	 * Set rejuvenation columns to 0, because they can't be bought.
	 */
	Config.MinColumn[0] = 2;
	Config.MinColumn[1] = 2;
	Config.MinColumn[2] = 2;
	Config.MinColumn[3] = 0;

**Comment by DarkHorseDre** [comment]
alright, so the bot will use rejuvs if merc life below 30. if above 30 but below 95 it will use hp. 
there is a delay in the code to handle any delay after drinking.

if this is still happening with your setup (mine is similar but my toon & merc usehp is lower to avoid chugging too many and having to pick/shop all the time) then something isnt right.  it probably is working correctly tho.

watch the bot and see what happens when it is hit - it should use hp first and only rejuv if under 30%.  if his max hp is low and he takes large damage then obv he will go below 30% and use rejuv.

**Comment by Dratos1** [comment]
Yes the problem is still persisting, however it does use hp appropriately, it just doesn't seem to recognize the rejuv delay and blasts the whole column before the rejuv even tics. 

May i see your whole potion section in config?

**Comment by DarkHorseDre** [comment]
tbh mine is similar to yours (but I dont use a buffer), config isn't the problem.
try and reduce your merc rej to 10-15% (and reduce your chicken to below this).

`  // Potion settings
    Config.UseHP = 80; // Drink a healing potion if life is under designated percent.
    Config.UseRejuvHP = 40;  // Drink a rejuvenation potion if life is under designated percent.
 
    Config.UseMP = 35; // Drink a mana potion if mana is under designated percent.
    Config.UseRejuvMP = 0; // Drink a rejuvenation potion if mana is under designated percent.
 
    Config.UseMercHP = 70; // Give a healing potion to your merc if his/her life is under designated percent.
    Config.UseMercRejuv = 10; // Give a rejuvenation potion to your merc if his/her life is under designated percent.
 
    Config.HPBuffer = 0; // Number of healing potions to keep in inventory.
    Config.MPBuffer = 0; // Number of mana potions to keep in inventory.
    Config.RejuvBuffer = 0; // Number of rejuvenation potions to keep in inventory.
 
    // Chicken settings
    Config.LifeChicken = 12; // Exit game if life is less or equal to designated percent.
    Config.ManaChicken = 0; // Exit game if mana is less or equal to designated percent.
    Config.MercChicken = 0; // Exit game if merc's life is less or equal to designated percent.
    Config.TownHP = 0; // Go to town if life is under designated percent.
    Config.TownMP = 0; // Go to town if mana is under designated percent.`
 
if that dont work, its about the maths I reckon.

how much max life does your merc have?
are you using small or large rejuv?

does your bot take more damage as it drinks the rejuv?  

is it a boss dealing damage?

ive seen this kinda thing with ubers etc where the damage dealt is more than the merc/toon can handle and so drinks all pots.. 

does this happen even with small damage?
does merc have any damage reduction?

**Comment by Dratos1** [comment]
-Max life: 1887
-Small and large rejuv
-It does not generally take more damage as it drinks a rejuv
-does it happen only with small damage? ANSWR: it happens indefinitely regardless of the damage contingest upon that it reaches that 30% life remaining mark.

**Comment by Dratos1** [comment]
So i found this:

@@ -197,11 +197,16 @@ function main() {

			break;
		case 2:
		case 4:
			if (timerLastDrink[type] && (tNow - timerLastDrink[type] < 300)) { // small delay for juvs just to prevent using more at once
				return false;
			}

			break;
		case 4:
			if (timerLastDrink[type] && (tNow - timerLastDrink[type] < 2000)) { // larger delay for juvs just to prevent using more at once, considering merc update rate
				return false;
			}

			break;
		default:
			if (timerLastDrink[type] && (tNow - timerLastDrink[type] < 8000)) {



Just copy and paste it in the potion area of config?

**Comment by Dratos1** [comment]
Can someone help me to figure out where to add this code?

**Comment by DarkHorseDre** [comment]
Good search - that's the delay I was talking about :) seems they added more time 11 hours ago
The filename listed is `d2bs/kolbot/tools/ToolsThread.js`

just change delay from 300 as they show in red vs green

**Comment by Dratos1** [comment]
DarkHorseDre, I want to thank you for helping me. You helped make my day!

Happy hunting <(^_^)v

**Comment by gut12** [comment]
I don't know where to put my question so I try here, my Java drink life potions all the time, even she have full life, where is the problem?
