### ISSUE TITLE
Dropping items instead of selling them?

### ISSUE THREAD

**Issue by ma9u5** [kolton/d2bot-with-kolbot#838]
Tried to find these lines where it decides to drop the items instead of vendoring them but was unable to. There was a line in the Town.js that I tried to change/delete around 1920 or so but didn't really do anything, unfortunately. Anyone else have any thoughts on this matter?

**Comment by aim2kill** [comment]
Check Misc.js

**Comment by DarkHorseDre** [comment]
I assume you want to sell when your gold is low (and not when you have 2.5mill lol)?

you can use a config option which is not present in the config templates (but is in config.js, town.js, pickit.js) by default for some reason:
`Config.LowGold = 400000` //bot will sell found items when gold is below this number

bot will also pick gold if it is in pickit range and total gold is below `Config.LowGold`

**Comment by ma9u5** [comment]
Trying to sell period at this point, not wanting to sell anything. Have tried changing the one Config.LowGold variable that is in the town.js which did nothing, changed the LowGold variable but then it literally picks up every and still doesn't sell to the vendors. So not really sure...

**Comment by DarkHorseDre** [comment]
no, you add that like to the character config only.

bot does sell if it has stuff when it gets to the shop (with fieldid and cain disabled of course) but with the above setting it will hold on to stuff and sell in shop

**Comment by DarkHorseDre** [comment]
@5noop sounds like he changed the wrong files as dont need to change town.js to get lowgold to work

**Comment by 5noop** [comment]
It seems it has nothing to do with Config.LowGold, but rather there is an issue somewhere (in Town.js ?) that makes the bot dropping items instead of selling them. Some of the code is indeed around line 19xx so if the issue is there, just grabbing the original file instead of trying to correct manually might fix the bug.

**Comment by DarkHorseDre** [comment]
ah so its not selling anything at all? it should at some point - especially when inventory is full and it returns to town mid run (for pots, repair etc). I assume he is saying even when it has items and is at the shop it does sell, but drops afterward?

better to svn update/replace the files as you say snoop

**Comment by mf022** [comment]
>Tried to find these lines where it decides to drop the items instead of vendoring them but was unable to. 

All you need is to enable ID in field and to put a tome of ID in inventory. 
```
	Config.FieldID = false; // Identify items in the field instead of going to town.
```
In this case is good to add in the pickit:
```
[name] == scrollofidentify # # [maxquantity] == 20
```

otherwise the default using of ID on Cain will drop unkept items
```
	Config.CainID.Enable = true; // Identify items at Cain
```
you should also consider to customize the next 2 rows
```
	Config.CainID.MinGold = 2500000; // Minimum gold (stash + character) to have in order to use Cain.
	Config.CainID.MinUnids = 3; // Minimum number of unid items in order to use Cain.
```
By example these settings will always ID on Cain:
```
Config.CainID.MinGold = 0; 
Config.CainID.MinUnids = 1;
```

**Comment by ma9u5** [comment]
Enabling FieldID will just drop the items in the field, but I did however just redownload the bot and it did begin to sell the items but only when completely full and needing to make room to pick something else up. This is another problem because the character just stays completely full and constantly goes back to town to sell 1 item to pick up another?

**Comment by DarkHorseDre** [comment]
FYI, I worked around it

This section of town.js (starts line 1937 for me) says to sell if at npc or in shop and valid item, else drop (dropping saves time walking to shop):

if (getUIFlag(0xC) || (Config.PacketShopping && getInteractedNPC() && getInteractedNPC().itemcount > 0)) { // Might as well sell the item if already in shop
						print("clearInventory sell " + items[i].name);
						Misc.itemLogger("Sold", items[i]);
						items[i].sell();
					} else {
						dhdMisc.itemLogger("Dropped", items[i], "clearInventory");
						dhditems[i].drop();
					}

cheap way is to comment out the else commands so no drop occurs, and replace with itemlogger sell info if needed:
} else {
						//dhdMisc.itemLogger("Dropped", items[i], "clearInventory");
						//dhditems[i].drop();
                                                print("clearInventory sell " + items[i].name);
						Misc.itemLogger("Sold", items[i]);
					}


better way to do it would be to tell the bot to goto shop npc and re-run the same check and it will sell as normal.

**Comment by Xoddan** [comment]
Any1 figurer this out? I tried everything mentioned above without any luck. Bot still throws items to the ground and runs out of gold

**Comment by DarkHorseDre** [comment]
yeah comment out the code from town.js as above, disable cainid, fieldid.

I recently shared my commented out seciton and addded commments for someone - you cant get lost following this:
```js
} else {
                        //Misc.itemLogger("Dropped", items[i], "clearInventory");
                        //items[i].drop();
                        print("*** Not dropping: " + items[i].name + " ***"); //dhd added - trying to keep items in inv for next shop stop, then sell.
                        //Misc.itemLogger("Sold", items[i]);
}
```
The sole items will be sold at next town visit and if you have itemlogging enabled, it will be logged as usual.

**Comment by Xoddan** [comment]
So I can just copy ur code above to replace
} else {
dhdMisc.itemLogger("Dropped", items[i], "clearInventory");
dhditems[i].drop();
}
And it should work? Ofc disable Cain and fieldid

**Comment by Xoddan** [comment]
Found out i had wrong config for the inventory.. works fine now :)
Ty for the help

**Comment by danmm55** [comment]
does anyone know just how to stop bot from selling items for gold? ive read every forum post about it and nobody knows or they suck at explaining it. sum ppl say to change config low gold to 0 but that isnt enough information to help anyone. its dumb that the bots sell items for gold when they cant hold anymore gold anyways. really dumb. If anyone knows how and isnt too lazy to explain it correctly please let us know

**Comment by danmm55** [comment]
I keep hearing about this config low gold but not one person can just say where its located...? is there anyone out there that wants to tell us how to stop bots form picking up gold for no reason.,.?

**Comment by danmm55** [comment]
Why cant anyone just say where the config low gold folder is?

**Comment by danmm55** [comment]
anyone at all know how to stop bots from picking up gold please leave a simple comment explaining how. for example if the config low gold folder is in kolbot>libs>config>(charactername that you want to change) just say that. if we knew how to do it we wouldnt be here. telling us to change the config low gold to 0 or w.e. or telling us it in x folder that doesnt even exist doesn't help anyone. try to pretend you dont already know how to do it and give us a simple way to make bots not get gold. it shouldnt be this hard. I cant believe out of all these ppl nobody knows how to do this

**Comment by danmm55** [comment]
It should take one sentence to explain how. is there even a way to do it? I sell ppl taking about changing cain ID and stuff. We just want to stop bots from selling junk for gold. idc if he uses cain or w.e. nobody cares about that.

**Comment by danmm55** [comment]
This post is almost 4 years old and still nobody can figure out such a simple problem... no answers on google or any other sites. tried creating my own forum posts but nobody can just say how....
