### ISSUE TITLE
Baal Bot is stalling after Dolls are found.

### ISSUE THREAD

**Issue by shiny001** [kolton/d2bot-with-kolbot#845]
My lead baal bot. Says: "Dolls found! NG.". and It just goes to town and stalls for 35 seconds, and once it leaves the game it doesn't create new one. 

It works fine if there are no dolls

Please help

**Comment by 5noop** [comment]
Set `Config.Baal.DollQuit = false;` in your character file.

**Comment by shiny001** [comment]
I got it ty. it is "Config.MinGameTime = 60; // Min game time in seconds.". that is why bot stalls
