### ISSUE TITLE
MF helper issue

### ISSUE THREAD

**Issue by munchysz** [kolton/d2bot-with-kolbot#849]
Error in MFHelper (mfhelper.js #153) MFHelper: Leader not partied  

I keep getting this error have no idea why follower wont party help plz? :) Basically MY follower doesnt accept the party invite of my leader IF i manually accept it though everything works. How to fix?

**Comment by sunace** [comment]
Config.Leader = ""; // Leader's ingame character name. Leave blank to try auto-detection (works in AutoBaal, Wakka, MFHelper)
	Config.QuitList = [""]; // List of character names to quit with. Example: Config.QuitList = ["MySorc", "MyDin"];
	Config.QuitListMode = 0; // 0 = use character names; 1 = use profile names (all profiles must run on the same computer).

make sure u set that up and also

	Config.PublicMode = 2; // 1 = invite and accept, 2 = accept only, 3 = invite only, 0 = disable

**Comment by sunace** [comment]
also the first config setting posted is case sensitive

**Comment by munchysz** [comment]
What do i put on quit list and quit list mode? also on public mode what number do i need? and is this for leader config or on the folower config? sry im kind  of new to this

**Comment by munchysz** [comment]
Got it working tyvm
