### ISSUE TITLE
leader not defined kolbot

### ISSUE THREAD

**Issue by Nicotine1986** [kolton/d2bot-with-kolbot#85]
![untitled](https://cloud.githubusercontent.com/assets/8402783/3866455/1e8071fe-1fd2-11e4-912e-dd751dcf3078.jpg)
can someone help me with this i cant figure out what i am dong wrong

**Comment by WiZzMaN47** [comment]
yup... u r correct . this will allow multipule accounts to give commands and control bot if your not present.. like chanter/bo/bc/hs/follow/rusher scrpts
