### ISSUE TITLE
fireball / meteor not casting

### ISSUE THREAD

**Issue by PenguinCollector** [kolton/d2bot-with-kolbot#852]
Hi guys, 
I am trying to get a 105fcr fireball/meteor sorc to run.
Glacial spike / blizzard works flawlessly, which is why I don't understand the problem.
The sorc casts meteor, but no fireballs in between, just takes a break.
With these settings:
	Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 56; // Primary skill to bosses.
	Config.AttackSkill[2] = 47; // Primary untimed skill to bosses.
	Config.AttackSkill[3] = 56; // Primary skill to others.
	Config.AttackSkill[4] = 47; // Primary untimed skill to others. 
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

I tried changing to fireball only, and she casts fireballs, but with a very long delay. seems like meteor/blizzard frequency...
	Config.AttackSkill[0] = -1; // Preattack skill.
	Config.AttackSkill[1] = 47; // Primary skill to bosses.
	Config.AttackSkill[2] = -1; // Primary untimed skill to bosses.
	Config.AttackSkill[3] = 47; // Primary skill to others.
	Config.AttackSkill[4] = -1; // Primary untimed skill to others. 
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

Any ideas?

**Comment by ma9u5** [comment]
Config.AttackSkill[0] = 56; // Preattack skill.
	Config.AttackSkill[1] = 47; // Primary skill to bosses.
	Config.AttackSkill[2] = 47; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.

This is what I run, seems fine.

**Comment by PenguinCollector** [comment]
when I do that, I get a "bad attack config" warning and the bot doesn't attack at all.
when I do that and add 47 to skill [3] and [4], I get back to the extremely slow casting.
Could you somehow post your entire script?
Or anyone else with ideas?
It seems to me that FB/Meteor should behave EXACTLY as Glacial/Blizzard :(

**Comment by ma9u5** [comment]
Config.AttackSkill[0] = 56; // Preattack skill.
	Config.AttackSkill[1] = 56; // Primary skill to bosses.
	Config.AttackSkill[2] = 47; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 56; // Primary skill to others.
	Config.AttackSkill[4] = 47; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = -1; // Secondary untimed skill if monster is immune to primary untimed.

**Comment by 5noop** [comment]
There is nothing wrong with the first config, it should work so the problem is most likely elsewhere. Which version do you use ? Did you modify Attack.js ?

**Comment by PenguinCollector** [comment]
thanks for the help guys. I figured it out.
I had a memory staff on switch for which I didn't have enough dex. Not sure why this made a difference, but it's working now!
