### ISSUE TITLE
issue with leecher stalling

### ISSUE THREAD

**Issue by cryptic7s** [kolton/d2bot-with-kolbot#853]
Cant seem to figure out why the bot stalls in town after he logs in through channel an finds game just fine.
heres a pic of the issue after waiting for stall countdown to expire.
![screenshot 1](https://user-images.githubusercontent.com/46088964/50385200-14f40e80-06ef-11e9-88be-0446b839d70c.png)

**Comment by cryptic7s** [comment]
running channel to leach off another game . he joins through lobby and as soon as boots hit the ground he stalls? idk what im doing wrong but ive tried dozens of variations to get it going . including a reinstall

**Comment by DarkHorseDre** [comment]
does it not give any indication for reason for stall anywhere? log file?
if leader not partied, it shows a message on console then stalls.  if cannot find leader, same thing.

**Comment by 5noop** [comment]
Alright so you are running channel as entry script, but then you have to define in the character config file which script the bot is gonna run once it's in game.
Check this https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config

**Comment by cryptic7s** [comment]
> 
> 
> does it not give any indication for reason for stall anywhere? log file?
> if leader not partied, it shows a message on console then stalls. if cannot find leader, same thing.

i think this is a possibility. i jsut put the account or character name and not sure where pretty new to kol. always ran etal .

**Comment by cryptic7s** [comment]
> 
> 
> Alright so you are running channel as entry script, but then you have to define in the character config file which script the bot is gonna run once it's in game.
> Check this https://github.com/kolton/d2bot-with-kolbot/wiki/Kolbot-Character-config

also i think not only to previous quote, this is most likely right . i really appreciate the help everyone. ill give it a shot see i can get her running. ill let you guys  know the outcome

**Comment by DarkHorseDre** [comment]
yeah Snoop 100% - I missed that: the bot needs to something (Even if just a baal/mf helper script) once it joins. otherwise it will sit there then exit
