### ISSUE TITLE
BaalAsistant.GetShrine

### ISSUE THREAD

**Issue by Rakkah** [kolton/d2bot-with-kolbot#855]
Hello there,

I was wondering if I could use the option:
Config.BaalAssistant.GetShrine = false; // Set to true to get a experience shrine at the start of the run.

on my sorceress, leech-fighting Baalruns with my Hammerdin. I've just set it to false and I've got an error:
Error in BaalAssistant (misc.js #1111) getPresetUnits failed, couldn't access the level! (Area: 109)

Misc.js says: (From line 1106 - 1111)
	// Check all shrines in area and get the first one of specified type
	getShrinesInArea: function (area, type, use) {
		var i, coords, shrine,
			shrineLocs = [],
			shrineIds = [2, 81, 83],
			unit = getPresetUnits(area);

I was trying to figure it out by changing a few numbers, sadly it didn't work out.
Could someone explain me what the reason is why it isn't working?

Merry xmas!

**Comment by DarkHorseDre** [comment]
Ive not used this, but the following two entries are supposed to grab exp shrines:

`Config.BaalAssistant.GetShrine = false; // Set to true to get a experience shrine at the start of the run.`
`Config.BaalAssistant.GetShrineWaitForHotTP = false; // Set to true to get a experience shrine after leader shouts the hot tp message as defined in Config.BaalAssistant.HotTPMessage`

Are you saying this doesn't grab xp shrine (if available) for you?

Do you have xp shrine [15] specified in `Config.ScanShrines`?

Merry chrimble :)

**Comment by Rakkah** [comment]
Thats what I have in my character config file:

	Scripts.BaalAssistant = true; // Used to leech or help in baal runs.
		Config.BaalAssistant.Wait = 680; // Seconds to wait for a runner to be in the throne / portal wait / safe TP wait / hot TP wait...
		Config.BaalAssistant.KillNihlathak = false; // Kill Nihlathak before going to Throne
		Config.BaalAssistant.FastChaos = false; // Kill Diablo before going to Throne
		Config.BaalAssistant.Helper = true; // Set to true to help attack, set false to to leech.
		Config.BaalAssistant.GetShrine = true; // Set to true to get a experience shrine at the start of the run.
		Config.BaalAssistant.GetShrineWaitForHotTP = true; // Set to true to get a experience shrine after leader shouts the hot tp message as defined in Config.BaalAssistant.HotTPMessage
		Config.BaalAssistant.SkipTP = false; // Set to true to enable the helper to skip the TP and teleport down to the throne room.
		Config.BaalAssistant.WaitForSafeTP = false; // Set to true to wait for a safe TP message (defined in SafeTPMessage)
		Config.BaalAssistant.DollQuit = false; // Quit on dolls. (Hardcore players?)
		Config.BaalAssistant.SoulQuit = false; // Quit on Souls. (Hardcore players?)
		Config.BaalAssistant.KillBaal = true; // Set to true to kill baal, if you set to false you MUST configure Config.QuitList or Config.BaalAssistant.NextGameMessage or the bot will wait indefinitely. 
		Config.BaalAssistant.HotTPMessage = ["Hot"]; // Configure safe TP messages.
		Config.BaalAssistant.SafeTPMessage = ["Safe", "Clear"]; // Configure safe TP messages.
		Config.BaalAssistant.BaalMessage = ["Baal"]; // Configure baal messages, this is a precautionary measure.
		Config.BaalAssistant.NextGameMessage = ["Next Game", "Next", "New Game"];	// Next Game message, this is a precautionary quit command, Reccomended setting up: Config.QuitList

	Config.ScanShrines = [15];

After leader shouts "Hot TP!" message, I'm getting this error:
Error in BaalAssistant (misc.js #1111) getPresetUnits failed, couldn't access the level! (Area: 109)

**Comment by Rakkah** [comment]
Ofcourse it can. I'm not sure if I know what you mean, but normally I do baalruns without that expshrine-option.

I'll put it again like this:
1 Everyone gets bo
2 Paladin starts Baal.script
3 Sorceress (The one who is supposed to get EXP-Shrine) goes to Act1 town waypoint and waits.
4 Paladin teleports to throne room and gives TP.
5 Immediately after "Hot TP!" message, I'm receiving an error:
`Error in BaalAssistant (misc.js #1111) getPresetUnits failed, couldn't access the level! (Area: 109)`
6 Paladin ofcourse keeps doing Baalrun
7 Sorceress is going further with ChestMania 

The only thing that comes on my mind its because I'm starting my games with Baalruns and then any other locations (yeah, pretty weird, but that's not without a reason) and for some reason my Sorceress can't find any Exp shrines. I would like to test it with baalruns at the end, but yeah, its christmas and soon I'm leaving my house, haha.

And ofcourse, script works perfectly without Exp-Shrine function. As soon as I turn it on, I'm getting that error.

**Comment by 5noop** [comment]
The sorc has the wp to get ES, like stony fields, cold plain etc ?

**Comment by justinpees** [comment]
Has your Sorc done ancients lol?

**Comment by Rakkah** [comment]
I'll refresh this thread.
Does it work for anyone here? (Exp shrine function for baalruns)
I've tested on a few characters, different games, different leaders/leechers, still the same thing.

**Comment by DarkHorseDre** [comment]
https://github.com/kolton/d2bot-with-kolbot/issues/1051

**Comment by Rakkah** [comment]
After updating to newest version, it works perfectly. I don't even have to note Exp shrine ID in Config.ScanShrines. Thank you!
