### ISSUE TITLE
BattleOrders script

### ISSUE THREAD

**Issue by munchysz** [kolton/d2bot-with-kolbot#859]
This might be a dumb question but I been trying to use the battleorders script Without a barb though I have a hdin and sorc i want my hdin to bo my sorc WIth CTA but it doesnt work they just sit still at wp. Does this only work with a  barb and if so is there a way to change it to work with CTA also? thank you

**Comment by munchysz** [comment]
Ok I will try that but basically they both wait at cata 2 hdin doesnt do anythign not even holy shield ill let you know what happens when i try.

**Comment by 5noop** [comment]
What are the BattleOrders parameters in your hdin config file ? (like Config.BattleOrders.Mode etc)

**Comment by munchysz** [comment]
my Paladins file is 
Scripts.BattleOrders = true;
		Config.BattleOrders.Mode. = 0; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = true; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = [1]; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.

My Sorc is
Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 1; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = []; //

**Comment by 5noop** [comment]
You have to put your sorceress name in the Getters array instead of 1, i.e. if your sorc is called munchysz then your paladin config will have the following line:
`Config.BattleOrders.Getters = ["munchysz"];`

**Comment by munchysz** [comment]
Ohhhh omfg thanks man haha

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by munchysz** [comment]
So i tried putting my sorcs name but that doesnt work either it says error *name* undefined

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 5noop** [comment]
Don't forget to write the name between quotes, c.f my previous post.

**Comment by DarkHorseDre** [comment]
cant believe I missed the [1] #doh

**Comment by munchysz** [comment]
Ty i got it working lol im so bad at this stuff

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
