### ISSUE TITLE
Open chests during clear area routine

### ISSUE THREAD

**Issue by EnjoyBotting** [kolton/d2bot-with-kolbot#864]
Hi everyone,

I'm wondering if there is a way for super chests (f.e. in A1 Pit and A1 Crypt) to be opened directly during the clear area routines?
I know there is the ChestMania script which I could activate, but I think it's not time efficient to teleport again the same locations which have just been cleared before just to open the chests.
Can't I set it up that chests will be opened right when clearing the area?

Thanks and wishing you all a great Xmas time.

**Comment by aim2kill** [comment]
Yes in ur char config look under general config
Config.OpenChests =

**Comment by EnjoyBotting** [comment]
call me blind... I have not seen it!
thank you very much!

**Comment by aim2kill** [comment]
😃👍 np mate just close the issue
