### ISSUE TITLE
Chestmania issue: Kolbot will keep running the same chests

### ISSUE THREAD

**Issue by gvc08** [kolton/d2bot-with-kolbot#875]
During chestmania it gets stuck in an endless loop of checking the same chests, before it eventually gets dropped or chickenlifes out of the game.. any idea what is causing this issue?

**Comment by DarkHorseDre** [comment]
paste a link to a pastebin of your config...

**Comment by justinpees** [comment]
can you provide more detail? are you trying to check chests only in one act or multiple acts?

**Comment by gvc08** [comment]
Yes, only have it set for A3.. I turned off chestmania because of this glitch.. I didn’t change anything in the code, except put the // in front of every other act

**Comment by gvc08** [comment]
I’ll do the paste bin when I get back home, and see if it’s diagnosable

**Comment by justinpees** [comment]
When you commented out each act with // did you leave ChestMania set to true? This might make him check every single chest.
