### ISSUE TITLE
Autobuild limedrop-utf8 question

### ISSUE THREAD

**Issue by aim2kill** [kolton/d2bot-with-kolbot#879]
Config.AutoSkill.Build  = 
// if satisfy boolean was defined for blizzard as [59, 1, true] and character was under level 24, AutoSkill will stop at this point
];

autoskill will stop completely or save points until get to lvl 24 and is able to use a point on blizzard and move on ?

**Comment by justinpees** [comment]
should save the point OR spend the point on something else specified already. maybe energy shield or telekinesis depending how smart the default autobuild scripts are. I've never used autobuild so i cant be certain. but dont worry im sure they are not dumb even to stop putting skills completely. I hope....

**Comment by imbalanced** [comment]
Autobuild will run AutoSkill at every level up so when your character reaches 24, it will satisfy blizzard requirement and move on to next array element.

**Comment by aim2kill** [comment]
Thank you
