### ISSUE TITLE
Trying to run 4+ bots?

### ISSUE THREAD

**Issue by m1cckalodeon** [kolton/d2bot-with-kolbot#88]
I am having an issue with running more than 4+ bots.

My issue lies with the manager itself.

I have followed and read many guides that suggest using game1.exe after the 4th bot or should I just keep it game.exe?

Also, if possible, could someone enlighten me on a simple process for doing multiple cdkeys? I will also look on the repository for info as well!

**Comment by WiZzMaN47** [comment]
u need cdkeys to install d2. just install diablo2 in a folder and rename it to diablo2 cd1
then install another copy with another cdkey and rename it diablo2 cd2. and so on and so on.
now u have a main folder that has as many d2 folders as u made and now u have to use d2bot.exe
and change the path of the profile to use the differnent files

**Comment by dzik87** [comment]
No no no. That is total waste of space. You do not need to install diablo multiple times. Open wiki page here and check new d2bot. There is exlained how add cdkeys to manager.
