### ISSUE TITLE
Clearing path in Chaos Sanct

### ISSUE THREAD

**Issue by chojo31** [kolton/d2bot-with-kolbot#882]
Hi,
I try to clear Chaos Sanctuary runs without teleport. The problem is with clearing trash mobs.

I added the following line to the Diablo.js file so I can run through River of Flames while clearing it : 
`Pather.moveToExit(108, true, true);`
It works really well.

Once my hero reach Chaos Sanctuary, it "rush" through it without killing anything until seals.
My cleartype is set to 0, so I think its maybe a pather config to change? : 
`Config.ClearType = 0; // Monster spectype to kill in level clear scripts (ie. Mausoleum). 0xF = skip normal, 0x7 = champions/bosses, 0 = all
`

Can someone help me with this? Since I do not have access to teleport, I would like to clear thrash and unique monster in the Chaos Sanctuary between me and all 3 seals.

Config: https://pastebin.com/zksVREC0
Diablo.js: https://pastebin.com/wBjaKfGi

Thank you

**Comment by cameronpfs** [comment]
Make sure you dont have fast diablo turned on.

**Comment by chojo31** [comment]
It is not, from my config file :  
`Scripts.FastDiablo = false;`

**Comment by 5noop** [comment]
Set Config.Diablo.Entrance to true.

**Comment by chojo31** [comment]
> 
> 
> Set Config.Diablo.Entrance to true.

Spot on. Thank you sir.
Closed
