### ISSUE TITLE
Picket issue

### ISSUE THREAD

**Issue by Jivarias** [kolton/d2bot-with-kolbot#883]
the .nip file isnt recognizing ShapeshiftingSkillTab as a valid input for item property.

I've tried several different variations as well.

Does anyone have a link to the list of item properties?

**Comment by 5noop** [comment]
Check NTItemsAlias.dbl in your libs folder.

**Comment by justinpees** [comment]
[shapeshiftingskilltab] == 2

if that doesnt work then you probably have an error in the previous line of code somewhere.

**Comment by Jivarias** [comment]
thanks justin, seems the borrowed pickit forgot a #
