### ISSUE TITLE
Desync in town

### ISSUE THREAD

**Issue by GabrielDias1992** [kolton/d2bot-with-kolbot#884]
I am suffering with to much desync in town, during almost every run.

I fix it manually walking away from waypoint, then the game just "teleport" me to my sync'd location.

Can i configure the bot to just far walk away from waypoint when "useWaypoint: Failed to use waypoint" ?

**Comment by 5noop** [comment]
This is fixed in the limedrop-utf8 branch.

**Comment by GabrielDias1992** [comment]
I will test the limedrop branch, thank you.
