### ISSUE TITLE
Create dupe?

### ISSUE THREAD

**Issue by master2g** [kolton/d2bot-with-kolbot#891]
I saw that "create dupe" is an option when right clicking on items in the D2Bot window that your bots have saved.  I'm not finding any information on this function any where.  Can someone enlighten me as to what this actually does and how to use it?

**Comment by justinpees** [comment]
this is old and doesnt work unless custom tweaked. nobody gonna give you their scripts unfortunately

**Comment by destinationsound** [comment]
i don't know the setup, but a hint in the correct direction is when I stay in a game too long i eventually get a "connection interrupted" message and the things i traded right before this happens are back in my inventory.
