### ISSUE TITLE
Muling Problem

### ISSUE THREAD

**Issue by GabrielDias1992** [kolton/d2bot-with-kolbot#892]
My KolBot LimeDrop branch does not mule correctly.

The mule enters in the game, pickup a few things, put these stuff on the stash and do not close the inventory/statsh screen to pickup the missing stuff.

I have to manually close, then the mule pickup the rest and remain at the same problem,

Can someone help me ?

**Comment by GabrielDias1992** [comment]
Let me know if any information is required.

**Comment by noah-** [comment]
is there any error in the console?

**Comment by justinpees** [comment]
> Let me know if any information is required.

pm'd :)

**Comment by GabrielDias1992** [comment]
It worked now.

I will try o figure out and get more informations, then i will reopen this issue.
