### ISSUE TITLE
shrine/scanner

### ISSUE THREAD

**Issue by cryptic7s** [kolton/d2bot-with-kolbot#901]
cant seem to figure out what im doing wrong when putting the number in sequence from most to least ...?
anybody happen to have this already filled out they could copy to here so i can see what im doing wrong. it would be greatly appreciated.

**Comment by 5noop** [comment]
You mean something like that ? `Config.ScanShrines = [1,2,3];`

**Comment by cryptic7s** [comment]
yes ,but in descending order . when i try he just goes right past shrines instead of getting closest shrine.

**Comment by cryptic7s** [comment]
5noop do you happen to have yours filled out .? im just looking at anothers to see if i have it set up correctly to see if i need to change something

**Comment by 5noop** [comment]
Post your config and which shrine you want.

**Comment by cryptic7s** [comment]
//Shrine Scanner - scan for shrines while moving.
	// Put the shrine types in order of priority (from highest to lowest). For a list of types, see sdk/shrines.txt
	Config.ScanShrines = [15,3,2,1];

this is what i have it set too . is this correct?

**Comment by 5noop** [comment]
It's correct, which shrine he doesn't take ?

**Comment by cryptic7s** [comment]
when im usually going past xp shrines just rolls right by .

**Comment by cryptic7s** [comment]
okay id like to say thanks for the help but i figured it out i really appreciate the help though
