### ISSUE TITLE
error useWaypoint

### ISSUE THREAD

**Issue by tuito1** [kolton/d2bot-with-kolbot#912]
got this error pretty often: https://imgur.com/a/24B6LzW

what happens is that the bot cant open the waypoint interface.

any clues what could be wrong with my bot??

**Comment by 5noop** [comment]
It's a desynch issue that is fixed in the last update.

**Comment by tuito1** [comment]
> It's a desynch issue that is fixed in the last update.

hey thanks for answer, but do you know how to update my bot without losing my profiles and configs?
