### ISSUE TITLE
Excessive crashing

### ISSUE THREAD

**Issue by gvc08** [kolton/d2bot-with-kolbot#917]
My bot seems to crash in roughly 40% of her runs..  it always follows with something like “pathing not found, pit lvl 2” in example, or can’t complete move, ancient tunnels .. it crashed in about 15% of the runs pre update.. plus, my sorc died for the first time in roughly 500 runs today... not sure if it’s connected

**Comment by gvc08** [comment]
And it will follow with, windows has unexpectedly crashed, restarting... I’m just worried too many are going to happen in succession and get me an extended realm down

**Comment by noah-** [comment]
Redownload all files and don't reuse old configs.
