### ISSUE TITLE
D2 kolbot

### ISSUE THREAD

**Issue by BoiValeX** [kolton/d2bot-with-kolbot#921]
Having problems with getting blizzard to cast ive looked at a few youtube videos and did what they did but my sorc wont cast any spell but teleport its probably something i over looked but new to botting so trying to get the hang of it

**Comment by pingpong9909** [comment]
you have to input the attack # in the config for your char.

**Comment by semirotta** [comment]
Here is an example from my Orb + Fireball combo in config.
	Config.AttackSkill[0] = 40; // Preattack skill.
	Config.AttackSkill[1] = 64; // Primary skill to bosses.
	Config.AttackSkill[2] = 64; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is untimed skill.
	Config.AttackSkill[3] = 64; // Primary skill to others.
	Config.AttackSkill[4] = 64; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is untimed skill.
	Config.AttackSkill[5] = 42; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[6] = 47; // Secondary untimed skill if monster is immune to primary untimed.

	// Low mana skills - these will be used if main skills can't be cast.
	Config.LowManaSkill[0] = 0; // Timed low mana skill.
	Config.LowManaSkill[1] = 0; // Untimed low mana skill.

**Comment by BoiValeX** [comment]
So i set it up like you said but only my merc attacks idk whats going on

**Comment by BoiValeX** [comment]
Config.AttackSkill[40] = -1; // Preattack skill.
	Config.AttackSkill[64] = -1; // Primary skill to bosses.
	Config.AttackSkill[64] = -1; // Primary untimed skill to bosses. Keep at -1 if Config.AttackSkill[1] is 
        untimed skill.
	Config.AttackSkill[64] = -1; // Primary skill to others.
	Config.AttackSkill[64] = -1; // Primary untimed skill to others. Keep at -1 if Config.AttackSkill[3] is 
        untimed skill.
	Config.AttackSkill[42] = -1; // Secondary skill if monster is immune to primary.
	Config.AttackSkill[56] = -1; // Secondary untimed skill if monster is immune to primary untimed. edit: made my sorc a orb-fireball still having problems with merc being the only one to attack

**Comment by semirotta** [comment]
-1 means no attack.
