### ISSUE TITLE
help with bo barb

### ISSUE THREAD

**Issue by MaisterV** [kolton/d2bot-with-kolbot#928]
hello. atm my barb  dont bo in cata. he joins game party up go cata 2 but just dont bo.
tnx forr help

Leader pala
// Battle orders script - Use this for 2+ characters (for example BO barb + sorc)
	Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 1; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = []; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.

barb 
	// Battle orders script - Use this for 2+ characters (for example BO barb + sorc)
	Scripts.BattleOrders = true;
		Config.BattleOrders.Mode = 0; // 0 = give BO, 1 = get BO
		Config.BattleOrders.Wait = false; // Idle until the player that received BO leaves.
		Config.BattleOrders.Getters = [0]; // List of players to wait for before casting Battle Orders (mode 0). All players must be in the same area as the BOer.

**Comment by 5noop** [comment]
You are supposed to put the name of your pala in the barb's `Config.BattleOrders.Getters` instead of 0, something like that `Config.BattleOrders.Getters = ["palaName"];` (don't forget the quote).

**Comment by Hooliganmb** [comment]
aaaa damit i rly hope that whernt the quoets all the time.as trayed name but  throwed error. gona try assap

**Comment by Hooliganmb** [comment]
hahah you are my hero lol. i feel so dum now hehe

**Comment by 5noop** [comment]
No problem, you can actually close the issue instead of editing the title.

**Comment by Hooliganmb** [comment]
5noop, 1 more thing, can exampel ["palaName"] and +1 more class? tryed adding but dosent work

**Comment by Hooliganmb** [comment]
not shure how to do it ["palaName", "druidName"] or ["palaName"], ["druidName"]

**Comment by 5noop** [comment]
1st one is correct, but you can always try both to see which one is working ;)
