### ISSUE TITLE
Crashes when connecting to Battle.net - no files changed

### ISSUE THREAD

**Issue by nostyler** [kolton/d2bot-with-kolbot#932]
Ran Kolbot successfully over the last few days. Grabbed a new copy two days ago, worked like a charm.

This morning when I started it again, it does not pass the 'checking versions' step when logging in to Battle.net, with the following messages:

```
13:57:58 (Online) Window has unexpectedly exited... starting profile
13:58:02 (Online) Crash Info: Script: none Area: out of game
```

1. I have not made any changes to (configuration) files since early this week.
2. I have switched to a Single Player profile, and this continues to work like a charm.

Any ideas?

**Comment by chill420** [comment]
im having the same problem just now

**Comment by nostyler** [comment]
Additional information: Between 'the crash' and the quiting Diablo2, a file is created "bnupdate.log" with the following content:  

```
Blizzard BNUpdate v2.72 compiled on Oct 16 2003
Log created at 12:37 pm on 01/05/2019

Registry error loading key 'Patch\SrcData'
The system cannot find the file specified.


RESULT: Patch failed
```

**Comment by nostyler** [comment]
Found how to resolve this. Remove the -ns option from the parameters.

Again, did not change anything myself to make this happen.

**Comment by aagudoarias** [comment]
> Found how to resolve this. Remove the -ns option from the parameters.
> 
> Again, did not change anything myself to make this happen.

NICEEEEEEEEEE
