### ISSUE TITLE
ethereal pickit question

### ISSUE THREAD

**Issue by olsoner1** [kolton/d2bot-with-kolbot#937]
Can someone give me an example of a pickit line item that will pick up both eth and non eth items?

**Comment by crush-you** [comment]
If you don't specify then it will pick both.

[name] == shako && [quality] == unique # [defense] == 138

that will pick up perfect defense shakos, normal or eth. Using

[flag] == ethereal or 
[flag] != ethereal 

will let you choose one or the other.
