### ISSUE TITLE
GameAction is not defined

### ISSUE THREAD

**Issue by hellsshadow** [kolton/d2bot-with-kolbot#939]
https://pastebin.com/XJ4TXWLH

ever since this new update i have been getting a few problems, i get this error:
[error (1)] File(kolbot\default.dbj:114) ReferenceError" GameAction is not defined
I am also getting another error with LocalChat

**Comment by bigsmxke** [comment]
Did you manage to get a fix? 

I'm also getting the same error, but on line 106. I set it to true as the brackets were empty, but still no difference. Yes I used N++. 

Hope someone gives some insight soon.
