### ISSUE TITLE
Delay MFLeader Config 

### ISSUE THREAD

**Issue by luvvi** [kolton/d2bot-with-kolbot#941]
I run Cows at the end of my run so I use MFLeader/Helper to get my follower to assist. The problem is, my leader keeps posting commands from the beginning of the run. Is there any way to shut him up until the Cows script?

**Comment by 5noop** [comment]
You can set MFLeader to false until you do cows:
```
Config.MFLeader = false;
Scripts.Cows = { MFLeader: true };
```

**Comment by luvvi** [comment]
Thanks works flawlessly
