### ISSUE TITLE
Bot in TCP/IP Games

### ISSUE THREAD

**Issue by semajtrip** [kolton/d2bot-with-kolbot#951]
Is there anyway to bot in TCP/IP games? I would like to setup a leader and a follower using TCP/IP.

**Comment by jaenster** [comment]
It is one of the options in the profile config. It works fine

**Comment by semajtrip** [comment]
When editing a profile in D2Bot I only have two mode options. Single Player or Battle.net

**Comment by cryptic7s** [comment]
works awesome i run it 24/7 with multiple.

**Comment by semajtrip** [comment]
Thank you for your help! I was able to get it working with 1.14. My problem was not having the latest changes in Master and trying to use 1.13D.
