### ISSUE TITLE
How do you reset game counter

### ISSUE THREAD

**Issue by Tomothyt** [kolton/d2bot-with-kolbot#961]
Probably obvious but i cant seem to find the way to reset the game counter back to 0.

**Comment by mrandros** [comment]
I assume it's here d2bot-with-kolbot-master\d2bs\kolbot\data

Open the file matching the character you want, and first line showing up,  {"runs":123,

Try change that to what you desire

**Comment by Tomothyt** [comment]
That was it, thanks you
