### ISSUE TITLE
Chaos paladin teleport

### ISSUE THREAD

**Issue by bulun22** [kolton/d2bot-with-kolbot#966]
Hi, my pali bot working , make all run like andy, mefi, baal correctly but when he goes on chaos run i doesnt teleport on the mob when he is on sanctuary! help plz

**Comment by bulun22** [comment]
PS: the hdin use vigor and not teleport and walking

**Comment by 5noop** [comment]
Did you set `Config.Diablo.WalkClear` to false ?

**Comment by bulun22** [comment]
damn bro thx a lot, error of newbies sorry lol
