### ISSUE TITLE
Public Bo Barb

### ISSUE THREAD

**Issue by chojo31** [kolton/d2bot-with-kolbot#975]
Hi,
I want my Bo Barb to join my Chant games and bo everyone that come to Cata 2 WP.

How can I achieve this? The Bo Barb need "names" at the getter line, but I want him to stay cata 2 and bo whenever someone take that wp.

It is possible?
Thank you for your help

**Comment by 5noop** [comment]
Lucky you, someone already made that script https://pastebin.com/JTmWbqLf
More info here https://github.com/mf022/d2bs/wiki/Misc_options
