### ISSUE TITLE
Fast pickit

### ISSUE THREAD

**Issue by janez12** [kolton/d2bot-with-kolbot#977]
Hello 
My problem is that my bot prioratises killing before pickit. So if i'm making a public game he wants to finish killing a group of monsters instead of picking items mid combat. FastPickit is enabled in config file. Is there a way to make him pickup items as soon as they drop so the other players in the game don't get them before me?

**Comment by DarkHorseDre** [comment]
fastpickit comment says "Check and pick items between attacks"

do you have `Config.BossPriority = true`?

**Comment by janez12** [comment]
tried with boss priority false and true.

**Comment by DarkHorseDre** [comment]
ah red herring I guess as fastpickit should pick between attacks. 

which class and attacks?  if it has tele it should tele in and pick items fast.  if its not got tele it may find it hard to path to items so may clear first..

**Comment by janez12** [comment]
sorceress. first time trying to attach something i hope it works.

[Sorceress.txt](https://github.com/kolton/d2bot-with-kolbot/files/2746866/Sorceress.txt)

**Comment by janez12** [comment]
Well i got kind of a solution. I found out there is a priority on runes and uniques. I tried that and it works on runes. But he still won't go for 3 socked 15ed AP. I'm ok for now but if someone can figure out how to make all pickit priority instead of just uniques and runes I would really appreciate it.

**Comment by DarkHorseDre** [comment]
I didnt realise there was a priority - just saw it in pickit.js as I guess you did - its the  section

Prioritise 74 (runes) and uniques (qual 7)
	// Prioritize runes and unique items for fast pick
		if (unitA.itemType === 74 || unitA.quality === 7) {
			return -1;
		}

as listed in the same file:
	if (type) {
			switch (unit.itemType) {
			case 4: // gold
				return "ÿc4";
			case 74: // runes
				return "ÿc8";
			case 76: // healing potions
				return "ÿc1";
			case 77: // mana potions
				return "ÿc3";
			case 78: // juvs
				return "ÿc;";
			}
		}

		switch (unit.quality) {
		case 4: // magic
			return "ÿc3";
		case 5: // set
			return "ÿc2";
		case 6: // rare
			return "ÿc9";
		case 7: // unique
			return "ÿc4";
		case 8: // crafted
			return "ÿc8";
		}

a normal armour with ED needs to be superior so quality === 3

	itemQualityToName: function (quality) {
		var qualNames = ["", "lowquality", "normal", "superior", "magic", "set", "rare", "unique", "crafted"];

so I am guessing we add another OR to the existing logic for quality 7
		if (unitA.itemType === 74 || unitA.quality === 7 || unitA.quality === 3) {
			return -1;
		}

The only thing I'd prefer is to narrow down the item type to armours, but I cant find a list of itemtypes and I've ran out of time..
