### ISSUE TITLE
chest script change sequence

### ISSUE THREAD

**Issue by crackedsash** [kolton/d2bot-with-kolbot#982]
Looking for a solution to change the sequence in the chest script. an example of what i want to do is:

1. Run chest script for a1 (13, 14)
2. Run maesoleum
3. run chest script for a2 (15,16)
4. run duriel or whatever next script 

I thought the lines under would do the trick but it just completes all chests in chestmania in one sequence... instead of doing 2 chests in a1 then going to maesoleum then 2 chest in a2 and duriel. i guess i need some end after the first chestmania config? 

1. Scripts.ChestMania = true; // Open chests in configured areas
                Config.ChestMania.Act1 = [13, 14]; 
2. Scripts.Mausoleum = true;
                Config.Mausoleum.KillBloodRaven = false;
                Config.Mausoleum.ClearCrypt = true;
3. Scripts.ChestMania = false; // Open chests in configured areas
                Config.ChestMania.Act2 = [55, 59];
4.   Scripts.Duriel = true;

**Comment by DarkHorseDre** [comment]
I found the bot works this way when I tried to get it to run bosses then clearanyarea in the same location (e.g. kill andy then clear cata 4): bot would run all bot scripts then do clearanyarea/chestmania etc.  I've not looked at the code but seems to be written to do all of one type of script together and in certain sequence.. I hope someone can provide a better idea than what I would: rejigging the bot to process the way you want it to :\

**Comment by 5noop** [comment]
The bot is running the scripts in the order of the first appearance in the config file. Everything after the first appearance won't be considered so you can't just split the script like you tried to. Now what you could do is create another script called ChestMania2.js with the same content as ChestMania.js, define it in Config.js with the adequate parameters (like Config.ChestMania2.Act1 etc) and then run it after Mausoleum.

**Comment by DarkHorseDre** [comment]
@5noop - painful!

@crackedsash - I take it you didnt run the config as written `Scripts.ChestMania = false`?  that line if executed would disable chestmania. I'd take that out to avoid confusion (although 5noop says it would be ignored anyway, but you never know the impact..)
- nice name btw! I found myself wearing a few of those this ladder in hc level 1 :)

**Comment by crackedsash** [comment]
hi guys, thanks a bunch for your input. I  am away so not able to actually run @5noop suggestion. Have you tried to see if it works? @5noop or @DarkHorseDre ? I feel it could be a solution you would also need to cut some of the parts in the chestmania.js or else it would still run the full sequence.

An example to simplify, lets say you want to split a1 and a2. you have to change chestmania.js to only run a1 sequence and then chestmania2 to run a2 sequence. then it would work right? 

@DarkHorseDre i will check when i am home but think its set to false yeah.. and happy you liked my name:D this belt is so useful early on:D

**Comment by 5noop** [comment]
> hi guys, thanks a bunch for your input. I am away so not able to actually run @5noop suggestion. Have you tried to see if it works? @5noop or @DarkHorseDre ? I feel it could be a solution you would also need to cut some of the parts in the chestmania.js or else it would still run the full sequence.

You don't need to cut ChestMania.js but as I said in my last post you have to set some different config parameters in Config.js and in your char file because that's what defines the chests the bot will run.

So your character file would look like this:
```
    Scripts.ChestMania = true; // Open chests in configured areas
    Config.ChestMania.Act1 = [13, 14];
    Scripts.Mausoleum = true;
    Config.Mausoleum.KillBloodRaven = false;
    Config.Mausoleum.ClearCrypt = true;
    Scripts.ChestMania2 = false; // Open chests in configured areas
    Config.ChestMania2.Act2 = [55, 59];
    Scripts.Duriel = true;
```

and in Config.js you would have:
```
ChestMania2: {
	Act1: [],
	Act2: [],
	Act3: [],
	Act4: [],
	Act5: []
}
```

**Comment by 5noop** [comment]
> Everything after the first appearance won't be considered so you can't just split the script like you tried to. 

Little correction here btw: if you set multiple times the same script to true then it won't have any effect, the script will only run once. However if just once you set a script to false and everywhere else the same script is set to true then it won't be run at all.

**Comment by crackedsash** [comment]
Ok, tested it. Works Great! Thanks for your effort guys, appreciate it;) i guess il close the issue😊😊
