### ISSUE TITLE
Mule Setup

### ISSUE THREAD

**Issue by germanchop** [kolton/d2bot-with-kolbot#987]
Hi!
i have this problem:
Profile not enables for muling.
Setup here:
"Mule1": {
muleProfile: "Mula67", // The name of mule profile in d2bot#. It will be started and stopped when needed.
accountPrefix: "germula", // Account prefix. Numbers added automatically when making accounts.
accountPassword: "********", // Account password.
charPrefix: "lolo", // Character prefix. Suffix added automatically when making characters.
realm: "useast", // Available options: "useast", "uswest", "europe", "asia"
expansion: true,
ladder: true,
hardcore: false,

		// Game name and password of the mule game. Never use the same game name as for mule logger.
		muleGameName: ["jo1","123"], // ["gamename", "password"]

		// List of profiles that will mule items. Example: enabledProfiles: ["profile 1", "profile 2"],
		enabledProfiles: ["Pala(6)"],

		// Stop a profile prior to muling. Useful when running 8 bots without proxies.
		stopProfile: "",
		stopProfileKeyRelease: true, // true = stopProfile key will get released on stop. useful when using 100% of your keys for botting.

		// Trigger muling at the end of a game if used space in stash and inventory is equal to or more than given percent.
		usedStashTrigger: 80,
		usedInventoryTrigger: 80,

		// Mule items that have been stashed at some point but are no longer in pickit.
		muleOrphans: true
	}

**Comment by iamacow** [comment]
What profile are you using when you try to start muling/when AutoMule triggers?

**Comment by germanchop** [comment]
Pala(6)

**Comment by germanchop** [comment]
i dont have any clue, anyone have one working? can paste setting?
thx
