### ISSUE TITLE
1.13d PlugY?

### ISSUE THREAD

**Issue by eemut** [kolton/d2bot-with-kolbot#989]
I am trying to get my Kolbot to work with PlugY 1.13d, and cannot get it to work. 

Most common errors are :

Attempt to access invalid address
Windows has unexpectedly excited... starting profile

**Comment by 5noop** [comment]
There are 2 branch 1.13d, did you try them ? Master won't work in 1.14, plugy or not.

**Comment by eemut** [comment]
Sorry, I’m not too well versed in this, and don’t really know what you mean about two branches.

**Comment by 5noop** [comment]
A github repository can contain multiple branches with different version of the project, if you use TurtoiseSVN to download the bot then you can chose which branch to dl from. You can see the different branches on the main page of the repo https://github.com/kolton/d2bot-with-kolbot/

Read the documentation for more information https://github.com/blizzhackers/documentation/blob/master/d2bot/Download.md

**Comment by jonashan** [comment]
I did not get it to work with plugy, I get the wrong address error too... Let me know if you get it to work 💃

**Comment by eemut** [comment]
@5noop Thanks! Will try when I get home.

**Comment by eemut** [comment]
I feel like were making progress but still no go. Downloaded and pulled out both the 1.13d branches and both of them now return the error: "Process with an Id of -1 is not running."

Any clue on what this means?

**Comment by eemut** [comment]
Anyone?

**Comment by Gawson01** [comment]
eemut, got discord?

**Comment by AuraofMana** [comment]
@Gawson01 How do you build against Plugy? I got the 1.13d (core15) but when I try to point it at Plugy.exe it won't show up.
