### ISSUE TITLE
D2BotMuleLog notepad formatting

### ISSUE THREAD

**Issue by olsoner1** [kolton/d2bot-with-kolbot#998]
I just started using the MuleLog to hopefully simplify everything. Everything is running good but the format that it spits out is just to much info. What do I need to set to make it more plain and simple. Something that can copy and pasted easy.

Example of what is currently put in notepad

{"itemColor":-1,"image":"gpw","title":"Perfect Diamond","description":"\\xffc0Perfect Diamond (1)\\n\\xffc0Can be Inserted into Socketed Items\\n\\xffc0\\n\\xffc0Weapons: +68% Damage to Undead\\n\\xffc0Armor: +100 to Attack Rating\\n\\xffc0Helms: +100 to Attack Rating\\n\\xffc0Shields: All Resistances +19\\n\\xffc0\\n\\xffc1Required Level: 18$4256861439:586:3:9:0","header":

**Comment by germanchop** [comment]
U try the notepad++? is good to see that files in the tab of the bot.
do u have a working Mule? i want setup one and i cant

**Comment by 5noop** [comment]
You can try Diabase https://github.com/mf022/d2bs/wiki/Misc_options

**Comment by olsoner1** [comment]
Diabase link does not work. Will this format my mule files for me? So I can actually copy and paste to trade things off. I am so dam lazy I been just giving everything away instead of trying to make a big list manually.
